### ISSUE TITLE
archive_file generates TypeError: unable to resolve type 'gid_t' on Windows 2012R2

### ISSUE THREAD

**Issue by gotimer** [chef/chef#10061]
## Description
Using the `archive_file` resource in Chef Infra Client 16.2.44 on Windows 2012R2 throws an error 

```
TypeError: unable to resolve type 'gid_t'
```

The same code worked on Chef Infra Client 16.1.16 before upgrading to 16.2.44 (and after downgrading back to 16.1.16).

## Chef Version
Chef Infra Client 16.2.44

## Platform Version
Windows 2012R2

## Replication Case

Any use of the `archive_file` resource seems to generate this error. I wrote a simple cookbook to recreate it on a fresh VM. The archive file and target directory already exist. There are no permissions issues. 

[Sample unzip_archive cookbook](https://github.com/gotimer/unzip_archive)

```
source = 'C:/Users/ggotimer/Documents/archive.zip'
target_dir = 'C:/Users/ggotimer/Documents/exploded'

archive_file source do
  destination target_dir
  action :extract
end
```

## Client Output

```
PS C:\Users\ggotimer> chef-client -o "recipe[unzip_archive::default]"
Starting Chef Infra Client, version 16.2.44
[2020-06-24T21:36:25+00:00] WARN: Run List override has been provided.
[2020-06-24T21:36:25+00:00] WARN: Original Run List: []
[2020-06-24T21:36:25+00:00] WARN: Overridden Run List: [recipe[unzip_archive::default]]
resolving cookbooks for run list: ["unzip_archive::default"]
Synchronizing Cookbooks:
  - unzip_archive (0.1.1)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 2 resources
Recipe: unzip_archive::default
  * directory[C:/Users/ggotimer/Documents/exploded] action create (up to date)
  * archive_file[C:/Users/ggotimer/Documents/archive.zip] action extract

    ================================================================================
    Error executing action `extract` on resource 'archive_file[C:/Users/ggotimer/Documents/archive.zip]'
    ================================================================================

    TypeError
    ---------
    unable to resolve type 'gid_t'

    Resource Declaration:
    ---------------------
    # In C:/chef/cache/cookbooks/unzip_archive/recipes/default.rb

     11: archive_file node['unzip_archive']['source'] do
     12:   destination node['unzip_archive']['target_dir']
     13:   action :extract
     14: end

    Compiled Resource:
    ------------------
    # Declared in C:/chef/cache/cookbooks/unzip_archive/recipes/default.rb:11:in `from_file'

    archive_file("C:/Users/ggotimer/Documents/archive.zip") do
      action [:extract]
      default_guard_interpreter :default
      declared_type :archive_file
      cookbook_name "unzip_archive"
      recipe_name "default"
      destination "C:/Users/ggotimer/Documents/exploded"
      options [:time]
    end

    System Info:
    ------------
    chef_version=16.2.44
    platform=windows
    platform_version=6.3.9600
    ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x64-mingw32]
    program_name=C:/opscode/chef/bin/chef-client
    executable=C:/opscode/chef/bin/chef-client


Running handlers:
[2020-06-24T21:36:26+00:00] ERROR: Running exception handlers
Running handlers complete
[2020-06-24T21:36:26+00:00] ERROR: Exception handlers complete
Chef Infra Client failed. 0 resources updated in 05 seconds
[2020-06-24T21:36:26+00:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
[2020-06-24T21:36:26+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-06-24T21:36:26+00:00] FATAL: TypeError: archive_file[C:/Users/ggotimer/Documents/archive.zip] (unzip_archive::defa
ult line 11) had an error: TypeError: unable to resolve type 'gid_t'
```

## Stacktrace

[chef-stacktrace.out](https://gist.github.com/gotimer/f892911b7c201e8247bc0602f22feaae)

**Comment by gotimer** [comment]
On Chef Infra Client 16.1.16:

```
PS C:\Users\ggotimer> chef-client -o "recipe[unzip_archive::default]"
Starting Chef Infra Client, version 16.1.16
[2020-06-24T21:56:54+00:00] WARN: Run List override has been provided.
[2020-06-24T21:56:54+00:00] WARN: Original Run List: []
[2020-06-24T21:56:54+00:00] WARN: Overridden Run List: [recipe[unzip_archive::default]]
resolving cookbooks for run list: ["unzip_archive::default"]
Synchronizing Cookbooks:
  - unzip_archive (0.2.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: unzip_archive::default
  * archive_file[C:/Users/ggotimer/Documents/archive.zip] action extract (up to date)
[2020-06-24T21:56:55+00:00] WARN: Skipping final node save because override_runlist was given

Running handlers:
Running handlers complete
Chef Infra Client finished, 0/1 resources updated in 07 seconds
```

**Comment by gotimer** [comment]
It fails on Chef Infra Client 16.2.50 as well:

```
PS C:\Users\ggotimer> chef-client -o "recipe[unzip_archive::default]"
Starting Chef Infra Client, version 16.2.50
[2020-06-24T22:00:28+00:00] WARN: Run List override has been provided.
[2020-06-24T22:00:28+00:00] WARN: Original Run List: []
[2020-06-24T22:00:28+00:00] WARN: Overridden Run List: [recipe[unzip_archive::default]]
resolving cookbooks for run list: ["unzip_archive::default"]
Synchronizing Cookbooks:
  - unzip_archive (0.2.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: unzip_archive::default
  * archive_file[C:/Users/ggotimer/Documents/archive.zip] action extract

    ================================================================================
    Error executing action `extract` on resource 'archive_file[C:/Users/ggotimer/Documents/archive.zip]'
    ================================================================================

    TypeError
    ---------
    unable to resolve type 'gid_t'

    Resource Declaration:
    ---------------------
    # In C:/chef/cache/cookbooks/unzip_archive/recipes/default.rb

     10: archive_file source do
     11:   destination target_dir
     12:   action :extract
     13: end

    Compiled Resource:
    ------------------
    # Declared in C:/chef/cache/cookbooks/unzip_archive/recipes/default.rb:10:in `from_file'

    archive_file("C:/Users/ggotimer/Documents/archive.zip") do
      action [:extract]
      default_guard_interpreter :default
      declared_type :archive_file
      cookbook_name "unzip_archive"
      recipe_name "default"
      destination "C:/Users/ggotimer/Documents/exploded"
      options [:time]
    end

    System Info:
    ------------
    chef_version=16.2.50
    platform=windows
    platform_version=6.3.9600
    ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x64-mingw32]
    program_name=C:/opscode/chef/bin/chef-client
    executable=C:/opscode/chef/bin/chef-client


Running handlers:
[2020-06-24T22:00:30+00:00] ERROR: Running exception handlers
Running handlers complete
[2020-06-24T22:00:30+00:00] ERROR: Exception handlers complete
Chef Infra Client failed. 0 resources updated in 07 seconds
[2020-06-24T22:00:30+00:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
[2020-06-24T22:00:30+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-06-24T22:00:30+00:00] FATAL: TypeError: archive_file[C:/Users/ggotimer/Documents/archive.zip] (unzip_archive::defa
ult line 10) had an error: TypeError: unable to resolve type 'gid_t'
```
