### ISSUE TITLE
macos_userdefaults blows up when passing an array with dictionary values

### ISSUE THREAD

**Issue by erikng** [chef/chef#10083]
## Description
Because of https://github.com/chef/chef/issues/10075 we are experimenting with moving some of our profiles to the `macos_userdefaults` resource when potentially applicable.

Unfortunately, it looks like there is a bug when attempting to deploy an array that has dictionary values.

My guess is because of the `value.map` is done only on dictionaries, and not when a dictionary is passed within an array.

https://github.com/chef/chef/blob/master/lib/chef/resource/macos_userdefaults.rb#L107

## Chef Version
16.2.50 and all versions since 14

## Platform Version
macOS 10.15.5

## Replication Case
in a recipe do
```
test_value = [{'test' => 'test'}]
macos_userdefaults 'Bad test' do
  domain '/Library/Preferences/chef.badtest'
  key 'test'
  value test_value
end
```

## Client Output
```
    * execute[defaults write '/Library/Preferences/chef.badtest' 'test' -array '{"test"=>"test"}'] action run
      
      ================================================================================
      Error executing action `run` on resource 'execute[defaults write '/Library/Preferences/chef.badtest' 'test' -array '{"test"=>"test"}']'
      ================================================================================
      
      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '1'
      ---- Begin output of defaults write '/Library/Preferences/chef.badtest' 'test' -array '{"test"=>"test"}' ----
      STDOUT: 
      STDERR: 2020-06-30 11:43:57.161 defaults[47898:3400292] Could not parse: {"test"=>"test"}.  Try single-quoting it.
      ---- End output of defaults write '/Library/Preferences/chef.badtest' 'test' -array '{"test"=>"test"}' ----
      Ran defaults write '/Library/Preferences/chef.badtest' 'test' -array '{"test"=>"test"}' returned 1
      
      Resource Declaration:
      ---------------------
      # In /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/resource/macos_userdefaults.rb
      
      117:           execute cmd.join(" ") do
      118:             user new_resource.user unless new_resource.user.nil?
      119:           end
      120:         end
      
      Compiled Resource:
      ------------------
      # Declared in /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/resource/macos_userdefaults.rb:117:in `block in <class:MacosUserDefaults>'
      
      execute("defaults write '/Library/Preferences/chef.badtest' 'test' -array '{"test"=>"test"}'") do
        action [:run]
        default_guard_interpreter :execute
        command "defaults write '/Library/Preferences/chef.badtest' 'test' -array '{\"test\"=>\"test\"}'"
        backup 5
        declared_type :execute
        cookbook_name "global_base"
        domain nil
        user nil
      end
      
      System Info:
      ------------
      chef_version=16.2.50
      platform=mac_os_x
      platform_version=10.15.5
      ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin17]
      program_name=/usr/local/bin/chef-client
      executable=/opt/chef/bin/chef-client
      
    
    ================================================================================
    Error executing action `write` on resource 'macos_userdefaults[Bad test]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    execute[defaults write '/Library/Preferences/chef.badtest' 'test' -array '{"test"=>"test"}'] (/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/resource/macos_userdefaults.rb line 117) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of defaults write '/Library/Preferences/chef.badtest' 'test' -array '{"test"=>"test"}' ----
    STDOUT: 
    STDERR: 2020-06-30 11:43:57.161 defaults[47898:3400292] Could not parse: {"test"=>"test"}.  Try single-quoting it.
    ---- End output of defaults write '/Library/Preferences/chef.badtest' 'test' -array '{"test"=>"test"}' ----
    Ran defaults write '/Library/Preferences/chef.badtest' 'test' -array '{"test"=>"test"}' returned 1
```

## Stacktrace
```
Generated at 2020-06-30 11:43:57 -0500
Mixlib::ShellOut::ShellCommandFailed: macos_userdefaults[Bad test] (global_base::helloit line 14) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[defaults write '/Library/Preferences/chef.badtest' 'test' -array '{"test"=>"test"}'] (/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/resource/macos_userdefaults.rb line 117) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of defaults write '/Library/Preferences/chef.badtest' 'test' -array '{"test"=>"test"}' ----
STDOUT: 
STDERR: 2020-06-30 11:43:57.161 defaults[47898:3400292] Could not parse: {"test"=>"test"}.  Try single-quoting it.
---- End output of defaults write '/Library/Preferences/chef.badtest' 'test' -array '{"test"=>"test"}' ----
Ran defaults write '/Library/Preferences/chef.badtest' 'test' -array '{"test"=>"test"}' returned 1
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.0.9/lib/mixlib/shellout.rb:300:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.0.9/lib/mixlib/shellout.rb:287:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/mixin/shell_out.rb:127:in `shell_out_compacted!'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/mixin/shell_out.rb:60:in `shell_out!'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/provider/execute.rb:52:in `block (2 levels) in <class:Execute>'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/mixin/why_run.rb:51:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/provider.rb:268:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/provider/execute.rb:50:in `block in <class:Execute>'
(eval):2:in `block in action_run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/provider.rb:279:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/provider.rb:279:in `compile_and_converge_action'
(eval):2:in `action_run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/provider.rb:220:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/resource.rb:603:in `block in run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/resource.rb:630:in `with_umask'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/resource.rb:602:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/runner.rb:74:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/runner.rb:108:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/resource_collection.rb:64:in `insert'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/dsl/declare_resource.rb:275:in `declare_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/dsl/resources.rb:36:in `execute'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/resource/macos_userdefaults.rb:117:in `block in <class:MacosUserDefaults>'
(eval):2:in `block in action_write'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/provider.rb:279:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/provider.rb:279:in `compile_and_converge_action'
(eval):2:in `action_write'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/provider.rb:220:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/resource.rb:603:in `block in run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/resource.rb:630:in `with_umask'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/resource.rb:602:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/runner.rb:74:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/runner.rb:108:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/runner.rb:132:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/resource_collection/stepable_iterator.rb:115:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/resource_collection/stepable_iterator.rb:86:in `step'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/runner.rb:130:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/client.rb:714:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/client.rb:709:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/client.rb:709:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/client.rb:733:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/client.rb:288:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/application.rb:292:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/application.rb:268:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/application.rb:251:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/application/base.rb:335:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.50/lib/chef/application.rb:68:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.2.50/bin/chef-client:25:in `<top (required)>'
/usr/local/bin/chef-client:162:in `load'
/usr/local/bin/chef-client:162:in `<main>'%                                   
```

**Comment by btm** [comment]
Chef 16.3 shipped with a rewritten macos_userdefaults resource as a short term improvement, but we believe we need to write a library to the preferences API for full coverage. That's represented in https://github.com/chef/chef/issues/10083.
