### ISSUE TITLE
Code within powershell_script resource not escaping special characters

### ISSUE THREAD

**Issue by douglax** [chef/chef#10215]
## Description
I'm trying to issue the following command within a powershell_script resource but it is failing to complete

```$proc = Invoke-WmiMethod -Class win32_process -Name create -ArgumentList "#{drive}\\Downloads\\#{module}\\SetupServer.exe /s:#{database_server} /d:#{database_name} /u:#{database_user} /p:\'#{database_password}\' "```

The variable database_password sometimes contains special characters like ()[]{} and -when it does- it returns error as if the character was part of an unfinished sentece, even if it is escaped with \' 
 
The error message returned
``` [10.228.X.X]     STDERR: At C:\Users\someuser\AppData\Local\
Temp\chef_powershell_script-user-code20200727-5036-l63s5j.ps1:1 char:1
 [10.228.X.X]
 [10.228.X.X]     + {
 [10.228.X.X]
 [10.228.X.X]     + ~
 [10.228.X.X]
 [10.228.X.X]     Missing closing '}' in statement block or type definition.
 [10.228.X.X]
 [10.228.X.X]         + CategoryInfo          : ParserError: (:) [], ParseException
 [10.228.X.X]
 [10.228.X.X]         + FullyQualifiedErrorId : MissingEndCurlyBrace```
## Chef Version
<!--- Tell us which version of chef-client you are using (see below for Server+ChefDK bugs). -->
Chef Workstation version: 0.17.5
## Platform Version
<!--- Tell us which operating system distribution and version chef-client is running on. -->
Chef Infra Client version: 15.8.23
## Replication Case
<!--- Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case. -->
Bootstrap a node that contains a recipe with a powershell_script resource and the password has one of the special characters mentioned above

Full resource code:
```    powershell_script 'install-module' do
        code <<-EOH  
        [System.Reflection.Assembly]::LoadWithPartialName('Microsoft.VisualBasic') | Out-Null
        $Continue=1
        
        if ($Continue -eq 1) {     
            $proc = Invoke-WmiMethod -Class win32_process -Name create -ArgumentList "#{drive}\\Downloads\\#{module}\\SetupServer.exe /s:#{database_server} /d:#{database_name} /u:#{database_user} /p:\'#{database_password}\' "}
            Wait-Process -Id $proc.ProcessId 
            if ($proc.ReturnValue -ne 0 -and $Continue -eq 1) {
        if ($Continue -eq 1) {     
                [microsoft.visualbasic.interaction]::MsgBox("ERROR, en #{module} , Codigo: "+($proc.ReturnValue))  | Out-Null
                $Continue=0
            }
        }   
        Remove-Variable proc
        EOH
    end```

## Client Output
```<!--- The relevant output of the chef-client run or a link to a gist of the entire run, if there is one.
[10.228.X.X]     STDERR: At C:\Users\someuser\AppData\Local\
Temp\chef_powershell_script-user-code20200727-5036-l63s5j.ps1:1 char:1
 [10.228.X.X]
 [10.228.X.X]     + {
 [10.228.X.X]
 [10.228.X.X]     + ~
 [10.228.X.X]
 [10.228.X.X]     Missing closing '}' in statement block or type definition.
 [10.228.X.X]
 [10.228.X.X]         + CategoryInfo          : ParserError: (:) [], ParseException
 [10.228.X.X]
 [10.228.X.X]         + FullyQualifiedErrorId : MissingEndCurlyBrace
```

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it. -->

[chef-client-debug.txt](https://github.com/chef/chef/files/4985120/chef-client-debug.txt)

## Stacktrace

Attached
[chef-stacktrace.out.log](https://github.com/chef/chef/files/4985074/chef-stacktrace.out.log)

**Comment by phiggins** [comment]
Hi,

I think you have a syntax error in your code. I created a simple resource like this:

```
database_password = "{}{}{}}}}}}{{{{{}"

powershell_script "test some powershell" do
  code <<~CODE
    echo "#{database_password}"
  CODE
end
```

and when I run it with chef-apply I see the output I would expect:

```
[2020-07-28T00:35:26+00:00] DEBUG: Reading products and relationships...
[2020-07-28T00:35:26+00:00] DEBUG: Successfully read products and relationships
[2020-07-28T00:35:26+00:00] DEBUG: Searching for the following licenses: ["infra-client", "inspec"]
[2020-07-28T00:35:26+00:00] DEBUG: Found license chef_infra_client at C:/Users/vagrant/.chef/accepted_licenses/chef_infra_client
[2020-07-28T00:35:26+00:00] DEBUG: Found license inspec at C:/Users/vagrant/.chef/accepted_licenses/inspec
[2020-07-28T00:35:26+00:00] DEBUG: Missing licenses remaining: []
[2020-07-28T00:35:26+00:00] DEBUG: All licenses present
[2020-07-28T00:35:27+00:00] DEBUG: Running Ohai with the following configuration: {:logger=>#<Mixlib::Log::Child:0x00000000080acb40 @parent=Chef::Log, @metadata={:system=>"ohai", :version=>"16.3.1"}>}
[2020-07-28T00:35:27+00:00] DEBUG: Running Ohai with the following configuration: {:logger=>#<Mixlib::Log::Child:0x00000000080acb40 @parent=Chef::Log, @metadata={:system=>"ohai", :version=>"16.3.1"}>}
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/win32-process-0.8.3/lib/win32/process.rb:744:in `kill': warning: $SAFE will become a normal global variable in Ruby 3.0 (StructuredWarnings::BuiltInWarning)
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/win32-process-0.8.3/lib/win32/process.rb:744:in `kill': warning: $SAFE will become a normal global variable in Ruby 3.0 (StructuredWarnings::BuiltInWarning)
[2020-07-28T00:36:01+00:00] DEBUG: Extracting run list from JSON attributes provided on command line
[2020-07-28T00:36:01+00:00] DEBUG: Applying attributes from json file
[2020-07-28T00:36:01+00:00] DEBUG: Platform is windows version 10.0.17763
[2020-07-28T00:36:01+00:00] INFO: Run List is []
[2020-07-28T00:36:01+00:00] INFO: Run List expands to []
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * powershell_script[test some powershell] action run[2020-07-28T00:36:01+00:00] INFO: Processing powershell_script[test some powershell] action run ((chef-apply cookbook)::(chef-apply recipe) line 3)

  echo "{}{}{}}}}}}{{{{{}"



    [execute] {}{}{}}}}}}{{{{{}
[2020-07-28T00:36:01+00:00] INFO: powershell_script[test some powershell] ran successfully
    - execute "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/vagrant/AppData/Local/Temp/1/chef-script20200728-5836-1se4vfn.ps1"
[2020-07-28T00:36:01+00:00] DEBUG: Exiting
```

In the example you've provided, there are 3 `if` statements with opening curly brackets `{`, but there are only two closing curly brackets `}`, so the error message you're getting of `Missing closing '}' in statement block or type definition.` seems like what I would expect.

If this is generally a problem with powershell code in Chef resources, it's not likely that this is fixable in Chef. In this example, how would Chef be able to tell that the special characters like `{` are part of a string of data and not the syntax of your powershell code? If this continues to be a problem, it's likely you'll have to do any escaping yourself. Alternatively, it is generally regarded as a bad practice to pass sensitive data like passwords in plain text on the command line, so it might be worth investigating whether the application you're running has an alternative for providing the password, like reading from STDIN or using a configuration file.

**Comment by douglax** [comment]
thank you @phiggins for the rapid response.

For debugging purposes, we write a file resource in the remote host containing the command that will be executed in the powershell_script. After we get this error we copy the command from the file -with all variables exploded- and execute it in a powershell terminal and it runs without errors. This is what got me thinking that maybe Chef/Ruby were misinterpreting  the original command at some point as it seems that it is copied to and invoked from a temporal ps1 file, can that be a possibility?

Thank you again for the support

**Comment by phiggins** [comment]
> This is what got me thinking that maybe Chef/Ruby were misinterpreting the original command at some point as it seems that it is copied to and invoked from a temporal ps1 file, can that be a possibility?

Code in a `powershell_script` resource is copied to a temporary file and executed, but it would not have caused the error in the example you provided.
