### ISSUE TITLE
Chef 16.3.38 on macOS has a NoMethodError

### ISSUE THREAD

**Issue by erikng** [chef/chef#10211]
## Description
I can't get chef to run

## Chef Version
Chef 16.3.38

## Platform Version
macOS 10.16.0 Beta 3

## Replication Case
Install chef, run chef

## Client Output
```
Starting Chef Infra Client, version 16.3.38
[2020-07-27T13:54:47-05:00] INFO: *** Chef Infra Client 16.3.38 ***
[2020-07-27T13:54:47-05:00] INFO: Platform: x86_64-darwin17
[2020-07-27T13:54:47-05:00] INFO: Chef-client pid: 34423

================================================================================
Chef encountered an error attempting to load the node data for "snipped"
================================================================================

Unexpected Error:
-----------------
NoMethodError: undefined method `possible_requests' for nil:NilClass

System Info:
------------
chef_version=16.3.38
ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin17]
program_name=/usr/local/bin/chef-client
executable=/opt/chef/bin/chef-client


Running handlers:
[2020-07-27T13:54:50-05:00] ERROR: Running exception handlers
[2020-07-27T13:54:50-05:00] INFO: Could not get failed cookbook from backtrace
[2020-07-27T13:54:50-05:00] INFO: Could not get failed rescipe from backtrace
[2020-07-27T13:54:50-05:00] INFO: Could not get failed line from backtrace
[2020-07-27T13:54:50-05:00] ERROR: Report handler Chef::Handler::Runstats raised #<NoMethodError: undefined method `[]' for nil:NilClass>
[2020-07-27T13:54:50-05:00] ERROR: /etc/chef/handlers/chef_runstats.rb:99:in `report'
[2020-07-27T13:54:50-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/handler.rb:256:in `run_report_unsafe'
[2020-07-27T13:54:50-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/handler.rb:244:in `run_report_safely'
[2020-07-27T13:54:50-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/handler.rb:149:in `block in run_exception_handlers'
[2020-07-27T13:54:50-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/handler.rb:147:in `each'
[2020-07-27T13:54:50-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/handler.rb:147:in `run_exception_handlers'
[2020-07-27T13:54:50-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/handler.rb:158:in `block in <class:Handler>'
[2020-07-27T13:54:50-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/client.rb:440:in `block in run_failed'
[2020-07-27T13:54:50-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/client.rb:439:in `each'
[2020-07-27T13:54:50-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/client.rb:439:in `run_failed'
[2020-07-27T13:54:50-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/client.rb:309:in `rescue in run'
[2020-07-27T13:54:50-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/client.rb:302:in `run'
[2020-07-27T13:54:50-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/application.rb:304:in `run_with_graceful_exit_option'
[2020-07-27T13:54:50-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/application.rb:280:in `block in run_chef_client'
[2020-07-27T13:54:50-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/local_mode.rb:42:in `with_server_connectivity'
[2020-07-27T13:54:50-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/application.rb:263:in `run_chef_client'
[2020-07-27T13:54:50-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/application/base.rb:335:in `run_application'
[2020-07-27T13:54:50-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/application.rb:68:in `run'
[2020-07-27T13:54:50-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.3.38/bin/chef-client:25:in `<top (required)>'
[2020-07-27T13:54:50-05:00] ERROR: /usr/local/bin/chef-client:162:in `load'
[2020-07-27T13:54:50-05:00] ERROR: /usr/local/bin/chef-client:162:in `<main>'
  - Chef::Handler::Runstats
Running handlers complete
[2020-07-27T13:54:50-05:00] ERROR: Exception handlers complete
Chef Infra Client failed. 0 resources updated in 02 seconds
[2020-07-27T13:54:51-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2020-07-27T13:54:51-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-07-27T13:54:51-05:00] FATAL: NoMethodError: undefined method `possible_requests' for nil:NilClass

```

## Stacktrace
```
Generated at 2020-07-27 13:54:51 -0500
NoMethodError: undefined method `possible_requests' for nil:NilClass
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/http.rb:474:in `version_retries'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/http.rb:158:in `rescue in request'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/http.rb:144:in `request'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/http.rb:115:in `get'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/node.rb:631:in `load'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/node.rb:614:in `find_or_create'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/policy_builder/dynamic.rb:72:in `load_node'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/client.rb:455:in `load_node'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/client.rb:271:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/application.rb:304:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/application.rb:280:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/application.rb:263:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/application/base.rb:335:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/application.rb:68:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.3.38/bin/chef-client:25:in `<top (required)>'
/usr/local/bin/chef-client:162:in `load'
/usr/local/bin/chef-client:162:in `<main>'

>>>> Caused by Net::HTTPServerException: 406 "Not Acceptable"
/opt/chef/embedded/lib/ruby/2.7.0/net/http/response.rb:124:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/http.rb:152:in `request'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/http.rb:115:in `get'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/node.rb:631:in `load'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/node.rb:614:in `find_or_create'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/policy_builder/dynamic.rb:72:in `load_node'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/client.rb:455:in `load_node'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/client.rb:271:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/application.rb:304:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/application.rb:280:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/application.rb:263:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/application/base.rb:335:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.38/lib/chef/application.rb:68:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.3.38/bin/chef-client:25:in `<top (required)>'
/usr/local/bin/chef-client:162:in `load'
/usr/local/bin/chef-client:162:in `<main>'
```

**Comment by erikng** [comment]
Tested on `16.3.43`:

```
Starting Chef Infra Client, version 16.3.43
[2020-07-28T09:43:43-05:00] INFO: *** Chef Infra Client 16.3.43 ***
[2020-07-28T09:43:43-05:00] INFO: Platform: x86_64-darwin17
[2020-07-28T09:43:43-05:00] INFO: Chef-client pid: 42576
================================================================================
Chef encountered an error attempting to load the node data for "snipped"
================================================================================
Incompatible server API version:
--------------------------------
This version of the API that this request specified is not supported by the server you sent this request to.
The server supports a min API version of 0 and a max API version of 1.
Chef Infra Client just made a request with an API version of 2.
Please either update your Chef Infra Client or the server to be a compatible set.
System Info:
------------
chef_version=16.3.43
ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin17]
program_name=/usr/local/bin/chef-client
executable=/opt/chef/bin/chef-client
Running handlers:
[2020-07-28T09:43:46-05:00] ERROR: Running exception handlers
[2020-07-28T09:43:46-05:00] INFO: Could not get failed cookbook from backtrace
[2020-07-28T09:43:46-05:00] INFO: Could not get failed rescipe from backtrace
[2020-07-28T09:43:46-05:00] INFO: Could not get failed line from backtrace
[2020-07-28T09:43:46-05:00] ERROR: Report handler Chef::Handler::Runstats raised #<NoMethodError: undefined method `[]' for nil:NilClass>
[2020-07-28T09:43:46-05:00] ERROR: /etc/chef/handlers/chef_runstats.rb:99:in `report'
[2020-07-28T09:43:46-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/handler.rb:258:in `run_report_unsafe'
[2020-07-28T09:43:46-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/handler.rb:246:in `run_report_safely'
[2020-07-28T09:43:46-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/handler.rb:149:in `block in run_exception_handlers'
[2020-07-28T09:43:46-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/handler.rb:147:in `each'
[2020-07-28T09:43:46-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/handler.rb:147:in `run_exception_handlers'
[2020-07-28T09:43:46-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/handler.rb:158:in `block in <class:Handler>'
[2020-07-28T09:43:46-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/client.rb:440:in `block in run_failed'
[2020-07-28T09:43:46-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/client.rb:439:in `each'
[2020-07-28T09:43:46-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/client.rb:439:in `run_failed'
[2020-07-28T09:43:46-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/client.rb:309:in `rescue in run'
[2020-07-28T09:43:46-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/client.rb:302:in `run'
[2020-07-28T09:43:46-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/application.rb:304:in `run_with_graceful_exit_option'
[2020-07-28T09:43:46-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/application.rb:280:in `block in run_chef_client'
[2020-07-28T09:43:46-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/local_mode.rb:42:in `with_server_connectivity'
[2020-07-28T09:43:46-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/application.rb:263:in `run_chef_client'
[2020-07-28T09:43:46-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/application/base.rb:335:in `run_application'
[2020-07-28T09:43:46-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/application.rb:68:in `run'
[2020-07-28T09:43:46-05:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.3.43/bin/chef-client:25:in `<top (required)>'
[2020-07-28T09:43:46-05:00] ERROR: /usr/local/bin/chef-client:162:in `load'
[2020-07-28T09:43:46-05:00] ERROR: /usr/local/bin/chef-client:162:in `<main>'
  - Chef::Handler::Runstats
Running handlers complete
[2020-07-28T09:43:46-05:00] ERROR: Exception handlers complete
Chef Infra Client failed. 0 resources updated in 02 seconds
[2020-07-28T09:43:46-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2020-07-28T09:43:46-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-07-28T09:43:46-05:00] FATAL: Net::HTTPServerException: 406 "Not Acceptable"
```

stack
```
Generated at 2020-07-28 09:43:46 -0500
Net::HTTPServerException: 406 "Not Acceptable"
/opt/chef/embedded/lib/ruby/2.7.0/net/http/response.rb:124:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/http.rb:151:in `request'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/http.rb:114:in `get'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/node.rb:631:in `load'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/node.rb:614:in `find_or_create'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/policy_builder/dynamic.rb:72:in `load_node'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/client.rb:455:in `load_node'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/client.rb:271:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/application.rb:304:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/application.rb:280:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/application.rb:263:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/application/base.rb:335:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.43/lib/chef/application.rb:68:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.3.43/bin/chef-client:25:in `<top (required)>'
/usr/local/bin/chef-client:162:in `load'
/usr/local/bin/chef-client:162:in `<main>'
```

**Comment by tas50** [comment]
Thank @lamont-granquist and @phiggins for digging in there
