### ISSUE TITLE
Error when starting chef-client. FATAL: OpenSSL::X509::CertificateError: not enough data

### ISSUE THREAD

**Issue by nicksadowy** [chef/chef#10306]
## Description
Attempting to bootstrap a Ubuntu VM (18.04). As it attempts to start chef-client it reports an Unexpected Error:
OpenSSL::X509::CertificateError: not enough data

## Chef Version
16.3.45

## Platform Version
Ubuntu server 18.04

## Replication Case
knife vsphere vm clone usweb2 --template UbuntuSvrTmpl --cips 10.1.0.37/24 --cgw 10.1.0.1 --cdnsips 10.1.0.32,10.1.0.31 --dest-folder /Servers --datastore LINUX1 --cdomain mydomain.com
knife vsphere vm net up usweb2
knife vsphere vm state usweb2 -s on
knife bootstrap 10.1.0.37 -U MyUser --sudo --use-sudo-password -P MyPassword -y -N usweb2

## Client Output
Connecting to 10.1.0.37 using ssh
Creating new client for usweb2
Creating new node for usweb2
Bootstrapping 10.1.0.37
 [10.1.0.37] [sudo] password for MyUser: 
 [10.1.0.37] -----> Existing Chef Infra Client installation detected
 [10.1.0.37] Starting the first Chef Infra Client Client run...
 [10.1.0.37] Starting Chef Infra Client, version 16.3.45
 [10.1.0.37] 
================================================================================
Chef encountered an error attempting to load the node data for "usweb2"
 [10.1.0.37] ================================================================================

 [10.1.0.37] Unexpected Error:
-----------------
OpenSSL::X509::CertificateError: not enough data

 [10.1.0.37] System Info:
------------
chef_version=16.3.45
ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
program_name=/usr/bin/chef-client
executable=/opt/chef/bin/chef-client
 [10.1.0.37] 

 [10.1.0.37] 
Running handlers:
 [10.1.0.37] [2020-08-15T05:20:00+00:00] ERROR: Running exception handlers
 [10.1.0.37] Running handlers complete
 [10.1.0.37] [2020-08-15T05:20:00+00:00] ERROR: Exception handlers complete
 [10.1.0.37] Chef Infra Client failed. 0 resources updated in 05 seconds
 [10.1.0.37] [2020-08-15T05:20:00+00:00] WARN: Error while reporting run start to Data Collector. URL: https://chefserver01.cd-data.com/organizations/pq/data-collector Exception: No HTTP Code -- not enough data 
 [10.1.0.37] [2020-08-15T05:20:00+00:00] WARN: Error while reporting run start to Data Collector. URL: https://chefserver01.cd-data.com/organizations/pq/data-collector Exception: No HTTP Code -- not enough data 
 [10.1.0.37] [2020-08-15T05:20:00+00:00] FATAL: Stacktrace dumped to /Users/nick/.chef/cache/chef-stacktrace.out
 [10.1.0.37] [2020-08-15T05:20:00+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
 [10.1.0.37] [2020-08-15T05:20:00+00:00] FATAL: OpenSSL::X509::CertificateError: not enough data
ERROR: The following error occurred on 10.1.0.37:

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it. -->

```
[2020-08-15T05:22:30+00:00] DEBUG: Reading products and relationships...
[2020-08-15T05:22:30+00:00] DEBUG: Successfully read products and relationships
[2020-08-15T05:22:30+00:00] DEBUG: Searching for the following licenses: ["infra-client", "inspec"]
[2020-08-15T05:22:30+00:00] DEBUG: Found license chef_infra_client at /etc/chef/accepted_licenses/chef_infra_client
[2020-08-15T05:22:30+00:00] DEBUG: Found license inspec at /etc/chef/accepted_licenses/inspec
[2020-08-15T05:22:30+00:00] DEBUG: Missing licenses remaining: []
[2020-08-15T05:22:30+00:00] DEBUG: All licenses present
[2020-08-15T05:22:30+00:00] DEBUG: Running Ohai with the following configuration: {:logger=>Chef::Log}
Starting Chef Infra Client, version 16.3.45
[2020-08-15T05:22:30+00:00] INFO: *** Chef Infra Client 16.3.45 ***
[2020-08-15T05:22:30+00:00] INFO: Platform: x86_64-linux
[2020-08-15T05:22:30+00:00] INFO: Chef-client pid: 2427
[2020-08-15T05:22:30+00:00] DEBUG: Chef-client request_id: 4ec05bbb-a502-4bfd-b4fb-1a81f86bec53
[2020-08-15T05:22:30+00:00] DEBUG: Running Ohai with the following configuration: {:logger=>Chef::Log}
[2020-08-15T05:22:30+00:00] DEBUG: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
[2020-08-15T05:22:35+00:00] DEBUG: Plugin Zpools: Could not shell_out "zpool list -H -o name,size,alloc,free,cap,dedup,health,version". Skipping plugin.

================================================================================
Chef encountered an error attempting to load the node data for "usweb2"
================================================================================

Unexpected Error:
-----------------
OpenSSL::X509::CertificateError: not enough data

System Info:
------------
chef_version=16.3.45
ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
program_name=/usr/bin/chef-client
executable=/opt/chef/bin/chef-client


Running handlers:
[2020-08-15T05:22:36+00:00] ERROR: Running exception handlers
Running handlers complete
[2020-08-15T05:22:36+00:00] ERROR: Exception handlers complete
Chef Infra Client failed. 0 resources updated in 05 seconds
[2020-08-15T05:22:36+00:00] WARN: Error while reporting run start to Data Collector. URL: https://chefserver01.cd-data.com/organizations/pq/data-collector Exception: No HTTP Code -- not enough data 
[2020-08-15T05:22:36+00:00] WARN: Error while reporting run start to Data Collector. URL: https://chefserver01.cd-data.com/organizations/pq/data-collector Exception: No HTTP Code -- not enough data 
[2020-08-15T05:22:36+00:00] FATAL: Stacktrace dumped to /Users/nick/.chef/cache/chef-stacktrace.out
[2020-08-15T05:22:36+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-08-15T05:22:36+00:00] DEBUG: OpenSSL::X509::CertificateError: not enough data
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http/ssl_policies.rb:84:in `initialize'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http/ssl_policies.rb:84:in `new'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http/ssl_policies.rb:84:in `block in set_custom_certs'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http/ssl_policies.rb:83:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http/ssl_policies.rb:83:in `set_custom_certs'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http/ssl_policies.rb:48:in `apply'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http/ssl_policies.rb:35:in `apply_to'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http/basic_client.rb:152:in `configure_ssl'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http/basic_client.rb:116:in `build_http_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http/basic_client.rb:50:in `http_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http/basic_client.rb:69:in `request'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http.rb:389:in `block in send_http_request'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http.rb:428:in `block in retrying_http_errors'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http.rb:426:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http.rb:426:in `retrying_http_errors'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http.rb:382:in `send_http_request'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http.rb:148:in `request'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http.rb:114:in `get'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/node.rb:631:in `load'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/node.rb:614:in `find_or_create'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/policy_builder/dynamic.rb:72:in `load_node'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/client.rb:455:in `load_node'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/client.rb:271:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/application.rb:304:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/application.rb:280:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/application.rb:263:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/application/base.rb:335:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/application.rb:68:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.3.45/bin/chef-client:25:in `<top (required)>'
/usr/bin/chef-client:162:in `load'
/usr/bin/chef-client:162:in `<main>'
[2020-08-15T05:22:36+00:00] FATAL: OpenSSL::X509::CertificateError: not enough data

```

## Stacktrace
Generated at 2020-08-15 05:22:36 +0000
OpenSSL::X509::CertificateError: not enough data
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http/ssl_policies.rb:84:in `initialize'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http/ssl_policies.rb:84:in `new'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http/ssl_policies.rb:84:in `block in set_custom_certs'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http/ssl_policies.rb:83:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http/ssl_policies.rb:83:in `set_custom_certs'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http/ssl_policies.rb:48:in `apply'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http/ssl_policies.rb:35:in `apply_to'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http/basic_client.rb:152:in `configure_ssl'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http/basic_client.rb:116:in `build_http_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http/basic_client.rb:50:in `http_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http/basic_client.rb:69:in `request'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http.rb:389:in `block in send_http_request'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http.rb:428:in `block in retrying_http_errors'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http.rb:426:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http.rb:426:in `retrying_http_errors'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http.rb:382:in `send_http_request'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http.rb:148:in `request'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/http.rb:114:in `get'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/node.rb:631:in `load'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/node.rb:614:in `find_or_create'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/policy_builder/dynamic.rb:72:in `load_node'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/client.rb:455:in `load_node'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/client.rb:271:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/application.rb:304:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/application.rb:280:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/application.rb:263:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/application/base.rb:335:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/application.rb:68:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.3.45/bin/chef-client:25:in `<top (required)>'
/usr/bin/chef-client:162:in `load'
/usr/bin/chef-client:162:in `<main>'

**Comment by phiggins** [comment]
Hi, I merged #10751 to attempt to fix this, and at the very least provide more information in the case of failure. If this is still an issue, please reopen this with more details about your certificates. Thanks.
