### ISSUE TITLE
Chef Client v16.4.35 `osx_profile` Resource Incorrectly Evaluates macOS Platform Version

### ISSUE THREAD

**Issue by ChefAustin** [chef/chef#10318]
## Description
On Chef client v16.4.35 the `osx_profile` resource for macOS improperly evaluates whether or not a device is running Big Sur (macOS 11.0/16.0) and will fail when a node is running 10.15.6.

## Chef Version
v16.4.35

## Platform Version
macOS 10.15.6 (19G2021)

## Replication Case
Run `chef-client` on a macOS 10.15.6 (19G2021) device with a `run_list` that includes a call to the `osx_profile` resource.

## Client Output

```
  * cpe_profiles[Managing all of Configuration Profiles] action run[2020-08-18T14:05:24+02:00] INFO: Processing cpe_profiles[Managing all of Configuration Profiles] action run (cpe_profiles::default line 17)

  Recipe: <Dynamically Defined Resource>
    * osx_profile[com.redacted.chef.sal] action install[2020-08-18T14:05:24+02:00] INFO: Processing osx_profile[com.redacted.chef.sal] action install (dynamically defined)


      ================================================================================
      Error executing action `install` on resource 'osx_profile[com.redacted.chef.sal]'
      ================================================================================

      RuntimeError
      ------------
      The osx_profile resource is not available on macOS Bug Sur or above due to the removal of apple support for CLI installation of profiles

      Cookbook Trace: (most recent call first)
      ----------------------------------------
      /var/chef/cache/cookbooks/cpe_profiles/resources/cpe_profiles.rb:54:in `osx_profiles_resource'
      /var/chef/cache/cookbooks/cpe_profiles/resources/cpe_profiles.rb:25:in `block (2 levels) in class_from_file'
      /var/chef/cache/cookbooks/cpe_profiles/resources/cpe_profiles.rb:21:in `each'
      /var/chef/cache/cookbooks/cpe_profiles/resources/cpe_profiles.rb:21:in `block in class_from_file'

      Compiled Resource:
      ------------------
      # Declared in

      osx_profile("com.redacted.chef.sal") do
        action [:install]
        default_guard_interpreter :default
        profile {"PayloadIdentifier"=>"com.redacted.chef.sal", "PayloadRemovalDisallowed"=>true, "PayloadScope"=>"System", "PayloadType"=>"Configuration", "PayloadUUID"=>"1c03dd17-d2d7-4a68-be40-f41bea3642a9", "PayloadOrganization"=>"Redacted", "PayloadVersion"=>1, "PayloadDisplayName"=>"Sal", "PayloadContent"=>[{"PayloadType"=>"com.github.salopensource.sal", "PayloadVersion"=>1, "PayloadIdentifier"=>"com.redacted.chef.sal", "PayloadUUID"=>"e33adee2-4a19-4e69-a330-461920ec8279", "PayloadEnabled"=>true, "PayloadDisplayName"=>"Sal", "key"=>"1jxnm3xvtjzrps9upfro6ucfy3x3jsb99s86ylxialq8mhk9m01fsyuhm8oxsgma381gkgc309grqrogj6nvji9fz3dx761s7u4ml2eu4e1j3jle4sidd19hkc4wghjj", "ServerURL"=>"https://sal.redacted.com"}]}
      end

      System Info:
      ------------
      chef_version=16.4.35
      platform=mac_os_x
      platform_version=10.15.6
      ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin17]
      program_name=/usr/local/bin/chef-client
      executable=/opt/chef/bin/chef-client


    ================================================================================
    Error executing action `run` on resource 'cpe_profiles[Managing all of Configuration Profiles]'
    ================================================================================

    RuntimeError
    ------------
    osx_profile[com.redacted.chef.sal] (dynamically defined) had an error: RuntimeError: The osx_profile resource is not available on macOS Bug Sur or above due to the removal of apple support for CLI installation of profiles

    Cookbook Trace: (most recent call first)
    ----------------------------------------
    /var/chef/cache/cookbooks/cpe_profiles/resources/cpe_profiles.rb:54:in `osx_profiles_resource'
    /var/chef/cache/cookbooks/cpe_profiles/resources/cpe_profiles.rb:25:in `block (2 levels) in class_from_file'
    /var/chef/cache/cookbooks/cpe_profiles/resources/cpe_profiles.rb:21:in `each'
    /var/chef/cache/cookbooks/cpe_profiles/resources/cpe_profiles.rb:21:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/cpe_profiles/recipes/default.rb

     17: cpe_profiles 'Managing all of Configuration Profiles'
     18:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/cpe_profiles/recipes/default.rb:17:in `from_file'

    cpe_profiles("Managing all of Configuration Profiles") do
      action [:run]
      default_guard_interpreter :default
      declared_type :cpe_profiles
      cookbook_name "cpe_profiles"
      recipe_name "default"
    end

    System Info:
    ------------
    chef_version=16.4.35
    platform=mac_os_x
    platform_version=10.15.6
    ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin17]
    program_name=/usr/local/bin/chef-client
    executable=/opt/chef/bin/chef-client

[2020-08-18T14:05:24+02:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2020-08-18T14:05:24+02:00] ERROR: Running exception handlers
[2020-08-18T14:05:24+02:00] INFO: Could not get failed cookbook from backtrace
[2020-08-18T14:05:24+02:00] INFO: Could not get failed rescipe from backtrace
[2020-08-18T14:05:24+02:00] INFO: Could not get failed line from backtrace
  - Chef::Handler::Runstats
Running handlers complete
[2020-08-18T14:05:24+02:00] ERROR: Exception handlers complete
Chef Infra Client failed. 0 resources updated in 23 seconds
[2020-08-18T14:05:24+02:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2020-08-18T14:05:24+02:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-08-18T14:05:24+02:00] FATAL: RuntimeError: cpe_profiles[Managing all of Configuration Profiles] (cpe_profiles::default line 17) had an error: RuntimeError: osx_profile[com.redacted.chef.sal] (dynamically defined) had an error: RuntimeError: The osx_profile resource is not available on macOS Bug Sur or above due to the removal of apple support for CLI installation of profiles
```

This seems to stem from `lib/chef/resource/osx_profile.rb:L83` introduced in this PR: https://github.com/chef/chef/pull/10239

**Comment by lamont-granquist** [comment]
fixed by #10319
