### ISSUE TITLE
Resource "windows_user_privilege" Does Not Work as Documented

### ISSUE THREAD

**Issue by jeremyciak** [chef/chef#10420]
## Description

Using the `windows_user_privilege` resource as documented results in a validation error.

## Chef Version

16.3.45

## Platform Version

Windows Server 2019

## Replication Case

```ruby
windows_user_privilege 'Administrators' do
  privilege %w(SeAssignPrimaryTokenPrivilege SeIncreaseQuotaPrivilege)
end
```

## Client Output

```
================================================================================
Error executing action `add` on resource 'windows_user_privilege[Administrators]'
================================================================================

Chef::Exceptions::ValidationFailed
----------------------------------
Option privilege's value ["SeSecurityPrivilege", "SeBackupPrivilege", "SeRestorePrivilege", "SeSystemtimePrivilege", "SeShutdownPrivilege", "SeRemoteShutdownPrivilege", "SeTakeOwnershipPrivilege", "SeDebugPrivilege", "SeSystemEnvironmentPrivilege", "SeSystemProfilePrivilege", "SeProfileSingleProcessPrivilege", "SeIncreaseBasePriorityPrivilege", "SeLoadDriverPrivilege", "SeCreatePagefilePrivilege", "SeIncreaseQuotaPrivilege", "SeUndockPrivilege", "SeManageVolumePrivilege", "SeImpersonatePrivilege", "SeCreateGlobalPrivilege", "SeTimeZonePrivilege", "SeCreateSymbolicLinkPrivilege", "SeChangeNotifyPrivilege", "SeDelegateSessionUserImpersonatePrivilege", "SeInteractiveLogonRight", "SeNetworkLogonRight", "SeBatchLogonRight", "SeRemoteInteractiveLogonRight"] Option privilege must include any of the: ["SeTrustedCredManAccessPrivilege", "SeNetworkLogonRight", "SeTcbPrivilege", "SeMachineAccountPrivilege", "SeIncreaseQuotaPrivilege", "SeInteractiveLogonRight", "SeRemoteInteractiveLogonRight", "SeBackupPrivilege", "SeChangeNotifyPrivilege", "SeSystemtimePrivilege", "SeTimeZonePrivilege", "SeCreatePagefilePrivilege", "SeCreateTokenPrivilege", "SeCreateGlobalPrivilege", "SeCreatePermanentPrivilege", "SeCreateSymbolicLinkPrivilege", "SeDebugPrivilege", "SeDenyNetworkLogonRight", "SeDenyBatchLogonRight", "SeDenyServiceLogonRight", "SeDenyInteractiveLogonRight", "SeDenyRemoteInteractiveLogonRight", "SeEnableDelegationPrivilege", "SeRemoteShutdownPrivilege", "SeAuditPrivilege", "SeImpersonatePrivilege", "SeIncreaseWorkingSetPrivilege", "SeIncreaseBasePriorityPrivilege", "SeLoadDriverPrivilege", "SeLockMemoryPrivilege", "SeBatchLogonRight", "SeServiceLogonRight", "SeSecurityPrivilege", "SeRelabelPrivilege", "SeSystemEnvironmentPrivilege", "SeManageVolumePrivilege", "SeProfileSingleProcessPrivilege", "SeSystemProfilePrivilege", "SeUndockPrivilege", "SeAssignPrimaryTokenPrivilege", "SeRestorePrivilege", "SeShutdownPrivilege", "SeSyncAgentPrivilege", "SeTakeOwnershipPrivilege"]!

Resource Declaration:
---------------------
# In C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/enable_elevated_shell/recipes/enable_elevated_shell.rb

  1: windows_user_privilege 'Administrators' do
  2:   privilege %w(SeAssignPrimaryTokenPrivilege SeIncreaseQuotaPrivilege)
  3: end
  4: 

Compiled Resource:
------------------
# Declared in C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/env_common/recipes/enable_elevated_shell.rb:1:in `from_file'

windows_user_privilege("Administrators") do
  action [:add]
  default_guard_interpreter :default
  declared_type :windows_user_privilege
  cookbook_name "env_common"
  recipe_name "enable_elevated_shell"
  privilege ["SeAssignPrimaryTokenPrivilege", "SeIncreaseQuotaPrivilege"]
  principal "Administrators"
end

System Info:
------------
chef_version=16.3.45
platform=windows
platform_version=10.0.17763
ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x64-mingw32]
program_name=C:/opscode/chef/bin/chef-client
executable=C:/opscode/chef/bin/chef-client
```

**Comment by Vasu1105** [comment]
@jeremyciak user has to be mentioned in block like follows

```
windows_user_privilege 'Remote interactive logon' do
  privilege      'SeDenyRemoteInteractiveLogonRight'
  users          ['Builtin\Guests', 'NT AUTHORITY\Local Account']
  action         :add
end
```
Could you please try that let us know ?

**Comment by jeremyciak** [comment]
@Vasu1105 have you actually tried that syntax and has it worked for you? I believe I have tried that previously without success. I will run another test in a bit. Maybe it's a Windows Server 2019 thing? I wouldn't think so though...

**Comment by Vasu1105** [comment]
@jeremyciak that syntax should work as far as I know and that's what the doc also says https://docs.chef.io/resources/windows_user_privilege/#syntax. I agree but that the Validation failed should not come on the previlege part though. But that would be different case.

**Comment by jeremyciak** [comment]
@Vasu1105 When I try this exact block you provided, or even a few different combinations of users with the `SeDenyRemoteInteractiveLogonRight` privilege it works:

```ruby
windows_user_privilege 'Remote interactive logon' do
  privilege      'SeDenyRemoteInteractiveLogonRight'
  users          ['Builtin\Guests', 'NT AUTHORITY\Local Account']
  action         :add
end
```

What I am finding in further testing is that the resource does not seem to support the usage of either the `SeAssignPrimaryTokenPrivilege` or `SeIncreaseQuotaPrivilege` privileges. I ran the following scenarios:

```ruby
windows_user_privilege 'Assign primary token privilege' do
  privilege 'SeAssignPrimaryTokenPrivilege'
  users     ['BUILTIN\Administrators']
  action    :add
end
```
```ruby
windows_user_privilege 'Assign primary token privilege' do
  privilege 'SeAssignPrimaryTokenPrivilege'
  users     ['BUILTIN\Guests']
  action    :add
end
```
```ruby
windows_user_privilege 'Increase quota privilege' do
  privilege 'SeIncreaseQuotaPrivilege'
  users     ['BUILTIN\Administrators']
  action    :add
end
```
```ruby
windows_user_privilege 'Increase quota privilege' do
  privilege 'SeIncreaseQuotaPrivilege'
  users     ['BUILTIN\Guests']
  action    :add
end
```

I always got something like this:

```
================================================================================
Error executing action `add` on resource 'windows_user_privilege[Assign primary token privilege]'
================================================================================
       
Chef::Exceptions::Win32APIError
-------------------------------
No mapping between account names and security IDs was done.
---- Begin Win32 API output ----
System Error Code: 1332
System Error Message: No mapping between account names and security IDs was done.
---- End Win32 API output ----
       
Resource Declaration:
---------------------
# In C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/env_common/recipes/enable_elevated_shell.rb
       
12: windows_user_privilege 'Assign primary token privilege' do
13:   privilege 'SeAssignPrimaryTokenPrivilege'
14:   users     ['BUILTIN\Administrators']
15:   action    :add
16: end
       
Compiled Resource:
------------------
# Declared in C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/env_common/recipes/enable_elevated_shell.rb:12:in `from_file'
       
windows_user_privilege("Assign primary token privilege") do
    action [:add]
    default_guard_interpreter :default
    declared_type :windows_user_privilege
    cookbook_name "env_common"
    recipe_name "enable_elevated_shell"
    privilege ["SeAssignPrimaryTokenPrivilege"]
    users ["BUILTIN\\Administrators"]
    principal "Assign primary token privilege"
end
       
System Info:
------------
chef_version=16.3.45
platform=windows
platform_version=10.0.14393
ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x64-mingw32]
program_name=C:/opscode/chef/bin/chef-client
executable=C:/opscode/chef/bin/chef-client
```

**Comment by MattoHopkins** [comment]
Still running into this issue with this code block

`windows_user_privilege 'Deny log on as a batch job' do
  privilege      'SeDenyBatchLogonRight'
  users           ['BUILTIN\Guests']
  action         :add
end`

Error as follows:

`================================================================================
    Error executing action `add` on resource 'windows_user_privilege[Deny log on as a batch job]'
    ================================================================================

    Chef::Exceptions::Win32APIError
    -------------------------------
    No mapping between account names and security IDs was done.
    ---- Begin Win32 API output ----
    System Error Code: 1332
    System Error Message: No mapping between account names and security IDs was done.
    ---- End Win32 API output ----`

Have I missed something? Trying to add the SID for 'Guests' to that security policy with no luck...

**Comment by MattoHopkins** [comment]
@tas50, Is there an update on this?

**Comment by asif-shaikh-1** [comment]
I have a requirement of using well known SIDs instead of usernames. Is this a supported scenario?

https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/security-identifiers-in-windows

**Comment by epang-dev** [comment]
I am facing below error using this resource with chef 17.1.35

windows_user_privilege 'set logon as a service right' do
  privilege %w(SeServiceLogonRight)
  users ["#{service_account}"]
  sensitive true
  action :nothing
end

           Chef::Exceptions::ValidationFailed
           ----------------------------------
           privilege is a required property


Anyone know how to resolve? You can clearly see that I have set the privilege property.

**Comment by JohnnyBopper** [comment]
I ran into this same issue and found out that the correct **principal** needs to be passed in. This is not documented other than saying that the default value for the principal is the resource blocks name. 

After doing some research, I found that the **principal** is the **Access Control Special Identity**. 

You can find them here [Special Identities](https://docs.microsoft.com/en-us/windows/security/identity-protection/access-control/special-identities).

I believe that clarification in the documentation on this subject is needed.

**Comment by jaymzh** [comment]
Fixed by attached PR, closing.
