### ISSUE TITLE
Requiring gems such as "addressable/uri" in cookbooks no longer work since 16.5

### ISSUE THREAD

**Issue by ramereth** [chef/chef#10452]
## Description

Using gems such as `addressable/uri` inside of cookbooks no longer work since 16.5 and cause the following error, even when they are required:
```
uninitialized constant Addressable::URI
```

This seems to be related to the recent change using ``autoload`` for gems.

## Chef Version
16.5.64

## Platform Version
Any platform

## Replication Case

Have the following in a recipe and/or a helper library:
```ruby
require 'addressable/uri'
```

A possible workaround seems to be the following:
```ruby
autoload :Addressable, 'addressable/uri'
```

## Client Output

```
Starting Chef Infra Client, version 16.5.64
Patents: https://www.chef.io/patents
Creating a new client identity for default-centos-7 using the validator key.
resolving cookbooks for run list: ["test::default"]
Synchronizing Cookbooks:
  - test (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /tmp/kitchen/cache/cookbooks/test/recipes/default.rb
================================================================================

NameError
---------
uninitialized constant Addressable::URI

Cookbook Trace: (most recent call first)
----------------------------------------
  /tmp/kitchen/cache/cookbooks/test/recipes/default.rb:18:in `from_file'

Relevant File Content:
----------------------
/tmp/kitchen/cache/cookbooks/test/recipes/default.rb:

 11:  #     http://www.apache.org/licenses/LICENSE-2.0
 12:  #
 13:  # Unless required by applicable law or agreed to in writing, software
 14:  # distributed under the License is distributed on an "AS IS" BASIS,
 15:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 16:  # See the License for the specific language governing permissions and
 17:  # limitations under the License.
 18>> require 'addressable/uri'
 19:  

System Info:
------------
chef_version=16.5.64
platform=centos
platform_version=7.8.2003
ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
program_name=/opt/chef/bin/chef-solo
executable=/opt/chef/bin/chef-solo


Running handlers:
[2020-09-21T16:52:39+00:00] ERROR: Running exception handlers
Running handlers complete
[2020-09-21T16:52:39+00:00] ERROR: Exception handlers complete
Chef Infra Client failed. 0 resources updated in 02 seconds
[2020-09-21T16:52:39+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
[2020-09-21T16:52:39+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-09-21T16:52:39+00:00] FATAL: NameError: uninitialized constant Addressable::URI
```

## Stacktrace
```
Generated at 2020-09-21 16:52:39 +0000
NameError: uninitialized constant Addressable::URI
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/addressable-2.7.0/lib/addressable/template.rb:31:in `<class:Template>'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/addressable-2.7.0/lib/addressable/template.rb:28:in `<module:Addressable>'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/addressable-2.7.0/lib/addressable/template.rb:24:in `<top (required)>'
/opt/chef/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/chef/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/addressable-2.7.0/lib/addressable.rb:4:in `<top (required)>'
/opt/chef/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/chef/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/addressable-2.7.0/lib/addressable/version.rb:23:in `<top (required)>'
/opt/chef/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/chef/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/addressable-2.7.0/lib/addressable/uri.rb:21:in `<top (required)>'
/opt/chef/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/chef/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/tmp/kitchen/cache/cookbooks/test/recipes/default.rb:18:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.64/lib/chef/mixin/from_file.rb:34:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.64/lib/chef/mixin/from_file.rb:34:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.64/lib/chef/cookbook_version.rb:230:in `load_ruby_recipe'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.64/lib/chef/cookbook_version.rb:200:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.64/lib/chef/run_context.rb:393:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.64/lib/chef/run_context/cookbook_compiler.rb:174:in `block in compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.64/lib/chef/run_context/cookbook_compiler.rb:171:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.64/lib/chef/run_context/cookbook_compiler.rb:171:in `compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.64/lib/chef/run_context/cookbook_compiler.rb:79:in `compile'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.64/lib/chef/run_context.rb:223:in `load'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.64/lib/chef/policy_builder/expand_node_object.rb:103:in `setup_run_context'
/opt/chef/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.64/lib/chef/client.rb:497:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.64/lib/chef/client.rb:283:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.64/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.64/lib/chef/application.rb:281:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.64/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.64/lib/chef/application.rb:264:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.64/lib/chef/application/base.rb:337:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.64/lib/chef/application.rb:67:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.64/lib/chef/application/solo.rb:60:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.5.64/bin/chef-solo:24:in `<top (required)>'
/opt/chef/bin/chef-solo:156:in `load'
/opt/chef/bin/chef-solo:156:in `<main>'
```

**Comment by lamont-granquist** [comment]
So autoload is triggering on the `module Addressable` definition in addressable/version.rb which is causing addressable.rb to be loaded which first attempts to require `addressable/uri` which is the middle of being processed so that is skipped and it goes on to `addressable/template` which needs `addressable/uri` parsed first, but that hasn't completed yet.  That explains what is happening, but I have no idea offhand how to fix it.

**Comment by lamont-granquist** [comment]
We could probably fix it in chef/chef since likely all we care about is Addressable::URI and we should probably only be autoloading that.

**Comment by ramereth** [comment]
Does this affect any other gems that you know of which are using autoload?

**Comment by ramereth** [comment]
Confirmed these fix the issue. Thanks!
