### ISSUE TITLE
windows_user_privilege resource fails for SeTimeZonePrivilege

### ISSUE THREAD

**Issue by trickyearlobe** [chef/chef#10552]
## Description
`windows_user_privilege` resource fails when trying to set the users who can exercise the `SeTimeZonePrivilege` right.

The problem occurs regardless of whether the resource is in desired state or not.

## Chef Version
Various `16.x` including `16.6.14` 

## Platform Version
Windows 10, Windows 2008r2, Windows 2016, Windows 2019

## Replication Case
Make a cookbook with the following recipe and run it on a Windows box in test kitchen (or on a node as administrator)

```
### This one works fine ###
windows_user_privilege 'Network Logon Rights' do
  privilege      'SeNetworkLogonRight'
  users          ['BUILTIN\Administrators']
  action         :set
end

### This one doesn't work fine ###
windows_user_privilege "Time Zone Privilege" do
  privilege     'SeTimeZonePrivilege'
  users         ['BUILTIN\Administrators']
  action        :set
end
```

## Client Output

```
         * windows_user_privilege[Network Logon Rights] action set
           - removing user 'BUILTIN\Backup Operators' from privilege SeNetworkLogonRight
           - removing user 'BUILTIN\Users' from privilege SeNetworkLogonRight
           - removing user 'Everyone' from privilege SeNetworkLogonRight
         * windows_user_privilege[Time Zone Privilege] action set
           - removing user 'BUILTIN\Users' from privilege SeTimeZonePrivilege
           ================================================================================
           Error executing action `set` on resource 'windows_user_privilege[Time Zone Privilege]'
           ================================================================================
           
           Chef::Exceptions::Win32APIError
           -------------------------------
           The request is not supported.
           ---- Begin Win32 API output ----
           System Error Code: 50
           System Error Message: The request is not supported.
           ---- End Win32 API output ----
           
           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/setimezoneprivilege/recipes/default.rb
           
            15: windows_user_privilege "Time Zone Privilege" do
            16:   privilege     'SeTimeZonePrivilege'
            17:   users         ['BUILTIN\Administrators']
            18:   action        :set
            19: end
           
           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/setimezoneprivilege/recipes/default.rb:15:in `from_file'
           
           windows_user_privilege("Time Zone Privilege") do
             action [:set]
             default_guard_interpreter :default
             declared_type :windows_user_privilege
             cookbook_name "setimezoneprivilege"
             recipe_name "default"
             privilege ["SeTimeZonePrivilege"]
             users ["BUILTIN\\Administrators"]
             principal "Time Zone Privilege"
           end
           
           System Info:
           ------------
           chef_version=16.6.14
           platform=windows
           platform_version=10.0.19041
           ruby=ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32]
           program_name=C:/opscode/chef/bin/chef-client
           executable=C:/opscode/chef/bin/chef-client
   
```

## Stacktrace
```
       Generated at 2020-10-26 20:28:52 +0000
       Chef::Exceptions::Win32APIError: windows_user_privilege[Time Zone Privilege] (setimezoneprivilege::default line 15) had an error: Chef::Exceptions::Win32APIError: The request is not supported.
       ---- Begin Win32 API output ----
       System Error Code: 50
       System Error Message: The request is not supported.
       ---- End Win32 API output ----
       
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/win32/error.rb:81:in `raise!'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/win32/security.rb:730:in `test_and_raise_lsa_nt_status'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/win32/security.rb:129:in `block in remove_account_right'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/win32/security.rb:668:in `with_lsa_policy'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/win32/security.rb:127:in `remove_account_right'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/resource/windows_user_privilege.rb:179:in `block (4 levels) in <class:WindowsUserPrivilege>'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/mixin/why_run.rb:51:in `add_action'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/provider.rb:265:in `converge_by'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/resource/windows_user_privilege.rb:178:in `block (3 levels) in <class:WindowsUserPrivilege>'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/resource/windows_user_privilege.rb:177:in `each'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/resource/windows_user_privilege.rb:177:in `block (2 levels) in <class:WindowsUserPrivilege>'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/resource/windows_user_privilege.rb:171:in `each'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/resource/windows_user_privilege.rb:171:in `block in <class:WindowsUserPrivilege>'
       (eval):2:in `block in action_set'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/provider.rb:276:in `instance_eval'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/provider.rb:276:in `compile_and_converge_action'
       (eval):2:in `action_set'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/provider.rb:217:in `run_action'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/resource.rb:599:in `block in run_action'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/resource.rb:626:in `with_umask'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/resource.rb:598:in `run_action'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/runner.rb:74:in `run_action'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/runner.rb:108:in `block in run_all_actions'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/runner.rb:108:in `each'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/runner.rb:108:in `run_all_actions'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/runner.rb:132:in `block in converge'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
       C:/opscode/chef/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `execute_each_resource'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/runner.rb:130:in `converge'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/client.rb:684:in `block in converge'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/client.rb:679:in `catch'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/client.rb:679:in `converge'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/client.rb:703:in `converge_and_save'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/client.rb:283:in `run'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/application.rb:281:in `block in run_chef_client'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/local_mode.rb:42:in `with_server_connectivity'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/application.rb:264:in `run_chef_client'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/application/base.rb:337:in `run_application'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14-universal-mingw32/lib/chef/application.rb:67:in `run'
       C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.6.14/bin/chef-client:25:in `<top (required)>'
       C:/opscode/chef/bin/chef-client:167:in `load'
       C:/opscode/chef/bin/chef-client:167:in `<main>'

```

**Comment by mwrock** [comment]
This is likely because Windows will not function correctly if the `LocalService` user is removed from that priviledge. Because you are assigning only `Administrators`, the resource will attempt to remove all users already assigned that are NOT in Administrators. If you change your `users` to `['LOCALSERVICE','BUILTIN\Administrators']` then the resource should succeed.
