### ISSUE TITLE
Error if log_location is set in chef_client_config resource

### ISSUE THREAD

**Issue by srb3** [chef/chef#10607]
## Description
Setting the log_location in the chef_client_config resource causes the client run to fail

## Chef Version
16.6.14

## Platform Version
CentOS 7.9

## Replication Case
Set the following recipe code
```
chef_client_config 'create client.rb' do
    chef_server_url  Chef::Config[:chef_server_url]
    log_location :syslog
    ssl_verify_mode :verify_none
  end
```

## Client Output

```
   
      ================================================================================
      Error executing action `create` on resource 'template[/etc/chef/client.rb]'
 [10.0.1.34]       ================================================================================
      
      Chef::Mixin::Template::TemplateError
      ------------------------------------
      class or module required
      
      Resource Declaration:
      ---------------------
      # In /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/resource/chef_client_config.rb
      
      249:         template ::File.join(new_resource.config_directory, "client.rb") do
      250:           source ::File.expand_path("support/client.erb", __dir__)
      251:           user new_resource.user unless new_resource.user.nil?
      252:           group new_resource.group unless new_resource.group.nil?
      253:           local true
      254:           variables(
      255:             chef_license: new_resource.chef_license,
      256:             chef_server_url: new_resource.chef_server_url,
      257:             event_loggers: new_resource.event_loggers,
      258:             exception_handlers: format_handler(new_resource.exception_handlers),
      259:             file_backup_path: new_resource.file_backup_path,
      260:             file_cache_path: new_resource.file_cache_path,
      261:             file_staging_uses_destdir: new_resource.file_staging_uses_destdir,
      262:             formatters: new_resource.formatters,
      263:             http_proxy: new_resource.http_proxy,
      264:             https_proxy: new_resource.https_proxy,
      265:             ftp_proxy: new_resource.ftp_proxy,
      266:             log_level: new_resource.log_level,
      267:             log_location: new_resource.log_location,
      268:             minimal_ohai: new_resource.minimal_ohai,
      269:             named_run_list: new_resource.named_run_list,
      270:             no_proxy: new_resource.no_proxy,
      271:             node_name: new_resource.node_name,
      272:             ohai_disabled_plugins: new_resource.ohai_disabled_plugins,
      273:             ohai_optional_plugins: new_resource.ohai_optional_plugins,
      274:             pid_file: new_resource.pid_file,
      275:             policy_group: new_resource.policy_group,
      276:             policy_name: new_resource.policy_name,
      277:             report_handlers: format_handler(new_resource.report_handlers),
      278:             ssl_verify_mode: new_resource.ssl_verify_mode,
      279:             start_handlers: format_handler(new_resource.start_handlers),
      280:             additional_config: new_resource.additional_config
      281:           )
      282:           mode "0640"
      283:           action :create
      284:         end
      285:       end
      
      Compiled Resource:
      ------------------
      # Declared in /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/resource/chef_client_config.rb:249:in `block in <class:ChefClientConfig>'
      
      template("/etc/chef/client.rb") do
        action [:create]
        default_guard_interpreter :default
        source "/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/resource/support/client.erb"
        declared_type :template
        cookbook_name "chef_client_wrapper"
        local true
        variables {:chef_license=>nil, :chef_server_url=>"https://10.0.1.5/organizations/acmecorp", :event_loggers=>[], :exception_handlers=>[], :file_backup_path=>nil, :file_cache_path=>nil, :file_staging_uses_destdir=>nil, :formatters=>[], :http_proxy=>nil, :https_proxy=>nil, :ftp_proxy=>nil, :log_level=>nil, :log_location=>:syslog, :minimal_ohai=>nil, :named_run_list=>nil, :no_proxy=>"", :node_name=>"linux-client-0", :ohai_disabled_plugins=>[], :ohai_optional_plugins=>[], :pid_file=>nil, :policy_group=>nil, :policy_name=>nil, :report_handlers=>[], :ssl_verify_mode=>:verify_none, :start_handlers=>[], :additional_config=>nil}
        mode "0640"
        path "/etc/chef/client.rb"
        owner nil
        group nil
        verifications []
      end
      
      Template Context:
 [10.0.1.34]       -----------------
      on line #28
       26: <%# log_location is special due to STDOUT/STDERR from String -> IO Object -%>
       27: <% unless @log_location.nil? %>
       28:   <% if @log_location.is_a? String && %w(STDOUT STDERR).include?(@log_location) -%>
       29: log_location = <%= @log_location %>
       30:   <% else -%>
      
      System Info:
      ------------
      chef_version=16.6.14
      platform=centos
      platform_version=7.7.1908
      ruby=ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
      program_name=/bin/chef-client
      executable=/opt/chef/bin/chef-client


    Error executing action `create` on resource 'chef_client_config[create client.rb]'
    ================================================================================
    
    Chef::Mixin::Template::TemplateError
    ------------------------------------
    class or module required
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/chef_client_wrapper/recipes/config.rb
    
      1: chef_client_config 'create client.rb' do
      2:   chef_server_url  Chef::Config[:chef_server_url]
      3:   log_location platform?('windows') ? :win_evt : :syslog
      4:   ssl_verify_mode :verify_none
      5: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/chef_client_wrapper/recipes/config.rb:1:in `from_file'
    
    chef_client_config("create client.rb") do
      action [:create]
      default_guard_interpreter :default
      declared_type :chef_client_config
      cookbook_name "chef_client_wrapper"
      recipe_name "config"
      chef_server_url "https://10.0.1.5/organizations/acmecorp"
      log_location :syslog
      ssl_verify_mode :verify_none
      no_proxy ""
      node_name "linux-client-0"
      ohai_disabled_plugins []
      ohai_optional_plugins []
    end
    
    Template Context:
    -----------------
    on line #28
     26: <%# log_location is special due to STDOUT/STDERR from String -> IO Object -%>
     27: <% unless @log_location.nil? %>
     28:   <% if @log_location.is_a? String && %w(STDOUT STDERR).include?(@log_location) -%>
     29: log_location = <%= @log_location %>
     30:   <% else -%>
    
    System Info:
    ------------
    chef_version=16.6.14
    platform=centos
    platform_version=7.7.1908
    ruby=ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
    program_name=/bin/chef-client
    executable=/opt/chef/bin/chef-client
```

## Potential Fix
I have not really come across this error before in this kind of context, but if you change this line:
```
<% if @log_location.is_a? String && %w(STDOUT STDERR).include?(@log_location) -%>
```
to:
```
<% if (@log_location.is_a? String) && (%w(STDOUT STDERR).include?(@log_location)) -%>
```
Things work as expected

There is a second issue with the template logic

```
<% next if instance_variable_get(prop).nil? || instance_variable_get(prop).empty? -%>
<%=prop.delete_prefix("@") %> = <%= instance_variable_get(prop).inspect %>
<% end -%>
<%# log_location is special due to STDOUT/STDERR from String -> IO Object -%>
<% unless @log_location.nil? %>
  <% if (@log_location.is_a? String) && (%w(STDOUT STDERR).include?(@log_location)) -%>
log_location = <%= @log_location %>
  <% else -%>
log_location = <%= @log_location.inspect %>
  <% end -%>
<% end -%>
```
This results in log_location being rendered twice into the client.rb, once by the line `<%=prop.delete_prefix("@") %> = <%= instance_variable_get(prop).inspect %>` and again by either condition of `<% if (@log_location.is_a? String) && (%w(STDOUT STDERR).include?(@log_location)) -%>`

https://github.com/chef/chef/blob/master/lib/chef/resource/support/client.erb#L23-L33

changing this line:
```
<% next if instance_variable_get(prop).nil? || instance_variable_get(prop).empty? -%>
```
to:
```
<% next if instance_variable_get(prop).nil? || instance_variable_get(prop).empty? || prop == '@log_location' -%>
```

fixes that problem

**Comment by tas50** [comment]
Fixed in master
