### ISSUE TITLE
Resolve failures preventing us from enabling Solaris builds again

### ISSUE THREAD

**Issue by tas50** [chef/chef#10616]
```
Failures:
  1) chef-client when the chef repo has a cookbook with a no-op recipe and a config file under .chef/knife.rb should load .chef/knife.rb when -z is specified
     Failure/Error: expect(result.stdout).to include("xxx")
       expected "[2020-11-10T19:15:58+00:00] WARN: No config file found or specified on command line. Using command line options instead.\nStarting Chef Infra Client, version 16.7.31\nPatents: https://www.chef.io/patents\n[2020-11-10T19:15:59+00:00] WARN: Run List override has been provided.\n[2020-11-10T19:15:59+00:00] WARN: Original Run List: []\n[2020-11-10T19:15:59+00:00] WARN: Overridden Run List: [recipe[x::default]]\nresolving cookbooks for run list: [\"x::default\"]\nSynchronizing Cookbooks:\n  - x (0.0.0)\nInstalling Cookbook Gems:\nCompiling Cookbooks...\nConverging 0 resources\n[2020-11-10T19:15:59+00:00] WARN: Skipping final node save because override_runlist was given\n\nRunning handlers:\nRunning handlers complete\nChef Infra Client finished, 0/0 resources updated in 00 seconds\n" to include "xxx"
       Diff:
       @@ -1,2 +1,18 @@
       -xxx
       +[2020-11-10T19:15:58+00:00] WARN: No config file found or specified on command line. Using command line options instead.
       +Starting Chef Infra Client, version 16.7.31
       +Patents: https://www.chef.io/patents
       +[2020-11-10T19:15:59+00:00] WARN: Run List override has been provided.
       +[2020-11-10T19:15:59+00:00] WARN: Original Run List: []
       +[2020-11-10T19:15:59+00:00] WARN: Overridden Run List: [recipe[x::default]]
       +resolving cookbooks for run list: ["x::default"]
       +Synchronizing Cookbooks:
       +  - x (0.0.0)
       +Installing Cookbook Gems:
       +Compiling Cookbooks...
       +Converging 0 resources
       +[2020-11-10T19:15:59+00:00] WARN: Skipping final node save because override_runlist was given
       +
       +Running handlers:
       +Running handlers complete
       +Chef Infra Client finished, 0/0 resources updated in 00 seconds
     # ./spec/integration/client/client_spec.rb:102:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:305:in `block (2 levels) in <top (required)>'
```

**Comment by lamont-granquist** [comment]
Yeah so the ultimate root cause of this is that shell_out on solaris when called without splat-args passed the string to the shell which is the very stupid old shell on bourne shell on solaris which doesn't do ENV['PWD'], while the ENV['PWD'] from the parent process is preserved (presumably we're running the buildkite tests under a halfway modern bash).  I can simulate the failure on Mac (and probably Linux) but only by converting the shell_out to splat-args to bypass the shell, and then by mangling the ENV['PWD'].  The solution should probably be to just clear ENV['PWD'] for that test.
