### ISSUE TITLE
ZD : IPAddr::AddressFamilyError: address family must be specified

### ISSUE THREAD

**Issue by dheerajd-msys** [chef/chef#10611]
## Description

Per one of the customers, he is facing the below error Upon upgrading chef client to version 14.x to 16.3.45.1, a couple servers out of ~100 servers, have the error which is attached to this ticket.

**On Working Node**
```
[root@mljaixt6:/] $ chef-shell
loading configuration: none (standalone session)
true
Session type: standalone
Loading.................done.
Welcome to the chef-shell 16.3.45
For usage see https://docs.chef.io/chef_shell/
run help' for help, exit' or ^D to quit.
chef (16.3.45)> Chef.node['network']['default_interface']
=> "en1"
chef (16.3.45)> Chef.node['ipaddress']
=> "10.216.123.21"
chef (16.3.45)> IPAddr.new(node['ipaddress'])
=> #<IPAddr: IPv4:10.216.123.21/255.255.255.255>
```
**Non - Working Node:**
```
chef (16.3.45)> Chef.node['network']['default_interface']
 => "en1"
chef (16.3.45)> Chef.node['ipaddress']
 => nil
chef (16.3.45)> IPAddr.new(node['ipaddress'])
Traceback (most recent call last):
        9: from /usr/bin/chef-shell:160:in `<main>'
        8: from /usr/bin/chef-shell:160:in `load'
        7: from /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.3.45/bin/chef-shell:31:in `<top (required)>'
        6: from /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/shell.rb:86:in `start'
        5: from /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/shell.rb:86:in `catch'
        4: from /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.3.45/lib/chef/shell.rb:87:in `block in start'
        3: from (irb):5
        2: from (irb):5:in `new'
        1: from /opt/chef/embedded/lib/ruby/2.7.0/ipaddr.rb:565:in `initialize'
IPAddr::AddressFamilyError (address family must be specified)
[root@mljaixt7:/] $ ifconfig -a
en0: flags=1e084863,80480<UP,BROADCAST,NOTRAILERS,RUNNING,SIMPLEX,MULTICAST,GROUPRT,64BIT,CHECKSUM_OFFLOAD(ACTIVE),CHAIN>
        inet 10.216.21.15 netmask 0xffffff00 broadcast 10.216.21.255
         tcp_sendspace 262144 tcp_recvspace 262144 rfc1323 1
en1: flags=1e084863,80480<UP,BROADCAST,NOTRAILERS,RUNNING,SIMPLEX,MULTICAST,GROUPRT,64BIT,CHECKSUM_OFFLOAD(ACTIVE),CHAIN>
        inet 10.216.123.13 netmask 0xffffff00 broadcast 10.216.123.255
         tcp_sendspace 262144 tcp_recvspace 262144 rfc1323 1
en2: flags=1e084863,80480<UP,BROADCAST,NOTRAILERS,RUNNING,SIMPLEX,MULTICAST,GROUPRT,64BIT,CHECKSUM_OFFLOAD(ACTIVE),CHAIN>
        inet 10.216.83.13 netmask 0xffff1900 broadcast 10.216.247.255
         tcp_sendspace 262144 tcp_recvspace 262144 rfc1323 1
en3: flags=1e084863,80480<UP,BROADCAST,NOTRAILERS,RUNNING,SIMPLEX,MULTICAST,GROUPRT,64BIT,CHECKSUM_OFFLOAD(ACTIVE),CHAIN>
        inet 10.216.82.65 netmask 0xffffff00 broadcast 10.216.82.255
         tcp_sendspace 262144 tcp_recvspace 262144 rfc1323 1
lo0: flags=e08084b,c0<UP,BROADCAST,LOOPBACK,RUNNING,SIMPLEX,MULTICAST,GROUPRT,64BIT,LARGESEND,CHAIN>
        inet 127.0.0.1 netmask 0xff000000 broadcast 127.255.255.255
        inet6 ::1%1/64
         tcp_sendspace 131072 tcp_recvspace 131072 rfc1323 1
```
## Client Output

```

```

**Comment by sanga1794** [comment]
Hello there, I have tried to reproduce the issue but not able to reproduce below are the steps i followed:
1) bootstrapped a node with chef-client version: `14.15.6`.
2) Updated a chef-client version to 16.3.45 using both the `curl` command and `chef_client_updater` cookbook.
3) By using chef-shell checked `Chef.node['ipaddress']`, `Chef.node['network']['default_interface']`, both are working fine and shows no error.

Please suggest me if i'm missing something. Thanks

**Comment by tas50** [comment]
The root cause of this problem is actually that node['ipaddress'] is not being populated by Ohai and we need to dig into that, which should be handled in the ohai project. I'll move this over.
