### ISSUE TITLE
AttributeError: 'Base' object has no attribute 'closeRpmDB'

### ISSUE THREAD

**Issue by breisig** [chef/chef#10677]
Tring to bootstrap a server using chef-client 16.6.14 (rpm 4.16, libdnf 0.55, dnf-4.4.2, modulemd 2.9.4) and getting the following error message when trying to install a package via dnf (dnf_package "net-tools")

```
root@ldap ~# cat /var/chef/cache/chef-stacktrace.out
Generated at 2020-11-22 17:07:58 -0600
RuntimeError: dnf_package[net-tools] (test-baseinstall::default line 9) had an error: RuntimeError: dnf-helper.py had stderr/stdout output:

Traceback (most recent call last):
  File "/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf/dnf_helper.py", line 164, in <module>
    query(command)
  File "/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf/dnf_helper.py", line 89, in query
    sack = get_sack()
  File "/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf/dnf_helper.py", line 28, in get_sack
    base.read_all_repos()
  File "/usr/lib/python3.6/site-packages/dnf/base.py", line 475, in read_all_repos
    for repo in reader:
  File "/usr/lib/python3.6/site-packages/dnf/conf/read.py", line 41, in __iter__
    for r in self._get_repos(self.conf.config_file_path):
  File "/usr/lib/python3.6/site-packages/dnf/conf/read.py", line 100, in _get_repos
    parser.setSubstitutions(substs)
  File "/usr/lib/python3.6/site-packages/libdnf/conf.py", line 1574, in setSubstitutions
    return _conf.ConfigParser_setSubstitutions(self, substitutions)
TypeError: in method 'ConfigParser_setSubstitutions', argument 2 of type 'std::map< std::string,std::string,std::less< std::string >,std::allocator< std::pair< std::string const,std::string > > > const &'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf/dnf_helper.py", line 173, in <module>
    base.closeRpmDB()
AttributeError: 'Base' object has no attribute 'closeRpmDB'

/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf/python_helper.rb:213:in `rescue in with_helper'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf/python_helper.rb:190:in `with_helper'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf/python_helper.rb:148:in `query'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf/python_helper.rb:114:in `package_query'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf.rb:213:in `installed_version'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf.rb:92:in `block in get_current_versions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf.rb:91:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf.rb:91:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf.rb:91:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf.rb:91:in `map'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf.rb:91:in `get_current_versions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf.rb:69:in `load_current_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider.rb:200:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/resource.rb:599:in `block in run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/resource.rb:626:in `with_umask'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/resource.rb:598:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/runner.rb:74:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/runner.rb:108:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/runner.rb:132:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/runner.rb:130:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/client.rb:684:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/client.rb:679:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/client.rb:679:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/client.rb:703:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/client.rb:283:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/application.rb:281:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/application.rb:264:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/application/base.rb:337:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/application.rb:67:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.6.14/bin/chef-client:25:in `<top (required)>'
/usr/bin/chef-client:155:in `load'
/usr/bin/chef-client:155:in `<main>'

>>>> Caused by EOFError: end of file reached
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf/python_helper.rb:152:in `sysread'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf/python_helper.rb:152:in `block in query'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf/python_helper.rb:195:in `block in with_helper'
/opt/chef/embedded/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/opt/chef/embedded/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
/opt/chef/embedded/lib/ruby/2.7.0/timeout.rb:33:in `catch'
/opt/chef/embedded/lib/ruby/2.7.0/timeout.rb:33:in `catch'
/opt/chef/embedded/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf/python_helper.rb:193:in `with_helper'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf/python_helper.rb:148:in `query'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf/python_helper.rb:114:in `package_query'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf.rb:213:in `installed_version'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf.rb:92:in `block in get_current_versions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf.rb:91:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf.rb:91:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf.rb:91:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf.rb:91:in `map'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf.rb:91:in `get_current_versions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider/package/dnf.rb:69:in `load_current_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/provider.rb:200:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/resource.rb:599:in `block in run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/resource.rb:626:in `with_umask'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/resource.rb:598:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/runner.rb:74:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/runner.rb:108:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/runner.rb:132:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/runner.rb:130:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/client.rb:684:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/client.rb:679:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/client.rb:679:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/client.rb:703:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/client.rb:283:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/application.rb:281:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/application.rb:264:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/application/base.rb:337:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/application.rb:67:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.6.14/bin/chef-client:25:in `<top (required)>'
/usr/bin/chef-client:155:in `load'
/usr/bin/chef-client:155:in `<main>'
```

**Comment by tas50** [comment]
This shipped in 17.1
