### ISSUE TITLE
uninitialized constant Chef::Knife::UI::TTY

### ISSUE THREAD

**Issue by evandam** [chef/chef#10705]
## Description

Hi folks,

We're seeing an issue when trying to run `knife ssh` when using `-P/--ssh-password` using both Chef Workstation 20.10.168 and 20.11.180:

@tas50 any thoughts?

```
$ knife ssh 'name:jumphost**' 'uptime' -VV -t 2 -A -P
INFO: Using configuration from /Users/evanvandam/.chef/config.rb
Traceback (most recent call last):
	13: from /opt/chef-workstation/bin/knife:352:in `<main>'
	12: from /opt/chef-workstation/bin/knife:352:in `load'
	11: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/bin/knife:24:in `<top (required)>'
	10: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/application/knife.rb:165:in `run'
	 9: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/knife.rb:229:in `run'
	 8: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/knife.rb:489:in `run_with_pretty_exceptions'
	 7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/local_mode.rb:42:in `with_server_connectivity'
	 6: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/knife.rb:490:in `block in run_with_pretty_exceptions'
	 5: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/knife/ssh.rb:603:in `run'
	 4: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/knife/ssh.rb:578:in `configure_password'
	 3: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/knife/ssh.rb:402:in `get_password'
	 2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/knife/ssh.rb:406:in `prompt_for_password'
	 1: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/knife/core/ui.rb:173:in `ask'
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.6.14/lib/chef/knife/core/ui.rb:67:in `prompt': uninitialized constant Chef::Knife::UI::TTY (NameError)
```

`knife ssh` works without passing `-P`, though.

Last working version of Chef Workstation:

```
Chef Workstation version: 20.9.148
Chef Infra Client version: 16.4.41
Chef InSpec version: 4.23.4
Chef CLI version: 3.0.27
Chef Habitat version: 1.6.56
Test Kitchen version: 2.7.1
Cookstyle version: 6.18.8
```

## Chef Version

```
Chef Workstation version: 20.11.180
Chef Infra Client version: 16.6.14
Chef InSpec version: 4.23.15
Chef CLI version: 3.0.33
Chef Habitat version: 1.6.56
Test Kitchen version: 2.7.2
Cookstyle version: 7.2.1
```

## Platform Version

macOS Catalina 10.15.7

**Comment by scalp42** [comment]
Same issue with:

```
Chef Workstation version: 20.12.187
Chef Infra Client version: 16.7.61
Chef InSpec version: 4.23.15
Chef CLI version: 3.0.33
Chef Habitat version: 1.6.181
Test Kitchen version: 2.8.0
Cookstyle version: 7.2.1
```

**Comment by tas50** [comment]
Fixed on master. Thanks for the report @scalp42 @evandam
