### ISSUE TITLE
rspec 3.10 breaks unit tests

### ISSUE THREAD

**Issue by tas50** [chef/chef#10817]
```
Failures:

  1) Chef::Knife::SupermarketShare run when the --dry-run flag is specified should list files in the tarball
     Failure/Error: allow(@knife).to receive_message_chain(:shell_out!, :stdout).and_return("file")

     ArgumentError:
       Cannot proxy frozen objects, rspec-mocks relies on proxies for method stubbing and expectations.
     # ./spec/unit/knife/supermarket_share_spec.rb:143:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:305:in `block (2 levels) in <top (required)>'

  2) Chef::Knife::SupermarketShare run when the --dry-run flag is specified does not upload the cookbook
     Failure/Error: allow(@knife).to receive_message_chain(:shell_out!, :stdout).and_return("file")

     ArgumentError:
       Cannot proxy frozen objects, rspec-mocks relies on proxies for method stubbing and expectations.
     # ./spec/unit/knife/supermarket_share_spec.rb:143:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:305:in `block (2 levels) in <top (required)>'

Finished in 0.83307 seconds (files took 3.96 seconds to load)
16 examples, 2 failures

Failed examples:

rspec ./spec/unit/knife/supermarket_share_spec.rb:146 # Chef::Knife::SupermarketShare run when the --dry-run flag is specified should list files in the tarball
rspec ./spec/unit/knife/supermarket_share_spec.rb:153 # Chef::Knife::SupermarketShare run when the --dry-run flag is specified does not upload the cookbook
```

**Comment by snehaldwivedi** [comment]
@tas50 I have tried running RSpec on ubuntu and on windows with the latest code with `rspec (3.10.0)` but I am not getting the above failures. Everything is working fine for me.

```$ bundle exec rspec ./spec/unit/knife/supermarket_share_spec.rb
Run options:
  include {:focus=>true}
  exclude {:provider=>#<Proc: ./spec/spec_helper.rb:213>, :arch=>#<Proc: ./spec/spec_helper.rb:207>, :pwsh_installed=>true, :requires_ifconfig=>true, :choco_installed=>true, :ruby=>"2.7.0", :chef=>"17.0.31", :not_intel_64bit=>true, :rhel_gte_8=>true, :rhel8=>true, :rhel7=>true, :rhel6=>true, :rhel=>true, :not_wpar=>true, :broken=>true, :openssl_lt_101=>true, :requires_root_or_running_windows=>true, :requires_root=>true, :selinux_only=>true, :opensuse=>true, :suse_only=>true, :aix_only=>true, :system_windows_service_gem_only=>true, :solaris_only=>true, :windows_service_requires_assign_token=>true, :windows_domain_joined_only=>true, :windows_powershell_dsc_only=>true, :ruby32_only=>true, :windows_gte_10=>true, :windows32_only=>true, :windows64_only=>true, :win2012r2_only=>true, :macos_gte_1014=>true, :macos_1013=>true, :macos_only=>true, :windows_only=>true, :volatile_from_verify=>false, :volatile=>true, :external=>true}

All examples were filtered out; ignoring {:focus=>true}
..Making tarball cookbook_name.tgz
Upload complete
.Making tarball cookbook_name.tgz
Upload complete
..Making tarball cookbook_name.tgz
Upload complete
..Making tarball cookbook_name.tgz
Upload complete
.Making tarball cookbook_name.tgz
.Making tarball cookbook_name.tgz
Upload complete
.Making tarball cookbook_name.tgz
Not uploading cookbook_name.tgz due to --dry-run flag.
file
.Making tarball cookbook_name.tgz
Not uploading cookbook_name.tgz due to --dry-run flag.
file
.....

Finished in 0.71415 seconds (files took 3.71 seconds to load)
16 examples, 0 failures
``` 
Please let me know if I am missing something?

**Comment by tas50** [comment]
Here's a PR updating inspec/rspec where you can see the rspec-mocks failure: https://buildkite.com/chef-oss/chef-chef-master-verify/builds/7556#9b401be3-242c-46f0-ba43-617cfe72a8c0/90-1023

**Comment by tas50** [comment]
@snehaldwivedi Do we have an update on this issue?

**Comment by snehaldwivedi** [comment]
@tas50 I have replicated this issue by using `rspec 3.10.1`.  I need to check the parameters for this command by running it to stub this request properly. So I am studying about the stove to use share a cookbook on supermarket using this command.

**Comment by tas50** [comment]
Fixed by @lamont-granquist in https://github.com/chef/chef/pull/10959

**Comment by tas50** [comment]
1 day engineering effort
