### ISSUE TITLE
PowerShell Script Timing Out, Leading to Orphaned Processes

### ISSUE THREAD

**Issue by JohnnyBopper** [chef/chef#10848]
## Description
This issue has happened twice in the past month on 2 different servers. Both of the servers are Citrix infrastructure servers.
I have a recipe that fixes all of the unquoted service paths. It uses the powershell_script resource with the not_if guard. 

Running the guard portion of the script manually on the server runs fine and returns "true" like I would expect.
We have our Chef client running every hour as a scheduled task. Every hour since the start of the issue I can see in the event log that the chef client run fails referring to the PowerShell script timeout.
```
Failed Chef Infra Client run 8f893f7e-e821-4155-a0d2-83eae552a8b4 in 3611.5560483 seconds.
 Exception type: Mixlib::ShellOut::CommandTimeout
 Exception message: powershell_script[fix-service-path] (bsb-windows-server-baseline_pf::servicepath line 1) had an error: Mixlib::ShellOut::CommandTimeout: powershell_script[Guard resource] (dynamically defined) had an error: Mixlib::ShellOut::CommandTimeout: command timed out:
---- Begin output of "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None  -File "C:/Windows/Temp/chef-script20210102-16608-1qa6qwv.ps1" ----
STDOUT: 
STDERR: 
---- End output of "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None  -File "C:/Windows/Temp/chef-script20210102-16608-1qa6qwv.ps1" ----

ProcessId: 16700
app_name: C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe
command_line: "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None  -File "C:/Windows/Temp/chef-script20210102-16608-1qa6qwv.ps1"
timeout: 3600
 Exception backtrace: C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.1.4-universal-mingw32/lib/mixlib/shellout/windows.rb:130:in `block in run_command'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.1.4-universal-mingw32/lib/mixlib/shellout/windows.rb:104:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.1.4-universal-mingw32/lib/mixlib/shellout/windows.rb:104:in `run_command'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.1.4-universal-mingw32/lib/mixlib/shellout.rb:270:in `run_command'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.1.4-universal-mingw32/lib/mixlib/shellout/helper.rb:154:in `__shell_out_command'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.1.4-universal-mingw32/lib/mixlib/shellout/helper.rb:128:in `shell_out_compacted!'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.1.4-universal-mingw32/lib/mixlib/shellout/helper.rb:54:in `shell_out!'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/provider/execute.rb:52:in `block (2 levels) in <class:Execute>'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/mixin/why_run.rb:51:in `add_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/provider.rb:268:in `converge_by'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/provider/execute.rb:50:in `block in <class:Execute>'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/provider/windows_script.rb:127:in `block (3 levels) in <class:WindowsScript>'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/provider/windows_script.rb:112:in `block in with_temp_script_file'
C:/opscode/chef/embedded/lib/ruby/2.7.0/tempfile.rb:291:in `open'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/provider/windows_script.rb:103:in `with_temp_script_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/provider/windows_script.rb:126:in `block (2 levels) in <class:WindowsScript>'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/provider/windows_script.rb:58:in `with_wow64_redirection_disabled'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/provider/windows_script.rb:125:in `block in <class:WindowsScript>'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/provider/powershell_script.rb:31:in `block in <class:PowershellScript>'
(eval):2:in `block in action_run'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/provider.rb:279:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/provider.rb:279:in `compile_and_converge_action'
(eval):2:in `action_run'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/provider.rb:220:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/resource.rb:599:in `block in run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/resource.rb:626:in `with_umask'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/resource.rb:598:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/guard_interpreter/resource_guard_interpreter.rb:74:in `block in evaluate_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/guard_interpreter/resource_guard_interpreter.rb:74:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/guard_interpreter/resource_guard_interpreter.rb:74:in `evaluate_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/guard_interpreter/resource_guard_interpreter.rb:60:in `evaluate'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/resource/conditional.rb:99:in `evaluate_command'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/resource/conditional.rb:95:in `evaluate'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/resource/conditional.rb:88:in `continue?'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/resource.rb:1542:in `block in should_skip?'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/resource.rb:1541:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/resource.rb:1541:in `find'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/resource.rb:1541:in `should_skip?'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/resource.rb:596:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/runner.rb:74:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/runner.rb:108:in `block in run_all_actions'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/runner.rb:108:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/runner.rb:108:in `run_all_actions'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/runner.rb:132:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/runner.rb:130:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/client.rb:714:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/client.rb:709:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/client.rb:709:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/client.rb:733:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/client.rb:288:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/application.rb:304:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/application.rb:280:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/local_mode.rb:42:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/application.rb:263:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/application/base.rb:335:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.4.41-universal-mingw32/lib/chef/application.rb:68:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.4.41/bin/chef-client:25:in `<top (required)>'
C:/opscode/chef/bin/chef-client:173:in `load'
C:/opscode/chef/bin/chef-client:173:in `<main>'
```
I also see this in the chef client log.
```
Recipe: bsb-windows-server-baseline_pf::servicepath
  * powershell_script[fix-service-path] action run[2021-01-06T04:40:46-06:00] INFO: Processing powershell_script[fix-service-path] action run (bsb-windows-server-baseline_pf::servicepath line 1)
[2021-01-06T04:40:46-06:00] INFO: Processing powershell_script[Guard resource] action run (dynamically defined)

    
    ================================================================================
    [31mError executing action `run` on resource 'powershell_script[fix-service-path]'[0m
    ================================================================================
    
    Mixlib::ShellOut::CommandTimeout
    --------------------------------
    powershell_script[Guard resource] (dynamically defined) had an error: Mixlib::ShellOut::CommandTimeout: command timed out:
    ---- Begin output of "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None  -File "C:/Windows/Temp/chef-script20210106-15020-qq1r2v.ps1" ----
    STDOUT: 
    STDERR: 
    ---- End output of "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None  -File "C:/Windows/Temp/chef-script20210106-15020-qq1r2v.ps1" ----
    
    ProcessId: 5600
    app_name: C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe
    command_line: "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None  -File "C:/Windows/Temp/chef-script20210106-15020-qq1r2v.ps1"
    timeout: 3600
    
    Resource Declaration:
    ---------------------
    # In C:/chef/cache/cookbooks/bsb-windows-server-baseline_pf/recipes/servicepath.rb
    
      1: powershell_script 'fix-service-path' do
      2:   code <<-EOH
      3:     $Services = Get-WmiObject -Class Win32_Service
      4: 
      5:     $Services | % {
      6:       #Check the path of each service, locate .exe in the path string, then check if any spaces in the path
      7:       #Also check if any " in the path before the EXE.  If no " and a space exists, then its not compliant
      8: 
      9:       $ServiceName = $_.Name
     10:       $ServiceEXEPath = $_.PathName
     11: 
     12:       $RegPath = (Get-itemproperty -LiteralPath "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\$ServiceName").ImagePath
     13: 
     14:       $IndexOfSpace = $RegPath.IndexOf(" ")
     15:       $IndexOfEXE   = ($RegPath.toupper()).IndexOf(".EXE")
     16:       $IndexOfQuote = $RegPath.IndexOf("`"")
     17: 
     18:       if (($IndexOfSpace -ne -1) -and ($IndexOfSpace -lt $IndexOfEXE) -and ($IndexOfQuote -ne 0))
     19:       {
     20:         $newpath = "`"" + $Regpath.substring(0,$IndexofEXE+4) + "`""
     21: 
     22: 	    if (($RegPath.length) -gt ($IndexOfEXE+4))
     23:         {
     24:           $newpath += $RegPath.substring($IndexOfEXE+4,($Regpath.length - $IndexofEXE - 4))
     25:         }
     26: 
     27: 	    #Write-Host "[$ServiceName]`n[$ServiceEXEPath]`n[$IndexOfSpace][$IndexOfEXE][$IndexOfQuote]`n[$NewPath]"
     28: 
     29: 	    Set-ItemProperty -LiteralPath "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\$ServiceName" -Name ImagePath -Value $newpath
     30: 	  }
     31:     }
     32:   EOH
     33: 
     34:   not_if <<-EOH
     35:     $Services = Get-WmiObject -Class Win32_Service
     36: 
     37: 	$Compliant = ""
     38: 
     39: 	$Services | % {
     40:       #Check the path of each service, locate .exe in the path string, then check if any spaces in the path
     41: 	  #Also check if any " in the path before the EXE.  If no " and a space exists, then its not compliant
     42: 
     43: 	  $ServiceName = $_.Name
     44: 	  $ServiceEXEPath = $_.PathName
     45: 
     46: 	  $RegPath = (Get-itemproperty -LiteralPath "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\$ServiceName").ImagePath
     47: 
     48: 	  $IndexOfSpace = $RegPath.IndexOf(" ")
     49: 	  $IndexOfEXE   = $RegPath.IndexOf(".exe")
     50: 	  $IndexOfQuote = $RegPath.IndexOf("`"")
     51: 
     52: 	  if (($IndexOfSpace -ne -1) -and ($IndexOfSpace -lt $IndexOfEXE) -and ($IndexOfQuote -ne 0))
     53: 	  {
    
    Compiled Resource:
    ------------------
    # Declared in C:/chef/cache/cookbooks/bsb-windows-server-baseline_pf/recipes/servicepath.rb:1:in `from_file'
    
    powershell_script("fix-service-path") do
      action [:run]
      default_guard_interpreter :powershell_script
      interpreter "powershell.exe"
      declared_type :powershell_script
      cookbook_name "bsb-windows-server-baseline_pf"
      recipe_name "servicepath"
      code "    $Services = Get-WmiObject -Class Win32_Service\n\n    $Services | % {\n      #Check the path of each service, locate .exe in the path string, then check if any spaces in the path\n      #Also check if any \" in the path before the EXE.  If no \" and a space exists, then its not compliant\n\n      $ServiceName = $_.Name\n      $ServiceEXEPath = $_.PathName\n\n      $RegPath = (Get-itemproperty -LiteralPath \"HKLM:\\SYSTEM\\CurrentControlSet\\Services\\$ServiceName\").ImagePath\n\n      $IndexOfSpace = $RegPath.IndexOf(\" \")\n      $IndexOfEXE   = ($RegPath.toupper()).IndexOf(\".EXE\")\n      $IndexOfQuote = $RegPath.IndexOf(\"`\"\")\n\n      if (($IndexOfSpace -ne -1) -and ($IndexOfSpace -lt $IndexOfEXE) -and ($IndexOfQuote -ne 0))\n      {\n        $newpath = \"`\"\" + $Regpath.substring(0,$IndexofEXE+4) + \"`\"\"\n\n\t    if (($RegPath.length) -gt ($IndexOfEXE+4))\n        {\n          $newpath += $RegPath.substring($IndexOfEXE+4,($Regpath.length - $IndexofEXE - 4))\n        }\n\n\t    #Write-Host \"[$ServiceName]`n[$ServiceEXEPath]`n[$IndexOfSpace][$IndexOfEXE][$IndexOfQuote]`n[$NewPath]\"\n\n\t    Set-ItemProperty -LiteralPath \"HKLM:\\SYSTEM\\CurrentControlSet\\Services\\$ServiceName\" -Name ImagePath -Value $newpath\n\t  }\n    }\n"
      domain nil
      user nil
      not_if "    $Services = Get-WmiObject -Class Win32_Service
    
    	$Compliant = ""
    
    	$Services | % {
          #Check the path of each service, locate .exe in the path string, then check if any spaces in the path
    	  #Also check if any " in the path before the EXE.  If no " and a space exists, then its not compliant
    
    	  $ServiceName = $_.Name
    	  $ServiceEXEPath = $_.PathName
    
    	  $RegPath = (Get-itemproperty -LiteralPath "HKLM:\SYSTEM\CurrentControlSet\Services\$ServiceName").ImagePath
    
    	  $IndexOfSpace = $RegPath.IndexOf(" ")
    	  $IndexOfEXE   = $RegPath.IndexOf(".exe")
    	  $IndexOfQuote = $RegPath.IndexOf("`"")
    
    	  if (($IndexOfSpace -ne -1) -and ($IndexOfSpace -lt $IndexOfEXE) -and ($IndexOfQuote -ne 0))
    	  {
            $Compliant += "[$ServiceName][$ServiceEXEPath]`n"
    	  }
    	}
    
    	if ($Compliant -eq "")
    	{
    	  $Compliant = $True
    	}
    	else
    	{
    	  $Compliant = $False
    	}
    
    	return $Compliant
    "
    end
    
    System Info:
    ------------
    chef_version=16.4.41
    platform=windows
    platform_version=6.3.9600
    ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x64-mingw32]
    program_name=C:/opscode/chef/bin/chef-client
    executable=C:/opscode/chef/bin/chef-client
    
[2021-01-06T05:40:56-06:00] INFO: Running queued delayed notifications before re-raising exception
```

This leads to a bunch or orphaned PowerShell processes.
## Chef Version
16.4.41

## Platform Version
Windows server 2012 R2

## Replication Case
Once the issue starts it continues until the server is rebooted. After the reboot the chef client run normally.

**Comment by JohnnyBopper** [comment]
I'm currently seeing 7 other servers doing the same thing. All of them are 2012 R2 servers.

**Comment by tas50** [comment]
@JohnnyBopper We did a refactor of how `powershell_script` works so that it no longer actually shells out. Can you try this out on the latest release of Chef Infra Client. It should be resolved with that.

**Comment by JohnnyBopper** [comment]
Installed the release 16.9.32 and I no longer see this issue.
