### ISSUE TITLE
Cannot find a version for node

### ISSUE THREAD

**Issue by whyte624** [chef/chef#11393]
## Description

Chef client breaks with an error: Cannot find a version for node

## Chef Version
15.16.4
(Also tried with 16.4.41)

## Platform Version
Windows server 2016

## Replication Case

`chef-client -c C:/chef/client.rb`

or

`chef-client -c C:/chef/client.rb -j C:/chef/first-boot.json`

## Client Output
Starting Chef Infra Client, version 15.16.4
[2021-04-19T07:53:12+00:00] WARN: Plugin Network: unable to detect ipaddress

Running handlers:
[2021-04-19T07:53:22+00:00] ERROR: Running exception handlers
Running handlers complete
[2021-04-19T07:53:22+00:00] ERROR: Exception handlers complete
Chef Infra Client failed. 0 resources updated in 17 seconds
[2021-04-19T07:53:22+00:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
[2021-04-19T07:53:22+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2021-04-19T07:53:22+00:00] FATAL: ArgumentError: Cannot find a version for node

## Stacktrace
Generated at 2021-04-19 07:53:22 +0000
ArgumentError: Cannot find a version for node
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.16.4-universal-mingw32/lib/chef/platform/provider_mapping.rb:49:in `find_platform_and_version'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.16.4-universal-mingw32/lib/chef/node.rb:362:in `consume_external_attrs'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.16.4-universal-mingw32/lib/chef/policy_builder/expand_node_object.rb:135:in `build_node'
C:/opscode/chef/embedded/lib/ruby/2.6.0/forwardable.rb:230:in `build_node'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.16.4-universal-mingw32/lib/chef/client.rb:469:in `build_node'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.16.4-universal-mingw32/lib/chef/client.rb:273:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.16.4-universal-mingw32/lib/chef/application.rb:320:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.16.4-universal-mingw32/lib/chef/application.rb:296:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.16.4-universal-mingw32/lib/chef/local_mode.rb:42:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.16.4-universal-mingw32/lib/chef/application.rb:279:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.16.4-universal-mingw32/lib/chef/application/base.rb:330:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.16.4-universal-mingw32/lib/chef/application.rb:68:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-bin-15.16.4/bin/chef-client:25:in `<top (required)>'
C:/opscode/chef/bin/chef-client:162:in `load'
C:/opscode/chef/bin/chef-client:162:in `<main>'

**Comment by whyte624** [comment]
Seems like ohai does not return attributes:

https://github.com/chef/ohai/issues/1655

**Comment by whyte624** [comment]
https://github.com/chef/ohai/issues/1655
