### ISSUE TITLE
macOS builds failing with bundler error

### ISSUE THREAD

**Issue by tas50** [chef/chef#11415]
This is preventing us from shipping Chef Infra Client 17

```

3:  omnibus-software (4.0.0) from /Users/administrator/.buildkite-agent/builds/MM008-local-1/chef/chef-chef-master-omnibus-release/omnibus/vendor/bundle/ruby/2.7.0/bundler/gems/omnibus-software-0dcaeb194028/omnibus-software.gemspec

Bundle complete! 9 Gemfile dependencies, 45 gems now installed.

Gems in the group development were not installed.

Bundled gems are installed into `./vendor/bundle`

[31mbundler: failed to load command: omnibus (/Users/administrator/.buildkite-agent/builds/MM008-local-1/chef/chef-chef-master-omnibus-release/omnibus/vendor/bundle/ruby/2.7.0/bin/omnibus)[0m

[1mTraceback[m (most recent call last):

	25: from /opt/omnibus-toolchain/bin/bundle:23:in `<main>'

	24: from /opt/omnibus-toolchain/bin/bundle:23:in `load'

	23: from /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.7.0/gems/bundler-2.2.15/exe/bundle:37:in `<top (required)>'

	22: from /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/friendly_errors.rb:130:in `with_friendly_errors'

	21: from /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.7.0/gems/bundler-2.2.15/exe/bundle:49:in `block in <top (required)>'

	20: from /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:24:in `start'

	19: from /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'

	18: from /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:30:in `dispatch'

	17: from /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'

	16: from /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'

	15: from /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'

	14: from /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/cli.rb:494:in `exec'

	13: from /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:28:in `run'

	12: from /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:61:in `kernel_load'

	11: from /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/cli/exec.rb:61:in `require_relative'

	10: from /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/setup.rb:10:in `<top (required)>'

	 9: from /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/ui/shell.rb:88:in `silence'

	 8: from /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/ui/shell.rb:136:in `with_level'

	 7: from /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/setup.rb:10:in `block in <top (required)>'

	 6: from /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler.rb:148:in `setup'

	 5: from /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:26:in `setup'

	 4: from /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:26:in `map'

	 3: from /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/spec_set.rb:150:in `each'

	 2: from /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/spec_set.rb:150:in `each'

	 1: from /opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:31:in `block in setup'

/opt/omnibus-toolchain/embedded/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:302:in `check_for_activated_spec!': [1mYou have already activated bundler 2.2.15, but your Gemfile requires bundler 2.2.12. Since bundler is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports bundler as a default gem. ([1;4mGem::LoadError[m[1m)[m

[31m🚨 Error: The command exited with status 1[0m
```

**Comment by tas50** [comment]
Engineer time 1hr

**Comment by tduffield** [comment]
Resolution Steps

1. SSH into MacStadium instance
2. Run `/opt/omnibus-toolchain/bin/gem list bundler` to determine the offending `bundler` version
3. Delete the offending bundler gemspec
   ```
   rm /opt/omnibus-toolchain/embedded/lib/ruby/gems/2.7.0/specifications/default/bundler-<OFFENDING_VERSION>.gemspec
   ```
