### ISSUE TITLE
Habitat tests are failing

### ISSUE THREAD

**Issue by tas50** [chef/chef#11419]
```
[0m[0m[1m[35m≡ Binlinked rwinrmcp.bat from chef/chef-infra-client/17.0.217/20210421203443 to C:\hab/bin\rwinrmcp.bat[0m
[0m[0m[1m[33m» Binlinking setup.bat from chef/chef-infra-client/17.0.217/20210421203443 into C:\hab/bin[0m
[0m[0m[1m[35m≡ Binlinked setup.bat from chef/chef-infra-client/17.0.217/20210421203443 to C:\hab/bin\setup.bat[0m
[0m[0m[1m[33m» Binlinking thor.bat from chef/chef-infra-client/17.0.217/20210421203443 into C:\hab/bin[0m
[0m[0m[1m[35m≡ Binlinked thor.bat from chef/chef-infra-client/17.0.217/20210421203443 to C:\hab/bin\thor.bat[0m

An error occurred while loading ./spec/functional/dsl/reboot_pending_spec.rb.
Failure/Error: Win32.autoload :Registry, File.expand_path("../monkey_patches/win32/registry", __dir__)

NameError:
  uninitialized constant Win32
# ./lib/chef/win32/registry.rb:25:in `<top (required)>'
# ./spec/functional/dsl/reboot_pending_spec.rb:21:in `<top (required)>'
Run options:
  include {:focus=>true}
  exclude {:provider=>#<Proc: ./spec/spec_helper.rb:203>, :arch=>#<Proc: ./spec/spec_helper.rb:197>, :pwsh_installed=>true, :requires_ifconfig=>true, :ruby=>"2.7.2", :chef=>"17.0.217", :not_intel_64bit=>true, :rhel_gte_8=>true, :rhel8=>true, :rhel7=>true, :rhel6=>true, :rhel=>true, :not_wpar=>true, :broken=>true, :openssl_lt_101=>true, :requires_root=>true, :selinux_only=>true, :debian_family_only=>true, :opensuse=>true, :suse_only=>true, :aix_only=>true, :linux_only=>true, :unix_only=>true, :solaris_only=>true, :windows_service_requires_assign_token=>true, :windows_domain_joined_only=>true, :windows_powershell_no_dsc_only=>true, :ruby32_only=>true, :windows_lt_10=>true, :windows32_only=>true, :win2012r2_only=>true, :macos_only=>true, :not_supported_on_windows=>true, :skip_buildkite=>true, :volatile_from_verify=>false, :volatile=>true, :external=>true, :executables=>true, :choco_installed=>true}

All examples were filtered out; ignoring {:focus=>true}


Finished in 0.00005 seconds (files took 11.51 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

functional testing failed
At C:\bkf3d9993b\habitat\tests\spec.ps1:22 char:20
+     if (-not $?) { throw "functional testing failed"}
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (functional testing failed:String) [], RuntimeException
    + FullyQualifiedErrorId : functional testing failed
 
functional spec suite failed
At C:\bkf3d9993b\habitat\tests\test.ps1:23 char:16
+ if (-not $?) { throw "functional spec suite failed" }
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (functional spec suite failed:String) [], RuntimeException
    + FullyQualifiedErrorId : functional spec suite failed
 
[31m🚨 Error: The command exited with status 1[0m
^^^ +++
^^^ +++
~~~ Running global pre-exit hook
```

https://buildkite.com/chef/chef-chef-master-habitat-test/builds/753#f3d9993b-edea-4eb1-9a45-037e4b51ab78

**Comment by mwrock** [comment]
probably spent about an hour investigating and fixing via #11430
