### ISSUE TITLE
Development Tools no longer included in Chef Infra Client 17

### ISSUE THREAD

**Issue by rhys96** [chef/chef#11476]
## Description
I can no longer install Ruby Gems that require development tools using the `chef_gem` resource in a Windows Operating System using Chef Infra Client 17. The Ruby Gem installation still works in Chef Infra Client 16.13.16. Is this expected in the new release?

## Chef Version

```
Chef Infra Client Version 17.0.242
```

## Platform Version

```
Microsoft Windows Server 2019 Datacenter Version 10.0.17763 Build 17763
```

## Replication Case

For example, create the following resource:
```ruby
chef_gem 'azure_key_vault' do
  compile_time true
  action :install
end
```

## Client Output

```
Starting Chef Infra Client, version 17.0.242
       Patents: https://www.chef.io/patents
       Creating a new client identity for default-windows2019 using the validator key.
       Using policy 'demo' at revision 'b9b18f0b80dd2fa2988f6717bcff572f1ca7da910759b8f13f9bcf29b09f35ac'
       resolving cookbooks for run list: ["azure::default@0.0.3 (5ab1c33)", "demo::default@0.1.0 (06cd7b5)"]
       Synchronizing Cookbooks:
         - azure (0.0.3)
         - demo (0.1.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       [2021-04-29T11:55:03+00:00] WARN: Missing gem 'azure_key_vault'. Use the default recipe to install it before using Azure Key Vault functions.
       Recipe: azure::default
         * build_essential[Install compilation tools] action install[2021-04-29T11:55:03+00:00] WARN:         The build_essential resource does not currently support the 'windows'
        platform family. Skipping...

        (up to date)
         * chef_gem[azure_key_vault] action install

           ================================================================================
           Error executing action `install` on resource 'chef_gem[azure_key_vault]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of C:/opscode/chef/embedded/bin/gem install azure_key_vault -q --no-document -v "0.17.4" --source=https://rubygems.org ----
           STDOUT: Successfully installed timeliness-0.3.10

           Successfully installed ms_rest-0.7.6

           Building native extensions. This could take a while...
           STDERR: ERROR:  Error installing azure_key_vault:

                ERROR: Failed to build gem native extension.



        current directory: C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/unf_ext-0.0.7.7/ext/unf_ext

           C:/opscode/chef/embedded/bin/ruby.exe -I C:/opscode/chef/embedded/lib/ruby/3.0.0 -r ./siteconf20210429-1072-9hp9m3.rb extconf.rb

           checking for -lstdc++... *** extconf.rb failed ***

           Could not create Makefile due to some reason, probably lack of necessary

           libraries and/or headers.  Check the mkmf.log file for more details.  You may

           need configuration options.



           Provided configuration options:

                --with-opt-dir

                --without-opt-dir

                --with-opt-include

                --without-opt-include=${opt-dir}/include

                --with-opt-lib

                --without-opt-lib=${opt-dir}/lib

                --with-make-prog

                --without-make-prog

                --srcdir=.

                --curdir

                --ruby=C:/opscode/chef/embedded/bin/$(RUBY_BASE_NAME)

                --with-static-libstdc++

                --without-static-libstdc++

                --with-stdc++-dir

                --without-stdc++-dir

                --with-stdc++-include

                --without-stdc++-include=${stdc++-dir}/include

                --with-stdc++-lib

                --without-stdc++-lib=${stdc++-dir}/lib

                --with-stdc++lib

                --without-stdc++lib

           C:/opscode/chef/embedded/lib/ruby/3.0.0/mkmf.rb:482:in `try_do': The compiler failed to generate an executable file. (RuntimeError)

           You have to install development tools first.

                from C:/opscode/chef/embedded/lib/ruby/3.0.0/mkmf.rb:575:in `try_link0'

                from C:/opscode/chef/embedded/lib/ruby/3.0.0/mkmf.rb:593:in `try_link'

                from C:/opscode/chef/embedded/lib/ruby/3.0.0/mkmf.rb:812:in `try_func'

                from C:/opscode/chef/embedded/lib/ruby/3.0.0/mkmf.rb:1040:in `block in have_library'

                from C:/opscode/chef/embedded/lib/ruby/3.0.0/mkmf.rb:982:in `block in checking_for'

                from C:/opscode/chef/embedded/lib/ruby/3.0.0/mkmf.rb:361:in `block (2 levels) in postpone'

                from C:/opscode/chef/embedded/lib/ruby/3.0.0/mkmf.rb:331:in `open'

                from C:/opscode/chef/embedded/lib/ruby/3.0.0/mkmf.rb:361:in `block in postpone'

                from C:/opscode/chef/embedded/lib/ruby/3.0.0/mkmf.rb:331:in `open'

                from C:/opscode/chef/embedded/lib/ruby/3.0.0/mkmf.rb:357:in `postpone'

                from C:/opscode/chef/embedded/lib/ruby/3.0.0/mkmf.rb:981:in `checking_for'

                from C:/opscode/chef/embedded/lib/ruby/3.0.0/mkmf.rb:1035:in `have_library'

                from extconf.rb:6:in `<main>'



           To see why this extension failed to compile, please check the mkmf.log which can be found here:



             C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/extensions/x64-mingw32/3.0.0/unf_ext-0.0.7.7/mkmf.log



           extconf failed, exit code 1
```

**Comment by ramereth** [comment]
Chef 17 now ships with Ruby 3.0 so gems you install using `chef_gem` might not be compatible with Ruby 3.0 yet. I recommend you check on the gem you're trying to install and see if it is indeed ready for Ruby 3.0 yet.

**Comment by tas50** [comment]
Closing based on the comment from @ramereth. We ship the same set of tooling we shipped with Chef Infra Client 16.

**Comment by rhys96** [comment]
Sorry for the delay in responding. You're right @ramereth, the Azure gems stopped working with Chef 17 due to Ruby 3.0 incompatibility. Instead, I've created a set of libraries using in-built Ruby gems to remove the dependency on the Azure Resource Management SDK for Ruby.
