### ISSUE TITLE
yum helper failing in specs

### ISSUE THREAD

**Issue by tas50** [chef/chef#11514]
```

  1) Chef::Provider::Package::Yum::PythonHelper propagates stacktraces on stderr from the forked subprocess

     [31mFailure/Error: [0m[32mexpect[0m { helper.package_query([33m:whatprovides[0m, [31m[1;31m"[0m[31mtcpdump[1;31m"[0m[31m[0m) }.to raise_error([35m[1;35m/[0m[35myour hands in the air[1;35m/[0m[35m[0m)[0m

     [31m[0m

     [31m  expected /your hands in the air/, got #<RuntimeError: yum-helper.py had stderr/stdout output:[0m

     [31m[0m

     [31m  Traceback (most recent call last):[0m

     [31m    File "/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.11/lib/chef/provider/package/yum/yum_helper.py", line 201, in <module>[0m

     [31m      raise RuntimeError("bad command")[0m

     [31m  RuntimeError: bad command[0m

     [31m  > with backtrace:[0m

     [31m    # ./lib/chef/provider/package/yum/python_helper.rb:227:in `rescue in with_helper'[0m

     [31m    # ./lib/chef/provider/package/yum/python_helper.rb:204:in `with_helper'[0m

     [31m    # ./lib/chef/provider/package/yum/python_helper.rb:162:in `query'[0m

     [31m    # ./lib/chef/provider/package/yum/python_helper.rb:128:in `package_query'[0m

     [31m    # ./spec/unit/provider/package/yum/python_helper_spec.rb:27:in `block (3 levels) in <top (required)>'[0m

     [31m    # ./spec/unit/provider/package/yum/python_helper_spec.rb:27:in `block (2 levels) in <top (required)>'[0m

     [31m    # ./spec/spec_helper.rb:306:in `block (2 levels) in <top (required)>'[0m

     [36m# ./spec/unit/provider/package/yum/python_helper_spec.rb:27:in `block (2 levels) in <top (required)>'[0m

     [36m# ./spec/spec_helper.rb:306:in `block (2 levels) in <top (required)>'[0m
```

**Comment by tas50** [comment]
8hrs of time
