### ISSUE TITLE
Chef 17 fails to converge recipe when chef-splunk cookbook is included

### ISSUE THREAD

**Issue by eheydrick** [chef/chef#11528]
## Description

I am unable to converge a simple recipe with Chef 17 that works with Chef 16. It happens when the  [chef-splunk](https://github.com/sous-chefs/chef-splunk) cookbook is being used. The issue appears to be related to the [`systemd?` helper](https://github.com/sous-chefs/chef-splunk/blob/607a1f120465c197cc16ffa10c5225f37a489132/libraries/helpers.rb#L271-L273) in the chef-splunk cookbook. I checked the release notes for any breaking changes that would explain this but didn't see anything relevant.

## Chef Version

Works = 16.13.16
Does not work = 17.0.242

## Platform Version

Debian 10

## Replication Case

I have provided a cookbook that can reproduce the issue at https://github.com/eheydrick/chef17. The kitchen config will create Chef 16 and 17 nodes.

## Client Output

```
Recipe: chef17::default
  * service[cron] action enable
    
    ================================================================================
    Error executing action `enable` on resource 'service[cron]'
    ================================================================================
    
    NameError
    ---------
    undefined local variable or method `node' for Chef::Provider::Service::Systemd:Class
    
    Cookbook Trace: (most recent call first)
    ----------------------------------------
    /opt/kitchen/cache/cookbooks/chef-splunk/libraries/helpers.rb:272:in `systemd?'
    
    Resource Declaration:
    ---------------------
    # In /opt/kitchen/cache/cookbooks/chef17/recipes/default.rb
    
      7: service 'cron' do
      8:   action [:enable]
      9: end
    
    Compiled Resource:
    ------------------
    # Declared in /opt/kitchen/cache/cookbooks/chef17/recipes/default.rb:7:in `from_file'
    
    service("cron") do
      action [:enable]
      default_guard_interpreter :default
      declared_type :service
      cookbook_name "chef17"
      recipe_name "default"
      supports {:restart=>nil, :reload=>nil, :status=>nil}
    end
    
    System Info:
    ------------
    chef_version=17.0.242
    platform=debian
    platform_version=10
    ruby=ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
    program_name=/opt/chef/bin/chef-client
    executable=/opt/chef/bin/chef-client
    

Running handlers:
[2021-05-06T05:00:09+00:00] ERROR: Running exception handlers
Running handlers complete
[2021-05-06T05:00:09+00:00] ERROR: Exception handlers complete
Chef Infra Client failed. 0 resources updated in 03 seconds
[2021-05-06T05:00:09+00:00] FATAL: Stacktrace dumped to /opt/kitchen/cache/chef-stacktrace.out
[2021-05-06T05:00:09+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2021-05-06T05:00:09+00:00] FATAL: NameError: service[cron] (chef17::default line 7) had an error: NameError: undefined local variable or method `node' for Chef::Provider::Service::Systemd:Class
```

## Stacktrace

```Generated at 2021-05-06 05:09:38 +0000
NameError: service[cron] (chef17::default line 7) had an error: NameError: undefined local variable or method `node' for Chef::Provider::Service::Systemd:Class
/opt/kitchen/cache/cookbooks/chef-splunk/libraries/helpers.rb:272:in `systemd?'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/provider/service/systemd.rb:30:in `block in <class:Systemd>'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/node_map.rb:276:in `block_matches?'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/node_map.rb:282:in `node_matches?'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/node_map.rb:144:in `block in list'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/node_map.rb:143:in `select'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/node_map.rb:143:in `list'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/provider_resolver.rb:86:in `potential_handlers'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/provider_resolver.rb:73:in `enabled_handlers'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/provider_resolver.rb:121:in `maybe_dynamic_provider_resolution'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/provider_resolver.rb:62:in `resolve'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/resource.rb:1530:in `provider_for_action'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/resource.rb:599:in `block in run_action'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/resource.rb:626:in `with_umask'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/resource.rb:598:in `run_action'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/runner.rb:74:in `run_action'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/runner.rb:108:in `each'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/runner.rb:132:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/3.0.0/forwardable.rb:238:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/runner.rb:130:in `converge'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/client.rb:687:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/client.rb:682:in `catch'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/client.rb:682:in `converge'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/client.rb:706:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/client.rb:286:in `run'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/application.rb:281:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/application.rb:264:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/application/base.rb:337:in `run_application'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242/lib/chef/application.rb:67:in `run'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-bin-17.0.242/bin/chef-client:25:in `<top (required)>'
/opt/chef/bin/chef-client:147:in `load'
/opt/chef/bin/chef-client:147:in `<main>'```

**Comment by ramereth** [comment]
I think this is really a chef-splunk cookbook issue. @lamont-granquist @damacus  feel free to transfer this over to Sous Chefs if I am correct.

**Comment by eheydrick** [comment]
@ramereth I agree I don't think chef-splunk should define its own `systemd?` helper. But it also seems like the cookbook helper being used over the built-in helper is a change in behavior from Chef 16.

I was able to work around this by monkeypatching chef-splunk's method to use the built-in one instead: 

```module ChefSplunk
  module Helpers
    def systemd?
      super
    end
  end
end
```

**Comment by damacus** [comment]
Agreed @ramereth this looks like chef-splunk misbehaving.

**Comment by tas50** [comment]
This was fixed in 17.1 I believe

**Comment by ramereth** [comment]
@tas50 what was the specific fix?

**Comment by haidangwa** [comment]
the chef-splunk cookbook doesn't claim to support Chef 17 yet -- this and a few other issues should be taken up as a single PR in chef-splunk to upgrade the cookbook for chef17.
