### ISSUE TITLE
knife upload errors out with "undefined method `parallel_each'"

### ISSUE THREAD

**Issue by ramereth** [chef/chef#11558]
## Description
Running a variety of `knife upload` commands result in a `undefined method `parallel_each'` error and fails. I believe this is related to #11397. I'm not sure if this is because Workstation is still using Ruby 2.7 and 3.0 yet or not. 

## Chef Version
17.0.242
## Platform Version
CentOS 7

## Replication Case
```
knife upload data_bags -d --purge
```

## Client Output

```
ERROR: knife encountered an unexpected error
This may be a bug in the 'upload' knife command or plugin
Please collect the output of this command with the `-VVV` option before filing a bug report.
Exception: NoMethodError: undefined method `parallel_each' for #<Array:0x0000000002a810e0>
```

## Stacktrace
```
Traceback (most recent call last):
        15: from /opt/cinc-workstation/embedded/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'
        14: from /opt/cinc-workstation/embedded/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'
        13: from /opt/cinc-workstation/embedded/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_worker'
        12: from /opt/cinc-workstation/embedded/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'
        11: from /opt/cinc-workstation/embedded/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker'
        10: from /opt/cinc-workstation/embedded/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'
         9: from /opt/cinc-workstation/embedded/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/future.rb:55:in `block in execute'
         8: from /opt/cinc-workstation/embedded/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/ivar.rb:169:in `safe_execute'
         7: from /opt/cinc-workstation/embedded/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:19:in `execute'
         6: from /opt/cinc-workstation/embedded/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
         5: from /opt/cinc-workstation/embedded/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:41:in `synchronize'
         4: from /opt/cinc-workstation/embedded/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:41:in `block in synchronize'
         3: from /opt/cinc-workstation/embedded/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
         2: from /opt/cinc-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-utils-17.0.242/lib/chef-utils/parallel_map.rb:49:in `block (2 levels) in parallel_map'
         1: from /opt/cinc-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-17.0.242/lib/chef/chef_fs/file_system.rb:146:in `block in copy_to'
/opt/cinc-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-17.0.242/lib/chef/chef_fs/file_system.rb:361:in `copy_entries': undefined method `parallel_each' for #<Array:0x0000000001d3e1d0> (NoMethodError)
```

**Comment by tas50** [comment]
This is probably going to need to wait until lamont is back

**Comment by lamont-granquist** [comment]
yep.

**Comment by lamont-granquist** [comment]
Uh yeah, this is probably because chef-client/knife 17 is being shipped on top of ruby 2.7 and that is broken because ruby itself broke refinements in 2.7 and didn't fix the bug until 3.0 -- once i determined that though i figured that was fine since 17 should only be running on 3.0

**Comment by ramereth** [comment]
I believe the problem is that chef-workstation is still only shipping 2.7 AFAIK.

**Comment by lamont-granquist** [comment]
Yep, upgrading ruby to 3.0 in workstation should have been a blocker to shipping chef-workstation

**Comment by Dylan-M** [comment]
So is there an ETA on this being fixed? :)

I'm part of a 2 man show for deploying all of the development environments at my company, and we depend heavily on Chef to automate that process.

Thank you.

**Comment by ramereth** [comment]
@Dylan-M I think it's mostly on getting https://github.com/chef/chef-workstation/pull/2010 merged and a new release cut. @lamont-granquist or @tas50 can correct me if I'm wrong.

**Comment by tas50** [comment]
Yes we will probably have a fix for a few issues in know coming up and then we'll have a further release with the Ruby 3 work.

**Comment by mkennedy85** [comment]
I believe this is the issue I am facing and it seems to have broken CI across all of our cookbooks as we grab `chef/chefworkstation` (implicitly latest). Do we know when this is expected to be resolved? This carries a big impact for me as I am unable to leverage CI for our cookbook development which includes pushing new cookbooks to Chef Server.

```
     Created /data_bags
     ERROR: knife encountered an unexpected error
     This may be a bug in the 'download' knife command or plugin
     Please collect the output of this command with the `-VVV` option before filing a bug report.
     Exception: NoMethodError: undefined method `parallel_each' for #<Array:0x000055adc3292c20>
```

**Comment by DmitriyStoyanov** [comment]
Looks like issue related to upgrade ruby to 3.0 still valid, or something like that.
Faced with similar error:
```ruby
knife show nodes -VVV
INFO: Using configuration from C:/Users/user/.chef/knife.rb
Traceback (most recent call last):
        9: from C:/opscode/chef-workstation/bin/knife:378:in `<main>'
        8: from C:/opscode/chef-workstation/bin/knife:378:in `load'
        7: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.2.18/bin/knife:24:in `<top (required)>'
        6: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.2.18/lib/chef/application/knife.rb:165:in `run'
        5: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.2.18/lib/chef/knife.rb:233:in `run'
        4: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.2.18/lib/chef/knife.rb:493:in `run_with_pretty_exceptions'
        3: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-17.1.35-universal-mingw32/lib/chef/local_mode.rb:42:in `with_server_connectivity'
        2: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.2.18/lib/chef/knife.rb:494:in `block in run_with_pretty_exceptions'
        1: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.2.18/lib/chef/knife/show.rb:39:in `run'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.2.18/lib/chef/chef_fs/knife.rb:145:in `parallelize': undefined method `parallel_map' for #<Array:0x0000000008ed6f68> (NoMethodError)
```
on latest 21.6.467 chef-workstation on windows

**Comment by ramereth** [comment]
@DmitriyStoyanov Chef Workstation 21.6.497 should have the fix you need AFAIK.

**Comment by tas50** [comment]
Yep this was fixed. Closing this one out.

**Comment by DmitriyStoyanov** [comment]
Yes, I've tested with 21.6.497 version, and all looks fine now, thank you.

**Comment by slabstone** [comment]
I'm having the same problem with Ruby 2.7.8 and `chef` and `knife` installed manually as gems. Latest 17 version of `chef` gem is `17.10.0` and it requires Ruby `>= 2.6.0`

https://github.com/chef/chef/blob/097eb843df5c1df12179da49b13a78e854b9677f/chef.gemspec#L25

Is this an oversight?

Downgrading `chef` gem to `16.18.30` solved the problem.
