### ISSUE TITLE
AIX builds failing with git failure

### ISSUE THREAD

**Issue by tas50** [chef/chef#11555]
```
Fetching https://github.com/chef/omnibus.git

fatal: unable to access 'https://github.com/chef/omnibus.git/': error setting certificate verify locations:

  CAfile: /opt/omnibus-toolchain/embedded/ssl/certs/cacert.pem

  CApath: none

Retrying `git clone 'https://github.com/chef/omnibus.git' "/home/jenkins/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/cache/bundler/git/omnibus-dae08cbdfc40f037c88b5de320377a72807a8770" --bare --no-hardlinks --quiet` due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'https://github.com/chef/omnibus.git' "/home/jenkins/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/cache/bundler/git/omnibus-dae08cbdfc40f037c88b5de320377a72807a8770" --bare --no-hardlinks --quiet` in directory /home/jenkins/buildkite-workspace/omnibus has failed.

Retrying `git clone 'https://github.com/chef/omnibus.git' "/home/jenkins/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/cache/bundler/git/omnibus-dae08cbdfc40f037c88b5de320377a72807a8770" --bare --no-hardlinks --quiet` due to error (3/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'https://github.com/chef/omnibus.git' "/home/jenkins/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/cache/bundler/git/omnibus-dae08cbdfc40f037c88b5de320377a72807a8770" --bare --no-hardlinks --quiet` in directory /home/jenkins/buildkite-workspace/omnibus has failed.

Retrying `git clone 'https://github.com/chef/omnibus.git' "/home/jenkins/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/cache/bundler/git/omnibus-dae08cbdfc40f037c88b5de320377a72807a8770" --bare --no-hardlinks --quiet` due to error (4/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'https://github.com/chef/omnibus.git' "/home/jenkins/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/cache/bundler/git/omnibus-dae08cbdfc40f037c88b5de320377a72807a8770" --bare --no-hardlinks --quiet` in directory /home/jenkins/buildkite-workspace/omnibus has failed.

Git error: command `git clone 'https://github.com/chef/omnibus.git'

"/home/jenkins/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/cache/bundler/git/omnibus-dae08cbdfc40f037c88b5de320377a72807a8770"

--bare --no-hardlinks --quiet` in directory

/home/jenkins/buildkite-workspace/omnibus has failed.

Bundler::Source::Git::GitCommandError: Git error: command `git clone 'https://github.com/chef/omnibus.git' "/home/jenkins/buildkite-workspace/omnibus/vendor/bundle/ruby/2.6.0/cache/bundler/git/omnibus-dae08cbdfc40f037c88b5de320377a72807a8770" --bare --no-hardlinks --quiet` in directory /home/jenkins/buildkite-workspace/omnibus has failed.

/opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/source/git/git_proxy.rb:181:in `git'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/source/git/git_proxy.rb:168:in `block in git_retry'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/retry.rb:40:in `run'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/retry.rb:30:in `attempt'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/source/git/git_proxy.rb:167:in `git_retry'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/source/git/git_proxy.rb:107:in `checkout'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/source/git.rb:308:in `fetch'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/source/git.rb:162:in `specs'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/lazy_specification.rb:75:in `__materialize__'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/spec_set.rb:83:in `block in materialize'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/spec_set.rb:80:in `map!'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/spec_set.rb:80:in `materialize'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:170:in `specs'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/definition.rb:158:in `resolve_remotely!'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/installer.rb:303:in `resolve_if_needed'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/installer.rb:84:in `block in run'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/process_lock.rb:12:in `block in lock'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/process_lock.rb:9:in `open'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/process_lock.rb:9:in `lock'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/installer.rb:73:in `run'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/installer.rb:25:in `install'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/cli/install.rb:66:in `run'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:256:in `block in install'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/settings.rb:124:in `temporary'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:255:in `install'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:30:in `dispatch'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:24:in `start'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/site_ruby/2.6.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'

  /opt/angry-omnibus-toolchain/embedded/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'

  /opt/angry-omnibus-toolchain/bin/bundle:23:in `load'

  /opt/angry-omnibus-toolchain/bin/bundle:23:in `<main>'
```

**Comment by tas50** [comment]
New WPARs updated. 1 hr engineering time
