### ISSUE TITLE
knife ssl fetch broken with bad require call in ssl_fetch.rb

### ISSUE THREAD

**Issue by Dylan-M** [chef/chef#11580]
## Description
knife ssl fetch does not work due to a bad require

## Chef Version
```
% chef --version
Chef Workstation version: 21.5.420
Chef Infra Client version: 17.0.242
Chef InSpec version: 4.36.4
Chef CLI version: 5.0.1
Chef Habitat version: 1.6.288
Test Kitchen version: 2.11.2
Cookstyle version: 7.10.1
```

## Platform Version
OSX Big Sur 11.4
 % uname -a
Darwin <redacted> 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64

## Replication Case
Install fresh. Configure for a server with a self signed certificate. Run knife ssl fetch.

## Client Output
```
% knife ssl fetch                                  
Traceback (most recent call last):
	9: from /usr/local/bin/knife:357:in `<main>'
	8: from /usr/local/bin/knife:357:in `load'
	7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/bin/knife:24:in `<top (required)>'
	6: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/lib/chef/application/knife.rb:165:in `run'
	5: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/lib/chef/knife.rb:230:in `run'
	4: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/lib/chef/knife.rb:245:in `load_deps'
	3: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/lib/chef/knife.rb:245:in `each'
	2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/lib/chef/knife/ssl_fetch.rb:31:in `block in <class:SslFetch>'
	1: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- chef/mixin/mixin/proxified_socket (LoadError)
```

## Stacktrace
```
Traceback (most recent call last):
	9: from /usr/local/bin/knife:357:in `<main>'
	8: from /usr/local/bin/knife:357:in `load'
	7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/bin/knife:24:in `<top (required)>'
	6: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/lib/chef/application/knife.rb:165:in `run'
	5: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/lib/chef/knife.rb:230:in `run'
	4: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/lib/chef/knife.rb:245:in `load_deps'
	3: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/lib/chef/knife.rb:245:in `each'
	2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-17.0.246/lib/chef/knife/ssl_fetch.rb:31:in `block in <class:SslFetch>'
	1: from /opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
/opt/chef-workstation/embedded/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- chef/mixin/mixin/proxified_socket (LoadError)
```

**Comment by lamont-granquist** [comment]
looks fixed
