### ISSUE TITLE
Systemd services can't be enabled or disabled in a chroot environment with Chef 17

### ISSUE THREAD

**Issue by rarenerd** [chef/chef#11750]
## Description
Using Chef 17 it's no longer possible to manage Systemd services within a chroot environment (e.g. in RHEL Kickstart post scripts) anymore.

```
Recipe: chrony_ii::service
  * service[chrony-daemon] action enable

  ================================================================================
  Error executing action `enable` on resource 'service[chrony-daemon]'
  ================================================================================

  Chef::Exceptions::Service
  -------------------------
  '/usr/bin/systemctl show' not reporting status for chronyd!

  Resource Declaration:
  ---------------------
  # In /var/chef/cache/cookbooks/chrony_ii/recipes/service.rb

   29: service 'chrony-daemon' do
   30:   service_name value_for_platform_family(
   31:     'rhel' => 'chronyd',
   32:     'amazon' => 'chronyd',
   33:     'debian' => 'chrony'
   34:   )
   35:   supports restart: true, status: true, reload: true
   36:   action %i[enable start]
   37: end
```

With Chef 17 the `systemd_service_status` method was introduced which uses `systemctl show` to determine the current state of the service (https://github.com/chef/chef/blob/master/lib/chef/provider/service/systemd.rb#L83).
However unlike the previously used `is-enabled` for example, `systemctl show` refuses to run in a chrooted environment as the Systemd daemon runs outside of that environment.

```
[anaconda root@kstest ~]# chroot /mnt /sysroot
[anaconda root@kstest /]# systemctl show chronyd
Running in chroot, ignoring request: show
```

## Chef Version
>= 17.0

## Platform Version
CentOS 8 (and any RHEL derivative using Kickstart)

## Replication Case
In a Kickstart configuration provide a `%post --interpreter=/bin/bash` section that installs Chef Infra 17, configures it and runs `chef-client` with for example `chrony_ii::default` (https://supermarket.chef.io/cookbooks/chrony_ii) on the run list.

## Client Output
See description

**Comment by r4han85** [comment]
This bug is also present in CentOS Linux release 7.9.2009 (Core) :
Chef::Exceptions::MultipleFailures: Chef::Exceptions::MultipleFailures
/opt/chef-17.8.25/embedded/lib/ruby/gems/3.0.0/gems/chef-17.8.25/lib/chef/provider/service/systemd.rb:96:in `systemd_service_status'
>>>> Caused by Chef::Exceptions::Service: '/usr/bin/systemctl show' not reporting status for sshd!
/opt/chef-17.8.25/embedded/lib/ruby/gems/3.0.0/gems/chef-17.8.25/lib/chef/provider/service/systemd.rb:96:in `systemd_service_status'

**Comment by sameerjethvani-alation** [comment]
Is there any update ?

**Comment by r4han85** [comment]
Hello,

I've noticed that bug remains in chef-client 18.2

Étienne Mollet

Le lun. 5 juin 2023 à 10:11, Sameer Jethvani ***@***.***> a
écrit :

**Comment by euthuppan** [comment]
We are having this same problem on chef-client 18.2.7.

Our kickstart script can't run any service resources without failing..

**Comment by nrgetik** [comment]
> Because post-install script runs in a chroot environment, most systemctl commands will refuse to perform any action.

From https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/performing_an_advanced_rhel_8_installation/index#post-script-in-kickstart-file_scripts-in-kickstart-file

The changes from 16.x to 17.x present here: https://github.com/chef/chef/blob/v17.10.130/lib/chef/provider/service/systemd.rb#L204-L214

And here: https://github.com/chef/chef/blob/v17.10.130/lib/chef/provider/service/systemd.rb#L79-L101

Seem to indicate that the switch from `enabled-runtime` to `systemctl show` was intentional, for stability reasons.

**Comment by petesisk** [comment]
Any update on this issue?
Does anyone have any workarounds?

**Comment by Stromweld** [comment]
Since it was an intentional change to make the resource more reliable the only way to revert it is to write a library that monkey patches it back to the original pattern. Even better would be to monkey patch if detected to be running in chroot environment.

**Comment by lytao** [comment]
An easy workaround is to replace the provider file with the one from Chef Infra Client 16:

```bash
curl -o "${CHEF_CLIENT_DIR}/lib/chef/provider/service/systemd.rb" \
  https://raw.githubusercontent.com/chef/chef/chef-16/lib/chef/provider/service/systemd.rb
```

or probably make a trick to run chef-client after reboot.
