### ISSUE TITLE
Unable to bootstrap Windows 2019 nodes 

### ISSUE THREAD

**Issue by sanga1794** [chef/chef#11796]
## Description
Customer bug: https://github.com/chef/customer-bugs/issues/424

 get the following when trying to bootstrap a Windows 2019 node:

PS C:\CvChef\EsRepo\cookbooks> knife bootstrap -o winrm 10.20.0.4 -U azureuser -P xxx –node-name cvmstgne02 -VVV

INFO: Using configuration from C:/CvChef/EsRepo/.chef/config.rb

DEBUG: Checking if we need to accept Chef license to bootstrap node

DEBUG: Reading products and relationships…

DEBUG: Successfully read products and relationships

DEBUG: License acceptance required for chef version: 16

DEBUG: Searching for the following licenses: [“infra-client”, “inspec”]

DEBUG: Found license chef_infra_client at C:/Users/umanas/.chef/accepted_licenses/chef_infra_client

DEBUG: Found license inspec at C:/Users/umanas/.chef/accepted_licenses/inspec

DEBUG: Missing licenses remaining: []

DEBUG: All licenses present

Connecting to 10.20.0.4 using winrm

DEBUG: winrm-fs requested, loading WinRM::FS gem (~> 1.0)

DEBUG: winrm-fs library loaded

DEBUG: winrm-elevated requested, loading WinRM-elevated gem (~> 1.2.2)

DEBUG: winrm-elevated previously loaded

DEBUG: [WinRM] @10.20.0.4<{:transport=>:negotiate, :disable_sspi=>false, :basic_auth_only=>false, :endpoint=>”http://10.20.0.4:5985/wsman”, :user=>”azureuser”, :password=>””, :no_ssl_peer_verification=>false, :realm=>nil, :service=>nil, :ca_trust_file=>nil, :ssl_peer_fingerprint=>nil}> (Write-Host ‘[WinRM] Established

‘)

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

DEBUG: [WinRM] opening remote shell on http://10.20.0.4:5985/wsman

Traceback (most recent call last):

    18: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context’

    17: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/train-winrm-0.2.12/lib/train-winrm/connection.rb:127:in `block in run_command_via_connection’

    16: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/winrm-2.3.6/lib/winrm/shells/base.rb:79:in `run’

    15: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/winrm-2.3.6/lib/winrm/shells/base.rb:128:in `with_command_shell’

    14: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/winrm-2.3.6/lib/winrm/shells/base.rb:168:in `open’

    13: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/winrm-2.3.6/lib/winrm/shells/retryable.rb:35:in `retryable’

    12: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/winrm-2.3.6/lib/winrm/shells/base.rb:170:in `block in open’

    11: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:123:in `open_shell’

    10: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:166:in `open_shell_payload’

     9: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:166:in `map’

     8: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:167:in `block in open_shell_payload’

     7: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:203:in `fragmenter’

     6: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:78:in `max_fragment_blob_size’

     5: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/winrm-2.3.6/lib/winrm/shells/power_shell.rb:153:in `max_envelope_size_kb’

     4: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/winrm-2.3.6/lib/winrm/http/transport.rb:181:in `send_request’

     3: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/winrm-2.3.6/lib/winrm/http/transport.rb:186:in `send_request’

     2: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/winrm-2.3.6/lib/winrm/http/response_handler.rb:34:in `parse_to_xml’

     1: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/winrm-2.3.6/lib/winrm/http/response_handler.rb:51:in `raise_if_error’
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/winrm-2.3.6/lib/winrm/http/response_handler.rb:59:in `raise_if_auth_error’: WinRM::WinRMAuthorizationError (WinRM::WinRMAuthorizationError)

## Replication Case
Trying to bootstrap a Windows 2019 node.
I did it & attaching the log file

## Client Output

```

```

**Comment by sanga1794** [comment]
Closing this issue as customer haven't responding to our queries as issue is not able to reproduce on latest versions.
