### ISSUE TITLE
`windows_certificate`  resource's `:delete` action (when no cert present) fails on v17 client

### ISSUE THREAD

**Issue by ChefAustin** [chef/chef#11994]
## Description
The issue I am seeing is with the `windows_certificate` resource. Specifically, the issue occurs when one tries to `:delete` a certificate in the `'ROOT'` certificate store (but other cert stores may be affected as well) when the certificate does not exist. Rather than Chef client proceeding with the run (because it doesn’t need to do anything with the certificate [because it does not exist]), the client run fails with `ArgumentError: Unable to retrieve the certificate (ArgumentError)`. 

## Chef Version
- Fails on v17.4.38
- Fails on v17.0.242
- Succeeds on v16.14.1
- Succeeds on v16.13.16

## Platform Version
Microsoft Windows 10 21H1 (OS Build 19043.1202)

## Replication Case
Use `windows_certificate` resource (supply `source` thumbprint, and `store_name` of `'ROOT'` to attempt deletion of a certificate which does not exist in the store.

## Client Output
**Failure case (v17.0.242):**
```
chef (17.0.242)> recipe_mode
irb: warn: can't alias ls from irb_ls.
chef:recipe > windows_certificate 'Remove SennCom Certificate - ROOT' do
chef:recipe >   source '1990649205b55eab5d692e9edb1be0ddd3b037de'
chef:recipe >   action :delete
chef:recipe >   store_name 'ROOT'
chef:recipe (17.0.242)> end
 => <windows_certificate[Remove SennCom Certificate - ROOT] @name: "Remove SennCom Certificate - ROOT" @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :create, :acl_add, :delete, :fetch, :verify] @action: [:delete] @updated: false @updated_by_last_action: false @source_line: "(irb#1):1:in `<main>'" @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @declared_type: :windows_certificate @cookbook_name: nil @recipe_name: nil @source: "1990649205b55eab5d692e9edb1be0ddd3b037de" @store_name: "ROOT">
chef:recipe (17.0.242)> run_chef
[2021-09-03T14:04:39+02:00] INFO: Processing windows_certificate[Remove SennCom Certificate - ROOT] action delete ((irb#1) line 1)

================================================================================
Error executing action `delete` on resource 'windows_certificate[Remove SennCom Certificate - ROOT]'
================================================================================

ArgumentError
-------------
Unable to retrieve the certificate

Resource Declaration:
---------------------


Compiled Resource:
------------------
# Declared in (irb#1):1:in `<main>'

windows_certificate("Remove SennCom Certificate - ROOT") do
  action [:delete]
  default_guard_interpreter :default
  declared_type :windows_certificate
  source "1990649205b55eab5d692e9edb1be0ddd3b037de"
  store_name "ROOT"
end

System Info:
------------
chef_version=17.0.242
platform=windows
platform_version=10.0.19043
ruby=ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x64-mingw32]
program_name=C:/opscode/chef/bin/chef-shell
executable=C:/opscode/chef/embedded/lib/ruby/3.0.0/irb/ext/multi-irb.rb

[2021-09-03T14:04:40+02:00] INFO: Running queued delayed notifications before re-raising exception
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/win32-certstore-0.6.2/lib/win32/certstore/store_base.rb:96:in `cert_get': windows_certificate[Remove SennCom Certificate - ROOT] ((irb#1) line 1) had an error: ArgumentError: Unable to retrieve the certificate (ArgumentError)
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/win32-certstore-0.6.2/lib/win32/certstore.rb:78:in `get'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242-universal-mingw32/lib/chef/resource/windows_certificate.rb:199:in `fetch_cert'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242-universal-mingw32/lib/chef/resource/windows_certificate.rb:132:in `block in <class:WindowsCertificate>'
        from (eval):2:in `block in action_delete'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242-universal-mingw32/lib/chef/provider.rb:276:in `instance_eval'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242-universal-mingw32/lib/chef/provider.rb:276:in `compile_and_converge_action'
        from (eval):2:in `action_delete'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242-universal-mingw32/lib/chef/provider.rb:217:in `run_action'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242-universal-mingw32/lib/chef/resource.rb:599:in `block in run_action'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242-universal-mingw32/lib/chef/resource.rb:626:in `with_umask'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242-universal-mingw32/lib/chef/resource.rb:598:in `run_action'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242-universal-mingw32/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.0.242-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
        ... 4 levels...
chef:recipe (17.0.242)> exit
```

Failure case (v17.4.38):
```
chef (17.4.38)> recipe_mode
irb: warn: can't alias ls from irb_ls.
chef:recipe > windows_certificate 'Remove SennCom Certificate - ROOT' do
chef:recipe >   source '1990649205b55eab5d692e9edb1be0ddd3b037de'
chef:recipe >   action :delete
chef:recipe >   store_name 'ROOT'
chef:recipe (17.4.38)> end
 => <windows_certificate[Remove SennCom Certificate - ROOT] @name: "Remove SennCom Certificate - ROOT" @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :create, :acl_add, :delete, :fetch, :verify] @action: [:delete] @updated: false @updated_by_last_action: false @source_line: "(irb#1):1:in `<main>'" @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @declared_type: :windows_certificate @cookbook_name: nil @recipe_name: nil @source: "1990649205b55eab5d692e9edb1be0ddd3b037de" @store_name: "ROOT">
chef:recipe (17.4.38)> run_chef
[2021-09-03T10:48:26+02:00] INFO: Processing windows_certificate[Remove SennCom Certificate - ROOT] action delete ((irb#1) line 1)

================================================================================
Error executing action `delete` on resource 'windows_certificate[Remove SennCom Certificate - ROOT]'
================================================================================

ArgumentError
-------------
Unable to retrieve the certificate

Resource Declaration:
---------------------


Compiled Resource:
------------------
# Declared in (irb#1):1:in `<main>'

windows_certificate("Remove SennCom Certificate - ROOT") do
  action [:delete]
  default_guard_interpreter :default
  declared_type :windows_certificate
  source "1990649205b55eab5d692e9edb1be0ddd3b037de"
  store_name "ROOT"
end

System Info:
------------
chef_version=17.4.38
platform=windows
platform_version=10.0.19043
ruby=ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x64-mingw32]
program_name=C:/opscode/chef/bin/chef-shell
executable=C:/opscode/chef/embedded/lib/ruby/3.0.0/irb/ext/multi-irb.rb

[2021-09-03T10:48:26+02:00] INFO: Running queued delayed notifications before re-raising exception
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/win32-certstore-0.6.2/lib/win32/certstore/store_base.rb:96:in `cert_get': windows_certificate[Remove SennCom Certificate - ROOT] ((irb#1) line 1) had an error: ArgumentError: Unable to retrieve the certificate (ArgumentError)
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/win32-certstore-0.6.2/lib/win32/certstore.rb:78:in `get'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.4.38-universal-mingw32/lib/chef/resource/windows_certificate.rb:199:in `fetch_cert'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.4.38-universal-mingw32/lib/chef/resource/windows_certificate.rb:132:in `block in <class:WindowsCertificate>'
        from (eval):2:in `block in action_delete'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.4.38-universal-mingw32/lib/chef/provider.rb:301:in `instance_eval'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.4.38-universal-mingw32/lib/chef/provider.rb:301:in `compile_and_converge_action'
        from (eval):2:in `action_delete'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.4.38-universal-mingw32/lib/chef/provider.rb:242:in `run_action'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.4.38-universal-mingw32/lib/chef/resource.rb:600:in `block in run_action'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.4.38-universal-mingw32/lib/chef/resource.rb:627:in `with_umask'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.4.38-universal-mingw32/lib/chef/resource.rb:599:in `run_action'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.4.38-universal-mingw32/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.4.38-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.4.38-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.4.38-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
        from C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.4.38-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
        ... 4 levels...
chef:recipe (17.4.38)>
```

**Success case (16.13.16):**
```
chef (16.13.16)> recipe_mode
chef:recipe > windows_certificate 'Remove SennCom Certificate - ROOT' do
chef:recipe > source '1990649205b55eab5d692e9edb1be0ddd3b037de'
chef:recipe > action :delete
chef:recipe > store_name 'ROOT'
chef:recipe (16.13.16)> end
 => <windows_certificate[Remove SennCom Certificate - ROOT] @name: "Remove SennCom Certificate - ROOT" @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :create, :acl_add, :delete, :fetch, :verify] @action: [:delete] @updated: false @updated_by_last_action: false @source_line: "(irb#1):1:in `irb_binding'" @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @declared_type: :windows_certificate @cookbook_name: nil @recipe_name: nil @source: "1990649205b55eab5d692e9edb1be0ddd3b037de" @store_name: "ROOT">
chef:recipe (16.13.16)> run_chef
[2021-09-03T11:00:05+02:00] INFO: Processing windows_certificate[Remove SennCom Certificate - ROOT] action delete ((irb#1) line 1)
[2021-09-03T11:00:05+02:00] DEBUG: Certificate not found
 => true
chef:recipe (16.13.16)>
```

**Success case (16.14.1):**
```
chef (16.14.1)> recipe_mode
chef:recipe > windows_certificate 'Remove SennCom Certificate - ROOT' do
chef:recipe > source '1990649205b55eab5d692e9edb1be0ddd3b037de'
chef:recipe > action :delete
chef:recipe > store_name 'ROOT'
chef:recipe (16.14.1)> end
 => <windows_certificate[Remove SennCom Certificate - ROOT] @name: "Remove SennCom Certificate - ROOT" @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :create, :acl_add, :delete, :fetch, :verify] @action: [:delete] @updated: false @updated_by_last_action: false @source_line: "(irb#1):1:in `irb_binding'" @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @declared_type: :windows_certificate @cookbook_name: nil @recipe_name: nil @source: "1990649205b55eab5d692e9edb1be0ddd3b037de" @store_name: "ROOT">
chef:recipe (16.14.1)> run_chef
[2021-09-03T14:15:37+02:00] INFO: Processing windows_certificate[Remove SennCom Certificate - ROOT] action delete ((irb#1) line 1)
[2021-09-03T14:15:37+02:00] DEBUG: Certificate not found
[2021-09-03T14:15:37+02:00] INFO: Processing windows_certificate[Remove SennCom Certificate - ROOT] action delete ((irb#1) line 1)
[2021-09-03T14:15:38+02:00] DEBUG: Certificate not found
 => true
```

**Comment by ChefAustin** [comment]
I am thinking this might possibly stem from upgrading `win32-certstore` from `v.03` to `v0.5`.

Specifically, it looks like the `:delete` action relies upon `fetch_cert` [[1](https://github.com/chef/chef/blob/b91d99f16947b82d09217079f5423b5c7cd0962c/lib/chef/resource/windows_certificate.rb#L131-L141)] which in turn relies upon the `win32-certstore` Gem's `get` function [[2]](https://github.com/chef/chef/blob/b91d99f16947b82d09217079f5423b5c7cd0962c/lib/chef/resource/windows_certificate.rb#L193-L201) which calls to `cert_get` [[3]](https://github.com/chef/win32-certstore/blob/133e49768b66b57d602c39ff1400064b499dfa2b/lib/win32/certstore.rb#L74-L79) which raises the `ArgumentError` when the certificate is unable to be found [[4]](https://github.com/chef/win32-certstore/blob/133e49768b66b57d602c39ff1400064b499dfa2b/lib/win32/certstore/store_base.rb#L90-L102).

This new `raise` logic was introduced in this [PR](https://github.com/chef/win32-certstore/pull/79) but I don't think it was realized that the `windows_certificate` resource's `:delete` action relies upon this method and, subsequently, the upstream code will need to handle that exception if the calling resource's action is `:delete`.

**Comment by ChefAustin** [comment]
I think I might have found a solution for this issue by modifying the `:delete` action definition to:
```
action :delete, description: "Deletes a certificate." do
  begin
    cert_obj = fetch_cert
  rescue ArgumentError => e
    raise e unless e.message == "Unable to retrieve the certificate"
  else
    if cert_obj
      converge_by("Deleting certificate #{new_resource.source} from Store #{new_resource.store_name}") do
        delete_cert
      end
    end
  end
end
```
Given that both `validate_thumprint` and `cert_get` return `ArgumentError` we need to differentiate between a _true_ failure (an `ArgumentError` returned by `validate_thumbprint`) and a _false_ failure (an `ArgumentError` returned by the conditional `if` block within `cert_get`'s definition) to determine whether or not to rescue the exception (in the instance that the certificate requested for deletion has already been deleted) or continue raising the exception up the stack (in the instance that the thumbprint does not validate, and resulting in a failed Chef run).

Open to alternative approaches but this seems sane-ish to me.

**Comment by rorymurdock** [comment]
If there was a certificate_exists function then we could evaluate that before attempting to fetch_cert and avoid catching any exceptions, whether that's evaluated in our cookbook of by fetch_cert and returning nil.

**Comment by jasonwbarnett** [comment]
I'm not sure why this was closed out prior to actually being fixed in a Chef Infra Client release. This problem is still impacting v17.10.3 because of at least two things:

1. There hasn't been a release of win32-certstore with the fixes published to [rubygems.org](https://rubygems.org/gems/win32-certstore)
2. chef infra client hasn't updated it's `Gemfile.lock`

/cc @johnmccrae

**Comment by ChefAustin** [comment]
> I'm not sure why this was closed out prior to actually being fixed in a Chef Infra Client release. This problem is still impacting v17.10.3 because of at least two things:
> 
> 
> 
> 1. There hasn't been a release of win32-certstore with the fixes published to [rubygems.org](https://rubygems.org/gems/win32-certstore)
> 
> 2. chef infra client hasn't updated it's `Gemfile.lock`
> 
> 
> 
> /cc @johnmccrae

Agreed. I've mentioned it to our Customer Success representatives over the past months and it never gained traction. I gave up.

**Comment by jaymzh** [comment]
This fix has since been released, closing.
