### ISSUE TITLE
dsc_resource/package idempotency issues.

### ISSUE THREAD

**Issue by jaymzh** [chef/chef#12324]
## Description

I have a server where suddenly `dsc_resource` around `windowscapabiltiy` isn't idempotent anymore. I... can't explain it:
```ruby
  dsc_resource 'uninstall ssh-server' do
    resource :windowscapability
    module_name 'ComputerManagementDsc'
    property :name, 'OpenSSH.Server~~~~0.0.1.0'
    property :ensure, 'Absent'
    notifies :stop, 'service[ssh]', :before
  end
```

```text
Chef::Exceptions::PowershellCmdletException
-------------------------------------------
PowerShell Cmdlet failed: DismInitialize failed. Error code = 0x80070008
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsCapabilityCommand    
    + PSComputerName        : localhost

PowerShell DSC resource DSC_WindowsCapability  failed to execute
Test-TargetResource functionality with error message: Specified Windows Capability   
'OpenSSH.Server~~~~0.0.1.0' not found.
Parameter name: Name
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:  
   String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
```

It claims it's not found, but that makes no sense, it clearly knows it's possible:

```powershell
> Get-WindowsCapability -Online | where {$_.Name -like '*SSH*'}

Name  : OpenSSH.Client~~~~0.0.1.0
State : NotPresent

Name  : OpenSSH.Server~~~~0.0.1.0
State : NotPresent
```

I tried making sure I was on the latest ComputerManagementDsc:

```powershell
> Get-Package | ? { $_.Name -like '*Dsc*' }
                                                                           
Name                           Version          Source                           Pro
----                           -------          ------                           --- 
ComputerManagementDsc          8.5.0            https://www.powershellgallery... Pow 
```

Meanwhile `Get-WindowsCapability` throws an error:

```powershell
> Get-WindowsCapability -Name OpenSSH.Server
Get-WindowsCapability : Parameter set cannot be resolved using the specified named 
parameters.
```

But it does the same on lots of other hosts as well that don't have this problem.

## Chef Version
16.7.61

## Platform Version

```
>  [System.Environment]::OSVersion.Version
                                                                          
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      19042  0
```

## Replication Case
See above

## Client Output

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it. -->

```
[2021-11-29T18:22:33-08:00] INFO: dsc_resource[uninstall ssh-server] running why-run 
run action to support before action
[2021-11-29T18:22:33-08:00] INFO: Processing dsc_resource[uninstall ssh-server] actio
n run (vcrs_windows::ssh line 16)

================================================================================     
Error executing action `run` on resource 'dsc_resource[uninstall ssh-server]'        
================================================================================     

Chef::Exceptions::PowershellCmdletException
-------------------------------------------
PowerShell Cmdlet failed: DismInitialize failed. Error code = 0x80070008
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsCapabilityCommand    
    + PSComputerName        : localhost

PowerShell DSC resource DSC_WindowsCapability  failed to execute
Test-TargetResource functionality with error message: Specified Windows Capability   
'OpenSSH.Server~~~~0.0.1.0' not found.
Parameter name: Name
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:  
   String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost


Resource Declaration:
---------------------
# In C:/chef/cache/cookbooks/vcrs_windows/recipes/ssh.rb

 16:   dsc_resource 'uninstall ssh-server' do
 17:     resource :windowscapability
 18:     module_name 'ComputerManagementDsc'
 19:     property :name, 'OpenSSH.Server~~~~0.0.1.0'
 20:     property :ensure, 'Absent'
 21:     notifies :stop, 'service[ssh]', :before
 22:   end
 23: 

Compiled Resource:
------------------
# Declared in C:/chef/cache/cookbooks/vcrs_windows/recipes/ssh.rb:16:in `from_file'  

dsc_resource("uninstall ssh-server") do
  action [:run]
  default_guard_interpreter :default
  properties {name=>"OpenSSH.Server~~~~0.0.1.0", ensure=>"Absent"}
  resource :windowscapability
  declared_type :dsc_resource
  cookbook_name "vcrs_windows"
  recipe_name "ssh"
  module_name "ComputerManagementDsc"
end

System Info:
------------
chef_version=16.7.61
platform=windows
platform_version=10.0.19042
ruby=ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x64-mingw32]
program_name=C:/cinc-project/cinc/bin/cinc-client
executable=C:/cinc-project/cinc/bin/cinc-client

[2021-11-29T18:22:35-08:00] INFO: Running queued delayed notifications before re-rais
ing exception
[2021-11-29T18:22:35-08:00] ERROR: Running exception handlers
[2021-11-29T18:22:35-08:00] ERROR: Exception handlers complete
[2021-11-29T18:22:35-08:00] DEBUG: Updated resources: 
[2021-11-29T18:22:35-08:00] INFO: vcrs_handlers: writing chef results for chef_ages  
[2021-11-29T18:22:35-08:00] FATAL: Stacktrace dumped to C:/chef/cache/cinc-stacktrace
.out
[2021-11-29T18:22:35-08:00] FATAL: Please provide the contents of the stacktrace.out 
file if you file a bug report
[2021-11-29T18:22:35-08:00] DEBUG: Chef::Exceptions::PowershellCmdletException: dsc_r
esource[uninstall ssh-server] (vcrs_windows::ssh line 16) had an error: Chef::Excepti
ons::PowershellCmdletException: PowerShell Cmdlet failed: DismInitialize failed. Erro
r code = 0x80070008
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsCapabilityCommand    
    + PSComputerName        : localhost

PowerShell DSC resource DSC_WindowsCapability  failed to execute
Test-TargetResource functionality with error message: Specified Windows Capability   
'OpenSSH.Server~~~~0.0.1.0' not found.
Parameter name: Name
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:  
   String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost


C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/util/powershell/cmdlet.rb:91:in `run!'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/provider/dsc_resource.rb:171:in `invoke_resource'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/provider/dsc_resource.rb:131:in `test_resource'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/provider/dsc_resource.rb:37:in `block in <class:DscResource>'
(eval):2:in `block in action_run'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/provider.rb:276:in `instance_eval'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/provider.rb:276:in `compile_and_converge_action'
(eval):2:in `action_run'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/provider.rb:217:in `run_action'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/resource.rb:599:in `block in run_action'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/resource.rb:626:in `with_umask'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/resource.rb:598:in `run_action'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/runner.rb:61:in `block in run_action'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/runner.rb:178:in `forced_why_run'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/runner.rb:59:in `run_action'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/runner.rb:108:in `block in run_all_actions'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/runner.rb:108:in `each'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/runner.rb:108:in `run_all_actions'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/runner.rb:132:in `block in converge'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'      
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
C:/cinc-project/cinc/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `execute_each_reso
urce'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/runner.rb:130:in `converge'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/client.rb:684:in `block in converge'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/client.rb:679:in `catch'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/client.rb:679:in `converge'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/client.rb:703:in `converge_and_save'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/client.rb:283:in `run'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/application.rb:281:in `block in run_chef_client'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/local_mode.rb:42:in `with_server_connectivity'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/application.rb:264:in `run_chef_client'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/application/base.rb:337:in `run_application'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/application.rb:67:in `run'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.7.61/bin/cinc-clie
nt:25:in `<top (required)>'
C:/cinc-project/cinc/bin/cinc-client:164:in `load'
C:/cinc-project/cinc/bin/cinc-client:164:in `<main>'

>>>> Caused by Chef::Exceptions::PowershellCmdletException: PowerShell Cmdlet failed:
 DismInitialize failed. Error code = 0x80070008
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsCapabilityCommand    
    + PSComputerName        : localhost

PowerShell DSC resource DSC_WindowsCapability  failed to execute
Test-TargetResource functionality with error message: Specified Windows Capability   
'OpenSSH.Server~~~~0.0.1.0' not found.
Parameter name: Name
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:  
   String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost


C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/util/powershell/cmdlet.rb:91:in `run!'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/provider/dsc_resource.rb:171:in `invoke_resource'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/provider/dsc_resource.rb:131:in `test_resource'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/provider/dsc_resource.rb:37:in `block in <class:DscResource>'
(eval):2:in `block in action_run'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/provider.rb:276:in `instance_eval'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/provider.rb:276:in `compile_and_converge_action'
(eval):2:in `action_run'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/provider.rb:217:in `run_action'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/resource.rb:599:in `block in run_action'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/resource.rb:626:in `with_umask'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/resource.rb:598:in `run_action'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/runner.rb:61:in `block in run_action'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/runner.rb:178:in `forced_why_run'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/runner.rb:59:in `run_action'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/runner.rb:108:in `block in run_all_actions'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/runner.rb:108:in `each'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/runner.rb:108:in `run_all_actions'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/runner.rb:132:in `block in converge'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'      
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
C:/cinc-project/cinc/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `execute_each_reso
urce'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/runner.rb:130:in `converge'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/client.rb:684:in `block in converge'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/client.rb:679:in `catch'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/client.rb:679:in `converge'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/client.rb:703:in `converge_and_save'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/client.rb:283:in `run'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/application.rb:281:in `block in run_chef_client'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/local_mode.rb:42:in `with_server_connectivity'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/application.rb:264:in `run_chef_client'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/application/base.rb:337:in `run_application'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-16.7.61-universal-mingw32
/lib/chef/application.rb:67:in `run'
C:/cinc-project/cinc/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.7.61/bin/cinc-clie
nt:25:in `<top (required)>'
C:/cinc-project/cinc/bin/cinc-client:164:in `load'
C:/cinc-project/cinc/bin/cinc-client:164:in `<main>'
[2021-11-29T18:22:35-08:00] FATAL: Chef::Exceptions::PowershellCmdletException: dsc_r
esource[uninstall ssh-server] (vcrs_windows::ssh line 16) had an error: Chef::Excepti
ons::PowershellCmdletException: PowerShell Cmdlet failed: DismInitialize failed. Erro
r code = 0x80070008
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsCapabilityCommand    
    + PSComputerName        : localhost

PowerShell DSC resource DSC_WindowsCapability  failed to execute
Test-TargetResource functionality with error message: Specified Windows Capability   
'OpenSSH.Server~~~~0.0.1.0' not found.
Parameter name: Name
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:  
   String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost


[2021-11-29 18:22:36 -0800] INFO chefctl: cinc-client.bat failed with exit code 1, ch
eck log output!

```

**Comment by jaymzh** [comment]
This is a bug in 8.4.0 of DSC. Whomp whomp.

**Comment by jaymzh** [comment]
Relevant bug, I believe: https://github.com/dsccommunity/ComputerManagementDsc/issues/380
