### ISSUE TITLE
ruby-shadow required, but can't compile on Ruby 3.0.0

### ISSUE THREAD

**Issue by cgoettel** [chef/chef#12333]
## Description
When running Chef on Ubuntu 20.04, Chef throws the following errors when trying to set a user password:
```[2021-11-29T11:24:17-07:00] FATAL: Chef::Exceptions::MissingLibrary: linux_user[administrator] (reponame::loc
al_users line 27) had an error: Chef::Exceptions::MissingLibrary: You must have ruby-shadow installed for password support!
```

So I tell Chef to install the ruby-shadow Gem:
```
chef_gem 'ruby-shadow' do
  action :install
end
```

and that errs out with:
```
================================================================================
Error executing action `install` on resource 'chef_gem[ruby-shadow]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of /opt/chef-workstation/embedded/bin/gem install ruby-shadow -q --no-document -v "2.5.0" --source=https://rubygems.org ----
STDOUT: Building native extensions. This could take a while...
STDERR: WARNING:  You don't have /root/.chefdk/gem/ruby/3.0.0/bin in your PATH,
          gem executables will not run.
ERROR:  Error installing ruby-shadow:
        ERROR: Failed to build gem native extension.

    current directory: /root/.chefdk/gem/ruby/3.0.0/gems/ruby-shadow-2.5.0
/opt/chef-workstation/embedded/bin/ruby -I /opt/chef-workstation/embedded/lib/ruby/3.0.0 -r ./siteconf20211201-89170-rv4z38.rb extconf.rb
checking for getspent() in -lshadow... no
checking for getspent()... yes
checking for fgetspent()... yes
checking for setspent()... yes
checking for endspent()... yes
checking for lckpwdf()... yes
checking for ulckpwdf()... yes
checking for sgetspent()... yes
checking for ruby/io.h... yes
creating Makefile

current directory: /root/.chefdk/gem/ruby/3.0.0/gems/ruby-shadow-2.5.0
make DESTDIR\= clean

current directory: /root/.chefdk/gem/ruby/3.0.0/gems/ruby-shadow-2.5.0
make DESTDIR\=
compiling shadow/shadow.c
shadow/shadow.c: In function ‘rb_shadow_fgetspent’:
shadow/shadow.c:21:26: error: ‘struct rb_io_t’ has no member named ‘f’; did you mean ‘fd’?
   21 | #define file_ptr(x) (x)->f
      |                          ^
shadow/shadow.c:95:22: note: in expansion of macro ‘file_ptr’
   95 |   entry = fgetspent( file_ptr( (RFILE(file)->fptr) ) );
      |                      ^~~~~~~~
shadow/shadow.c: In function ‘rb_shadow_putspent’:
shadow/shadow.c:21:26: error: ‘struct rb_io_t’ has no member named ‘f’; did you mean ‘fd’?
   21 | #define file_ptr(x) (x)->f
      |                          ^
shadow/shadow.c:154:11: note: in expansion of macro ‘file_ptr’
  154 |   cfile = file_ptr( RFILE(file)->fptr );
      |           ^~~~~~~~
make: *** [Makefile:245: shadow.o] Error 1

make failed, exit code 2

Gem files will remain installed in /root/.chefdk/gem/ruby/3.0.0/gems/ruby-shadow-2.5.0 for inspection.
Results logged to /root/.chefdk/gem/ruby/3.0.0/extensions/x86_64-linux/3.0.0/ruby-shadow-2.5.0/gem_make.out
---- End output of /opt/chef-workstation/embedded/bin/gem install ruby-shadow -q --no-document -v "2.5.0" --source=https://rubygems.org ----
Ran /opt/chef-workstation/embedded/bin/gem install ruby-shadow -q --no-document -v "2.5.0" --source=https://rubygems.org returned 1```

The problem is documented [here](https://github.com/apalmblad/ruby-shadow/issues/26) with a fix [here](https://src.fedoraproject.org/rpms/rubygem-ruby-shadow/blob/rawhide/f/ruby-shadow-2.5.0-cflags.patch). I have submitted [a PR for it](https://github.com/apalmblad/ruby-shadow/pull/27), but here's the problem:
- Chef uses ruby-shadow on the backend on Ubuntu 20.04 for managing user passwords (right? I'm not making this up?)
- The current version of ruby-shadow, 2.5.0, came out in 2015
- The linked patch was written in 2017
- The linked patch still hasn't been merged (and there was no PR for it until I submitted one today)

If Chef is using ruby-shadow on the backend, it would make sense for Chef to also maintain it. Or use something else to handle that functionality.

## Chef Version
<!--- Tell us which version of chef-client you are using (see below for Server+ChefDK bugs). -->
```System Info:
------------
chef_version=17.6.18
platform=ubuntu
platform_version=20.04
ruby=ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
program_name=/usr/bin/chef-client
executable=/opt/chef-workstation/bin/chef-client```

## Platform Version
Ubuntu 20.04

## Replication Case
<!--- Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case. -->
cookbook:
```chef_gem 'ruby-shadow' do
  action :install
end```

## Client Output
<!--- The relevant output of the chef-client run or a link to a gist of the entire run, if there is one.

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it. -->

```
see above
```

## Stacktrace
<!--- Please include the stacktrace.out output or link to a gist of it, if there is one. -->
```Generated at 2021-12-01 13:07:35 -0700
Mixlib::ShellOut::ShellCommandFailed: chef_gem[ruby-shadow] (baseline::local_users line 10) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/chef-workstation/embedded/bin/gem install ruby-shadow -q --no-document -v "2.5.0" --source=https://rubygems.org ----
STDOUT: Building native extensions. This could take a while...
STDERR: WARNING:  You don't have /root/.chefdk/gem/ruby/3.0.0/bin in your PATH,
	  gem executables will not run.
ERROR:  Error installing ruby-shadow:
	ERROR: Failed to build gem native extension.

    current directory: /root/.chefdk/gem/ruby/3.0.0/gems/ruby-shadow-2.5.0
/opt/chef-workstation/embedded/bin/ruby -I /opt/chef-workstation/embedded/lib/ruby/3.0.0 -r ./siteconf20211201-89170-rv4z38.rb extconf.rb
checking for getspent() in -lshadow... no
checking for getspent()... yes
checking for fgetspent()... yes
checking for setspent()... yes
checking for endspent()... yes
checking for lckpwdf()... yes
checking for ulckpwdf()... yes
checking for sgetspent()... yes
checking for ruby/io.h... yes
creating Makefile

current directory: /root/.chefdk/gem/ruby/3.0.0/gems/ruby-shadow-2.5.0
make DESTDIR\= clean

current directory: /root/.chefdk/gem/ruby/3.0.0/gems/ruby-shadow-2.5.0
make DESTDIR\=
compiling shadow/shadow.c
shadow/shadow.c: In function ‘rb_shadow_fgetspent’:
shadow/shadow.c:21:26: error: ‘struct rb_io_t’ has no member named ‘f’; did you mean ‘fd’?
   21 | #define file_ptr(x) (x)->f
      |                          ^
shadow/shadow.c:95:22: note: in expansion of macro ‘file_ptr’
   95 |   entry = fgetspent( file_ptr( (RFILE(file)->fptr) ) );
      |                      ^~~~~~~~
shadow/shadow.c: In function ‘rb_shadow_putspent’:
shadow/shadow.c:21:26: error: ‘struct rb_io_t’ has no member named ‘f’; did you mean ‘fd’?
   21 | #define file_ptr(x) (x)->f
      |                          ^
shadow/shadow.c:154:11: note: in expansion of macro ‘file_ptr’
  154 |   cfile = file_ptr( RFILE(file)->fptr );
      |           ^~~~~~~~
make: *** [Makefile:245: shadow.o] Error 1

make failed, exit code 2

Gem files will remain installed in /root/.chefdk/gem/ruby/3.0.0/gems/ruby-shadow-2.5.0 for inspection.
Results logged to /root/.chefdk/gem/ruby/3.0.0/extensions/x86_64-linux/3.0.0/ruby-shadow-2.5.0/gem_make.out
---- End output of /opt/chef-workstation/embedded/bin/gem install ruby-shadow -q --no-document -v "2.5.0" --source=https://rubygems.org ----
Ran /opt/chef-workstation/embedded/bin/gem install ruby-shadow -q --no-document -v "2.5.0" --source=https://rubygems.org returned 1
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout.rb:300:in `invalid!'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout.rb:287:in `error!'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout/helper.rb:130:in `shell_out_compacted!'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/mixlib-shellout-3.2.5/lib/mixlib/shellout/helper.rb:54:in `shell_out!'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/provider/package/rubygems.rb:587:in `install_via_gem_command'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/provider/package/rubygems.rb:555:in `install_package'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/provider/package.rb:120:in `block (3 levels) in <class:Package>'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/provider/package.rb:269:in `multipackage_api_adapter'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/provider/package.rb:119:in `block (2 levels) in <class:Package>'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/mixin/why_run.rb:51:in `add_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/provider.rb:290:in `converge_by'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/provider/package.rb:118:in `block in <class:Package>'
(eval):2:in `block in action_install'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/provider.rb:301:in `instance_eval'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/provider.rb:301:in `compile_and_converge_action'
(eval):2:in `action_install'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/provider.rb:242:in `run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/resource.rb:600:in `block in run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/resource.rb:627:in `with_umask'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/resource.rb:599:in `run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/runner.rb:74:in `run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/runner.rb:108:in `each'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/runner.rb:132:in `block in converge'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef-workstation/embedded/lib/ruby/3.0.0/forwardable.rb:238:in `execute_each_resource'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/runner.rb:130:in `converge'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/client.rb:686:in `block in converge'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/client.rb:681:in `catch'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/client.rb:681:in `converge'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/client.rb:705:in `converge_and_save'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/client.rb:285:in `run'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/application.rb:281:in `block in run_chef_client'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/application.rb:264:in `run_chef_client'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/application/base.rb:352:in `run_application'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.6.18/lib/chef/application.rb:67:in `run'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-bin-17.6.18/bin/chef-client:25:in `<top (required)>'
/usr/bin/chef-client:376:in `load'
/usr/bin/chef-client:376:in `<main>'```

**Comment by lamont-granquist** [comment]
Uh, you already worked with the maintainer to fix that yesterday (which was good now we can pull it in properly), but there's nothing to do here.

The chef-workstation package should really be including that but that's needs to be cut against chef/chef-workstation.

**Comment by cgoettel** [comment]
Honestly, I wasn't expecting the package maintainer to reply since it had been so long since anything had been done. I'll go file the request in chef-workstation. Thanks!
