### ISSUE TITLE
Calling chef_sleep from windows_package via notification fails 

### ISSUE THREAD

**Issue by JHBoricua** [chef/chef#12385]
## Description
Attempting to call chef_sleep via a notification from windows_package resource is failing to compile the chef-client run. I'm trying to pause the chef run after installation of the software to give the service that gets created enough time to start before I modify it and attempt to restart it further down in the cookbook.

## Chef Version
chef-client 17.1.35

## Platform Version
Windows Server 2019

## Replication Case
The two resources are defined as follows:
```
windows_package 'zabbix-agent2' do
  action :install
  checksum 'f459f55bf917861e7ea5c4e0ff68eb20f9bff26fd0b092c443acd3222733bc6b'
  options "SERVER=MyZabbixServer"
  source "Agent installer URL"
  version '5.0.18.2400'
  timeout 1200
  notifies :sleep, chef_sleep['wait for agent start'], :immediately
end

chef_sleep 'wait for agent start' do
  seconds 30
  action :nothing
end
```

## Client Output
```
       Compiling Cookbooks...
       
       ================================================================================
       Recipe Compile Error in C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/zabbix/recipes/windows.rb
       ================================================================================
       
       NoMethodError
       -------------
       undefined method `chef_sleep' for Chef::Resource::WindowsPackage
       
       Cookbook Trace: (most recent call first)
       ----------------------------------------
         C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/zabbix/recipes/windows.rb:15:in `block in from_file'
         C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/zabbix/recipes/windows.rb:8:in `from_file'
       
       Relevant File Content:
       ----------------------
       C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/zabbix/recipes/windows.rb:
       
         8:  windows_package 'zabbix-agent2' do
         9:    action :install
        10:    checksum 'f459f55bf917861e7ea5c4e0ff68eb20f9bff26fd0b092c443acd3222733bc6b'
        11:    options "MyZabbixServer"
        12:    source "Agent Installer URL"
        13:    version '5.0.18.2400'
        14:    timeout 1200
        15>>   notifies :sleep, chef_sleep['wait for agent start'], :immediately
        16:  end
        17:  
        18:  chef_sleep 'wait for agent start' do
        19:    seconds 30
        20:    action :nothing
        21:  end
        22:  
        23:  template 'zabbix_agent2.conf' do
        24:    path 'C:\\Program Files\\Zabbix Agent 2\\zabbix_agent2.conf'
       
       System Info:
       ------------
       chef_version=17.1.35
       platform=windows
       platform_version=10.0.17763
       ruby=ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x64-mingw32]
       program_name=C:/opscode/chef/bin/chef-client
       executable=C:/opscode/chef/bin/chef-client
       
       
       Running handlers:
       [2021-12-17T01:06:57+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2021-12-17T01:06:57+00:00] ERROR: Exception handlers complete
       Chef Infra Client failed. 0 resources updated in 30 seconds
       [2021-12-17T01:06:57+00:00] FATAL: Stacktrace dumped to C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       [2021-12-17T01:06:57+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2021-12-17T01:06:57+00:00] FATAL: NoMethodError: undefined method `chef_sleep' for Chef::Resource::WindowsPackage
$$$$$$ C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ohai-17.1.0/lib/ohai/plugins/hostname.rb:194:in `gethostbyname': warning: Socket.gethostbyname is deprecated; use Addrinfo.getaddrinfo instead. (StructuredWarnings::BuiltInWarning)
$$$$$$ C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ohai-17.1.0/lib/ohai/plugins/hostname.rb:201:in `gethostbyaddr': warning: Socket.gethostbyaddr is deprecated; use Addrinfo#getnameinfo instead. (StructuredWarnings::BuiltInWarning)
```
## Stacktrace
```
       Generated at 2021-12-17 01:06:57 +0000
       NoMethodError: undefined method `chef_sleep' for Chef::Resource::WindowsPackage
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/resource.rb:1347:in `method_missing'
       C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/zabbix/recipes/windows.rb:15:in `block in from_file'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/resource_builder.rb:70:in `instance_exec'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/resource_builder.rb:70:in `build'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/dsl/declare_resource.rb:313:in `build_resource'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/dsl/declare_resource.rb:265:in `declare_resource'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/dsl/resources.rb:36:in `windows_package'
       C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/ecmc_zabbix/recipes/windows.rb:8:in `from_file'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/mixin/from_file.rb:34:in `instance_eval'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/mixin/from_file.rb:34:in `from_file'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/cookbook_version.rb:230:in `load_ruby_recipe'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/cookbook_version.rb:200:in `load_recipe'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/run_context.rb:393:in `load_recipe'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:174:in `block in compile_recipes'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:171:in `each'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:171:in `compile_recipes'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:79:in `compile'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/run_context.rb:223:in `load'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/policy_builder/policyfile.rb:196:in `setup_run_context'
       C:/opscode/chef/embedded/lib/ruby/3.0.0/forwardable.rb:238:in `setup_run_context'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/client.rb:496:in `setup_run_context'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/client.rb:282:in `run'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/application.rb:281:in `block in run_chef_client'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/local_mode.rb:42:in `with_server_connectivity'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/application.rb:264:in `run_chef_client'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/application/base.rb:337:in `run_application'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/application.rb:67:in `run'
       C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-bin-17.1.35/bin/chef-client:25:in `<top (required)>'
       C:/opscode/chef/bin/chef-client:152:in `load'
       C:/opscode/chef/bin/chef-client:152:in `<main>'
```

**Comment by lamont-granquist** [comment]
not a bug...

````
notifies :sleep, chef_sleep['wait for agent start'], :immediately
```

that line needs to be:

````
notifies :sleep, 'chef_sleep[wait for agent start]', :immediately
````

**Comment by tas50** [comment]
@JHBoricua I created a cookstyle rule to detect this formatting mistake in notification: https://github.com/chef/cookstyle/pull/925
