### ISSUE TITLE
New rspec gems find broken ruby 3.0 issues that remain in our code/tests

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#12563]
If we `bundle update` and then `bundle exec rspec` to test the latest version of rspec what we wind up with a bunch of failures:

```
rspec ./spec/unit/api_client_spec.rb:310 # Chef::ApiClient when requesting a new key and the client exists and the client exists on a Chef 11-like server returns an ApiClient with a private key
rspec ./spec/unit/api_client_spec.rb:328 # Chef::ApiClient when requesting a new key and the client exists and the client exists on a Chef 10-like server returns an ApiClient with a private key
rspec './spec/unit/client_spec.rb[1:6:1:1]' # Chef::Client a full client run when running chef-client without fork runs ohai, sets up authentication, loads node state, synchronizes policy, converges
rspec './spec/unit/client_spec.rb[1:6:2:1]' # Chef::Client a full client run when the client key already exists runs ohai, sets up authentication, loads node state, synchronizes policy, converges
rspec './spec/unit/client_spec.rb[1:6:3:2:1]' # Chef::Client a full client run when an override run list is given calling run runs ohai, sets up authentication, loads node state, synchronizes policy, converges
rspec ./spec/unit/client_spec.rb:482 # Chef::Client a full client run when a permanent run list is passed as an option sets the new run list on the node
rspec './spec/unit/client_spec.rb[1:6:4:2]' # Chef::Client a full client run when a permanent run list is passed as an option runs ohai, sets up authentication, loads node state, synchronizes policy, converges
rspec ./spec/unit/client_spec.rb:280 # Chef::Client a full client run when converge errors skips node save and raises the error in a wrapping error
rspec ./spec/unit/client_spec.rb:810 # Chef::Client deprecated enforce_path_sanity print a warning, when enforce_path_sanity is passed
rspec ./spec/unit/client_spec.rb:816 # Chef::Client deprecated enforce_path_sanity should not print a warning, when enforce_path_sanity is not passed
rspec ./spec/unit/policy_builder/policyfile_spec.rb:135 # Chef::PolicyBuilder::Policyfile configures a Chef HTTP API client
rspec ./spec/unit/provider/package/rubygems_spec.rb:186 # Chef::Provider::Package::Rubygems::CurrentGemEnvironment installs a gem with a hash of options for the dependency installer
rspec ./spec/unit/provider/package/rubygems_spec.rb:194 # Chef::Provider::Package::Rubygems::CurrentGemEnvironment builds an uninstaller for a gem with options set to avoid requiring user input
rspec ./spec/unit/provider/package/rubygems_spec.rb:201 # Chef::Provider::Package::Rubygems::CurrentGemEnvironment uninstalls all versions of a gem
rspec ./spec/unit/provider/package/rubygems_spec.rb:208 # Chef::Provider::Package::Rubygems::CurrentGemEnvironment uninstalls a specific version of a gem
rspec ./spec/unit/provider/service/windows_spec.rb:293 # Chef::Provider::Service::Windows load_current_resource Chef::Provider::Service::Windows action_create service does not exist creates service with correct configuration
rspec ./spec/unit/provider/service/windows_spec.rb:458 # Chef::Provider::Service::Windows load_current_resource Chef::Provider::Service::Windows converge_delayed_start delayed start needs to be updated configures delayed start with correct params
rspec ./spec/unit/provider/user/windows_spec.rb:141 # Chef::Provider::User::Windows when creating the user should call @net_user.add with the return of set_options
rspec ./spec/unit/provider/user/windows_spec.rb:153 # Chef::Provider::User::Windows manage_user should call @net_user.update with the return of set_options
```

Those failures look nonsensical, for example:

```
  19) Chef::Provider::User::Windows manage_user should call @net_user.update with the return of set_options
      Failure/Error: @provider.manage_user

        #<Double "Chef::Util::Windows::NetUser"> received :update with unexpected arguments
          expected: ({:name=>"monkey"})
               got: ({:name=>"monkey"})
        Diff:

      # ./lib/chef/provider/user/windows.rb:85:in `manage_user'
      # ./spec/unit/provider/user/windows_spec.rb:155:in `block (3 levels) in <top (required)>'
      # ./spec/spec_helper.rb:307:in `block (2 levels) in <top (required)>'
```

I fixed a similar issue in berkshelf and it turned out to be the typical ruby-3.0 problem of options hashes missing the `**options` splat args:

https://github.com/berkshelf/berkshelf/pull/1874/files#diff-4928680f9b7d4faec59fd818f7dbd4f8a9bb15a93dc8d4808e7a3ae8a565b056L159-R159

It looks like we have similar problem still existing in the chef/chef codebase and probably need some `**`'s added in places.

There is also this kind of failure though and I'm not sure what this is:

```
3) Chef::Client a full client run when running chef-client without fork runs ohai, sets up authentication, loads node state, synchronizes policy, converges
     Failure/Error: expect(client.run).to be true

     Errno::EACCES:
       Permission denied @ rb_sysopen - /var/chef/cache/chef-stacktrace.out
     Shared Example Group: "a completed run" called from ./spec/unit/client_spec.rb:435
     Shared Example Group: "a successful client run" called from ./spec/unit/client_spec.rb:439
     # ./lib/chef/file_cache.rb:57:in `initialize'
     # ./lib/chef/file_cache.rb:57:in `open'
     # ./lib/chef/file_cache.rb:57:in `store'
     # ./lib/chef/application.rb:378:in `debug_stacktrace'
     # ./lib/chef/client.rb:309:in `rescue in run'
     # ./lib/chef/client.rb:299:in `run'
     # ./spec/unit/client_spec.rb:269:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:307:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     #   #<Chef::ServerAPI (class)> received :new with unexpected arguments
     #     expected: ("https://localhost:443", {:version_class=>Chef::CookbookManifestVersions})
     #          got: ("https://localhost:443", {:version_class=>Chef::CookbookManifestVersions})
     #   Diff:
     #
     #   ./lib/chef/policy_builder/expand_node_object.rb:251:in `api_service'
```

That may ultimately be similar although it might be some allow-stub that isn't mocking the test correctly because something is missing a `**` somewhere so some code which should be mocked runs and then the test fails due to failure to find the file.   So the mocking probably needs to be debugging to find the broken mock which is allowing code to run which shouldn't.

**Comment by tas50** [comment]
Replaced with https://chefio.atlassian.net/browse/INFC-53
