### ISSUE TITLE
The proxifier gem no longer works under ruby 3.1.1

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#12626]
```
% bundle exec rspec

An error occurred while loading ./spec/unit/mixin/proxified_socket_spec.rb.
Failure/Error: require "proxifier"

NameError:
  uninitialized class variable @@schemes in URI
  Did you mean?  scheme_list
# ./lib/chef/mixin/proxified_socket.rb:18:in `require'
# ./lib/chef/mixin/proxified_socket.rb:18:in `<top (required)>'
# ./spec/unit/mixin/proxified_socket_spec.rb:20:in `require'
# ./spec/unit/mixin/proxified_socket_spec.rb:20:in `<top (required)>'
```

This is a gem we depend on for http proxy support which hasn't been updated in 10 years:

https://rubygems.org/gems/proxifier

**Comment by lamont-granquist** [comment]
forked and fixed at chef/ruby-proxifier
