### ISSUE TITLE
Chef-client does not send data-collector logs when some deprecations are present

### ISSUE THREAD

**Issue by collinmcneese** [chef/chef#12668]
## Description

When some deprecation warnings are present in a chef-client run, the node object will fail to transmit to Chef Automate (via chef-infra-server proxy).  

While ultimately deprecated code should be fixed in cookbooks to resolve this problem - unfortunately when this condition happens that means that there will potentially be failures or deprecated code running on nodes and it will prevent the nodes from checking with report data to Chef Automate, so operators would not know that an error is present unless they notice that the nodes are not checking in or are running `chef-client` interactively.

The following deprecation warning results in error `rpc error: code = Internal desc = Unable to transform Run message to ChefClientRun: json: cannot unmarshal bool into Go struct field Deprecation.deprecations.message of type string` coming back from Automate (this shows in local trace log as well):

```
 Running handlers:
Running handlers complete

Deprecation warnings that must be addressed before upgrading to Chef Infra 18:

  true at 1 location:
    - /var/chef/cache/cookbooks/test_cookbook/recipes/default.rb:15:in `block in from_file'
   See https://docs.chef.io/deprecations_property/ for further details.

Infra Phase complete, 5/22 resources updated in 07 seconds
[2022-03-04T19:46:01+00:00] WARN: Server returned error 500 for https://ec2-54-218-248-185.us-west-2.compute.amazonaws.com/organizations/a2local/data-collector, retrying 1/5 in 4s
[2022-03-04T19:46:06+00:00] WARN: Server returned error 500 for https://ec2-54-218-248-185.us-west-2.compute.amazonaws.com/organizations/a2local/data-collector, retrying 2/5 in 5s
```

## Chef Version

Tested with:
16.17.51
17.9.52

## Platform Version

tested with almalinux-8 and amazonlinux-2

## Replication Case

Write a resource that is using a deprecated property.  In this instance, the `clean_headers` property has been deprecated.

```ruby
yum_repository 'some_repo' do
  description 'some_repo'
  mirrorlist 'http://mirror.centos.org/centos/7/os/x86_64/'
  make_cache false
  gpgcheck false
  enabled true
  clean_headers true
  action :add
end
```

Running `chef-client` will fail to send data to Chef Automate with this present:

```plain
Running handlers:
Running handlers complete

Deprecation warnings that must be addressed before upgrading to Chef Infra 18:

  true at 1 location:
    - /var/chef/cache/cookbooks/test_cookbook/recipes/default.rb:15:in `block in from_file'
   See https://docs.chef.io/deprecations_property/ for further details.

Infra Phase complete, 5/22 resources updated in 07 seconds
[2022-03-04T19:46:01+00:00] WARN: Server returned error 500 for https://ec2-54-218-248-185.us-west-2.compute.amazonaws.com/organizations/a2local/data-collector, retrying 1/5 in 4s
[2022-03-04T19:46:06+00:00] WARN: Server returned error 500 for https://ec2-54-218-248-185.us-west-2.compute.amazonaws.com/organizations/a2local/data-collector, retrying 2/5 in 5s
```

This is an example of a deprecation warning that does not produce this issue -- when this deprecation happens the node data is sent correctly and no errors are observed on the client:

```
  The  resource in the yum cookbook should declare `unified_mode true` at 1 location:
    - /var/chef/cache/cookbooks/yum/resources/globalconfig.rb
   See https://docs.chef.io/deprecations_unified_mode/ for further details.
```

**Comment by lamont-granquist** [comment]
```
  true at 1 location:
    - /var/chef/cache/cookbooks/test_cookbook/recipes/default.rb:15:in `block in from_file'
   See https://docs.chef.io/deprecations_property/ for further details.
```

that looks like a rendering problem with the deprecated property stuff where my guess would be that the JSON payload (which would be good to get the actual payload from -l trace or something to validate) looks like it is probably throwing a boolean `true` somewhere that the server-side is maybe expecting a string.  Or something that rhymes with that.

**Comment by collinmcneese** [comment]
Yep it does look like it is dropping the Boolean `true` as the `message` here, where it it is expecting a string instead

I used this resource sample:

```ruby
yum_repository 'some_repo' do
  description 'some_repo'
  mirrorlist 'http://mirror.centos.org/centos/7/os/x86_64/'
  make_cache false
  gpgcheck false
  enabled true
  clean_headers true
  action :add
end
```

Here what the `deprecations` key of the body payload looks like that it is trying to send

```json
[
  {
    "message": true,
    "url": "https://docs.chef.io/deprecations_property/",
    "location": "/home/ec2-user/recipe.rb:7:in `block in from_file'"
  }
]
```

It is a bit trickier to see what this looks like for deprecation warnings that are not erroring out, but I do see in the run_context of one that it has an actual message string instead of a Boolean for the `message` and that is able to send to the data_collector without issue:

```ruby
@events=
      #<Chef::EventDispatch::Dispatcher:0x000000000343b720
       @in_call=true,
       @subscribers=
        [#<Chef::Formatters::Doc:0x000000000343bce8
          @current_recipe="@recipe_files::/home/ec2-user/recipe.rb",
          @deprecations=
           {"The inspec_gem resource in the audit cookbook should declare `unified_mode true`"=>
             {:url=>"https://docs.chef.io/deprecations_unified_mode/", :locations=>#<Set: {"/var/chef/cache/cookbooks/audit/resources/inspec_gem.rb"}>}},
```
