### ISSUE TITLE
`no implicit conversion from nil to integer` when enforcing idempotency in Test-Kitchen

### ISSUE THREAD

**Issue by jakauppila** [chef/chef#12786]
## Description
Attempting to perform multiple converges and enforcing idempotency in Test-Kitchen results in an error:

```
/opt/cinc/embedded/lib/ruby/gems/3.0.0/gems/chef-bin-17.10.0/bin/chef-client:41:in `exit': no implicit conversion from nil to integer (TypeError)
        from /opt/cinc/embedded/lib/ruby/gems/3.0.0/gems/chef-bin-17.10.0/bin/chef-client:41:in `<top (required)>'
        from /opt/cinc/bin/chef-client:160:in `load'
        from /opt/cinc/bin/chef-client:160:in `<main>'
```

## Chef Version
Cinc 17.10.0

## Platform Version
CentOS 7

## Replication Case
Generate a cookbook, add this resource to the default recipe:

```ruby
execute 'hello' do
  command 'echo hello'
end
```

Modify the Chef provisioner to:

```ruby
provisioner:
  name: chef_infra
  product_name: chef
  enforce_idempotency: true
  multiple_converge: 2
```

## Client Output
```
Cinc Client, version 17.10.0
       Patents: https://www.chef.io/patents
       Infra Phase starting
       Using Policyfile 'multiple-converge' at revision 'eebb2d91e3e1ee59a560bd16f22b535387a62d6b789bd0490840a3f6149690ba'
       Resolving cookbooks for run list: ["multiple-converge::default@0.1.0 (bf74028)"]
       Synchronizing cookbooks:
         - multiple-converge (0.1.0)
       Installing cookbook gem dependencies:
       Compiling cookbooks...
       Loading Cinc Auditor profile files:
       Loading Cinc Auditor input files:
       Loading Cinc Auditor waiver files:
       Converging 1 resources
       Recipe: multiple-converge::default
         * execute[hello] action run
           - execute echo hello

       Running handlers:
       Running handlers complete
       Infra Phase complete, 1/1 resources updated in 03 seconds
       Redirecting to cinc-client
       Cinc Client, version 17.10.0
       Patents: https://www.chef.io/patents
       Infra Phase starting
       Using Policyfile 'multiple-converge' at revision 'eebb2d91e3e1ee59a560bd16f22b535387a62d6b789bd0490840a3f6149690ba'
       Resolving cookbooks for run list: ["multiple-converge::default@0.1.0 (bf74028)"]
       Synchronizing cookbooks:
         - multiple-converge (0.1.0)
       Installing cookbook gem dependencies:
       Compiling cookbooks...
       Loading Cinc Auditor profile files:
       Loading Cinc Auditor input files:
       Loading Cinc Auditor waiver files:
       Converging 1 resources
       Recipe: multiple-converge::default
         * execute[hello] action run
           - execute echo hello

       Running handlers:
       First chef run should have reached a converged state.
       Resources updated in a second chef-client run:
       - execute[hello]
       /opt/cinc/embedded/lib/ruby/gems/3.0.0/gems/chef-bin-17.10.0/bin/chef-client:41:in `exit': no implicit conversion from nil to integer (TypeError)
        from /opt/cinc/embedded/lib/ruby/gems/3.0.0/gems/chef-bin-17.10.0/bin/chef-client:41:in `<top (required)>'
        from /opt/cinc/bin/chef-client:160:in `load'
        from /opt/cinc/bin/chef-client:160:in `<main>'
D      Cleaning up local sandbox in C:/Users/077009/AppData/Local/Temp/default-centos-7-sandbox-20220412-32604-v38reu
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-centos-7>.  Please see .kitchen/logs/default-centos-7.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

## Stacktrace
```
D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-centos-7>.  Please see .kitchen/logs/default-centos-7.log for more details
D      ----------------------
D      ------Backtrace-------
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:181:in `report_errors'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:172:in `run_action'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command/action.rb:35:in `block in call'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command/action.rb:33:in `call'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/cli.rb:52:in `perform'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/cli.rb:198:in `block (2 levels) in <class:CLI>'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/bin/kitchen:11:in `block in <top (required)>'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/errors.rb:183:in `with_friendly_errors'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/bin/kitchen:11:in `<top (required)>'
D      C:/cinc-project/cinc-workstation/bin/kitchen:395:in `load'
D      C:/cinc-project/cinc-workstation/bin/kitchen:395:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::InstanceFailure
D      Message: Converge failed on instance <default-centos-7>.  Please see .kitchen/logs/default-centos-7.log for more details
D      ----------------------
D      ------Backtrace-------
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/provisioner/base.rb:100:in `rescue in call'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/provisioner/base.rb:99:in `call'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:419:in `block in converge_action'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:563:in `synchronize_or_call'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:524:in `block in action'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:523:in `action'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:414:in `converge_action'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:392:in `block (2 levels) in transition_to'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/lifecycle_hooks.rb:47:in `run_with_hooks'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:391:in `block in transition_to'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:390:in `each'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:390:in `transition_to'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:139:in `converge'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:195:in `public_send'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:195:in `run_action_in_thread'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:166:in `block (2 levels) in run_action'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: SSH exited (1) for command: [sh -c '
TEST_KITCHEN="1"; export TEST_KITCHEN
sudo -E /opt/cinc/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889

' && sh -c '
TEST_KITCHEN="1"; export TEST_KITCHEN
sudo -E /opt/cinc/bin/chef-client --local-mode --config /tmp/kitchen/client_no_updated_resources.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889
']
D      ----------------------
D      ------Backtrace-------
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/provisioner/base.rb:100:in `rescue in call'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/provisioner/base.rb:99:in `call'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:419:in `block in converge_action'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:563:in `synchronize_or_call'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:524:in `block in action'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:523:in `action'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:414:in `converge_action'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:392:in `block (2 levels) in transition_to'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/lifecycle_hooks.rb:47:in `run_with_hooks'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:391:in `block in transition_to'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:390:in `each'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:390:in `transition_to'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:139:in `converge'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:195:in `public_send'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:195:in `run_action_in_thread'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:166:in `block (2 levels) in run_action'
D      C:/cinc-project/cinc-workstation/embedded/lib/ruby/gems/3.0.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D      ----End Backtrace-----
```

**Comment by jakauppila** [comment]
This can be kicked over to the test-kitchen repo if it belongs there, but it looked like it was an issue on the Chef side.
