### ISSUE TITLE
win32-certstore updates broke the windows_certificate resource

### ISSUE THREAD

**Issue by jasonwbarnett** [chef/chef#12881]
## Description

recently `win32-certstore` was [updated in the chef Gemfile.lock from v0.6.2 to v0.6.10][1]. The MINOR release (semver) of `win32-certstore` has a backwards incompatible change and should have been released as a major version change. The API change caused downstream problems to chef.

[CI job with details][2]

## Chef Version

main branch

## Platform Version

Windows 2019 and 2022

## Replication Case

Use `windows_certificate` from main branch build of chef infra client.

## Client Output

```text
  * windows_certificate[c:/mordor/steveb.pfx] action create
    
    ================================================================================
    Error executing action `create` on resource 'windows_certificate[c:/mordor/steveb.pfx]'
    ================================================================================
    
    ArgumentError
    -------------
    wrong number of arguments (given 2, expected 1)
    
    Resource Declaration:
    ---------------------
    # In C:/Users/runneradmin/.chef/local-mode-cache/cache/cookbooks/end_to_end/recipes/windows.rb
    
    164: windows_certificate "c:/mordor/steveb.pfx" do
    165:   sensitive false # For debugging
    166:   pfx_password "1234"
    167:   action :create
    168:   user_store true
    169:   store_name "MY"
    170: end
    171: 
    
    Compiled Resource:
    ------------------
    # Declared in C:/Users/runneradmin/.chef/local-mode-cache/cache/cookbooks/end_to_end/recipes/windows.rb:164:in `from_file'
    
    windows_certificate("c:/mordor/steveb.pfx") do
      action [:create]
      default_guard_interpreter :default
      declared_type :windows_certificate
      cookbook_name "end_to_end"
      recipe_name "windows"
      sensitive false
      pfx_password "1234"
      user_store true
      store_name "MY"
      source "c:/mordor/steveb.pfx"
    end
    
    System Info:
    ------------
    chef_version=18.0.94
    platform=windows
    platform_version=10.0.20348
    ruby=ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]
    program_name=C:/opscode/chef/bin/chef-client
    executable=C:/opscode/chef/bin/chef-client
```

## Stacktrace

```text
[2022-05-12T00:10:13+00:00] FATAL: ArgumentError: windows_certificate[c:/mordor/steveb.pfx] (end_to_end::windows line 164) had an error: ArgumentError: wrong number of arguments (given 2, expected 1)
Generated at 2022-05-12 00:10:13 +0000
ArgumentError: windows_certificate[c:/mordor/steveb.pfx] (end_to_end::windows line 164) had an error: ArgumentError: wrong number of arguments (given 2, expected 1)
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/win32-certstore-0.6.10/lib/win32/certstore.rb:120:in `valid?'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/resource/windows_certificate.rb:281:in `verify_cert'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/resource/windows_certificate.rb:488:in `block in import_certificates'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/resource/windows_certificate.rb:482:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/resource/windows_certificate.rb:482:in `import_certificates'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/resource/windows_certificate.rb:103:in `block in <class:WindowsCertificate>'
(eval):2:in `block in action_create'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/provider.rb:304:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/provider.rb:304:in `compile_and_converge_action'
(eval):2:in `action_create'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/provider.rb:245:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/resource.rb:601:in `block in run_action'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/resource.rb:628:in `with_umask'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/resource.rb:600:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/runner.rb:74:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/runner.rb:108:in `block in run_all_actions'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/runner.rb:108:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/runner.rb:108:in `run_all_actions'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/runner.rb:132:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/3.0.0/forwardable.rb:238:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/runner.rb:130:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/client.rb:788:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/client.rb:783:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/client.rb:783:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/client.rb:807:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/client.rb:289:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/application.rb:281:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/local_mode.rb:42:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/application.rb:264:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/application/base.rb:352:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-18.0.94-universal-mingw32/lib/chef/application.rb:67:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-bin-18.0.94/bin/chef-client:25:in `<top (required)>'
C:/opscode/chef/bin/chef-client:197:in `load'
C:/opscode/chef/bin/chef-client:197:in `<main>'
```

[1]: https://github.com/chef/chef/commit/912a6a461e7be743431aeb22f68db11e90c5865f
[2]: https://github.com/chef/chef/runs/6397725450?check_suite_focus=true

**Comment by growingtara** [comment]
hi - could you kindly update the latest status on this issue? We see similar err from Chef v16.16.13 when trying to grant read-only permission to service account for private key. Thank you.

windows_certificate 'C:\temp\test.pfx' do
  pfx_password         'test_password'
  private_key_acl      ["domain\svc_acct"]
end

>>>  .. action create (up to date) #without pk read-only permission granted

windows_certificate 'C:\temp\test.pfx' do
  pfx_password         'test_password'
  private_key_acl      ["domain\svc_acct"]
  action :acl_add
end

>>> [2023-02-10T03:12:12+00:00] FATAL: ArgumentError: windows_certificate[C:\temp\test.pfx] (cookbook::default line 1) had an error: ArgumentError: wrong number of arguments (given 2, expected 1)

**Comment by PrajaktaPurohit** [comment]
Sorry for the delay in responding to this issue, The original issue has since been fixed in the [win32_certstore](https://github.com/chef/win32-certstore/commit/93ae085c1e035b23b5e59380f5de09dc3f07480c) repo.
[Chef-18](https://www.chef.io/downloads/tools/infra-client?v=18.1.0) uses 0.6.15 of win32-certstore that contains the fix.
Chef-17 is currently in works for getting shaped up for a release, the upcoming release will contain the fix for the issue.
We do not have an exact date for the release of Chef-17 yet.

**Comment by jaymzh** [comment]
Closed with attached PRs.
