### ISSUE TITLE
windows_task execution_time_limit crashes when defined in minutes / ISO8601 /

### ISSUE THREAD

**Issue by hunter86bg** [chef/chef#13012]
## Description
When setting execution_time_limit in a  windows_task , the recipe crash.

## Chef Version
Test system:
Windows 2012R2 with chef-client-17.10.3-1-x64.msi on it.

Client system (where chef-kitchen is executed):
Chef Workstation version: 22.6.973
Chef InSpec version: 4.56.20
Chef CLI version: 5.6.1
Chef Habitat version: 1.6.420
Test Kitchen version: 3.2.2
Cookstyle version: 7.32.1
Chef Infra Client version: 17.10.0

## Platform Version

Test system:
Windows 2012R2 with chef-client-17.10.3-1-x64.msi on it.

Client system (where chef-kitchen is executed):
Chef Workstation version: 22.6.973
Chef InSpec version: 4.56.20
Chef CLI version: 5.6.1
Chef Habitat version: 1.6.420
Test Kitchen version: 3.2.2
Cookstyle version: 7.32.1
Chef Infra Client version: 17.10.0

## Replication Case
1. Install Windows 2012R2 VHD from [Microsoft](https://go.microsoft.com/fwlink/p/?linkid=2195588&clcid=0x409&culture=en-us&country=us)
2. Activate Hyper-V on Windows 10 (21H2/ OS Build 19044.1766)
3. Create a new VM and attach the disk
4. Use default switch (if connectivity is broken , create an internal one)
5. Start the 2012R2, set a user and a password
6. Upload and install the chef-client (chef-client-17.10.3-1-x64.msi) on the 2012R2
7. Allow winrm from the client system (win10 21H2) over the IP:
```
Set-Item WSMan:\localhost\Client\TrustedHosts -Value '172.26.121.*'
```
8.Test winrm connectivity
```
$cred = Get-Credential
Enter-PSSession -Computername <VMIP> -Authentication Negotiate -Credential $cred
```
9. Create cookbook & recipe
```
chef generate cookbook mycookbook
cd mycookbook
chef generate recipe myrecipe
```
10. Create recipe like this:
```
directory 'web_scripts' do
  inherits                   true
  mode                       '0777'
  path                       'C:\\scripts\\web\\'
  recursive                  true
  action                     :create
end

cookbook_file 'mypowershell_script.ps1' do
  atomic_update              true
  backup                     false
  inherits                   true
  mode                       '0777'
  path                       'C:\\scripts\\web\\mypowershell_script.ps1'
  source                     'mypowershell_script.ps1'
  action                     :create
  notifies                   :create, 'directory[web_scripts]', :before
end

windows_task 'webtask' do
  user 'SYSTEM'
  run_level :highest
  frequency :daily
  start_time '09:50'
  execution_time_limit PT10M 
  command 'powershell.exe -ExecutionPolicy Bypass -File "C:\\scripts\\web\\mypowershell_script.ps1"'
  guard_interpreter :powershell_script
  force true
  only_if 'Test-Path "C:\\scripts\\web\\mypowershell_script.ps1"'
  # notifies :create, 'cookbook_file[mypowershell_script.ps1]', :before
end
```
11. Create kitchen's yml (replace IP, username and pass)
```
---
provisioner:
  name: chef_zero
  log_level: debug


verifier:
  name: inspec


platforms:
  - name: windows-2012R2
    os_type: windows
    shell_type: powershell
    transport:
      name: winrm
      elevated: true
      username: 'user'
      password: 'pass'
      hostname: 'ip_of_VM'
    driver:
      box: windows-2012r2


suites:
  - name: myrecipe
    run_list:
      - recipe[myrecipe]

```
12. Create a file in cookbook_dir/files that is named "mypowershell_script.ps1"
13. Execute kitchen 
```
kitchen converge -l debug
```
15. Verify the task on the  2012R2 system

 
## Client Output
https://gist.githubusercontent.com/hunter86bg/da95ceedd0b401ebf01872807841fb6d/raw/177a9637c1ccfe3d71e28c07465c2d682750d0ec/windows_task%2520execution_time_limit%2520tracebacks%2520on%2520ISO8601%2520duration%2520format

## Backtrace
```
D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:181:in `report_errors'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:172:in `run_action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command/action.rb:35:in `block in call'
D      C:/opscode/chef-workstation/embedded/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command/action.rb:33:in `call'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/cli.rb:52:in `perform'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/cli.rb:198:in `block (2 levels) in <class:CLI>'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/bin/kitchen:11:in `block in <top (required)>'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/errors.rb:183:in `with_friendly_errors'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/bin/kitchen:11:in `<top (required)>'
D      C:/opscode/chef-workstation/bin/kitchen:408:in `load'
D      C:/opscode/chef-workstation/bin/kitchen:408:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::InstanceFailure
D      Message: Converge failed on instance <myrecipe-windows-2012R2>.  Please see .kitchen/logs/myrecipe-windows-2012R2.log for more details
D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/provisioner/base.rb:100:in `rescue in call'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/provisioner/base.rb:99:in `call'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:419:in `block in converge_action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:563:in `synchronize_or_call'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:524:in `block in action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:523:in `action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:414:in `converge_action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:392:in `block (2 levels) in transition_to'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/lifecycle_hooks.rb:47:in `run_with_hooks'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:391:in `block in transition_to'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:390:in `each'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:390:in `transition_to'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:139:in `converge'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:195:in `public_send'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:195:in `run_action_in_thread'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:166:in `block (2 levels) in run_action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: WinRM exited (1) for command: [$env:TEST_KITCHEN = "1"
$env:PATH = try {
[System.Environment]::GetEnvironmentVariable('PATH','Machine')
} catch { $env:PATH }

& $env:systemdrive\opscode\chef\bin\chef-client.bat --local-mode --config $env:TEMP\kitchen\client.rb --log_level debug --force-formatter --no-color --json-attributes $env:TEMP\kitchen\dna.json --chef-zero-port 8889 ; exit $LastExitCode]
D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/provisioner/base.rb:100:in `rescue in call'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/provisioner/base.rb:99:in `call'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:419:in `block in converge_action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:563:in `synchronize_or_call'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:524:in `block in action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:523:in `action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:414:in `converge_action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:392:in `block (2 levels) in transition_to'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/lifecycle_hooks.rb:47:in `run_with_hooks'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:391:in `block in transition_to'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:390:in `each'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:390:in `transition_to'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:139:in `converge'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:195:in `public_send'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:195:in `run_action_in_thread'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:166:in `block (2 levels) in run_action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D      ----End Backtrace-----
```

Workaround:
Set execution_time_limit in seconds (600).

**Comment by johnmccrae** [comment]
Yeah, this was totally borked. Whoever wrote this nonsense didn't actually add any code to convert or interpret ANYTHING into ISO8601 format except the default 72 hour limit. That was total nonsense. We're downgrading
