### ISSUE TITLE
cookbook_file crashes when copying file ending on ".dll" to a Windows 2012R2

### ISSUE THREAD

**Issue by hunter86bg** [chef/chef#13013]
## Description
When copying a ".dll" file, the recipe crashes.

## Chef Version
Test system:
Windows 2012R2 with chef-client-17.10.3-1-x64.msi on it.

Client system (where chef-kitchen is executed):
Chef Workstation version: 22.6.973
Chef InSpec version: 4.56.20
Chef CLI version: 5.6.1
Chef Habitat version: 1.6.420
Test Kitchen version: 3.2.2
Cookstyle version: 7.32.1
Chef Infra Client version: 17.10.0

## Platform Version

Test system:
Windows 2012R2 with chef-client-17.10.3-1-x64.msi on it.

Client system (where chef-kitchen is executed):
Chef Workstation version: 22.6.973
Chef InSpec version: 4.56.20
Chef CLI version: 5.6.1
Chef Habitat version: 1.6.420
Test Kitchen version: 3.2.2
Cookstyle version: 7.32.1
Chef Infra Client version: 17.10.0

## Replication Case
1. Install Windows 2012R2 VHD from [Microsoft](https://go.microsoft.com/fwlink/p/?linkid=2195588&clcid=0x409&culture=en-us&country=us)
2. Activate Hyper-V on Windows 10 (21H2/ OS Build 19044.1766)
3. Create a new VM and attach the disk
4. Use default switch (if connectivity is broken , create an internal one)
5. Start the 2012R2, set a user and a password
6. Upload and install the chef-client (chef-client-17.10.3-1-x64.msi) on the 2012R2
7. Allow winrm from the client system (win10 21H2) over the IP:
```
Set-Item WSMan:\localhost\Client\TrustedHosts -Value '172.26.121.*'
```
8.Test winrm connectivity
```
$cred = Get-Credential
Enter-PSSession -Computername <VMIP> -Authentication Negotiate -Credential $cred
```
9. Create cookbook & recipe
```
chef generate cookbook mycookbook
cd mycookbook
chef generate recipe myrecipe
```
10. Create recipe like this:
```
cookbook_file 'mydllfile.dll' do
  atomic_update              true
  backup                     false
  inherits                   true
  mode                       '0777'
  path                       'C:\\mydllfile.dll'
  source                     'mydllfile.dll'
  action                     :create
end
```
11. Create kitchen's yml (replace IP, username and pass)
```
---
provisioner:
  name: chef_zero
  log_level: debug


verifier:
  name: inspec


platforms:
  - name: windows-2012R2
    os_type: windows
    shell_type: powershell
    transport:
      name: winrm
      elevated: true
      username: 'user'
      password: 'pass'
      hostname: 'ip_of_VM'
    driver:
      box: windows-2012r2


suites:
  - name: myrecipe
    run_list:
      - recipe[myrecipe]

```
12. Copy a dll file named "mydllfile.dll" into cookbook/files
13. Execute kitchen 
```
kitchen converge -l debug
```

 
## Client Output
https://gist.githubusercontent.com/hunter86bg/32b4163fe4d132125cd4fe241c6cdac2/raw/09a115c3c276fbdd7485ac71e21e422703a8e630/cookbook_file%2520dll%2520crash

## backtrace
D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:181:in `report_errors'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:172:in `run_action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command/action.rb:35:in `block in call'
D      C:/opscode/chef-workstation/embedded/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command/action.rb:33:in `call'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/cli.rb:52:in `perform'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/cli.rb:198:in `block (2 levels) in <class:CLI>'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/bin/kitchen:11:in `block in <top (required)>'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/errors.rb:183:in `with_friendly_errors'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/bin/kitchen:11:in `<top (required)>'
D      C:/opscode/chef-workstation/bin/kitchen:408:in `load'
D      C:/opscode/chef-workstation/bin/kitchen:408:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::InstanceFailure
D      Message: Converge failed on instance <mycookbook-windows-2012R2>.  Please see .kitchen/logs/mycookbook-windows-2012R2.log for more details
D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/provisioner/base.rb:100:in `rescue in call'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/provisioner/base.rb:99:in `call'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:419:in `block in converge_action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:563:in `synchronize_or_call'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:524:in `block in action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:523:in `action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:414:in `converge_action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:392:in `block (2 levels) in transition_to'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/lifecycle_hooks.rb:47:in `run_with_hooks'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:391:in `block in transition_to'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:390:in `each'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:390:in `transition_to'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:139:in `converge'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:195:in `public_send'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:195:in `run_action_in_thread'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:166:in `block (2 levels) in run_action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: WinRM exited (1) for command: [$env:TEST_KITCHEN = "1"
$env:PATH = try {
[System.Environment]::GetEnvironmentVariable('PATH','Machine')
} catch { $env:PATH }

& $env:systemdrive\opscode\chef\bin\chef-client.bat --local-mode --config $env:TEMP\kitchen\client.rb --log_level debug --force-formatter --no-color --json-attributes $env:TEMP\kitchen\dna.json --chef-zero-port 8889 ; exit $LastExitCode]
D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/provisioner/base.rb:100:in `rescue in call'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/provisioner/base.rb:99:in `call'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:419:in `block in converge_action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:563:in `synchronize_or_call'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:524:in `block in action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:523:in `action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:414:in `converge_action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:392:in `block (2 levels) in transition_to'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/lifecycle_hooks.rb:47:in `run_with_hooks'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:391:in `block in transition_to'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:390:in `each'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:390:in `transition_to'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/instance.rb:139:in `converge'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:195:in `public_send'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:195:in `run_action_in_thread'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/test-kitchen-3.2.2/lib/kitchen/command.rb:166:in `block (2 levels) in run_action'
D      C:/opscode/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/logging-2.3.1/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D      ----End Backtrace-----

**Comment by PrajaktaPurohit** [comment]
Thank you for the detailed bug report! 

We would like to understand what is the specific usecase that you are looking to address by copying the dll using chef?
Is this a blocker for the work that you are doing or do you have a workaround in getting past this issue?

**Comment by hunter86bg** [comment]
It seems that the workaround is to name the file as 'Myfile_dll' and then select that as source.

The use case is to deliver the NuGet Package Provider dll to systems behind firewall, so after that via chef deliver nuget packages locally and via powershell to create a local/internal (behind firewall) Powershell Repo and install those powershell modules (for example IISAdministration)

**Comment by hunter86bg** [comment]
As I was reporting multiple issues at once, I might have mixed the problems, so don't hesitate to ask if something looks odd.

**Comment by jaymzh** [comment]
2012R2 is no longer supported, so going to close this.

**Comment by hunter86bg** [comment]
@jaymzh are you sure it is not affecting newer versions ?

**Comment by jaymzh** [comment]
I don't, but since no one has said anything about it since 2022, and we're trying to clean up a mass of old Issues, we decided to go ahead and close this. If you have reason to believe this is still a problem, please open a new issue.
