### ISSUE TITLE
ConvertTo-SecureString can't find specified path

### ISSUE THREAD

**Issue by matthewdavidson09** [chef/chef#13353]
Running chef-client from Scheduled Task with chef_client_scheduled_task resource. Able to run chef client normally with chef-client.bat, but when run as scheduled task get below error. I get 

LastTaskResult of 1, 

```
PS C:\Windows\system32> Get-ScheduledTask -TaskName chef_run | Get-ScheduledTaskInfo


LastRunTime        : 11/10/2022 10:49:49 PM
LastTaskResult     : 1
NextRunTime        : 11/10/2022 11:04:04 PM
NumberOfMissedRuns : 0
TaskName           : chef_run
TaskPath           : \
PSComputerName     :
```

Can run manually, but when run as task, either time based or on-demand get below stacktrace. 
```
ChefPowerShell::PowerShellExceptions::PowerShellCommandFailed: Unexpected exit in PowerShell command: ["ConvertTo-SecureString: The system cannot find the path specified.\r\n\nAt line:1 char:363\r\n+ ... 0004eceb625b9fe69b03ea
837c8c2ea29a6e677d30d\" | ConvertTo-SecureString\r\n+                                                    ~~~~~~~~~~~~~~~~~~~~~~", ": Exception calling \"SecureStringToBSTR\" with \"1\" argument(s): \"Value cannot be null.\r\nP
arameter name: s\"\nAt line:2 char:1\r\n+ $string = [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"]
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-powershell-1.0.13/lib/chef-powershell/powershell.rb:63:in `error!'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-powershell-1.0.13/lib/chef-powershell/powershell_exec.rb:128:in `powershell_exec!'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169-x64-mingw-ucrt/lib/chef/http/authenticator.rb:215:in `decrypt_pfx_pass'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169-x64-mingw-ucrt/lib/chef/http/authenticator.rb:177:in `block in get_cert_password'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169-x64-mingw-ucrt/lib/chef/http/authenticator.rb:175:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169-x64-mingw-ucrt/lib/chef/http/authenticator.rb:175:in `get_cert_password'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169-x64-mingw-ucrt/lib/chef/http/authenticator.rb:222:in `retrieve_certificate_key'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169-x64-mingw-ucrt/lib/chef/http/authenticator.rb:98:in `retrieve_certificate_key'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169-x64-mingw-ucrt/lib/chef/http/authenticator.rb:140:in `load_signing_key'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169-x64-mingw-ucrt/lib/chef/http/authenticator.rb:45:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169-x64-mingw-ucrt/lib/chef/http.rb:104:in `new'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169-x64-mingw-ucrt/lib/chef/http.rb:104:in `block in initialize'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169-x64-mingw-ucrt/lib/chef/http.rb:103:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169-x64-mingw-ucrt/lib/chef/http.rb:103:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169-x64-mingw-ucrt/lib/chef/server_api.rb:40:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169-x64-mingw-ucrt/lib/chef/client.rb:393:in `new'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169-x64-mingw-ucrt/lib/chef/client.rb:393:in `rest'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169-x64-mingw-ucrt/lib/chef/client.rb:266:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169-x64-mingw-ucrt/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169-x64-mingw-ucrt/lib/chef/application.rb:281:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169-x64-mingw-ucrt/lib/chef/local_mode.rb:42:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169-x64-mingw-ucrt/lib/chef/application.rb:264:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169-x64-mingw-ucrt/lib/chef/application/base.rb:352:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169-x64-mingw-ucrt/lib/chef/application.rb:67:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-bin-18.0.169/bin/chef-client:25:in `<top (required)>'
C:/opscode/chef/bin/chef-client:197:in `load'
C:/opscode/chef/bin/chef-client:197:in `<main>'
```

**Comment by matthewdavidson09** [comment]
This is on Chef Client v 18.0.169. 

```
PS C:\Windows\system32> chef-client --version
Chef Infra Client: 18.0.169
```

Works properly on Chef Client v 17.10.3

**Comment by rcorning** [comment]
@matthewdavidson09 hey i ran into this issue and this was the only thread I could find. If you're still having issues i'll let you know what i did.

For me, the issue was that i installed this with chocolatey and chocolatey needs an elevated terminal to install chef-workstation. The problem was that in my scenario, the elevated terminal installed it under a different administrator user. However, all of my chef cli runs were with a different user. So in order to fix that, I added an environment variable for chef_dir to the admin account that did the chef workstation install and set it to the chef directory for the non admin account. Now I can do converges and knife commands without issue.

For your use case, whatever admin account is the account that installed chef workstation needs to be the account configured to run the scheduled task itself.  Hope that helps.
