### ISSUE TITLE
rhsm_register fails when release is not set

### ISSUE THREAD

**Issue by ianl678** [chef/chef#13351]
## Description
rhsm_register fails when release is not set

## Chef Version
chef-18.0.169

## Platform Version
RHEL9

## Replication Case
Create an activation key using RedHat EUS repos only
Do not specify the release version in the key
Register using rhsm_register

## Client Output

```
Recipe: COOKBOOKNAME::configure
         * rhsm_register[name] action register[2022-11-10T20:43:32+00:00] INFO: Processing rhsm_register[name] action register (COOKBOOKNAME::configure line 139)
       
           * dnf_package[subscription-manager] action install[2022-11-10T20:43:32+00:00] INFO: Processing dnf_package[subscription-manager] action install (COOKBOOKNAME::configure line 99)
        (up to date)
           * dnf_package[rhsm_register-name-flush_cache] action nothing[2022-11-10T20:43:34+00:00] INFO: Processing dnf_package[rhsm_register-name-flush_cache] action nothing (COOKBOOKNAME::configure line 120)
        (skipped due to action :nothing)
           * execute[Register to RHSM] action run[2022-11-10T20:43:34+00:00] INFO: Processing execute[Register to RHSM] action run (COOKBOOKNAME::configure line 124)
       
             [execute] The system has been registered with ID: 11df3736-718b-4f35-b9de-b12f4bd24968
                The registered system name is: kitchen-satellite-obm-rhel9.vagrantup.com
                Installed Product Current Status:
                Product Name: Red Hat Enterprise Linux for x86_64
                Status:       Subscribed
                
       [2022-11-10T20:43:39+00:00] INFO: execute[Register to RHSM] ran successfully
             - execute subscription-manager register --activationkey=ACTIVATION_KEY --org=ORGNAME
       [2022-11-10T20:43:39+00:00] INFO: execute[Register to RHSM] sending flush_cache action to dnf_package[rhsm_register-name-flush_cache] (immediate)
           * dnf_package[rhsm_register-name-flush_cache] action flush_cache[2022-11-10T20:43:39+00:00] INFO: Processing dnf_package[rhsm_register-name-flush_cache] action flush_cache (COOKBOOKNAME::configure line 120)
        (up to date)
           
           ================================================================================
           Error executing action `flush_cache` on resource 'dnf_package[rhsm_register-name-flush_cache]'
           ================================================================================
           
           RuntimeError
           ------------
           dnf-helper.py had stderr/stdout output:
           
           Errors during downloading metadata for repository 'codeready-builder-for-rhel-9-x86_64-eus-rpms':
             - Status code: 404 for https://SATELLITENAME.DOMAIN.ORGNAME.com.au/pulp/content/ORGNAME/Production/CV_NAME/content/eus/rhel9/9/x86_64/codeready-builder/os/repodata/repomd.xml (IP: IPADDR)
           Traceback (most recent call last):
             File "/usr/lib/python3.9/site-packages/dnf/repo.py", line 573, in load
        ret = self._repo.load()
             File "/usr/lib64/python3.9/site-packages/libdnf/repo.py", line 331, in load
        return _repo.Repo_load(self)
           libdnf._error.Error: Failed to download metadata for repo 'codeready-builder-for-rhel-9-x86_64-eus-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
           
           During handling of the above exception, another exception occurred:
           
           Traceback (most recent call last):
             File "/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169/lib/chef/provider/package/dnf/dnf_helper.py", line 182, in <module>
        query(command)
             File "/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169/lib/chef/provider/package/dnf/dnf_helper.py", line 89, in query
        sack = get_sack()
             File "/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169/lib/chef/provider/package/dnf/dnf_helper.py", line 44, in get_sack
        base.fill_sack(load_system_repo='auto')
             File "/usr/lib/python3.9/site-packages/dnf/base.py", line 399, in fill_sack
        self._add_repo_to_sack(r)
             File "/usr/lib/python3.9/site-packages/dnf/base.py", line 139, in _add_repo_to_sack
        repo.load()
             File "/usr/lib/python3.9/site-packages/dnf/repo.py", line 580, in load
        raise dnf.exceptions.RepoError(str(e))
           dnf.exceptions.RepoError: Failed to download metadata for repo 'codeready-builder-for-rhel-9-x86_64-eus-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
           
           Resource Declaration:
           ---------------------
           # In /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169/lib/chef/resource/rhsm_register.rb
           
           120:         package flush_package_cache_name do
           121:           action :nothing
           122:         end
           123: 
           
           Compiled Resource:
           ------------------
           # Declared in /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169/lib/chef/resource/rhsm_register.rb:120:in `block in <class:RhsmRegister>'
           
           dnf_package("rhsm_register-name-flush_cache") do
             package_name "rhsm_register-name-flush_cache"
             action [:nothing]
             default_guard_interpreter :default
             declared_type :package
             cookbook_name "COOKBOOKNAME"
             recipe_name "configure"
             flush_cache {:before=>false, :after=>false}
           end
           
           System Info:
           ------------
           chef_version=18.0.169
           platform=redhat
           platform_version=9.0
           ruby=ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
           program_name=/opt/chef/bin/chef-client
           executable=/opt/chef/bin/chef-client
           
       [2022-11-10T20:43:44+00:00] INFO: Retrying execution of rhsm_register[name], 0 attempt left
         * dnf_package[subscription-manager] action install[2022-11-10T20:43:46+00:00] INFO: Processing dnf_package[subscription-manager] action install (COOKBOOKNAME::configure line 99)
       
           
           ================================================================================
           Error executing action `install` on resource 'dnf_package[subscription-manager]'
           ================================================================================
           
           RuntimeError
           ------------
           dnf-helper.py had stderr/stdout output:
           
           Errors during downloading metadata for repository 'codeready-builder-for-rhel-9-x86_64-eus-rpms':
             - Status code: 404 for https://SATELLITENAME.DOMAIN.ORGNAME.com.au/pulp/content/ORGNAME/Production/CV_NAME/content/eus/rhel9/9/x86_64/codeready-builder/os/repodata/repomd.xml (IP: IPADDR)
           Traceback (most recent call last):
             File "/usr/lib/python3.9/site-packages/dnf/repo.py", line 573, in load
        ret = self._repo.load()
             File "/usr/lib64/python3.9/site-packages/libdnf/repo.py", line 331, in load
        return _repo.Repo_load(self)
           libdnf._error.Error: Failed to download metadata for repo 'codeready-builder-for-rhel-9-x86_64-eus-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
           
           During handling of the above exception, another exception occurred:
           
           Traceback (most recent call last):
             File "/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169/lib/chef/provider/package/dnf/dnf_helper.py", line 182, in <module>
        query(command)
             File "/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169/lib/chef/provider/package/dnf/dnf_helper.py", line 89, in query
        sack = get_sack()
             File "/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169/lib/chef/provider/package/dnf/dnf_helper.py", line 44, in get_sack
        base.fill_sack(load_system_repo='auto')
             File "/usr/lib/python3.9/site-packages/dnf/base.py", line 399, in fill_sack
        self._add_repo_to_sack(r)
             File "/usr/lib/python3.9/site-packages/dnf/base.py", line 139, in _add_repo_to_sack
        repo.load()
             File "/usr/lib/python3.9/site-packages/dnf/repo.py", line 580, in load
        raise dnf.exceptions.RepoError(str(e))
           dnf.exceptions.RepoError: Failed to download metadata for repo 'codeready-builder-for-rhel-9-x86_64-eus-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
           
           Resource Declaration:
           ---------------------
           # In /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169/lib/chef/resource/rhsm_register.rb
           
            99:         package "subscription-manager"
           100: 
           
           Compiled Resource:
           ------------------
           # Declared in /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169/lib/chef/resource/rhsm_register.rb:99:in `block in <class:RhsmRegister>'
           
           dnf_package("subscription-manager") do
             package_name "subscription-manager"
             action [:install]
             default_guard_interpreter :default
             declared_type :package
             cookbook_name "COOKBOOKNAME"
             recipe_name "configure"
             flush_cache {:before=>false, :after=>false}
           end
           
           System Info:
           ------------
           chef_version=18.0.169
           platform=redhat
           platform_version=9.0
           ruby=ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
           program_name=/opt/chef/bin/chef-client
           executable=/opt/chef/bin/chef-client
           
         
         ================================================================================
         Error executing action `register` on resource 'rhsm_register[name]'
         ================================================================================
         
         RuntimeError
         ------------
         dnf_package[subscription-manager] (COOKBOOKNAME::configure line 99) had an error: RuntimeError: dnf-helper.py had stderr/stdout output:
         
         Errors during downloading metadata for repository 'codeready-builder-for-rhel-9-x86_64-eus-rpms':
           - Status code: 404 for https://SATELLITENAME.DOMAIN.ORGNAME.com.au/pulp/content/ORGNAME/Production/CV_NAME/content/eus/rhel9/9/x86_64/codeready-builder/os/repodata/repomd.xml (IP: IPADDR)
         Traceback (most recent call last):
           File "/usr/lib/python3.9/site-packages/dnf/repo.py", line 573, in load
             ret = self._repo.load()
           File "/usr/lib64/python3.9/site-packages/libdnf/repo.py", line 331, in load
             return _repo.Repo_load(self)
         libdnf._error.Error: Failed to download metadata for repo 'codeready-builder-for-rhel-9-x86_64-eus-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
         
         During handling of the above exception, another exception occurred:
         
         Traceback (most recent call last):
           File "/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169/lib/chef/provider/package/dnf/dnf_helper.py", line 182, in <module>
             query(command)
           File "/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169/lib/chef/provider/package/dnf/dnf_helper.py", line 89, in query
             sack = get_sack()
           File "/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169/lib/chef/provider/package/dnf/dnf_helper.py", line 44, in get_sack
             base.fill_sack(load_system_repo='auto')
           File "/usr/lib/python3.9/site-packages/dnf/base.py", line 399, in fill_sack
             self._add_repo_to_sack(r)
           File "/usr/lib/python3.9/site-packages/dnf/base.py", line 139, in _add_repo_to_sack
             repo.load()
           File "/usr/lib/python3.9/site-packages/dnf/repo.py", line 580, in load
             raise dnf.exceptions.RepoError(str(e))
         dnf.exceptions.RepoError: Failed to download metadata for repo 'codeready-builder-for-rhel-9-x86_64-eus-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
         
         Resource Declaration:
         ---------------------
         # In /tmp/kitchen/cache/cookbooks/COOKBOOKNAME/recipes/configure.rb
         
         139: rhsm_register 'name' do
         140:   activation_key combined_key
         141:   organization node[ATTR]['organization']
         142:   install_katello_agent false
         143:   retries node[ATTR]['retries']
         144:   ignore_failure node[ATTR]['ignore_registration_failure'].to_s.downcase == 'true'
         145:   action :register
         146:   only_if { node['packages'].key?(required_package_name) }
         147: end
         148: 
         
         Compiled Resource:
         ------------------
         # Declared in /tmp/kitchen/cache/cookbooks/COOKBOOKNAME/recipes/configure.rb:139:in `from_file'
         
         rhsm_register("name") do
           action [:register]
           updated true
           updated_by_last_action true
           default_guard_interpreter :default
           declared_type :rhsm_register
           cookbook_name "COOKBOOKNAME"
           recipe_name "configure"
           activation_key ["ACTIVATION_KEY"]
           organization "ORGNAME"
           retries 1
           only_if { #code block }
         end
         
         System Info:
         ------------
         chef_version=18.0.169
         platform=redhat
         platform_version=9.0
         ruby=ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
         program_name=/opt/chef/bin/chef-client
         executable=/opt/chef/bin/chef-client
         
       [2022-11-10T20:43:51+00:00] INFO: Running queued delayed notifications before re-raising exception
       
       Running handlers:
       [2022-11-10T20:43:51+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2022-11-10T20:43:51+00:00] ERROR: Exception handlers complete
       Infra Phase failed. 1 resources updated in 21 seconds
       [2022-11-10T20:43:51+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2022-11-10T20:43:51+00:00] FATAL: ---------------------------------------------------------------------------------------
       [2022-11-10T20:43:51+00:00] FATAL: PLEASE PROVIDE THE CONTENTS OF THE stacktrace.out FILE (above) IF YOU FILE A BUG REPORT
       [2022-11-10T20:43:51+00:00] FATAL: ---------------------------------------------------------------------------------------
       [2022-11-10T20:43:51+00:00] FATAL: RuntimeError: rhsm_register[name] (COOKBOOKNAME::configure line 139) had an error: RuntimeError: dnf_package[subscription-manager] (COOKBOOKNAME::configure line 99) had an error: RuntimeError: dnf-helper.py had stderr/stdout output:
       
       Errors during downloading metadata for repository 'codeready-builder-for-rhel-9-x86_64-eus-rpms':
         - Status code: 404 for https://SATELLITENAME.DOMAIN.ORGNAME.com.au/pulp/content/ORGNAME/Production/CV_NAME/content/eus/rhel9/9/x86_64/codeready-builder/os/repodata/repomd.xml (IP: IPADDR)
       Traceback (most recent call last):
         File "/usr/lib/python3.9/site-packages/dnf/repo.py", line 573, in load
           ret = self._repo.load()
         File "/usr/lib64/python3.9/site-packages/libdnf/repo.py", line 331, in load
           return _repo.Repo_load(self)
       libdnf._error.Error: Failed to download metadata for repo 'codeready-builder-for-rhel-9-x86_64-eus-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
       
       During handling of the above exception, another exception occurred:
       
       Traceback (most recent call last):
         File "/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169/lib/chef/provider/package/dnf/dnf_helper.py", line 182, in <module>
           query(command)
         File "/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169/lib/chef/provider/package/dnf/dnf_helper.py", line 89, in query
           sack = get_sack()
         File "/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169/lib/chef/provider/package/dnf/dnf_helper.py", line 44, in get_sack
           base.fill_sack(load_system_repo='auto')
         File "/usr/lib/python3.9/site-packages/dnf/base.py", line 399, in fill_sack
           self._add_repo_to_sack(r)
         File "/usr/lib/python3.9/site-packages/dnf/base.py", line 139, in _add_repo_to_sack
           repo.load()
         File "/usr/lib/python3.9/site-packages/dnf/repo.py", line 580, in load
           raise dnf.exceptions.RepoError(str(e))
       dnf.exceptions.RepoError: Failed to download metadata for repo 'codeready-builder-for-rhel-9-x86_64-eus-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
       
```

**Comment by ianl678** [comment]
https://github.com/chef/chef/pull/13352

**Comment by jaymzh** [comment]
Closed by attached PR.
