### ISSUE TITLE
bundler failed to load command knife with Ruby3.2

### ISSUE THREAD

**Issue by fen9li** [chef/chef#13502]
Hey

I come cross an error when trying to upgrade chef client from 17.10.3 (Ruby 3.0)  to 18.1.0 (Ruby 3.2).

## Description
bundler: failed to load command: knife (/home/jenkins/.bundle/vendor/ruby/3.2.0/bin/knife)

## Chef Version
Chef 18.1.0

## Platform Version
ruby:3.2.0-alpine3.17

## Replication Case
Start a container from Ruby 3.2 docker image 'ruby:3.2.0-alpine3.17', install bundler, chef etc. Run command 'bundle exec knife cookbook list'. 

## Client Output
```
[2023-01-16T22:56:17.501Z] + bundle exec knife ssl_fetch https://p-ssvc-01-chef-automate-6oeqevumx98wquce.ap-southeast-2.opsworks-cm.io/ --trace

[2023-01-16T22:56:18.080Z] bundler: failed to load command: knife (/home/jenkins/.bundle/vendor/ruby/3.2.0/bin/knife)

[2023-01-16T22:56:18.080Z] /home/jenkins/.bundle/vendor/ruby/3.2.0/gems/knife-18.1.0/lib/chef/knife/core/gem_glob_loader.rb:81:in `block in find_files_latest_gems': undefined method `untaint' for "/home/jenkins/.bundle/vendor/ruby/3.2.0/gems/knife-18.1.0/lib/chef/knife/acl_add.rb":String (NoMethodError)

[2023-01-16T22:56:18.080Z] 

[2023-01-16T22:56:18.080Z]             end.flatten.select { |file| File.file? file.untaint }

[2023-01-16T22:56:18.080Z]                                                        ^^^^^^^^

[2023-01-16T22:56:18.080Z] 	from /home/jenkins/.bundle/vendor/ruby/3.2.0/gems/knife-18.1.0/lib/chef/knife/core/gem_glob_loader.rb:81:in `select'

[2023-01-16T22:56:18.080Z] 	from /home/jenkins/.bundle/vendor/ruby/3.2.0/gems/knife-18.1.0/lib/chef/knife/core/gem_glob_loader.rb:81:in `find_files_latest_gems'

[2023-01-16T22:56:18.080Z] 	from /home/jenkins/.bundle/vendor/ruby/3.2.0/gems/knife-18.1.0/lib/chef/knife/core/gem_glob_loader.rb:49:in `find_subcommands_via_rubygems'

[2023-01-16T22:56:18.080Z] 	from /home/jenkins/.bundle/vendor/ruby/3.2.0/gems/knife-18.1.0/lib/chef/knife/core/gem_glob_loader.rb:43:in `gem_and_builtin_subcommands'

[2023-01-16T22:56:18.080Z] 	from /home/jenkins/.bundle/vendor/ruby/3.2.0/gems/knife-18.1.0/lib/chef/knife/core/gem_glob_loader.rb:29:in `subcommand_files'

[2023-01-16T22:56:18.080Z] 	from /home/jenkins/.bundle/vendor/ruby/3.2.0/gems/knife-18.1.0/lib/chef/knife/core/subcommand_loader.rb:106:in `load_commands'

[2023-01-16T22:56:18.080Z] 	from /home/jenkins/.bundle/vendor/ruby/3.2.0/gems/knife-18.1.0/lib/chef/knife/core/subcommand_loader.rb:116:in `load_command'

[2023-01-16T22:56:18.080Z] 	from /home/jenkins/.bundle/vendor/ruby/3.2.0/gems/knife-18.1.0/lib/chef/knife/core/subcommand_loader.rb:130:in `command_class_from'

[2023-01-16T22:56:18.080Z] 	from /home/jenkins/.bundle/vendor/ruby/3.2.0/gems/knife-18.1.0/lib/chef/knife.rb:165:in `subcommand_class_from'

[2023-01-16T22:56:18.080Z] 	from /home/jenkins/.bundle/vendor/ruby/3.2.0/gems/knife-18.1.0/lib/chef/knife.rb:228:in `run'

[2023-01-16T22:56:18.080Z] 	from /home/jenkins/.bundle/vendor/ruby/3.2.0/gems/knife-18.1.0/lib/chef/application/knife.rb:165:in `run'

[2023-01-16T22:56:18.080Z] 	from /home/jenkins/.bundle/vendor/ruby/3.2.0/gems/knife-18.1.0/bin/knife:24:in `<top (required)>'

[2023-01-16T22:56:18.080Z] 	from /home/jenkins/.bundle/vendor/ruby/3.2.0/bin/knife:25:in `load'

[2023-01-16T22:56:18.081Z] 	from /home/jenkins/.bundle/vendor/ruby/3.2.0/bin/knife:25:in `<top (required)>'

[2023-01-16T22:56:18.081Z] 	from /usr/local/bundle/gems/bundler-2.4.3/lib/bundler/cli/exec.rb:58:in `load'

[2023-01-16T22:56:18.081Z] 	from /usr/local/bundle/gems/bundler-2.4.3/lib/bundler/cli/exec.rb:58:in `kernel_load'

[2023-01-16T22:56:18.081Z] 	from /usr/local/bundle/gems/bundler-2.4.3/lib/bundler/cli/exec.rb:23:in `run'

[2023-01-16T22:56:18.081Z] 	from /usr/local/bundle/gems/bundler-2.4.3/lib/bundler/cli.rb:491:in `exec'

[2023-01-16T22:56:18.081Z] 	from /usr/local/bundle/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'

[2023-01-16T22:56:18.081Z] 	from /usr/local/bundle/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'

[2023-01-16T22:56:18.081Z] 	from /usr/local/bundle/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'

[2023-01-16T22:56:18.081Z] 	from /usr/local/bundle/gems/bundler-2.4.3/lib/bundler/cli.rb:34:in `dispatch'

[2023-01-16T22:56:18.081Z] 	from /usr/local/bundle/gems/bundler-2.4.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'

[2023-01-16T22:56:18.081Z] 	from /usr/local/bundle/gems/bundler-2.4.3/lib/bundler/cli.rb:28:in `start'

[2023-01-16T22:56:18.081Z] 	from /usr/local/bundle/gems/bundler-2.4.3/exe/bundle:45:in `block in <top (required)>'

[2023-01-16T22:56:18.081Z] 	from /usr/local/bundle/gems/bundler-2.4.3/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'

[2023-01-16T22:56:18.081Z] 	from /usr/local/bundle/gems/bundler-2.4.3/exe/bundle:33:in `<top (required)>'

[2023-01-16T22:56:18.081Z] 	from /usr/local/bundle/bin/bundle:25:in `load'

[2023-01-16T22:56:18.081Z] 	from /usr/local/bundle/bin/bundle:25:in `<main>'

script returned exit code 1
```

**Comment by Noel-Jones** [comment]
A bit of further info, seems that taint checking was removed from Ruby 3.2 https://bugs.ruby-lang.org/issues/16131

**Comment by rmoriz** [comment]
can confirm this bug still exists with Chef 18.3.0 and Ruby 3.2.2
