### ISSUE TITLE
`recipe-url` parameter fails accessing S3 from EC2 instances

### ISSUE THREAD

**Issue by thheinen** [chef/chef#13524]
## Description

Trying to fetch a bundled cookbook via S3 fails if it is supposed to use EC2 instance credentials.

## Chef Version

18.1.0

## Platform Version

Amazon Linux 2 (x86)

## Replication Case

Start EC2 instance, attach IAM role with S3 read access, and deploy cookbook bundle.
Run Chef Infra:

```shell
chef-client --local-mode --recipe-url s3://bucketname/bundlename.tgz --runlist 'recipe[cookbookname]'
```

## Client Output

```
[2023-01-23T11:26:58+00:00] WARN: No config file found or specified on command line. Using command line options instead.
[2023-01-23T11:26:58+00:00] WARN: No cookbooks directory found at or above current directory.  Assuming /opt/chef/embedded/bin.
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.168.4/lib/aws-sdk-core/plugins/regional_endpoint.rb:92:in `after_initialize': No region was provided. Configure the `:region` option or export the region name to ENV['AWS_REGION'] (Aws::Errors::MissingRegionError)
        from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.168.4/lib/seahorse/client/base.rb:81:in `block in after_initialize'
        from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.168.4/lib/seahorse/client/base.rb:80:in `each'
        from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.168.4/lib/seahorse/client/base.rb:80:in `after_initialize'
        from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.168.4/lib/seahorse/client/base.rb:24:in `initialize'
        from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/aws-sdk-s3-1.117.2/lib/aws-sdk-s3/client.rb:452:in `initialize'
        from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/aws-sdk-core-3.168.4/lib/seahorse/client/base.rb:102:in `new'
        from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/application/base.rb:389:in `fetch_recipe_tarball'
        from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/application/client.rb:108:in `reconfigure'
        from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/application.rb:64:in `run'
        from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-bin-18.1.0/bin/chef-client:25:in `<top (required)>'
        from /bin/chef-client:184:in `load'
        from /bin/chef-client:184:in `<main>'
```

The current implementation assumes a configured AWS profile in `~/.aws/config`, containing a `region` statement.

Running Chef Infra on a fresh instance (installing via user-data) does not have this, so a region is unavailable, and the message above is thrown.

**Comment by jaymzh** [comment]
Fixed in attached PR
