### ISSUE TITLE
aws-sdk-ec2 gem broken in infra client 17.x

### ISSUE THREAD

**Issue by drewhammond** [chef/chef#13563]
## Description

In chef infra client 17.x, it is no longer possible to use the latest version of the `aws-sdk-ec2` gem because it conflicts with a pinned dependency in chef-client.

It looks like AWS had to bump the dependency constraints to fix a backwards compatibility problem here https://github.com/aws/aws-sdk-ruby/issues/2774

## Chef Version

Chef Infra Client 17.10.3

## Platform Version

Ubuntu 20.04.5 LTS

## Replication Case

In a recipe:

```ruby
chef_gem 'aws-sdk-ec2' do
  compile_time true
end

require 'aws-sdk-ec2'
```

## Client Output

```
Gem::ConflictError
------------------
Unable to activate aws-sdk-ec2-1.364.0, because aws-sdk-core-3.130.0 conflicts with aws-sdk-core (~> 3, >= 3.165.0)
```

## Stacktrace

```
Gem::ConflictError: Unable to activate aws-sdk-ec2-1.364.0, because aws-sdk-core-3.130.0 conflicts with aws-sdk-core (~> 3, >= 3.165.0)
/opt/chef/embedded/lib/ruby/3.0.0/rubygems/specification.rb:2237:in `raise_if_conflicts'
/opt/chef/embedded/lib/ruby/3.0.0/rubygems/specification.rb:1368:in `activate'
/opt/chef/embedded/lib/ruby/3.0.0/rubygems.rb:221:in `rescue in try_activate'
/opt/chef/embedded/lib/ruby/3.0.0/rubygems.rb:214:in `try_activate'
<internal:/opt/chef/embedded/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:153:in `rescue in require'
<internal:/opt/chef/embedded/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
/var/chef/cache/cookbooks/example/recipes/test.rb:5:in `from_file'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.10.3/lib/chef/mixin/from_file.rb:34:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.10.3/lib/chef/mixin/from_file.rb:34:in `from_file'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.10.3/lib/chef/cookbook_version.rb:233:in `load_ruby_recipe'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.10.3/lib/chef/cookbook_version.rb:203:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.10.3/lib/chef/run_context.rb:417:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.10.3/lib/chef/run_context/cookbook_compiler.rb:228:in `block in compile_recipes'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.10.3/lib/chef/run_context/cookbook_compiler.rb:225:in `each'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.10.3/lib/chef/run_context/cookbook_compiler.rb:225:in `compile_recipes'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.10.3/lib/chef/run_context/cookbook_compiler.rb:109:in `compile'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.10.3/lib/chef/run_context.rb:247:in `load'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.10.3/lib/chef/policy_builder/expand_node_object.rb:103:in `setup_run_context'
/opt/chef/embedded/lib/ruby/3.0.0/forwardable.rb:238:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.10.3/lib/chef/client.rb:495:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.10.3/lib/chef/client.rb:281:in `run'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.10.3/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.10.3/lib/chef/application.rb:281:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.10.3/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.10.3/lib/chef/application.rb:264:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.10.3/lib/chef/application/base.rb:352:in `run_application'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.10.3/lib/chef/application.rb:67:in `run'
/opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-bin-17.10.3/bin/chef-client:25:in `<top (required)>'
/opt/chef/bin/chef-client:160:in `load'
/opt/chef/bin/chef-client:160:in `<main>'
```

**Comment by tpowell-progress** [comment]
This will be resolved in the next release of Chef 17 (>17.10.80)

**Comment by johnmccrae** [comment]
I tested this today and was able to repro the error. Oddly, you get a version of that error no matter what version of the ec2 gem you install. I found an article that discussed that some aws gems DO have built in conflicts. I decided to try something whacky and ``` gem install aws-sdk-ec2 ``` and then run that code snippet from above again. And guess what? I got the same error EXCEPT that I also got this:

```
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * chef_gem[aws-sdk-ec2] action install (up to date)
[2024-07-23T19:52:18+00:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
[2024-07-23T19:52:18+00:00] FATAL: ---------------------------------------------------------------------------------------
[2024-07-23T19:52:18+00:00] FATAL: PLEASE PROVIDE THE CONTENTS OF THE stacktrace.out FILE (above) IF YOU FILE A BUG REPORT
[2024-07-23T19:52:18+00:00] FATAL: ---------------------------------------------------------------------------------------
[2024-07-23T19:52:18+00:00] FATAL: Gem::ConflictError: Unable to activate aws-sdk-ec2-1.466.0, because aws-sdk-core-3.181.0 conflicts with aws-sdk-core (~> 3, >= 3.201.0)
```

Notice that the code KNOWS the gem is installed and does not try to install it but something still caused a version conflict. This requires deeper debugging

**Comment by johnmccrae** [comment]
OK, I did more testing and research and concluded that the issue is not with chef. It's a built-in issue between AWS gems. As of today 12-August, 2024, if I load aws-sdk-core 3.201.4 I can then load aws-sdk-ec2  1.469.0 without conflict. We wrote an article last year about these kinds of issues and how to get past them. [Managing Dependencies](https://discourse.chef.io/t/one-way-to-safely-manage-gem-dependencies-when-upgrading-your-chef-client/22561)

**Comment by johnmccrae** [comment]
Rubygems.org lists the compatible versions - Look up aws-sdk-ec2 and it tells you what version of aws-sdk-core you have to load for compatibility with it on the landing page.

**Comment by drewhammond** [comment]
@johnmccrae are you saying this is not a bug? To be clear, the origin of the conflicting version is baked into `chef-client` binaries:

```
root@localhost:/home/testuser# grep 'aws-sdk-core' /opt/chef/bin/chef-client
  gem "aws-sdk-core", "= 3.130.0"
```

So the gem version baked into chef-client is preventing our use of the latest AWS gems and this limitation is not clearly documented. IMO, that makes it a bug that warrants a patch release (or at the very least a doc fix to list out the maximum versions of AWS gems you can use with this version of chef)

If it were some esoteric gem dependency, I'd concede that we should fix it on our end, but these are the `aws-sdk-*` gems that have been downloaded literally billions of times per rubygems.org.

**Comment by johnmccrae** [comment]
I too show the gem built in, that's weird because we don't have it in the Chef-17 gemfile


But if I install  the EC2 gem  and the Core gem manually with the versions discussed, no conflict.
```shell
azureuser@ubuntu2204:~$ sudo /opt/chef/embedded/bin/gem install gem install aws-sdk-core:3.201.4
ERROR:  Could not find a valid gem 'gem' (>= 0) in any repository
ERROR:  Possible alternatives: 42858gemtest, 42_gem, AABeginnerTestGem, AccountGem, Alonso_gem, AndyFirstGem, Backup_GEM_2, BeverageMaker, BidManagerLoggerGem, BoardGameGem
ERROR:  Could not find a valid gem 'install' (>= 0) in any repository
ERROR:  Possible alternatives: WindowsInstaller, abiquo-installer-tests, adamcooke-key-installer, afinstaller, android-sdk-installer, appextensioninstaller, appinstaller, atlassian_plugin_installer, auto_bundle_install, beaker-module_install_helper
Fetching aws-sdk-core-3.201.4.gem
Fetching aws-sigv4-1.9.1.gem
Fetching aws-eventstream-1.3.0.gem
Successfully installed aws-eventstream-1.3.0
Successfully installed aws-sigv4-1.9.1
Successfully installed aws-sdk-core-3.201.4
Parsing documentation for aws-eventstream-1.3.0
Installing ri documentation for aws-eventstream-1.3.0
Parsing documentation for aws-sigv4-1.9.1
Installing ri documentation for aws-sigv4-1.9.1
Parsing documentation for aws-sdk-core-3.201.4
Installing ri documentation for aws-sdk-core-3.201.4
Done installing documentation for aws-eventstream, aws-sigv4, aws-sdk-core after 2 seconds
3 gems installed
azureuser@ubuntu2204:~$ sudo /opt/chef/embedded/bin/gem install gem install aws-sdk-ec2:1.469.0
ERROR:  Could not find a valid gem 'gem' (>= 0) in any repository
ERROR:  Possible alternatives: 42858gemtest, 42_gem, AABeginnerTestGem, AccountGem, Alonso_gem, AndyFirstGem, Backup_GEM_2, BeverageMaker, BidManagerLoggerGem, BoardGameGem
ERROR:  Could not find a valid gem 'install' (>= 0) in any repository
ERROR:  Possible alternatives: WindowsInstaller, abiquo-installer-tests, adamcooke-key-installer, afinstaller, android-sdk-installer, appextensioninstaller, appinstaller, atlassian_plugin_installer, auto_bundle_install, beaker-module_install_helper
Fetching aws-sdk-ec2-1.469.0.gem
Successfully installed aws-sdk-ec2-1.469.0
Parsing documentation for aws-sdk-ec2-1.469.0
Installing ri documentation for aws-sdk-ec2-1.469.0
Done installing documentation for aws-sdk-ec2 after 14 seconds
1 gem installed
```

Try it again using the chef-gem resource.
```shell
    # In installer.rb

      1: chef_gem "aws-sdk-ec2" do
      2:   compile_time true
      3:   version "1.469.0"
      4: end
```

Still works:
```shell
azureuser@ubuntu2204:~$ sudo chef-apply installer.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * chef_gem[aws-sdk-ec2] action install
    - install version 1.469.0 of package aws-sdk-ec2
  * chef_gem[aws-sdk-ec2] action nothing (skipped due to action :nothing)
```
What am I doing wrong?
