### ISSUE TITLE
rubygems version not working with chef_gem on Chef 18.1.0

### ISSUE THREAD

**Issue by davidjkling** [chef/chef#13608]
## Description
Issue when using `chef_gem` resource installing a custom gem

## Chef Version
Chef Client 18.1.0

## Platform Version
Oracle Linux 7.x

## Replication Case
Using chef client 18 to install gem
Works correctly on Chef 16

## Client Output
Chef 18
```
---- Begin output of /opt/chef/embedded/bin/gem install ibus -q --no-document -v "0.10.0" --clear-sources --source=https://<redacted>/api/gems/rubygems/ ----
STDOUT:
STDERR: ERROR:  While executing gem ... (ArgumentError)
    undefined class/module YAML::
---- End output of /opt/chef/embedded/bin/gem install ibus -q --no-document -v "0.10.0" --clear-sources --source=https://<redacted>/api/gems/rubygems/ ----
```

Chef 16
```
* chef_gem[ibus] action upgrade[2023-02-22T17:49:45+00:00] INFO: Processing chef_gem[ibus] action upgrade (/tmp/kitchen/cache/cookbooks/cwxtiauto_ibus_ops/libraries/host_helper.rb line 15)
[2023-02-22T17:50:08+00:00] INFO: chef_gem[ibus] upgraded(allow_downgrade) ibus to 0.9.3

      - upgrade(allow_downgrade) package ibus from uninstalled to 0.9.3
```
## Stacktrace
```
================================================================================
Error executing action `upgrade` on resource 'chef_gem[ibus]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of /opt/chef/embedded/bin/gem install ibus -q --no-document -v "0.10.0" --clear-sources --source=https://<redacted>/api/gems/rubygems/ ----
STDOUT:
STDERR: ERROR:  While executing gem ... (ArgumentError)
undefined class/module YAML::
---- End output of /opt/chef/embedded/bin/gem install ibus -q --no-document -v "0.10.0" --clear-sources --source=https://<redacted>/api/gems/rubygems/ ----
Ran /opt/chef/embedded/bin/gem install ibus -q --no-document -v "0.10.0" --clear-sources --source=https://<redacted>/api/gems/rubygems/ returned 1

...

[2023-02-22T19:29:47+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
[2023-02-22T19:29:47+00:00] FATAL: ---------------------------------------------------------------------------------------
[2023-02-22T19:29:47+00:00] FATAL: PLEASE PROVIDE THE CONTENTS OF THE stacktrace.out FILE (above) IF YOU FILE A BUG REPORT
[2023-02-22T19:29:47+00:00] FATAL: ---------------------------------------------------------------------------------------
[2023-02-22T19:29:47+00:00] DEBUG: Mixlib::ShellOut::ShellCommandFailed: mysql[install_mysql] (cwxtiauto_ibus_ops::mysql_install line 7) had an error: Mixlib::ShellOut::ShellCommandFailed: chef_gem[ibus] (cwxtiauto_ibus_ops::mysql_install line 15) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/chef/embedded/bin/gem install ibus -q --no-document -v "0.10.0" --clear-sources --source=https://<redacted>/api/gems/rubygems/ ----
STDOUT:
STDERR: ERROR:  While executing gem ... (ArgumentError)
    undefined class/module YAML::
---- End output of /opt/chef/embedded/bin/gem install ibus -q --no-document -v "0.10.0" --clear-sources --source=https://<redacted>/api/gems/rubygems/ ----
Ran /opt/chef/embedded/bin/gem install ibus -q --no-document -v "0.10.0" --clear-sources --source=https://<redacted>/api/gems/rubygems/ returned 1
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/mixlib-shellout-3.2.7/lib/mixlib/shellout.rb:300:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/mixlib-shellout-3.2.7/lib/mixlib/shellout.rb:287:in `error!'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/mixlib-shellout-3.2.7/lib/mixlib/shellout/helper.rb:130:in `shell_out_compacted!'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/mixlib-shellout-3.2.7/lib/mixlib/shellout/helper.rb:54:in `shell_out!'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/provider/package/rubygems.rb:587:in `install_via_gem_command'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/provider/package/rubygems.rb:555:in `install_package'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/provider/package/rubygems.rb:594:in `upgrade_package'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/provider/package.rb:147:in `block (3 levels) in <class:Package>'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/provider/package.rb:269:in `multipackage_api_adapter'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/provider/package.rb:146:in `block (2 levels) in <class:Package>'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/mixin/why_run.rb:51:in `add_action'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/provider.rb:293:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/provider/package.rb:145:in `block in <class:Package>'
(eval):2:in `block in action_upgrade'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/provider.rb:304:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/provider.rb:304:in `compile_and_converge_action'
(eval):2:in `action_upgrade'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/provider.rb:245:in `run_action'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/resource.rb:601:in `block in run_action'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/resource.rb:628:in `with_umask'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/resource.rb:600:in `run_action'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/resource_builder.rb:85:in `block in build'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/resource_builder.rb:84:in `each'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/resource_builder.rb:84:in `build'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/dsl/declare_resource.rb:313:in `build_resource'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/dsl/declare_resource.rb:265:in `declare_resource'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/dsl/resources.rb:36:in `chef_gem'
/tmp/kitchen/cache/cookbooks/cwxtiauto_ibus_ops/libraries/host_helper.rb:15:in `rescue in require_ibus_gem'
/tmp/kitchen/cache/cookbooks/cwxtiauto_ibus_ops/libraries/host_helper.rb:5:in `require_ibus_gem'
/tmp/kitchen/cache/cookbooks/cwxtiauto_ibus_ops/libraries/host_helper.rb:30:in `host'
/tmp/kitchen/cache/cookbooks/cwxtiauto_ibus_ops/resources/mysql.rb:312:in `block in class_from_file'
(eval):2:in `block in action_install'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/provider.rb:304:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/provider.rb:304:in `compile_and_converge_action'
(eval):2:in `action_install'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/provider.rb:245:in `run_action'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/resource.rb:601:in `block in run_action'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/resource.rb:628:in `with_umask'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/resource.rb:600:in `run_action'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/runner.rb:74:in `run_action'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/runner.rb:108:in `each'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/runner.rb:132:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/3.1.0/forwardable.rb:238:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/runner.rb:130:in `converge'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/client.rb:852:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/client.rb:847:in `catch'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/client.rb:847:in `converge'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/client.rb:871:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/client.rb:289:in `run'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/application.rb:281:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/application.rb:264:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/application/base.rb:352:in `run_application'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/application.rb:67:in `run'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-bin-18.1.0/bin/chef-client:25:in `<top (required)>'
/opt/chef/bin/chef-client:184:in `load'
/opt/chef/bin/chef-client:184:in `<main>'

>>>> Caused by Gem::MissingSpecError: Gem::MissingSpecError
/opt/chef/embedded/lib/ruby/3.1.0/rubygems/dependency.rb:311:in `to_specs'
/opt/chef/embedded/lib/ruby/3.1.0/rubygems/dependency.rb:323:in `to_spec'
/opt/chef/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_gem.rb:62:in `gem'
/tmp/kitchen/cache/cookbooks/cwxtiauto_ibus_ops/libraries/host_helper.rb:7:in `require_ibus_gem'
/tmp/kitchen/cache/cookbooks/cwxtiauto_ibus_ops/libraries/host_helper.rb:30:in `host'
/tmp/kitchen/cache/cookbooks/cwxtiauto_ibus_ops/resources/mysql.rb:312:in `block in class_from_file'
(eval):2:in `block in action_install'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/provider.rb:304:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/provider.rb:304:in `compile_and_converge_action'
(eval):2:in `action_install'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/provider.rb:245:in `run_action'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/resource.rb:601:in `block in run_action'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/resource.rb:628:in `with_umask'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/resource.rb:600:in `run_action'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/runner.rb:74:in `run_action'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/runner.rb:108:in `each'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/runner.rb:132:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/3.1.0/forwardable.rb:238:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/runner.rb:130:in `converge'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/client.rb:852:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/client.rb:847:in `catch'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/client.rb:847:in `converge'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/client.rb:871:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/client.rb:289:in `run'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/application.rb:281:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/application.rb:264:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/application/base.rb:352:in `run_application'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.1.0/lib/chef/application.rb:67:in `run'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-bin-18.1.0/bin/chef-client:25:in `<top (required)>'
/opt/chef/bin/chef-client:184:in `load'
/opt/chef/bin/chef-client:184:in `<main>'
[2023-02-22T19:29:47+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: mysql[install_mysql] (cwxtiauto_ibus_ops::mysql_install line 7) had an error: Mixlib::ShellOut::ShellCommandFailed: chef_gem[ibus] (cwxtiauto_ibus_ops::mysql_install line 15) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/chef/embedded/bin/gem install ibus -q --no-document -v "0.10.0" --clear-sources --source=https://<redacted>/api/gems/rubygems/ ----
STDOUT:
STDERR: ERROR:  While executing gem ... (ArgumentError)
    undefined class/module YAML::
---- End output of /opt/chef/embedded/bin/gem install ibus -q --no-document -v "0.10.0" --clear-sources --source=https://<redacted>/api/gems/rubygems/ ----
Ran /opt/chef/embedded/bin/gem install ibus -q --no-document -v "0.10.0" --clear-sources --source=https://<redacted>/api/gems/rubygems/ returned 1
```

## Workaround
Was able to get it to work after running `/opt/chef/embedded/bin/gem update --system '3.3.15' -q --no-document`

Seems that we need a newer version of `rubygems`

rubygems `3.3.7` is installed by default in Chef 18
after running `gem update --system`  to version `3.3.15` it works correctly

Fix is in [3.3.15](https://github.com/rubygems/rubygems/blob/master/CHANGELOG.md#3315--2022-06-01)
I tried `3.3.14` and verified the issue was still there

Not the best workaround though as Chef still thinks its using `3.3.7` (since I assume it's pinned to that version)
```
irb(main):010:0> Gem.loaded_specs['chef'].rubygems_version
=> "3.3.7"
```
But embedded shows the updated version
```
 # /opt/chef/embedded/bin/gem -v
3.3.15
```

## Options?
Not sure we can `update --system` using `chef_gem` resource? Was trying to do that to keep them in sync, but no luck. So right now running the command with an `execute` resource

Also wasn't sure we can update rubygems without needing to take a new version of ruby, which looks like we would need to take `3.2` to get an updated rubygems as well

**Comment by PrajaktaPurohit** [comment]
Thank you for posting the details with the issue. We will be looking into bumping the version of Ruby to 3.2 for chef/chef in the upcoming year. Closing this for now, please reopen if needed.
