### ISSUE TITLE
yum_repository TypeError: no implicit conversion of false into String

### ISSUE THREAD

**Issue by chouetz** [chef/chef#13829]
## Description

When running chef-solo on Amazon Linux 2022 or 2023, I face
```
FATAL: TypeError: yum_repository[datadog] (datadog::repository line 265) had an error: TypeError: no implicit conversion of false into String
```
which comes from https://github.com/chef/chef/blob/main/lib/chef/provider/yum_repository.rb#L48

## Chef Version

18.2.7
## Platform Version

AmazonLinux2023
## Client Output

```
 ================================================================================
    Error executing action `create` on resource 'yum_repository[datadog]'
    ================================================================================

    TypeError
    ---------
    no implicit conversion of false into String

    Cookbook Trace: (most recent call first)
    ----------------------------------------
    /tmp/chef/cookbooks/apt/libraries/helpers.rb:38:in `join'
    /tmp/chef/cookbooks/apt/libraries/helpers.rb:38:in `block in which'
    /tmp/chef/cookbooks/apt/libraries/helpers.rb:37:in `each'
    /tmp/chef/cookbooks/apt/libraries/helpers.rb:37:in `which'

    Resource Declaration:
    ---------------------
    # In /tmp/chef/cookbooks/datadog/recipes/repository.rb

    265:   yum_repository 'datadog' do
    266:     description 'datadog'
    267:     baseurl baseurl
    268:     proxy node['datadog']['yumrepo_proxy']
    269:     proxy_username node['datadog']['yumrepo_proxy_username']
    270:     proxy_password node['datadog']['yumrepo_proxy_password']
    271:     gpgkey yumrepo_gpgkeys
    272:     gpgcheck true
    273:     repo_gpgcheck repo_gpgcheck
    274:     action :create
    275:   end
    276: when 'suse'

    Compiled Resource:
    ------------------
    # Declared in /tmp/chef/cookbooks/datadog/recipes/repository.rb:265:in `from_file'

    yum_repository("datadog") do
      action [:create]
      default_guard_interpreter :default
      declared_type :yum_repository
      cookbook_name "datadog"
      recipe_name "repository"
      baseurl "https://yum.datadoghq.com/stable/7/x86_64/"
      gpgkey ["https://keys.datadoghq.com/DATADOG_RPM_KEY_CURRENT.public", "https://keys.datadoghq.com/DATADOG_RPM_KEY_XXXXXXXX.public", "https://keys.datadoghq.com/DATADOG_RPM_KEY_YYYYYYYY.public"]
      gpgcheck true
      repo_gpgcheck true
      reposdir "/etc/yum.repos.d/"
      repositoryid "datadog"
      mode "0644"
    end

    System Info:
    ------------
    chef_version=18.2.7
    platform=amazon
    platform_version=2022
    ruby=ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
    program_name=/usr/bin/chef-solo
    executable=/opt/chef-workstation/bin/chef-solo


Running handlers:
[2023-07-03T12:49:29+00:00] ERROR: Running exception handlers
Running handlers complete
[2023-07-03T12:49:29+00:00] ERROR: Exception handlers complete
Infra Phase failed. 0 resources updated in 03 seconds
[2023-07-03T12:49:29+00:00] FATAL: Stacktrace dumped to /tmp/chef/chef-stacktrace.out
[2023-07-03T12:49:29+00:00] FATAL: ---------------------------------------------------------------------------------------
[2023-07-03T12:49:29+00:00] FATAL: PLEASE PROVIDE THE CONTENTS OF THE stacktrace.out FILE (above) IF YOU FILE A BUG REPORT
[2023-07-03T12:49:29+00:00] FATAL: ---------------------------------------------------------------------------------------
[2023-07-03T12:49:29+00:00] FATAL: TypeError: yum_repository[datadog] (datadog::repository line 265) had an error: TypeError: no implicit conversion of false into String
```

## Stacktrace

```
Generated at 2023-07-03 12:49:29 +0000
TypeError: yum_repository[datadog] (datadog::repository line 265) had an error: TypeError: no implicit conversion of false into String
/tmp/chef/cookbooks/apt/libraries/helpers.rb:38:in `join'
/tmp/chef/cookbooks/apt/libraries/helpers.rb:38:in `block in which'
/tmp/chef/cookbooks/apt/libraries/helpers.rb:37:in `each'
/tmp/chef/cookbooks/apt/libraries/helpers.rb:37:in `which'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/provider/yum_repository.rb:48:in `block (2 levels) in <class:YumRepository>'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/resource_builder.rb:72:in `instance_exec'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/resource_builder.rb:72:in `build'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/dsl/declare_resource.rb:313:in `build_resource'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/dsl/declare_resource.rb:265:in `declare_resource'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/dsl/resources.rb:36:in `template'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/provider/yum_repository.rb:35:in `block in <class:YumRepository>'
(eval):2:in `block in action_create'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/provider.rb:304:in `instance_eval'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/provider.rb:304:in `compile_and_converge_action'
(eval):2:in `action_create'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/provider.rb:245:in `run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/resource.rb:601:in `block in run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/resource.rb:628:in `with_umask'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/resource.rb:600:in `run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/runner.rb:74:in `run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/runner.rb:108:in `each'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/runner.rb:132:in `block in converge'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/resource_collection/stepable_iterator.rb:54:in `each_with_index'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef-workstation/embedded/lib/ruby/3.1.0/forwardable.rb:238:in `execute_each_resource'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/runner.rb:130:in `converge'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/client.rb:869:in `block in converge'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/client.rb:864:in `catch'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/client.rb:864:in `converge'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/client.rb:888:in `converge_and_save'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/client.rb:298:in `run'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/application.rb:281:in `block in run_chef_client'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/application.rb:264:in `run_chef_client'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/application/base.rb:352:in `run_application'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/application.rb:67:in `run'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.2.7/lib/chef/application/solo.rb:60:in `run'
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-bin-18.2.7/bin/chef-solo:24:in `<top (required)>'
/usr/bin/chef-solo:410:in `load'
/usr/bin/chef-solo:410:in `<main>'
```

**Comment by chouetz** [comment]
PR had been merged, I close the issue (would re-open if re-occurs)
Thanks!
