### ISSUE TITLE
Load error: libmysqlclient.so is not found

### ISSUE THREAD

**Issue by nitins12** [chef/chef#13858]
We use GitHub issues to track bugs and feature requests. If you need help please post to our Mailing List or join the Chef Community Slack.

 * Chef Community Slack at http://community-slack.chef.io/.
 * Chef Mailing List https://discourse.chef.io/

 Support issues opened here will be closed and redirected to Slack or Discourse.

**Comment by nitins12** [comment]
(eval):2:in `block in action_create'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/provider.rb:245:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/provider.rb:245:in `compile_and_converge_action'
(eval):2:in `action_create'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/provider.rb:189:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/resource.rb:586:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/runner.rb:74:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/runner.rb:108:in `each'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/runner.rb:132:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/resource_collection/stepable_iterator.rb:115:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/resource_collection/stepable_iterator.rb:86:in `step'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/2.6.0/forwardable.rb:230:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/runner.rb:130:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/client.rb:712:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/client.rb:707:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/client.rb:707:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/client.rb:731:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/client.rb:288:in `run'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/application.rb:320:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/application.rb:296:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/application.rb:279:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/application/base.rb:330:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/application.rb:68:in `run'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-bin-15.10.12/bin/chef-client:25:in `<top (required)>'
/opt/chef/bin/chef-client:181:in `load'
/opt/chef/bin/chef-client:181:in `<main>'

>>>> Caused by LoadError: cannot load such file -- mysql2
/opt/chef/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/chef/embedded/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/var/chef/cache/cookbooks/jmh-db/recipes/server.rb:2:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/mixin/from_file.rb:34:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/mixin/from_file.rb:34:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/cookbook_version.rb:199:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/run_context.rb:393:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/run_context.rb:349:in `block in include_recipe'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/run_context.rb:348:in `each'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/run_context.rb:348:in `include_recipe'
/var/chef/cache/cookbooks/jmh-db/providers/database.rb:9:in `block in class_from_file'
(eval):2:in `block in action_create'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/provider.rb:245:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/provider.rb:245:in `compile_and_converge_action'
(eval):2:in `action_create'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/provider.rb:189:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/resource.rb:586:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/runner.rb:74:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/runner.rb:108:in `each'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/runner.rb:132:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/resource_collection/stepable_iterator.rb:115:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/resource_collection/stepable_iterator.rb:86:in `step'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/2.6.0/forwardable.rb:230:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/runner.rb:130:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/client.rb:712:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/client.rb:707:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/client.rb:707:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/client.rb:731:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/client.rb:288:in `run'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/application.rb:320:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/application.rb:296:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/application.rb:279:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/application/base.rb:330:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.10.12/lib/chef/application.rb:68:in `run'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-bin-15.10.12/bin/chef-client:25:in `<top (required)>'
/opt/chef/bin/chef-client:181:in `load'
/opt/chef/bin/chef-client:181:in `<main>'

**Comment by nitins12** [comment]
Although this shared library is there in libmysqlclient.so I am getting this error during chef-client run.
