### ISSUE TITLE
Chef shell broken in 18.3.0

### ISSUE THREAD

**Issue by cisco-abrandel** [chef/chef#13940]
## Description

chef-shell fails to launch when using the infra client session switch (-z) after updating to infra client 18.3.0, this did not happen before. 

Suspect PR https://github.com/chef/chef/pull/13766

## Chef Version

18.3.0

## Platform Version

Any platform, issues seen on MacOS, Windows, Linux, of various flavours

## Replication Case

Run chef-shell -z when a node contains a cookbook with attributes

## Client Output

```
loading configuration: /etc/chef/client.rb
true
Session type: client
Loading.......Resolving cookbooks for run list: ["systems", "icinga2", "icinga2_master", "icinga2_web"]
.
================================================================================
Error Syncing Cookbooks:
================================================================================

Unexpected Error:
-----------------
NoMethodError: undefined method `to_set' for ["attributes/default.rb"]:Array

System Info:
------------
chef_version=18.3.0
platform=centos
platform_version=7.8.2003
ruby=ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
program_name=/usr/bin/chef-shell
executable=/opt/chef/bin/chef-shell


```
## Stacktrace

```
epic fail!

/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/cookbook/synchronizer.rb:243:in `block (2 levels) in remove_deleted_files': undefined method `to_set' for ["attributes/default.rb"]:Array (NoMethodError)
	from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/cookbook/synchronizer.rb:241:in `each_key'
	from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/cookbook/synchronizer.rb:241:in `block in remove_deleted_files'
	from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/cookbook/synchronizer.rb:240:in `each_key'
	from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/cookbook/synchronizer.rb:240:in `remove_deleted_files'
	from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/cookbook/synchronizer.rb:268:in `clear_obsoleted_cookbooks'
	from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/cookbook/synchronizer.rb:169:in `sync_cookbooks'
	from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/policy_builder/expand_node_object.rb:205:in `sync_cookbooks'
	from /opt/chef/embedded/lib/ruby/3.1.0/forwardable.rb:238:in `sync_cookbooks'
	from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/client.rb:496:in `sync_cookbooks'
	from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/shell/shell_session.rb:213:in `rebuild_context'
	from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/shell/shell_session.rb:61:in `block in reset!'
	from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/shell/shell_session.rb:105:in `loading'
	from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/shell/shell_session.rb:56:in `reset!'
	from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/shell.rb:155:in `session'
	from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/shell.rb:164:in `init'
	from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/shell.rb:83:in `start'
	from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-bin-18.3.0/bin/chef-shell:31:in `<top (required)>'
	from /usr/bin/chef-shell:180:in `load'
	from /usr/bin/chef-shell:180:in `<main>'
```

**Comment by tpowell-progress** [comment]
@dafyddcrosby do you have any bandwidth to follow-up with this issue that seems to have been introduced by the `.to_set` changes? I did a quick test and it *looks* like `Set` and the `#to_set` patch to `Array` should by default exist on 18's Ruby version.  (And you `require` it just in case, anyway)

**Comment by dafyddcrosby** [comment]
I can sort it out today, will move it back to the earlier Hash implementation from that PR. Not sure why to_set isn't available, but I'll figure out why this wasn't found in the tests. Sorry about the regression @cisco-abrandel (also hi! 👋)

**Comment by tpowell-progress** [comment]
Ok, we'll line this fix up for the next promotion to stable, but it should be available in the current channel relatively soon after merge (there's a current blocker on releases, but that may likely be resolved about the same time as this PR merges)

**Comment by tpowell-progress** [comment]
Thanks for the report @cisco-abrandel! 

If you happen to run across signs why `require "set"` didn't load in this case, please tag it in here to help us chase down the cause of the regression.
