### ISSUE TITLE
"can't modify frozen Chef::Node::ImmutableMash" when reading node attributes

### ISSUE THREAD

**Issue by dafyddcrosby** [chef/chef#13981]
## Description
Copying from chef-infra-dev slack channel from report from fretb

> We use the value of another attribute for the default of nginx_ports, maybe that’s the cause.

I've written a bunch of unit tests trying to repro the issue on my end (tests in a branch at https://github.com/dafyddcrosby/chef/tree/13981_regression), but I think we'll need a smaller repro that can be shared to fish this one out.

## Chef Version
Regression occurs from 18.2.7 to 18.3.0

## Client Output
Issue is on cinc build, but given the problem it's possible this surfaced due to https://github.com/chef/chef/commit/42a076b15384dc4451dfbd0026c6b8d31d0774c1 (or less likely https://github.com/chef/chef/commit/2d3c0d34b135c8a4e42b8f55531df2219edb96dd).  

```
         ================================================================================
         Recipe Compile Error in /var/tmp/kitchen/cache/cookbooks/nginx/recipes/default.rb
         ================================================================================
         
         FrozenError
         -----------
         can't modify frozen Chef::Node::ImmutableMash: {"http"=>{"port"=>nil, "enabled"=>false}, "https"=>{"port"=>443, "enabled"=>true}}
         
         Cookbook Trace: (most recent call first)
         ----------------------------------------
           /var/tmp/kitchen/cache/cookbooks/nginx/recipes/default.rb:12:in `https_active?'
         
         Relevant File Content:
         ----------------------
         /var/tmp/kitchen/cache/cookbooks/nginx/recipes/default.rb:
         
          11:  def https_active?
          12>>   return true if node.read("nginx", "ports", "https", "enabled")
          13:    false
          14:  end
```

```
18.3.0
[7] pry(#<Chef::Recipe>)> node.read("nginx").dup["ports"]
=> {"http"=>{"port"=>8000, "enabled"=>true}, "https"=>{"port"=>443, "enabled"=>false}}
[8] pry(#<Chef::Recipe>)> node.read("nginx")["ports"]
FrozenError: can't modify frozen Chef::Node::ImmutableMash: {"http"=>{"port"=>8000, "enabled"=>true}, "https"=>{"port"=>443, "enabled"=>false}}
from /opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/node/mixin/state_tracking.rb:56:in `__path__='
[9] pry(#<Chef::Recipe>)> node.read("nginx", "ports")
FrozenError: can't modify frozen Chef::Node::ImmutableMash: {"http"=>{"port"=>8000, "enabled"=>true}, "https"=>{"port"=>443, "enabled"=>false}}
from /opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/node/mixin/state_tracking.rb:56:in `__path__='
[10] pry(#<Chef::Recipe>)> node["nginx"]["ports"]
FrozenError: can't modify frozen Chef::Node::ImmutableMash: {"http"=>{"port"=>8000, "enabled"=>true}, "https"=>{"port"=>443, "enabled"=>false}}
from /opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/node/mixin/state_tracking.rb:56:in `__path__='
[11] pry(#<Chef::Recipe>)> node["nginx"].dup["ports"]
=> {"http"=>{"port"=>8000, "enabled"=>true}, "https"=>{"port"=>443, "enabled"=>false}}
18.2.7
[1] pry(#<Chef::Recipe>)> node.read("nginx").dup["ports"]
=> {"http"=>{"port"=>8000, "enabled"=>true}, "https"=>{"port"=>443, "enabled"=>false}}
[2] pry(#<Chef::Recipe>)> node.read("nginx")["ports"]
=> {"http"=>{"port"=>8000, "enabled"=>true}, "https"=>{"port"=>443, "enabled"=>false}}
[3] pry(#<Chef::Recipe>)> node.read("nginx", "ports")
=> {"http"=>{"port"=>8000, "enabled"=>true}, "https"=>{"port"=>443, "enabled"=>false}}
[4] pry(#<Chef::Recipe>)> node["nginx"]["ports"]
=> {"http"=>{"port"=>8000, "enabled"=>true}, "https"=>{"port"=>443, "enabled"=>false}}
[5] pry(#<Chef::Recipe>)> node["nginx"].dup["ports"]
=> {"http"=>{"port"=>8000, "enabled"=>true}, "https"=>{"port"=>443, "enabled"=>false}}
[6] pry(#<Chef::Recipe>)>
```

## Stacktrace
```
Generated at 2023-10-03 07:21:51 +0200
FrozenError: can't modify frozen Chef::Node::ImmutableMash: {"http"=>{"port"=>8000, "enabled"=>true}, "https"=>{"port"=>443, "enabled"=>false}}
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/node/mixin/state_tracking.rb:56:in `__path__='
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/node/mixin/state_tracking.rb:86:in `copy_state_to'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/node/mixin/state_tracking.rb:41:in `[]'
/var/tmp/kitchen/cache/cookbooks/nginx/recipes/default.rb:12:in `https_active?'
/var/tmp/kitchen/cache/cookbooks/nginx/recipes/sock.rb:18:in `from_file'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/mixin/from_file.rb:34:in `instance_eval'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/mixin/from_file.rb:34:in `from_file'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/cookbook_version.rb:233:in `load_ruby_recipe'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/cookbook_version.rb:203:in `load_recipe'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/run_context.rb:429:in `load_recipe'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/run_context.rb:385:in `block in include_recipe'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/run_context.rb:384:in `each'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/run_context.rb:384:in `include_recipe'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/tmp/kitchen/cache/cookbooks/nginx/recipes/default.rb:5:in `from_file'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/mixin/from_file.rb:34:in `instance_eval'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/mixin/from_file.rb:34:in `from_file'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/cookbook_version.rb:233:in `load_ruby_recipe'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/cookbook_version.rb:203:in `load_recipe'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/run_context.rb:429:in `load_recipe'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/run_context/cookbook_compiler.rb:228:in `block in compile_recipes'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/run_context/cookbook_compiler.rb:225:in `each'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/run_context/cookbook_compiler.rb:225:in `compile_recipes'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/run_context/cookbook_compiler.rb:109:in `compile'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/run_context.rb:259:in `load'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/policy_builder/expand_node_object.rb:103:in `setup_run_context'
/opt/cinc/embedded/lib/ruby/3.1.0/forwardable.rb:238:in `setup_run_context'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/client.rb:508:in `setup_run_context'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/client.rb:294:in `run'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/application.rb:281:in `block in run_chef_client'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/application.rb:264:in `run_chef_client'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/application/base.rb:354:in `run_application'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/application.rb:67:in `run'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-bin-18.3.0/bin/cinc-client:25:in `<top (required)>'
/opt/cinc/bin/cinc-client:180:in `load'
/opt/cinc/bin/cinc-client:180:in `<main>'
```

**Comment by fretb** [comment]
Ok, so this is interesting, I found out this happens due to the attribute being used as a property in a resource:

`property :ports, Hash, default: node["nginx"]["ports"]`

When changing this to `property :ports, Hash, default: node["nginx"]["ports"].dup`, the error is not triggered anymore.
