### ISSUE TITLE
Net::HTTPServerException: 405 "Not Allowed" while saving node at the end of a chef-client run / node bootstrap

### ISSUE THREAD

**Issue by wzin** [chef/chef#14122]
## Description

I do run multiple nodes in the environment. There are 2 nodes that converge succesfully but they will never successfully submit their attribs/ohai back to api.chef.io because a `Net::HTTPServerException: 405 "Not Allowed"` is thrown at the end of each run.

## Chef Version

Chef Infra Client: 18.3.0

## Platform Version

Ubuntu 22.04 - up to date.

## Replication Case

run chef-client or knife bootstrap - happens on 2 random nodes in my stack.

## Client Output

The following happens both when I bootstrap the node or just run chef-client manually (or via systemd).

```
     Resolving cookbooks for run list: []
     opening connection to api.chef.io:443...
     opened
     starting SSL for api.chef.io:443...
     SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256
     Synchronizing cookbooks:
     Installing cookbook gem dependencies:
     Compiling cookbooks...
     Loading Chef InSpec profile files:
     Loading Chef InSpec input files:
     Loading Chef InSpec waiver files:
     [2023-12-05T11:25:02+00:00] WARN: Node foobar.com has an empty run list.
     opening connection to api.chef.io:443...
     opened
     starting SSL for api.chef.io:443...
     SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256
     Converging 0 resources
     opening connection to api.chef.io:443...
     opened
     starting SSL for api.chef.io:443...
     SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256
     
     Running handlers:
     [2023-12-05T11:25:03+00:00] ERROR: Running exception handlers
     Running handlers complete
     [2023-12-05T11:25:03+00:00] ERROR: Exception handlers complete
     Infra Phase failed. 0 resources updated in 34 seconds
     [2023-12-05T11:25:03+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
     [2023-12-05T11:25:03+00:00] FATAL: ---------------------------------------------------------------------------------------
     [2023-12-05T11:25:03+00:00] FATAL: PLEASE PROVIDE THE CONTENTS OF THE stacktrace.out FILE (above) IF YOU FILE A BUG REPORT
     [2023-12-05T11:25:03+00:00] FATAL: ---------------------------------------------------------------------------------------
     [2023-12-05T11:25:03+00:00] FATAL: Net::HTTPServerException: 405 "Not Allowed"
```

## Stacktrace

Specifically the `save_updated_node` does fail:

```ruby
Generated at 2023-12-05 11:25:03 +0000
Net::HTTPServerException: 405 "Not Allowed"
/opt/chef/embedded/lib/ruby/3.1.0/net/http/response.rb:124:in `error!'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/http.rb:158:in `request'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/http.rb:129:in `put'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/node.rb:647:in `save'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/client.rb:585:in `save_updated_node'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/client.rb:889:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/client.rb:298:in `run'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/application.rb:281:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/application.rb:264:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/application/base.rb:354:in `run_application'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.3.0/lib/chef/application.rb:67:in `run'
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-bin-18.3.0/bin/chef-client:25:in `<top (required)>'
/usr/bin/chef-client:180:in `load'
/usr/bin/chef-client:180:in `<main>'```

What I've tried:
- completely wiped out the node and its client from api.chef.io
- removed /opt/chef
- removed /etc/chef
- cleared the runlist so it's empty and node just runs with nothing to execute
- tried bootstraping running chef manually - no difference - always the same error.

The only thing that makes the run go just fine is

```bash
chef-client --minimal-ohai
```

then the node run looks like that:

```bash
root@foobar.com:/home/foobar# chef-client --minimal-ohai
Chef Infra Client, version 18.3.0
Patents: https://www.chef.io/patents
Infra Phase starting
opening connection to api.chef.io:443...
opened
starting SSL for api.chef.io:443...
SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256
opening connection to api.chef.io:443...
opened
starting SSL for api.chef.io:443...
SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256
opening connection to api.chef.io:443...
opened
starting SSL for api.chef.io:443...
SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256
Resolving cookbooks for run list: []
opening connection to api.chef.io:443...
opened
starting SSL for api.chef.io:443...
SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256
Synchronizing cookbooks:
Installing cookbook gem dependencies:
Compiling cookbooks...
Loading Chef InSpec profile files:
Loading Chef InSpec input files:
Loading Chef InSpec waiver files:
[2023-12-05T11:33:48+00:00] WARN: Node foobar.com has an empty run list.
opening connection to api.chef.io:443...
opened
starting SSL for api.chef.io:443...
SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256
Converging 0 resources
opening connection to api.chef.io:443...
opened
starting SSL for api.chef.io:443...
SSL established, protocol: TLSv1.2, cipher: ECDHE-RSA-AES128-GCM-SHA256

Running handlers:
Running handlers complete
Infra Phase complete, 0/0 resources updated in 01 seconds
```

**Comment by wzin** [comment]
After more research it came out that it's the api.chef.io specifically that refuses to handle large PUT methods during `node.save`.

How to reproduce:

1. have a node that `ohai`'s output size is 3MB like mine
2. reproduce by:
- run chef-shell 
```
chef-shell -c /etc/chef/client.rb
```
```
node.save
```
for servers with large OHAI payload you'll get 405 error.

I think this might be actual problem or configuration param on api.chef.io, not chef-client itself.

**Comment by wzin** [comment]
closing as this is api.chef.io limit
