### ISSUE TITLE
Chef client under FIPS mode now broken in RHEL 9.4/Rocky Linux 9.4

### ISSUE THREAD

**Issue by breisig** [chef/chef#14376]
## Description
We have Rocky Linux/RHEL 9.3 servers running in FIPS mode using Chef Client 18.4.12. Everything is fine. Rocky Linux/RHEL 9.4 has been released and upgraded to the Latest 9.4 version. Now when doing a chef-client, the following output appears

```
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-config-18.4.12/lib/chef-config/config.rb:1292:in `fips_mode=': This version of OpenSSL does not support FIPS mode (OpenSSL::OpenSSLError)
        from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-config-18.4.12/lib/chef-config/config.rb:1292:in `enable_fips_mode'
        from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-config-18.4.12/lib/chef-config/config.rb:737:in `init_openssl'
        from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/application.rb:104:in `configure_chef'
        from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/application.rb:55:in `reconfigure'
        from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/application/client.rb:76:in `reconfigure'
        from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/application.rb:64:in `run'
        from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-bin-18.4.12/bin/chef-client:25:in `<top (required)>'
        from /usr/bin/chef-client:183:in `load'
        from /usr/bin/chef-client:183:in `<main>'
```
It seems all of a sudden the chef-client won't work anymore. Servers are in fact running in FIPS mode and working so something is up with chef-client. The only workaround is running 'chef-client --no-fips' but that's such a pain. I even tried with a *fresh* install of 9.4 and the same error exists.

## Chef Version
Chef Client 18.4.12

## Platform Version
Rocky Linux 9.4/RHEL 9.4

## Client Output
```
/opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-config-18.4.12/lib/chef-config/config.rb:1292:in `fips_mode=': This version of OpenSSL does not support FIPS mode (OpenSSL::OpenSSLError)
        from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-config-18.4.12/lib/chef-config/config.rb:1292:in `enable_fips_mode'
        from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-config-18.4.12/lib/chef-config/config.rb:737:in `init_openssl'
        from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/application.rb:104:in `configure_chef'
        from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/application.rb:55:in `reconfigure'
        from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/application/client.rb:76:in `reconfigure'
        from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-18.4.12/lib/chef/application.rb:64:in `run'
        from /opt/chef/embedded/lib/ruby/gems/3.1.0/gems/chef-bin-18.4.12/bin/chef-client:25:in `<top (required)>'
        from /usr/bin/chef-client:183:in `load'
        from /usr/bin/chef-client:183:in `<main>'
```

**Comment by tpowell-progress** [comment]
@breisig can you confirm the URL and/or package that was used to install Chef 18.4.12. I'm looking at the builder image for EL9 and the Ruby installed on it has FIPS mode compiled.

Also, are you able to confirm the following on the system running chef-client errors out?
```sh
/opt/chef/embedded/bin/ruby -e "require 'openssl'; puts OpenSSL::OPENSSL_VERSION_NUMBER.to_s(16); puts OpenSSL::OPENSSL_LIBRARY_VERSION; OpenSSL.fips_mode = 1; puts 'FIPS mode successfully activated for Ruby' + RUBY_VERSION"
```
