### ISSUE TITLE
cookbook upload fails if there is a brace in the cookbook path

### ISSUE THREAD

**Issue by pmacdougall** [chef/chef#1625]
I couldn't find this as a known issue anywhere, but if there is a brace (`{` or `}`) anywhere in the cookbook path, I cannot upload cookbooks.

Here's an example of a successful upload, changing the directory name, and the failure.

```
$ pwd
/Users/pmacdougall/test/nobracetest
$ knife cookbook upload xml -o . --force 
Uploading xml            [1.2.2]
Uploaded 1 cookbook.
$ cd ..
$ mv nobracetest brace\{test\}
$ cd brace\{test\}/
$ knife cookbook upload xml -o . --force  -VV
DEBUG: Signing the request as pmacdougall
DEBUG: Initiating GET to https://api.opscode.com/organizations/pmacdougall-sandbox/cookbooks?num_versions=all
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.0;
DEBUG: X-OPS-USERID: pmacdougall
DEBUG: X-OPS-TIMESTAMP: 2014-07-09T18:37:24Z
DEBUG: X-OPS-CONTENT-HASH: 2jmj7l5rSw0yVb/vlWAYkK/YBwk=
DEBUG: X-OPS-AUTHORIZATION-1: kqtzA/nGOdJzRewLznG30JiXHZMiQYgmcb6ZzJBIM+FU+5zjEzzVtPUOw1Ma
DEBUG: X-OPS-AUTHORIZATION-2: kR+GCUPpUPotIlEbMdDv+X8BRK8W1Q+T3FpmKqbSBH/HXl7EO3cgLU6G1i98
DEBUG: X-OPS-AUTHORIZATION-3: U+snIXYu9a1iyvXWwa27gh5nUY+1fSXQk9wBFYArvncjR7c0rIZ3T370CBXI
DEBUG: X-OPS-AUTHORIZATION-4: 8QaU8OAaNRGqvTQzP7XBHliPktyF0djcvTLWDfb8Tyaf9wXDh+MXlHTx1eGS
DEBUG: X-OPS-AUTHORIZATION-5: +o3YZsKrB+XrEr/gtpG/RifFU6j1MPJuDoB1NoUy20yONc+iAHQ0F47UqPfN
DEBUG: X-OPS-AUTHORIZATION-6: A3yQ2slM6rlrh7HACvl2JN1bG8bTB9fUrHekZKdkUA==
DEBUG: HOST: api.opscode.com:443
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 200 OK
DEBUG: server: ngx_openresty
DEBUG: date: Wed, 09 Jul 2014 18:37:22 GMT
DEBUG: content-type: application/json
DEBUG: transfer-encoding: chunked
DEBUG: connection: close
DEBUG: x-ops-api-info: flavor=hec;version=11.0.0;oc_erchef=0.25.16
DEBUG: content-encoding: gzip
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: decompressing gzip response
DEBUG: No chefignore file found at /Users/pmacdougall/test/brace{test}/chefignore no files will be ignored
ERROR: Could not find cookbook xml in your cookbook path, skipping it
DEBUG: Cannot find a cookbook named xml; did you forget to add metadata to a cookbook? (http://wiki.opscode.com/display/chef/Metadata) (Chef::Exceptions::CookbookNotFoundInRepo)
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.0/lib/chef/cookbook_loader.rb:106:in `[]'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.0/lib/chef/knife/cookbook_upload.rb:163:in `block in cookbooks_to_upload'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.0/lib/chef/knife/cookbook_upload.rb:160:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.0/lib/chef/knife/cookbook_upload.rb:160:in `cookbooks_to_upload'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.0/lib/chef/knife/cookbook_upload.rb:119:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.0/lib/chef/knife.rb:485:in `run_with_pretty_exceptions'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.0/lib/chef/knife.rb:174:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.0/lib/chef/application/knife.rb:133:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.8.0/bin/knife:25:in `<top (required)>'
/usr/bin/knife:23:in `load'
/usr/bin/knife:23:in `<main>'
ERROR: Failed to upload 1 cookbook.
```

**Comment by tas50** [comment]
It looks as though some of our path sanitation for Windows cleared this problem up.  I created a similar directory setup with chef 12.12 and I was unable to reproduce the failure.

MBP:~/dev/chef-cookbooks/{test} knife cookbook upload tomcat -o .
Uploading tomcat         [2.3.1]
Uploaded 1 cookbook.
