### ISSUE TITLE
Policyfile mode cannot fetch templates correctly

### ISSUE THREAD

**Issue by danielsdeleo** [chef/chef#1675]
On line 160 of policyfile.rb (https://github.com/opscode/chef/blob/dd742991862f6b1c9b8d193549f6b87c5c92cfa6/lib/chef/policy_builder/policyfile.rb#L160) it should refer to `http_api` instead of `api_service`. Currently it fails with a NameError and a stack trace like this:

```
NameError: template[/etc/default/jenkins] (jenkins::_master_package line 38) had an error: NameError: undefined local variable or method `api_service' for #<Chef::PolicyBuilder::Policyfile:0x00000002dbfa40>
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/policy_builder/policyfile.rb:160:in `block in setup_run_context'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/cookbook/file_vendor.rb:35:in `call'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/cookbook/file_vendor.rb:35:in `create_from_manifest'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/cookbook_version.rb:661:in `file_vendor'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/cookbook_version.rb:323:in `preferred_filename_on_disk_location'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/provider/template_finder.rb:40:in `find'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/provider/template/content.rb:32:in `template_location'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/provider/template.rb:49:in `block in define_resource_requirements'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/mixin/why_run.rb:315:in `assert'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/provider/template.rb:47:in `define_resource_requirements'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/provider.rb:109:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/resource.rb:637:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/runner.rb:81:in `block in converge'
```

**Comment by lamont-granquist** [comment]
hoping this got fixed at some point.
