### ISSUE TITLE
Link resource does not support lazy attribute eval on target_file

### ISSUE THREAD

**Issue by Jamstah** [chef/chef#1767]
When it gets down to scan access control, it complains about not having a string.

```
[2014-08-06T16:32:55+01:00] DEBUG: TypeError: link[Build script] (butterfly::buildengine line 39) had an error: TypeError: can't convert Chef::DelayedEvaluator into String
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/scan_access_control.rb:49:in `exist?'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/scan_access_control.rb:49:in `set_all!'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/provider/link.rb:68:in `load_current_resource'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/provider.rb:103:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/resource.rb:637:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/runner.rb:49:in `run_action'
```

**Comment by smurawski** [comment]
@thommay is going to pick up the PR that fixes this.
