### ISSUE TITLE
Uploading a cookbook with a 3.5mb file fails

### ISSUE THREAD

**Issue by duncanphillips** [chef/chef#2043]
I'm using berkshelf to upload cookbooks to my chef server. When I do the upload, one cookbook in particular fails, namely php from chefsupermarket. Digging into the debug logs, it fails on a 3.5mb file which it tries to post to the chef server. I haven't managed to get to the root of the issue, but so far I've made modifications to the various configuration files on the chef server (nginx, erchef, bookshelf) to ensure that maximum file size allows more than 10mb, and restarted everything. So far, this hasn't solved the issue, and the only solution so far is to remove the offending file from the php cookbook. I can't think of what else might be causing this. I don't see anything in the logs files, including the 413 response in the nginx logs which is strange.

``` text
D, [2014-09-11T16:58:45.926780 #28453] DEBUG -- : ==> handling Chef response
D, [2014-09-11T16:58:45.926961 #28453] DEBUG -- : request env: #<struct Faraday::Env method=:put, body="<html>\r\n<head><title>413 Request Entity Too Large</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>413 Request Entity Too Large</h1></center>\r\n<hr><center>
nginx/1.4.7</center>\r\n</body>\r\n</html>\r\n", url=#<URI::HTTPS:0x007fd516068b08 URL:https://chef.some-chef-server.com/bookshelf/organization-00000000000000000000000000000000/checksum-69d7b635c1ff57117b125ad3219dd2cf?AWSAccessKeyId=5ce8ee90396215421d26a9a6af286dff6a
f335f5&Expires=1410448388&Signature=aPQrxIeCFjcYejLFyUdy2d9mgQo%3D>, request=#<Faraday::RequestOptions (empty)>, request_headers={"Accept"=>"application/json", "Content-Type"=>"application/x-binary", "X-Chef-Version"=>"11.4.0", "User-Agent"=>"Faraday v0.9.0", "content-md5
"=>"ade2NcH/VxF7ElrTIZ3Szw==", "X-OPS-SIGN"=>"algorithm=sha1;version=1.0;", "X-OPS-USERID"=>"admin", "X-OPS-TIMESTAMP"=>"2014-09-11T14:58:11Z", "X-OPS-CONTENT-HASH"=>"ouTICFTXRVjqzYeOFzSuGh2gEzw=", "X-OPS-AUTHORIZATION-1"=>"wiUzZjHjCwiGxFEICls4xuEMHJj6K9/FwLsJzHMKlZWEBJKc
T0YdxkXtysf0", "X-OPS-AUTHORIZATION-2"=>"qbVGs7R/ux9QZfAlL5OxpL9rSIztcG46Z4lGd/otC3mD0gp/u5n8rlYuuM0M", "X-OPS-AUTHORIZATION-3"=>"t1zIXAZE5FYoBrvoFB0Wjpc7wd/tKsRfYBq/cTUzBzX9NmawHfx6Ar8Yv1qB", "X-OPS-AUTHORIZATION-4"=>"s+ZF3OPiHVntcrFGUN5B30SfgXiCzIEshukpoBzA4eKI9Rl2RZUOv
lonmmx6", "X-OPS-AUTHORIZATION-5"=>"6g+148vpM73+2UrtCiy4VESByEuOK0/OHAfXkzQVlod18doAK/kc0AE9KEPK", "X-OPS-AUTHORIZATION-6"=>"hPZ/lUWVGQ9O9sC+kMCy4Y0YhafEQzVLtWRLXtyCqg==", "HOST"=>"chef.some-chef-server:443", "Content-Length"=>"3658571"}, ssl=#<Faraday::SSLOptions
 (empty)>, parallel_manager=nil, params=nil, response=nil, response_headers={"server"=>"nginx/1.4.7", "date"=>"Thu, 11 Sep 2014 14:58:21 GMT", "content-type"=>"text/html", "content-length"=>"198", "connection"=>"close"}, status=413>
D, [2014-09-11T16:58:45.929803 #28453] DEBUG -- : ** error encounted in Chef response
E, [2014-09-11T16:58:45.934406 #28453] ERROR -- : Ridley::Errors::HTTPRequestEntityTooLarge: <html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.4.7</center>
</body>
</html>

E, [2014-09-11T16:58:45.934504 #28453] ERROR -- : /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ridley-4.0.0/lib/ridley/middleware/chef_response.rb:24:in `on_complete'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/faraday-0.9.0/lib/faraday/response.rb:9:in `block in call'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/faraday-0.9.0/lib/faraday/connection.rb:177:in `put'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/ridley-4.0.0/lib/ridley/sandbox_uploader.rb:91:in `upload'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0.pre3/lib/celluloid/calls.rb:26:in `public_send'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0.pre3/lib/celluloid/calls.rb:26:in `dispatch'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0.pre3/lib/celluloid/calls.rb:63:in `dispatch'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0.pre3/lib/celluloid/cell.rb:60:in `block in invoke'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0.pre3/lib/celluloid/cell.rb:71:in `block in task'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0.pre3/lib/celluloid/actor.rb:357:in `block in task'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0.pre3/lib/celluloid/tasks.rb:57:in `block in initialize'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/celluloid-0.16.0.pre3/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
(celluloid):0:in `remote procedure call'
```

**Comment by dhiraj26683** [comment]
duncanphillips, can you know how this issue got resolved?.

**Comment by xakraz** [comment]
@duncanphillips any tips on the issue ?

**Comment by kareiva** [comment]
You may consider setting:

    nginx['client_max_body_size'] = "4m"

in your `chef-server.rb` file and then running a `chef-server-ctl reconfigure` to apply the changes.
