### ISSUE TITLE
remote_file's source attribute does not support DelayedEvaluators

### ISSUE THREAD

**Issue by knoxvilledba** [chef/chef#2047]
I am opening this issue, as CHEF-5162 does not seem to be fixed in the latest chef-client, although it was in the changelog for 11.14.2. This is a chef-shell output of the same test case from the original ticket (https://tickets.opscode.com/browse/CHEF-5162)

This is the chef-shell.
 Chef Version: 11.16.0
 http://www.opscode.com/chef
 http://docs.opscode.com/

```
run `help' for help, `exit' or ^D to quit.

Ohai2u vagrant@localhost!
chef > recipe_mode
chef:recipe > remote_file "/tmp/g2" do
chef:recipe > source lazy {"http://www.google.com"}
chef:recipe ?> end
Chef::Exceptions::InvalidRemoteFileURI: #<Chef::DelayedEvaluator:0x00000003a2d188@(irb#1):2> is not a valid `source` parameter for remote_file. `source` must be an absolute URI or an array of URIs.
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/resource/remote_file.rb:138:in `block in validate_source'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/resource/remote_file.rb:136:in `each'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/resource/remote_file.rb:136:in `validate_source'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/resource/remote_file.rb:128:in `after_created'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/dsl/recipe.rb:139:in `build_resource'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/dsl/recipe.rb:85:in `declare_resource'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.0/lib/chef/dsl/recipe.rb:41:in `method_missing'
	from (irb#1):1
```

**Comment by albertsj1** [comment]
This is still not working on 12.0.3.
```
                      ================================================================================

                      Chef::Exceptions::InvalidRemoteFileURI
                      --------------------------------------
                      #<Chef::DelayedEvaluator:0x00000004f6be78@/var/chef/cache/cookbooks/quickbuild-mspot/recipes/_common.rb:44> is not a valid `source` parameter for remote_file. `source` must be an absolute URI or an array of URIs.
```

**Comment by stevendanna** [comment]
@albertsj1 Can you run that in debug mode and provide more of the stacktrace?

**Comment by stevendanna** [comment]
@albertsj1 Never mind, looks like the same issue identified above, for some reason I thought the fix for this had been merged.

**Comment by thommay** [comment]
This should be resolved now.
