### ISSUE TITLE
service resource is incapable of managing the SSH service on Mac OS X

### ISSUE THREAD

**Issue by jgoldschrafe** [chef/chef#2200]
The Mac OS X provider for `service` does this super-smart thing where it globs across the system's LaunchDaemon directories for files that contain the service name. If more than one is found, it blows up with the following error:

    Several plist files match service name. Please use full service name.

The problem is that I'm *using the full service name*, which is just `ssh` (see: `/System/Library/LaunchDaemons/ssh.plist`), and there's no way to get it to stop matching whatever it feels like in these directories. Maybe a two-step process would be a better approach, where it looks for an exact match before globbing all the things?

**Comment by rveznaver** [comment]
Hi, I am also running into the bug. As previously noted, the launchd provider plist scan is incorrect. It should go through *all* plists (in the specified directories), extract the label for each, and compare with the service name. The Label "contains a unique string that identifies your daemon to launchd." ([docs](https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html)). Therefore, the plist file names should be completely ignored (as their names are only a convention, not a strict rule), and it should (probably) fail on duplicate labels. FYI, the _full service name_ for shh in launchd is: 'com.openssh.sshd'

**Comment by lamont-granquist** [comment]
@jtimberman ?

**Comment by jtimberman** [comment]
I'll look into this next week.

**Comment by jtimberman** [comment]
Adding some context:

```
$ sudo chef-apply -e 'service("ssh") { action [:enable, :start] }'
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * service[ssh] action enable
    * Several plist files match service name. Please use full service name.
    ================================================================================
    Error executing action `enable` on resource 'service[ssh]'
    ================================================================================

    Chef::Exceptions::Service
    -------------------------
    Several plist files match service name. Please use full service name.

    Resource Declaration:
    ---------------------
    # In /tmp/recipe-temporary-file20150218-299-15otrh7

      1: service("ssh") { action [:enable, :start] }

    Compiled Resource:
    ------------------
    # Declared in /tmp/recipe-temporary-file20150218-299-15otrh7:1:in `run_chef_recipe'

    service("ssh") do
      action [:enable, :start]
      supports {:restart=>false, :reload=>false, :status=>false}
      retries 0
      retry_delay 2
      guard_interpreter :default
      service_name "ssh"
      pattern "ssh"
      cookbook_name "(chef-apply cookbook)"
      recipe_name "(chef-apply recipe)"
    end

[2015-02-18T10:46:02-07:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-02-18T10:46:02-07:00] FATAL: Chef::Exceptions::Service: service[ssh] ((chef-apply cookbook)::(chef-apply recipe) line 1) had an error: Chef::Exceptions::Service: Several plist files match service name. Please use full service name.
```

The stacktrace:

```
$ sudo cat /var/chef/cache/chef-stacktrace.out
Generated at 2015-02-18 10:46:02 -0700
Chef::Exceptions::Service: service[ssh] ((chef-apply cookbook)::(chef-apply recipe) line 1) had an error: Chef::Exceptions::Service: Several plist files match service name. Please use full service name.
/opt/chefdk/embedded/apps/chef/lib/chef/mixin/why_run.rb:241:in `run'
/opt/chefdk/embedded/apps/chef/lib/chef/mixin/why_run.rb:322:in `block in run'
/opt/chefdk/embedded/apps/chef/lib/chef/mixin/why_run.rb:321:in `each'
/opt/chefdk/embedded/apps/chef/lib/chef/mixin/why_run.rb:321:in `run'
/opt/chefdk/embedded/apps/chef/lib/chef/provider.rb:134:in `process_resource_requirements'
/opt/chefdk/embedded/apps/chef/lib/chef/provider.rb:111:in `run_action'
/opt/chefdk/embedded/apps/chef/lib/chef/resource.rb:648:in `run_action'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection.rb:98:in `block in execute_each_resource'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection.rb:96:in `execute_each_resource'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chefdk/embedded/apps/chef/lib/chef/application/apply.rb:144:in `run_chef_recipe'
/opt/chefdk/embedded/apps/chef/lib/chef/application/apply.rb:153:in `run_application'
/opt/chefdk/embedded/apps/chef/lib/chef/application/apply.rb:166:in `run'
/opt/chefdk/embedded/apps/chef/bin/chef-apply:25:in `<top (required)>'
/usr/bin/chef-apply:38:in `load'
/usr/bin/chef-apply:38:in `<main>'
```

**Comment by jtimberman** [comment]
Dropping off helpful links

**Comment by jtimberman** [comment]
- https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html
- https://github.com/chef/chef/blob/master/lib/chef/provider/service/macosx.rb

**Comment by mikedodge04** [comment]
I have a simple change that might address this. 
https://github.com/chef/chef/pull/3051

**Comment by juliandunn** [comment]
Is this still an issue now that #3051 was merged?

**Comment by jtimberman** [comment]
Paging @jgoldschrafe -

**Comment by lamont-granquist** [comment]
assuming #3051 fixed this
