### ISSUE TITLE
knife ssh doesn't handle Net::SSH::Disconnect well

### ISSUE THREAD

**Issue by glasschef** [chef/chef#2299]
When using `knife ssh` along with some search terms that return multiple servers, if one of those servers times out for any reason then no output will come back.

```
DEBUG: queueing packet nr 7 type 90 len 44
DEBUG: queueing packet nr 7 type 90 len 44
DEBUG: read 204 bytes
DEBUG: received packet nr 7 type 80 len 44
INFO: global request received: keepalive@openssh.com true
DEBUG: queueing packet nr 8 type 82 len 28
DEBUG: read 0 bytes
/home/admin/ruby/lib/ruby/gems/2.1.0/gems/net-ssh-2.7.0/lib/net/ssh/transport/packet_stream.rb:87:in `next_packet': connection closed by remote host (Net::SSH::Disconnect)
        from /home/admin/ruby/lib/ruby/gems/2.1.0/gems/net-ssh-2.7.0/lib/net/ssh/transport/session.rb:172:in `block in poll_message'
        from /home/admin/ruby/lib/ruby/gems/2.1.0/gems/net-ssh-2.7.0/lib/net/ssh/transport/session.rb:167:in `loop'
        from /home/admin/ruby/lib/ruby/gems/2.1.0/gems/net-ssh-2.7.0/lib/net/ssh/transport/session.rb:167:in `poll_message'
        from /home/admin/ruby/lib/ruby/gems/2.1.0/gems/net-ssh-2.7.0/lib/net/ssh/connection/session.rb:460:in `dispatch_incoming_packets'
        from /home/admin/ruby/lib/ruby/gems/2.1.0/gems/net-ssh-2.7.0/lib/net/ssh/connection/session.rb:221:in `preprocess'
        from /home/admin/ruby/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.0/lib/net/ssh/multi/server.rb:204:in `preprocess'
        from /home/admin/ruby/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.0/lib/net/ssh/multi/session.rb:449:in `block in preprocess'
        from /home/admin/ruby/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.0/lib/net/ssh/multi/server_list.rb:47:in `block in each'
        from /home/admin/ruby/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.0/lib/net/ssh/multi/server_list.rb:45:in `each'
        from /home/admin/ruby/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.0/lib/net/ssh/multi/server_list.rb:45:in `each'
        from /home/admin/ruby/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.0/lib/net/ssh/multi/session.rb:449:in `preprocess'
        from /home/admin/ruby/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.0/lib/net/ssh/multi/session.rb:430:in `process'
        from /home/admin/ruby/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.0/lib/net/ssh/multi/session.rb:417:in `block in loop'
        from /home/admin/ruby/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.0/lib/net/ssh/multi/session.rb:417:in `loop'
        from /home/admin/ruby/lib/ruby/gems/2.1.0/gems/net-ssh-multi-1.2.0/lib/net/ssh/multi/session.rb:417:in `loop'
        from /home/admin/ruby/lib/ruby/gems/2.1.0/gems/chef-11.16.4/lib/chef/knife/ssh.rb:277:in `ssh_command'
        from /home/admin/ruby/lib/ruby/gems/2.1.0/gems/chef-11.16.4/lib/chef/knife/ssh.rb:521:in `run'
        from /home/admin/ruby/lib/ruby/gems/2.1.0/gems/chef-11.16.4/lib/chef/knife.rb:493:in `run_with_pretty_exceptions'
        from /home/admin/ruby/lib/ruby/gems/2.1.0/gems/chef-11.16.4/lib/chef/knife.rb:174:in `run'
        from /home/admin/ruby/lib/ruby/gems/2.1.0/gems/chef-11.16.4/lib/chef/application/knife.rb:139:in `run'
        from /home/admin/ruby/lib/ruby/gems/2.1.0/gems/chef-11.16.4/bin/knife:25:in `<top (required)>'
        from /home/admin/ruby/bin/knife:23:in `load'
        from /home/admin/ruby/bin/knife:23:in `<main>'
```

**Comment by lamont-granquist** [comment]
Can we replicate this and see if `--exit-on-error` did anything to help here or not?
