### ISSUE TITLE
Kill process failed from pushy-client in windows

### ISSUE THREAD

**Issue by HappyRainy** [chef/chef#2504]
Hi there,

By using pushy-client in windows, I experienced an exception while pushy-client trying to kill a chef-client process. 

```
[2014-11-28T03:25:29+00:00] INFO: [WIN-TFE589IHTHQ] Received commit f1d47fed4b2427e612e2d9065e57fc96
[2014-11-28T03:25:30+00:00] INFO: [WIN-TFE589IHTHQ] Received run f1d47fed4b2427e612e2d9065e57fc96
[2014-11-28T03:25:30+00:00] INFO: [WIN-TFE589IHTHQ] Job f1d47fed4b2427e612e2d9065e57fc96: started command 'chef-client' with PID '648'
[2014-11-28T03:25:49+00:00] INFO: [WIN-TFE589IHTHQ] Received abort
[2014-11-28T03:25:49+00:00] INFO: [WIN-TFE589IHTHQ] Killing process 648
[2014-11-28T03:25:49+00:00] ERROR: [WIN-TFE589IHTHQ] Exception in Process.kill(1, 648): Invalid Memory object
C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/win32-process-0.7.3/lib/win32/process.rb:859:in `=='
C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/win32-process-0.7.3/lib/win32/process.rb:859:in `block in kill'
C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/win32-process-0.7.3/lib/win32/process.rb:793:in `each'
C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/win32-process-0.7.3/lib/win32/process.rb:793:in `kill'
C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/job_runner.rb:217:in `kill_process'
C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/job_runner.rb:55:in `stop'
C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/job_runner.rb:131:in `block in abort'
<internal:prelude>:10:in `synchronize'
C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/job_runner.rb:129:in `abort'
C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client.rb:141:in `abort'
C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/protocol_handler.rb:294:in `handle_message'
C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/protocol_handler.rb:224:in `block (2 levels) in start_receive_thread'
C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/protocol_handler.rb:222:in `each'
C:/opscode/pushy/embedded/lib/ruby/gems/1.9.1/gems/opscode-pushy-client-1.1.3/lib/pushy_client/protocol_handler.rb:222:in `block in start_receive_thread'
C:/opscode/pushy/embedded/lib/ruby/1.9.1/win32ole.rb:13:in `call'
C:/opscode/pushy/embedded/lib/ruby/1.9.1/win32ole.rb:13:in `block in initialize'
```

This exception causes no more chef-client can run any more due to the previous chef-client process still existing.

Very appreciate your work and looking forward to hearing from you soon.

Thank
Jing Li

**Comment by smalltown** [comment]
I also encounter the same issue, 
When there are more than about 15 nodes need to be pushed...
Then the crashed rate increases ...

**Comment by jdmundrawala** [comment]
Looks like we there is a fairly isolated repro here:
https://www.ruby-forum.com/topic/4413016

**Comment by manderson26** [comment]
Sorry I missed this. Moving this to opscode-pushy-client to track there.

**Comment by HappyRainy** [comment]
Thanks for you help.
