### ISSUE TITLE
UTF-8 names cause problems with the user provider on OS X

### ISSUE THREAD

**Issue by joerg** [chef/chef#2519]
Simply setting the user shell in OSX 10.10 returns an error:

```
joerg@MacBook-Pro % chef-apply --no-color -l debug -e "user 'joerg' do;shell '/usr/local/bin/zsh';end"
[2014-12-02T09:41:58+01:00] DEBUG: Building node object for Jorgs-MacBook-Pro.local
[2014-12-02T09:41:58+01:00] DEBUG: Extracting run list from JSON attributes provided on command line
[2014-12-02T09:41:58+01:00] DEBUG: Applying attributes from json file
[2014-12-02T09:41:58+01:00] DEBUG: Platform is mac_os_x version 10.10.1
[2014-12-02T09:41:58+01:00] INFO: Run List is []
[2014-12-02T09:41:58+01:00] INFO: Run List expands to []
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * user[joerg] action create[2014-12-02T09:41:58+01:00] INFO: Processing user[joerg] action create ((chef-apply cookbook)::(chef-apply recipe) line 1)
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>HeimdalSRPKey</key>
        <array>
                <data>
## REMOVED
                </data>
        </array>
        <key>KerberosKeys</key>
        <array>
                <data>
## REMOVED
                </data>
        </array>
        <key>ShadowHashData</key>
        <array>
                <data>
## REMOVED
                </data>
        </array>
        <key>_writers_UserCertificate</key>
        <array>
                <string>joerg</string>
        </array>
        <key>_writers_hint</key>
        <array>
                <string>joerg</string>
        </array>
        <key>_writers_jpegphoto</key>
        <array>
                <string>joerg</string>
        </array>
        <key>_writers_passwd</key>
        <array>
                <string>joerg</string>
        </array>
        <key>_writers_picture</key>
        <array>
                <string>joerg</string>
        </array>
        <key>_writers_realname</key>
        <array>
                <string></string>
        </array>
        <key>accountPolicyData</key>
        <array>
                <data>
## REMOVED
                </data>
        </array>
        <key>authentication_authority</key>
        <array>
## REMOVED
        </array>
        <key>generateduid</key>
        <array>
                <string>89913C77-B9EB-4467-B248-E6EDDABD8141</string>
        </array>
        <key>gid</key>
        <array>
                <string>20</string>
        </array>
        <key>home</key>
        <array>
                <string>/Users/joerg</string>
        </array>
        <key>jpegphoto</key>
        <array>
                <data>
## REMOVED
                </data>                                                                                                                                                   [47/1809]
        </array>
        <key>name</key>
        <array>
                <string>joerg</string>
        </array>
        <key>passwd</key>
        <array>
                <string>********</string>
        </array>
        <key>picture</key>
        <array>
                <string>/Library/User Pictures/Nature/Zen.tif</string>
        </array>
        <key>realname</key>
        <array>
                <string>Jörg Herzinger</string>
        </array>
        <key>shell</key>
        <array>
                <string>/usr/local/bin/zsh</string>
        </array>
        <key>uid</key>
        <array>
                <string>501</string>
        </array>
</dict>
</plist>


    ================================================================================
    Error executing action `create` on resource 'user[joerg]'
    ================================================================================

    Encoding::CompatibilityError
    ----------------------------
    incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)

    Resource Declaration:
    ---------------------
    # In /tmp/recipe-temporary-file20141202-50099-iipu5u

      1: user 'joerg' do;shell '/usr/local/bin/zsh';end

    Compiled Resource:
    ------------------
    # Declared in /tmp/recipe-temporary-file20141202-50099-iipu5u:1:in `run_chef_recipe'                                                                                   [1/1809]

    user("joerg") do
      action :create
      supports {:manage_home=>false, :non_unique=>false}
      retries 0
      retry_delay 2
      guard_interpreter :default
      username "joerg"
      shell "/usr/local/bin/zsh"
      iterations 27855
      cookbook_name "(chef-apply cookbook)"
      recipe_name "(chef-apply recipe)"
    end

[2014-12-02T09:41:58+01:00] INFO: Running queued delayed notifications before re-raising exception
[2014-12-02T09:41:58+01:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2014-12-02T09:41:58+01:00] DEBUG: Encoding::CompatibilityError: user[joerg] ((chef-apply cookbook)::(chef-apply recipe) line 1) had an error: Encoding::CompatibilityError: incomp
atible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/plist-3.1.0/lib/plist/parser.rb:91:in `scan'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/plist-3.1.0/lib/plist/parser.rb:91:in `parse'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/plist-3.1.0/lib/plist/parser.rb:29:in `parse_xml'
/opt/chefdk/embedded/apps/chef/lib/chef/provider/user/dscl.rb:565:in `read_user_info'
/opt/chefdk/embedded/apps/chef/lib/chef/provider/user/dscl.rb:113:in `load_current_resource'
/opt/chefdk/embedded/apps/chef/lib/chef/provider.rb:104:in `run_action'
/opt/chefdk/embedded/apps/chef/lib/chef/resource.rb:648:in `run_action'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection.rb:98:in `block in execute_each_resource'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection.rb:96:in `execute_each_resource'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chefdk/embedded/apps/chef/lib/chef/application/apply.rb:144:in `run_chef_recipe'
/opt/chefdk/embedded/apps/chef/lib/chef/application/apply.rb:153:in `run_application'
/opt/chefdk/embedded/apps/chef/lib/chef/application/apply.rb:166:in `run'
/opt/chefdk/embedded/apps/chef/bin/chef-apply:25:in `<top (required)>'
/usr/bin/chef-apply:33:in `load'
/usr/bin/chef-apply:33:in `<main>'
[2014-12-02T09:41:58+01:00] FATAL: Encoding::CompatibilityError: user[joerg] ((chef-apply cookbook)::(chef-apply recipe) line 1) had an error: Encoding::CompatibilityError: incomp
atible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)
```

The removed parts are simple ASCII strings, so there should be nothing special.
Setting the shell manually works like a charm:
joerg@MacBook-Pro % sudo dscl . create /Users/joerg UserShell /usr/local/bin/zsh
Password:
joerg@MacBook-Pro % echo $?
0

**Comment by smurawski** [comment]
@joerg 

It looks like the successful command uses "sudo"
Fails - joerg@MacBook-Pro % chef-apply --no-color -l debug -e "user 'joerg' do;shell '/usr/local/bin/zsh';end" 
Succeeds - sudo dscl . create /Users/joerg UserShell /usr/local/bin/zsh

Does chef-apply fail if you sudo it as well?

**Comment by joerg** [comment]
Sorry, that was a copy/paste error. Yes, I executed the command with sudo and yes, the error is stil there. I did that one just a few minutes ago...

```
joerg@Jorgs-MacBook-Pro ~ % sudo chef-apply --no-color -l debug -e "user 'joerg' do;shell '/usr/local/bin/zsh';end"
Password:
[2015-03-10T09:30:01+01:00] DEBUG: Building node object for Jorgs-MacBook-Pro.local
[2015-03-10T09:30:01+01:00] DEBUG: Extracting run list from JSON attributes provided on command line
[2015-03-10T09:30:01+01:00] DEBUG: Applying attributes from json file
[2015-03-10T09:30:01+01:00] DEBUG: Platform is mac_os_x version 10.10.2
[2015-03-10T09:30:01+01:00] INFO: Run List is []
[2015-03-10T09:30:01+01:00] INFO: Run List expands to []
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * user[joerg] action create[2015-03-10T09:30:01+01:00] INFO: Processing user[joerg] action create ((chef-apply cookbook)::(chef-apply recipe) line 1)
[2015-03-10T09:30:01+01:00] DEBUG: providers for generic user resource enabled on node include: []
[2015-03-10T09:30:01+01:00] DEBUG: providers that refused resource user[joerg] were: []
[2015-03-10T09:30:01+01:00] DEBUG: providers that support resource user[joerg] include: []
[2015-03-10T09:30:01+01:00] DEBUG: no providers supported the resource, falling back to enabled handlers
[2015-03-10T09:30:01+01:00] DEBUG: providers that survived replacement include: []
[2015-03-10T09:30:01+01:00] DEBUG: dynamic provider resolver FAILED to resolve a provider
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>HeimdalSRPKey</key>
  <array>
    <data>
    ## ASCII String
    </data>
  </array>
  <key>KerberosKeys</key>
  <array>
    <data>
    ## ASCII String
    </data>
  </array>
  <key>ShadowHashData</key>
  <array>
    <data>
    ## ASCII String
    </data>
  </array>
  <key>_writers_UserCertificate</key>
  <array>
    <string>joerg</string>
  </array>
  <key>_writers_hint</key>
  <array>
    <string>joerg</string>
  </array>
  <key>_writers_jpegphoto</key>
  <array>
    <string>joerg</string>
  </array>
  <key>_writers_passwd</key>
  <array>
    <string>joerg</string>
  </array>
  <key>_writers_picture</key>
  <array>
    <string>joerg</string>
  </array>
  <key>_writers_realname</key>
  <array>
    <string></string>
  </array>
  <key>accountPolicyData</key>
  <array>
    <data>
    ## ASCII String
    </data>
  </array>
  <key>authentication_authority</key>
  <array>
    <string>;ShadowHash;HASHLIST:&lt;SALTED-SHA512-PBKDF2&gt;</string>
    <string>;Kerberosv5;;joerg@ ## String omitted ##</string>
  </array>
  <key>generateduid</key>
  <array>
    <string>## ASCII String</string>
  </array>
  <key>gid</key>
  <array>
    <string>20</string>
  </array>
  <key>home</key>
  <array>
    <string>/Users/joerg</string>
  </array>
  <key>jpegphoto</key>
  <array>
    <data>
    ## Long long long ASCII String
    </data>
  </array>
  <key>name</key>
  <array>
    <string>joerg</string>
  </array>
  <key>passwd</key>
  <array>
    <string>********</string>
  </array>
  <key>picture</key>
  <array>
    <string>/Library/User Pictures/Animals/Parrot.tif</string>
  </array>
  <key>realname</key>
  <array>
    <string>Jörg Herzinger</string>
  </array>
  <key>shell</key>
  <array>
    <string>/usr/local/bin/zsh</string>
  </array>
  <key>uid</key>
  <array>
    <string>501</string>
  </array>
</dict>
</plist>

    
    ================================================================================
    Error executing action `create` on resource 'user[joerg]'
    ================================================================================
    
    Encoding::CompatibilityError
    ----------------------------
    incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)
    
    Resource Declaration:
    ---------------------
    # In /tmp/recipe-temporary-file20150310-19482-67ipoc
    
      1: user 'joerg' do;shell '/usr/local/bin/zsh';end
    
    Compiled Resource:
    ------------------
    # Declared in /tmp/recipe-temporary-file20150310-19482-67ipoc:1:in `run_chef_recipe'
    
    user("joerg") do
      action :create
      supports {:manage_home=>false, :non_unique=>false}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      username "joerg"
      shell "/usr/local/bin/zsh"
      iterations 27855
      declared_type :user
      cookbook_name "(chef-apply cookbook)"
      recipe_name "(chef-apply recipe)"
    end
    
[2015-03-10T09:30:01+01:00] INFO: Running queued delayed notifications before re-raising exception
[2015-03-10T09:30:01+01:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-03-10T09:30:01+01:00] DEBUG: Encoding::CompatibilityError: user[joerg] ((chef-apply cookbook)::(chef-apply recipe) line 1) had an error: Encoding::CompatibilityError: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/plist-3.1.0/lib/plist/parser.rb:91:in `scan'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/plist-3.1.0/lib/plist/parser.rb:91:in `parse'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/plist-3.1.0/lib/plist/parser.rb:29:in `parse_xml'
/opt/chefdk/embedded/apps/chef/lib/chef/provider/user/dscl.rb:565:in `read_user_info'
/opt/chefdk/embedded/apps/chef/lib/chef/provider/user/dscl.rb:113:in `load_current_resource'
/opt/chefdk/embedded/apps/chef/lib/chef/provider.rb:128:in `run_action'
/opt/chefdk/embedded/apps/chef/lib/chef/resource.rb:582:in `run_action'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chefdk/embedded/apps/chef/lib/chef/application/apply.rb:150:in `run_chef_recipe'
/opt/chefdk/embedded/apps/chef/lib/chef/application/apply.rb:159:in `run_application'
/opt/chefdk/embedded/apps/chef/lib/chef/application/apply.rb:172:in `run'
/opt/chefdk/embedded/apps/chef/bin/chef-apply:25:in `<top (required)>'
/usr/bin/chef-apply:40:in `load'
/usr/bin/chef-apply:40:in `<main>'
[2015-03-10T09:30:01+01:00] FATAL: Encoding::CompatibilityError: user[joerg] ((chef-apply cookbook)::(chef-apply recipe) line 1) had an error: Encoding::CompatibilityError: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)
joerg@Jorgs-MacBook-Pro-9 ~ % echo $?
1                 
joerg@Jorgs-MacBook-Pro ~ % chef-client --version
Chef: 12.0.3
joerg@Jorgs-MacBook-Pro-9 ~ % sudo dscl . create /Users/joerg UserShell /usr/local/bin/zsh
Password:
joerg@Jorgs-MacBook-Pro-9 ~ % echo $?
0
```

**Comment by thommay** [comment]
This looks like an encoding issue with your name, actually. (But still a bug)

**Comment by natewalck** [comment]
I've seen this problem pop up recently on a few of our client machines. This is breaking their chef runs completely and after digging a bit, I noticed a few things

On the system where this occurs, 'locale' returns:

```
sh-3.2# locale
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

And in irb, if I do a test to see what the encoding it:

```
# /opt/chef/embedded/bin/irb
irb(main):005:0> "test".encoding
=> #<Encoding:US-ASCII>
```

Whereas on a working machine, it shows:

```
# locale                                                                                    ✓  10015  10:52:32
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en
```

```
irb(main):007:0> "test".encoding
=> #<Encoding:UTF-8>
```

Happy to provide more details as I have an easily accessible machine in this broken state.

**Comment by natewalck** [comment]
Also, could this bug fix be bumped up in priority a little bit? Is it reasonable to expect chef to be immune to localization issues on the machine?

**Comment by natewalck** [comment]
Also, the actual error I am seeing: 

```
Encoding::CompatibilityError
----------------------------
incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/cpe_utils/libraries/profile_provider.rb:232:in `read_plist'
/var/chef/cache/cookbooks/cpe_utils/libraries/profile_provider.rb:218:in `query_installed_profiles'
/var/chef/cache/cookbooks/cpe_utils/libraries/profile_provider.rb:212:in `get_installed_profiles'
/var/chef/cache/cookbooks/cpe_utils/libraries/profile_provider.rb:39:in `load_current_resource'

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/cpe_security/recipes/disable_sparkleupdate.rb

 46: osx_profile 'com.facebook.cpe.disablesparkle' do
 47:   action :remove
 48: end
 49:
```

**Comment by lamont-granquist** [comment]
this is blowing up in the plist parser gem:

```
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/plist-3.1.0/lib/plist/parser.rb:91:in `scan'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/plist-3.1.0/lib/plist/parser.rb:91:in `parse'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/plist-3.1.0/lib/plist/parser.rb:29:in `parse_xml'
```

there's no bug to fix here in chef-client, and i suspect the plist gem devs are going to tell you to fix your localization issues on the box.

you can manually set the ENV variables somewhere early (even chef's /etc/chef/config.rb) and force them to some appropriate UTF-8 locale, but you need to consider that once you do that all your software in e.g. the `service` provider will launch with that locale.  for our perspective we cannot make those kinds of decisions across the board for every site, so we cannot fix this.  if throwing `ENV['LC_ALL']="en_US.UTF-8"` (or whatever) in config.rb works for you, then that is the correct solution, we can't engineer anything better than that.
