### ISSUE TITLE
`knife client create` fails when attempting to upload a public_key

### ISSUE THREAD

**Issue by stevendanna** [chef/chef#2541]
The Chef Server API allows a user to upload a client with a public_key from a pre-made keypair.  `knife client create` however, makes this difficult.

Regardless of the public_key value in the passed json, a new private_key is returned and the old private_key does not work:

```
> cat clients/upload_test_3.json
{
  "name": "upload_test_3",
  "public_key": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnRWBJ3edLpFdjasMYlY1\nFAMX9kABCjTJfscIozqpShOPuxaNjEgcVbmhg4nsZialoBbOa9O2eDgNm4urEmNS\nWHWz8842/UFJCb2LqingSrDrASKFQ2M7xP7tDL5uqeox0MEM8UUWiTQLVZe6/C7y\nqSYRxm31UeGQMgCZQuUccIU5hf6Ssh9dWlhCNKFGtDM8jxAHZWWBgdFdxAXUukSB\ngPUbMvpBjMbhjCZ4M0PqrktVBCV5Ii4xYaJkx43MmL4v677C4xwd+W6s4pZzr/eN\nZ3Tbt7q2IA3bUmS9fU851nq7wrKBk/Qtr/Z3ef57hz6lG29VEt5JA9gdwgXdUxRn\npwIDAQAB\n-----END PUBLIC KEY-----",
  "json_class": "Chef::ApiClient"
}
> EDITOR="cat clients/upload_test_3.json >" knife client create upload_test_3
Created client[upload_test_3]
-----BEGIN RSA PRIVATE KEY-----
REDACTED
-----END RSA PRIVATE KEY-----
> knife node list -k mykey.pem -u upload_test_3
ERROR: Failed to authenticate to https://api.chef.io/organizations/steve-ocs as upload_test_3 with key /Users/sdanna/src/oc/steve-ocs/mykey.pem
Response:  Invalid signature for user or client 'upload_test_3'
```

Attempting again with `private_key: false` in the json also yields an error:

```
> knife client delete -y upload_test_3
Deleted client[upload_test_3]
> cat clients/upload_test_3.json
{
  "name": "upload_test_3",
  "public_key": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnRWBJ3edLpFdjasMYlY1\nFAMX9kABCjTJfscIozqpShOPuxaNjEgcVbmhg4nsZialoBbOa9O2eDgNm4urEmNS\nWHWz8842/UFJCb2LqingSrDrASKFQ2M7xP7tDL5uqeox0MEM8UUWiTQLVZe6/C7y\nqSYRxm31UeGQMgCZQuUccIU5hf6Ssh9dWlhCNKFGtDM8jxAHZWWBgdFdxAXUukSB\ngPUbMvpBjMbhjCZ4M0PqrktVBCV5Ii4xYaJkx43MmL4v677C4xwd+W6s4pZzr/eN\nZ3Tbt7q2IA3bUmS9fU851nq7wrKBk/Qtr/Z3ef57hz6lG29VEt5JA9gdwgXdUxRn\npwIDAQAB\n-----END PUBLIC KEY-----",
  "json_class": "Chef::ApiClient",
  "private_key" : false
}
> EDITOR="cat clients/upload_test_3.json >" knife client create upload_test_3
ERROR: Chef::Exceptions::ValidationFailed: Option private_key must be a kind of String!  You passed false.
```

Using the ChefFS `upload` command on the original json, yields the expected results:

```
> knife upload clients/upload_test_3.json
Created clients/upload_test_3.json
> knife node list -k mykey.pem -u upload_test_3 >/dev/null
> echo $?
0
```

**Comment by lamont-granquist** [comment]
Feels like this is part of a entire level up of old commands to new ChefFS commands that needs to occur.

**Comment by thommay** [comment]
Fixing this is part of #3368

**Comment by stuartnelson3** [comment]
What's the status on this? We are attempting to migrate from chef11 -> chef12, and the following methods fail:

- restoring a backup created with `knife-backup` doesn't respect `admin: true` in the json (but does create the user)
- `knife client edit` from the above method fails with `ERROR: Chef::Exceptions::ValidationFailed: Option private_key must be a kind of String!  You passed false.` regardless of if I pass `private_key` as a string or not at all
- `knife upload` results in 
```
/usr/lib/ruby/vendor_ruby/chef/chef_fs/file_system/base_fs_object.rb:121:in `create_child': Chef::ChefFS::FileSystem::OperationNotAllowedError (Chef::ChefFS::FileSystem::OperationNotAllowedError)
	from /usr/lib/ruby/vendor_ruby/chef/chef_fs/file_system.rb:414:in `get_or_create_parent'
	from /usr/lib/ruby/vendor_ruby/chef/chef_fs/file_system.rb:410:in `get_or_create_parent'
	from /usr/lib/ruby/vendor_ruby/chef/chef_fs/file_system.rb:410:in `get_or_create_parent'
	from /usr/lib/ruby/vendor_ruby/chef/chef_fs/file_system.rb:410:in `get_or_create_parent'
	from /usr/lib/ruby/vendor_ruby/chef/chef_fs/file_system.rb:410:in `get_or_create_parent'
	from /usr/lib/ruby/vendor_ruby/chef/chef_fs/file_system.rb:144:in `block in copy_to'
	from /usr/lib/ruby/vendor_ruby/chef/chef_fs/parallelizer.rb:95:in `call'
	from /usr/lib/ruby/vendor_ruby/chef/chef_fs/parallelizer.rb:95:in `process_input'
	from /usr/lib/ruby/vendor_ruby/chef/chef_fs/parallelizer.rb:70:in `each'
	from /usr/lib/ruby/vendor_ruby/chef/chef_fs/file_system.rb:422:in `to_a'
	from /usr/lib/ruby/vendor_ruby/chef/chef_fs/file_system.rb:422:in `parallel_do'
	from /usr/lib/ruby/vendor_ruby/chef/chef_fs/file_system.rb:142:in `copy_to'
	from /usr/lib/ruby/vendor_ruby/chef/knife/upload.rb:60:in `block in run'
	from /usr/lib/ruby/vendor_ruby/chef/knife/upload.rb:59:in `each'
	from /usr/lib/ruby/vendor_ruby/chef/knife/upload.rb:59:in `run'
	from /usr/lib/ruby/vendor_ruby/chef/knife.rb:492:in `run_with_pretty_exceptions'
	from /usr/lib/ruby/vendor_ruby/chef/knife.rb:174:in `run'
	from /usr/lib/ruby/vendor_ruby/chef/application/knife.rb:135:in `run'
	from /usr/bin/knife:24:in `<main>'
```

Can you advise on a timeframe, or if you need more information because I'm in a unique situation?

**Comment by stuartnelson3** [comment]
note:

`EDITOR="cat clients/example_client.json >" knife client create example_client` creates a client, but also doesn't respect the `admin: true` field within the json, and editing that fails as well.

**Comment by lamont-granquist** [comment]
Another issue that we should probably just fix and not block on the knife epic that we're unlikely to ever complete.
