### ISSUE TITLE
ignore_failure not ignoring failure

### ISSUE THREAD

**Issue by Thermatix** [chef/chef#2598]
I have an execute resource that will fail on the first ever run, so I did :

ignore_failure true

But it's failing with a Mixlib::ShellOut::ShellCommandFailed
and I can see that it's in the compiled resource as it says:

==> default: ignore_failure true

in the output.

So why is the chef run being terminated when it should just ignore the error and carry on?

Here's the whole error

```
==> default: [2014-12-09T13:00:20+00:00] ERROR: execute[stop service] (gg-web-internal-cryptoboard::install line 58) had an error:
 Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> default: ---- Begin output of stop gg-web-internal-cryptoboard ----
==> default: STDOUT:
==> default: STDERR: stop: Unknown job: gg-web-internal-cryptoboard
==> default: ---- End output of stop gg-web-internal-cryptoboard ----
==> default: Ran stop gg-web-internal-cryptoboard returned 1; ignore_failure is set, continuing
==> default:
==> default: ================================================================================
==> default: Error executing action `run` on resource 'execute[stop service]'
==> default: ================================================================================
==> default:
==> default: Mixlib::ShellOut::ShellCommandFailed
==> default: ------------------------------------
==> default: Expected process to exit with [0], but received '1'
==> default: ---- Begin output of stop gg-web-internal-cryptoboard ----
==> default: STDOUT:
==> default: STDERR: stop: Unknown job: gg-web-internal-cryptoboard
==> default: ---- End output of stop gg-web-internal-cryptoboard ----
==> default: Ran stop gg-web-internal-cryptoboard returned 1
==> default:
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /tmp/vagrant-chef-3/chef-solo-1/cookbooks/gg-web-internal-cryptoboard/recipes/install.rb
==> default:
==> default:  58: execute 'stop service' do
==> default:  59:   ignore_failure true
==> default:  60:   user app_user
==> default:  61:   timeout 100
==> default:  62:   command "stop #{app_name}"
==> default:  63:   action :run
==> default:  64: end
==> default:  65:
==> default:
==> default: Compiled Resource:
==> default: ------------------
==> default: # Declared in /tmp/vagrant-chef-3/chef-solo-1/cookbooks/gg-web-internal-cryptoboard/recipes/install.rb:58:in `from_fi
le'
==> default:
==> default: execute("stop service") do
==> default:   action [:run]
==> default:   ignore_failure true
==> default:   retries 0
==> default:   retry_delay 2
==> default:   default_guard_interpreter :execute
==> default:   command "stop gg-web-internal-cryptoboard"
==> default:   backup 5
==> default:   returns 0
==> default:   timeout 100
==> default:   user "gg-web-internal-cryptoboard_user"
==> default:   cookbook_name :"gg-web-internal-cryptoboard"
==> default:   recipe_name "install"
==> default: end
==> default: [2014-12-09T13:00:20+00:00] INFO: Chef Run complete in 1.522302995 seconds
==> default: [2014-12-09T13:00:20+00:00] INFO: Skipping removal of unused files from the cache
==> default: [2014-12-09T13:00:20+00:00] INFO: Running report handlers
==> default: [2014-12-09T13:00:20+00:00] INFO: Report handlers complete
```

I'm aware that you don't have service's on linux, Just named it that for convenience

**Comment by jsirex** [comment]
Looks like notify doesn't work with ignore_failure. I'm not sure is it feature or bug:
```ruby
remote_file 'oracle-java8-jdk-deb' do
  path pkg_path
  source node['e3s']['java']['url']
  checksum node['e3s']['java']['checksum']
  mode '0644'

  notifies :install, 'package[oracle-java8-jdk]', :immediately
end

package 'oracle-java8-jdk' do
  source pkg_path
  ignore_failure true # We need to install dependencies

  if pkg_path.end_with?('.deb')
    provider Chef::Provider::Package::Dpkg
  elsif pkg_path.end_with?('.rpm')
    provider Chef::Provider::Package::Rpm
  end

  notifies :run, 'execute[fix-dependencies-for-oracle-java8-jdk]', :immediately
end

execute 'fix-dependencies-for-oracle-java8-jdk' do
  command 'apt-get -yf install'
  action :nothing
end
```

Result:
```
Errors were encountered while processing:
            oracle-java8-jdk
           ---- End output of dpkg -i /tmp/kitchen/cache/oracle-java8-jdk_8u111_amd64.deb ----
           Ran dpkg -i /tmp/kitchen/cache/oracle-java8-jdk_8u111_amd64.deb returned 1
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/e3s-java/recipes/install.rb
           
            15: package 'oracle-java8-jdk' do
            16:   source pkg_path
            17:   ignore_failure true # We need to install dependencies
            18: 
            19:   if pkg_path.end_with?('.deb')
            20:     provider Chef::Provider::Package::Dpkg
            21:   elsif pkg_path.end_with?('.rpm')
            22:     provider Chef::Provider::Package::Rpm
            23:   end
            24: 
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/e3s-java/recipes/install.rb:15:in `from_file'
           
           apt_package("oracle-java8-jdk") do
             package_name "oracle-java8-jdk"
             provider Chef::Provider::Package::Dpkg
             action [:install]
             ignore_failure true
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :package
             cookbook_name "e3s-java"
             recipe_name "install"
             source "/tmp/kitchen/cache/oracle-java8-jdk_8u111_amd64.deb"
           end
           
           Platform:
           ---------
           x86_64-linux
           
         * execute[fix-dependencies-for-oracle-java8-jdk] action nothing (skipped due to action :nothing)
```

**Comment by kwilczynski** [comment]
@jsirex this indeed looks like a potential issue. But I would recommend opening a separate issue and providing details e.g. Chef client version, etc.

**Comment by shortdudey123** [comment]
Agree, new issue is needed since this specific issue is over 2 yrs old
