### ISSUE TITLE
Directory provider fails with EEXIST

### ISSUE THREAD

**Issue by cbaenziger** [chef/chef#2680]
I have a system which has a failed disk -- its mount point on Ubuntu is raising EIO but Chef is bailing with EEXIST.

When I have a directory provider to create a directory it should not fail with EEXIST that is rather against my intention of using Chef. However, if a directory raises EIO, then Chef fails with EEXIST:

```
$ sudo chef-shell
[sudo] password for ubuntu:
loading configuration: none (standalone session)
Session type: standalone
Loading........done.

This is the chef-shell.
 Chef Version: 11.12.8
 http://www.opscode.com/chef
 http://docs.opscode.com/

run `help' for help, `exit' or ^D to quit.

Ohai2u ubuntu@machine.example.com!
chef > recipe_mode
chef:recipe > directory "/disk/6" do
chef:recipe >   action :create
chef:recipe ?> end
 => <directory[/disk/6] @name: "/disk/6" @noop: nil @before: nil @params: {} @provider: Chef::Provider::Directory @allowed_actions: [:nothing, :create, :delete] @action: [:create] @updated: false @updated_by_last_action: false @supports: {} @ignore_failure: false @retries: 0 @retry_delay: 2 @source_line: "(irb#1):1:in `irb_binding'" @guard_interpreter: :default @elapsed_time: 0 @resource_name: :directory @path: "/disk/6" @recursive: false @cookbook_name: nil @recipe_name: nil>
chef:recipe > chef_run
 => nil
chef:recipe > run_chef
[2014-12-18T09:49:13-05:00] INFO: Processing directory[/disk/6] action create ((irb#1) line 1)

================================================================================
Error executing action `create` on resource 'directory[/disk/6]'
================================================================================

Errno::EEXIST
-------------
File exists - /disk/6

Resource Declaration:
---------------------


Compiled Resource:
------------------
# Declared in (irb#1):1:in `irb_binding'

directory("/disk/6") do
  provider Chef::Provider::Directory
  action [:create]
  retries 0
  retry_delay 2
  guard_interpreter :default
  path "/disk/6"
end
[2014-12-18T09:49:13-05:00] INFO: Running queued delayed notifications before re-raising exception
Errno::EEXIST: directory[/disk/6] ((irb#1) line 1) had an error: Errno::EEXIST: File exists - /disk/6
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/provider/directory.rb:103:in `mkdir'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/provider/directory.rb:103:in `block in action_create'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/mixin/why_run.rb:52:in `call'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/mixin/why_run.rb:52:in `add_action'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/provider.rb:155:in `converge_by'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/provider/directory.rb:99:in `action_create'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/provider.rb:120:in `run_action'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/resource.rb:637:in `run_action'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/runner.rb:49:in `run_action'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/runner.rb:81:in `block (2 levels) in converge'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/runner.rb:81:in `each'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/runner.rb:81:in `block in converge'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/resource_collection.rb:98:in `block in execute_each_resource'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/resource_collection.rb:96:in `execute_each_resource'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/runner.rb:80:in `converge'
        from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.8/lib/chef/shell/ext.rb:236:in `run_chef'
        from (irb#1):5
chef:recipe >
```

This stopped my automatic Chef runs and means I need to guard all mountpoint related directory creation steps with lstat to successfully catch this and recover (in my case adjust my RAID to rebuild):

```
$ /opt/chef/embedded/bin/irb 
irb(main):001:0> File.lstat("/disk/6")
Errno::EIO: Input/output error - /disk/6
        from (irb):1:in `lstat'
        from (irb):1
        from /opt/chef/embedded/bin/irb:12:in `<main>'
```

Can Chef be friendlier and accept that yes, a directory entry exists and that's all that I wanted it to do for me?

For reference here are the standard Unix tools' behaviors:

```
$ sudo mkdir /disk/6
mkdir: cannot create directory `/disk/6': File exists
$ ls /disk/6
ls: cannot access /disk/6: Input/output error
```

**Comment by smurawski** [comment]
The error behavior is the desired behavior, but the error message could possibly be cleaned up - though that'll be a non-trivial dive into the bowels of Ruby to figure out where we need to catch this error.
