### ISSUE TITLE
remote_directory does not obey removal of file specificity

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#2837]
```
Recipe: sk_role_base::usr_local_bin
  * remote_directory[/usr/local/bin] action create

    ================================================================================
    Error executing action `create` on resource 'remote_directory[/usr/local/bin]'
    ================================================================================

    Chef::Exceptions::FileNotFound
    ------------------------------
    cookbook sk_role_base has no directory files/default/usr.local/bin

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/sk_role_base/recipes/usr_local_bin.rb

      3: remote_directory "/usr/local/bin" do
      4:   source "usr.local/bin"
      5:   files_mode "0755"
      6:   mode "0755"
      7: end
      8:

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/sk_role_base/recipes/usr_local_bin.rb:3:in `from_file'

    remote_directory("/usr/local/bin") do
      action :create
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      path "/usr/local/bin"
      recursive true
      source "usr.local/bin"
      files_backup 5
      files_mode "0755"
      overwrite true
      declared_type :remote_directory
      cookbook_name "sk_role_base"
      recipe_name "usr_local_bin"
      mode "0755"
      owner "root"
      group "root"
    end

[2015-01-29T10:13:18-08:00] ERROR: Converge failed with error message remote_directory[/usr/local/bin] (sk_role_base::usr_local_bin line 3) had an error: Chef::Exceptions::FileNotFound: cookbook sk_role_base has no directory files/default/usr.local/bin

Running handlers:
[2015-01-29T10:13:18-08:00] ERROR: Running exception handlers
Running handlers complete
[2015-01-29T10:13:18-08:00] ERROR: Exception handlers complete
[2015-01-29T10:13:18-08:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 6 resources updated in 137.547779866 seconds
[2015-01-29T10:13:19-08:00] FATAL: Chef::Exceptions::RunFailedWrappingError: Found 1 errors, they are stored in the backtrace
```

But `files/usr.local/bin` exists:

```
# ls -la /var/chef/cache/cookbooks/sk_role_base/files/usr.local/bin
total 16
drwxr-xr-x 2 root root 4096 Jan  9 13:36 ./
drwxr-xr-x 3 root root 4096 Jan  9 13:36 ../
-rw------- 1 root root  355 Jan  9 13:36 lesspipe.sh
-rw------- 1 root root  434 Jan  9 13:36 sysprep
```

```
1) Chef::Exceptions::FileNotFound -  remote_directory[/usr/local/bin] (sk_role_base::usr_local_bin line 3) had an error: Chef::Exceptions::FileNotFound: cookbook sk_role_base has no directory files/default/usr.local/bin
/opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:384:in `relative_filenames_in_preferred_directory'
/opt/chef/embedded/apps/chef/lib/chef/provider/remote_directory.rb:109:in `files_to_transfer'
/opt/chef/embedded/apps/chef/lib/chef/provider/remote_directory.rb:45:in `action_create'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:552:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:331:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:326:in `catch'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:326:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:345:in `converge_and_save'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:448:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:244:in `run_with_graceful_exit_option'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:221:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:202:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:365:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:40:in `load'
/usr/bin/chef-client:40:in `<main>'
```

**Comment by lamont-granquist** [comment]
@coderanger might be something missed in #2165
