### ISSUE TITLE
Knife boostrap in local_mode with a too generic error message

### ISSUE THREAD

**Issue by gionn** [chef/chef#2865]
Hi,

I was trying if it's possibile a workflow using the recent local_mode for chef-client, but I am stuck without a meaningful error message:

```
$ knife bootstrap gt-xps.local -z                                                                                                                                         
Connecting to gt-xps.local
ERROR: TypeError: no implicit conversion of nil into String
```

Is this supposed to works? I've not found anything on the documentation.

Other commands works, like:
```
$ knife node list
gt-xps.local
```
(I have a nodes/gt-xps.json)

Is there a way to get a proper stacktrace or something similar? I've tried -VV but it doesn't print anything useful.

**Comment by ianbamforth** [comment]
Also suffering the same problem I think - I use knife ec2 in local mode, and after creating the instance it bombs because it's using knife bootstrap.

**Comment by h4ck3rm1k3** [comment]
yes, same here.

**Comment by h4ck3rm1k3** [comment]
I have straced this:

```
 last 22723 stat("/var/lib/gems/2.1.0/gems/chef-12.4.1/lib/chef/knife/bootstrap/templates/chef-full.erb", {st_mode=S_IFREG|0644, st_size=5428, ...}) = 0
```
This was the last open, so I imagine it was something with the bootstrap.

**Comment by h4ck3rm1k3** [comment]
you can reproduce this with:

`` knife bootstrap 54.xx.xxx.xxx
Doing old-style registration with the validation key at ...
Delete your validation key in order to use your user credentials instead

Connecting to 54.xx.xxx.xxx
ERROR: TypeError: no implicit conversion of nil into String
````

So you can see it is the bootstrap error.

**Comment by h4ck3rm1k3** [comment]
Here is my patch to catch errors on the eval :+1: 

```
mdupont@mdupont-Aspire-7750G:~/experiments/chef$ diff /var/lib/gems/2.1.0/gems/chef-12.4.1/lib/chef/knife/bootstrap.rb ./lib/chef/knife/bootstrap.rb
307c307,316
<         Erubis::Eruby.new(template).evaluate(bootstrap_context)
---
> 
> 
>         ## error handler
>         begin
>           Erubis::Eruby.new(template).evaluate(bootstrap_context)
>         rescue => e
>           puts e.message
>           puts e.backtrace.inspect 
>         end
> 
```

Here is the stacktrace : 

no implicit conversion of nil into String
```
["/var/lib/gems/2.1.0/gems/chef-12.4.1/lib/chef/knife/core/bootstrap_context.rb:47:in `expand_path'", "/var/lib/gems/2.1.0/gems/chef-12.4.1/lib/chef/knife/core/bootstrap_context.rb:47:in `validation_key'", "(erubis):190:in `block in evaluate'", "/usr/lib/ruby/vendor_ruby/erubis/evaluator.rb:74:in `instance_eval'", "/usr/lib/ruby/vendor_ruby/erubis/evaluator.rb:74:in `evaluate'", "/var/lib/gems/2.1.0/gems/chef-12.4.1/lib/chef/knife/bootstrap.rb:311:in `render_template'", "/var/lib/gems/2.1.0/gems/chef-12.4.1/lib/chef/knife/bootstrap.rb:393:in `ssh_command'", "/var/lib/gems/2.1.0/gems/chef-12.4.1/lib/chef/knife/bootstrap.rb:372:in `knife_ssh'", "/var/lib/gems/2.1.0/gems/chef-12.4.1/lib/chef/knife/bootstrap.rb:386:in `knife_ssh_with_password_auth'", "/var/lib/gems/2.1.0/gems/chef-12.4.1/lib/chef/knife/bootstrap.rb:354:in `rescue in run'", "/var/lib/gems/2.1.0/gems/chef-12.4.1/lib/chef/knife/bootstrap.rb:347:in `run'", "/var/lib/gems/2.1.0/gems/knife-solo-0.5.2/lib/chef/knife/bootstrap_solo.rb:25:in `run'", "/var/lib/gems/2.1.0/gems/chef-12.4.1/lib/chef/knife.rb:425:in `block in run_with_pretty_exceptions'", "/var/lib/gems/2.1.0/gems/chef-12.4.1/lib/chef/local_mode.rb:39:in `with_server_connectivity'", "/var/lib/gems/2.1.0/gems/chef-12.4.1/lib/chef/knife.rb:424:in `run_with_pretty_exceptions'", "/var/lib/gems/2.1.0/gems/chef-12.4.1/lib/chef/knife.rb:215:in `run'", "/var/lib/gems/2.1.0/gems/chef-12.4.1/lib/chef/application/knife.rb:142:in `run'", "/var/lib/gems/2.1.0/gems/chef-12.4.1/bin/knife:25:in `<top (required)>'", "./knife:37:in `load'", "./knife:37:in `<main>'"]
```

**Comment by h4ck3rm1k3** [comment]
The culprit in my case: :validation_key was not set.
```def validation_key
          if File.exist?(File.expand_path(@chef_config[:validation_key]))
            IO.read(File.expand_path(@chef_config[:validation_key]))
          else
            false
          end
        end
```

**Comment by h4ck3rm1k3** [comment]
here is my patch : 

```
mdupont@mdupont-Aspire-7750G:~/experiments/chef$ diff /var/lib/gems/2.1.0/gems/chef-12.4.1/lib/chef/knife/core/bootstrap_context.rb ./lib/chef/knife/core/bootstrap_context.rb 
47,48c47,52
<           if File.exist?(File.expand_path(@chef_config[:validation_key]))
<             IO.read(File.expand_path(@chef_config[:validation_key]))
---
>           if @chef_config.has_key?("validation_key")
>             if File.exist?(File.expand_path(@chef_config[:validation_key]))
>               IO.read(File.expand_path(@chef_config[:validation_key]))
>             else
>               false
>             end

```

**Comment by h4ck3rm1k3** [comment]
https://github.com/chef/chef/pull/3866
