### ISSUE TITLE
Multipackage apt installs containing virtual packages are broken

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#2914]
On Ubuntu 14.10:

`package [ "libxslt-dev" ]` 

is broken.

There's a bug here where `package` (an array) is used where `pkg` (the individual package) should have been used:

https://github.com/chef/chef/blob/master/lib/chef/provider/package/apt.rb#L78

After fixing that, it still blows up:

```
1) Mixlib::ShellOut::ShellCommandFailed -  multipackage_install[collected packages] (sk_role_base::packages line 12) had an error: Mixlib::ShellOut::ShellCommandFailed: apt_package[collected packages] (/var/chef/cache/cookbooks/multipackage/providers/install.rb line 8) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
---- Begin output of apt-get -q -y install libxslt-dev=(none) ----
STDOUT:
STDERR: sh: 1: Syntax error: "(" unexpected
---- End output of apt-get -q -y install libxslt-dev=(none) ----
Ran apt-get -q -y install libxslt-dev=(none) returned 2
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.0/lib/mixlib/shellout.rb:267:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.0/lib/mixlib/shellout.rb:254:in `error!'
/opt/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:56:in `shell_out!'
/opt/chef/embedded/apps/chef/lib/chef/provider/package/apt.rb:179:in `run_noninteractive'
/opt/chef/embedded/apps/chef/lib/chef/provider/package/apt.rb:133:in `install_package'
/opt/chef/embedded/apps/chef/lib/chef/provider/package.rb:84:in `block in action_install'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `call'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:180:in `converge_by'
/opt/chef/embedded/apps/chef/lib/chef/provider/package.rb:83:in `action_install'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:561:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:61:in `recipe_eval_with_update_check'
/opt/chef/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:45:in `block in action'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:149:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:561:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:331:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:326:in `catch'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:326:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:345:in `converge_and_save'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:448:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:253:in `run_with_graceful_exit_option'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:230:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:365:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:40:in `load'
/usr/bin/chef-client:40:in `<main>'

Chef Client failed. 0 resources updated in 34.496115857 seconds
```

relevant section of the debug code showing where it goes wrong:

```
[2015-02-14T09:34:29-08:00] DEBUG: apt_package[collected packages] candidate version is 2.9.1+dfsg1-3ubuntu4.4
libxslt-dev:
  Installed: (none)
  Candidate: (none)
  Version table:
[2015-02-14T09:34:29-08:00] DEBUG: apt_package[collected packages] current version is nil
Package: libxslt-dev
Versions:

Reverse Depends:
  libabiword-3.0-dev,libxslt-dev
  ruby-build,libxslt-dev
  libabiword-3.0-dev,libxslt-dev
Dependencies:
Provides:
Reverse Provides:
libxslt1-dev 1.1.28-2build1
[2015-02-14T09:34:29-08:00] INFO: apt_package[collected packages] is a virtual package, actually acting on package[libxslt1-dev]
libxslt1-dev:
  Installed: 1.1.28-2build1
  Candidate: 1.1.28-2build1
  Version table:
 *** 1.1.28-2build1 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
```

Its getting '(none)' from the virtual package not the real package, and is thinking it isn't installed when libxslt1-dev really is installed.

**Comment by lamont-granquist** [comment]
@btm showstopper for Chef 12.1.0

**Comment by lamont-granquist** [comment]
Actually this has to be a non virtual package followed by a virtual package:

```
apt_package [ "zsh", "libxslt-dev" ]  # fails
apt_package [ "zsh", "libxslt-dev", "lsof" ] # fails
apt_package [ "libxslt-dev", "zsh" ] # works
apt_package "libxslt-dev" # works
apt_package [ "libxslt-dev" ] # works
```

So the impact isn't quite as bad as I thought, but its still a fairly bad bug in the multipackage apt stuff

**Comment by lamont-granquist** [comment]
Okay, figured it out.   My improvements to the package base class means that I'm no longer calling install_package with the full array and I've pruned it down to only the packages that need to install.  This is a problem because the subclass apt provider has the `@is_virtual_package` array which runs with the same indexes as all the `*_array`s in the package base class.  So when "zsh" is installed it only calls install_package with [ "libxslt-dev" ] but the @is_virtual_package array is [ "false", "true" ] so it thinks that "libxslt-dev" is not a virtual package.

Not sure of how to patch this.

Think is kinda screaming out that we need one array of abstract package objects that contain candidate_version, installed_version, is_virtual_package, etc and then we can prune that and don't have to keep indexes in synch across multiple isolated arrays (which was always pretty stinky), but I don't really want to clean all that up this weekend with another 1,000 line patch.

Also, it seems like it shouldn't be even trying to reinstall libxslt-dev since libxslt1-dev is already installed, so there's still some kind of bug there even earlier in the process as well.
