### ISSUE TITLE
New attributes from Chef 12 (source_url and source_url) crash Chef < 12

### ISSUE THREAD

**Issue by gregkare** [chef/chef#2937]
A metadata.rb with the new attributes like [mosh 0.4](https://github.com/jtimberman/mosh-cookbook/blob/1a85fc0ae22d6c5f3ea208e0db3e9a3a0c70eb3a/metadata.rb) crashes Chef 11 (probably Chef 10, I haven't checked as I don't use it anymore).

Is that behaviour expected? Are all new cookbook versions supposed to break compatibility with Chef 11? If not, are cookbook maintainers supposed to handle this themselves by using something like `if Gem::Version.new(Chef::VERSION) < Gem::Version.new('12.0.0')`?

```ruby
>> cl = Chef::CookbookLoader.new('./cookbooks/')
=> #<Chef::CookbookLoader:0x007f8e113f7518 @cookbooks_by_name={}, @loaded_cookbooks={}, @metadata={}, @cookbooks_paths={}, @chefignores={}, @repo_paths=["/path/chef/cookbooks"], @merged_cookbooks=[]>
>> cl.load_cookbooks
NoMethodError: undefined method `source_url' for #<Chef::Cookbook::Metadata:0x007f8e117529d8>
        from /path/chef/cookbooks/mosh/metadata.rb:17:in `from_file'
        from /path/chef/vendor/gems/ruby/2.1.0/gems/chef-11.16.4/lib/chef/mixin/from_file.rb:30:in `instance_eval'
        from /path/chef/vendor/gems/ruby/2.1.0/gems/chef-11.16.4/lib/chef/mixin/from_file.rb:30:in `from_file'
        from /path/chef/vendor/gems/ruby/2.1.0/gems/chef-11.16.4/lib/chef/cookbook/cookbook_version_loader.rb:172:in `apply_ruby_metadata'
        from /path/chef/vendor/gems/ruby/2.1.0/gems/chef-11.16.4/lib/chef/cookbook/cookbook_version_loader.rb:110:in `block in metadata'
        from /path/chef/vendor/gems/ruby/2.1.0/gems/chef-11.16.4/lib/chef/cookbook/cookbook_version_loader.rb:107:in `each'
        from /path/chef/vendor/gems/ruby/2.1.0/gems/chef-11.16.4/lib/chef/cookbook/cookbook_version_loader.rb:107:in `metadata'
        from /path/chef/vendor/gems/ruby/2.1.0/gems/chef-11.16.4/lib/chef/cookbook/cookbook_version_loader.rb:99:in `block in cookbook_version'
        from /path/chef/vendor/gems/ruby/2.1.0/gems/chef-11.16.4/lib/chef/cookbook/cookbook_version_loader.rb:88:in `tap'
        from /path/chef/vendor/gems/ruby/2.1.0/gems/chef-11.16.4/lib/chef/cookbook/cookbook_version_loader.rb:88:in `cookbook_version'
        from /path/chef/vendor/gems/ruby/2.1.0/gems/chef-11.16.4/lib/chef/cookbook_loader.rb:95:in `load_cookbook'
        from /path/chef/vendor/gems/ruby/2.1.0/gems/chef-11.16.4/lib/chef/cookbook_loader.rb:69:in `block (2 levels) in load_cookbooks'
        from /path/chef/vendor/gems/ruby/2.1.0/gems/chef-11.16.4/lib/chef/cookbook_loader.rb:68:in `each'
        from /path/chef/vendor/gems/ruby/2.1.0/gems/chef-11.16.4/lib/chef/cookbook_loader.rb:68:in `block in load_cookbooks'
        from /path/chef/vendor/gems/ruby/2.1.0/gems/chef-11.16.4/lib/chef/cookbook_loader.rb:67:in `each'
        from /path/chef/vendor/gems/ruby/2.1.0/gems/chef-11.16.4/lib/chef/cookbook_loader.rb:67:in `load_cookbooks'
        from (irb):2
```

Thanks in advance.

**Comment by lamont-granquist** [comment]
Its better to ask questions like this on StackOverflow, the mailing list or IRC.

But, yes, its the responsibility of the cookbook maintainer to provide backcompat if they're adopting features.  They can use `if respond_to?(:source_url)` or `if defined source_url` instead.  This should be a PR or bug against the mosh cookbook.

**Comment by MarkGibbons** [comment]
Fails on this u6 server - SunOS x0319vt124 5.10 Generic_144488-11 sun4v sparc SUNW,T5140   
Works on this u6 server - SunOS x0319t139 5.10 Generic_150400-16 sun4v sparc SUNW,T5140
