### ISSUE TITLE
Chef 12.0.3 Cookbook Upload Environment Pinning Failure

### ISSUE THREAD

**Issue by sean-horn** [chef/chef#2991]
Zendesk 3165
## OS Versions

Ubuntu 12.04
Mac OSX 7.5+
## Reproduction

The following command succeeds on both platforms with Chef 11.16.4 and fails on both platforms with Chef 12.0.3

```
knife cookbook upload COOKBOOKNAME -E ENVIRONMENTNAME
```

with the following stacktrace

```
knife cookbook upload junk -E production -VV
INFO: Using configuration from /home/vagrant/.chef/knife.rb
/opt/chef/embedded/apps/chef/lib/chef/knife/cookbook_upload.rb:200:in `environment': uninitialized constant Chef::Knife::CookbookUpload::Environment (NameError)
    from /opt/chef/embedded/apps/chef/lib/chef/knife/cookbook_upload.rb:226:in `assert_environment_valid!'
    from /opt/chef/embedded/apps/chef/lib/chef/knife/cookbook_upload.rb:95:in `run'
    from /opt/chef/embedded/apps/chef/lib/chef/knife.rb:417:in `block in run_with_pretty_exceptions'
    from /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
    from /opt/chef/embedded/apps/chef/lib/chef/knife.rb:416:in `run_with_pretty_exceptions'
    from /opt/chef/embedded/apps/chef/lib/chef/knife.rb:213:in `run'
    from /opt/chef/embedded/apps/chef/lib/chef/application/knife.rb:139:in `run'
    from /opt/chef/embedded/apps/chef/bin/knife:25:in `<top (required)>'
    from /usr/bin/knife:40:in `load'
    from /usr/bin/knife:40:in `<main>'
```
## Workaround

If I change the environment method in `/opt/chef/embedded/apps/chef/lib/chef/knife/cookbook_upload.rb` like this

```
      def environment
        @environment ||= config[:environment] ? ::Chef::Environment.load(config[:environment]) : nil
      end
```

and the `/opt/chef/embedded/apps/chef/lib/chef/knife.rb` requires like this

```
require 'chef/rest'
require 'chef/environment'
require 'pp'
```

It seems to work ok.
There may be a better way to do this?

**Comment by sean-horn** [comment]
Customer reports back that this solved the issue.

**Comment by kelvinatstreetline** [comment]
work around not working, still getting the same error.

**Comment by lamont-granquist** [comment]
This needs replication to determine if it still exists as a problem in Chef 15

**Comment by vsingh-msys** [comment]
Tested it with the latest chef-15 seems it working fine we can close this issue.

Steps followed: 
```
#> knife -v
Chef Infra Client: 15.4.1

#> knife environment create production
Created production

#> knife cookbook upload starter -E production -VV
INFO: Using configuration from /chef-workstation/.chef/config.rb
Uploading starter        [1.0.13]
INFO: Validating ruby files
INFO: Validating templates
INFO: Syntax OK
INFO: Saving starter
INFO: Uploading files
INFO: Upload complete!
Uploaded 1 cookbook.
```
