### ISSUE TITLE
Error loading gems on chef-client 12.1.0 upgrade

### ISSUE THREAD

**Issue by eheydrick** [chef/chef#3024]
Upgrading from 12.0.3 to 12.1.0 using omnibus_updater results in a gem loading error and a dead client.

```
can't activate highline-1.7.1, already activated highline-1.6.21
````

**Comment by jdmundrawala** [comment]
What platform? Did you get a stack trace?

**Comment by eheydrick** [comment]
Ubuntu 14.04. 

```
Generated at 2015-03-04 03:20:41 +0000
Gem::LoadError: can't activate highline-1.7.1, already activated highline-1.6.21
/opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2087:in `check_version_conflict'
/opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1278:in `activate'
/opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:198:in `rescue in try_activate'
/opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:195:in `try_activate'
/opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
/opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
/opt/chef/embedded/apps/chef/lib/chef/formatters/indentable_output_stream.rb:22:in `highline'
/opt/chef/embedded/apps/chef/lib/chef/formatters/indentable_output_stream.rb:126:in `print_line'
/opt/chef/embedded/apps/chef/lib/chef/formatters/indentable_output_stream.rb:108:in `print_string'
/opt/chef/embedded/apps/chef/lib/chef/formatters/indentable_output_stream.rb:79:in `block in print'
/opt/chef/embedded/apps/chef/lib/chef/formatters/indentable_output_stream.rb:74:in `synchronize'
/opt/chef/embedded/apps/chef/lib/chef/formatters/indentable_output_stream.rb:74:in `print'
/opt/chef/embedded/apps/chef/lib/chef/formatters/indentable_output_stream.rb:44:in `puts'
/opt/chef/embedded/apps/chef/lib/chef/formatters/base.rb:79:in `puts'
/opt/chef/embedded/apps/chef/lib/chef/formatters/base.rb:108:in `display_error'
/opt/chef/embedded/apps/chef/lib/chef/formatters/base.rb:140:in `resource_failed'
/opt/chef/embedded/apps/chef/lib/chef/event_dispatch/dispatcher.rb:29:in `block in resource_failed'
/opt/chef/embedded/apps/chef/lib/chef/event_dispatch/dispatcher.rb:29:in `each'
/opt/chef/embedded/apps/chef/lib/chef/event_dispatch/dispatcher.rb:29:in `resource_failed'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:594:in `rescue in run_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:603:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:57:in `block in run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:55:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:55:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:111:in `run_delayed_notification'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:99:in `block in run_delayed_notifications'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:98:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:98:in `run_delayed_notifications'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:88:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:315:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:400:in `block in run'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:399:in `catch'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:399:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:261:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:215:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:201:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:355:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:345:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:345:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:335:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:40:in `load'
/usr/bin/chef-client:40:in `<main>'
```

**Comment by btm** [comment]
@eheydrick 'chef gem list' ?

**Comment by jdmundrawala** [comment]
`gem dependency -R highline`

**Comment by eheydrick** [comment]
```
/opt/chef/embedded/bin/gem list

*** LOCAL GEMS ***

activesupport (3.2.21)
appbundler (0.4.0)
bigdecimal (1.2.4)
builder (3.2.2)
bundler (1.7.2)
chef (12.1.0)
chef-rewind (0.0.9)
chef-zero (4.0)
coderay (1.1.0)
diff-lcs (1.2.5)
docile (1.1.5)
erubis (2.7.0)
ffi (1.9.6)
ffi-yajl (1.4.0)
hashie (2.1.2)
highline (1.7.1)
hipchat (1.4.0)
httparty (0.13.3)
i18n (0.7.0)
io-console (0.4.2)
ipaddress (0.8.0)
json (1.8.1)
libyajl2 (1.2.0)
method_source (0.8.2)
mime-types (2.4.3)
minitest (4.7.5)
mixlib-authentication (1.3.0)
mixlib-cli (1.5.0)
mixlib-config (2.1.0)
mixlib-log (1.6.0)
mixlib-shellout (2.0.1)
multi_json (1.10.1)
multi_xml (0.5.5)
net-dhcp (1.3.2)
net-scp (1.2.1)
net-ssh (2.9.2)
net-ssh-gateway (1.2.0)
net-ssh-multi (1.2.0)
ohai (8.1.1)
plist (3.1.0)
pry (0.10.1)
psych (2.0.5)
rack (1.5.2)
rake (10.4.2, 10.1.1, 10.1.0)
rdoc (4.1.0)
rspec (3.2.0)
rspec-core (3.2.1)
rspec-expectations (3.2.0)
rspec-its (1.2.0)
rspec-mocks (3.2.1)
rspec-support (3.2.2)
rspec_junit_formatter (0.2.0)
ruby-shadow (2.4.1)
serverspec (2.9.1)
simplecov (0.9.2)
simplecov-html (0.9.0)
slop (3.6.0)
specinfra (2.18.0)
systemu (2.6.4)
test-unit (2.1.4.0)
uuidtools (2.1.5)
wmi-lite (1.0.0)
```

```
/opt/chef/embedded/bin/gem dependency -R highline
Gem highline-1.7.1
  code_statistics (>= 0, development)
  Used by
    chef-12.1.0 (highline (>= 1.6.9, ~> 1.6))
```

**Comment by jdmundrawala** [comment]
I don't see highline 1.6.x...wonder where it's getting it form

**Comment by btm** [comment]
@eheydrick is your gems installation trolling us?

 ```find /opt/chef -name 'highline-*'```

**Comment by eheydrick** [comment]
highline 1.6.x is coming from the 12.0.3 install. 

```
$ chef-client --version
Chef: 12.0.3
$ /opt/chef/embedded/bin/gem list highline

*** LOCAL GEMS ***

highline (1.6.21)
```

**Comment by eheydrick** [comment]
Should add that the client works fine once I start it back up. It bombs out during the omnibus_upgrade run.

**Comment by tyler-ball** [comment]
I think this is what is happening...

1. Chef client 12.0.3 starts and loads highline 1.6
2. The omnibus_upgrade installs the new package which adds highline 1.7 gem
3. Chef continues running and encounters another `require 'highline'`
4. This tries to load highline 1.7, which causes the error

**Comment by lamont-granquist** [comment]
do we have to do something like `require 'highline'` unless defined? Highline`?

**Comment by lamont-granquist** [comment]
(and if rubygems can't load two different versions of the same gem, why doesn't it already essentially do that?)

**Comment by jdmundrawala** [comment]
appbundler is going to activate the 1.6 gem when chef starts, and then omnubus_updater is deleting the 1.6 gem...so weird stuff happens when you try to use it?

**Comment by eheydrick** [comment]
Had this happen again on upgrade from 12.2.1 to 12.3.0

**Comment by thechile** [comment]
I have this going from chef 11.4 to 11.18. 

`Gem::LoadError: can't activate highline-1.7.2, already activated highline-1.6.15`

This was after updating the client with `yum update chef`

**Comment by lamont-granquist** [comment]
The root cause of this is that you need to have this option set to true:

```
default[:omnibus_updater][:kill_chef_on_upgrade] = true
```

If omnibus_updater runs and updates chef-client, then chef-client cannot continue or this kind of thing will happen.  The kill_chef_on_upgrade attribute should not really be optional.  There's not really a bug to fix here inside of chef-client.

We want to pull omnibus_updater like logic into chef-client and we probably won't make the restart chef-client behavior optional because of tickets like this.
