### ISSUE TITLE
Net::HTTPServerException: 412 "Precondition Failed" error message isn't helpful

### ISSUE THREAD

**Issue by vkatsikaros** [chef/chef#3083]
The exception `Net::HTTPServerException: 412 "Precondition Failed"` causes chef-client to fail.

## Behavior
A message is displayed and provides 3 possible causes of the problem

## Expected behavior
Display the module/contraint that caused the problem, and the informational message with the 3 possible causes.

## Example
```
$ chef-client 
Starting Chef Client, version 11.6.2
resolving cookbooks for run list: ["cookbook1", "cookbook2", ..., "cookbookN"]

================================================================================
Error Resolving Cookbooks for Run List:
================================================================================


Cookbook dependency resolution error:
-------------------------------------
Error message: unable to solve dependencies in alotted time
You might be able to resolve this issue with:
  1-) Removing cookbook versions that depend on deleted cookbooks.
  2-) Removing unused cookbook versions.
  3-) Pinning exact cookbook versions using environments.



Expanded Run List:
------------------
* cookbook1
* cookbook2
...
* cookbookN


[2015-03-16T10:18:43+00:00] ERROR: Running exception handlers
[2015-03-16T10:18:43+00:00] ERROR: Exception handlers complete
[2015-03-16T10:18:43+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated
[2015-03-16T10:18:43+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)


$ cat /var/chef/cache/chef-stacktrace.out 
Generated at 2015-03-16 10:18:43 +0000
Net::HTTPServerException: 412 "Precondition Failed"
/opt/chef/embedded/lib/ruby/1.9.1/net/http.rb:2633:in `error!'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/rest.rb:207:in `block in raw_http_request'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/rest.rb:289:in `retriable_rest_request'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/rest.rb:167:in `raw_http_request'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/rest.rb:161:in `api_request'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/rest.rb:121:in `post'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/client.rb:402:in `sync_cookbooks'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/client.rb:243:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/client.rb:492:in `do_run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/client.rb:199:in `block in run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/client.rb:193:in `fork'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/client.rb:193:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/application.rb:183:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/application/client.rb:302:in `block in run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/application/client.rb:294:in `loop'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/application/client.rb:294:in `run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.6.2/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:23:in `load'
/usr/bin/chef-client:23:in `<main>'
```

**Comment by lamont-granquist** [comment]
This is a chef-server bug, so its misfiled here.  It is also all going to change very soon with PolicyFiles as depsolving is moved from the server to the Chef-DK command line workstation client.  This error message is likely to be deprecated and retired before it is ever fixed.

**Comment by katt0050** [comment]
@vkatsikaros 
I am running into similar issue. Wondering if you figured out what the issue is, in your case? If so, can you please explain how you found the issue?
