### ISSUE TITLE
OpenBSD package provider installation issues

### ISSUE THREAD

**Issue by vxnick** [chef/chef#3096]
Chef Client 12.1.1
OpenBSD 5.6, attempting to install VIM (for which `pkg_add` prompts for a choice)

Unable to install `vim-7.4.135p2-no_x11` via the package provider.

## Steps to reproduce

Install `vim-7.4.135p2-no_x11` on OpenBSD via `package 'vim-7.4.135p2-no_x11'`.

The output from this is: https://gist.github.com/vxnick/318c68e7c2895d0e07fd, but the package is not actually installed.

Specifying `package 'vim'` installs the first choice from the `pkg_add` prompt, which is `vim-7.4.135p2-gtk2` - not what I want.

The output from this is: https://gist.github.com/vxnick/b03880d643c728fb8760

**Comment by jdmundrawala** [comment]
The original commit of this code would fail in this case because it could not find it... which is a regression. It should not say up-to-date.

The following code did at one time work
```ruby
package 'vim' do
  version '7.4.135p2-no_x11'
end
```

however no longer does:
```
[2015-03-18T17:44:59+00:00] ERROR: openbsd_package[vim] (@recipe_files::/home/vagrant/chef/test.rb line 1) had an error: NameError: undefined local variable or method `version' for #<Chef::Provider::Package::Openbsd:0x000b535a8dc350>
[2015-03-18T17:45:00+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

The full stack trace:
```
bash-4.3# cat ~/.chef/local-mode-cache/cache/chef-stacktrace.out
Generated at 2015-03-18 17:44:59 +0000
NameError: openbsd_package[vim] (@recipe_files::/home/vagrant/chef/test.rb line 1) had an error: NameError: undefined local variable or method `version' for #<Chef::Provider::Package::Openbsd:0x000b535a8dc350>
/home/vagrant/chef/lib/chef/provider/package/openbsd.rb:88:in `candidate_version'
/home/vagrant/chef/lib/chef/provider/package.rb:457:in `candidate_version_array'
/home/vagrant/chef/lib/chef/provider/package.rb:438:in `block in each_package'
/home/vagrant/chef/lib/chef/provider/package.rb:437:in `each'
/home/vagrant/chef/lib/chef/provider/package.rb:437:in `each_with_index'
/home/vagrant/chef/lib/chef/provider/package.rb:437:in `each_package'
/home/vagrant/chef/lib/chef/provider/package.rb:423:in `forced_packages_missing_candidates'
/home/vagrant/chef/lib/chef/provider/package.rb:54:in `block in define_resource_requirements'
/home/vagrant/chef/lib/chef/mixin/why_run.rb:315:in `assert'
/home/vagrant/chef/lib/chef/provider/package.rb:52:in `define_resource_requirements'
/home/vagrant/chef/lib/chef/provider.rb:134:in `run_action'
/home/vagrant/chef/lib/chef/resource.rb:561:in `run_action'
/home/vagrant/chef/lib/chef/runner.rb:49:in `run_action'
/home/vagrant/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/home/vagrant/chef/lib/chef/runner.rb:81:in `each'
/home/vagrant/chef/lib/chef/runner.rb:81:in `block in converge'
/home/vagrant/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/home/vagrant/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/home/vagrant/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/home/vagrant/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/home/vagrant/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/home/vagrant/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/home/vagrant/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/home/vagrant/chef/lib/chef/runner.rb:80:in `converge'
/home/vagrant/chef/lib/chef/client.rb:331:in `block in converge'
/home/vagrant/chef/lib/chef/client.rb:326:in `catch'
/home/vagrant/chef/lib/chef/client.rb:326:in `converge'
/home/vagrant/chef/lib/chef/client.rb:345:in `converge_and_save'
/home/vagrant/chef/lib/chef/client.rb:449:in `run'
/home/vagrant/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
/home/vagrant/chef/lib/chef/application.rb:259:in `fork'
/home/vagrant/chef/lib/chef/application.rb:259:in `fork_chef_client'
/home/vagrant/chef/lib/chef/application.rb:225:in `block in run_chef_client'
/home/vagrant/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/home/vagrant/chef/lib/chef/application.rb:213:in `run_chef_client'
/home/vagrant/chef/lib/chef/application/client.rb:392:in `block in interval_run_chef_client'
/home/vagrant/chef/lib/chef/application/client.rb:382:in `loop'
/home/vagrant/chef/lib/chef/application/client.rb:382:in `interval_run_chef_client'
/home/vagrant/chef/lib/chef/application/client.rb:372:in `run_application'
/home/vagrant/chef/lib/chef/application.rb:60:in `run'
/home/vagrant/chef/bin/chef-client:26:in `<top (required)>'
/usr/local/lib/ruby/gems/2.1/bin/chef-client:23:in `load'
/usr/local/lib/ruby/gems/2.1/bin/chef-client:23:in `<main>'
```
