### ISSUE TITLE
SmartOS "pkgin install" failing to get proper package name

### ISSUE THREAD

**Issue by hulu1522** [chef/chef#3112]
I am running converges on a Joyent SmartOS machine.

This is my resource:

```ruby
package "postgresql94-server" do
	action :install
end
```

This is the error:
````
           ================================================================================
       Error executing action `install` on resource 'smartos_package[postgresql94-server]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '3'
           ---- Begin output of /opt/local/bin/pkgin -y install postgresql94-server-9.4.0;;PostgreSQL ----
           STDOUT:
           STDERR: sh: syntax error at line 1: `;;' unexpected
       ---- End output of /opt/local/bin/pkgin -y install postgresql94-server-9.4.0;;PostgreSQL ----
       Ran /opt/local/bin/pkgin -y install postgresql94-server-9.4.0;;PostgreSQL returned 3

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/tcn_db/recipes/testing.rb

        19: package "postgresql94-server" do
        20:        action :install
        21: end
            22:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/tcn_db/recipes/testing.rb:19:in `from_file'

       smartos_package("postgresql94-server") do
         action [:install]
         retries 0
             retry_delay 2
             default_guard_interpreter :default
             package_name "postgresql94-server"
             version "9.4.0;;PostgreSQL"
             timeout 900
         declared_type :package
         cookbook_name "tcn_db"
         recipe_name "testing"
       end

       [2015-03-19T19:12:07+00:00] ERROR: Converge failed with error message smartos_package[postgresql94-server] (tcn_db::testing line 19) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '3'
       ---- Begin output of /opt/local/bin/pkgin -y install postgresql94-server-9.4.0;;PostgreSQL ----
       STDOUT:
       STDERR: sh: syntax error at line 1: `;;' unexpected
       ---- End output of /opt/local/bin/pkgin -y install postgresql94-server-9.4.0;;PostgreSQL ----
       Ran /opt/local/bin/pkgin -y install postgresql94-server-9.4.0;;PostgreSQL returned 3

       Running handlers:
       [2015-03-19T19:12:07+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-03-19T19:12:07+00:00] ERROR: Exception handlers complete
       [2015-03-19T19:12:07+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       Chef Client failed. 0 resources updated in 3.281732583 seconds
       [2015-03-19T19:12:07+00:00] ERROR: Found 1 errors, they are stored in the backtrace
       [2015-03-19T19:12:07+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
````

Line of code it is referencing (I think):
https://github.com/chef/chef/blob/master/lib/chef/provider/package/smartos.rb#L77

**Comment by hulu1522** [comment]
UPDATE:

It will actually install if you specify a version in the resource.

```ruby
package "postgresql94-server" do
    version "9.4.0"
    action :install
end
````

**Comment by jdmundrawala** [comment]
What version of chef client?
Stack trace would also be helpful

**Comment by hulu1522** [comment]
Ruby 2.1.0
Chef 12.1.1

```
Generated at 2015-03-20 02:07:53 +0000
Chef::Exceptions::RunFailedWrappingError: Found 1 errors, they are stored in the backtrace
1) Mixlib::ShellOut::ShellCommandFailed -  smartos_package[postgresql94-server] (tcn_db::testing line 39) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '3'
---- Begin output of /opt/local/bin/pkgin -y install postgresql94-server-9.4.0;;PostgreSQL ----
STDOUT:
STDERR: sh: syntax error at line 1: `;;' unexpected
---- End output of /opt/local/bin/pkgin -y install postgresql94-server-9.4.0;;PostgreSQL ----
Ran /opt/local/bin/pkgin -y install postgresql94-server-9.4.0;;PostgreSQL returned 3
/opt/local/lib/ruby/gems/2.0.0/gems/mixlib-shellout-2.0.1/lib/mixlib/shellout.rb:278:in `invalid!'
/opt/local/lib/ruby/gems/2.0.0/gems/mixlib-shellout-2.0.1/lib/mixlib/shellout.rb:265:in `error!'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/mixin/shell_out.rb:56:in `shell_out!'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/provider/package/smartos.rb:77:in `install_package'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/provider/package.rb:87:in `block in action_install'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/mixin/why_run.rb:52:in `call'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/provider.rb:180:in `converge_by'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/provider/package.rb:86:in `action_install'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/provider.rb:145:in `run_action'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/resource.rb:561:in `run_action'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/runner.rb:49:in `run_action'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/runner.rb:81:in `each'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/runner.rb:81:in `block in converge'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/runner.rb:80:in `converge'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/client.rb:331:in `block in converge'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/client.rb:326:in `catch'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/client.rb:326:in `converge'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/client.rb:345:in `converge_and_save'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/client.rb:448:in `run'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/application.rb:271:in `block in fork_chef_client'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/application.rb:259:in `fork'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/application.rb:259:in `fork_chef_client'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/application.rb:225:in `block in run_chef_client'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/application.rb:213:in `run_chef_client'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/application/client.rb:392:in `block in interval_run_chef_client'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/application/client.rb:382:in `loop'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/application/client.rb:382:in `interval_run_chef_client'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/application/client.rb:372:in `run_application'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/lib/chef/application.rb:60:in `run'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.1.1/bin/chef-client:26:in `<top (required)>'
/opt/chef/bin/chef-client:23:in `load'
/opt/chef/bin/chef-client:23:in `<main>'
```

[This](https://github.com/chef/chef/blob/master/lib/chef/provider/package/smartos.rb#L67) probably needs to be:   `name, version = line.split[0].split(/-([^-]+);;.*$/)`.

**Comment by bahamas10** [comment]
this should fix it ^

also this is a perfect example of `sh` injection (the `;` character being interpreted by `sh`).  the calls to `shell_out` should be as separate arguments, or an array, so the shell is skipped.

**Comment by joshzitting** [comment]
Same issue... 
==================
           Error executing action `install` on resource 'smartos_package[bc]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '3'
           ---- Begin output of /opt/local/bin/pkgin -y install bc-1.06nb3;;Arbitrary ----
           STDOUT:
           STDERR: sh: syntax error at line 1: `;;' unexpected
       ---- End output of /opt/local/bin/pkgin -y install bc-1.06nb3;;Arbitrary ----
       Ran /opt/local/bin/pkgin -y install bc-1.06nb3;;Arbitrary returned 3

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/tcn_monitor/recipes/client_install.rb

        48: package "bc" do
        49:   action :install
            50: end
            51:

           Compiled Resource:

**Comment by btm** [comment]
Did this work with earlier versions of Chef?

What is the output of ```/opt/local/bin/pkgin se postgresql94-server``` or ```/opt/local/bin/pkgin se bc```?

**Comment by hulu1522** [comment]
```
[root@058e52df-de6f-cef8-9e98-8d02fb5033f8 ~]# /opt/local/bin/pkgin se postgresql94-server
postgresql94-server-9.4.0  PostgreSQL database server programs

=: package is installed and up-to-date
<: package is installed but newer version is available
>: installed package has a greater version than available package


[root@058e52df-de6f-cef8-9e98-8d02fb5033f8 ~]# /opt/local/bin/pkgin se bc
xkbcomp-1.3.0        XKBD keymap compiler
xbeeb-0.4.1nb2       Acorn BBC Micro emulator with an X based interface
vobcopy-1.2.0nb1     Copies DVD .vob files to harddisk
unixodbc-2.3.0nb2    ODBC 2.x/3.x driver manager
tex-abc-doc-1.0      Documentation for tex-abc
tex-abc-1.0nb1       Support ABC music notation in LaTeX
sqlrelay-odbc-0.57   ODBC support for SQL Relay
spiceprm-0.11nb3     Spice preprocessor for parameterized subcircuits
smbchartool-2.3anb6  File name conversion tool for Samba
sbcl-1.2.0           SBCL, a Common Lisp implementation
ruby215-patron-0.4.18nb3  Ruby HTTP client library based on libcurl
ruby215-odbc-0.99995nb1  ODBC binding for Ruby
ruby215-dbd-odbc-0.2.5nb1  ODBC support for Ruby/DBI
ruby215-bcrypt-3.1.7  OpenBSD's bcrypt() password hashing algorithm for Ruby
ruby215-activerecord-odbc-2.0nb1  ActiveRecord ODBC adapter
ruby200-patron-0.4.18nb3  Ruby HTTP client library based on libcurl
ruby200-odbc-0.99995nb1  ODBC binding for Ruby
ruby200-dbd-odbc-0.2.5nb1  ODBC support for Ruby/DBI
ruby200-bcrypt-3.1.7  OpenBSD's bcrypt() password hashing algorithm for Ruby
ruby200-activerecord-odbc-2.0nb1  ActiveRecord ODBC adapter
ruby193-patron-0.4.18nb3  Ruby HTTP client library based on libcurl
ruby193-odbc-0.99995nb1  ODBC binding for Ruby
ruby193-dbd-odbc-0.2.5nb1  ODBC support for Ruby/DBI
ruby193-bcrypt-3.1.7  OpenBSD's bcrypt() password hashing algorithm for Ruby
ruby193-activerecord-odbc-2.0nb1  ActiveRecord ODBC adapter
ruby18-patron-0.4.18nb3  Ruby HTTP client library based on libcurl
ruby18-odbc-0.99995nb1  ODBC binding for Ruby
ruby18-dbd-odbc-0.2.5nb1  ODBC support for Ruby/DBI
ruby18-bcrypt-3.1.7  OpenBSD's bcrypt() password hashing algorithm for Ruby
ruby18-activerecord-odbc-2.0nb1  ActiveRecord ODBC adapter
qt5-odbc-5.2.1nb1    Qt5 odbc plugin
py34-webcolors-1.4   Library for working with color specifications for HTML and CSS
py34-bcrypt-1.0.2    Modern password hashing for your software and your servers
py34-apache-libcloud-0.14.1  Python library for interacting with cloud service providers
py33-webcolors-1.4   Library for working with color specifications for HTML and CSS
py33-bcrypt-1.0.2    Modern password hashing for your software and your servers
py33-apache-libcloud-0.14.1  Python library for interacting with cloud service providers
py27-webcolors-1.4   Library for working with color specifications for HTML and CSS
py27-compizconfig-0.8.4nb29  Python bindings for libcompizconfig
py27-bcrypt-1.0.2    Modern password hashing for your software and your servers
py27-apache-libcloud-0.14.1  Python library for interacting with cloud service providers
py26-webcolors-1.4   Library for working with color specifications for HTML and CSS
py26-compizconfig-0.8.4nb29  Python bindings for libcompizconfig
py26-bcrypt-1.0.2    Modern password hashing for your software and your servers
py26-apache-libcloud-0.14.1  Python library for interacting with cloud service providers
poco-data-odbc-1.4.2p1nb2  POCO C++ ODBC RDBMS Accessor libraries
php56-pdo_odbc-5.6.6  PHP ODBC v3 Interface driver for PDO
php56-pdo_odbc-5.6.5  PHP ODBC v3 Interface driver for PDO
php56-bcmath-5.6.6   PHP extension for bc-style arbitrary precision math
php56-bcmath-5.6.5   PHP extension for bc-style arbitrary precision math
php55-pdo_odbc-5.5.22  PHP ODBC v3 Interface driver for PDO
php55-pdo_odbc-5.5.21  PHP ODBC v3 Interface driver for PDO
php55-bcmath-5.5.22  PHP extension for bc-style arbitrary precision math
php55-bcmath-5.5.21  PHP extension for bc-style arbitrary precision math
php54-pdo_odbc-5.4.38  PHP ODBC v3 Interface driver for PDO
php54-pdo_odbc-5.4.37  PHP ODBC v3 Interface driver for PDO
php54-bcmath-5.4.38  PHP extension for bc-style arbitrary precision math
php54-bcmath-5.4.37  PHP extension for bc-style arbitrary precision math
php53-pdo_odbc-5.3.29  PHP ODBC v3 Interface driver for PDO
php53-bcmath-5.3.29  PHP extension for bc-style arbitrary precision math
perdition-odbc-1.18nb1  IMAP/POP3 proxy redirector (UnixODBC user database module)
pbc-0.5.14           Pair-based cryptographic library based on Gap Diffie Helman groups
p5-Tie-RefHash-Weak-0.09nb6  Perl 5 Tie::RefHash subclass with weakened references in the keys
p5-Test-WWW-Mechanize-1.44nb2  Perl5 module providing testing-specific WWW::Mechanize subclass
p5-Test-SubCalls-1.09nb5  Perl5 module to track the number of times subs are called
p5-Template-Multilingual-1.00nb5  Subclass of Template Toolkit supporting multilingual templates
p5-MooseX-NonMoose-0.26  Perl 5 module to subclass non-Moose classes with Moose
p5-LWPx-ParanoidAgent-1.10nb1  Subclass of module LWP::UserAgent that protects you from harm
p5-DBD-ODBC-1.50     Perl DBI/DBD driver for ODBC
p5-Curses-UI-POE-0.03500nb5  Subclass for Curses::UI that enables it to work with POE
p5-Crypt-Rijndael-1.12nb1  Crypt::CBC compliant Rijndael encryption module
p5-Crypt-CBC-2.33nb2  Perl5 cipher block chaining mode for various crypto algorithms
odbc-postgresql-9.0.200nb3  ODBC interface to PostgreSQL
obconf-2.0.4nb1      Tool for configuring the Openbox window manager
nspr-4.10.7          Platform-neutral API for system level and libc like functions
myodbc-5.3.2         ODBC driver (server side) for MySQL
lua52-curl-0.2nb8    Full lua bindings for libcurl
lua51-curl-0.2nb8    Full lua bindings for libcurl
libxkbcommon-0.5.0   Library to handle keyboard descriptions
libnbcompat-20140725  Portable NetBSD compatibility library
libexecinfo-1.1nb1   BSD Licensed clone of backtrace facility found in GNU libc
libcurvecpr-20130806  Uses elliptic-curve cryptography to encrypt and authenticate data
libcuefile-0rc475    CUE File library for the musepack decoder
libctl-3.2.1         Guile-based flexible control file library for scientific simulations
libcroco-0.6.8       Toolkit to parse and manipulate CSS (Cascading Style Sheets)
libcrack-2.7nb1      Password checking library
libcouchbase-2.3.2   C/C++ client library to access a Couchbase server
libconfig-1.4.9      Simple library for manipulating structured configuration files
libcomprex-0.3.3nb8  Library to handle (de)compression of files
libcompizconfig-0.8.8nb12  Configuration backend for compiz
libcmis-0.4.1nb3     Client library for the CMIS interface
libclucene-2.3.3.4nb4  Text search engine written in C++
libchewing-0.4.0nb1  The intelligent phonetic input method library
libchewing-0.2.7     The intelligent phonetic input method library
libchamplain08-0.8.3nb26  Map widget
libchamplain06-0.6.1nb30  Map widget
libchamplain04-0.4.7nb24  Map widget
libcfg+-0.6.2nb3     Command line and configuration file parsing library
libcdr-0.1.1         Corel Draw file format importer library
libcdio-paranoia-0.93  CD-ROM access library: CDDA support
libcdio-0.93         CD-ROM access library
libcddb-1.3.2nb1     Library to access data on a CDDB server
libcdaudio-0.99.12nb2  Multi-platform CD player development library
libcassandra-20101010nb17  C++ interface to Cassandra
libcares-1.10.0      Asynchronous resolver library, c-ares
libcarddav-0.6.2.2.2nb6  CardDAV library
libcanberra-0.27nb4  Desktop event sound library
libcaca-0.99.18      Graphics library that outputs text instead of pixels, in colour
jdbc-postgresql92-1002  PostgreSQL 9.2 JDBC4 driver
jdbc-postgresql84-701  PostgreSQL 8.4 JDBC3 driver
jdbc-mysql-5.0.8     MySQL 5.0 JDBC driver
jdbc-mysql-3.1.14    MySQL 3.1 JDBC driver
jcabc2ps-20060106nb3  Music typesetting program for abc
iodbc-3.52.9         ODBC 3.x driver manager
heirloom-libcommon-070715  Collection of standard Unix utilities (libcommon)
hebcal-3.11          Perpetual Hebrew calendar
gambc-4.6.5          GambitC Scheme System
festvox-abc-2.0nb1   Mexican Spanish male voice for the festival speech synthesis system
evolution-webcal-2.32.0nb29  GNOME URL handler for web-published iCal calendar files
epubcheck-1.2        Tool to validate IDPF Epub files
compiz-bcop-0.8.8nb1  Option code generator for compiz
cheese-2.26.3nb39    Use your webcam to take photos and videos
ccxstream-1.0.15     Program for streaming multimedia content to XMBC over XBMSP protocol
bibclean-2.11.4nb1   Prettyprinter and syntax checker for BibTeX bibliography databases
bcrypt-1.1           Cross platform file encryption utility
bcollect-0.6.0       Incremental remote backup tool
bchunk-1.2.0         `.bin/.cue` CD image converter
bc-1.06nb3           Arbitrary precision calculator language
bbcim-0.95b5nb1      File and diskimage conversion utility for BBC Micro software
argp-1.3nb1          Argument parsing function from glibc
abcmidi-20121201     Music utilities for abc
abcm2ps-6.6.6nb12    Converts ABC to music sheet in PostScript format
abclock-1.0d         Analogue Bitmap Clock
abcl-1.3.1           Armed Bear Common Lisp
abcde-2.3.99.7nb2    Command-line utility to rip and encode an audio CD
abc2ps-1.3.3         Music typesetting program for abc

=: package is installed and up-to-date
<: package is installed but newer version is available
>: installed package has a greater version than available package
```

**Comment by btm** [comment]
I don't understand where the ;; is coming from.

**Comment by hulu1522** [comment]
Neither do we.  Maybe we change the [fix above](https://github.com/chef/chef/issues/3112#issuecomment-83853033) to this:
`name, version = line.gsub(/;/, ' ').split[0].split(/-([^-]+)$/)`

**Comment by bahamas10** [comment]
aha! what a fun issue

writing to stdout (is a tty)... notice it's separated by spaces

```
[root@arbiter ~]# pkgin se htop
htop-1.0.1           Enhanced version of top utility

=: package is installed and up-to-date
<: package is installed but newer version is available
>: installed package has a greater version than available package
```

writing to `cat` (not a tty)... noticed it's separated by semicolons

```
[root@arbiter ~]# pkgin se htop | cat
htop-1.0.1;;Enhanced version of top utility

=: package is installed and up-to-date
<: package is installed but newer version is available
>: installed package has a greater version than available package
```

So, newer versions of `pkgin` it look like use `;;` as a separator when `!isatty(1)`.  AFAIK other operating systems that use `pkgsrc` should experience this issues as well.

---

the solution would be to change this line https://github.com/chef/chef/blob/master/lib/chef/provider/package/smartos.rb#L67

from 

``` ruby
name, version = line.split[0].split(/-([^-]+)$/)
```

to

``` ruby
name, version = line.split(/[; ]/)[0].split(/-([^-]+)$/)
```

This will split the initial string on spaces or semicolons to handle both versions

example

``` ruby
old = 'htop-1.0.1           Enhanced version of top utility'
new = 'htop-1.0.1;;Enhanced version of top utility'

p old.split(/[; ]/)[0].split(/-([^-]+)$/)
# => ["htop", "1.0.1"]

p new.split(/[; ]/)[0].split(/-([^-]+)$/)
# => ["htop", "1.0.1"]
```

**Comment by bahamas10** [comment]
Added implementation based on my above comment (with tests) in https://github.com/chef/chef/pull/3165

**Comment by bixu** [comment]
Still seeing issues with this under chef 12.4.0:
```
Recipe: newrelic::server_monitor_agent
         * smartos_package[nrsysmond] action install

           ================================================================================
           Error executing action `install` on resource 'smartos_package[nrsysmond]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of ["/opt/local/bin/pkgin", "-y", "install", "nrsysmond-2.0.2.111;;New"] ----
           STDOUT: calculating dependencies... done.
       nothing to do.
           STDERR:
           ---- End output of ["/opt/local/bin/pkgin", "-y", "install", "nrsysmond-2.0.2.111;;New"] ----
           Ran ["/opt/local/bin/pkgin", "-y", "install", "nrsysmond-2.0.2.111;;New"] returned 1

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/newrelic/recipes/server_monitor_agent.rb

            14:   package node['newrelic']['server_monitor_agent']['service_name'] do
            15:     action node['newrelic']['server_monitor_agent']['agent_action']
            16:   end
            17:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/newrelic/recipes/server_monitor_agent.rb:14:in `from_file'

           smartos_package("nrsysmond") do
             action :install
             retries 0
             retry_delay 2
             default_guard_interpreter :default
         package_name "nrsysmond"
             version "2.0.2.111;;New"
             declared_type :package
             cookbook_name "newrelic"
             recipe_name "server_monitor_agent"
           end
```

**Comment by hulu1522** [comment]
@bixu What SmartOS image are you using?  It has been working for me just fine.  Here's my latest test env when testing your package install:

```
OS:
 - SmartOS
Image:
 - base-64-lts
 - 14.4.2
 - b67492c2-055c-11e5-85d8-8b039ac981ec
Chef:
 - 12.4.1 (Omnibus installation)
```

I then did a very simple `package 'nrsysmond'` as my recipe. The run was successful:

```
Starting Chef Client, version 12.4.1
[2015-07-17T14:51:05+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
resolving cookbooks for run list: ["test_book::default"]
Synchronizing Cookbooks:
  - test_book
Compiling Cookbooks...
Converging 1 resources
Recipe: test_book::default
  * smartos_package[nrsysmond] action install
    - install version 2.0.2.111 of package nrsysmond

Running handlers:
Running handlers complete
Chef Client finished, 1/1 resources updated in 3.939983855 seconds
Finished converging <test01-smartos> (0m46.19s).
```

**Comment by bixu** [comment]
You are correct.  My issues were caused by lingering monkeypatches that were in place to correct issues that have been fixed in Chef 12+ :)
