### ISSUE TITLE
"Option name must be a kind of String!" regression (?) since 12.1.x with chef_rbenv cookbook

### ISSUE THREAD

**Issue by aried3r** [chef/chef#3115]
In https://github.com/fnichol/chef-rbenv/issues/107 there's been an issue since updating to Chef 12.1.1 (from 12.0.3) and I wondered what exact change made the cookbook throw the exception below, I couldn't quite find it in the [changelog](https://github.com/chef/chef/blob/12-stable/CHANGELOG.md) and wondered if it is a regression, like the ones in #3107.

Config is the same as in https://github.com/fnichol/chef-rbenv/issues/107, once the `gems` section is commented, it works.

The resources declare attributes with ```:kind_of => String```, do they have to explicitly accept `NilClass` as well (which is just a wild guess, since some of the options are nil)?

Any clues on if this is an issue with chef or with the cookbook itself, so I can try to send a PR to either one of the projects.

Ubuntu 14.04.2
Chef 12.1.1
chef_rbenv cookbook

```Shell
================================================================================
Error executing action `install` on resource 'rbenv_gem[2.2.1::bundler] (system)'
================================================================================

Chef::Exceptions::ValidationFailed
----------------------------------
Option name must be a kind of String!  You passed <rbenv_gem[2.2.1::bundler] (system) @name: "bundler" @noop: nil @before: nil @params: {} @provider: Chef::Provider::Package::RbenvRubygems @allowed_actions: [:nothing, :install, :upgrade, :remove, :purge] @action: :install @updated: false @updated_by_last_action: false @supports: {} @ignore_failure: false @retries: 0 @retry_delay: 2 @source_line: "/home/vagrant/chef-solo/cookbooks-2/rbenv/recipes/system.rb:46:in `block (2 levels) in from_file'" @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @sensitive: false @resource_name: :rbenv_gem @declared_type: :rbenv_gem @cookbook_name: :rbenv @recipe_name: "system" @rbenv_version: "2.2.1" @options: "--no-document" @package_name: "bundler" @source: nil @gem_binary: "export RBENV_ROOT=\"/usr/local/rbenv\" && export PATH=\"$RBENV_ROOT/bin:$RBENV_ROOT/shims:$PATH\" && export RBENV_VERSION=\"2.2.1\" && $RBENV_ROOT/shims/gem" @root_path: nil @user: nil @version: "1.8.5" @response_file: nil>.

Cookbook Trace:
---------------
/home/vagrant/chef-solo/cookbooks-2/rbenv/resources/rehash.rb:29:in `initialize'
/home/vagrant/chef-solo/cookbooks-2/rbenv/libraries/chef_provider_package_rbenvrubygems.rb:86:in `new'
/home/vagrant/chef-solo/cookbooks-2/rbenv/libraries/chef_provider_package_rbenvrubygems.rb:86:in `rehash'
/home/vagrant/chef-solo/cookbooks-2/rbenv/libraries/chef_provider_package_rbenvrubygems.rb:67:in `install_package'

Resource Declaration:
---------------------
# In /home/vagrant/chef-solo/cookbooks-2/rbenv/recipes/system.rb

 46:     rbenv_gem gem['name'] do
 47:       rbenv_version rubie
 48:
 49:       %w{version action options source}.each do |attr|
 50:         send(attr, gem[attr]) if gem[attr]
 51:       end
 52:     end
 53:   end

Compiled Resource:
------------------
# Declared in /home/vagrant/chef-solo/cookbooks-2/rbenv/recipes/system.rb:46:in `block (2 levels) in from_file'

rbenv_gem("bundler") do
  provider Chef::Provider::Package::RbenvRubygems
  action :install
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :rbenv_gem
  cookbook_name :rbenv
  recipe_name "system"
  rbenv_version "2.2.1"
  options "--no-document"
  package_name "bundler"
  gem_binary "export RBENV_ROOT=\"/usr/local/rbenv\" && export PATH=\"$RBENV_ROOT/bin:$RBENV_ROOT/shims:$PATH\" && export RBENV_VERSION=\"2.2.1\" && $RBENV_ROOT/shims/gem"
  version "1.8.5"
end
```
and a more easily readable version of the *You passed:* part:
```Ruby
<rbenv_gem[2.2.1::bundler] (system) 
@name: "bundler" 
@noop: nil 
@before: nil 
@params: {} 
@provider: Chef::Provider::Package::RbenvRubygems 
@allowed_actions: [:nothing, :install, :upgrade, :remove, :purge] 
@action: :install 
@updated: false 
@updated_by_last_action: false 
@supports: {} 
@ignore_failure: false 
@retries: 0 
@retry_delay: 2 
@source_line: "/home/vagrant/chef-solo/cookbooks-2/rbenv/recipes/system.rb:46:in `block (2 levels) in from_file'" 
@guard_interpreter: nil 
@default_guard_interpreter: :default 
@elapsed_time: 0 
@sensitive: false 
@resource_name: :rbenv_gem 
@declared_type: :rbenv_gem 
@cookbook_name: :rbenv 
@recipe_name: "system" 
@rbenv_version: "2.2.1" 
@options: "--no-document" 
@package_name: "bundler" 
@source: nil 
@gem_binary: "export RBENV_ROOT=\"/usr/local/rbenv\" && export PATH=\"$RBENV_ROOT/bin:$RBENV_ROOT/shims:$PATH\" && export RBENV_VERSION=\"2.2.1\" && $RBENV_ROOT/shims/gem" 
@root_path: nil 
@user: nil 
@version: "1.8.5" 
@response_file: nil>
```

**Comment by lamont-granquist** [comment]
This was a deliberate breaking change rbenv cookbook needed to be updated.
