### ISSUE TITLE
smartos "CRON" resource failing on special characters and mailto "" 

### ISSUE THREAD

**Issue by joshzitting** [chef/chef#3120]
recipe runs on Ubuntu,
running chef 12.1.1 
Cron resource 
```
cron "insert sensu-client into cron" do
  mailto "''"
  minute '*/3'
  user 'root'
  path "/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
  command "pgrep sensu-client || (service sensu-client restart; echo 'Client-restarted '$(date) >> /var/log/sensu/client-restarts.txt)"
end
```

crontab -(e,u,l,etc) work on the machine but not in the recipe..  if I comment out the "mailto" section it then fails on "path", if I comment "path" out it fails on the "command"... 

Here is the stack trace.. 
```
      Recipe: tcn_monitor::client_install
         * cron[insert sensu-client into cron] action create

           ================================================================================
           Error executing action `create` on resource 'cron[insert sensu-client into cron]'
           ================================================================================

           Chef::Exceptions::Cron
           ----------------------
           Error updating state of insert sensu-client into cron, exit: 1, message: MAILTO=' '
           crontab: error on previous line; unexpected character found in line.
           PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
           crontab: error on previous line; unexpected character found in line.
           */3 * * * * pgrep sensu-client || (service sensu-client restart; echo 'Client-restarted '$(date) >> /var/log/sensu/client-restarts.txt)
           crontab: error on previous line; unexpected character found in line.
           crontab: errors detected in input, no crontab file generated.

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/tcn_monitor/recipes/client_install.rb

            23: cron "insert sensu-client into cron" do
            24:   mailto "' '"
            25:   minute '*/3'
            26:   user 'root'
            27:   path "/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
            28:   command "pgrep sensu-client || (service sensu-client restart; echo 'Client-restarted '$(date) >> /var/log/sensu/client-restarts.txt)"
            29: end
            30:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/tcn_monitor/recipes/client_install.rb:23:in `from_file'

       cron("insert sensu-client into cron") do
             action :create
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             minute "*/3"
         hour "*"
             day "*"
             month "*"
         weekday "*"
             command "pgrep sensu-client || (service sensu-client restart; echo 'Client-restarted '$(date) >> /var/log/sensu/client-restarts.txt)"
             user "root"
         mailto "' '"
         path "/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
         declared_type :cron
             cookbook_name "tcn_monitor"
             recipe_name "client_install"
           end

         * ruby_block[show host info] action create
           - execute the ruby block show host info
       [2015-03-20T22:23:22+00:00] ERROR: Converge failed with error message cron[insert sensu-client into cron] (tcn_monitor::client_install line 23) had an error: Chef::Exceptions::Cron: Error updating state of insert sensu-client into cron, exit: 1, message: MAILTO=' '
       crontab: error on previous line; unexpected character found in line.
       PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
       crontab: error on previous line; unexpected character found in line.
       */3 * * * * pgrep sensu-client || (service sensu-client restart; echo 'Client-restarted '$(date) >> /var/log/sensu/client-restarts.txt)
       crontab: error on previous line; unexpected character found in line.
       crontab: errors detected in input, no crontab file generated.


       Running handlers:
```

**Comment by hulu1522** [comment]
I am also having this issue:
```
Generated at 2015-03-30 20:51:06 +0000
Chef::Exceptions::Cron: cron[JIRA_restart] (tcn_atlassian::jira line 152) had an error: Chef::Exceptions::Cron: Error updating state of JIRA_restart, exit: 1, message: MAILTO=''
crontab: error on previous line; unexpected character found in line.
crontab: errors detected in input, no crontab file generated.

/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/provider/cron/unix.rb:75:in `write_crontab'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/provider/cron.rb:157:in `block in action_create'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/mixin/why_run.rb:52:in `call'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/provider.rb:180:in `converge_by'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/provider/cron.rb:156:in `action_create'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/provider.rb:145:in `run_action'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/resource.rb:561:in `run_action'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/runner.rb:49:in `run_action'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/runner.rb:81:in `each'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/runner.rb:81:in `block in converge'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/runner.rb:80:in `converge'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/client.rb:331:in `block in converge'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/client.rb:326:in `catch'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/client.rb:326:in `converge'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/client.rb:345:in `converge_and_save'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/client.rb:449:in `run'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/application.rb:271:in `block in fork_chef_client'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/application.rb:259:in `fork'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/application.rb:259:in `fork_chef_client'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/application.rb:225:in `block in run_chef_client'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/application.rb:213:in `run_chef_client'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/application/client.rb:392:in `block in interval_run_chef_client'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/application/client.rb:382:in `loop'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/application/client.rb:382:in `interval_run_chef_client'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/application/client.rb:372:in `run_application'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/lib/chef/application.rb:60:in `run'
/opt/local/lib/ruby/gems/2.0.0/gems/chef-12.2.1/bin/chef-client:26:in `<top (required)>'
...skipping...
Generated at 2015-03-30 20:51:06 +0000
```
The only fix was to comment out the `mailto` option.
```ruby
cron "JIRA_restart" do
  case node['platform_family']
  when "smartos"
    command "/usr/sbin/svcadm restart svc:/application/management/jira:default"
  when "debian"
    command "/etc/init.d/jira restart"
  end
  hour    3
  minute  0
  user    "root"
  # mailto  %Q['']
end
```

**Comment by lamont-granquist** [comment]
Solaris crontabs don't support environment variables (MAILTO, PATH, etc) and also don't support the "*/3" kind of syntax.  Both of those are vixie cron extensions which are linux-specific.

Since you're trying to render something into a file that the underlying operation system won't be able to interpret I don't think there's a bug we can fix.
