### ISSUE TITLE
chef-client 12.2.0 fails to start without HOME environment variable

### ISSUE THREAD

**Issue by dgivens** [chef/chef#3153]
Just upgraded my Debian Wheezy systems to 12.2.0 and now get the following when trying to start the chef-client service.

```
[production-dfw] root@api-n01a:~ # service chef-client start
Starting chef-client : chef-client/opt/chef/embedded/apps/chef/lib/chef/util/path_helper.rb:199:in `home': couldn't find HOME environment -- expanding `~' (ArgumentError)
        from /opt/chef/embedded/apps/chef/lib/chef/util/path_helper.rb:199:in `all_homes'
        from /opt/chef/embedded/apps/chef/lib/chef/util/path_helper.rb:161:in `home'
        from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:36:in `gather_plist_dirs'
        from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:40:in `<class:Macosx>'
        from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:27:in `<class:Service>'
        from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:26:in `<class:Provider>'
        from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:25:in `<class:Chef>'
        from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:24:in `<top (required)>'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/apps/chef/lib/chef/providers.rb:93:in `<top (required)>'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/apps/chef/lib/chef.rb:25:in `<top (required)>'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/apps/chef/bin/chef-client:23:in `<top (required)>'
        from /usr/bin/chef-client:51:in `load'
        from /usr/bin/chef-client:51:in `<main>'
^N failed!
````

**Comment by coderanger** [comment]
The specific issue is the use of Dir.home at https://github.com/chef/chef/blob/master/lib/chef/util/path_helper.rb#L199

That should be replaced with:

```ruby
paths << ENV['HOME'] if ENV['HOME']
```
or something similar.

**Comment by jdmundrawala** [comment]
Also, as another bug, why is osx code running under debian

**Comment by coderanger** [comment]
It is run statically at file load time https://github.com/chef/chef/blob/master/lib/chef/provider/service/macosx.rb#L40

**Comment by jdmundrawala** [comment]
right... we probably should not be doing that

**Comment by coderanger** [comment]
Indeed, switch gather_plist_dirs to stay a normal method with some memo-izing. That said, other than this bug it isn't bad to run that code on non-OSX, it will just produce garbage that is never used.
