### ISSUE TITLE
trusted_certs_dir doesn't seem to work if a path is constructed from multiple strings

### ISSUE THREAD

**Issue by vinyar** [chef/chef#3157]
Example of knife.rb

Working:
```ruby
current_dir       = File.dirname(__FILE__)
node_name         'unicorn'
chef_server_url   'https://12.12.13.14/organizations/my_org'
client_key        "#{current_dir}/my_key.pem"
cookbook_path     "#{current_dir}/../local-mode-cache/cache/cookbooks"
trusted_certs_dir "/Users/alexvinyar/Documents/Projects/unicorn/unicorn-cluster_chefconf2015/unicorn-demo/.chef/unicorn-cluster-data/../trusted_certs"
```

If trusted dir is using the current_dir variable to construct an identical string, cert validation fails
Broken
```ruby
...
trusted_certs_dir "#{File.expand_path(current_dir)}/../trusted_certs}"
```

**Comment by vinyar** [comment]
I took a quick look at it with pry and perhaps the error is because `..` are used?

pry from working config:
```ruby
$ k ssl check
WARN: Unresolved specs during Gem::Specification.reset:
      httpclient (>= 2.2.0.2, ~> 2.2)
      gyoku (>= 0.4.0)
      mini_portile (~> 0.6.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
before_session hook failed: Pry::CommandError: Cannot locate this method: allocate. Try `gem-install pry-doc` to get access to Ruby Core documentation.
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/method.rb:489:in `pry_doc_info'
(see _pry_.hooks.errors to debug)
2.1.4 (Chef::Config):0 > trusted_certs_dir
=> "/Users/alexvinyar/Documents/Projects/unicorn/unicorn-cluster_chefconf2015/unicorn-demo/.chef/trusted_certs"
2.1.4 (Chef::Config):0 > exit
before_session hook failed: Pry::CommandError: Cannot locate this method: allocate. Try `gem-install pry-doc` to get access to Ruby Core documentation.
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/method.rb:489:in `pry_doc_info'
(see _pry_.hooks.errors to debug)
2.1.4 (Chef::Config):0 > trusted_certs_dir
=> "/Users/alexvinyar/Documents/Projects/unicorn/unicorn-cluster_chefconf2015/unicorn-demo/.chef/unicorn-cluster-data/../trusted_certs"
2.1.4 (Chef::Config):0 > exit
Connecting to host 10.194.14.127:443
Successfully verified certificates from `10.194.14.127'
```

Broken config
```ruby
$ k ssl check
WARN: Unresolved specs during Gem::Specification.reset:
      httpclient (>= 2.2.0.2, ~> 2.2)
      gyoku (>= 0.4.0)
      mini_portile (~> 0.6.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
before_session hook failed: Pry::CommandError: Cannot locate this method: allocate. Try `gem-install pry-doc` to get access to Ruby Core documentation.
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/method.rb:489:in `pry_doc_info'
(see _pry_.hooks.errors to debug)
2.1.4 (Chef::Config):0 > trusted_certs_dir
=> "/Users/alexvinyar/Documents/Projects/unicorn/unicorn-cluster_chefconf2015/unicorn-demo/.chef/trusted_certs"
2.1.4 (Chef::Config):0 > exit
before_session hook failed: Pry::CommandError: Cannot locate this method: allocate. Try `gem-install pry-doc` to get access to Ruby Core documentation.
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/pry-0.10.1/lib/pry/method.rb:489:in `pry_doc_info'
(see _pry_.hooks.errors to debug)
2.1.4 (Chef::Config):0 > trusted_certs_dir
=> "/Users/alexvinyar/Documents/Projects/unicorn/unicorn-cluster_chefconf2015/unicorn-demo/.chef/unicorn-cluster-data/../trusted_certs}"
2.1.4 (Chef::Config):0 > exit
Connecting to host 10.194.14.127:443
ERROR: The SSL certificate of 10.194.14.127 could not be verified
Certificate issuer data: /C=US/ST=WA/L=Seattle/O=YouCorp/OU=Operations/CN=10.194.14.127/emailAddress=you@example.com

Configuration Info:
...
```

**Comment by lamont-granquist** [comment]
Both trusted_certs_dirs have '..'s in them so that's not it.  The problem looks like a trailing '}' at the very end of the busted trusted_certs_dir:

```
> trusted_certs_dir
=> "/Users/alexvinyar/Documents/Projects/unicorn/unicorn-cluster_chefconf2015/unicorn-demo/.chef/unicorn-cluster-data/../trusted_certs}"
```

**Comment by vinyar** [comment]
The extra bracket is coming from somewhere, probably some sort of string concat..
I hadn't tested this in a while. I'll see if that's still going on, and follow up.

**Comment by vinyar** [comment]
just for the kicks verified it just now, the error seems to have gone away.
