### ISSUE TITLE
Homebrew package upgrade doesn't take revision into account

### ISSUE THREAD

**Issue by simmel** [chef/chef#3215]
When using action :upgrade on a Homebrew formula which has revisions chef Homebrew package resource tries to upgrade the package even though the latest version is installed.

```
$ chef-apply -e 'Chef::Resource::HomebrewPackage.provides :package, os: "darwin"; package "elinks" do action :upgrade end'
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * homebrew_package[elinks] action upgrade
    - upgrade package elinks from uninstalled to 0.11.7
$ chef-apply -e 'Chef::Resource::HomebrewPackage.provides :package, os: "darwin"; package "elinks" do action :upgrade end'
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * homebrew_package[elinks] action upgrade

    ================================================================================
    Error executing action `upgrade` on resource 'homebrew_package[elinks]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of brew upgrade  elinks ----
    STDOUT:
    STDERR: Error: elinks 0.11.7_2 already installed
    ---- End output of brew upgrade  elinks ----
    Ran brew upgrade  elinks returned 1

    Resource Declaration:
    ---------------------
    # In /tmp/recipe-temporary-file20150410-30570-1i2ytjg

      1: Chef::Resource::HomebrewPackage.provides :package, os: "darwin"; package "elinks" do action :upgrade end

    Compiled Resource:
    ------------------
    # Declared in /tmp/recipe-temporary-file20150410-30570-1i2ytjg:1:in `run_chef_recipe'

    homebrew_package("elinks") do
      action [:upgrade]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      package_name "elinks"
      version "0.11.7"
      timeout 900
      declared_type :package
      cookbook_name "(chef-apply cookbook)"
      recipe_name "(chef-apply recipe)"
    end

[2015-04-10T22:38:30+02:00] FATAL: Stacktrace dumped to /Users/simmel/.chef/cache/chef-stacktrace.out
[2015-04-10T22:38:30+02:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: homebrew_package[elinks] ((chef-apply cookbook)::(chef-apply recipe) line 1) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of brew upgrade  elinks ----
STDOUT:
STDERR: Error: elinks 0.11.7_2 already installed
---- End output of brew upgrade  elinks ----
Ran brew upgrade  elinks returned 1
$ cat /Users/simmel/.chef/cache/chef-stacktrace.out
Generated at 2015-04-10 22:38:30 +0200
Mixlib::ShellOut::ShellCommandFailed: homebrew_package[elinks] ((chef-apply cookbook)::(chef-apply recipe) line 1) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of brew upgrade  elinks ----
STDOUT:
STDERR: Error: elinks 0.11.7_2 already installed
---- End output of brew upgrade  elinks ----
Ran brew upgrade  elinks returned 1
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.1/lib/mixlib/shellout.rb:278:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.1/lib/mixlib/shellout.rb:265:in `error!'
/opt/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:56:in `shell_out!'
/opt/chef/embedded/apps/chef/lib/chef/provider/package/homebrew.rb:129:in `get_response_from_command'
/opt/chef/embedded/apps/chef/lib/chef/provider/package/homebrew.rb:76:in `brew'
/opt/chef/embedded/apps/chef/lib/chef/provider/package/homebrew.rb:59:in `upgrade_package'
/opt/chef/embedded/apps/chef/lib/chef/provider/package.rb:114:in `block in action_upgrade'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `call'
/opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:180:in `converge_by'
/opt/chef/embedded/apps/chef/lib/chef/provider/package.rb:113:in `action_upgrade'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:561:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/application/apply.rb:166:in `run_chef_recipe'
/opt/chef/embedded/apps/chef/lib/chef/application/apply.rb:175:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application/apply.rb:188:in `run'
/opt/chef/embedded/apps/chef/bin/chef-apply:25:in `<top (required)>'
/usr/bin/chef-apply:51:in `load'
/usr/bin/chef-apply:51:in `<main>'
$ EDITOR=cat brew edit elinks
require 'formula'

class Elinks < Formula
  homepage 'http://elinks.or.cz/'
  url 'http://elinks.or.cz/download/elinks-0.11.7.tar.bz2'
  sha1 'd13edc1477d0ab32cafe7d3c1f3a23ae1c0a5c54'
  revision 2

  bottle do
    revision 1
    sha1 "97954464d63684d343152aa3dbb7bd5384d8e56d" => :mavericks
    sha1 "882e21d742e1f373b9403ef932bddc855430948e" => :mountain_lion
    sha1 "ce8f6c3521d89ed3c0e3f09813934154ec6b4bcb" => :lion
  end

  devel do
    url 'http://elinks.cz/download/elinks-0.12pre6.tar.bz2'
    version '0.12pre6'
    sha1 '3517795e8a390cb36ca249a5be6514b9784520a5'
  end

  head do
    url 'http://elinks.cz/elinks.git'

    depends_on "autoconf" => :build
    depends_on "automake" => :build
    depends_on "libtool" => :build
  end

  depends_on "openssl"

  def install
    ENV.deparallelize
    ENV.delete('LD')
    system "./autogen.sh" if build.head?
    system "./configure", "--prefix=#{prefix}", "--without-spidermonkey",
                          "--enable-256-colors"
    system "make install"
  end

  test do
    (testpath/"test.html").write <<-EOS.undent
      <!DOCTYPE html>
      <title>elinks test</title>
      Hello world!
      <ol><li>one</li><li>two</li></ol>
    EOS
    assert_match /^\s*Hello world!\n+ *1. one\n *2. two\s*$/,
                 shell_output("elinks test.html")
  end
end
$ brew info --json=v1 elinks | python -mjson.tool
[
    {
        "caveats": null,
        "conflicts_with": [],
        "dependencies": [
            "openssl"
        ],
        "homepage": "http://elinks.or.cz/",
        "installed": [
            {
                "built_as_bottle": null,
                "poured_from_bottle": true,
                "used_options": [],
                "version": "0.11.7_2"
            }
        ],
        "keg_only": null,
        "linked_keg": "0.11.7_2",
        "name": "elinks",
        "options": [],
        "revision": 2,
        "versions": {
            "bottle": true,
            "devel": "0.12pre6",
            "head": "HEAD",
            "stable": "0.11.7"
        }
    }
]
```

Note that the formula version is 0.11.7 but the actual installed version is 0.11.7_2.

I can do the change, but I want to discuss the best solution. One is to use `candidate_version` instead of `current_resource.version` here https://github.com/chef/chef/blob/3ac9ac602f837a1a38d320f453fa50488f670f60/lib/chef/provider/package/homebrew.rb#L54

Thoughts?

**Comment by lamont-granquist** [comment]
I would expect to see an idempotency check between candidate_version (what we think we should install after resolving the new_resource.version that the user requested -- which should be 0.11.7_2) and current_resource.version (which should be what is installed -- 0.11.7_2)

**Comment by lavahot** [comment]
I'm running into this too. Anybody have a workaround for this issue?
