### ISSUE TITLE
Cannot save node to server: cannot encode to UTF-8

### ISSUE THREAD

**Issue by theWeird** [chef/chef#3216]
Applyment of the recipes on my new debian wheezy client works great. But the call of chef-client ends up with this output:

```
Running handlers:
[2015-04-13T11:50:47+02:00] ERROR: Running exception handlers
Running handlers complete
[2015-04-13T11:50:47+02:00] ERROR: Exception handlers complete
[2015-04-13T11:50:47+02:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 1.142610037 seconds
[2015-04-13T11:50:47+02:00] ERROR: Invalid UTF-8 string: cannot encode to UTF-8
[2015-04-13T11:50:47+02:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Stack trace tells me:
```
# cat /var/chef/cache/chef-stacktrace.out
Generated at 2015-04-13 11:50:47 +0200
Chef::Exceptions::JSON::EncodeError: Invalid UTF-8 string: cannot encode to UTF-8
/opt/chef/embedded/apps/chef/lib/chef/json_compat.rb:107:in `rescue in to_json'
/opt/chef/embedded/apps/chef/lib/chef/json_compat.rb:104:in `to_json'
/opt/chef/embedded/apps/chef/lib/chef/http/json_input.rb:35:in `handle_request'
/opt/chef/embedded/apps/chef/lib/chef/http.rb:221:in `block in apply_request_middleware'
/opt/chef/embedded/apps/chef/lib/chef/http.rb:219:in `each'
/opt/chef/embedded/apps/chef/lib/chef/http.rb:219:in `inject'
/opt/chef/embedded/apps/chef/lib/chef/http.rb:219:in `apply_request_middleware'
/opt/chef/embedded/apps/chef/lib/chef/http.rb:140:in `request'
/opt/chef/embedded/apps/chef/lib/chef/http.rb:117:in `put'
/opt/chef/embedded/apps/chef/lib/chef/node.rb:515:in `save'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:270:in `save_updated_node'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:348:in `converge_and_save'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:449:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:372:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:51:in `load'
/usr/bin/chef-client:51:in `<main>'
```

I isolated the problem to occour during write-back of the node to the server. It also occours if I try to save the node from chef-shell:
```
# chef-shell
loading configuration: none (standalone session)
Session type: standalone
Loading..done.

This is the chef-shell.
 Chef Version: 12.2.1
 http://www.chef.io/
 http://docs.chef.io/

run `help' for help, `exit' or ^D to quit.

Ohai2u root@my.host.de!
chef > node.save
Chef::Exceptions::JSON::EncodeError: Invalid UTF-8 string: cannot encode to UTF-8
        from /opt/chef/embedded/apps/chef/lib/chef/json_compat.rb:107:in `rescue in to_json'
        from /opt/chef/embedded/apps/chef/lib/chef/json_compat.rb:104:in `to_json'
        from /opt/chef/embedded/apps/chef/lib/chef/http/json_input.rb:35:in `handle_request'
        from /opt/chef/embedded/apps/chef/lib/chef/http.rb:221:in `block in apply_request_middleware'
        from /opt/chef/embedded/apps/chef/lib/chef/http.rb:219:in `each'
        from /opt/chef/embedded/apps/chef/lib/chef/http.rb:219:in `inject'
        from /opt/chef/embedded/apps/chef/lib/chef/http.rb:219:in `apply_request_middleware'
        from /opt/chef/embedded/apps/chef/lib/chef/http.rb:140:in `request'
        from /opt/chef/embedded/apps/chef/lib/chef/http.rb:117:in `put'
        from /opt/chef/embedded/apps/chef/lib/chef/node.rb:515:in `save'
        from (irb):1
        from /opt/chef/embedded/apps/chef/lib/chef/shell.rb:76:in `block in start'
        from /opt/chef/embedded/apps/chef/lib/chef/shell.rb:75:in `catch'
        from /opt/chef/embedded/apps/chef/lib/chef/shell.rb:75:in `start'
        from /opt/chef/embedded/apps/chef/bin/chef-shell:37:in `<top (required)>'
        from /usr/bin/chef-shell:51:in `load'
        from /usr/bin/chef-shell:51:in `<main>'
```

**Comment by rmoriz** [comment]
(just my 2cts as chef user:)

- Any ISO 8859-1 chars in `ohai` output?
- Might be related to https://github.com/chef/ohai/issues/496 and https://github.com/chef/ohai/issues/503
- I suggest to run ohai on the shell and pipe the stdout to a file - then scanning for invalid characters.

**Comment by theWeird** [comment]
I ran ohai from shell as root and got another error.
So it seems it really is an ohai problem.

```
# ohai 
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:50:in `raise_error_for_status': Invalid UTF-8 string: cannot encode to UTF-8 (FFI_Yajl::EncodeError)
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `do_yajl_encode'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.4.0/lib/ffi_yajl/encoder.rb:21:in `encode'
	from /opt/chef/embedded/apps/ohai/lib/ohai/system.rb:181:in `json_pretty_print'
	from /opt/chef/embedded/apps/ohai/lib/ohai/application.rb:97:in `run_application'
	from /opt/chef/embedded/apps/ohai/lib/ohai/application.rb:70:in `run'
	from /opt/chef/embedded/apps/ohai/bin/ohai:42:in `<top (required)>'
	from /usr/bin/ohai:22:in `load'
	from /usr/bin/ohai:22:in `<main>'
```

BTW: the machine with this error is run as openVZ container.

**Comment by daxroc** [comment]
Getting a similar issue when bootstrapping

OS: RHEL 6.5
Platform: vsphere
Chef: 12.2.1

Issue:  Bootstrap fails with
Creating new client for testsrv
Creating new node for testsrv
Connecting to 192.1.1.1
ERROR: ArgumentError: invalid byte sequence in UTF-8

No noticeable errors/ characters with ohai as root

#locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by lamont-granquist** [comment]
These are all ohai bugs, and the only thing to do is track down the non-UTF8 illegal character in the ohai data.

**Comment by mijarck** [comment]
We have 11 GB DB and wanted to upgrade from Gitlab CE 7.5.3 to Gitlab CE 7.10.1, but stuck because of this ohai problem. Is there some more instructions how to get through this problem? Will check ohai revision history next, if it would be possible to update ohai to get DB migrated and up and running again.

**Comment by johnc10uk** [comment]
Seeing same on EC2 instance after gitlab 7.10.1 upgrade, gitlab-ctl reconfigure is successful except outputs UTF-8 error right at the end.  Ohai  7.4.1, EC2 instance user data api returns a zipped file (i.e. binary) which ohai tries to convert to UTF-8 and print. Temp fix -

CHANGE: ec2[:userdata] = self.fetch_userdata 
TO: ec2[:userdata] = nil

in /opt/gitlab/embedded/lib/ruby/gems/2.1.0/gems/ohai-7.4.1/lib/ohai/plugins/ec2.rb

**Comment by lamont-granquist** [comment]
#3320 has fixed this.  It'll go out with chef 12.4.0, it'll be up to gitlab to get that out in one of their builds.

**Comment by maxlazio** [comment]
@johnc10uk Our latest 7.10 packages have the EC2 plugin disabled. 

@lamont-granquist Thanks for the fix, we will work on this as soon as possible.
