### ISSUE TITLE
Control recipes fail on Windows with 'no implicit conversion of Symbol into Integer'

### ISSUE THREAD

**Issue by smford22** [chef/chef#3234]
### Version:
```
~/chef-repo/cookbooks/tk-windows (fords-chefaws)
scottford$ chef -v
Chef Development Kit Version: 0.5.0.rc.3
chef-client version: 12.2.1
berks version: 3.2.3
kitchen version: 1.4.0.rc.1
```

### Environment: [Details about the environment such as the Operating System, cookbook details, etc...]
```
    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro11,1
      Processor Name: Intel Core i7
      Processor Speed: 2.8 GHz
      Number of Processors: 1
      Total Number of Cores: 2
      L2 Cache (per Core): 256 KB
      L3 Cache: 4 MB
      Memory: 16 GB
      Boot ROM Version: MBP111.0138.B03
      SMC Version (system): 2.16f58
```

```
Software:

    System Software Overview:

      System Version: OS X 10.9.5 (13F34)
      Kernel Version: Darwin 13.4.0
      Time since boot: 2:22
```

### Scenario:
Regardless of the control supplied, audits in Windows are failing with `no implicit conversion of Symbol into Integer` 

### Steps to reproducce:
Create a cookbook
`chef generate cookbook tk-windows`  
`$ cd tk-windows`

Create a .kitchen.yml with audit_mode enabled
```
scottford$ cat .kitchen.yml
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :audit_only

platforms:
  - name: win2012r2
    driver:
      box: win2012r2
      box_url:  https://s3-us-west-1.amazonaws.com/scottford.io/win2012r2-datacenter-nocm-1.0.2.box
      customize:
        memory: 2048
        cpus: 2

suites:
  - name: default
    run_list:
      - recipe[tk-windows::audit_windows]
    attributes:
```

Create a basic control recipe in `recipes/audit_windows.rb`
```
scottford$ cat recipes/audit_windows.rb
control_group 'Windows Services' do
  control 'DHCP Audits' do
    it "DHCP Client" do
      expect(service("DHCP Client")).to be_installed
    end
  end
end
```

Converge the test
```
scottford$ kitchen converge default-win2012r2
-----> Starting Kitchen (v1.4.0.rc.1)
-----> Converging <default-win2012r2>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 3.2.3...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <default-win2012r2>
       [2015-04-16T15:57:02-07:00] WARN: Chef-client has been configured to skip converge and only audit. Audit mode is an experimental feature currently under development. API changes may occur. Use at your own risk.
       * To enable audit mode after converge, use command line option `--audit-mode enabled` or set `:audit_mode = :enabled` in your config file.
       * To disable audit mode, use command line option `--audit-mode disabled` or set `:audit_mode = :disabled` in your config file.
       * To only run audit mode, use command line option `--audit-mode audit-only` or set `:audit_mode = :audit_only` in your config file.
       Audit mode is disabled by default.
       Starting Chef Client, version 12.2.1
       [2015-04-16T15:57:13-07:00] WARN: Child with name 'dna.json' found in multiple directories: C:/Users/vagrant/AppData/Local/Temp/kitchen/dna.json and C:/Users/vagrant/AppData/Local/Temp/kitchen/dna.json
       resolving cookbooks for run list: ["tk-windows::audit_windows"]
       Synchronizing Cookbooks:
         - tk-windows
       Compiling Cookbooks...
       Starting audit phase
       Windows Services
         DHCP Audits
           DHCP Client (FAILED - 1)

       Failures:

         1) Windows Services DHCP Audits DHCP Client
            Failure/Error: expect(service("DHCP Client")).to be_installed
            TypeError:
       no implicit conversion of Symbol into Integer
            # C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/tk-windows/recipes/audit_windows.rb:4:in `block (3 levels) in from_file'

       Finished in 11.72 seconds (files took 0.62499 seconds to load)
       1 example, 1 failure

       Failed examples:

       rspec  # Windows Services DHCP Audits DHCP Client
       [2015-04-16T15:57:26-07:00] ERROR: Audit phase failed with error message: Audit phase found failures - 1/1 controls failed

       Audit phase exception:
         Audit phase found failures - 1/1 controls failed
         C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:365:in `run_audits'
         C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:456:in `run'
         C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:253:in `run_with_graceful_exit_option'
         C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:230:in `block in run_chef_client'
         C:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
         C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
         C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `block in interval_run_chef_client'
         C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `loop'
         C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `interval_run_chef_client'
         C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:372:in `run_application'
         C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
         C:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
         C:/opscode/chef/bin/chef-client:63:in `load'
         C:/opscode/chef/bin/chef-client:63:in `<main>'

         Running handlers:
       [2015-04-16T15:57:26-07:00] ERROR: Running exception handlers
         Running handlers complete
       [2015-04-16T15:57:26-07:00] ERROR: Exception handlers complete
       [2015-04-16T15:57:26-07:00] FATAL: Stacktrace dumped to C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
         Chef Client failed. 0 resources updated in 23.857864 seconds
           0 controls succeeded
       [2015-04-16T15:57:26-07:00] FATAL: Chef::Exceptions::RunFailedWrappingError: Found 1 errors, they are stored in the backtrace
>>>>>> Converge failed on instance <default-win2012r2>.
>>>>>> Please see .kitchen/logs/default-win2012r2.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: WinRM exited (1) for command: [
$env:PATH = [System.Environment]::GetEnvironmentVariable("PATH","Machine")

& $env:systemdrive\opscode\chef\bin\chef-client.bat --local-mode --config $env:TEMP\kitchen\client.rb --log_level auto --force-formatter --no-color --json-attributes $env:TEMP\kitchen\dna.json --chef-zero-port 8889]
```

### Expected Result
Since 'DHCP Client' is installed, the test should pass

### Actual Result 
Test fails with:

```1) Windows Services DHCP Audits DHCP Client
            Failure/Error: expect(service("DHCP Client")).to be_installed
            TypeError:
       no implicit conversion of Symbol into Integer
```

This failure happens regardless of the test

**Comment by juliandunn** [comment]
By turning off RSpec's [backtrace_exclusion_patterns](https://github.com/chef/chef/blob/master/lib/chef/audit/runner.rb#L107) (i.e. setting it to `[]`) I was able to get a bigger stacktrace that could help narrow down where the bug is:

```
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/specinfra-2.27.0/lib/specinfra/command_factory.rb:26:in `[]'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/specinfra-2.27.0/lib/specinfra/command_factory.rb:26:in `create_command_class'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/specinfra-2.27.0/lib/specinfra/command_factory.rb:16:in `get'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/specinfra-2.27.0/lib/specinfra/runner.rb:26:in `run'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/specinfra-2.27.0/lib/specinfra/runner.rb:13:in `method_missing'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/serverspec-2.13.0/lib/serverspec/type/service.rb:7:in `enabled?'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/serverspec-2.13.0/lib/serverspec/matcher/be_enabled.rb:4:in `block (2 levels) in <top (required)>'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-expectations-3.2.0/lib/rspec/matchers/dsl.rb:61:in `block in match'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-expectations-3.2.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-expectations-3.2.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-expectations-3.2.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-expectations-3.2.0/lib/rspec/expectations/expectation_target.rb:54:in `to'
            # C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/winsecurity/recipes/default.rb:41:in `block (3 levels) in from_file'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.2.2/lib/rspec/core/example.rb:177:in `instance_exec'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.2.2/lib/rspec/core/example.rb:177:in `block in run'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.2.2/lib/rspec/core/example.rb:385:in `block in with_around_and_singleton_context_hooks'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.2.2/lib/rspec/core/example.rb:343:in `block in with_around_example_hooks'
       core-3.2.2/lib/rspec/core/hooks.rb:474:in `block in run'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.2.2/lib/rspec/core/hooks.rb:612:in `run_around_example_hooks_for'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.2.2/lib/rspec/core/hooks.rb:474:in `run'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.2.2/lib/rspec/core/example.rb:343:in `with_around_example_hooks'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.2.2/lib/rspec/core/example.rb:385:in `with_around_and_singleton_context_hooks'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.2.2/lib/rspec/core/example.rb:174:in `run'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.2.2/lib/rspec/core/example_group.rb:548:in `block in run_examples'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.2.2/lib/rspec/core/example_group.rb:544:in `map'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.2.2/lib/rspec/core/example_group.rb:544:in `run_examples'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.2.2/lib/rspec/core/example_group.rb:512:in `run'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.2.2/lib/rspec/core/example_group.rb:513:in `block in run'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.2.2/lib/rspec/core/example_group.rb:513:in `map'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.2.2/lib/rspec/core/example_group.rb:513:in `run'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:110:in `block (3 levels) in run_specs'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:110:in `map'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:110:in `block (2 levels) in run_specs'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.2.2/lib/rspec/core/configuration.rb:1526:in `with_suite_hooks'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:109:in `block in run_specs'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.2.2/lib/rspec/core/reporter.rb:62:in `report'
            # C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/rspec-core-3.2.2/lib/rspec/core/runner.rb:108:in `run_specs'
            # C:/opscode/chef/embedded/apps/chef/lib/chef/audit/runner.rb:186:in `do_run'
            # C:/opscode/chef/embedded/apps/chef/lib/chef/audit/runner.rb:33:in `run'
            # C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:363:in `run_audits'
            # C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:456:in `run'
            # C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:253:in `run_with_graceful_exit_option'
            # C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:230:in `block in run_chef_client'
            # C:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
            # C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
            # C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `block in interval_run_chef_client'
            # C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `loop'
            # C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `interval_run_chef_client'
            # C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:372:in `run_application'
            # C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
            # C:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
            # C:/opscode/chef/bin/chef-client:63:in `load'
            # C:/opscode/chef/bin/chef-client:63:in `<main>'
```
