### ISSUE TITLE
ps_credential doesn't work when run from winrm transport

### ISSUE THREAD

**Issue by adamedx** [chef/chef#3246]
I ran this fragment via knife winrm, and it failed (see stack below). When I logged in interactively over RDP and then ran `chef-client`, it worked fine. Seems to be an issue with `ps_credential`:

```
adameddevz.cloudapp.net [2015-04-20T15:47:38+00:00] INFO: Processing dsc_resource[Create Test User] action run (dsc_resource_try::default line 43)
adameddevz.cloudapp.net 
adameddevz.cloudapp.net ================================================================================
adameddevz.cloudapp.net Error executing action `run` on resource 'dsc_resource[Create Test User]'
adameddevz.cloudapp.net ================================================================================
adameddevz.cloudapp.net 
adameddevz.cloudapp.net Chef::Exceptions::Win32APIError
adameddevz.cloudapp.net -------------------------------
adameddevz.cloudapp.net Access is denied.
adameddevz.cloudapp.net ---- Begin Win32 API output ----
adameddevz.cloudapp.net System Error Code: 5
adameddevz.cloudapp.net System Error Message: Access is denied.
adameddevz.cloudapp.net ---- End Win32 API output ----
adameddevz.cloudapp.net 
adameddevz.cloudapp.net Resource Declaration:
adameddevz.cloudapp.net ---------------------
adameddevz.cloudapp.net # In C:/chef/cache/cookbooks/dsc_resource_try/recipes/default.rb
adameddevz.cloudapp.net 
adameddevz.cloudapp.net  43: dsc_resource 'Create Test User' do
adameddevz.cloudapp.net  44:   resource :user
adameddevz.cloudapp.net  45:   property :username, 'testuser1'
adameddevz.cloudapp.net  46:   property :password, ps_credential('xxxxxx')
adameddevz.cloudapp.net  47:   property :ensure, 'Present'
adameddevz.cloudapp.net  48: end
adameddevz.cloudapp.net  49: 
adameddevz.cloudapp.net 
adameddevz.cloudapp.net Compiled Resource:
adameddevz.cloudapp.net ------------------
adameddevz.cloudapp.net # Declared in C:/chef/cache/cookbooks/dsc_resource_try/recipes/default.rb:43:in `from_file'
adameddevz.cloudapp.net 
adameddevz.cloudapp.net dsc_resource("Create Test User") do
adameddevz.cloudapp.net   action :run
adameddevz.cloudapp.net   retries 0
adameddevz.cloudapp.net   retry_delay 2
adameddevz.cloudapp.net   default_guard_interpreter :default
adameddevz.cloudapp.net   properties {:username=>"testuser1", :password=>#<Chef::Util::Powershell::PSCredential:0x113c8e0 @username="placeholder", @password="xxxxxxx">, :ensure=>"Present"}
adameddevz.cloudapp.net   resource :user
adameddevz.cloudapp.net   declared_type :dsc_resource
adameddevz.cloudapp.net   cookbook_name "dsc_resource_try"
adameddevz.cloudapp.net   recipe_name "default"
adameddevz.cloudapp.net end
adameddevz.cloudapp.net
```

Here's the stack:

```
C:/opscode/chef/embedded/apps/chef/lib/chef/win32/error.rb:69:in `raise!'                                                   
C:/opscode/chef/embedded/apps/chef/lib/chef/win32/crypto.rb:33:in `encrypt'                                                 
C:/opscode/chef/embedded/apps/chef/lib/chef/util/powershell/ps_credential.rb:35:in `encrypt'                                
C:/opscode/chef/embedded/apps/chef/lib/chef/util/powershell/ps_credential.rb:29:in `to_psobject'                            
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/powershell_type_coercions.rb:41:in `translate_type'                       
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/powershell_type_coercions.rb:51:in `block in translate_hash'              
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/powershell_type_coercions.rb:50:in `each'                                 
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/powershell_type_coercions.rb:50:in `inject'                               
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/powershell_type_coercions.rb:50:in `translate_hash'                       
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/powershell_type_coercions.rb:30:in `block in type_coercions'              
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/powershell_type_coercions.rb:39:in `call'                                 
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/powershell_type_coercions.rb:39:in `translate_type'                       
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/dsc_resource.rb:133:in `invoke_resource'                               
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/dsc_resource.rb:119:in `test_resource'                                 
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/dsc_resource.rb:38:in `action_run'                                     
C:/opscode/chef/embedded/apps/chef/lib/chef/provider.rb:145:in `run_action'                                                 
C:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:561:in `run_action'                                                 
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'                                                    
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'                                  
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'                                                          
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'                                             
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'     
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'                          
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'           
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'                           
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'                       
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'                
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'              
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'                                                      
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:331:in `block in converge'                                            
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:326:in `catch'                                                        
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:326:in `converge'                                                     
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:345:in `converge_and_save'                                            
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:449:in `run'                                                          
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:253:in `run_with_graceful_exit_option'                           
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:230:in `block in run_chef_client'                                
C:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'                                  
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'                                         
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `block in interval_run_chef_client'                
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `loop'                                             
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `interval_run_chef_client'                         
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:372:in `run_application'                                  
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'                                                      
C:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'                                                 
C:/opscode/chef/bin/chef-client:63:in `load'                                                                                
C:/opscode/chef/bin/chef-client:63:in `<main>'
```

**Comment by adamedx** [comment]
@jdmundrawala have you seen this? Might be an easy repro with test kitchen.

**Comment by jdmundrawala** [comment]
I have not seen this before, but I also have not run this in test-kitchen (because updating powershell). Can you run ConvertTo-SecureString when you remote in?

**Comment by jdmundrawala** [comment]
https://social.technet.microsoft.com/Forums/windowsserver/en-US/5dac39ca-9e44-4594-8637-feb78fada120/data-protection-in-pssession-access-is-denied?forum=winserverpowershell

**Comment by jdmundrawala** [comment]
Going to try to repro with test-kitchen

**Comment by jdmundrawala** [comment]
couldn't repro in test kitchen

**Comment by gadgetmg** [comment]
I get this in test kitchen when trying to converge a dsc_resource with a ps_credential in it. For example, I'm trying to create a domain with the xADDomain resource and I'm getting the Win32APIError back.

Here's a recipe I'm trying to run. The box is running 2012 R2 with the February WMF5 preview installed and my cookbook depends on the powershell cookbook:

```ruby
# Disable LCM Refresh
powershell_script 'disable RefreshMode' do
  code <<-EOH
    [DscLocalConfigurationManager()]
    Configuration LCMSettings {
      Node localhost {
        Settings {
          RefreshMode = "Disabled"
        }
      }
    }
    LCMSettings
    Set-DscLocalConfigurationManager -Path ./LCMSettings -Verbose
EOH
  not_if '(Get-DscLocalConfigurationManager).RefreshMode -eq "Disabled"'
end

# Install the xActiveDirectory module
powershell_module 'xActiveDirectory' do
  package_name 'xActiveDirectory'
  source 'https://gallery.technet.microsoft.com/scriptcenter/xActiveDirectory-f2d573f3/file/131340/2/xActiveDirectory_2.3.zip'
end

dsc_resource 'AD-Domain-Services' do
  resource :WindowsFeature
  property :name, 'AD-Domain-Services'
  property :ensure, 'Present'
end

dsc_resource 'create domain' do
  resource :xADDomain
  property :DomainName, 'example.com'
  property :DomainAdministratorCredential, ps_credential('Administrator', 'P@ssw0rd')
  property :SafemodeAdministratorPassword, ps_credential('P@ssw0rd')
end
```

**Comment by adamedx** [comment]
Are you running over WinRM? If you run it without WinRM, does it succeed?



-Adam



*From:* Matt Graham [mailto:notifications@github.com]
*Sent:* Thursday, April 30, 2015 11:29 AM
*To:* chef/chef
*Cc:* Adam Edwards
*Subject:* Re: [chef] ps_credential doesn't work when run from winrm
transport (#3246)



I get this in test kitchen when trying to converge a dsc_resource with a
ps_credential in it. For example, I'm trying to create a domain with the
xADDomain resource and I'm getting the Win32APIError back.

Here's a recipe I'm trying to run. The box is running 2012 R2 with the
February WMF5 preview installed and my cookbook depends on the powershell
cookbook:

# Disable LCM Refresh

powershell_script 'disable RefreshMode' do

  code <<-EOH

    [DscLocalConfigurationManager()]

    Configuration LCMSettings {

      Node localhost {

        Settings {

          RefreshMode = "Disabled"

        }

      }

    }

    LCMSettings

    Set-DscLocalConfigurationManager -Path ./LCMSettings -Verbose

EOH

  not_if '(Get-DscLocalConfigurationManager).RefreshMode -eq "Disabled"'

end



# Install the xActiveDirectory module

powershell_module 'xActiveDirectory' do

  package_name 'xActiveDirectory'

  source 'https://gallery.technet.microsoft.com/scriptcenter/xActiveDirectory-f2d573f3/file/131340/2/xActiveDirectory_2.3.zip'

end



dsc_resource 'AD-Domain-Services' do

  resource :WindowsFeature

  property :name, 'AD-Domain-Services'

  property :ensure, 'Present'

end



dsc_resource 'create domain' do

  resource :xADDomain

  property :DomainName, 'example.com'

  property :DomainAdministratorCredential,
ps_credential('Administrator', 'P@ssw0rd')

  property :SafemodeAdministratorPassword, ps_credential('P@ssw0rd')

end

—
Reply to this email directly or view it on GitHub
<https://github.com/chef/chef/issues/3246#issuecomment-97909352>.
