### ISSUE TITLE
Enabling a service a second time results in a fatal error on Mac OS X

### ISSUE THREAD

**Issue by glevine** [chef/chef#3285]
I have the following recipe for installing Elasticsearch on my OS X dev machine using Homebrew:

```
package 'elasticsearch'

link "#{ENV['HOME']}/Library/LaunchAgents/homebrew.mxcl.elasticsearch.plist" do
  to '/usr/local/opt/elasticsearch/homebrew.mxcl.elasticsearch.plist'
end

service 'homebrew.mxcl.elasticsearch' do
  action :enable
  supports :enable => true, :disable => true, :start => true, :stop => true, :restart => true
end
```

If `homebrew.mxcl.elasticsearch` has not been loaded, then everything will work fine. This is typical on the first install. However, if I run the cookbook with this recipe a second time, then I get the following error:

```
Running handlers:
[2015-04-26T02:44:26-04:00] ERROR: Running exception handlers
Running handlers complete
[2015-04-26T02:44:26-04:00] ERROR: Exception handlers complete
[2015-04-26T02:44:26-04:00] FATAL: Stacktrace dumped to /Users/glevine/.chef/local-mode-cache/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 2.307148 seconds
[2015-04-26T02:44:26-04:00] ERROR: service[homebrew.mxcl.elasticsearch] (elasticsearch::default line 11) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of launchctl list ----
STDOUT:
STDERR: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.1/lib/mixlib/shellout/unix.rb:131:in `egid=': Operation not permitted (Errno::EPERM)
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.1/lib/mixlib/shellout/unix.rb:131:in `set_group'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.1/lib/mixlib/shellout/unix.rb:298:in `block in fork_subprocess'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.1/lib/mixlib/shellout/unix.rb:284:in `fork'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.1/lib/mixlib/shellout/unix.rb:284:in `fork_subprocess'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.1/lib/mixlib/shellout/unix.rb:52:in `run_command'
    from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.1/lib/mixlib/shellout.rb:248:in `run_command'
    from /opt/chefdk/embedded/apps/chef/lib/chef/mixin/shell_out.rb:91:in `shell_out_command'
    from /opt/chefdk/embedded/apps/chef/lib/chef/mixin/shell_out.rb:44:in `shell_out'
    from /opt/chefdk/embedded/apps/chef/lib/chef/mixin/shell_out.rb:49:in `shell_out!'
    from /opt/chefdk/embedded/apps/chef/lib/chef/provider/service/macosx.rb:161:in `set_service_status'
    from /opt/chefdk/embedded/apps/chef/lib/chef/provider/service/macosx.rb:49:in `load_current_resource'
    from /opt/chefdk/embedded/apps/chef/lib/chef/provider.rb:128:in `run_action'
    from /opt/chefdk/embedded/apps/chef/lib/chef/resource.rb:582:in `run_action'
    from /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
    from /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
    from /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
    from /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
    from /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
    from /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
    from /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
    from /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
    from /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
    from /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
    from /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
    from /opt/chefdk/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
    from /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
    from /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:315:in `converge'
    from /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:400:in `block in run'
    from /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:399:in `catch'
    from /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:399:in `run'
    from /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:261:in `block in fork_chef_client'
    from /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:249:in `fork'
    from /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:249:in `fork_chef_client'
    from /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:215:in `block in run_chef_client'
    from /opt/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
    from /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:201:in `run_chef_client'
    from /opt/chefdk/embedded/apps/chef/lib/chef/application/client.rb:355:in `block in interval_run_chef_client'
    from /opt/chefdk/embedded/apps/chef/lib/chef/application/client.rb:345:in `loop'
    from /opt/chefdk/embedded/apps/chef/lib/chef/application/client.rb:345:in `interval_run_chef_client'
    from /opt/chefdk/embedded/apps/chef/lib/chef/application/client.rb:335:in `run_application'
    from /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:58:in `run'
    from /opt/chefdk/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
    from /usr/bin/chef-client:40:in `load'
    from /usr/bin/chef-client:40:in `<main>'
---- End output of launchctl list ----
Ran launchctl list returned 1
[2015-04-26T02:44:26-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by glevine** [comment]
This turns out to also be true if I were to simply stop the service immediately after enabling it in the same recipe.

```
service 'homebrew.mxcl.elasticsearch' do
  action :enable
end

service 'homebrew.mxcl.elasticsearch' do
  action :stop # could be any action
end
```

**Comment by tas50** [comment]
This isn't an issue we've seen reported again since this initial report. I'm going to close this one out now. If someone runs into the same issue with Chef Infra Client 17+ please feel free to open a new issue.
