### ISSUE TITLE
12.3.0 --minimal-ohai a bit to minimal? command.ps attribute missing

### ISSUE THREAD

**Issue by erichelgeson** [chef/chef#3304]
I have a "standalone" service (no init script) and when i run a chef-recipe with this and minimal ohai (works fine in 12.2.1 and 12.3.0 without --minimal-ohai)

```
service "app_httpd" do
  provider Chef::Provider::Service::Simple
  restart_command "/data/apps/httpd/bin/apachectl -k graceful"
  supports restart: true, reload: false, status: false, start: true, stop: false
  action :nothing
end
```
```
service[app_httpd] could not determine how to inspect the process table, please set this node's 'command.ps' attribute
```

```
==> default: * service[app_httpd] action restart
==> default: 
==> default:     
==> default:     ================================================================================
==> default:     Error executing action `restart` on resource 'service[app_httpd]'
==> default:     ================================================================================
==> default:     
==> default:     TypeError
==> default:     ---------
==> default:     no implicit conversion from nil to integer
==> default:     
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /tmp/vagrant-chef/45bf471f21f79174541f3de893ab55e4/cookbooks/app/recipes/default.rb
==> default:     
==> default:      15: service "app_httpd" do
==> default:      16:   provider Chef::Provider::Service::Simple
==> default:      17:   restart_command "/data/apps/httpd/bin/apachectl -k graceful"
==> default:      18:   supports restart: true, reload: false, status: false, start: true, stop: false
==> default:      19:   action :nothing
==> default:      20: end
==> default:     
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /tmp/vagrant-chef/45bf471f21f79174541f3de893ab55e4/cookbooks/app/recipes/default.rb:15:in `from_file'
==> default:     
==> default:     service("app_httpd") do
==> default:       provider Chef::Provider::Service::Simple
==> default:       action [:nothing]
==> default:       supports {:restart=>true, :reload=>false, :status=>false, :start=>true, :stop=>false}
==> default:       retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :default
==> default:       service_name "app_httpd"
==> default:       pattern "app_httpd"
==> default:       restart_command "/data/apps/httpd/bin/apachectl -k graceful"
==> default:       declared_type :service
==> default:       cookbook_name :app
==> default:       recipe_name "default"
==> default:     end
==> default:     
```

**Comment by ranjib** [comment]
can you share the stack trace. also, im not sure if this will be considered as bug, i'll expect more things to break in minimal ohai mode , unless they were written to work with minimal ohai mode (i.e. they use atttributes other than the ones defined by minimal ohai), but if the attribute is  used by lot of chef core resources, we should definitely rethink about it. in this case its process table, and i generally it holds lot of data :-/ .

**Comment by erichelgeson** [comment]
```
Generated at 2015-04-30 14:15:19 +0000
TypeError: service[app_httpd] (app::default line 15) had an error: TypeError: no implicit conversion from nil to integer
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.1/lib/mixlib/shellout/unix.rb:337:in `kill'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.1/lib/mixlib/shellout/unix.rb:337:in `reap_errant_child'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.1/lib/mixlib/shellout/unix.rb:97:in `ensure in run_command'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.1/lib/mixlib/shellout/unix.rb:105:in `run_command'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.1/lib/mixlib/shellout.rb:248:in `run_command'
/opt/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:97:in `shell_out_command'
/opt/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:50:in `shell_out'
/opt/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:55:in `shell_out!'
/opt/chef/embedded/apps/chef/lib/chef/provider/service/simple.rb:150:in `determine_current_status!'
/opt/chef/embedded/apps/chef/lib/chef/provider/service/simple.rb:39:in `load_current_resource'
/opt/chef/embedded/apps/chef/lib/chef/provider.rb:113:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:562:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:111:in `run_delayed_notification'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:99:in `block in run_delayed_notifications'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:98:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:98:in `run_delayed_notifications'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:88:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:339:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:334:in `catch'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:334:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:353:in `converge_and_save'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:457:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:280:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:269:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:269:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:247:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:51:in `load'
/usr/bin/chef-solo:51:in `<main>'
```

**Comment by erichelgeson** [comment]
Looks like that is missing https://github.com/chef/ohai/blob/master/lib/ohai/plugins/ps.rb . I'm not familiar with ohai but the blog post says you can load missing plugins in your recipe - https://www.chef.io/blog/2015/04/28/chef-client-12-3-0-released/

If this fixes it, I'd suggest adding the ps plugin back in since it's only setting a 1 or 2 node attributes.

**Comment by erichelgeson** [comment]
`ohai "ps"` in your recipe to workaround for now as well.

**Comment by lamont-granquist** [comment]
minimal ohai is for internal use, its not intended to cover every use case

**Comment by coderanger** [comment]
@lamont-granquist If it is for internal use, that should probably be noted in the `--help` output
