### ISSUE TITLE
undefined method `reset_defaults_and_overrides'

### ISSUE THREAD

**Issue by leshik** [chef/chef#3359]
Hi,

I'm getting weird error on each start of chef-client run, even chef-shell can't start:

```[2015-05-09T11:00:33+03:00] DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
[2015-05-09T11:00:33+03:00] DEBUG: Content-Length validated correctly.
[2015-05-09T11:00:33+03:00] DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
[2015-05-09T11:00:33+03:00] DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
[2015-05-09T11:00:33+03:00] DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
[2015-05-09T11:00:33+03:00] DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
[2015-05-09T11:00:33+03:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_response
[2015-05-09T11:00:33+03:00] DEBUG: Expected JSON response, but got content-type ''
[2015-05-09T11:00:33+03:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
[2015-05-09T11:00:33+03:00] DEBUG: Re-raising exception: NoMethodError - undefined method `reset_defaults_and_overrides' for #<String:0x00000005597c98>
/opt/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:117:in `build_node'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:243:in `build_node'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:437:in `run'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `block in interval_run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `loop'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `interval_run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:372:in `run_application'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
  /opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
  /usr/bin/chef-client:51:in `load'
  /usr/bin/chef-client:51:in `<main>'
[2015-05-09T11:00:33+03:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-05-09T11:00:33+03:00] DEBUG: NoMethodError: undefined method `reset_defaults_and_overrides' for #<String:0x00000005597c98>```

Tried with chef-client 12.0.0 and 12.2.1. There is 12.0.7 chef open source version on server. Have ~3000 nodes but see this error only on few nodes. This started to appear after upgrading from opensource chef 11. There is no errors when listing node attributes with knife, however (knife node show ... -l).

What else can I do to help troubleshoot the issue?

**Comment by leshik** [comment]
Used tcpdump and figured out that provider used transparent proxy to forge web pages. Problem solved, sorry to bother all of you, guys.
