### ISSUE TITLE
undefined method `excluded_members' for Chef::Resource::Group

### ISSUE THREAD

**Issue by mabrizio** [chef/chef#3468]
I have a recipe that manages my nodes' (local) user accounts based on a data bag, so only registered users (in my data bags) are allowed.

When I delete users, I try remove them from a group I made (sudoers), but it's failing when I use ``excluded_members``, this is my full trace:
```
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/my_cookbook/recipes/user_enforcement.rb
================================================================================


NoMethodError
-------------
undefined method `excluded_members' for Chef::Resource::Group


Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/my_cookbook/recipes/user_enforcement.rb:150:in `block (2 levels) in from_file'
  /var/chef/cache/cookbooks/my_cookbook/recipes/user_enforcement.rb:148:in `block in from_file'
  /var/chef/cache/cookbooks/my_cookbook/recipes/user_enforcement.rb:125:in `each'
  /var/chef/cache/cookbooks/my_cookbook/recipes/user_enforcement.rb:125:in `from_file'


Relevant File Content:
----------------------
/var/chef/cache/cookbooks/my_cookbook/recipes/user_enforcement.rb:

143:      group "#{user}" do
144:        action :remove
145:      end
146:
147:      # Remove it from sudoers
148:      group 'sudoers' do
149:        append true
150>>       excluded_members user
151:      end
152:
153:      # Remove user's home
154:      directory "/home/#{user}" do
155:        action :delete
156:        recursive true
157:      end
158:    end
159:  end



[2015-06-02T16:20:11+00:00] ERROR: Running exception handlers
[2015-06-02T16:20:11+00:00] ERROR: Exception handlers complete
[2015-06-02T16:20:11+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated
[2015-06-02T16:20:12+00:00] ERROR: undefined method `excluded_members' for Chef::Resource::Group
[2015-06-02T16:20:13+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
I'm running ``Chef 12.0.8-1`` on ``Ubuntu 14.04``.

If you need any additional information,  please let me know.

Thanks

**Comment by lamont-granquist** [comment]
It looks like 12.0.8 is your chef server version.  What is your chef-client version?  The error message that you are getting looks like the client is older than 11.10.0 where that property on that resource was added.

**Comment by adamedx** [comment]
This is consistent with an older version of Chef Client that doesn't support the `excluded_members` attribute (it was added in the middle of the 11 series: https://github.com/chef/chef/pull/1127), if you use a more recent version of Chef Client (e.g. 12.4.3) you should not hit this problem.
