### ISSUE TITLE
W000013: Can't open file '/root/.subversion/servers': Permission denied

### ISSUE THREAD

**Issue by onknows** [chef/chef#3502]
The subversion resource seems to have a number of issues associated with it. One is that it is only working correctly when not using `root`.

If you specificy not root account there will be message related to config dir.  Messages like below will be frequent for non root accounts - I am using the account `vagrant` that Vagrant creates - for example.

> ==> default: STDERR: svn: warning: W000013: Can't open file '/root/.subversion/servers': Permission denied

You can try to tell Chef to use other config dir for example the config dir of the account like below by using `svn_arguments` and `svn_info_args`.  That will fix some errors but won't result in a working resource.

The resource below will be succesful on first run. On subsequent runs it will fail.

```
  subversion "My Repo" do
    repository "https://my.svn.repo/svn/"
    svn_arguments "--depth immediates --config-dir #{h}/.subversion"
    svn_info_args "--config-dir #{h}/.subversion"
    revision "HEAD"
    destination "#{h}/test"
    group u
    user u
    svn_username '"myuser"'
    svn_password '"****"' 
    action :checkout
  end
```

**Comment by thommay** [comment]
Hi,
sorry to take so long in getting back to you, but we need a bit more information from you to process this ticket. Can you confirm that, in the above example, the variable `h` is set to `/root/` and `u` is `root`? Can you also show `ls -ld /root` and `ls -la /root/.subversion` because this feels like a permission problem rather than a problem with the resource.
Thanks!

**Comment by taleodor** [comment]
Hi, I just had the same issue with a non-root user. So far happens only on Vagrant when using chef-zero provisioner. Doesn't happen in test-kitchen and also doesn't happen with AWS / GCE nodes provisioned via chef-server. Still trying to find a work around.

Please see the stacktrace below:

```
Generated at 2016-01-21 16:16:15 +0000
Mixlib::ShellOut::ShellCommandFailed: subversion[sync_svn_repo] (ccportal::default line 83) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0, 1], but received ''
---- Begin output of svn info ----
STDOUT:
STDERR: svn: warning: W000013: Can't open file '/root/.subversion/servers': Permission denied
---- End output of svn info ----
Ran svn info returned
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.5/lib/mixlib/shellout.rb:289:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.5/lib/mixlib/shellout.rb:276:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/mixin/shell_out.rb:56:in `shell_out!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/provider/subversion.rb:145:in `find_current_revision'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/provider/subversion.rb:44:in `load_current_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/provider.rb:127:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource.rb:596:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/runner.rb:74:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/runner.rb:106:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/runner.rb:106:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/runner.rb:106:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/runner.rb:105:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/client.rb:658:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/client.rb:653:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/client.rb:653:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/client.rb:692:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/client.rb:271:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:261:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:249:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:249:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:215:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:203:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application/client.rb:413:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application/client.rb:403:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application/client.rb:403:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application/client.rb:393:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
```

**Comment by starx** [comment]
@taleodor Have you found a solution to this?

**Comment by bhorstmann** [comment]
@taleodor, did you ever resolve this?

I know this is over a year old, but I have just run into the same issue and a bit of googling has led me here. I have made a workaround for now.

I realised that this only happens when I set the user and group of the checked out files. By removing this, the sync now works regardless of which user runs chef.

Before:
```
subversion "Logstash Patterns" do
    repository "http://xxxxxxxxxxxxxxxxxxx/svn/xxxx/logstash/patterns/"
    destination "/opt/logstash/patterns"
    svn_username "#{node['subversion']['username']}"
    svn_password "#{node['subversion']['password']}"
    action :sync
    user "logstash"
    group "logstash"
    notifies :restart, "service[logstash]"
end
```

After:
```
subversion "Logstash Patterns" do
    repository "http://xxxxxxxxxxxxxxxxxxx/svn/xxxx/logstash/patterns/"
    destination "/opt/logstash/patterns"
    svn_username "#{node['subversion']['username']}"
    svn_password "#{node['subversion']['password']}"
    action :sync
    notifies :restart, "service[logstash]"
    notifies :run, "execute[Logstash Patterns: Set permissions]", :immediately
end

execute "Logstash Patterns: Set permissions" do
    command "chown -R logstash: /opt/logstash/patterns"
    action :nothing
end
```

**Comment by georgexsh** [comment]
a workable patch, for `chef/provider/subversion.rb`, from

```ruby
147         svn_info = shell_out!(command, run_options(:cwd => cwd, :returns => [0, 1])).stdout
```

 to 
```ruby
147         svn_info = shell_out!(command, run_options(:cwd => cwd, :returns => [0, 1], :login => true)).stdout
```
