### ISSUE TITLE
Chef 12.3.0-1 on Solaris 10 sun4u fails where 11.18.0-1 worked

### ISSUE THREAD

**Issue by jblaine** [chef/chef#3505]
Chef 11.18.0-1 worked fine on this host: `SunOS babylon 5.10 Generic_142900-12 sun4u sparc SUNW,Sun-Fire-V240`

I ran `pkgrm chef` and confirmed /opt/chef no longer even exists. Then installed the only Solaris 10 SPARC package available from chef.io:

```
pkgadd -d chef-12.3.0-1.sun4v.solaris chef

Processing package instance <chef> from </tmp/chef-12.3.0-1.sun4v.solaris>

chef(sparc) 12.3.0-1
...
Installation of <chef> was successful.
```

```
/:babylon # which chef-client
/usr/bin/chef-client
/:babylon # ls -ld /usr/bin/chef-client
lrwxrwxrwx   1 root     other         25 Jun  8 16:08 /usr/bin/chef-client -> /opt/chef/bin/chef-client
/:babylon #
/:babylon # chef-client
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-2.1.0/lib/ffi_yajl/map_library_name.rb:90:in `dlopen_yajl_library': cannot find yajl library for platform (RuntimeError)
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-2.1.0/lib/ffi_yajl/ext.rb:34:in `<module:FFI_Yajl>'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-2.1.0/lib/ffi_yajl/ext.rb:30:in `<top (required)>'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-2.1.0/lib/ffi_yajl.rb:45:in `<top (required)>'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.2.1/lib/chef_zero/endpoints/rest_list_endpoint.rb:1:in `<top (required)>'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-zero-4.2.1/lib/chef_zero/server.rb:39:in `<top (required)>'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/apps/chef/lib/chef/http/socketless_chef_zero_client.rb:46:in `<top (required)>'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/apps/chef/lib/chef/http.rb:28:in `<top (required)>'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/apps/chef/lib/chef/rest.rb:24:in `<top (required)>'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/apps/chef/lib/chef/search/query.rb:21:in `<top (required)>'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/apps/chef/lib/chef/dsl/data_query.rb:19:in `<top (required)>'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/apps/chef/lib/chef/mixin/language.rb:20:in `<top (required)>'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/apps/chef/lib/chef/dsl/platform_introspection.rb:259:in `<top (required)>'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/apps/chef/lib/chef/resource.rb:21:in `<top (required)>'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/apps/chef/lib/chef/resource/file.rb:20:in `<top (required)>'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/apps/chef/lib/chef/provider/file.rb:22:in `<top (required)>'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/apps/chef/lib/chef/provider/cookbook_file.rb:19:in `<top (required)>'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/apps/chef/lib/chef/providers.rb:21:in `<top (required)>'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/apps/chef/lib/chef.rb:25:in `<top (required)>'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /opt/chef/embedded/apps/chef/bin/chef-client:23:in `<top (required)>'
        from /usr/bin/chef-client:51:in `load'
        from /usr/bin/chef-client:51:in `<main>'
```

```
/:babylon # find /opt/chef -name libyajl.so
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/libyajl2-1.2.0/ext/libyajl2/libyajl.so
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/libyajl2-1.2.0/lib/libyajl2/vendored-libyajl2/lib/libyajl.so
/:babylon #
```

On a whim, I set `LD_LIBRARY_PATH` and it gets further
```
/:babylon # LD_LIBRARY_PATH=/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/libyajl2-1.2.0/lib/libyajl2/vendored-libyajl2/lib chef-client
[2015-06-08T16:10:45-04:00] INFO: Forking chef instance to converge...
Starting Chef Client, version 12.3.0
[2015-06-08T16:10:46-04:00] INFO: *** Chef 12.3.0 ***
[2015-06-08T16:10:46-04:00] INFO: Chef-client pid: 29041
[2015-06-08T16:10:57-04:00] INFO: Run List is [role[rcf-advanced-sunos-base]]
[2015-06-08T16:10:57-04:00] INFO: Run List expands to [blah blah blah...]
[2015-06-08T16:10:57-04:00] INFO: Starting Chef Run for babylon.our.org
[2015-06-08T16:10:57-04:00] INFO: Running start handlers
[2015-06-08T16:10:57-04:00] INFO: Start handlers complete.
...
Synchronizing Cookbooks:
  - mitre-location
  - rcf-chef-handlers
  - chef_handler
  - graphite_handler
[2015-06-08T16:11:04-04:00] INFO: Storing updated cookbooks/our-certs/files/default/OUR-BA-Root.crt in the cache.
ld.so.1: ruby: fatal: relocation error: file /opt/chef/embedded/lib/libruby.so.2: symbol utimensat: referenced symbol not found
```

**Comment by thommay** [comment]
ping @chef/release-engineers

**Comment by cachamber** [comment]
I can't replicate the issue with chef-12.3.0-1.sun4v.solaris package on a sun4u host:
```
bash-3.2# uname -a
SunOS XXXXXXX 5.10 Generic_147147-26 sun4u sparc SUNW,Sun-Fire-480R
bash-3.2# chef-client --version
Chef: 12.3.0
bash-3.2# chef-client
[2015-06-10T17:26:15-05:00] INFO: Forking chef instance to converge...
Starting Chef Client, version 12.3.0
[2015-06-10T17:26:15-05:00] INFO: *** Chef 12.3.0 ***
[2015-06-10T17:26:16-05:00] INFO: Chef-client pid: 8737
[2015-06-10T17:26:26-05:00] INFO: Run List is XXXXXXX
[2015-06-10T17:26:26-05:00] INFO: Run List expands to XXXXXXX
[2015-06-10T17:26:26-05:00] INFO: Starting Chef Run for XXXXXXX
[2015-06-10T17:26:26-05:00] INFO: Running start handlers
[2015-06-10T17:26:26-05:00] INFO: Start handlers complete.
[2015-06-10T17:26:35-05:00] INFO: Chef Run complete in 9.1001239 seconds
Running handlers:
[2015-06-10T17:26:36-05:00] INFO: Running report handlers
Running handlers complete
[2015-06-10T17:26:36-05:00] INFO: Report handlers complete
Chef Client finished, 0/134 resources updated in 20.8050826 seconds
[2015-06-10T17:26:36-05:00] INFO: Sending resource update report (run-id: bfe190f0-2270-423d-a8ad-b76b5e284fb6)
```

It's interesting to note that you had to use LD_LIBRARY_PATH settings to get it to semi-work.  Can you add a ldd of libruby.so.2.  I'm wondering if you have a non-standard library path configuration.
```
bash-3.2# ldd /opt/chef/embedded/lib/libruby.so.2
        libpthread.so.1 =>       /lib/libpthread.so.1
        librt.so.1 =>    /lib/librt.so.1
        libsocket.so.1 =>        /lib/libsocket.so.1
        libdl.so.1 =>    /lib/libdl.so.1
        libcrypt_d.so.1 =>       /usr/lib/libcrypt_d.so.1
        libm.so.2 =>     /lib/libm.so.2
        libaio.so.1 =>   /lib/libaio.so.1
        libmd.so.1 =>    /lib/libmd.so.1
        libc.so.1 =>     /lib/libc.so.1
        libnsl.so.1 =>   /lib/libnsl.so.1
        libgen.so.1 =>   /lib/libgen.so.1
        libmp.so.2 =>    /lib/libmp.so.2
        libscf.so.1 =>   /lib/libscf.so.1
        libdoor.so.1 =>  /lib/libdoor.so.1
        libuutil.so.1 =>         /lib/libuutil.so.1
        /platform/SUNW,Sun-Fire-480R/lib/libmd_psr.so.1
        /platform/SUNW,Sun-Fire-480R/lib/libc_psr.so.1
bash-3.2# 
```

**Comment by jblaine** [comment]
```
        libpthread.so.1 =>       /lib/libpthread.so.1
        librt.so.1 =>    /lib/librt.so.1
        libsocket.so.1 =>        /lib/libsocket.so.1
        libdl.so.1 =>    /lib/libdl.so.1
        libcrypt_d.so.1 =>       /usr/lib/libcrypt_d.so.1
        libm.so.2 =>     /lib/libm.so.2
        libaio.so.1 =>   /lib/libaio.so.1
        libmd.so.1 =>    /lib/libmd.so.1
        libc.so.1 =>     /lib/libc.so.1
        libnsl.so.1 =>   /lib/libnsl.so.1
        libgen.so.1 =>   /lib/libgen.so.1
        libmp.so.2 =>    /lib/libmp.so.2
        libscf.so.1 =>   /lib/libscf.so.1
        libdoor.so.1 =>  /lib/libdoor.so.1
        libuutil.so.1 =>         /lib/libuutil.so.1
        /platform/SUNW,Sun-Fire-V240/lib/libmd_psr.so.1
        /platform/SUNW,Sun-Fire-V240/lib/libc_psr.so.1
```

**Comment by lamont-granquist** [comment]
It looks like it could be some kind of bug in the new dlopen stuff in ffi-yajl 2.x but I don't have any idea what the bug would be.

**Comment by lamont-granquist** [comment]
Is this still an issue, still couldn't replicate it, still no idea what the cause could be...

**Comment by jblaine** [comment]
Yes. On *some* of our Solaris 10 hosts, as before.

Based on that, it's likely a Solaris 10 patchlevel issue that surfaced in Chef 12.

There's a different error now with 12.4.1 compared to 12.3.0 above.

```
cairo# pkginfo -l chef
   PKGINST:  chef
      NAME:  chef
  CATEGORY:  application
      ARCH:  sparc
   VERSION:  12.4.1-1
   BASEDIR:  /opt
    VENDOR:  Chef Software, Inc. <maintainers@chef.io>
      DESC:  The full stack of chef
    PSTAMP:  chef-solaris-10-sun4v-builder-68a3f5.chef.co2015-07-07T15:17:35Z
  INSTDATE:  Sep 09 2015 21:07
     EMAIL:  Chef Software, Inc. <maintainers@chef.io>
    STATUS:  completely installed
     FILES:    16809 installed pathnames
                1016 linked files
                2336 directories
                 351 executables
              234938 blocks used (approx)
cairo# /opt/chef/bin/chef-client
ld.so.1: ruby: fatal: libdl.so.1: version `SUNW_1.5' not found (required by file /opt/chef/embedded/lib/libruby.so.2)
ld.so.1: ruby: fatal: libdl.so.1: open failed: No such file or directory
Killed
cairo#
```

**Comment by jblaine** [comment]
Really though, if I'm the only person noticing it, it's probably not worth pursuing.

It was just a bummer surprise when we hit 12.x.

While I would really like to continue to use Chef on Solaris 10, our Solaris 10 hosts are old, crusty, unchanging, and ... that's not going to change.

**Comment by lamont-granquist** [comment]
That error is at least slightly more comprehensible, but still doesn't quite make sense.

It looks like we might be missing an rpath somewhere so that the linker can't find libdl.so

That smells like it might be a @scotthain bug in either how ruby builds itself and/or how ruby is configured to build extensions.

Although....

Are these so crusty that they're sol10u1 or some patchlevel like that?  I'm pretty certain we build on sol10u3 now for $REASONS and had to drop sol10u1 support.  The binaries on sol10uX aren't backwards compatible, I'd expect an undefined symbol kind of message out of the linker that smelled very similar to the one you've got there.

**Comment by lamont-granquist** [comment]
And I think $REASONS were that sol10u1 doesn't run on the old-ass hardware we got for builders and requires even older-ass hardware and that'd slow our builds even more, so support got dropped fairly decisively.

**Comment by jblaine** [comment]
They're update 5 and newer.

**Comment by jblaine** [comment]
In fact, one of the failing hosts is u6 and one of the working hosts is u7.

**Comment by scotthain** [comment]
@jblaine @lamont-granquist - This is a bug. We need to enable the linker mapfile in the omnibus-chef project so it links against the correct version of the symbols (We targeted SUNW_1.22.1, which was 10u2, if I recall correctly?) I've put an expedited ticket on our board, we'll get this fixed up. Thanks Jeff!

**Comment by schisamo** [comment]
Expedited *Engineering Services* team ticket is: https://chefio.atlassian.net/browse/ES-408

**Comment by schisamo** [comment]
@sersut I'm reopening this as we'll want @jblaine to validate things once we have a new integration build.

**Comment by sersut** [comment]
@schisamo thanks for catching it. Github is being intelligent and closing things based on the commit message :smile:

**Comment by sersut** [comment]
@jblaine can you try this package and see if that works for you:

http://opscode-omnibus-packages-current.s3.amazonaws.com/solaris2/5.10/sun4v/chef-12.5.0%2B20150914175724-1.sun4v.solaris

**Comment by jblaine** [comment]
@sersut No dice:

```
tmp:cairo # /opt/chef/bin/chef-client
ld.so.1: ruby: fatal: libdl.so.1: version `SUNW_1.5' not found (required by file /opt/chef/embedded/lib/libruby.so.2)
ld.so.1: ruby: fatal: libdl.so.1: open failed: No such file or directory
Killed
tmp:cairo #
```

**Comment by scotthain** [comment]
@jblaine hmmm that's odd.. Can you post the output of `ldd -v /opt/chef/embedded/lib/libruby.so.2`?

**Comment by jblaine** [comment]
```
   find object=libpthread.so.1; required by /opt/chef/embedded/lib/libruby.so.2
        libpthread.so.1 =>       /lib/libpthread.so.1
   find version=libpthread.so.1
        libpthread.so.1 (SUNW_1.2) =>    /lib/libpthread.so.1
        libpthread.so.1 (SUNW_1.1) =>    /lib/libpthread.so.1
        libpthread.so.1 (SUNW_0.9) =>    /lib/libpthread.so.1

   find object=librt.so.1; required by /opt/chef/embedded/lib/libruby.so.2
        librt.so.1 =>    /lib/librt.so.1
   find version=librt.so.1
        librt.so.1 (SUNW_0.7) =>         /lib/librt.so.1

   find object=libsocket.so.1; required by /opt/chef/embedded/lib/libruby.so.2
        libsocket.so.1 =>        /lib/libsocket.so.1
   find version=libsocket.so.1
        libsocket.so.1 (SISCD_2.3) =>    /lib/libsocket.so.1

   find object=libdl.so.1; required by /opt/chef/embedded/lib/libruby.so.2
        libdl.so.1 =>    /lib/libdl.so.1
   find version=libdl.so.1
        libdl.so.1 (SUNW_1.5) =>         (version not found)
        libdl.so.1 (SISCD_2.3) =>        /lib/libdl.so.1

   find object=libcrypt_d.so.1; required by /opt/chef/embedded/lib/libruby.so.2
        libcrypt_d.so.1 =>       /usr/lib/libcrypt_d.so.1
   find version=libcrypt_d.so.1
        libcrypt_d.so.1 (SUNW_1.1) =>    /usr/lib/libcrypt_d.so.1

   find object=libm.so.2; required by /opt/chef/embedded/lib/libruby.so.2
        libm.so.2 =>     /lib/libm.so.2
   find version=libm.so.2
        libm.so.2 (SUNW_1.2) =>  /lib/libm.so.2
        libm.so.2 (SUNW_1.1) =>  /lib/libm.so.2

   find object=libaio.so.1; required by /lib/librt.so.1
        libaio.so.1 =>   /lib/libaio.so.1
   find version=libaio.so.1
        libaio.so.1 (SUNWprivate_1.1) =>         /lib/libaio.so.1

   find object=libmd.so.1; required by /lib/librt.so.1
        libmd.so.1 =>    /lib/libmd.so.1

   find object=libc.so.1; required by /lib/librt.so.1
        libc.so.1 =>     /lib/libc.so.1
   find version=libc.so.1
        libc.so.1 (SUNW_1.21) =>         /lib/libc.so.1
        libc.so.1 (SUNWprivate_1.1) =>   /lib/libc.so.1

   find object=libnsl.so.1; required by /lib/libsocket.so.1
        libnsl.so.1 =>   /lib/libnsl.so.1
   find version=libnsl.so.1
        libnsl.so.1 (SUNW_1.7) =>        /lib/libnsl.so.1
        libnsl.so.1 (SUNWprivate_1.1) =>         /lib/libnsl.so.1

   find object=libc.so.1; required by /lib/libsocket.so.1
   find version=libc.so.1
        libc.so.1 (SUNW_1.19) =>         /lib/libc.so.1
        libc.so.1 (SUNWprivate_1.1) =>   /lib/libc.so.1

   find object=libgen.so.1; required by /usr/lib/libcrypt_d.so.1
        libgen.so.1 =>   /lib/libgen.so.1
   find version=libgen.so.1
        libgen.so.1 (SUNWprivate_1.1) =>         /lib/libgen.so.1

   find object=libc.so.1; required by /usr/lib/libcrypt_d.so.1
   find version=libc.so.1
        libc.so.1 (SYSVABI_1.3) =>       /lib/libc.so.1
        libc.so.1 (SUNWprivate_1.1) =>   /lib/libc.so.1

   find object=libc.so.1; required by /lib/libm.so.2
   find version=libc.so.1
        libc.so.1 (SUNW_1.1) =>  /lib/libc.so.1

   find object=libc.so.1; required by /lib/libaio.so.1
   find version=libc.so.1
        libc.so.1 (SUNW_1.22) =>         /lib/libc.so.1
        libc.so.1 (SUNWprivate_1.1) =>   /lib/libc.so.1

   find object=libc.so.1; required by /lib/libmd.so.1
   find version=libc.so.1
        libc.so.1 (SUNW_0.9) =>  /lib/libc.so.1

   find object=libmp.so.2; required by /lib/libnsl.so.1
        libmp.so.2 =>    /lib/libmp.so.2
   find version=libmp.so.2
        libmp.so.2 (SUNW_1.1) =>         /lib/libmp.so.2
        libmp.so.2 (SUNWprivate_1.1) =>  /lib/libmp.so.2

   find object=libmd.so.1; required by /lib/libnsl.so.1

   find object=libscf.so.1; required by /lib/libnsl.so.1
        libscf.so.1 =>   /lib/libscf.so.1
   find version=libscf.so.1
        libscf.so.1 (SUNW_1.1) =>        /lib/libscf.so.1

   find object=libc.so.1; required by /lib/libnsl.so.1
   find version=libc.so.1
        libc.so.1 (SUNW_1.22.2) =>       /lib/libc.so.1
        libc.so.1 (SUNWprivate_1.1) =>   /lib/libc.so.1

   find object=libc.so.1; required by /lib/libgen.so.1
   find version=libc.so.1
        libc.so.1 (SUNW_1.1) =>  /lib/libc.so.1
        libc.so.1 (SUNWprivate_1.1) =>   /lib/libc.so.1

   find object=libc.so.1; required by /lib/libmp.so.2
   find version=libc.so.1
        libc.so.1 (SYSVABI_1.3) =>       /lib/libc.so.1

   find object=libdoor.so.1; required by /lib/libscf.so.1
        libdoor.so.1 =>  /lib/libdoor.so.1
   find version=libdoor.so.1
        libdoor.so.1 (SUNWprivate_1.1) =>        /lib/libdoor.so.1

   find object=libuutil.so.1; required by /lib/libscf.so.1
        libuutil.so.1 =>         /lib/libuutil.so.1
   find version=libuutil.so.1
        libuutil.so.1 (SUNWprivate_1.1) =>       /lib/libuutil.so.1

   find object=libc.so.1; required by /lib/libscf.so.1
   find version=libc.so.1
        libc.so.1 (SUNW_1.21) =>         /lib/libc.so.1
        libc.so.1 (SUNWprivate_1.1) =>   /lib/libc.so.1

   find object=libgen.so.1; required by /lib/libscf.so.1
   find version=libgen.so.1
        libgen.so.1 (SUNW_1.1) =>        /lib/libgen.so.1

   find object=libc.so.1; required by /lib/libdoor.so.1
   find version=libc.so.1
        libc.so.1 (SUNW_1.22.1) =>       /lib/libc.so.1
        libc.so.1 (SUNWprivate_1.1) =>   /lib/libc.so.1

   find object=libc.so.1; required by /lib/libuutil.so.1
   find version=libc.so.1
        libc.so.1 (SUNW_1.19) =>         /lib/libc.so.1
        libc.so.1 (SUNWprivate_1.1) =>   /lib/libc.so.1

   object=/lib/libpthread.so.1; filter for libc.so.1

   find object=libc.so.1; required by /lib/libpthread.so.1

   object=/lib/libdl.so.1; filter for /usr/lib/ld.so.1

   object=/usr/lib/libcrypt_d.so.1; filter for libc.so.1

   find object=libc.so.1; required by /usr/lib/libcrypt_d.so.1
   find version=libc.so.1
        libc.so.1 (SYSVABI_1.3) =>       /lib/libc.so.1
        libc.so.1 (SUNWprivate_1.1) =>   /lib/libc.so.1

   object=/lib/libm.so.2; filter for $ORIGIN/libm/$HWCAP

   find object=/lib/libm/sparcv9; required by /lib/libm.so.2

   find object=/lib/libm/libm_hwcap1.so.2; required by /lib/libm.so.2

   object=/lib/libmd.so.1; filter for /platform/$PLATFORM/lib/libmd_psr.so.1

   find object=/platform/SUNW,Sun-Fire-280R/lib/libmd_psr.so.1; required by /lib/libmd.so.1
        /platform/SUNW,Sun-Fire-280R/lib/libmd_psr.so.1

   find object=libc.so.1; required by /platform/SUNW,Sun-Fire-280R/lib/libmd_psr.so.1
   find version=libc.so.1
        libc.so.1 (SUNW_0.9) =>  /lib/libc.so.1

   object=/lib/libc.so.1; filter for /usr/lib/ld.so.1

   object=/lib/libc.so.1; filter for libm.so.2

   find object=libm.so.2; required by /lib/libc.so.1

   object=/lib/libc.so.1; filter for /platform/$PLATFORM/lib/libc_psr.so.1

   find object=/platform/SUNW,Sun-Fire-280R/lib/libc_psr.so.1; required by /lib/libc.so.1
        /platform/SUNW,Sun-Fire-280R/lib/libc_psr.so.1

   object=/lib/libnsl.so.1; filter for libc.so.1

   find object=libc.so.1; required by /lib/libnsl.so.1
   find version=libc.so.1
        libc.so.1 (SUNW_1.22.2) =>       /lib/libc.so.1
        libc.so.1 (SUNWprivate_1.1) =>   /lib/libc.so.1
```

**Comment by scotthain** [comment]
Thanks @jblaine, I have some suspicions. My first guess is that the machines it's not working on may have originally started out as earlier than Solaris 10u2 and were patched up to that point (or beyond) but some required patches (required for this to work) may not have been applied. Do you know if these may have had a 9->10 or 10->10u2+ patch sequence?

Also - for some more data, can you give me the output of `/usr/ccs/bin/elfdump -v /lib/libdl.so.1` ?

I'd really like to get you up and running on the latest version of 12, if at all possible!

**Comment by jblaine** [comment]
I don't know the exact history other than none of them went from Solaris 9 -> 10. They were all fresh installs of Solaris 10 originally.

/usr/ccs/bin/elfdump -v /lib/libdl.so.1
```
Version Definition Section:  .SUNW_version
     index  version                     dependency
       [1]  libdl.so.1                                       [ BASE ]
       [2]  SUNW_1.4                    SUNW_1.3
       [3]  SUNW_1.3                    SUNW_1.2
       [4]  SUNW_1.2                    SUNW_1.1
       [5]  SUNW_1.1                    SUNW_0.8
       [7]  SUNW_0.8                    SUNW_0.7
       [6]  SUNWprivate_1.1
       [8]  SUNW_0.7                    SISCD_2.3
       [9]  SISCD_2.3
```

**Comment by MarkGibbons** [comment]
I've got the same issue on a server running u6.  It was built as u6 originally.  I can test a fix when you have one.

thanks,
  Mark

**Comment by scotthain** [comment]
@jblaine @MarkGibbons Thanks for all the information - we've made a few tweaks and will have a new build for y'all to test out shortly. I'll post a link here once it gets through.

**Comment by scotthain** [comment]
@jblaine @MarkGibbons - The build isn't up in the current S3 but here it is available from my S3 bucket if you want to try it out: https://shain-bucket.s3.amazonaws.com/chef-12.5.0%2B20150916214345-1.sun4v.solaris

**Comment by MarkGibbons** [comment]
That fails the same way.

chef-client -v
ld.so.1: ruby: fatal: libdl.so.1: version `SUNW_1.5' not found (required by file /opt/chef/embedded/lib/libruby.so.2)
ld.so.1: ruby: fatal: libdl.so.1: open failed: No such file or directory
Killed

**Comment by scotthain** [comment]
@MarkGibbons @jblaine I think I've found the problem, we weren't as stringent about the allowable symbol versions in all the libraries, as we should have been. I'm running some tests now on a new build, I should have a new build for y'all to test tomorrow.

Thanks for your patience and help on this.

**Comment by MarkGibbons** [comment]
@scotthain  I noticed you are calling the builds .sun4v instead of sparc.  Since there's no sun4u version could you name them .sparc ?

**Comment by scotthain** [comment]
@MarkGibbons currently it names it based on the arch/machine it's built on (which is a sun4v based machine). Can you open an issue with this if it's causing problems for you so we can discuss?

**Comment by scotthain** [comment]
Hey there - sorry for the delay, had to juggle some libraries. I think I've narrowed it down to where it should work on u5+, but there's still an oddity in libnsl, I'm not sure if it's transitively linking correctly or not, and unfortunately I don't have a sparc system running u5.

Here's a new test build, if one of y'all would be so kind as to check it out.
https://shain-bucket.s3.amazonaws.com/chef-12.5.0%2B20150921211707-1.sun4v.solaris

If it does end up failing, a `pvs -dos ` on libsocket.so, libnsl.so and libdl.so would be super helpful (that is a lot of output, I know... maybe a gist if possible?)

Thanks again for helping work this out!

**Comment by MarkGibbons** [comment]
The version, chef-12.5.0%2B20150921211707-1.sun4v.solaris, works on an old u6 solaris server where 12.4.1-1 fails.

thanks

**Comment by jblaine** [comment]
Ditto comment above. Works for me.

**Comment by scotthain** [comment]
@MarkGibbons @jblaine Awesome! I'll get these changes in and hopefully it'll make it to the 12.5.0 release> Thanks for the help!

**Comment by schisamo** [comment]
Changes @scotthain referenced above: https://github.com/chef/omnibus-chef/pull/506

**Comment by jblaine** [comment]
This is back again in 12.17.44. Affecting the same systems above as when I reported this for 12.3.x.

**Comment by jblaine** [comment]
Our paid Chef Support ticket in Zendesk on this topic today: #13069

**Comment by MarkGibbons** [comment]
@jblaine Are you running Solaris 10 Update 11?  If I remember correctly chef-client 12.14 requires U11.  I've got my old solaris boxes up to to chef-client 12.13.37 and stopped there until I can retire or upgrade the OS.

**Comment by scotthain** [comment]
@MarkGibbons You are correct, the RFC went up August 1st to drop support for Solaris 10 pre update 11, you can find that here: https://github.com/chef/chef-rfc/pull/212. It was also noted in the changelog for 12.14.60: https://github.com/chef/chef/blob/v12.14.77/CHANGELOG.md

@jblaine I would recommend using 12.13.37 as well, and sorry for the confusion.

**Comment by jblaine** [comment]
Bummer it was not in the **release notes**

Thanks for the pointers.
