### ISSUE TITLE
deploy_revision ends up nuking all the releases if a deploy fails, because a reference can't be resolved.

### ISSUE THREAD

**Issue by aabes** [chef/chef#3532]
Chef 11.16.4,  deploying from git.

If rollback_on_error is set = true, and the release tag is fat fingered and not found, the complete releases/ directory, destroying the server! leading to a fun few hours of production recovery

```
   [2015-06-12T22:45:00+00:00] DEBUG: Re-raising exception: Chef::Exceptions::UnresolvableGitReference - deploy_revision[/home/XX] (XX::webserver line 232) had 
   an error: Chef::Exceptions::UnresolvableGitReference: Unable to parse SHA reference for '20150612.xx' in repository 'git@github.com:XX/yy.git'. Verify your (case-se
   nsitive) repository URL and revision.
   `git ls-remote` output: 
   /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/mixin/why_run.rb:241:in `run'
     /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/mixin/why_run.rb:322:in `block in run'
     /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/mixin/why_run.rb:321:in `each'
     /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/mixin/why_run.rb:321:in `run'
     /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider.rb:134:in `process_resource_requirements'
     /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider.rb:111:in `run_action'
     /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider/deploy.rb:259:in `run_scm_sync'
     /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider/deploy.rb:254:in `update_cached_repo'
     /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider/deploy.rb:154:in `deploy'
     /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider/deploy.rb:109:in `block in action_deploy'
     /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4/lib/chef/provider/deploy.rb:443:in `with_rollback_on_error'

```

followed by a total wipe of the releases directory:

```
   [2015-06-12T22:44:59+00:00] INFO: Removing failed deploy */home/XX/releases/*
   [2015-06-12T22:45:00+00:00] INFO: Running queued delayed notifications before re-raising exception
```

Looking at the code in 11-stable, this is still an issue !

**Comment by lamont-granquist** [comment]
Still an issue in 12?

**Comment by aabes** [comment]
12 requires ruby >2 (https://www.chef.io/blog/2014/11/25/ruby-1-9-3-eol-and-chef-12/)
It's not an option for us.

**Comment by lamont-granquist** [comment]
11 is not receiving bugfixes only security updates.  if this bug affects only 11 or if you hit any other bugs that affect only 11 those will not be getting fixed.  you should use the omnibus updaters which come pre-packaged with ruby 2.x and not be rolling your own distro or gem solutions to avoid this problem.  we cannot and will not support bugs specific to chef running in distro rubies or hand rolled rubies.

**Comment by aabes** [comment]
The code in: https://github.com/chef/chef/blob/11-stable/lib/chef/provider/deploy/revision.rb#L45 seems relatively trival to fix... and this is a pretty critical issue ((which according to support, is still applicable to 12!)
