### ISSUE TITLE
chef_12.4.0~rc.2 - Option action must be equal to one of: enable, disable!  You passed :nothing.

### ISSUE THREAD

**Issue by martinb3** [chef/chef#3535]
Hello! We've gotten a [bug report](https://github.com/rackspace-cookbooks/chef-slack_handler/issues/3) on the chef [slack handler cookbook](https://github.com/rackspace-cookbooks/chef-slack_handler/issues/3) that uses the [chef_handler cookbook](https://github.com/opscode-cookbooks/chef_handler) like so:

```
chef_handler "Chef::Handler::Slack" do
  source handler_file
  arguments [
              node['chef_client']['handler']['slack']
            ]
  action :nothing
end.run_action(:enable)
```

In chef 12.3, this works great. When I upgrade to the 12.4 rc2 release candidate, it breaks with:
```
         ================================================================================
         Recipe Compile Error in /tmp/kitchen/cache/cookbooks/slack_handler/recipes/default.rb
         ================================================================================
         
         Chef::Exceptions::ValidationFailed
         ----------------------------------
         Option action must be equal to one of: enable, disable!  You passed :nothing.
         
       Cookbook Trace:
         ---------------
           /tmp/kitchen/cache/cookbooks/slack_handler/recipes/default.rb:47:in `block in from_file'
           /tmp/kitchen/cache/cookbooks/slack_handler/recipes/default.rb:42:in `from_file'
         
       Relevant File Content:
         ----------------------
         /tmp/kitchen/cache/cookbooks/slack_handler/recipes/default.rb:
         
          40:  end.run_action(:create)
          41:  
          42:  chef_handler "Chef::Handler::Slack" do
        43:    source handler_file
          44:    arguments [
          45:                node['chef_client']['handler']['slack']
          46:              ]
          47>>   action :nothing
          48:  end.run_action(:enable)
          49:  
```

In currently released versions, `:nothing` is [common to all resources](https://docs.chef.io/resource_common.html). Did this change in 12.4?

**Comment by martinb3** [comment]
This change appears to have been made in https://github.com/chef/chef/commit/236570dc9605ac312b44508b1c3a6a0e7c19b4dc by @jkeiser. `:nothing` is no longer an allowed action on any resource subclassed from lib/chef/resource.rb.

**Comment by jkeiser** [comment]
It's supposed to be common.  Looking.

**Comment by jkeiser** [comment]
@martinb3 when I run this cookbook on master of chef, it seems to run the right action:

```ruby
class X < Chef::Resource
  allowed_actions :enable, :disable
end

x 'foo' do
  action :nothing
end
```

Yields this:

```
~/s/chef> bundle exec chef-apply x.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * x[foo] action nothing (skipped due to action :nothing)
```

**Comment by martinb3** [comment]
@jkeiser I don't have an environment setup where I can test against master -- perhaps this is just something wrong with the 12.4 release candidate? I've had two different users of the cookbook report it, so even if it's fixed in master, what should I do let the release managers know? Can you confirm you see it in the 12-stable branch?

**Comment by jkeiser** [comment]
I found a way to reproduce, I'll look at a fix tomorrow!

**Comment by martinb3** [comment]
@jkeiser thanks! I hope I didn't call out your change as the breaking one unnecessarily; I appreciate the help!!

**Comment by lamont-granquist** [comment]
I might have found this as well, although not with action :nothing:

```
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/sk_role_base/recipes/default.rb
================================================================================

Chef::Exceptions::ValidationFailed
----------------------------------
Option action must be equal to one of: install, upgrade, reconfig, remove, purge, install! You passed :remove.

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/sk_ruby/recipes/ubuntu.rb:12:in `block in from_file'
/var/chef/cache/cookbooks/sk_ruby/recipes/ubuntu.rb:11:in `from_file'
/var/chef/cache/cookbooks/sk_ruby/recipes/default.rb:28:in `from_file'
/var/chef/cache/coo
kbooks/sk_app_base/recipes/ruby_install.rb:1:in `from_file'
    /var/chef/cache/cookbooks/sk_app_base/recipes/default.rb:4:in `from_file'
    /var/chef/cache/cookbooks/sk_role_base/recipes/unix.rb:16:in `from_file'
    /var/chef/cache/cookbooks/sk_role_base/recipes/default.rb:5:in `from_file'
  
  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/sk_ruby/recipes/ubuntu.rb:
  
    5:  pkgs_remove = %w{ ruby ruby1.9.1 ruby1.9.3 ruby1.9.1-dev libruby1.9.1 libruby-extras libruby1.8-extras }
    6:  
    7:  if node['platform'] == 'ubuntu' && node['platform_version'].to_f < 14.04
    8:    pkgs_remove += %w{ ruby1.8-dev rubygems rubygems1.8 }
    9:  end
   10:  
   11:  multipackage pkgs_remove do
   12>>   action :remove
   13:  end
   14:  
   15:  # install packages necessary to build
   16:  multipackage_install %w{ wget zlib1g-dev libssl-dev libyaml-dev libxml2-dev libxslt-dev }
   17:  
   18:  if node['platform'] == 'ubuntu' && node['platform_version'].to_f < 11.10
   19:    multipackage_install "libreadline5-dev"
   20:  else
   21:    multipackage_install "libreadline6-dev"
  
  
  Running handlers:
  Running handlers complete
  Chef Client failed. 0 resources updated in 22.645040132 seconds
```

```
# cat /var/chef/cache/chef-stacktrace.out
Generated at 2015-06-15 18:00:36 -0700
Chef::Exceptions::RunFailedWrappingError: Found 1 errors, they are stored in the backtrace
1) Chef::Exceptions::ValidationFailed - Option action must be equal to one of: install, upgrade, reconfig, remove, purge, install! You passed :remove.
/opt/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:143:in `_pv_equal_to'
/opt/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:70:in `block (2 levels) in validate'
/opt/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:67:in `each'
/opt/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:67:in `block in validate'
/opt/chef/embedded/apps/chef/lib/chef/mixin/params_validate
.rb:57:in `each'
/opt/chef/embedded/apps/chef/lib/chef/mixin/params_validate.rb:57:in `validate'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:183:in `block in action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:182:in `each'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:182:in `action'
/var/chef/cache/cookbooks/sk_ruby/recipes/ubuntu.rb:12:in `block in from_file'
/opt/chef/embedded/apps/chef/lib/chef/resource_builder.rb:77:in `instance_eval'
/opt/chef/embedded/apps/chef/lib/chef/resource_builder.rb:77:in `build'
/opt/chef/embedded/apps/chef/lib/chef/dsl/recipe.rb:110:in `build_resource'
/opt/chef/embedded/apps/chef/lib/chef/dsl/recipe.rb:71:in `declare_resource'
/opt/chef/embedded/apps/chef/lib/chef/dsl/resources.rb:14:in `multipackage'
/var/chef/cache/cookbooks/sk_ruby/recipes/ubuntu.rb:11:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:228:in `load_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:174:in `load_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:143:in `block in include_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:142:in `each'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:142:in `include_recipe'
/opt/chef/embedded/apps/chef/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/chef/cache/cookbooks/sk_ruby/recipes/default.rb:28:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:228:in `load_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:174:in `load_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:143:in `block in include_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:142:in `each'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:142:in `include_recipe'
/opt/chef/embedded/apps/chef/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/chef/cache/cookbooks/sk_app_base/recipes/ruby_install.rb:1:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:228:in `load_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:174:in `load_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:143:in `block in include_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:142:in `each'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:142:in `include_recipe'
/opt/chef/embedded/apps/chef/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/chef/cache/cookbooks/sk_app_base/recipes/default.rb:4:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:228:in `load_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:174:in `load_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:143:in `block in include_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:142:in `each'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:142:in `include_recipe'
/opt/chef/embedded/apps/chef/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/chef/cache/cookbooks/sk_role_base/recipes/unix.rb:16:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:228:in `load_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:174:in `load_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:143:in `block in include_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:142:in `each'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:142:in `include_recipe'
/opt/chef/embedded/apps/chef/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/chef/cache/cookbooks/sk_role_base/recipes/default.rb:5:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:228:in `load_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:174:in `load_recipe'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
/opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
/opt/chef/embedded/apps/chef/lib/chef/run_context.rb:97:in `load'
/opt/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:87:in `setup_run_context'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:480:in `setup_run_context'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:266:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:252:in `run_with_graceful_exit_option'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:229:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:212:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:375:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:53:in `load'
/usr/bin/chef-client:53:in `<main>'#    
```
