### ISSUE TITLE
Recipe Names in Run List get mutated when version constraints are present.

### ISSUE THREAD

**Issue by danielsdeleo** [chef/chef#3618]
This issue was reported to Chef Software's support team, so not sure how much I can copy publicly. Anyway, when using cookbook version constraints in roles, eventually the `CookbookCompiler` will try to load the recipe using a string like `cookbook_name::recipe_name@version` which isn't understood by the regex that load_recipe/include_recipe use.

```
[2015-06-29T17:06:31-07:00] DEBUG: Re-raising exception: Chef::Exceptions::RecipeNotFound - could not find recipe REDACTED@1.2.3 for cookbook REDACTED
/opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:217:in `load_recipe'
  /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:174:in `load_recipe'
  /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
  /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
  /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
  /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
  /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:97:in `load'
  /opt/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:87:in `setup_run_context'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:486:in `setup_run_context'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:266:in `run'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:270:in `block in fork_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:224:in `block in run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:212:in `run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
  /opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
  /usr/bin/chef-client:53:in `load'
  /usr/bin/chef-client:53:in `<main>'
```

I think the issue is this line mutates the recipe string: https://github.com/chef/chef/pull/2312/files#diff-fe1868f8a23c261be1628c559123b3eaR79

**Comment by danielsdeleo** [comment]
cc @justinredd @double-z
