### ISSUE TITLE
chef-client fails to save an updated node to Chef Server

### ISSUE THREAD

**Issue by nicknameforever** [chef/chef#3637]
**Chef Server Version** 12.3.0
**Chef Client Version** 12.3.0 or 12.4.0
**OS** CentOS 6.6

The chef-client can execute its runlist, but fails to save its state back to the server. It issues a PUT request to the server, in server nginx logs I can see a 200 response. The client is freezing for 7 minutes or so, then gives the following output and successfully sends an error report to the server.

<pre>
[2015-07-05T16:23:48+02:00] DEBUG: Converging node nodename
[2015-07-05T16:23:48+02:00] DEBUG: Saving the current state of node nodename
[2015-07-05T16:23:48+02:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
[2015-07-05T16:23:48+02:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_request
[2015-07-05T16:23:48+02:00] DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
[2015-07-05T16:23:48+02:00] DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
[2015-07-05T16:23:48+02:00] DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request
[2015-07-05T16:23:48+02:00] DEBUG: Signing the request as nodename
[2015-07-05T16:23:48+02:00] DEBUG: String to sign: 'Method:PUT
Hashed Path:tlCVChMRPtcjKXpKa70Hx5OgUtQ=
X-Ops-Content-Hash:UX3pZyOkOwMu6tBwWsFKHLfbhT4=
X-Ops-Timestamp:2015-07-05T14:23:48Z
X-Ops-UserId:nodename'
Header hash: {"X-Ops-Sign"=>"algorithm=sha1;version=1.0;", "X-Ops-Userid"=>"nodename", "X-Ops-Timestamp"=>"2015-07-05T14:23:48Z", "X-Ops-Content-Hash"=>"UX3pZyOkOwMu6tBwWsFKHLfbhT4=", "X-Ops-Authorization-1"=>"oKBnu7JDTFdeKlBY+e6ca07GJwvJUH1fztn7WhXhWS53cN6/wQjlIWEhA+Kv", "X-Ops-Authorization-2"=>"JdEMBAao7Xp/xC1/1jUlYG8SI/WccLCq0Uq4CRCZnsd+ELSBEnodKmbsgI2W", "X-Ops-Authorization-3"=>"90l3sVjPRMQq7TGdSVaEPxaLIkdJPWtkdj0lcLfR+KAMqZpvN2nYzCwYzq+H", "X-Ops-Authorization-4"=>"xvCrrpXIbaVxTUrm+E27d3aHbD2d9o6MGhQHIRhpe/06L6XHeDvOA1Ew7JlM", "X-Ops-Authorization-5"=>"N91ttDvauX1XrHX+CrowIgVj57CpwjypCrk18tH0eDMtqpQvrcnHlKoDxWKu", "X-Ops-Authorization-6"=>"RxafGVecuIXmDmVY72U/YrORq3bXT9TWF4/B2a0pgQ=="}
[2015-07-05T16:23:48+02:00] DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
[2015-07-05T16:23:48+02:00] DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
[2015-07-05T16:23:48+02:00] DEBUG: Initiating PUT to https://xx.xx.xx.xx/organizations/organizationname/nodes/nodename
[2015-07-05T16:23:48+02:00] DEBUG: ---- HTTP Request Header Data: ----
[2015-07-05T16:23:48+02:00] DEBUG: Content-Type: application/json
[2015-07-05T16:23:48+02:00] DEBUG: Accept: application/json
[2015-07-05T16:23:48+02:00] DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
[2015-07-05T16:23:48+02:00] DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.0;
[2015-07-05T16:23:48+02:00] DEBUG: X-OPS-USERID: nodename
[2015-07-05T16:23:48+02:00] DEBUG: X-OPS-TIMESTAMP: 2015-07-05T14:23:48Z
[2015-07-05T16:23:48+02:00] DEBUG: X-OPS-CONTENT-HASH: UX3pZyOkOwMu6tBwWsFKHLfbhT4=
[2015-07-05T16:23:48+02:00] DEBUG: X-OPS-AUTHORIZATION-1: oKBnu7JDTFdeKlBY+e6ca07GJwvJUH1fztn7WhXhWS53cN6/wQjlIWEhA+Kv
[2015-07-05T16:23:48+02:00] DEBUG: X-OPS-AUTHORIZATION-2: JdEMBAao7Xp/xC1/1jUlYG8SI/WccLCq0Uq4CRCZnsd+ELSBEnodKmbsgI2W
[2015-07-05T16:23:48+02:00] DEBUG: X-OPS-AUTHORIZATION-3: 90l3sVjPRMQq7TGdSVaEPxaLIkdJPWtkdj0lcLfR+KAMqZpvN2nYzCwYzq+H
[2015-07-05T16:23:48+02:00] DEBUG: X-OPS-AUTHORIZATION-4: xvCrrpXIbaVxTUrm+E27d3aHbD2d9o6MGhQHIRhpe/06L6XHeDvOA1Ew7JlM
[2015-07-05T16:23:48+02:00] DEBUG: X-OPS-AUTHORIZATION-5: N91ttDvauX1XrHX+CrowIgVj57CpwjypCrk18tH0eDMtqpQvrcnHlKoDxWKu
[2015-07-05T16:23:48+02:00] DEBUG: X-OPS-AUTHORIZATION-6: RxafGVecuIXmDmVY72U/YrORq3bXT9TWF4/B2a0pgQ==
[2015-07-05T16:23:48+02:00] DEBUG: HOST: xx.xx.xx.xx:443
[2015-07-05T16:23:48+02:00] DEBUG: X-REMOTE-REQUEST-ID: f4a53560-9ece-4629-a4dc-c193c1d522e2
[2015-07-05T16:23:48+02:00] DEBUG: Content-Length: 14672
[2015-07-05T16:23:48+02:00] DEBUG: ---- End HTTP Request Header Data ----
[2015-07-05T16:30:39+02:00] DEBUG: Re-raising exception: Errno::ECONNRESET - Connection reset by peer
/opt/chef/embedded/lib/ruby/2.1.0/openssl/buffering.rb:182:in `sysread_nonblock'
  /opt/chef/embedded/lib/ruby/2.1.0/openssl/buffering.rb:182:in `read_nonblock'
  /opt/chef/embedded/lib/ruby/2.1.0/net/protocol.rb:153:in `rbuf_fill'
  /opt/chef/embedded/lib/ruby/2.1.0/net/protocol.rb:134:in `readuntil'
  /opt/chef/embedded/lib/ruby/2.1.0/net/protocol.rb:144:in `readline'
  /opt/chef/embedded/lib/ruby/2.1.0/net/http/response.rb:39:in `read_status_line'
  /opt/chef/embedded/lib/ruby/2.1.0/net/http/response.rb:28:in `read_new'
  /opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:1408:in `block in transport_request'
  /opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:1405:in `catch'
  /opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:1405:in `transport_request'
  /opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:1378:in `request'
  /opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:1371:in `block in request'
  /opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:853:in `start'
  /opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:1369:in `request'
  /opt/chef/embedded/apps/chef/lib/chef/http/basic_client.rb:65:in `request'
  /opt/chef/embedded/apps/chef/lib/chef/http.rb:266:in `block in send_http_request'
  /opt/chef/embedded/apps/chef/lib/chef/http.rb:298:in `block in retrying_http_errors'
  /opt/chef/embedded/apps/chef/lib/chef/http.rb:296:in `loop'
  /opt/chef/embedded/apps/chef/lib/chef/http.rb:296:in `retrying_http_errors'
  /opt/chef/embedded/apps/chef/lib/chef/http.rb:260:in `send_http_request'
  /opt/chef/embedded/apps/chef/lib/chef/http.rb:143:in `request'
  /opt/chef/embedded/apps/chef/lib/chef/http.rb:118:in `put'
  /opt/chef/embedded/apps/chef/lib/chef/node.rb:515:in `save'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:277:in `save_updated_node'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:356:in `converge_and_save'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:457:in `run'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
  /opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
  /usr/bin/chef-client:51:in `load'
  /usr/bin/chef-client:51:in `<main>'
</pre>

**Comment by nicknameforever** [comment]
It was a firewall issue. Looks like chef also needs some very high port numbers.

**Comment by veilig2000** [comment]
do you remember what ports you had to open for this issue?  I'm running into the same issue - thought I had opened everything I needed to, but I must be missing something.

**Comment by nicknameforever** [comment]
Unfortunately not, i just opened a port range

**Comment by chankongching** [comment]
May i know what is the content of your X-Ops-Content-Hash? i know how to generate that but dunno what to be generated
