### ISSUE TITLE
Report handler error from state_attrs

### ISSUE THREAD

**Issue by tfitch** [chef/chef#3677]
A customer has encountered this issue while using a report handler.

```
[2015-06-26T00:53:57+00:00] INFO: bash[deploy ] ran successfully
[2015-06-26T00:53:57+00:00] INFO: Chef Run complete in 66.470284846 seconds
[2015-06-26T00:53:58+00:00] INFO: Running report handlers
[2015-06-26T00:53:58+00:00] INFO: Report handlers complete
[2015-06-26T00:53:58+00:00] ERROR: Running exception handlers
[2015-06-26T00:53:58+00:00] ERROR: Exception handlers complete
[2015-06-26T00:53:58+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-06-26T00:53:58+00:00] ERROR: undefined method `state_attrs' for Hash:Class
[2015-06-26T00:53:58+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
 
=====================================
[2015-06-26T00:53:58+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Here it is:
=====================================
 
Generated at 2015-06-26 00:53:58 +0000
NoMethodError: undefined method `state_attrs' for Hash:Class
/opt/chef/embedded/apps/chef/lib/chef/resource_reporter.rb:94:in `state'
/opt/chef/embedded/apps/chef/lib/chef/resource_reporter.rb:66:in `for_json'
/opt/chef/embedded/apps/chef/lib/chef/resource_reporter.rb:273:in `block in prepare_run_data'
/opt/chef/embedded/apps/chef/lib/chef/resource_reporter.rb:272:in `map'
/opt/chef/embedded/apps/chef/lib/chef/resource_reporter.rb:272:in `prepare_run_data'
/opt/chef/embedded/apps/chef/lib/chef/resource_reporter.rb:229:in `post_reporting_data'
/opt/chef/embedded/apps/chef/lib/chef/resource_reporter.rb:214:in `run_completed'
/opt/chef/embedded/apps/chef/lib/chef/event_dispatch/dispatcher.rb:29:in `block (2 levels) in def_forwarding_method'
/opt/chef/embedded/apps/chef/lib/chef/event_dispatch/dispatcher.rb:29:in `each'
/opt/chef/embedded/apps/chef/lib/chef/event_dispatch/dispatcher.rb:29:in `block in def_forwarding_method'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:476:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:51:in `load'
/usr/bin/chef-client:51:in `<main>'
```

Doing a `class.inspect` on the report handler for debugging they noticed the item is a Hash instead of a Chef Resource.

```
/opt/chef/embedded/apps/chef/lib/chef/resource_reporter.rb: 94
Chef::Resource::Template
/opt/chef/embedded/apps/chef/lib/chef/resource_reporter.rb: 94
Chef::Resource::RubyBlock
/opt/chef/embedded/apps/chef/lib/chef/resource_reporter.rb: 94
Hash
[2015-07-01T19:14:34+00:00] DEBUG: Re-raising exception: NoMethodError - undefined method `state_attrs' for Hash:Class
/opt/chef/embedded/apps/chef/lib/chef/resource_reporter.rb:96:in `state'
  /opt/chef/embedded/apps/chef/lib/chef/resource_reporter.rb:66:in `for_json'
  /opt/chef/embedded/apps/chef/lib/chef/resource_reporter.rb:275:in `block in prepare_run_data'
  /opt/chef/embedded/apps/chef/lib/chef/resource_reporter.rb:274:in `map'
  /opt/chef/embedded/apps/chef/lib/chef/resource_reporter.rb:274:in `prepare_run_data'
  /opt/chef/embedded/apps/chef/lib/chef/resource_reporter.rb:231:in `post_reporting_data'
  /opt/chef/embedded/apps/chef/lib/chef/resource_reporter.rb:216:in `run_completed'
  /opt/chef/embedded/apps/chef/lib/chef/event_dispatch/dispatcher.rb:29:in `block (2 levels) in def_forwarding_method'
  /opt/chef/embedded/apps/chef/lib/chef/event_dispatch/dispatcher.rb:29:in `each'
  /opt/chef/embedded/apps/chef/lib/chef/event_dispatch/dispatcher.rb:29:in `block in def_forwarding_method'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:476:in `run'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
  /opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
  /usr/bin/chef-client:51:in `load'
  /usr/bin/chef-client:51:in `<main>'
```

Lots to digest there - thanks for looking at it.

**Comment by tfitch** [comment]
Whew - got the customer to dig in further and it was an error in their handler code.  We're all clear here, marking as closed.
