### ISSUE TITLE
Chef-Client cookbook broken against latest nightly

### ISSUE THREAD

**Issue by jaym** [chef/chef#3696]
Build Version: 12.5.0-current.0+20150721082808.git.14.c91b337-1

```
-----> Starting Kitchen (v1.4.2.dev.0)
-----> Cleaning up any prior instances of <server-ubuntu-1204-ubuntu-1204>
-----> Destroying <server-ubuntu-1204-ubuntu-1204>...
       Finished destroying <server-ubuntu-1204-ubuntu-1204> (0m0.00s).
-----> Testing <server-ubuntu-1204-ubuntu-1204>
-----> Creating <server-ubuntu-1204-ubuntu-1204>...
       If you are not using an account that qualifies under the AWS
free-tier, you may be charged to run these suites. The charge
should be minimal, but neither Test Kitchen nor its maintainers
are responsible for your incurred costs.

       Instance <i-8efa1578> requested.
       EC2 instance <i-8efa1578> created.
       Waited 0/300s for instance <i-8efa1578> to become ready.
       Waited 5/300s for instance <i-8efa1578> to become ready.
       EC2 instance <i-8efa1578> ready.
       [SSH] Established
       Finished creating <server-ubuntu-1204-ubuntu-1204> (1m3.27s).
-----> Converging <server-ubuntu-1204-ubuntu-1204>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 3.3.0...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus (12.5.0-current.0+20150721082808.git.14.c91b337-1)
       Downloading https://www.chef.io/chef/install.sh to file /tmp/install.sh
       Trying wget...
       Download complete.
       Downloading Chef 12.5.0-current.0%2B20150721082808.git.14.c91b337-1 for ubuntu...
       downloading https://www.chef.io/chef/metadata?v=12.5.0-current.0%2B20150721082808.git.14.c91b337-1&prerelease=false&nightlies=false&p=ubuntu&pv=12.04&m=x86_64
         to file /tmp/install.sh.1031/metadata.txt
       trying wget...
       url	https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/10.04/x86_64/chef_12.5.0~current.0%2B20150721082808.git.14.c91b337-1_amd64.deb
       md5	cb84126906e457559d73f1b6d0f44b8f
       sha256	2e4ecdf4ebcd9346ada355f5c4bd5d5e71d9ad136f2c9bb197597ec9e35bc510
       downloaded metadata file looks valid...
       downloading https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/10.04/x86_64/chef_12.5.0~current.0%2B20150721082808.git.14.c91b337-1_amd64.deb
         to file /tmp/install.sh.1031/chef_12.5.0~current.0%2B20150721082808.git.14.c91b337-1_amd64.deb
       trying wget...
       Comparing checksum with sha256sum...
       Installing Chef 12.5.0-current.0%2B20150721082808.git.14.c91b337-1
       installing with dpkg...
       Selecting previously unselected package chef.
(Reading database ... 47562 files and directories currently installed.)
       Unpacking chef (from .../chef_12.5.0~current.0%2B20150721082808.git.14.c91b337-1_amd64.deb) ...
       Setting up chef (12.5.0~current.0+20150721082808.git.14.c91b337-1) ...
       Thank you for installing Chef!
       Processing triggers for initramfs-tools ...
       update-initramfs: Generating /boot/initrd.img-3.2.0-87-virtual
       Transferring files to <server-ubuntu-1204-ubuntu-1204>
       Starting Chef Client, version 12.5.0.current.0
       Creating a new client identity for server-ubuntu-1204-ubuntu-1204 using the validator key.
       [2015-07-22T04:19:26+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       [2015-07-22T04:19:26+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       resolving cookbooks for run list: ["chef-server", "chef-client::config", "chef-client::service"]
       [2015-07-22T04:19:26+00:00] WARN: Child with name 'dna.json' found in multiple directories: /tmp/kitchen/dna.json and /tmp/kitchen/dna.json
       Synchronizing Cookbooks:
         - chef-server
         - chef-client
         - chef-ingredient
         - cron
         - logrotate
         - windows
         - apt-chef
         - yum-chef
         - chef_handler
         - apt
         - yum
       Compiling Cookbooks...

       ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/omnibus_service_provider.rb
       ================================================================================

       SyntaxError
       -----------
       /opt/chef/embedded/apps/chef/lib/chef/provider.rb:282: syntax error, unexpected '-', expecting ';' or '\n'
            def action_graceful-kill
                                ^
       /opt/chef/embedded/apps/chef/lib/chef/provider.rb:286: syntax error, unexpected keyword_ensure, expecting end-of-input

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/omnibus_service_provider.rb:33:in `block in <class:OmnibusService>'
         /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/omnibus_service_provider.rb:32:in `each'
         /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/omnibus_service_provider.rb:32:in `<class:OmnibusService>'
         /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/omnibus_service_provider.rb:22:in `<class:Provider>'
         /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/omnibus_service_provider.rb:21:in `<class:Chef>'
         /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/omnibus_service_provider.rb:20:in `<top (required)>'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/chef-ingredient/libraries/omnibus_service_provider.rb:

        26:        use_inline_resources
        27:
        28:        def whyrun_supported?
        29:          true
        30:        end
        31:
        32:        %i(start stop restart hup int kill graceful-kill once).each do |sv_command|
        33>>         action sv_command do
        34:            execute "#{omnibus_ctl_command} #{sv_command} #{omnibus_service_name.last}"
        35:          end
        36:        end
        37:
        38:        private
        39:
        40:        def omnibus_ctl_command
        41:          new_resource.ctl_command || chef_ctl_command(omnibus_service_name.first)
        42:        end


       Running handlers:
       [2015-07-22T04:19:47+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-07-22T04:19:47+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 24.364437162 seconds
       [2015-07-22T04:19:47+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2015-07-22T04:19:47+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/provider.rb:282: syntax error, unexpected '-', expecting ';' or '\n'
            def action_graceful-kill
                                ^
       /opt/chef/embedded/apps/chef/lib/chef/provider.rb:286: syntax error, unexpected keyword_ensure, expecting end-of-input
       [2015-07-22T04:19:48+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <server-ubuntu-1204-ubuntu-1204>.
>>>>>> Please see .kitchen/logs/server-ubuntu-1204-ubuntu-1204.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '

sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889
']
>>>>>> ----------------------

cleanup.out:
# Logfile created on 2015-07-21 23:19:40 -0500 by logger.rb/44203
-----> Starting Kitchen (v1.4.2.dev.0)
-----> Destroying <server-ubuntu-1204-ubuntu-1204>...
       EC2 instance <i-8efa1578> destroyed.
       Finished destroying <server-ubuntu-1204-ubuntu-1204> (0m0.77s).
-----> Kitchen is finished. (0m1.22s)
```

**Comment by jaym** [comment]
Looks like this came from https://github.com/chef/chef/pull/3437
