### ISSUE TITLE
Chef should provide a more clear error message upon missing environments

### ISSUE THREAD

**Issue by thomasbiddle** [chef/chef#3711]
Issue: Chef provides an unclear error message (See below) when the error is that an `environments/the_environment.rb` file is non-existent.

Stacktrace:
Command run: `chef-solo -c solo.rb --environment staging`

```
[2015-07-27T04:33:55+00:00] INFO: Forking chef instance to converge...
Starting Chef Client, version 12.5.0.alpha.1
[2015-07-27T04:33:55+00:00] INFO: *** Chef 12.5.0.alpha.1 ***
[2015-07-27T04:33:55+00:00] INFO: Chef-client pid: 7652

================================================================================
Error expanding the run_list:
================================================================================

Unexpected Error:
-----------------
TypeError: no implicit conversion of Array into String


Running handlers:
[2015-07-27T04:33:57+00:00] ERROR: Running exception handlers
Running handlers complete
[2015-07-27T04:33:57+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 2.668491481 seconds
[2015-07-27T04:33:57+00:00] FATAL: Stacktrace dumped to /tmp/app/chef/chef-stacktrace.out
[2015-07-27T04:33:57+00:00] ERROR: no implicit conversion of Array into String
[2015-07-27T04:33:58+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

```
Generated at 2015-07-27 04:33:57 +0000
TypeError: no implicit conversion of Array into String
/opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/environment.rb:249:in `directory?'
/opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/environment.rb:249:in `load_from_file'
/opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/environment.rb:242:in `load'
/opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/node.rb:409:in `apply_expansion_attributes'
/opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/node.rb:398:in `expand!'
/opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/policy_builder/expand_node_object.rb:149:in `expand_run_list'
/opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/policy_builder/expand_node_object.rb:136:in `build_node'
/opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/client.rb:459:in `build_node'
/opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/client.rb:257:in `run'
/opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/application.rb:258:in `fork'
/opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/application.rb:258:in `fork_chef_client'
/opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/application.rb:224:in `block in run_chef_client'
/opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/application.rb:212:in `run_chef_client'
/opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/application/solo.rb:280:in `block in interval_run_chef_client'
/opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/application/solo.rb:269:in `loop'
/opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/application/solo.rb:269:in `interval_run_chef_client'
/opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/application/solo.rb:247:in `run_application'
/opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/lib/chef/application.rb:60:in `run'
/opt/rubies/ruby-2.1.3/lib/ruby/gems/2.1.0/gems/chef-12.5.0.alpha.1/bin/chef-solo:25:in `<top (required)>'
/opt/rubies/ruby-2.1.3/bin/chef-solo:23:in `load'
/opt/rubies/ruby-2.1.3/bin/chef-solo:23:in `<main>
```

node.json file:

```
{
  "run_list": [ "recipe[app_web::default]" ]
}
```

**Comment by thomasbiddle** [comment]
An additional comment:

I noticed that if the environments_path does already exist (In this case, `environments/`) then you get the error:

`Chef::Exceptions::EnvironmentNotFound: Environment 'stagingasdf' could not be loaded from disk`

The original error seems to occur when the directory for `environments_path` does not exist at all.

**Comment by ranjib** [comment]
@thomasbiddle can you test with the current master, im getting expected error message
```sh
chef-solo  -o recipe[test::issue_3711] -c ~/workspace/foss/chef-telemetry/solo.rb   -E xxx
```
```sh
Starting Chef Client, version 12.5.0.current.0
[2015-08-28T00:36:07-07:00] WARN: Run List override has been provided.
[2015-08-28T00:36:07-07:00] WARN: Original Run List: []
[2015-08-28T00:36:07-07:00] WARN: Overridden Run List: [recipe[test::issue_3711]]

================================================================================
Error expanding the run_list:
================================================================================

Unexpected Error:
-----------------
Chef::Exceptions::InvalidEnvironmentPath: Environment path '/home/zenith/workspace/foss/chef-telemetry/environments' is invalid


Running handlers:
[2015-08-28T00:36:07-07:00] ERROR: Running exception handlers
Running handlers complete
[2015-08-28T00:36:07-07:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 2.485440609 seconds
[2015-08-28T00:36:07-07:00] FATAL: Stacktrace dumped to /home/zenith/workspace/foss/chef-telemetry/cache/chef-stacktrace.out
[2015-08-28T00:36:07-07:00] ERROR: Environment path '/home/zenith/workspace/foss/chef-telemetry/environments' is invalid
[2015-08-28T00:36:07-07:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
