### ISSUE TITLE
Bug when creating client that already exists

### ISSUE THREAD

**Issue by spuder** [chef/chef#3717]
If you attempt to create a client, with a name that already exists, you get an unhanded exception. 

```
$ knife client create duplicateuser 
ERROR: knife encountered an unexpected error
This may be a bug in the 'client create' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `[]' for #<Chef::ApiClient:0x007f9f99338e58>
```

Steps to reproduce:

```
knife client create duplicateuser 
knife client create duplicateuser 
```

```
knife --version
Chef: 12.3.0
chef --version
Chef Development Kit Version: 0.6.2
chef-client version: 12.3.0
berks version: 3.2.4
kitchen version: 1.4.0
```

Obligitory -VV output

```
knife client create devops-gitci01 -VV
INFO: Using configuration from /Users/sowen/.chef/knife.rb
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request
DEBUG: Signing the request as sowen
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating PUT to https://devops-chef.ndlab.local/organizations/dev/clients/devops-gitci01
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Content-Type: application/json
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.0;
DEBUG: X-OPS-USERID: sowen
DEBUG: X-OPS-TIMESTAMP: 2015-07-28T17:56:32Z
DEBUG: X-OPS-CONTENT-HASH: xxxxxxxxxxx=
DEBUG: X-OPS-AUTHORIZATION-1: a3vlQFV0Fyhezajyt3BrHxFmWl8G/xxxxxxxxxxx
DEBUG: X-OPS-AUTHORIZATION-2: mXTB+xxxxxxxxxxx
DEBUG: X-OPS-AUTHORIZATION-3: O29fnpzog+pD4wB+xxxxxxxxxxx
DEBUG: X-OPS-AUTHORIZATION-4: 15n2fL6B+LW+1Uy+xxxxxxxxxxx
DEBUG: X-OPS-AUTHORIZATION-5: xxxxxxxxxxx+SSFLqTyvonM
DEBUG: X-OPS-AUTHORIZATION-6: xxxxxxxxxxx==
DEBUG: HOST: chef.example.com:443
DEBUG: X-REMOTE-REQUEST-ID: 435e7823-fc7d-4bcf-9201-xxxxxxxxxxx
DEBUG: Content-Length: 57
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 200 OK
DEBUG: server: openresty/1.7.10.1
DEBUG: date: Tue, 28 Jul 2015 17:56:24 GMT
DEBUG: content-type: application/json
DEBUG: transfer-encoding: chunked
DEBUG: connection: close
DEBUG: x-ops-api-info: flavor=cs;version=12.0.0;oc_erchef=1.6.4
DEBUG: content-encoding: gzip
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: HTTP server did not include a Content-Length header in response, cannot identify truncated downloads.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
/opt/chefdk/embedded/apps/chef/lib/chef/knife/client_create.rb:70:in `run': undefined method `[]' for #<Chef::ApiClient:0x007f84a9031f30> (NoMethodError)
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:422:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:421:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:214:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:142:in `run'
	from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:51:in `load'
	from /opt/chefdk/bin/knife:51:in `<main>'
```

**Comment by ranjib** [comment]
@spuder i cant reproduce this on current chef master. for existing client theres no error on recreation, except the private key is printed no more.

**Comment by lamont-granquist** [comment]
Yeah, i can't repro either.
