### ISSUE TITLE
chef-client 12.4.1 Errno::ENOENT: No such file or directory - git

### ISSUE THREAD

**Issue by loualrid** [chef/chef#3725]
### Version:
12.4.1

### Environment:
Ubuntu 14.04, Application Cookbook, `which git` returns /usr/bin/git

Note: This scenario also occurs on "virgin" deploys to fresh servers as well, but is strangly resolved by adding `retries 1` to the deploy_revision resource. New code cannot be deployed to these servers due to the issue however...

### Scenario:
When using the application cookbook via the application_ruby cookbook to deploy _new_ code to the server with chef-client runs, the run fails with the `Errno::ENOENT: No such file or directory - git` (exact trace to be included below)

### Steps to Reproduce:
Berksfile:
```
source 'https://api.berkshelf.com'
metadata

cookbook 'nginx'
cookbook 'database', git: 'git@github.com:opscode-cookbooks/database'
cookbook 'postgresql'
cookbook 'application_ruby', git: 'https://github.com/loualrid/application_ruby.git', branch: 'development'
cookbook 'puma', git: 'git@github.com:yourabi/chef-puma.git'
cookbook 'application', git: 'git@github.com:SocialCentivPublic/application.git', branch: 'development'
cookbook 'rvm', git: 'git@github.com:martinisoft/chef-rvm.git', tag: 'v0.9.4' 
cookbook 'simple_iptables', git: 'git@github.com:rtkwlf/cookbook-simple-iptables.git'
```
Setup a basic ruby app with application cookbook and application_ruby cookbook and attempt to deploy / update code

### Expected Result:
I was expecting for the deploy resource to update the "current" directory of the repository on the server to the latest revision of the master branch

### Actual Result:
An error is raised after chef specifies its target revision and thus the code in the target revision is never symlinked to the "current". The release folder containing the new code is not created either.

Trace:
```
[2015-07-29T12:06:25-04:00] DEBUG: Providers for generic deploy_revision resource enabled on node include: [Chef::Provider::Deploy::Revision]
[2015-07-29T12:06:25-04:00] DEBUG: Provider for action deploy on resource deploy_revision[locus_core] is Chef::Provider::Deploy::Revision
[2015-07-29T12:06:25-04:00] DEBUG: deploy_revision[locus_core] finding current git revision
[2015-07-29T12:06:25-04:00] DEBUG: deploy_revision[locus_core] resolving remote reference
[2015-07-29T12:06:26-04:00] DEBUG: deploy_revision[locus_core] not creating /var/www/vhosts/locus_core because it already exists
[2015-07-29T12:06:26-04:00] DEBUG: deploy_revision[locus_core] not creating /var/www/vhosts/locus_core/shared because it already exists
[2015-07-29T12:06:26-04:00] DEBUG: deploy_revision[locus_core] finding current git revision
[2015-07-29T12:06:26-04:00] DEBUG: deploy_revision[locus_core] current revision: 6b7c82800430c3dccd7fbd19dc49adc4c64bf923 target revision: 562be586947de9b334ad7ffbd98f8aa801f6be54
[2015-07-29T12:06:26-04:00] DEBUG: deploy_revision[locus_core] configuring remote tracking branches for repository https://*************************************************************@github.com/TheLocusCo/locus_core.git at remote origin
[2015-07-29T12:06:26-04:00] WARN: Error on deploying /var/www/vhosts/locus_core/releases/562be586947de9b334ad7ffbd98f8aa801f6be54: No such file or directory - git
[2015-07-29T12:06:26-04:00] INFO: deploy_revision[locus_core] rolling back to previous release /var/www/vhosts/locus_core/releases/6b7c82800430c3dccd7fbd19dc49adc4c64bf923
[2015-07-29T12:06:26-04:00] INFO: deploy_revision[locus_core] purged directories in checkout log
[2015-07-29T12:06:26-04:00] INFO: deploy_revision[locus_core] created directories before symlinking: 
[2015-07-29T12:06:26-04:00] INFO: deploy_revision[locus_core] linked shared paths into current release: config/database.yml => config/database.yml, log => log
[2015-07-29T12:06:26-04:00] INFO: deploy_revision[locus_core] made pre-migration symlinks
[2015-07-29T12:06:27-04:00] INFO: deploy_revision[locus_core] set user to deploy
[2015-07-29T12:06:27-04:00] INFO: deploy_revision[locus_core] set group to www-data
[2015-07-29T12:06:27-04:00] INFO: deploy_revision[locus_core] linked release /var/www/vhosts/locus_core/releases/6b7c82800430c3dccd7fbd19dc49adc4c64bf923 into production at /var/www/vhosts/locus_core/current
[2015-07-29T12:06:27-04:00] INFO: deploy_revision[locus_core] set user to deploy
[2015-07-29T12:06:27-04:00] INFO: deploy_revision[locus_core] set group to www-data
[2015-07-29T12:06:27-04:00] INFO: deploy_revision[locus_core] updated symlinks
[2015-07-29T12:06:27-04:00] INFO: deploy_revision[locus_core] restarting with previous release
[2015-07-29T12:06:27-04:00] INFO: deploy_revision[locus_core] restarting app with embedded recipe
[2015-07-29T12:06:27-04:00] INFO: Removing failed deploy /var/www/vhosts/locus_core/releases/562be586947de9b334ad7ffbd98f8aa801f6be54

================================================================================
Error executing action `deploy` on resource 'deploy_revision[locus_core]'
================================================================================

Errno::ENOENT
-------------
No such file or directory - git

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/application/providers/default.rb

130:   @deploy_resource = send(new_resource.strategy.to_sym, new_resource.name) do
131:     action force ? :force_deploy : :deploy
132:     scm_provider new_resource.scm_provider
133:     retries new_resource.retries
134:     checkout_branch "deploy"
135:     revision new_resource.revision
136:     repository new_resource.repository
137:     enable_submodules new_resource.enable_submodules
138:     user new_resource.owner
139:     group new_resource.group
140:     keep_releases new_resource.keep_releases
141:     deploy_to new_resource.path
142:     ssh_wrapper "#{new_resource.path}/deploy-ssh-wrapper" if new_resource.deploy_key
143:     shallow_clone new_resource.shallow_clone
144:     rollback_on_error new_resource.rollback_on_error
145:     all_environments = ([new_resource.environment]+new_resource.sub_resources.map{|res| res.environment}).inject({}){|acc, val| acc.merge(val)}
146:     environment all_environments
147:     migrate new_resource.migrate
148:     all_migration_commands = ([new_resource.migration_command]+new_resource.sub_resources.map{|res| res.migration_command}).select{|cmd| cmd && !cmd.empty?}
149:     migration_command all_migration_commands.join(' && ')
150:     restart_command do
151:       ([new_resource]+new_resource.sub_resources).each do |res|
152:         cmd = res.restart_command
153:         if cmd.is_a? Proc
154:           app_provider.deploy_provider.instance_eval(&cmd) # @see libraries/default.rb
155:         elsif cmd && !cmd.empty?
156:           execute cmd do
157:             user new_resource.owner
158:             group new_resource.group
159:             environment all_environments
160:           end
161:         end
162:       end
163:     end
164:     purge_before_symlink (new_resource.purge_before_symlink + new_resource.sub_resources.map(&:purge_before_symlink)).flatten

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/application/providers/default.rb:130:in `run_deploy'

deploy_revision("locus_core") do
  action [:deploy]
  retries 1
  retry_delay 2
  default_guard_interpreter :default
  deploy_to "/var/www/vhosts/locus_core"
  environment {"RAILS_ENV"=>"production", "PATH"=>"/home/deploy/.rvm/gems/ruby-2.2.1/bin:/home/deploy/.rvm/gems/ruby-2.2.1@global/bin:/home/deploy/.rvm/rubies/ruby-2.2.1:/home/deploy/.rvm/bin:usr/local/sbin:usr/local/bin:usr/bin:usr/sbin:/sbin:usr/games:/bin:usr/local/games:", "GEM_PATH"=>"/home/deploy/.rvm/gems/ruby-2.2.1:/home/deploy/.rvm/gems/ruby-2.2.1@global", "GEM_HOME"=>"/home/deploy/.rvm/gems/ruby-2.2.1"}
  repository_cache "cached-copy"
  purge_before_symlink ["log"]
  symlink_before_migrate {"database.yml"=>"config/database.yml"}
  symlinks {"config/database.yml"=>"config/database.yml", "log"=>"log"}
  revision "master"
  rollback_on_error true
  remote "origin"
  scm_provider Chef::Provider::Git
  keep_releases 5
  enable_checkout true
  checkout_branch "master"
  declared_type :deploy_revision
  cookbook_name "LocusDeploy"
  repo "https://*****************************************************@github.com/TheLocusCo/locus_core.git"
  user "deploy"
  group "www-data"
  git_ssh_wrapper "/var/www/vhosts/locus_core/deploy-ssh-wrapper"
  migration_command "/etc/profile.d/rvm.sh && /home/deploy/.rvm/gems/ruby-2.2.1@global/bin/bundle exec rake db:migrate"
  restart_command #<Proc:0x0000000ac45d60@/var/chef/cache/cookbooks/application/providers/default.rb:150>
  before_migrate #<Proc:0x0000000ac449d8@/var/chef/cache/cookbooks/application/providers/default.rb:170>
  before_symlink #<Proc:0x0000000ac44820@/var/chef/cache/cookbooks/application/providers/default.rb:173>
  before_restart #<Proc:0x0000000ac44668@/var/chef/cache/cookbooks/application/providers/default.rb:176>
  after_restart #<Proc:0x0000000ac444b0@/var/chef/cache/cookbooks/application/providers/default.rb:179>
  shared_path "/var/www/vhosts/locus_core/shared"
  destination "/var/www/vhosts/locus_core/shared/cached-copy"
  current_path "/var/www/vhosts/locus_core/current"
end

[2015-07-29T12:06:27-04:00] INFO: Running queued delayed notifications before re-raising exception
[2015-07-29T12:06:27-04:00] DEBUG: Re-raising exception: Errno::ENOENT - deploy_revision[locus_core] (/var/chef/cache/cookbooks/application/providers/default.rb line 130) had an error: Errno::ENOENT: No such file or directory - git
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.1.0/lib/mixlib/shellout/unix.rb:338:in `exec'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.1.0/lib/mixlib/shellout/unix.rb:338:in `block in fork_subprocess'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.1.0/lib/mixlib/shellout/unix.rb:316:in `fork'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.1.0/lib/mixlib/shellout/unix.rb:316:in `fork_subprocess'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.1.0/lib/mixlib/shellout/unix.rb:93:in `run_command'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.1.0/lib/mixlib/shellout.rb:259:in `run_command'
  /opt/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:97:in `shell_out_command'
  /opt/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:50:in `shell_out'
  /opt/chef/embedded/apps/chef/lib/chef/mixin/shell_out.rb:55:in `shell_out!'
  /opt/chef/embedded/apps/chef/lib/chef/provider/git.rb:195:in `block in setup_remote_tracking_branches'
  /opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `call'
  /opt/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `add_action'
  /opt/chef/embedded/apps/chef/lib/chef/provider.rb:175:in `converge_by'
  /opt/chef/embedded/apps/chef/lib/chef/provider/git.rb:191:in `setup_remote_tracking_branches'
  /opt/chef/embedded/apps/chef/lib/chef/provider/git.rb:181:in `fetch_updates'
  /opt/chef/embedded/apps/chef/lib/chef/provider/git.rb:97:in `action_sync'
  /opt/chef/embedded/apps/chef/lib/chef/provider.rb:140:in `run_action'
  /opt/chef/embedded/apps/chef/lib/chef/provider/deploy.rb:259:in `run_scm_sync'
  /opt/chef/embedded/apps/chef/lib/chef/provider/deploy.rb:254:in `update_cached_repo'
  /opt/chef/embedded/apps/chef/lib/chef/provider/deploy.rb:155:in `deploy'
  /opt/chef/embedded/apps/chef/lib/chef/provider/deploy.rb:110:in `block in action_deploy'
  /opt/chef/embedded/apps/chef/lib/chef/provider/deploy.rb:443:in `with_rollback_on_error'
  /opt/chef/embedded/apps/chef/lib/chef/provider/deploy.rb:109:in `action_deploy'
  /opt/chef/embedded/apps/chef/lib/chef/provider/deploy/revision.rb:39:in `action_deploy'
  /opt/chef/embedded/apps/chef/lib/chef/provider.rb:140:in `run_action'
  /opt/chef/embedded/apps/chef/lib/chef/resource.rb:584:in `run_action'
  /opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
  /opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
  /opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
  /opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
  /opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
  /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
  /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
  /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
  /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
  /opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
  /opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
  /opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:654:in `block in converge'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:649:in `catch'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:649:in `converge'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:688:in `converge_and_save'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:269:in `run'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:270:in `block in fork_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:224:in `block in run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:212:in `run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
  /opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
  /usr/bin/chef-client:55:in `load'
  /usr/bin/chef-client:55:in `<main>'
[2015-07-29T12:06:27-04:00] ERROR: Running exception handlers
```

**Comment by coderanger** [comment]
This is a bug (more or less) in the old application cookbook. Chef includes a `git` resource, but that resource doesn't work unless git is actually installed and doing that is out of scope for core Chef. The new `application_git` plugin cookbook for the app* framework does correctly use the `git` cookbook to make sure things are installed.
