### ISSUE TITLE
chef-client 12.0.0 run failure on AIX 7100-00-03-1115

### ISSUE THREAD

**Issue by frederickywu** [chef/chef#3739]
chef-client run fails on some AIX clients.  Excerpt from chef-client.log:

[2015-07-30T02:57:35+00:00] DEBUG: Saving the current state of node <hostname>
[2015-07-30T02:57:35+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
[2015-07-30T02:57:35+00:00] DEBUG: Re-raising exception: Chef::Exceptions::JSON::EncodeError - Unknown YAJL Error, please report this as a bug
/opt/chef/embedded/apps/chef/lib/chef/json_compat.rb:107:in `rescue in to_json'
  /opt/chef/embedded/apps/chef/lib/chef/json_compat.rb:104:in `to_json'
  /opt/chef/embedded/apps/chef/lib/chef/http/json_input.rb:35:in `handle_request'
  /opt/chef/embedded/apps/chef/lib/chef/http.rb:222:in `block in apply_request_middleware'
  /opt/chef/embedded/apps/chef/lib/chef/http.rb:220:in `each'
  /opt/chef/embedded/apps/chef/lib/chef/http.rb:220:in `inject'
  /opt/chef/embedded/apps/chef/lib/chef/http.rb:220:in `apply_request_middleware'
  /opt/chef/embedded/apps/chef/lib/chef/http.rb:141:in `request'
  /opt/chef/embedded/apps/chef/lib/chef/http.rb:118:in `put'
  /opt/chef/embedded/apps/chef/lib/chef/node.rb:512:in `save'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:257:in `save_updated_node'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:403:in `run'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:261:in `block in fork_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:215:in `block in run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:201:in `run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:353:in `block in interval_run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:343:in `loop'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:343:in `interval_run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:333:in `run_application'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:58:in `run'
  /opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
  /usr/bin/chef-client:40:in `load'
  /usr/bin/chef-client:40:in `<main>'
[2015-07-30T02:57:35+00:00] ERROR: Running exception handlers
[2015-07-30T02:57:35+00:00] ERROR: Creating JSON exception report
[2015-07-30T02:57:35+00:00] ERROR: Report handler Chef::Handler::JsonFile raised #<Chef::Exceptions::JSON::EncodeError: Unknown YAJL Error, please report this as a bug>
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/json_compat.rb:107:in `rescue in to_json'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/json_compat.rb:104:in `to_json'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/node.rb:407:in `to_json'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.3.1/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.3.1/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.3.1/lib/ffi_yajl/encoder.rb:21:in `do_yajl_encode'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.3.1/lib/ffi_yajl/encoder.rb:21:in `encode'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.3.1/lib/ffi_yajl/encoder.rb:27:in `encode'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/json_compat.rb:105:in `to_json'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/json_compat.rb:116:in `to_json_pretty'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler/json_file.rb:50:in `block in report'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler/json_file.rb:43:in `open'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler/json_file.rb:43:in `report'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:226:in `run_report_unsafe'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:214:in `run_report_safely'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:118:in `block in run_exception_handlers'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:117:in `each'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:117:in `run_exception_handlers'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:127:in `block in <class:Handler>'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:135:in `call'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:135:in `block in run_failed'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:134:in `each'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:134:in `run_failed'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:421:in `rescue in run'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:433:in `run'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:261:in `block in fork_chef_client'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork_chef_client'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:215:in `block in run_chef_client'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:201:in `run_chef_client'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:353:in `block in interval_run_chef_client'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:343:in `loop'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:343:in `interval_run_chef_client'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:333:in `run_application'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:58:in `run'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
[2015-07-30T02:57:35+00:00] ERROR: /usr/bin/chef-client:40:in `load'
[2015-07-30T02:57:35+00:00] ERROR: /usr/bin/chef-client:40:in `<main>'
[2015-07-30T02:57:35+00:00] ERROR: Report handler Chef::Handler::ErrorReport raised #<Chef::Exceptions::JSON::EncodeError: Unknown YAJL Error, please report this as a bug>
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/json_compat.rb:107:in `rescue in to_json'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/json_compat.rb:104:in `to_json'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/node.rb:407:in `to_json'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.3.1/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.3.1/lib/ffi_yajl/encoder.rb:21:in `ffi_yajl'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.3.1/lib/ffi_yajl/encoder.rb:21:in `do_yajl_encode'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.3.1/lib/ffi_yajl/encoder.rb:21:in `encode'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ffi-yajl-1.3.1/lib/ffi_yajl/encoder.rb:27:in `encode'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/json_compat.rb:105:in `to_json'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/json_compat.rb:116:in `to_json_pretty'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler/error_report.rb:27:in `report'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:226:in `run_report_unsafe'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:214:in `run_report_safely'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:118:in `block in run_exception_handlers'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:117:in `each'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:117:in `run_exception_handlers'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/handler.rb:127:in `block in <class:Handler>'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:135:in `call'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:135:in `block in run_failed'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:134:in `each'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:134:in `run_failed'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:421:in `rescue in run'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/client.rb:433:in `run'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:261:in `block in fork_chef_client'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork_chef_client'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:215:in `block in run_chef_client'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:201:in `run_chef_client'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:353:in `block in interval_run_chef_client'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:343:in `loop'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:343:in `interval_run_chef_client'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:333:in `run_application'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/lib/chef/application.rb:58:in `run'
[2015-07-30T02:57:35+00:00] ERROR: /opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
[2015-07-30T02:57:35+00:00] ERROR: /usr/bin/chef-client:40:in `load'
[2015-07-30T02:57:35+00:00] ERROR: /usr/bin/chef-client:40:in `<main>'
[2015-07-30T02:57:35+00:00] ERROR: Exception handlers complete
[2015-07-30T02:57:35+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-07-30T02:57:35+00:00] DEBUG: Chef::Exceptions::JSON::EncodeError: Unknown YAJL Error, please report this as a bug
/opt/chef/embedded/apps/chef/lib/chef/json_compat.rb:107:in `rescue in to_json'
/opt/chef/embedded/apps/chef/lib/chef/json_compat.rb:104:in `to_json'
/opt/chef/embedded/apps/chef/lib/chef/http/json_input.rb:35:in `handle_request'
/opt/chef/embedded/apps/chef/lib/chef/http.rb:222:in `block in apply_request_middleware'
/opt/chef/embedded/apps/chef/lib/chef/http.rb:220:in `each'
/opt/chef/embedded/apps/chef/lib/chef/http.rb:220:in `inject'
/opt/chef/embedded/apps/chef/lib/chef/http.rb:220:in `apply_request_middleware'
/opt/chef/embedded/apps/chef/lib/chef/http.rb:141:in `request'
/opt/chef/embedded/apps/chef/lib/chef/http.rb:118:in `put'
/opt/chef/embedded/apps/chef/lib/chef/node.rb:512:in `save'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:257:in `save_updated_node'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:403:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:261:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:249:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:215:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:201:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:353:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:343:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:343:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:333:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:40:in `load'
/usr/bin/chef-client:40:in `<main>'
[2015-07-30T02:57:35+00:00] DEBUG: Server doesn't support resource history, skipping resource report.
[2015-07-30T02:57:35+00:00] ERROR: Unknown YAJL Error, please report this as a bug
[2015-07-30T02:57:35+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by juliandunn** [comment]
Looks like this is being thrown by `ffi-yajl` -- ideas, @lamont-granquist?

**Comment by lamont-granquist** [comment]
This is from Chef 12.0.0 and ffi-yajl 1.3.1 and there's been a lot of bugs fixed since December.  

I recall a contribution that fixed the error message to be correct and not an "internal error" and then I fixed the subsequent problem, but I can't tell you offhand which versions, but it should be fixed in 12.4.1 and the latest ffi-yajl.

**Comment by frederickywu** [comment]
Thank you, we will try 12.4.1 and the latest yajl


Fred

Fred Wu
IBM Research
914-945-2414 t/l 862-2414
