### ISSUE TITLE
Exception after tried to pre-warm chef-client cache with a cookbooks.tar.gz

### ISSUE THREAD

**Issue by gionn** [chef/chef#3807]
As per #3803, I've tried to unpack my cookbooks.tar.gz directly in the cookbooks cache folder of chef-client, in the hope of faster startup times (it looks like test-kitchen is doing it https://github.com/test-kitchen/test-kitchen/pull/620), but I get an exception:

```
[2015-08-21T09:42:43+00:00] INFO: Removing cookbooks/apache2/.rubocop.yml from the cache; its cookbook is no longer needed on this client.
[2015-08-21T09:42:43+00:00] INFO: Removing cookbooks/apache2/test/fixtures/cookbooks/apache2_test/.gitignore from the cache; its cookbook is no longer needed on this client.
[2015-08-21T09:42:43+00:00] INFO: Removing cookbooks/apache2/.kitchen.cloud.yml from the cache; its cookbook is no longer needed on this client.
[2015-08-21T09:42:43+00:00] INFO: Removing cookbooks/docker/.kitchen.yml from the cache; its cookbook is no longer needed on this client.
[2015-08-21T09:42:43+00:00] INFO: Removing cookbooks/docker/.rubocop.yml from the cache; its cookbook is no longer needed on this client.
[2015-08-21T09:42:43+00:00] INFO: Removing cookbooks/gdebi/.kitchen.yml from the cache; its cookbook is no longer needed on this client.
[2015-08-21T09:42:43+00:00] INFO: Removing cookbooks/golang/.kitchen.yml from the cache; its cookbook is no longer needed on this client.
[2015-08-21T09:42:43+00:00] INFO: Removing cookbooks/cd-rails/.kitchen.yml from the cache; its cookbook is no longer needed on this client.

================================================================================
Error Syncing Cookbooks:
================================================================================

Unexpected Error:
-----------------
NoMethodError: private method `select' called for nil:NilClass

[2015-08-21T09:51:08+00:00] DEBUG: Re-raising exception: NoMethodError - private method `select' called for nil:NilClass
/opt/chef/embedded/apps/chef/lib/chef/cookbook/synchronizer.rb:204:in `block in remove_deleted_files'
  /opt/chef/embedded/apps/chef/lib/chef/cookbook/synchronizer.rb:198:in `each'
  /opt/chef/embedded/apps/chef/lib/chef/cookbook/synchronizer.rb:198:in `remove_deleted_files'
  /opt/chef/embedded/apps/chef/lib/chef/cookbook/synchronizer.rb:225:in `clear_obsoleted_cookbooks'
  /opt/chef/embedded/apps/chef/lib/chef/cookbook/synchronizer.rb:146:in `sync_cookbooks'
  /opt/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:196:in `sync_cookbooks'
  /opt/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:76:in `setup_run_context'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:486:in `setup_run_context'
  /opt/chef/embedded/apps/chef/lib/chef/client.rb:266:in `run'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:270:in `block in fork_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:224:in `block in run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:212:in `run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
  /opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
  /opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
  /opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
  /usr/bin/chef-client:55:in `load'
  /usr/bin/chef-client:55:in `<main>'
```

I've noticed that unused cookbooks directories have not been deleted from the cache, just the files.

**Comment by lamont-granquist** [comment]
Yeah that's probably the wrong way to solve this problem

**Comment by lamont-granquist** [comment]
We've been addressing the perf issues with ChefFS/chef-zero.  Gonna close this, since its the wrong way to go about fixing it...
