### ISSUE TITLE
Service resource fails if systemd unit files are not present on ubuntu 15.04

### ISSUE THREAD

**Issue by ranjib** [chef/chef#3934]
```ruby
service 'go-agent' do
    action [:enable, :start]
end
```
trace
```sh
Generated at 2015-09-20 19:53:02 -0700
NoMethodError: service[go-agent] (go_cd::agent line 76) had an error: NoMethodError: undefined method `+' for false:FalseClass
/opt/chef/embedded/apps/chef/lib/chef/platform/service_helpers.rb:134:in `platform_has_systemd_unit?'
/opt/chef/embedded/apps/chef/lib/chef/platform/service_helpers.rb:98:in `config_for_service'
/opt/chef/embedded/apps/chef/lib/chef/provider/service/debian.rb:35:in `supports?'
/opt/chef/embedded/apps/chef/lib/chef/provider_resolver.rb:79:in `block in supported_handlers'
/opt/chef/embedded/apps/chef/lib/chef/provider_resolver.rb:79:in `select'
/opt/chef/embedded/apps/chef/lib/chef/provider_resolver.rb:79:in `supported_handlers'
/opt/chef/embedded/apps/chef/lib/chef/provider_resolver.rb:91:in `prioritized_handlers'
/opt/chef/embedded/apps/chef/lib/chef/provider_resolver.rb:116:in `maybe_dynamic_provider_resolution'
/opt/chef/embedded/apps/chef/lib/chef/provider_resolver.rb:61:in `resolve'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:1619:in `provider_for_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:582:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:654:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:649:in `catch'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:649:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:688:in `converge_and_save' 
/opt/chef/embedded/apps/chef/lib/chef/client.rb:269:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:224:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:212:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:55:in `load'
/usr/bin/chef-client:55:in `<main>'

```

**Comment by jkeiser** [comment]
Marking 12.5.0 because Ranjib's PR was marked 12.5.0
