### ISSUE TITLE
reboot_now crashes chef

### ISSUE THREAD

**Issue by spuder** [chef/chef#4051]
If you attempt to use the `reboot_now` action on the `reboot` resource in windows, chef will crash

    chef-apply ~/reboot.rb

```ruby
reboot 'Restart Computer' do
  action :nothing
end

file 'c:\\foo.txt' do
  action :create
  notifies :reboot_now, 'reboot[Restart Computer]', :immediately
end

file 'c:\\bar.txt' do
  action :create
  notifies :reboot_now, 'reboot[Restart Computer]', :immediately
end
```

```powershell
PS C:\Users\sowen\cookbooks\nd-web> Get-Content C:\chef\cache\chef-stacktrace.out
Generated at 2015-10-12 12:15:37 -0400
ArgumentError: reboot[Restart Computer] ((chef-apply cookbook)::(chef-apply recipe) line 1) had an erro r: ArgumentError: uncaught throw :end_client_run_early
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/reboot.rb:58:in `throw'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/reboot.rb:58:in `block in action_reboot_now'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `call'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `add_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider.rb:175:in `converge_by'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/reboot.rb:55:in `action_reboot_now'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider.rb:140:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:584:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:57:in `block in run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:55:in `each'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:55:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execut e_each_resource'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_itera tor_block'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_i ndex'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_re source'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/apply.rb:171:in `run_chef_recipe'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/apply.rb:180:in `run_application'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/apply.rb:193:in `run'
C:/opscode/chef/embedded/apps/chef/bin/chef-apply:25:in `<top (required)>'
C:/opscode/chef/bin/chef-apply:67:in `load'
C:/opscode/chef/bin/chef-apply:67:in `<main>'
```

These examples are taken right from the documentation.

https://docs.chef.io/resource_reboot.html

Chef: 12.4.1
Windows Server 2012 R2

**Comment by spuder** [comment]
Furthermore, If I move this recipe to a cookbook, then call it with `chef-client -z`, it doesn't crash, but it doesn't reboot either. 

    chef-client -z -r 'recipe[foo::reboot]' -c c:\chef\client.rb

client.rb
```ruby
log_level        :info
log_location     STDOUT

chef_server_url  "https://devops-chef.ndlab.local/organizations/dev"
validation_client_name "dev-validator"
client_key        "c:/chef/client.pem"
validation_key    "c:/chef/validation.pem"

file_cache_path   "c:/chef/cache"
file_backup_path  "c:/chef/backup"
cache_options     ({:path => "c:/chef/cache/checksums", :skip_expires => true})

node_name "dvp-chefzero"
trusted_certs_dir "C:/chef/trusted_certs"

cookbook_path "c:/Users/sowen/cookbooks/"
role_path "c:/Users/sowen/chef-repo-lab/roles/"
environment_path "c:/Users/sowen/chef-repo-lab/environments/"
data_bag_path "c:/Users/sowen/databags"
````

**Comment by spuder** [comment]
I reproduced again with the latest version of chef (12.5.1) with the exact same results. 

chef-apply = crash
chef-client -z = no crash, but system never reboots

**Comment by spuder** [comment]
This was actually a problem with the client.rb file. The reboot resource does in fact work properly. 

The chef-apply crash still stands and is documented in the linked issue.
