### ISSUE TITLE
undefined method `make_child_entry' in knife upload

### ISSUE THREAD

**Issue by glenjamin** [chef/chef#4070]
Since updating to chefdk 0.9.0 we've been seeing this error intermittently when running `knife upload`.

I'm trying to pin down the exact steps to reproduce, but wanted to get something recorded for now.

The error occurs when a cookbook has some changes to upload, and can be fixed by deleting it from the server, or uploading with `--force`.

```
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/file_system/base_fs_object.rb:100:in `child': undefined method `make_child_entry' for #<Chef::ChefFS::FileSystem::CookbookSubdir:0x007f88858eef08> (NoMethodError)
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/file_system.rb:234:in `block in child_pairs'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/file_system.rb:232:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/file_system.rb:232:in `child_pairs'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/command_line.rb:145:in `diff_entries'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/command_line.rb:146:in `block in diff_entries'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `call'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `process_input'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:257:in `process_one'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:195:in `each_with_exceptions_unordered'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:214:in `each_with_exceptions_ordered'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:68:in `each_with_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:50:in `each_with_input'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:37:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/flatten_enumerable.rb:16:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/flatten_enumerable.rb:25:in `flatten'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/flatten_enumerable.rb:17:in `block in each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:38:in `block in each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:58:in `block in each_with_input'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:218:in `block in each_with_exceptions_ordered'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:188:in `each_with_exceptions_unordered'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:214:in `each_with_exceptions_ordered'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:68:in `each_with_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:50:in `each_with_input'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:37:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/flatten_enumerable.rb:16:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/file_system/cookbook_dir.rb:159:in `compare_to'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/file_system.rb:243:in `compare'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/file_system.rb:343:in `copy_entries'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/file_system.rb:360:in `block in copy_entries'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `call'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `process_input'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:257:in `process_one'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer.rb:93:in `call'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer.rb:93:in `worker_loop'
```

**Comment by goacid** [comment]
+1
Thanks for --force

**Comment by glenjamin** [comment]
I've also found that `knife cookbook upload` is able to workaround the error.

**Comment by jfbibeau** [comment]
Same issue with Chef 12.5.1, when trying to do `knife upload <cookbook>`:

```
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/file_system/base_fs_object.rb:99:in `child': undefined method `make_child_entry' for #<Chef::ChefFS::FileSystem::CookbookSubdir:0x007fd339289600> (NoMethodError)
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/file_system.rb:234:in `block in child_pairs'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/file_system.rb:232:in `each'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/file_system.rb:232:in `child_pairs'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/command_line.rb:145:in `diff_entries'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/command_line.rb:146:in `block in diff_entries'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `call'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `process_input'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:257:in `process_one'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer.rb:93:in `call'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/chef_fs/parallelizer.rb:93:in `worker_loop'
```

Workaround of doing `knife cookbook upload <name>` worked fine.

**Comment by abrooke** [comment]
Confirmed breaking in ChefDK 0.9.0 and Chef 12.5.1.
