### ISSUE TITLE
chef-apply crashes if using the `reboot` resource

### ISSUE THREAD

**Issue by spuder** [chef/chef#4088]
Splitting issue #4051 into two, easier to understand issues. 

If you try and use the reboot resource with `chef-apply` then it will crash. 
Understandably, `chef-apply` really isn't meant to be used outside of files, templates, ect.. (according to cheeseplus in the irc). 

Nevertheless, crashes are bad any way you look at them. 

Steps to reproduce

Windows Server 2012 R2
Chef 12.5.1

``` ruby
reboot 'foo' do
  action :reboot_now
end
```

```
chef-apply foo.rb
```

```
Get-Content C:\chef\cache\chef-stacktrace.out
Generated at 2015-10-12 12:15:37 -0400
ArgumentError: reboot[Restart Computer] ((chef-apply cookbook)::(chef-apply recipe) line 1) had an erro r: ArgumentError: uncaught throw :end_client_run_early
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/reboot.rb:58:in `throw'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/reboot.rb:58:in `block in action_reboot_now'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `call'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `add_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider.rb:175:in `converge_by'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/reboot.rb:55:in `action_reboot_now'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider.rb:140:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:584:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:57:in `block in run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:55:in `each'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:55:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execut e_each_resource'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_itera tor_block'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_i ndex'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_re source'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/apply.rb:171:in `run_chef_recipe'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/apply.rb:180:in `run_application'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/apply.rb:193:in `run'
C:/opscode/chef/embedded/apps/chef/bin/chef-apply:25:in `<top (required)>'
C:/opscode/chef/bin/chef-apply:67:in `load'
```

**Comment by lamont-granquist** [comment]
I can replicate this under test-kitchen and chef-zero

```
-----> Starting Kitchen (v1.6.0)
-----> Converging <default-windows-2008r2>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.3.0...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (12.1.2)

       Transferring files to <default-windows-2008r2>
       Starting Chef Client, version 12.1.2
       [2016-03-11T12:10:49-08:00] WARN: Child with name 'dna.json' found in multiple directories: C:/Users/vagrant/AppData/Local/Temp/kitchen/dna.json and C:/Users/vagrant/AppData/Local/Temp/kitchen/dna.json
       resolving cookbooks for run list: ["unit::default"]
       Synchronizing Cookbooks:
         - unit
         - compat_resource
         - chef_hostname
       Compiling Cookbooks...
       Recipe: unit::default
         * hostname[foobar.example.com] action set
           * ohai[reload hostname] action nothing (skipped due to action :nothing)
           * cookbook_file[C:\Program Files\Amazon\Ec2ConfigService\Settings\config.xml] action create (skipped due to only_if)
           * powershell_script[set hostname] action run
             - execute "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File "C:/Users/vagrant/AppData/Local/Temp/chef-script20160311-1236-acr9t1.ps1"
           * reboot[setting hostname] action reboot_now[2016-03-11T12:10:50-08:00] WARN: Rebooting system immediately, requested by 'setting hostname'


             ================================================================================
             Error executing action `reboot_now` on resource 'reboot[setting hostname]'
             ================================================================================

             ArgumentError
             -------------
             uncaught throw :end_client_run_early

             Resource Declaration:
             ---------------------
             # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chef_hostname/resources/hostname.rb

             122:     reboot "setting hostname" do
             123:       reason "chef setting hostname"
             124:       action :reboot_now
             125:       only_if { new_resource.windows_reboot }
             126:     end
             127:   end

             Compiled Resource:
             ------------------
             # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chef_hostname/resources/hostname.rb:122:in `block in class_from_file'

             reboot("setting hostname") do
        provider Chef::Provider::Reboot
        action [:reboot_now]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        reason "chef setting hostname"
        delay_mins 0
        declared_type :reboot
        cookbook_name "unit"
        only_if { #code block }
             end


           ================================================================================
           Error executing action `set` on resource 'hostname[foobar.example.com]'
           ================================================================================

           ArgumentError
           -------------
           reboot[setting hostname] (C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chef_hostname/resources/hostname.rb line 122) had an error: ArgumentError: uncaught throw :end_client_run_early

           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/unit/recipes/default.rb

             7: hostname "foobar.example.com"
             8:

           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/unit/recipes/default.rb:7:in `from_file'

           chef_hostname_hostname("foobar.example.com") do
             action [:set]
             updated true
             updated_by_last_action true
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :hostname
             cookbook_name "unit"
             recipe_name "default"
             compile_time true
             hostname "foobar.example.com"
             windows_reboot true
           end


         ================================================================================
         Recipe Compile Error in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/unit/recipes/default.rb
         ================================================================================

         ArgumentError
         -------------
         hostname[foobar.example.com] (unit::default line 7) had an error: ArgumentError: reboot[setting hostname] (C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chef_hostname/resources/hostname.rb line 122) had an error: ArgumentError: uncaught throw :end_client_run_early

         Cookbook Trace:
         ---------------
           C:/opscode/chef/embedded/apps/chef/lib/chef/provider/reboot.rb:57:in `throw'
           C:/opscode/chef/embedded/apps/chef/lib/chef/provider/reboot.rb:57:in `block in action_reboot_now'
           C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `call'
           C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `add_action'
           C:/opscode/chef/embedded/apps/chef/lib/chef/provider.rb:180:in `converge_by'
           C:/opscode/chef/embedded/apps/chef/lib/chef/provider/reboot.rb:54:in `action_reboot_now'
           C:/opscode/chef/embedded/apps/chef/lib/chef/provider.rb:145:in `run_action'
           C:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:561:in `run_action'
           C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
           C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
           C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
           C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
           C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
           C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
           C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
           C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
           C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
           C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
           C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
           C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
           C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:123:in `compile_and_converge_action'
           (eval):2:in `action_set'
           C:/opscode/chef/embedded/apps/chef/lib/chef/provider.rb:149:in `run_action'
           C:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:561:in `run_action'
           C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chef_hostname/resources/hostname.rb:134:in `block in after_created'
           C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chef_hostname/resources/hostname.rb:133:in `each'
           C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chef_hostname/resources/hostname.rb:133:in `after_created'
           C:/opscode/chef/embedded/apps/chef/lib/chef/resource_builder.rb:82:in `build'
           C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/dsl/declare_resource.rb:113:in `build_resource'
           C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/dsl/declare_resource.rb:71:in `declare_resource'
           C:/opscode/chef/embedded/apps/chef/lib/chef/dsl/recipe.rb:44:in `method_missing'
           C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/unit/recipes/default.rb:7:in `from_file'
           C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
           C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
           C:/opscode/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:218:in `load_recipe'
           C:/opscode/chef/embedded/apps/chef/lib/chef/run_context.rb:173:in `load_recipe'
           C:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
           C:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
           C:/opscode/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
```

**Comment by stuartpreston** [comment]
This still repros in 14.2.0 on Windows 2012 R2

```
PS C:\vagrant> chef-apply repro.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * reboot[foo] action reboot_now[2018-07-11T14:27:52+01:00] WARN: Rebooting system immediately, requested by 'foo'


    ================================================================================
    Error executing action `reboot_now` on resource 'reboot[foo]'
    ================================================================================

    UncaughtThrowError
    ------------------
    uncaught throw :end_client_run_early

    Resource Declaration:
    ---------------------
    # In repro.rb

      1: reboot 'foo' do
      2:   action :reboot_now
      3: end

    Compiled Resource:
    ------------------
    # Declared in repro.rb:1:in `run_chef_recipe'

    reboot("foo") do
      action [:reboot_now]
      default_guard_interpreter :default
      declared_type :reboot
      cookbook_name "(chef-apply cookbook)"
      recipe_name "(chef-apply recipe)"
    end

    System Info:
    ------------
    chef_version=14.2.0
    platform=windows
    platform_version=6.3.9600
    ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
    program_name=C:/opscode/angrychef/bin/chef-apply
    executable=C:/opscode/angrychef/bin/chef-apply

[2018-07-11T14:27:52+01:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
[2018-07-11T14:27:52+01:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-07-11T14:27:52+01:00] FATAL: UncaughtThrowError: reboot[foo] ((chef-apply cookbook)::(chef-apply recipe) line 1) had an error: UncaughtThrowError: uncaught throw :end_client_run_early
```

**Comment by btm** [comment]
I suppose the expected outcome here is that this would actually reboot, just like a client run. Any disagreement with that?

We probably need to wrap [these lines](https://github.com/chef/chef/blob/master/lib/chef/application/apply.rb#L194-L198) in a `catch(:end_client_run_early) do` block.

**Comment by Vasu1105** [comment]
@ddubey If I am not wrong you are getting above output with your changes made in chef-apply to fix reboot right ?

**Comment by dheerajd-msys** [comment]
@Vasu1105 Thanks for pointing this. I've also tried this without my changes too and can see `chef-zero` finishes successfully and windows machine reboots properly. 

```
$ bundle exec kitchen converge
-----> Starting Kitchen (v1.23.2)
-----> Converging <end-to-end-windows-2012r2>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 7.0.6...
       Removing non-cookbook files before transfer
       Preparing data_bags
       Preparing validation.pem
       Preparing client.rb

       ModuleType Version    Name                                ExportedCommands
       ---------- -------    ----                                ----------------
       Script     0.0        Omnitruck                           {Get-ProjectMetada...
       chef installation detected
       install_strategy set to 'once'
       Nothing to install
       Transferring files to <end-to-end-windows-2012r2>
       Starting Chef Client, version 14.1.12
       Creating a new client identity for end-to-end-windows-2012r2 using the validator key.
       resolving cookbooks for run list: ["end_to_end::tests"]
       Synchronizing Cookbooks:
         - end_to_end (1.0.0)
       Installing Cookbook Gems:

       Compiling Cookbooks...
       Converging 1 resources
       Recipe: end_to_end::tests
         * reboot[foo] action reboot_now[2018-10-05T13:26:51+00:00] WARN: Rebooting system immediately, requested by 'foo'
       [2018-10-05T13:26:51+00:00] WARN: Rebooting system immediately, requested by 'foo'


           Running handlers:
           Running handlers complete
           Chef Client finished, 0/0 resources updated in 06 minutes 04 seconds
       [2018-10-05T13:26:51+00:00] WARN: Rebooting server at a recipe's request. Details: {:delay_mins=>2, :reason=>"Reboot by Chef", :timestamp=>2018-10-05 13:26:51 +0000, :requested_by=>"foo"}
       [2018-10-05T13:26:51+00:00]
```
This will work with latest `kitchen` and `chef`.

Thanks.
