### ISSUE TITLE
Chef client install hangs temporarily on windows 7

### ISSUE THREAD

**Issue by dscowan** [chef/chef#4119]
I see this issue on Windows 7 chef client.  Windows Server 2012R2 appears fine.  There is 12 minutes between the Chef-client pid: XXXX and the Client key registration

```
test0016 C:\Users\Administrator>chef-client -c c:/chef/client.rb -j c:/chef/first-boot.json -E testing 
test0016 [2015-10-28T17:06:17-04:00] INFO: *** Chef 12.5.1 ***
test0016 [2015-10-28T17:06:17-04:00] INFO: Chef-client pid: 3960
test0016 [2015-10-28T17:18:20-04:00] INFO: Client key c:/chef/client.pem is not present - registering
test0016 [2015-10-28T17:18:21-04:00] INFO: HTTP Request Returned 404 Object Not Found: error
test0016 [2015-10-28T17:18:21-04:00] INFO: Setting the run_list to ["role[test]"] from CLI options
```

**Comment by btm** [comment]
@dscowan can you run with "-l debug" and share relevant log output?

**Comment by dscowan** [comment]
I tried attaching the log but didn't have permissions.  Here is the snippet I think matters

```
[2015-10-29T09:20:54-04:00] DEBUG: Sleeping for 0 seconds
[2015-10-29T09:20:58-04:00] INFO: *** Chef 12.5.1 ***
[2015-10-29T09:20:58-04:00] INFO: Chef-client pid: 1860
[2015-10-29T09:20:58-04:00] DEBUG: Chef-client request_id: 34060e19-5632-48a1-915d-6b9e950ed1b4
[2015-10-29T09:21:26-04:00] DEBUG: Plugin NetworkRoutes threw exception #<LoadError: cannot load such file -- sigar> C:/opscode/chef/embedded/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/opscode/chef/embedded/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.7.0/lib/ohai/plugins/sigar/network_route.rb:42:in `block (2 levels) in <main>'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.7.0/lib/ohai/dsl/plugin/versionvii.rb:90:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.7.0/lib/ohai/dsl/plugin/versionvii.rb:90:in `run_plugin'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.7.0/lib/ohai/dsl/plugin.rb:98:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.7.0/lib/ohai/dsl/plugin.rb:169:in `safe_run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.7.0/lib/ohai/runner.rb:84:in `run_v7_plugin'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.7.0/lib/ohai/runner.rb:43:in `run_plugin'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.7.0/lib/ohai/system.rb:98:in `block in run_plugins'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.7.0/lib/ohai/system.rb:97:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.7.0/lib/ohai/system.rb:97:in `run_plugins'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.7.0/lib/ohai/system.rb:75:in `all_plugins'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/client.rb:535:in `run_ohai'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/client.rb:251:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application.rb:252:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application.rb:229:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application.rb:212:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application/client.rb:408:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application/client.rb:398:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application/client.rb:398:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application/client.rb:388:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application.rb:60:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:65:in `load'
C:/opscode/chef/bin/chef-client:65:in `<main>'
[2015-10-29T09:21:26-04:00] DEBUG: Plugin NetworkListeners threw exception #<LoadError: cannot load such file -- sigar> C:/opscode/chef/embedded/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/opscode/chef/embedded/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.7.0/lib/ohai/plugins/network_listeners.rb:25:in `block (2 levels) in <main>'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.7.0/lib/ohai/dsl/plugin/versionvii.rb:90:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.7.0/lib/ohai/dsl/plugin/versionvii.rb:90:in `run_plugin'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.7.0/lib/ohai/dsl/plugin.rb:98:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.7.0/lib/ohai/dsl/plugin.rb:169:in `safe_run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.7.0/lib/ohai/runner.rb:84:in `run_v7_plugin'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.7.0/lib/ohai/runner.rb:43:in `run_plugin'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.7.0/lib/ohai/system.rb:98:in `block in run_plugins'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.7.0/lib/ohai/system.rb:97:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.7.0/lib/ohai/system.rb:97:in `run_plugins'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ohai-8.7.0/lib/ohai/system.rb:75:in `all_plugins'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/client.rb:535:in `run_ohai'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/client.rb:251:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application.rb:252:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application.rb:229:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application.rb:212:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application/client.rb:408:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application/client.rb:398:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application/client.rb:398:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application/client.rb:388:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application.rb:60:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:65:in `load'
C:/opscode/chef/bin/chef-client:65:in `<main>'
[2015-10-29T09:21:26-04:00] DEBUG: [inet] Using default interface 0xa and default gateway 192.169.1.2 to set the default ip to 192.169.2.159
[2015-10-29T09:21:26-04:00] DEBUG: [inet6] no default interface, picking the first ipaddress
[2015-10-29T09:21:26-04:00] DEBUG: No data to collect for plugin LSB. Continuing...
[2015-10-29T09:31:30-04:00] DEBUG: Plugin Virtualization threw #<Mixlib::ShellOut::CommandTimeout: command timed out:
---- Begin output of powershell.exe "Get-WmiObject -Class Win32_BIOS" ----
STDOUT: 
STDERR: The following error occurred while loading the extended type data file: Microsoft.PowerShell.Core, C:\Windows\SysWOW64\WindowsPowerShell\v1.0\typesv3.ps1xml: The file was skipped because of the following validation exception: File C:\Windows\SysWOW64\WindowsPowerShell\v1.0\typesv3.ps1xml cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170..
---- End output of powershell.exe "Get-WmiObject -Class Win32_BIOS" ----
>
[2015-10-29T09:31:30-04:00] DEBUG: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/mixlib-shellout-2.2.1-universal-mingw32/lib/mixlib/shellout/windows.rb:115:in `run_command'
[2015-10-29T09:31:30-04:00] DEBUG: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/mixlib-shellout-2.2.1-universal-mingw32/lib/mixlib/shellout.rb:259:in `run_command'
```

**Comment by btm** [comment]
Yeah, here you go:

```
[2015-10-29T09:31:30-04:00] DEBUG: Plugin Virtualization threw #<Mixlib::ShellOut::CommandTimeout: command timed out:
---- Begin output of powershell.exe "Get-WmiObject -Class Win32_BIOS" ----
STDOUT: 
STDERR: The following error occurred while loading the extended type data file: Microsoft.PowerShell.Core, C:\Windows\SysWOW64\WindowsPowerShell\v1.0\typesv3.ps1xml: The file was skipped because of the following validation exception: File C:\Windows\SysWOW64\WindowsPowerShell\v1.0\typesv3.ps1xml cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170..
---- End output of powershell.exe "Get-WmiObject -Class Win32_BIOS" ----
```

We could probably put something in Ohai to avoid running that plugin.

As a work-around, you might try with a line like this in your Chef client.rb (with the latest version of Chef for [RFC53](https://github.com/chef/chef-rfc/blob/master/rfc053-ohai-config.md) support for Ohai configuration):

```
Ohai.config[:disabled_plugins] = [ :Virtualization ]
```

Because we don't have a built-in way yet to populate the client.rb on first run (best right now is the [chef-client](https://supermarket.chef.io/cookbooks/chef-client) cookbook ) you would have to modify your `lib/chef/knife/core/bootstrap_context.rb` and add this change:

```
diff --git a/lib/chef/knife/core/bootstrap_context.rb b/lib/chef/knife/core/bootstrap_context.rb
index 8613a50..e396502 100644
--- a/lib/chef/knife/core/bootstrap_context.rb
+++ b/lib/chef/knife/core/bootstrap_context.rb
@@ -120,6 +120,8 @@ CONFIG
             client_rb << %Q{trusted_certs_dir "/etc/chef/trusted_certs"\n}
           end

+          client_rb << %Q{Ohai.config[:disabled_plugins] = [ :Virtualization ]\n}
+
           client_rb
         end
```
That's all off the top of my head and untested.

**Comment by dscowan** [comment]
I ended up just setting my powershell policy to unrestricted to work around this for now

**Comment by btm** [comment]
https://github.com/chef/ohai/pull/642 should fix this when complete.
