### ISSUE TITLE
Running knife diff on cookbook that contains binary files in it's root fails with invalid byte sequence in UTF-8 (ArgumentError)

### ISSUE THREAD

**Issue by iggyzap** [chef/chef#4180]
### Version:
Knife version 11.18.0, server : osc;version=11.0.2;erchef=1.4.0

### Environment: 
knife being executed on MacOS X
### Scenario:
Running knife diff against cookbook that contains binary file in strange place results in knife failure instead of correct diff. 
 
### Steps to Reproduce:
1. Download & install sample cookbook (now it's linked as png file, download it, remove png extension and untar-gz) to your chef server
2. Run knife diff cookbooks/madme-sample-binary -VV
3. Observe failure

### Expected Result:
As result of running 2 steps I would expect knife to not to find any difference

### Actual Result:
Following stacktrace is printed out:
```
Only in cookbooks/madme-sample-binary: files
/Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/command_line.rb:274:in `gsub': invalid byte sequence in UTF-8 (ArgumentError)
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/command_line.rb:274:in `diff_text'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/command_line.rb:91:in `block in diff_print'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/flatten_enumerable.rb:29:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/flatten_enumerable.rb:29:in `flatten'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/flatten_enumerable.rb:26:in `block in flatten'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/flatten_enumerable.rb:29:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/flatten_enumerable.rb:29:in `flatten'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/flatten_enumerable.rb:26:in `block in flatten'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/flatten_enumerable.rb:25:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/flatten_enumerable.rb:25:in `flatten'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/flatten_enumerable.rb:17:in `block in each'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:38:in `block in each'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:58:in `block in each_with_input'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:218:in `block in each_with_exceptions_ordered'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:162:in `block in each_with_exceptions_unordered'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:155:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:155:in `each_with_index'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:155:in `each_with_exceptions_unordered'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:214:in `each_with_exceptions_ordered'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:68:in `each_with_exceptions'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:50:in `each_with_input'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:37:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/flatten_enumerable.rb:16:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/flatten_enumerable.rb:25:in `flatten'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/flatten_enumerable.rb:17:in `block in each'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:38:in `block in each'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:58:in `block in each_with_input'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:218:in `block in each_with_exceptions_ordered'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:188:in `each_with_exceptions_unordered'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:214:in `each_with_exceptions_ordered'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:68:in `each_with_exceptions'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:50:in `each_with_input'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:37:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/parallelizer/flatten_enumerable.rb:16:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/chef_fs/command_line.rb:36:in `diff_print'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/knife/diff.rb:52:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/knife/diff.rb:51:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/knife/diff.rb:51:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/knife.rb:493:in `run_with_pretty_exceptions'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/knife.rb:174:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/lib/chef/application/knife.rb:139:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/chef-11.18.0/bin/knife:25:in `<top (required)>'
	from /usr/bin/knife:23:in `load'
	from /usr/bin/knife:23:in `<main>'
```
![madme-sample-binary tar gz](https://cloud.githubusercontent.com/assets/4525023/11216903/a6989184-8d45-11e5-9fbc-abe8096cecce.png)

**Comment by coderanger** [comment]
Does it work on the current versions of Chef and Chef Server?

**Comment by iggyzap** [comment]
Have not tested....

If someone can point me to instance of current chef server I can verify against - I can do so.

**Comment by coderanger** [comment]
Hosted Chef would be an example.

**Comment by iggyzap** [comment]
I can't reproduce it against latest hosted chef, please free to close the issue.

DEBUG: x-ops-api-info: flavor=cs;version=12.0.0;oc_erchef=12.2.0+20151005111019
[root@localhost sample-chef-repo]# knife -v
Chef: 12.5.1
