### ISSUE TITLE
Resource reporter throws Exception when filename contains ISO-8859-1 encoded characters

### ISSUE THREAD

**Issue by cmnayak** [chef/chef#4302]
Hi,
I am trying to add a file resource, where the file name has french characters. I guess below error in the log and chef client is stopped abruptly.

Chef::Handler::JsonFile raised #<Chef::Exceptions::JSON::EncodeError: Invalid UTF-8 string 'Encoding::InvalidByteSequenceError

Encoding::InvalidByteSequenceError: "\xE9" followed by "s" on UTF-8': cannot encode to UTF-8

Can you provide some suggessions.

**Comment by lamont-granquist** [comment]
What version of chef-client and can you replicate this bug on 12.5.1?

**Comment by lamont-granquist** [comment]
also would need the entire stacktrace.out

**Comment by lamont-granquist** [comment]
I tested on 12.5.1 with the following resource:

```
file "#{home_dir}/chef-test-ümlauts" do
  content "ümlauts"
end
```

it correctly creates the file with umlauts in the name, and in the contents, it runs to completion, displays the diff and the POST to reporting at the end succeeds.

so, can't replicate and can only assume that this bug is against an chef 11.x or something like that (and  fixing annoying UTF-8 issues is a major reason for chef-12 -- EMEA and JP users must be on 12.x or they'll suffer these kinds of problems).

**Comment by cmnayak** [comment]
Hi,

Sorry for late reply.
Can you try the same test provided the file is already existing. I believe
i observed this when a file is already existing.

thanks
Chintan

**Comment by lamont-granquist** [comment]
still cannot replicate:

```
  * file[/home/lamont/chef-test-ümlauts] action create
    - update content in file /home/lamont/chef-test-ümlauts from 0edb01 to 7ae177
    --- /home/lamont/chef-test-ümlauts	2016-01-13 11:00:09.000000000 -0800
    +++ /home/lamont/.chef-test-ümlauts20160114-33800-19dim51	2016-01-14 11:11:00.000000000 -0800
    @@ -1,2 +1,2 @@
    -ümlauts
    +different umläuts
```

**Comment by lamont-granquist** [comment]
is the filename in UTF-8 or in iso-8859-1 (latin-1)?

if its an iso-8859-1 character that might explain it...

**Comment by lamont-granquist** [comment]
Replicated with stacktrace and debug logs:

```
Chef Client finished, 18/775 resources updated in 51 seconds
[2016-01-14T11:28:07-08:00] INFO: Sending resource update report (run-id: 7c9df6b0-388c-4625-b7a3-4fb7e47baf77)
[2016-01-14T11:28:07-08:00] DEBUG: {"action"=>"end", "resources"=>[{"type"=>:remote_directory, "name"=>"/home/lamont", "id"=>"/home/lamont", "after"=>{:group=>2001, :mode=>"0755", :owner=>2001, :files_owner=>2001, :files_group=>2001, :files_mode=>420}, "before"=>{:group=>2001, :mode=>"0755", :owner=>2001}, "duration"=>"189", "delta"=>"", "result"=>"create", "cookbook_name"=>"sk_users", "cookbook_version"=>"1.1.36"}, {"type"=>:file, "name"=>"/home/lamont/.ssh/id_rsa", "id"=>"/home/lamont/.ssh/id_rsa", "after"=>{:checksum=>nil, :owner=>"lamont", :group=>2001, :mode=>"0600"}, "before"=>{:checksum=>nil, :owner=>"lamont", :group=>2001, :mode=>"0644"}, "duration"=>"6", "delta"=>"", "result"=>"create", "cookbook_name"=>"sk_users", "cookbook_version"=>"1.1.36"}, {"type"=>:file, "name"=>"/home/lamont/.ssh/id_ecdsa", "id"=>"/home/lamont/.ssh/id_ecdsa", "after"=>{:checksum=>nil, :owner=>"lamont", :group=>2001, :mode=>"0600"}, "before"=>{:checksum=>nil, :owner=>"lamont", :group=>2001, :mode=>"0644"}, "duration"=>"5", "delta"=>"", "result"=>"create", "cookbook_name"=>"sk_users", "cookbook_version"=>"1.1.36"}, {"type"=>:file, "name"=>"/home/lamont/chef-test-\xFDmlaut", "id"=>"/home/lamont/chef-test-\xFDmlaut", "after"=>{:checksum=>"3ff17858c05cbadc25afc2996cc09e19f208cd54838afc0986e3403e0ba3717f", :owner=>"root", :group=>"root", :mode=>"0644"}, "before"=>{:checksum=>nil, :owner=>nil, :group=>nil, :mode=>nil}, "duration"=>"4", "delta"=>"", "result"=>"create", "cookbook_name"=>"sk_users", "cookbook_version"=>"1.1.36"}, {"type"=>:runit_service, "name"=>"chef-client", "id"=>"chef-client", "after"=>{:enabled=>false, :running=>false}, "before"=>{}, "duration"=>"127", "delta"=>"", "result"=>"enable", "cookbook_name"=>"chef-client", "cookbook_version"=>"4.3.1"}, {"type"=>:service, "name"=>"nscd", "id"=>"nscd", "after"=>{:enabled=>true, :running=>true}, "before"=>{:enabled=>true, :running=>nil}, "duration"=>"41", "delta"=>"", "result"=>"start", "cookbook_name"=>"nscd", "cookbook_version"=>"2.0.0"}, {"type"=>:runit_service, "name"=>"sickstarfish", "id"=>"sickstarfish", "after"=>{:enabled=>false, :running=>false}, "before"=>{}, "duration"=>"109", "delta"=>"", "result"=>"enable", "cookbook_name"=>"rails_app_sickstarfish", "cookbook_version"=>"0.1.29"}, {"type"=>:runit_service, "name"=>"alchemy", "id"=>"alchemy", "after"=>{:enabled=>false, :running=>false}, "before"=>{}, "duration"=>"117", "delta"=>"", "result"=>"enable", "cookbook_name"=>"rails_app_alchemy", "cookbook_version"=>"0.1.9"}, {"type"=>:ruby_block, "name"=>"awois before_deploy", "id"=>"awois before_deploy", "after"=>{:block_name=>"awois before_deploy"}, "before"=>{}, "duration"=>"1009", "delta"=>"", "result"=>"run", "cookbook_name"=>"rails_app_awois", "cookbook_version"=>"0.1.1"}, {"type"=>:runit_service, "name"=>"tides", "id"=>"tides", "after"=>{:enabled=>false, :running=>false}, "before"=>{}, "duration"=>"109", "delta"=>"", "result"=>"enable", "cookbook_name"=>"rails_app_tides", "cookbook_version"=>"0.1.5"}, {"type"=>:runit_service, "name"=>"git-wiki", "id"=>"git-wiki", "after"=>{:enabled=>false, :running=>false}, "before"=>{}, "duration"=>"110", "delta"=>"", "result"=>"enable", "cookbook_name"=>"rails_app_git_wiki", "cookbook_version"=>"0.1.5"}], "status"=>"success", "run_list"=>"[\"role[base]\",\"role[burn]\",\"role[loadbalancer]\",\"role[sickstarfish]\",\"role[linode]\",\"role[alchemy]\",\"role[awois]\",\"role[tides]\",\"role[git_wiki]\",\"role[sensu]\"]", "total_res_count"=>"775", "data"=>{}, "start_time"=>"2016-01-14 11:27:27 -0800", "end_time"=>"2016-01-14 11:28:07 -0800", "expanded_run_list"=>"{\"id\":\"production\",\"run_list\":[{\"type\":\"role\",\"name\":\"base\",\"children\":[{\"type\":\"recipe\",\"name\":\"sk_role_base\",\"version\":null,\"skipped\":false}],\"missing\":null,\"error\":null,\"skipped\":null},{\"type\":\"role\",\"name\":\"burn\",\"children\":[],\"missing\":null,\"error\":null,\"skipped\":null},{\"type\":\"role\",\"name\":\"loadbalancer\",\"children\":[{\"type\":\"recipe\",\"name\":\"nginx\",\"version\":null,\"skipped\":false},{\"type\":\"recipe\",\"name\":\"sk_loadbalancer\",\"version\":null,\"skipped\":false}],\"missing\":null,\"error\":null,\"skipped\":null},{\"type\":\"role\",\"name\":\"sickstarfish\",\"children\":[{\"type\":\"recipe\",\"name\":\"rails_app_sickstarfish\",\"version\":null,\"skipped\":false}],\"missing\":null,\"error\":null,\"skipped\":null},{\"type\":\"role\",\"name\":\"linode\",\"children\":[],\"missing\":null,\"error\":null,\"skipped\":null},{\"type\":\"role\",\"name\":\"alchemy\",\"children\":[{\"type\":\"recipe\",\"name\":\"rails_app_alchemy\",\"version\":null,\"skipped\":false}],\"missing\":null,\"error\":null,\"skipped\":null},{\"type\":\"role\",\"name\":\"awois\",\"children\":[{\"type\":\"recipe\",\"name\":\"rails_app_awois\",\"version\":null,\"skipped\":false}],\"missing\":null,\"error\":null,\"skipped\":null},{\"type\":\"role\",\"name\":\"tides\",\"children\":[{\"type\":\"recipe\",\"name\":\"rails_app_tides\",\"version\":null,\"skipped\":false}],\"missing\":null,\"error\":null,\"skipped\":null},{\"type\":\"role\",\"name\":\"git_wiki\",\"children\":[{\"type\":\"recipe\",\"name\":\"rails_app_git_wiki\",\"version\":null,\"skipped\":false}],\"missing\":null,\"error\":null,\"skipped\":null},{\"type\":\"role\",\"name\":\"sensu\",\"children\":[{\"type\":\"recipe\",\"name\":\"sk_sensu::server\",\"version\":null,\"skipped\":false}],\"missing\":null,\"error\":null,\"skipped\":null}]}"}
[2016-01-14T11:28:07-08:00] DEBUG: Re-raising exception: Chef::Exceptions::JSON::EncodeError - Invalid UTF-8 string '/home/lamont/chef-test-�mlaut': cannot encode to UTF-8
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/json_compat.rb:108:in `rescue in to_json'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/json_compat.rb:105:in `to_json'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_reporter.rb:231:in `post_reporting_data'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_reporter.rb:208:in `run_completed'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/event_dispatch/dispatcher.rb:43:in `call'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/event_dispatch/dispatcher.rb:43:in `block in call_subscribers'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/event_dispatch/dispatcher.rb:34:in `each'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/event_dispatch/dispatcher.rb:34:in `call_subscribers'
  (eval):2:in `run_completed'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:287:in `run'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:270:in `block in fork_chef_client'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:258:in `fork'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:258:in `fork_chef_client'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:224:in `block in run_chef_client'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:212:in `run_chef_client'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:413:in `block in interval_run_chef_client'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:403:in `loop'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:403:in `interval_run_chef_client'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:393:in `run_application'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:60:in `run'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/chef-client:26:in `<top (required)>'
  /usr/bin/chef-client:54:in `load'
  /usr/bin/chef-client:54:in `<main>'

Running handlers:
[2016-01-14T11:28:07-08:00] ERROR: Running exception handlers
Running handlers complete
[2016-01-14T11:28:07-08:00] ERROR: Exception handlers complete
Chef Client failed. 18 resources updated in 51 seconds
[2016-01-14T11:28:07-08:00] INFO: Sending resource update report (run-id: 7c9df6b0-388c-4625-b7a3-4fb7e47baf77)
[2016-01-14T11:28:07-08:00] DEBUG: {"action"=>"end", "resources"=>[{"type"=>:remote_directory, "name"=>"/home/lamont", "id"=>"/home/lamont", "after"=>{:group=>2001, :mode=>"0755", :owner=>2001, :files_owner=>2001, :files_group=>2001, :files_mode=>420}, "before"=>{:group=>2001, :mode=>"0755", :owner=>2001}, "duration"=>"189", "delta"=>"", "result"=>"create", "cookbook_name"=>"sk_users", "cookbook_version"=>"1.1.36"}, {"type"=>:file, "name"=>"/home/lamont/.ssh/id_rsa", "id"=>"/home/lamont/.ssh/id_rsa", "after"=>{:checksum=>nil, :owner=>"lamont", :group=>2001, :mode=>"0600"}, "before"=>{:checksum=>nil, :owner=>"lamont", :group=>2001, :mode=>"0644"}, "duration"=>"6", "delta"=>"", "result"=>"create", "cookbook_name"=>"sk_users", "cookbook_version"=>"1.1.36"}, {"type"=>:file, "name"=>"/home/lamont/.ssh/id_ecdsa", "id"=>"/home/lamont/.ssh/id_ecdsa", "after"=>{:checksum=>nil, :owner=>"lamont", :group=>2001, :mode=>"0600"}, "before"=>{:checksum=>nil, :owner=>"lamont", :group=>2001, :mode=>"0644"}, "duration"=>"5", "delta"=>"", "result"=>"create", "cookbook_name"=>"sk_users", "cookbook_version"=>"1.1.36"}, {"type"=>:file, "name"=>"/home/lamont/chef-test-\xFDmlaut", "id"=>"/home/lamont/chef-test-\xFDmlaut", "after"=>{:checksum=>"3ff17858c05cbadc25afc2996cc09e19f208cd54838afc0986e3403e0ba3717f", :owner=>"root", :group=>"root", :mode=>"0644"}, "before"=>{:checksum=>nil, :owner=>nil, :group=>nil, :mode=>nil}, "duration"=>"4", "delta"=>"", "result"=>"create", "cookbook_name"=>"sk_users", "cookbook_version"=>"1.1.36"}, {"type"=>:runit_service, "name"=>"chef-client", "id"=>"chef-client", "after"=>{:enabled=>false, :running=>false}, "before"=>{}, "duration"=>"127", "delta"=>"", "result"=>"enable", "cookbook_name"=>"chef-client", "cookbook_version"=>"4.3.1"}, {"type"=>:service, "name"=>"nscd", "id"=>"nscd", "after"=>{:enabled=>true, :running=>true}, "before"=>{:enabled=>true, :running=>nil}, "duration"=>"41", "delta"=>"", "result"=>"start", "cookbook_name"=>"nscd", "cookbook_version"=>"2.0.0"}, {"type"=>:runit_service, "name"=>"sickstarfish", "id"=>"sickstarfish", "after"=>{:enabled=>false, :running=>false}, "before"=>{}, "duration"=>"109", "delta"=>"", "result"=>"enable", "cookbook_name"=>"rails_app_sickstarfish", "cookbook_version"=>"0.1.29"}, {"type"=>:runit_service, "name"=>"alchemy", "id"=>"alchemy", "after"=>{:enabled=>false, :running=>false}, "before"=>{}, "duration"=>"117", "delta"=>"", "result"=>"enable", "cookbook_name"=>"rails_app_alchemy", "cookbook_version"=>"0.1.9"}, {"type"=>:ruby_block, "name"=>"awois before_deploy", "id"=>"awois before_deploy", "after"=>{:block_name=>"awois before_deploy"}, "before"=>{}, "duration"=>"1009", "delta"=>"", "result"=>"run", "cookbook_name"=>"rails_app_awois", "cookbook_version"=>"0.1.1"}, {"type"=>:runit_service, "name"=>"tides", "id"=>"tides", "after"=>{:enabled=>false, :running=>false}, "before"=>{}, "duration"=>"109", "delta"=>"", "result"=>"enable", "cookbook_name"=>"rails_app_tides", "cookbook_version"=>"0.1.5"}, {"type"=>:runit_service, "name"=>"git-wiki", "id"=>"git-wiki", "after"=>{:enabled=>false, :running=>false}, "before"=>{}, "duration"=>"110", "delta"=>"", "result"=>"enable", "cookbook_name"=>"rails_app_git_wiki", "cookbook_version"=>"0.1.5"}], "status"=>"failure", "run_list"=>"[\"role[base]\",\"role[burn]\",\"role[loadbalancer]\",\"role[sickstarfish]\",\"role[linode]\",\"role[alchemy]\",\"role[awois]\",\"role[tides]\",\"role[git_wiki]\",\"role[sensu]\"]", "total_res_count"=>"775", "data"=>{"exception"=>{"class"=>"#<Chef::Exceptions::JSON::EncodeError: Invalid UTF-8 string '/home/lamont/chef-test-�mlaut': cannot encode to UTF-8>", "message"=>"Invalid UTF-8 string '/home/lamont/chef-test-�mlaut': cannot encode to UTF-8", "backtrace"=>"[\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/json_compat.rb:108:in `rescue in to_json'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/json_compat.rb:105:in `to_json'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_reporter.rb:231:in `post_reporting_data'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_reporter.rb:208:in `run_completed'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/event_dispatch/dispatcher.rb:43:in `call'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/event_dispatch/dispatcher.rb:43:in `block in call_subscribers'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/event_dispatch/dispatcher.rb:34:in `each'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/event_dispatch/dispatcher.rb:34:in `call_subscribers'\",\"(eval):2:in `run_completed'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:287:in `run'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:270:in `block in fork_chef_client'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:258:in `fork'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:258:in `fork_chef_client'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:224:in `block in run_chef_client'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:212:in `run_chef_client'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:413:in `block in interval_run_chef_client'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:403:in `loop'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:403:in `interval_run_chef_client'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:393:in `run_application'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:60:in `run'\",\"/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/chef-client:26:in `<top (required)>'\",\"/usr/bin/chef-client:54:in `load'\",\"/usr/bin/chef-client:54:in `<main>'\"]", "description"=>{}}}, "start_time"=>"2016-01-14 11:27:27 -0800", "end_time"=>"2016-01-14 11:28:07 -0800", "expanded_run_list"=>"{\"id\":\"production\",\"run_list\":[{\"type\":\"role\",\"name\":\"base\",\"children\":[{\"type\":\"recipe\",\"name\":\"sk_role_base\",\"version\":null,\"skipped\":false}],\"missing\":null,\"error\":null,\"skipped\":null},{\"type\":\"role\",\"name\":\"burn\",\"children\":[],\"missing\":null,\"error\":null,\"skipped\":null},{\"type\":\"role\",\"name\":\"loadbalancer\",\"children\":[{\"type\":\"recipe\",\"name\":\"nginx\",\"version\":null,\"skipped\":false},{\"type\":\"recipe\",\"name\":\"sk_loadbalancer\",\"version\":null,\"skipped\":false}],\"missing\":null,\"error\":null,\"skipped\":null},{\"type\":\"role\",\"name\":\"sickstarfish\",\"children\":[{\"type\":\"recipe\",\"name\":\"rails_app_sickstarfish\",\"version\":null,\"skipped\":false}],\"missing\":null,\"error\":null,\"skipped\":null},{\"type\":\"role\",\"name\":\"linode\",\"children\":[],\"missing\":null,\"error\":null,\"skipped\":null},{\"type\":\"role\",\"name\":\"alchemy\",\"children\":[{\"type\":\"recipe\",\"name\":\"rails_app_alchemy\",\"version\":null,\"skipped\":false}],\"missing\":null,\"error\":null,\"skipped\":null},{\"type\":\"role\",\"name\":\"awois\",\"children\":[{\"type\":\"recipe\",\"name\":\"rails_app_awois\",\"version\":null,\"skipped\":false}],\"missing\":null,\"error\":null,\"skipped\":null},{\"type\":\"role\",\"name\":\"tides\",\"children\":[{\"type\":\"recipe\",\"name\":\"rails_app_tides\",\"version\":null,\"skipped\":false}],\"missing\":null,\"error\":null,\"skipped\":null},{\"type\":\"role\",\"name\":\"git_wiki\",\"children\":[{\"type\":\"recipe\",\"name\":\"rails_app_git_wiki\",\"version\":null,\"skipped\":false}],\"missing\":null,\"error\":null,\"skipped\":null},{\"type\":\"role\",\"name\":\"sensu\",\"children\":[{\"type\":\"recipe\",\"name\":\"sk_sensu::server\",\"version\":null,\"skipped\":false}],\"missing\":null,\"error\":null,\"skipped\":null}]}"}
[2016-01-14T11:28:07-08:00] ERROR: Invalid UTF-8 string '/home/lamont/chef-test-�mlaut': cannot encode to UTF-8
[2016-01-14T11:28:07-08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by lamont-granquist** [comment]
fix in #4409

**Comment by lamont-granquist** [comment]
Also note that in 2016 if you're still using ISO-8851-1 / Latin-1 and not UTF-8 you are ultimately in for a world of pain.  I can 'fix' this issue and make chef-client not fail spectacularly, but I can't ever guess which non-UTF-8 charset a garbled filename is in and I can't ever make reporting be correct, and since this is a filename and not file contents there's no way to use a magic comment to change the encoding.  By far the best solution here is to just adopt UTF-8.

**Comment by lamont-granquist** [comment]
Also note that picking up the ISO-8859-1 charset from your environment settings and using that by default is going to be much worse since the whole rest of the Chef universe (all the shared cookbooks) uses UTF-8 by default.

**Comment by cmnayak** [comment]
Hi,

Really appreciate your effort on this. Thanks for the help.


thanks
Chintan
