### ISSUE TITLE
Windows package resource: The specified resource type cannot be found in the image file

### ISSUE THREAD

**Issue by webframp** [chef/chef#4354]
Testing on Windows 2012R2 @mwrock vagrant box + TK from latest released ChefDK, chef 12.6.0 on the Windows kitchen vm.

This simple recipe:

```rb
package 'Go Agent' do
  action :install
  source 'https://download.go.cd/gocd/go-agent-15.3.1-2777-setup.exe'
end
```

fails with `Win32APIError`:
```
---- Begin Win32 API output ----
System Error Code: 1813
System Error Message: The specified resource type cannot be found in the image file.
---- End Win32 API output ----
```

Looking at https://github.com/chef/chef/blob/master/lib/chef/win32/file/version_info.rb I suspect that the exe may not have the version info fields being searched for but haven't done furth investigation.

Here's the `kitchen converge` output:
```
C:\src\chef\cookbook-gocd [master ≡ +3 ~6 -0 !]> kitchen converge agent
-----> Starting Kitchen (v1.4.2)
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/webagent-cookie.rb:458: warning: already initialized constant HTTPClient::CookieManager
C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/cookie.rb:8: warning: previous definition of CookieManager was here
-----> Converging <agent-Windows2012R2>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.0.1...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <agent-Windows2012R2>
       Starting Chef Client, version 12.6.0
       resolving cookbooks for run list: ["gocd::test"]
       Synchronizing Cookbooks:
         - gocd (0.1.7)
         - windows (1.39.0)
         - git (4.3.5)
         - java (1.36.0)
         - chef_handler (1.2.0)
         - build-essential (2.2.4)
         - dmg (2.3.0)
         - yum-epel (0.6.5)
         - apt (2.9.2)
         - yum (3.8.2)
       Compiling Cookbooks...
       Converging 1 resources
       Recipe: gocd::test


           ================================================================================
           Error executing action `install` on resource 'windows_package[Go Agent]'
           ================================================================================

           Chef::Exceptions::Win32APIError
           -------------------------------
           The specified resource type cannot be found in the image file.
           ---- Begin Win32 API output ----
           System Error Code: 1813
           System Error Message: The specified resource type cannot be found in the image file.
           ---- End Win32 API output ----

           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/gocd/recipes/test.rb

             1: package 'Go Agent' do
             2:   action :install
             3:   source 'https://download.go.cd/gocd/go-agent-15.3.1-2777-setup.exe'
             4: end

           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/gocd/recipes/test.rb:1:in `from_file'

           windows_package("Go Agent") do
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             package_name "Go Agent"
             timeout 600
             source "https://download.go.cd/gocd/go-agent-15.3.1-2777-setup.exe"
             returns [0]
             declared_type :package
             cookbook_name "gocd"
             recipe_name "test"
           end


       Running handlers:
       [2016-01-04T20:46:16+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-01-04T20:46:16+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 09 seconds
       [2016-01-04T20:46:16+00:00] FATAL: Stacktrace dumped to C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       [2016-01-04T20:46:16+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-01-04T20:46:16+00:00] FATAL: Chef::Exceptions::Win32APIError: windows_package[Go Agent] (gocd::test line 1) had an error: Chef::Exceptions::Win32APIError: The specified resource type cannot be found in the image file.
       ---- Begin Win32 API output ----
       System Error Code: 1813
       System Error Message: The specified resource type cannot be found in the image file.
       ---- End Win32 API output ----
>>>>>> Converge failed on instance <agent-Windows2012R2>.
>>>>>> Please see .kitchen/logs/agent-Windows2012R2.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: WinRM exited (1) for command: [
$env:PATH = [System.Environment]::GetEnvironmentVariable("PATH","Machine")

& $env:systemdrive\opscode\chef\bin\chef-client.bat --local-mode --config $env:TEMP\kitchen\client.rb --log_level auto --force-formatter --no-color --json-attributes $env:TEMP\kitchen\dna.json --chef-zero-port 8889]
>>>>>> ----------------------
```

Here's the stack trace:
```
Generated at 2016-01-04 18:02:37 +0000
Chef::Exceptions::Win32APIError: windows_package[Go Agent] (gocd::test line 1) had an error: Chef::Exceptions::Win32APIError: The specified resource type cannot be found in the image file.
---- Begin Win32 API output ----
System Error Code: 1813
System Error Message: The specified resource type cannot be found in the image file.
---- End Win32 API output ----

C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/win32/error.rb:69:in `raise!'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/win32/api/file.rb:607:in `retrieve_file_version_info'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/win32/file/version_info.rb:31:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/win32/file.rb:154:in `new'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/win32/file.rb:154:in `version_info'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/provider/package/windows/exe.rb:103:in `install_file_version'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/provider/package/windows/exe.rb:51:in `package_version'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/provider/package/windows.rb:45:in `load_current_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/provider.rb:127:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/resource.rb:596:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/runner.rb:74:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/runner.rb:106:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/runner.rb:106:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/runner.rb:106:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/runner.rb:105:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/client.rb:658:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/client.rb:653:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/client.rb:653:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/client.rb:692:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/client.rb:271:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/application.rb:243:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/application.rb:220:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/application.rb:203:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/application/client.rb:413:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/application/client.rb:403:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/application/client.rb:403:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/application/client.rb:393:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/application.rb:58:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:64:in `load'
C:/opscode/chef/bin/chef-client:64:in `<main>'
```

**Comment by trevorghess** [comment]
I am also running into this issue running 12.6.0 on an Azure Windows 2012R2 box.

```


      Recipe: powershell::powershell5
        * windows_package[Windows Management Framework Core 5.0] action install[2016-01-05T19:08:42+00:00] INFO: Processing windows_package[Windows Management Framework Core 5.0] action install (powershell::powershell5 line 32)


          ================================================================================
          Error executing action `install` on resource 'windows_package[Windows Management Framework Core 5.0]'
          ================================================================================

          Chef::Exceptions::Win32APIError
          -------------------------------
          The specified image file did not contain a resource section.
          ---- Begin Win32 API output ----
          System Error Code: 1812
          System Error Message: The specified image file did not contain a resource section.
          ---- End Win32 API output ----

          Resource Declaration:
          ---------------------
          # In C:/Users/azure/AppData/Local/Temp/kitchen/cache/cookbooks/powershell/recipes/powershell5.rb

           32:     windows_package 'Windows Management Framework Core 5.0' do # ~FC009
           33:       source node['powershell']['powershell5']['url']
           34:       checksum node['powershell']['powershell5']['checksum']
           35:       installer_type :custom
           36:       options '/quiet /norestart'
           37:       action :install
           38:       success_codes [0, 42, 127, 3010]
           39:       # Note that the :immediately is to immediately notify the other resource,
           40:       # not to immediately reboot. The windows_reboot 'notifies' does that.
           41:       notifies :request, 'windows_reboot[powershell]', :immediately if reboot_pending? && node['powershell']['installation_reboot_mode'] != 'no_reboot'
           42:       not_if { registry_data_exists?('HKLM\SOFTWARE\Microsoft\PowerShell\3\PowerShellEngine', name: 'PowerShellVersion', type: :string, data: node['powershell']['powershell5']['version']) }
           43:     end
           44:
           45:   else
           46:     Chef::Log.warn("PowerShell 5.0 is not supported or already installed on this version of Windows: #{node['platform_version']}")
           47:   end
           48:

          Compiled Resource:
          ------------------
          # Declared in C:/Users/azure/AppData/Local/Temp/kitchen/cache/cookbooks/powershell/recipes/powershell5.rb:32:in `from_file'

          windows_package("Windows Management Framework Core 5.0") do
            provider Chef::Provider::Package::Windows
            action [:install]
            retries 0
            retry_delay 2
            default_guard_interpreter :default
            declared_type :windows_package
            cookbook_name "powershell"
            recipe_name "powershell5"
            source "http://download.microsoft.com/download/3/F/D/3FD04B49-26F9-4D9A-8C34-4533B9D5B020/Win8.1AndW2K12R2-KB3066437-x64.msu"
            checksum "9c57302ff0515a6b7eb53ab07bed0f5d420bd7204296d9f3fd17452fca1d5b3d"
            installer_type :custom
            options "/quiet /norestart"
            success_codes [0, 42, 127, 3010]
            package_name "Windows Management Framework Core 5.0"
            not_if { #code block }
          end

      [2016-01-05T19:08:43+00:00] INFO: Running queued delayed notifications before re-raising exception

      Running handlers:
      [2016-01-05T19:08:43+00:00] ERROR: Running exception handlers
      Running handlers complete
      [2016-01-05T19:08:43+00:00] ERROR: Exception handlers complete
      Chef Client failed. 1 resources updated in 30 seconds
      [2016-01-05T19:08:43+00:00] FATAL: Stacktrace dumped to C:/Users/azure/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
      [2016-01-05T19:08:43+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
      [2016-01-05T19:08:43+00:00] FATAL: Chef::Exceptions::Win32APIError: windows_package[Windows Management Framework Core 5.0] (powershell::powershell5 line 32) had an error: Chef::Exceptions::Win32APIError: The specified image file did not contain a resource section.

      ---- Begin Win32 API output ----
      System Error Code: 1812
      System Error Message: The specified image file did not contain a resource section.
      ---- End Win32 API output ----
```

**Comment by djmbm** [comment]
Any word on when a release with this fix will be out?
We're currently facing broken deployments for 2 pieces of software that are affected by this. They're both simple, but essential for our business: Notepad++ and Virtual Clone Drive.

**Comment by mwrock** [comment]
soon. hard to say just when but you can find this in the change log currently being prepped for 12.7 in #4507

**Comment by jaym** [comment]
You can also get an integration build from yesterday: https://omnitruck.chef.io/current/chef/download?p=windows&pv=2012&m=i386
