### ISSUE TITLE
Notifying a service from a custom resource

### ISSUE THREAD

**Issue by msawka** [chef/chef#4410]
### Version:
Chef Development Kit Version: 0.10.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2

### Environment: 
OS X El Capitan

### Scenario:
Notifying a service from a custom resource

### Steps to Reproduce:
I've defined a custom resource (resources/quicktest.rb):

```ruby
property :name, kind_of: String, name_attribute: true

# Chef 0.10.10 or greater
default_action :disable

action :disable do

  # verify the resource is in the collection
  test_serivce = resources(service: 'test')
  Chef::Log.fatal("test_serivce:  #{test_serivce}")

  execute "foo" do
    command "bar"
    notifies :nothing, 'service[test]', :delayed
  end
end
```

and am calling it from a recipe, where I define the service (recipes/quicktest.rb):

```ruby
service 'test' do
  service_name 'test'
  supports [:start, :restart, :reload, :status]
  action [:nothing]
end

schoolspring_quicktest 'foobar' do
  action :disable
end
```

My kitchen file(s) look like this:
```
---
driver:
  name: docker
  socket: tcp://1.2.3.4:2375
provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: qt
    run_list:
      - recipe[schoolspring::quicktest]
    attributes:
```

### Expected Result:
The service[test] is found and notified

### Actual Result:

When I run it via test kitchen, I'm getting the following error:

```
       Recipe: schoolspring::quicktest
         * service[test] action nothing (skipped due to action :nothing)
       * schoolspring_quicktest[foobar] action disable[2016-01-14T20:52:22+00:00] FATAL: test_serivce:  service[test]
       
       
           ================================================================================
           Error executing action `disable` on resource 'schoolspring_quicktest[foobar]'
           ================================================================================
           
           Chef::Exceptions::ResourceNotFound
           ----------------------------------
           resource execute[foo] is configured to notify resource service[test] with action nothing, but service[test] cannot be found in the resource collection. execute[foo] is defined in /tmp/kitchen/cache/cookbooks/schoolspring/resources/quicktest.rb:47:in `block in class_from_file'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/schoolspring/recipes/quicktest.rb
           
             8: schoolspring_quicktest 'foobar' do
             9:   action :disable
            10: end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/schoolspring/recipes/quicktest.rb:8:in `from_file'
           
           schoolspring_quicktest("foobar") do
             action [:disable]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :schoolspring_quicktest
             cookbook_name "schoolspring"
         recipe_name "quicktest"
           end
```

**Comment by coderanger** [comment]
This is expected behavior. The 12.5 custom resource syntax uses `use_inline_resources` internally and so has the same behavior. It creates an internal run context with an isolated resource collection. If you want to design code like this, Poise's `notifying_block` helper allows it.
