### ISSUE TITLE
cat chef-stacktrace showing this error

### ISSUE THREAD

**Issue by sernapallyanurag** [chef/chef#4442]
```
Generated at 2016-01-21 09:14:02 +0000
NoMethodError: undefined method `length' for nil:NilClass
/opt/chef/embedded/lib/ruby/2.1.0/openssl/ssl.rb:214:in `verify_wildcard'
/opt/chef/embedded/lib/ruby/2.1.0/openssl/ssl.rb:196:in `verify_hostname'
/opt/chef/embedded/lib/ruby/2.1.0/openssl/ssl.rb:161:in `block in verify_certificate_identity'
/opt/chef/embedded/lib/ruby/2.1.0/openssl/ssl.rb:159:in `each'
/opt/chef/embedded/lib/ruby/2.1.0/openssl/ssl.rb:159:in `verify_certificate_identity'
/opt/chef/embedded/lib/ruby/2.1.0/openssl/ssl.rb:231:in `post_connection_check'
/opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:925:in `connect'
/opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
/opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:852:in `start'
/opt/chef/embedded/lib/ruby/2.1.0/net/http.rb:1375:in `request'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/http/basic_client.rb:65:in `request'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/http.rb:275:in`block in send_http_request'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/http.rb:307:in`block in retrying_http_errors'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/http.rb:305:in`loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/http.rb:305:in`retrying_http_errors'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/http.rb:269:in`send_http_request'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/http.rb:144:in`request'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/http.rb:127:in`post'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/api_client/registration.rb:94:in `create'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/api_client/registration.rb:85:in `create_or_update'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/api_client/registration.rb:57:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/client.rb:612:in `register'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/client.rb:255:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:261:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:
249:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:
249:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:
215:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/local_mode.rb:4
4:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:
203:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application/cli
ent.rb:413:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application/cli
ent.rb:403:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application/cli
ent.rb:403:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application/cli
ent.rb:393:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:
58:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<
top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>
```

**Comment by lamont-granquist** [comment]
dup of #4301

**Comment by lamont-granquist** [comment]
(i think)

**Comment by lamont-granquist** [comment]
closing this since there's no more useful information in it than the other ticket already has
