### ISSUE TITLE
Knife errors on node show and search node

### ISSUE THREAD

**Issue by shortdudey123** [chef/chef#4547]
Knife errors out when trying to search for my chef server.  However, it works for most other nodes.

Replicated on 2 computers

```
$ bundle exec knife --version
Chef: 12.6.0
$ 
```

```
INFO: Using configuration from /Users/user/chef/.chef/knife.rb
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request
DEBUG: Signing the request as chef_user
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating GET to https://chef.server.local/organizations/org/search/node?q=name%253A*chef*&sort=X_CHEF_id_CHEF_X%20asc&start=0
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.0;
DEBUG: X-OPS-USERID: chef_user
DEBUG: X-OPS-TIMESTAMP: 2016-02-09T19:37:41Z
DEBUG: X-OPS-CONTENT-HASH: 2jmj7l5rSw0yVb/vlWAYkK/YBwk=
DEBUG: X-OPS-AUTHORIZATION-1: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
DEBUG: X-OPS-AUTHORIZATION-2: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
DEBUG: X-OPS-AUTHORIZATION-3: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
DEBUG: X-OPS-AUTHORIZATION-4: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
DEBUG: X-OPS-AUTHORIZATION-5: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
DEBUG: X-OPS-AUTHORIZATION-6: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
DEBUG: HOST: chef.server.local:443
DEBUG: X-Ops-Server-API-Version: 1
DEBUG: X-REMOTE-REQUEST-ID: 2f815a02-8852-4bdb-aba6-415b2bf27be1
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 200 OK
DEBUG: server: openresty/1.7.10.1
DEBUG: date: Tue, 09 Feb 2016 19:37:43 GMT
DEBUG: content-type: application/json
DEBUG: transfer-encoding: chunked
DEBUG: connection: close
DEBUG: x-ops-server-api-version: {"min_version":"0","max_version":"1","request_version":"1","response_version":"1"}
DEBUG: x-ops-api-info: flavor=cs;version=12.0.0;oc_erchef=12.1.1
DEBUG: content-encoding: gzip
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: HTTP server did not include a Content-Length header in response, cannot identify truncated downloads.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
5 items found

/Users/user/chef/.bundle/ruby/2.2.0/gems/chef-12.6.0/lib/chef/knife/core/node_presenter.rb:128:in `summarize': undefined method `join' for nil:NilClass (NoMethodError)
    from /Users/user/chef/.bundle/ruby/2.2.0/gems/chef-12.6.0/lib/chef/knife/core/generic_presenter.rb:77:in `format'
    from /Users/user/chef/.bundle/ruby/2.2.0/gems/chef-12.6.0/lib/chef/knife/core/node_presenter.rb:60:in `format'
    from /Users/user/chef/.bundle/ruby/2.2.0/gems/chef-12.6.0/lib/chef/knife/core/ui.rb:131:in `output'
    from /Users/user/chef/.bundle/ruby/2.2.0/gems/chef-12.6.0/lib/chef/knife/search.rb:128:in `block in run'
    from /Users/user/chef/.bundle/ruby/2.2.0/gems/chef-12.6.0/lib/chef/knife/search.rb:127:in `each'
    from /Users/user/chef/.bundle/ruby/2.2.0/gems/chef-12.6.0/lib/chef/knife/search.rb:127:in `run'
    from /Users/user/chef/.bundle/ruby/2.2.0/gems/chef-12.6.0/lib/chef/knife.rb:419:in `block in run_with_pretty_exceptions'
    from /Users/user/chef/.bundle/ruby/2.2.0/gems/chef-12.6.0/lib/chef/local_mode.rb:44:in `with_server_connectivity'
    from /Users/user/chef/.bundle/ruby/2.2.0/gems/chef-12.6.0/lib/chef/knife.rb:418:in `run_with_pretty_exceptions'
    from /Users/user/chef/.bundle/ruby/2.2.0/gems/chef-12.6.0/lib/chef/knife.rb:212:in `run'
    from /Users/user/chef/.bundle/ruby/2.2.0/gems/chef-12.6.0/lib/chef/application/knife.rb:142:in `run'
    from /Users/user/chef/.bundle/ruby/2.2.0/gems/chef-12.6.0/bin/knife:25:in `<top (required)>'
    from /Users/user/chef/.bundle/ruby/2.2.0/bin/knife:23:in `load'
    from /Users/user/chef/.bundle/ruby/2.2.0/bin/knife:23:in `<main>'
```

Dropping into a pry shell shows that `node.tags` is `nil`
```
From: /Users/user/chef/.bundle/ruby/2.2.0/gems/chef-12.6.0/lib/chef/knife/core/node_presenter.rb @ line 104 Chef::Knife::Core::NodePresenter#summarize:

     99:             ip = (node[:ec2] && node[:ec2][:public_ipv4]) || node[:ipaddress]
    100: 
    101: 
    102: require 'pry'
    103: binding.pry
 => 104:             summarized=<<-SUMMARY
    105: #{ui.color('Node Name:', :bold)}   #{ui.color(node.name, :bold)}
    106: SUMMARY
    107:             show_policy = !(node.policy_name.nil? && node.policy_group.nil?)
    108:             if show_policy
    109:               summarized << <<-POLICY

[1] pry(#<Chef::Knife::Core::NodePresenter>)> node.tags
=> nil
[2] pry(#<Chef::Knife::Core::NodePresenter>)> 
```

EDIT: nodes being searched are running chef-client `12.6.0`

**Comment by shortdudey123** [comment]
Talked to @coderanger on IRC
Doing a node edit and replacing `"tags": null,` with `"tags": [],` fixed the issue
