### ISSUE TITLE
knife cookbook site download fails

### ISSUE THREAD

**Issue by thommay** [chef/chef#4549]
```
13:21 ~/work/chef % be knife cookbook site download chef-solo-search   [master]
Downloading chef-solo-search from Supermarket at version 0.5.1 to /Users/thom/work/chef/chef-solo-search-0.5.1.tar.gz
ERROR: knife encountered an unexpected error
This may be a bug in the 'cookbook site download' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `sign_on_redirect=' for #<Chef::HTTP::SimpleJSON:0x007ff4c6893a88>
[1]    91706 exit 100   bundle exec knife cookbook site download chef-solo-search
```

**Comment by thommay** [comment]
```
13:52 ~/work/chef % be knife cookbook site download chef-solo-search -VV
INFO: Using configuration from /Users/thom/.chef/knife.rb
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating GET to https://supermarket.chef.io/api/v1/cookbooks/chef-solo-search
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-REMOTE-REQUEST-ID: 2f21d9cb-0e2b-4519-9519-94ed02eaef1e
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 200 OK
DEBUG: cache-control: max-age=0, private, must-revalidate
DEBUG: content-encoding: gzip
DEBUG: content-type: application/json; charset=utf-8
DEBUG: date: Tue, 09 Feb 2016 21:52:18 GMT
DEBUG: etag: W/"a7892ce7f9e4073377c3b4140f2f400a"
DEBUG: server: nginx/1.8.0
DEBUG: status: 200 OK
DEBUG: x-content-type-options: nosniff
DEBUG: x-frame-options: SAMEORIGIN
DEBUG: x-request-id: 9ecd300b-d8ee-45a9-80c1-2647cebed2ec
DEBUG: x-runtime: 0.019299
DEBUG: x-xss-protection: 1; mode=block
DEBUG: content-length: 400
DEBUG: connection: Close
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: Content-Length validated correctly.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating GET to https://supermarket.chef.io/api/v1/cookbooks/chef-solo-search/versions/0.5.1
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-REMOTE-REQUEST-ID: 2f21d9cb-0e2b-4519-9519-94ed02eaef1e
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 200 OK
DEBUG: cache-control: max-age=0, private, must-revalidate
DEBUG: content-encoding: gzip
DEBUG: content-type: application/json; charset=utf-8
DEBUG: date: Tue, 09 Feb 2016 21:52:18 GMT
DEBUG: etag: W/"d73bd0d3856f1b173d06f62431d9d721"
DEBUG: server: nginx/1.8.0
DEBUG: status: 200 OK
DEBUG: x-content-type-options: nosniff
DEBUG: x-frame-options: SAMEORIGIN
DEBUG: x-request-id: 22421eea-f22c-4fce-b764-1455db5c5935
DEBUG: x-runtime: 0.009973
DEBUG: x-xss-protection: 1; mode=block
DEBUG: content-length: 173
DEBUG: connection: Close
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: Content-Length validated correctly.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
Downloading chef-solo-search from Supermarket at version 0.5.1 to /Users/thom/work/chef/chef-solo-search-0.5.1.tar.gz
/Users/thom/work/chef/lib/chef/knife/cookbook_site_download.rb:88:in `download_cookbook': undefined method `sign_on_redirect=' for #<Chef::HTTP::SimpleJSON:0x007fc18a53e5c8> (NoMethodError)
	from /Users/thom/work/chef/lib/chef/knife/cookbook_site_download.rb:52:in `run'
	from /Users/thom/work/chef/lib/chef/knife.rb:416:in `block in run_with_pretty_exceptions'
	from /Users/thom/work/chef/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /Users/thom/work/chef/lib/chef/knife.rb:415:in `run_with_pretty_exceptions'
	from /Users/thom/work/chef/lib/chef/knife.rb:214:in `run'
	from /Users/thom/work/chef/lib/chef/application/knife.rb:148:in `run'
	from /Users/thom/work/chef/bin/knife:25:in `<top (required)>'
	from /Users/thom/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bin/knife:23:in `load'
	from /Users/thom/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bin/knife:23:in `<main>'
```
