### ISSUE TITLE
Cron resource breaks if crontab has non-UTF-8 characters in it

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/chef#4595]
## Description

The `cron` resource breaks with `ArgumentError: invalid byte sequence in UTF-8` if the user's crontab has non-UTF-8 characters in it.
## Chef Version

12.7.2
## Platform Version

Ubuntu 14.04
Centos 6.6
## Replication Case

.kitchen.yml contents

```

---
driver:
  name: vagrant
  require_chef_omnibus: '12.7.2'

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[cron_utf-8::default]
```

cron_utf-8::default recipe contents

```
cron 'noop-1' do
  hour '5'
  minute '0'
  command '/bin/true'
end

case node['platform_family']
when "rhel"
  cron_file = "/var/spool/cron/root"
when "debian"
  cron_file = "/var/spool/cron/crontabs/root"
end

ruby_block 'Append bad character' do
  block do
    IO.write(cron_file, "# \xC2\n", mode: 'a')
  end
end

cron 'noop-2' do
  hour '5'
  minute '0'
  command '/bin/true'
end
```
## Client Output

```
$ kitchen converge ubuntu
-----> Starting Kitchen (v1.5.0)
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/webagent-cookie.rb:458: warning: already initialized constant HTTPClient::CookieManager
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/cookie.rb:8: warning: previous definition of CookieManager was here
-----> Converging <default-ubuntu-1404>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.0.1...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (12.7.2)
       Transferring files to <default-ubuntu-1404>
       Starting Chef Client, version 12.7.2
       resolving cookbooks for run list: ["cron_utf-8::default"]
       Synchronizing Cookbooks:
         - cron (1.6.1)
         - cron_utf-8 (0.1.0)
         - logrotate (1.9.2)
         - windows (1.39.1)
         - chef-client (4.3.1)
         - chef_handler (1.2.0)
       Compiling Cookbooks...
       Converging 3 resources
       Recipe: cron_utf-8::default
         * cron[noop-1] action create
           - add crontab entry for cron[noop-1]
         * ruby_block[Append bad character] action run
           - execute the ruby block Append bad character
         * cron[noop-2] action create

           ================================================================================
           Error executing action `create` on resource 'cron[noop-2]'
           ================================================================================

           ArgumentError
           -------------
           invalid byte sequence in UTF-8

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/cron_utf-8/recipes/default.rb

            26: cron 'noop-2' do
            27:   hour '5'
            28:   minute '0'
            29:   command '/bin/true'
            30: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/cron_utf-8/recipes/default.rb:26:in `from_file'

           cron("noop-2") do
             action [:create]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             minute "0"
             hour "5"
             day "*"
             month "*"
             weekday "*"
             command "/bin/true"
             user "root"
             declared_type :cron
             cookbook_name "cron_utf-8"
             recipe_name "default"
           end


       Running handlers:
       [2016-02-18T14:27:35+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-02-18T14:27:35+00:00] ERROR: Exception handlers complete
       Chef Client failed. 2 resources updated in 02 seconds
       [2016-02-18T14:27:35+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-02-18T14:27:35+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-02-18T14:27:35+00:00] ERROR: cron[noop-2] (cron_utf-8::default line 26) had an error: ArgumentError: invalid byte sequence in UTF-8
       [2016-02-18T14:27:37+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <default-ubuntu-1404>.
>>>>>> Please see .kitchen/logs/default-ubuntu-1404.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '

sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level warn --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889
']
>>>>>> ----------------------
zlib(finalizer): the stream was freed prematurely.
```
## Stacktrace

```
Generated at 2016-02-18 14:12:08 +0000
ArgumentError: cron[noop-1] (cron_utf-8::default line 7) had an error: ArgumentError: invalid byte sequence in UTF-8
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/provider/cron.rb:63:in `==='
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/provider/cron.rb:63:in `block in load_current_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/provider/cron.rb:56:in `each_line'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/provider/cron.rb:56:in `load_current_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/provider.rb:127:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource.rb:596:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/runner.rb:73:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/runner.rb:105:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/runner.rb:105:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/runner.rb:105:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/runner.rb:104:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/client.rb:668:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/client.rb:663:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/client.rb:663:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/client.rb:702:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/client.rb:280:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:258:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:223:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:211:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/client.rb:433:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/client.rb:423:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/client.rb:423:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/client.rb:412:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/bin/chef-client:26:in `<top (required)>'
/opt/chef/bin/chef-client:50:in `load'
/opt/chef/bin/chef-client:50:in `<main>'
```

**Comment by jeremiahsnapp** [comment]
@lamont-granquist this is the UTF-8 issue we talked about a couple days ago.

**Comment by tas50** [comment]
I'm going to close this out since the workaround is using the cron_d resource which avoids any parsing of the crontab file.
