### ISSUE TITLE
`windows_package` requires source to be set on :remove action

### ISSUE THREAD

**Issue by Valiev** [chef/chef#4627]
## Description

Unable to remove `windows_package` not setting `source` attribute

## Chef Version

chef-client 12.7.2 

## Platform Version

Windows Server 2008 R2 Standart

## Replication Case

```
windows_package "package_name" do
  action         :remove
  installer_type :msi
end
```  

## Client Output

```
 the contents of the stacktrace.out file if you file a bug report
[2016-02-25T05:45:36-08:00] DEBUG: Chef::Exceptions::ValidationFailed: windows_package[MyPackage] (cookbook::recipe line 37) had an error: Chef::Exceptions::ValidationFailed: source is required
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/property.rb:367:in `get'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/property.rb:262:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/property.rb:511:in `source'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/provider/package/windows.rb:198:in `downloadable_file_missing?'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/provider/package/windows.rb:47:in `load_current_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/provider.rb:127:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource.rb:596:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/runner.rb:73:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/runner.rb:105:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/runner.rb:105:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/runner.rb:105:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/runner.rb:104:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/client.rb:668:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/client.rb:663:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/client.rb:663:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/client.rb:702:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/client.rb:280:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application.rb:252:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application.rb:228:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application.rb:211:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application/client.rb:433:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application/client.rb:423:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application/client.rb:423:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application/client.rb:412:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application.rb:58:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/embedded/bin/chef-client:22:in `load'
C:/opscode/chef/embedded/bin/chef-client:22:in `<main>'
[2016-02-25T05:45:36-08:00] FATAL: Chef::Exceptions::ValidationFailed: windows_package[MyPackage] (cookbook::recipe line 37) had an error: Chef::Exceptions::ValidationFailed: source is required

```
## Stacktrace

```
Generated at 2016-02-25 06:07:06 -0800
Chef::Exceptions::ValidationFailed: windows_package[MyCDeliverNotesGenerator.msi] (dng::update_app line 37) had an error: Chef::Exceptions::ValidationFailed: source is required
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/property.rb:367:in `get'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/property.rb:262:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/property.rb:511:in `source'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/provider/package/windows.rb:198:in `downloadable_file_missing?'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/provider/package/windows.rb:47:in `load_current_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/provider.rb:127:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource.rb:596:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/runner.rb:73:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/runner.rb:105:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/runner.rb:105:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/runner.rb:105:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/runner.rb:104:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/client.rb:668:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/client.rb:663:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/client.rb:663:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/client.rb:702:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/client.rb:280:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application.rb:252:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application.rb:228:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application.rb:211:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application/client.rb:433:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application/client.rb:423:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application/client.rb:423:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application/client.rb:412:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/lib/chef/application.rb:58:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.7.2-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/embedded/bin/chef-client:22:in `load'
C:/opscode/chef/embedded/bin/chef-client:22:in `<main>'
```

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by Valiev** [comment]
Okay. I've found that it was required by `windows` cookbook. Closing this ticket.
