### ISSUE TITLE
Unexpected error when using "knife cookbook show ...."

### ISSUE THREAD

**Issue by nlam79** [chef/chef#4659]
## Description

Un unexpected error when using "knife cookbook show COOKBOOK [VERSION] [PART] [FILENAME]" with chef-client 12.7.2.   With chef-client 12.5.1, it did not have this problem.  

## Chef Version

Chef Development Kit Version: 0.11.2
Chef-client version: 12.7.2

## Platform Version

Ubuntu 14.04

## Replication Case

```
> knife cookbook show bb-chef-svv -c /home/nlam/.chef/knife_cluster_master.rb
output> bb-chef-svv   0.50.0  0.1.10
```
```
> knife cookbook show bb-chef-svv 0.50.0 recipes default.rb -c /home/nlam/.chef/knife_cluster_master.rb
output>
ERROR: knife encountered an unexpected error
This may be a bug in the 'cookbook show' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `preferred_manifest_record' for #<Hash:0x000000029ca548>
```

## Client Output

N/A

## Stacktrace
```
knife cookbook show bb-chef-svv 0.50.0 recipes default.rb -c /home/nlam/.chef/knife_cluster_master.rb -VV
INFO: Using configuration from /home/nlam/.chef/knife_cluster_master.rb
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request
DEBUG: Signing the request as admin-mandolin
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating GET to https://chef-server.nlam.svv.thor.altus.bblabs/organizations/mandolin/cookbooks/bb-chef-svv/0.50.0
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-Ops-Server-API-Version: 1
DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.1;
DEBUG: X-OPS-USERID: admin-mandolin
DEBUG: X-OPS-TIMESTAMP: 2016-03-03T14:58:48Z
DEBUG: X-OPS-CONTENT-HASH: 2jmj7l5rSw0yVb/vlWAYkK/YBwk=
DEBUG: X-OPS-AUTHORIZATION-1: brw005daB9iEkBX91pP7nOGJjWmqSd0rWr5C/woD8lmlbq6MjZ8NLd/Tb/LZ
DEBUG: X-OPS-AUTHORIZATION-2: JF592xeTqjTXimDrhEuAFzFZVOdT9wlFYuBagKN1mXwuJkkFqHtb5Up9c2ze
DEBUG: X-OPS-AUTHORIZATION-3: YiebShRzxSoElaJ9t6P940/+N/r3rYo0wIusUVb9/p+rrO24vSS0e39tE2OZ
DEBUG: X-OPS-AUTHORIZATION-4: ptHJn8Nr04RgETN8UEW71Hoi2pEHqof7b1LFn3F51BKbuBUX3EihWZ1pO59S
DEBUG: X-OPS-AUTHORIZATION-5: LsXg0tGYXpzLBRKTr7xA0UaEdtGyTC5I6h1C55AaG3Y7bVp03j6ewAkAQRop
DEBUG: X-OPS-AUTHORIZATION-6: 3iJvmt34Eq9xlbzo1ikn9qwKMtYlrgZ4WsQYhCDkrw==
DEBUG: HOST: chef-server.nlam.svv.thor.altus.bblabs:443
DEBUG: X-REMOTE-REQUEST-ID: e5c4cc5a-3ae2-4050-b771-964f42fd16a2
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 200 OK
DEBUG: server: openresty/1.9.3.1
DEBUG: date: Thu, 03 Mar 2016 14:58:48 GMT
DEBUG: content-type: application/json
DEBUG: transfer-encoding: chunked
DEBUG: connection: close
DEBUG: x-ops-server-api-version: {"min_version":"0","max_version":"1","request_version":"1","response_version":"1"}
DEBUG: x-ops-api-info: flavor=cs;version=12.0.0;oc_erchef=12.3.0
DEBUG: content-encoding: gzip
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: HTTP server did not include a Content-Length header in response, cannot identify truncated downloads.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife/cookbook_show.rb:71:in `run': undefined method `preferred_manifest_record' for #<Hash:0x000000027257e8> (NoMethodError)
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife.rb:416:in `block in run_with_pretty_exceptions'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/local_mode.rb:44:in `with_server_connectivity'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife.rb:415:in `run_with_pretty_exceptions'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/knife.rb:214:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/lib/chef/application/knife.rb:148:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.7.2/bin/knife:25:in `<top (required)>'
        from /opt/chefdk/bin/knife:50:in `load'
        from /opt/chefdk/bin/knife:50:in `<main>'
```

**Comment by lamont-granquist** [comment]
#4673 fixed this
