### ISSUE TITLE
homebrew_package installing from taps is broken

### ISSUE THREAD

**Issue by a-melnyk** [chef/chef#4704]
## Description

It seems, that chef doesn't correctly work with [brew taps](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/brew-tap.md). Chef looks for package version and checks status using command `brew info`, which works only with cloned repos, and if repo isn't still cloned it fails:

```
bash-3.2$ brew info homebrew/php/php70
Error: No available formula with the name "homebrew/php/php70"
Please tap it and then try again: brew tap homebrew/php
bash-3.2$ echo $?
1
```

But, homebrew supports search for formulas/packages in homebrew repos:

```
bash-3.2$ brew search homebrew/php/php70
homebrew/php/php70
bash-3.2$ echo $?
0
```

And homebrew handles installation from not cloned repos:

```
bash-3.2$ brew install homebrew/php/php70
==> Tapping homebrew/php
Cloning into '/usr/local/Library/Taps/homebrew/homebrew-php'...
remote: Counting objects: 585, done.
remote: Compressing objects: 100% (370/370), done.
remote: Total 585 (delta 393), reused 241 (delta 213), pack-reused 0
Receiving objects: 100% (585/585), 235.69 KiB | 0 bytes/s, done.
Resolving deltas: 100% (393/393), done.
Checking connectivity... done.
Tapped 563 formulae (601 files, 1M)
==> Installing php70 from homebrew/php
==> Downloading https://php.net/get/php-7.0.4.tar.bz2/from/this/mirror
...
```

it starts from cloning repo (using `brew tap`) and then installing package, [source of brew install](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/install.rb#L17)
## Chef Version

tested on chef 12.6.0 and 12.8.1
## Platform Version

OS X 10.11.3 & Homebrew 0.9.5 (git revision 5355; last commit 2016-03-11)
## Replication Case

```
bash-3.2$ cat /tmp/pack.rb
package 'homebrew/php/php70'

bash-3.2$ sudo chef-apply /tmp/pack.rb
```
## Client Output

```
bash-3.2$ sudo chef-apply /tmp/pack.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * homebrew_package[homebrew/php/php70] action install

    ================================================================================
    Error executing action `install` on resource 'homebrew_package[homebrew/php/php70]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of brew info --json=v1 homebrew/php/php70 ----
    STDOUT:
    STDERR: Error: No available formula with the name "homebrew/php/php70"
    Please tap it and then try again: brew tap homebrew/php
    ---- End output of brew info --json=v1 homebrew/php/php70 ----
    Ran brew info --json=v1 homebrew/php/php70 returned 1

    Resource Declaration:
    ---------------------
    # In /tmp/pack.rb

      1: package "homebrew/php/php70"
      2:

    Compiled Resource:
    ------------------
    # Declared in /tmp/pack.rb:1:in `run_chef_recipe'

    homebrew_package("homebrew/php/php70") do
      package_name "homebrew/php/php70"
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :package
      cookbook_name "(chef-apply cookbook)"
      recipe_name "(chef-apply recipe)"
    end

[2016-03-13T15:50:58+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-03-13T15:50:58+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-03-13T15:50:58+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: homebrew_package[homebrew/php/php70] ((chef-apply cookbook)::(chef-apply recipe) line 1) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of brew info --json=v1 homebrew/php/php70 ----
STDOUT:
STDERR: Error: No available formula with the name "homebrew/php/php70"
Please tap it and then try again: brew tap homebrew/php
---- End output of brew info --json=v1 homebrew/php/php70 ----
Ran brew info --json=v1 homebrew/php/php70 returned 1
```
## Stacktrace

```
Generated at 2016-03-13 15:50:58 +0000
Mixlib::ShellOut::ShellCommandFailed: homebrew_package[homebrew/php/php70] ((chef-apply cookbook)::(chef-apply recipe) line 1) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of brew info --json=v1 homebrew/php/php70 ----
STDOUT:
STDERR: Error: No available formula with the name "homebrew/php/php70"
Please tap it and then try again: brew tap homebrew/php
---- End output of brew info --json=v1 homebrew/php/php70 ----
Ran brew info --json=v1 homebrew/php/php70 returned 1
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout.rb:289:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout.rb:276:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/mixin/shell_out.rb:56:in `shell_out!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/package.rb:538:in `shell_out_with_timeout!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/package/homebrew.rb:130:in `get_response_from_command'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/package/homebrew.rb:76:in `brew'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/package/homebrew.rb:88:in `brew_info'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/package/homebrew.rb:98:in `current_installed_version'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider/package/homebrew.rb:37:in `load_current_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/provider.rb:127:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/resource.rb:596:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/runner.rb:73:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/runner.rb:105:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/runner.rb:105:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/runner.rb:105:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/resource_collection/resource_list.rb:84:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/resource_collection/resource_list.rb:82:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/runner.rb:104:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/apply.rb:195:in `run_chef_recipe'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/apply.rb:205:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/apply.rb:218:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/bin/chef-apply:25:in `<top (required)>'
/usr/local/bin/chef-apply:50:in `load'
/usr/local/bin/chef-apply:50:in `<main>'
```
## Workaround
1. Pull repo using `brew tap`
2. Install package using package/homebrew_package

```
bash-3.2$ cat /tmp/pack.rb
execute 'install homebrew/php tap' do
  command 'brew tap homebrew/php'
  user 'brew_user'
end

package 'homebrew/php/php70'
```

**Comment by tas50** [comment]
I believe we fixed this issue when we rewrote the homebrew_package resource. If you run into this issue in a new Chef Infra Client release please let us know.
