### ISSUE TITLE
Cookbook fails to compile with new style resources if dash ( - ) is used in the cookbook name

### ISSUE THREAD

**Issue by vinyar** [chef/chef#4723]
## Description
cookbooks with dashes and custom resources fail to compile.

## Chef Version
$ chef -v
Chef Development Kit Version: 0.11.2
chef-client version: 12.7.2
berks version: 4.2.0
kitchen version: 1.5.0

chef-client 12.8.1 on the test nodes

## Platform Version
default-win2012
default-opscode-ubuntu-1404
default-opscode-centos-65

Repro via both, chef-zero and chef-solo provisioners

## Replication Case
create a cookbook with `-` in the name. Example windows-users
create a custom resource. default.rb or custom_name.rb
example:

Resource: (default.rb)
```
property :username, String, name_property: true
property :description, String

action :create do
  powershell_script "create user" do
    code <<-EOH
      write-host "hello world"
    EOH
    guard_interpreter :powershell_script
    end
end
```

Recipe: (default.rb)
```
windows-users 'batman' do
  action :create
end
```
## Client Output
```
-----> Chef Omnibus installation detected (12.8.1)

       Transferring files to <default-win2012-chef11-14-2>
       Starting Chef Client, version 12.8.1
       Installing Cookbook Gems:
       Compiling Cookbooks...

       ================================================================================
       Recipe Compile Error in C:\Users\vagrant\AppData\Local\Temp\kitchen\cookbooks\carbonite-windows\recipes\default.rb
       ================================================================================

       SyntaxError
       -----------
       C:\Users\vagrant\AppData\Local\Temp\kitchen\cookbooks\carbonite-windows\recipes\default.rb:24: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
       carbonite-windows 'batman' do
                   ^
       C:\Users\vagrant\AppData\Local\Temp\kitchen\cookbooks\carbonite-windows\recipes\default.rb:24: syntax error, unexpected keyword_do, expecting end-of-input


       Running handlers:
       [2016-03-18T02:43:23-07:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-03-18T02:43:23-07:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 28 seconds
       [2016-03-18T02:43:23-07:00] FATAL: Stacktrace dumped to C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       [2016-03-18T02:43:23-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-03-18T02:43:23-07:00] FATAL: SyntaxError: C:\Users\vagrant\AppData\Local\Temp\kitchen\cookbooks\carbonite-windows\recipes\default.rb:24: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
       carbonite-windows 'batman' do
                   ^
       C:\Users\vagrant\AppData\Local\Temp\kitchen\cookbooks\carbonite-windows\recipes\default.rb:24: syntax error, unexpected keyword_do, expecting end-of-input
$$$$$$ DL is deprecated, please use Fiddle
>>>>>> Converge failed on instance <default-win2012-chef11-14-2>.
>>>>>> Please see .kitchen/logs/default-win2012-chef11-14-2.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: WinRM exited (1) for command: [
$env:PATH = [System.Environment]::GetEnvironmentVariable("PATH","Machine")

& $env:systemdrive\opscode\chef\bin\chef-solo.bat --config $env:TEMP\kitchen\solo.rb --log_level auto --force-formatter --no-color --json-attributes $env:TEMP\kitchen\dna.json]
>>>>>> ----------------------
```

## Stacktrace
```
enerated at 2016-03-18 09:44:08 +0000
SyntaxError: /tmp/kitchen/cookbooks/carbonite-windows/recipes/default.rb:24: syntax error, unexpected tSTRING_BEG, expecting keyword_do or '{' or '('
carbonite-windows 'batman' do
                   ^
/tmp/kitchen/cookbooks/carbonite-windows/recipes/default.rb:24: syntax error, unexpected keyword_do, expecting end-of-input
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/cookbook_version.rb:233:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/run_context.rb:332:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/run_context.rb:167:in `load'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/client.rb:509:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/client.rb:277:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application.rb:258:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application.rb:223:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application.rb:211:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/solo.rb:301:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/solo.rb:301:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/solo.rb:290:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/solo.rb:290:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/solo.rb:269:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/bin/chef-solo:25:in `<top (required)>'
/opt/chef/bin/chef-solo:50:in `load'
/opt/chef/bin/chef-solo:50:in `<main>'
```

**Comment by coderanger** [comment]
`-` is not a valid character in a Ruby method. Use `windows_user` instead.

**Comment by vinyar** [comment]
Um. If that's the case, `knife cookbook create` and `chef generate cookbook` should prevent cookbook creation with dashes in them. Also, presently there is nothing in documentation to reflect that dash is illegal.

I am pretty sure LWRP used to work with cookbook having dashes in the metadata name field.

**Comment by jrunning** [comment]
@vinyar: What @coderanger means is that if you have a cookbook name with dashes, you can use it in a recipe by replacing the dashes with underscores. You can use the cookbook in your example like this:

```ruby
windows_users 'batman' do
  action :create
end
```

We're working on improving the docs and tools to make it clear to users that dashes and other non-alphanumeric-or-underscore characters in cookbook names should be avoided for this reason. Sorry for the confusion!

**Comment by lamont-granquist** [comment]
yeah it has always worked this way -- custom resources or LWRPs -- simply because of ruby.

because the dash-to-underscore conversion is scattered around the code is tends to become buggy and requires user's to think too hard, converting dashes in cookbooks to underscores is recommended and will simplify your life.

**Comment by narendra0087** [comment]
Generally, this error comes by syntax error,
check **_do_** and **_end_** properly
