### ISSUE TITLE
Chef-solo fails to install chocolatey package.

### ISSUE THREAD

**Issue by StephenDrewLDS** [chef/chef#4772]
## Description

Cannot install chocolatey package due to failure to process (I think) the Chocolatey version info that is output when running e.g. `"choco list -ar 7zip"`

I think parse_list_output in chocolatey.rb should do:

```ruby
            name, version = line.split("|")
            if version != nil 
              list << [ name.downcase, version.chomp ]
            end
```

## Chef Version

12.8.1

## Platform Version

Windows 8.1

## Replication Case

Create a recipe that tries to install 7zip chocolatey package:

chocolatey_package '7zip' do
end

## Client Output

```
  * chocolatey_package[7zip] action install

    ============================================================================
====
    Error executing action `install` on resource 'chocolatey_package[7zip]'
    ============================================================================
====

    NoMethodError
    -------------
    undefined method `chomp' for nil:NilClass

    Resource Declaration:
    ---------------------
    # In C:\chef\cookbooks\zookeeper\recipes\default.rb

     10: chocolatey_package '7zip' do
     11:
     12: end
     13:

    Compiled Resource:
    ------------------
    # Declared in C:\chef\cookbooks\zookeeper\recipes\default.rb:10:in `from_fil
e'

    chocolatey_package("7zip") do
      package_name ["7zip"]
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :chocolatey_package
      cookbook_name :zookeeper
      recipe_name "default"
    end
```

## Stacktrace

```
NoMethodError: chocolatey_package[7zip] (zookeeper::default line 10) had an error: NoMethodError: undefined method `chomp' for nil:NilClass
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/package/chocolatey.rb:260:in `block in parse_list_output'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/package/chocolatey.rb:258:in `each_line'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/package/chocolatey.rb:258:in `parse_list_output'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/package/chocolatey.rb:234:in `available_packages'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/package/chocolatey.rb:181:in `block in build_candidate_versions'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/package/chocolatey.rb:180:in `map'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/package/chocolatey.rb:180:in `build_candidate_versions'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/package/chocolatey.rb:72:in `candidate_version'
```

**Comment by StephenDrewLDS** [comment]
OK sorry duplicate of #4760
