### ISSUE TITLE
dsc_resource :script timeout

### ISSUE THREAD

**Issue by electronicalias** [chef/chef#4823]
Hi all,

## Description
I am getting a timeout in a chef run if I use the dsc_resource resource with the :script type. It doesn't matter if it is complex or simple commands as below, it produces the same result.

If I leave out any of the 3 properties I get an error to tell me so, which means each value is expected.

I have tried with and without {} ' ' and "" in many different combinations and have not managed to yield any positive result, so this could be a syntax error on my part, however it is how I have interpreted the documentation.

## Chef Version

Using chef-client with the following:
Starting Chef Client, version 12.8.1
resolving cookbooks for run list: ["base-webserver::firewall"]
Synchronizing Cookbooks:
  - base-webserver (1.0.0)
  - windows (1.39.2)
  - chef_handler (1.3.0)

## Platform Version

Windows 2012 R2
```
Major  Minor      Build  Revision
6         3       9600   0
```

I'm using Powershell 5 that comes with the Windows Management Framework V5 (RTM):
```
Name                                      Value

PSVersion                               5.0.10586.117
PSCompatibleVersions                    {1.0, 2.0, 3.0, 4.0...}
BuildVersion                            10.0.10586.117
CLRVersion                              4.0.30319.42000
WSManStackVersion                       3.0
PSRemotingProtocolVersion               2.3
SerializationVersion                    1.1.0.1
```
## Replication Case

In a cloud of your choice, I'm using AWS, create a Windows 2012 R2 host, install the [management framework.](https://www.microsoft.com/en-us/download/details.aspx?id=50395)

I also had to apply this fix as I'm using Powershell 5/WMF 5 on RTM otherwise it doesn't work correctly as stated in the chef documentation for dsc_resource, look at the ['DSC cmdlets may not work if WMF 5.0 RTM is installed on top of WMF 5.0 Production Preview Issue'](https://msdn.microsoft.com/en-us/powershell/wmf/limitation_dsc)

Create the following base-webserver/recipes/firewall.rb:

```
dsc_resource 'disable_firewall' do
  resource :script
  property :setscript, 'return @{ Timezone = ("{0}" -f (tzutil.exe /g)) }'
  property :getscript, 'return @{ Timezone = ("{0}" -f (tzutil.exe /g)) }'
  property :testscript, 'return @{ Timezone = ("{0}" -f (tzutil.exe /g)) }'
end
```
NOTE: I have tried this with and without surrounding { } for each property value, the original script is far more complex however I can replicate it with something like this, or even 

Now run a command similar to the following, or whatever your env requires:
```
chef-client -z -c "C:\chef\win-client.rb" -r recipe[base-webserver::firewall] -E prod -l debug
```
NOTE: win-client.rb just sets the chef directories/logs etc

## Client Output

The output is below, debug is set but the output includes all dependent cookbooks which are 'windows' and 'chef_handler' as above:

```
Recipe: base-webserver::firewall
  * dsc_resource[disable_firewall] action run
    ←[0m
    ================================================================================
    Error executing action `run` on resource 'dsc_resource[disable_firewall]'
    ================================================================================

    Mixlib::ShellOut::CommandTimeout
    --------------------------------
    command timed out:
    ---- Begin output of powershell.exe -executionpolicy bypass -noprofile -noninteractive -command "trap [Exception] {w
rite-error -exception ($_.Exception.Message);exit 1};Invoke-DscResource -Method test -Name script -Property @{setscript=
([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('cmV0dXJuIEB7IFRpbWV6b25lID0gKCJ7MH0iIC1mICh0
enV0aWwuZXhlIC9nKSkgfQ==')));getscript=([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('cmV0d
XJuIEB7IFRpbWV6b25lID0gKCJ7MH0iIC1mICh0enV0aWwuZXhlIC9nKSkgfQ==')));testscript=([System.Text.Encoding]::UTF8.GetString([
System.Convert]::FromBase64String('cmV0dXJuIEB7IFRpbWV6b25lID0gKCJ7MH0iIC1mICh0enV0aWwuZXhlIC9nKSkgfQ==')))} -Module PSD
esiredStateConfiguration -Verbose   4> 'C:/Users/ADMINI~1/AppData/Local/Temp/2/verbose20160412-2284-jq8cje' | convertto-
json -compress -depth 5 > C:/Users/ADMINI~1/AppData/Local/Temp/2/json20160412-2284-11j4rp9";if ( ! $? ) { exit 1 } ----
    STDOUT:
    STDERR:
    ---- End output of powershell.exe -executionpolicy bypass -noprofile -noninteractive -command "trap [Exception] {wri
te-error -exception ($_.Exception.Message);exit 1};Invoke-DscResource -Method test -Name script -Property @{setscript=([
System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('cmV0dXJuIEB7IFRpbWV6b25lID0gKCJ7MH0iIC1mICh0en
V0aWwuZXhlIC9nKSkgfQ==')));getscript=([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('cmV0dXJ
uIEB7IFRpbWV6b25lID0gKCJ7MH0iIC1mICh0enV0aWwuZXhlIC9nKSkgfQ==')));testscript=([System.Text.Encoding]::UTF8.GetString([Sy
stem.Convert]::FromBase64String('cmV0dXJuIEB7IFRpbWV6b25lID0gKCJ7MH0iIC1mICh0enV0aWwuZXhlIC9nKSkgfQ==')))} -Module PSDes
iredStateConfiguration -Verbose   4> 'C:/Users/ADMINI~1/AppData/Local/Temp/2/verbose20160412-2284-jq8cje' | convertto-js
on -compress -depth 5 > C:/Users/ADMINI~1/AppData/Local/Temp/2/json20160412-2284-11j4rp9";if ( ! $? ) { exit 1 } ----

    ProcessId: 2040
    app_name: C:\Windows\System32\WindowsPowerShell\v1.0\/powershell.exe
    command_line: powershell.exe -executionpolicy bypass -noprofile -noninteractive -command "trap [Exception] {write-er
ror -exception ($_.Exception.Message);exit 1};Invoke-DscResource -Method test -Name script -Property @{setscript=([Syste
m.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('cmV0dXJuIEB7IFRpbWV6b25lID0gKCJ7MH0iIC1mICh0enV0aWw
uZXhlIC9nKSkgfQ==')));getscript=([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('cmV0dXJuIEB7
IFRpbWV6b25lID0gKCJ7MH0iIC1mICh0enV0aWwuZXhlIC9nKSkgfQ==')));testscript=([System.Text.Encoding]::UTF8.GetString([System.
Convert]::FromBase64String('cmV0dXJuIEB7IFRpbWV6b25lID0gKCJ7MH0iIC1mICh0enV0aWwuZXhlIC9nKSkgfQ==')))} -Module PSDesiredS
tateConfiguration -Verbose   4> 'C:/Users/ADMINI~1/AppData/Local/Temp/2/verbose20160412-2284-jq8cje' | convertto-json -c
ompress -depth 5 > C:/Users/ADMINI~1/AppData/Local/Temp/2/json20160412-2284-11j4rp9";if ( ! $? ) { exit 1 }
    timeout: 600

    Resource Declaration:
    ---------------------
    # In c:/chef/local-mode-cache/cache/cookbooks/base-webserver/recipes/firewall.rb

      1: dsc_resource 'disable_firewall' do
      2:   resource :script
      3:   property :setscript, 'return @{ Timezone = ("{0}" -f (tzutil.exe /g)) }'
      4:   property :getscript, 'return @{ Timezone = ("{0}" -f (tzutil.exe /g)) }'
      5:   property :testscript, 'return @{ Timezone = ("{0}" -f (tzutil.exe /g)) }'
      6: end

    Compiled Resource:
    ------------------
    # Declared in c:/chef/local-mode-cache/cache/cookbooks/base-webserver/recipes/firewall.rb:1:in `from_file'

    dsc_resource("disable_firewall") do
      action [:run]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      properties {setscript=>"return @{ Timezone = (\"{0}\" -f (tzutil.exe /g)) }", getscript=>"return @{ Timezone = (\"
{0}\" -f (tzutil.exe /g)) }", testscript=>"return @{ Timezone = (\"{0}\" -f (tzutil.exe /g)) }"}
      resource :script
      reboot_action :nothing
      declared_type :dsc_resource
      cookbook_name "base-webserver"
      recipe_name "firewall"
    end

←[0m
Running handlers:
Running handlers complete
Chef Client failed. 0 resources updated in 10 minutes 20 seconds
```

## Stacktrace

```
Generated at 2016-04-12 20:42:44 +0000
Mixlib::ShellOut::CommandTimeout: dsc_resource[disable_firewall] (base-webserver::firewall line 1) had an error: Mixlib::ShellOut::CommandTimeout: command timed out:
---- Begin output of powershell.exe -executionpolicy bypass -noprofile -noninteractive -command "trap [Exception] {write-error -exception ($_.Exception.Message);exit 1};Invoke-DscResource -Method test -Name script -Property @{setscript=([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('cmV0dXJuIEB7IFRpbWV6b25lID0gKCJ7MH0iIC1mICh0enV0aWwuZXhlIC9nKSkgfQ==')));getscript=([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('cmV0dXJuIEB7IFRpbWV6b25lID0gKCJ7MH0iIC1mICh0enV0aWwuZXhlIC9nKSkgfQ==')));testscript=([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('cmV0dXJuIEB7IFRpbWV6b25lID0gKCJ7MH0iIC1mICh0enV0aWwuZXhlIC9nKSkgfQ==')))} -Module PSDesiredStateConfiguration -Verbose   4> 'C:/Users/ADMINI~1/AppData/Local/Temp/2/verbose20160412-2284-jq8cje' | convertto-json -compress -depth 5 > C:/Users/ADMINI~1/AppData/Local/Temp/2/json20160412-2284-11j4rp9";if ( ! $? ) { exit 1 } ----
STDOUT: 
STDERR: 
---- End output of powershell.exe -executionpolicy bypass -noprofile -noninteractive -command "trap [Exception] {write-error -exception ($_.Exception.Message);exit 1};Invoke-DscResource -Method test -Name script -Property @{setscript=([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('cmV0dXJuIEB7IFRpbWV6b25lID0gKCJ7MH0iIC1mICh0enV0aWwuZXhlIC9nKSkgfQ==')));getscript=([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('cmV0dXJuIEB7IFRpbWV6b25lID0gKCJ7MH0iIC1mICh0enV0aWwuZXhlIC9nKSkgfQ==')));testscript=([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('cmV0dXJuIEB7IFRpbWV6b25lID0gKCJ7MH0iIC1mICh0enV0aWwuZXhlIC9nKSkgfQ==')))} -Module PSDesiredStateConfiguration -Verbose   4> 'C:/Users/ADMINI~1/AppData/Local/Temp/2/verbose20160412-2284-jq8cje' | convertto-json -compress -depth 5 > C:/Users/ADMINI~1/AppData/Local/Temp/2/json20160412-2284-11j4rp9";if ( ! $? ) { exit 1 } ----

ProcessId: 2040
app_name: C:\Windows\System32\WindowsPowerShell\v1.0\/powershell.exe
command_line: powershell.exe -executionpolicy bypass -noprofile -noninteractive -command "trap [Exception] {write-error -exception ($_.Exception.Message);exit 1};Invoke-DscResource -Method test -Name script -Property @{setscript=([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('cmV0dXJuIEB7IFRpbWV6b25lID0gKCJ7MH0iIC1mICh0enV0aWwuZXhlIC9nKSkgfQ==')));getscript=([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('cmV0dXJuIEB7IFRpbWV6b25lID0gKCJ7MH0iIC1mICh0enV0aWwuZXhlIC9nKSkgfQ==')));testscript=([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('cmV0dXJuIEB7IFRpbWV6b25lID0gKCJ7MH0iIC1mICh0enV0aWwuZXhlIC9nKSkgfQ==')))} -Module PSDesiredStateConfiguration -Verbose   4> 'C:/Users/ADMINI~1/AppData/Local/Temp/2/verbose20160412-2284-jq8cje' | convertto-json -compress -depth 5 > C:/Users/ADMINI~1/AppData/Local/Temp/2/json20160412-2284-11j4rp9";if ( ! $? ) { exit 1 }
timeout: 600
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/mixlib-shellout-2.2.6-universal-mingw32/lib/mixlib/shellout/windows.rb:118:in `run_command'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/mixlib-shellout-2.2.6-universal-mingw32/lib/mixlib/shellout.rb:259:in `run_command'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/util/powershell/cmdlet.rb:80:in `block in run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/mixin/windows_architecture_helper.rb:67:in `with_os_architecture'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/util/powershell/cmdlet.rb:79:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/util/powershell/cmdlet.rb:87:in `run!'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/dsc_resource.rb:160:in `invoke_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/dsc_resource.rb:124:in `test_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/dsc_resource.rb:36:in `action_run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider.rb:144:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource.rb:596:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/runner.rb:73:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/runner.rb:105:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/runner.rb:105:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/runner.rb:105:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/resource_list.rb:84:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/resource_list.rb:82:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/runner.rb:104:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:668:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:663:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:663:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:702:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:280:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application.rb:252:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application.rb:228:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application.rb:211:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application/client.rb:445:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application/client.rb:435:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application/client.rb:435:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application/client.rb:424:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application.rb:58:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:60:in `load'
C:/opscode/chef/bin/chef-client:60:in `<main>'
```

**Comment by electronicalias** [comment]
Hi, 

I think it was a syntax error, hope I haven't caused anyone to waste any time, I was able to get it working after rebuilding the instance and then running the following block:

```
dsc_resource 'disable_firewall' do
  resource :script
  property :getscript, '<# something here #>'
  property :setscript, '
        Start-Process netsh -ArgumentList "advfirewall set allprofiles state off"
    '
  property :testscript, '
        Function Get-FW-State {
            $output = "netsh advfirewall show publicprofile"
            $output = $output[3..($output.length-2)]
            $output | foreach {
                $parts = $_ -split "\s+",0
                New-Object -Type PSObject -Property @{
                    Value = ($parts[1])
                    Name = ($parts[0])
                }
            }
        }
        if ((Get-FW-State | Where-Object {$_.Name -like "*State*"}).Value -eq "ON") {
            return $false
        }
        else {
            return $true
        }
    '
end
```
