### ISSUE TITLE
chef-shell fails to launch on omnios

### ISSUE THREAD

**Issue by tas50** [chef/chef#4842]
## Description

chef-shell fails to launch on OmniOS
## Chef Version

Chef 12.9
## Platform Version

Omnios r15101
## Replication Case

Using the Omnios r151014 vagrant box install chef and run chef-shell.
## Client Output

```
root@omnios-r151014:/etc# chef-shell
loading configuration: none (standalone session)
Session type: standalone
Loading.[2016-04-19T00:54:31+00:00] WARN: unable to detect ipaddress
..done.

This is the chef-shell.
 Chef Version: 12.9.38
 http://www.chef.io/
 http://docs.chef.io/

run `help' for help, `exit' or ^D to quit.

Ohai2u vagrant@!
infocmp: mandatory padding removed
infocmp: padding information moved to end
infocmp: mandatory padding removed
infocmp: padding information moved to end
infocmp: WARNING: termcap entry is too long!
infocmp: mandatory padding removed
infocmp: padding information moved to end
infocmp: WARNING: termcap entry is too long!
unknown mode: size
infocmp: mandatory padding removed
infocmp: padding information moved to end
infocmp: WARNING: termcap entry is too long!
/opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rbreadline.rb:2061:in `scan': invalid byte sequence in UTF-8 (ArgumentError)
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rbreadline.rb:2061:in `block in rl_tty_set_default_bindings'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rbreadline.rb:6912:in `retry_if_interrupted'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rbreadline.rb:2060:in `rl_tty_set_default_bindings'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rbreadline.rb:2075:in `readline_default_bindings'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rbreadline.rb:2522:in `readline_initialize_everything'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rbreadline.rb:3804:in `rl_initialize'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rbreadline.rb:4823:in `readline'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/readline.rb:45:in `readline'
        from /opt/chef/embedded/lib/ruby/2.1.0/irb/input-method.rb:152:in `gets'
        from /opt/chef/embedded/lib/ruby/2.1.0/irb.rb:472:in `block (2 levels) in eval_input'
        from /opt/chef/embedded/lib/ruby/2.1.0/irb.rb:624:in `signal_status'
        from /opt/chef/embedded/lib/ruby/2.1.0/irb.rb:471:in `block in eval_input'
        from /opt/chef/embedded/lib/ruby/2.1.0/irb/ruby-lex.rb:190:in `call'
        from /opt/chef/embedded/lib/ruby/2.1.0/irb/ruby-lex.rb:190:in `buf_input'
        from /opt/chef/embedded/lib/ruby/2.1.0/irb/ruby-lex.rb:105:in `getc'
        from /opt/chef/embedded/lib/ruby/2.1.0/irb/slex.rb:206:in `match_io'
        from /opt/chef/embedded/lib/ruby/2.1.0/irb/slex.rb:76:in `match'
        from /opt/chef/embedded/lib/ruby/2.1.0/irb/ruby-lex.rb:290:in `token'
        from /opt/chef/embedded/lib/ruby/2.1.0/irb/ruby-lex.rb:266:in `lex'
        from /opt/chef/embedded/lib/ruby/2.1.0/irb/ruby-lex.rb:237:in `block (2 levels) in each_top_level_statement'
        from /opt/chef/embedded/lib/ruby/2.1.0/irb/ruby-lex.rb:233:in `loop'
        from /opt/chef/embedded/lib/ruby/2.1.0/irb/ruby-lex.rb:233:in `block in each_top_level_statement'
        from /opt/chef/embedded/lib/ruby/2.1.0/irb/ruby-lex.rb:232:in `catch'
        from /opt/chef/embedded/lib/ruby/2.1.0/irb/ruby-lex.rb:232:in `each_top_level_statement'
        from /opt/chef/embedded/lib/ruby/2.1.0/irb.rb:488:in `eval_input'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38/lib/chef/shell.rb:75:in `block in start'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38/lib/chef/shell.rb:74:in `catch'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38/lib/chef/shell.rb:74:in `start'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38/bin/chef-shell:34:in `<top (required)>'
        from /usr/bin/chef-shell:51:in `load'
        from /usr/bin/chef-shell:51:in `<main>'
```

**Comment by tas50** [comment]
Closing in favor of https://github.com/chef/chef/issues/6446 which tracks more platform failures
