### ISSUE TITLE
windows_package error when registry key contains special characters like registered trademark symbol

### ISSUE THREAD

**Issue by sh9189** [chef/chef#4897]
## Description
When using windows_package resource in a chef recipe,  special characters like registered trademark symbol present in windows registry under **'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall'** cause 
**Encoding::UndefinedConversionError**. The error comes from the following code in windows_package provider https://github.com/chef/chef/blob/master/lib/chef/provider/package/windows/registry_uninstall_entry.rb#L38-L39 when it tries to iterate over the registry keys.
## Chef Version
chef client - 12.9.38
## Platform Version
Windows 2008 r2

## Replication Case
Having a windows registry key with special character under **'HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall'** , for example (Progress DataDirect Connect64 ® and Connect64 XE for ODBC 7.1 SP6) and using a simple windows_package resource as follows will cause the error.

```ruby
windows_package 'mypackage' do
 action :install
  source 'mysource'
  installer_type :msi
end
```
## Client Output
[2016-05-05T15:18:17-04:00] FATAL: Encoding::UndefinedConversionError: windows_package[CollectdWinService] (collectdwin::default line 22) had an error: Encoding::UndefinedConversionError: U+00AE to IBM437 in conversion from UTF-16LE to UTF-8 to IBM437

## Stacktrace
```shell
Generated at 2016-05-05 12:14:59 -0400
Encoding::UndefinedConversionError: windows_package[CollectdWinService] (collectdwin::default line 22) had an error: Encoding::UndefinedConversionError: U+00AE to IBM437 in conversion from UTF-16LE to UTF-8 to IBM437
C:/opscode/chef/embedded/lib/ruby/2.1.0/win32/registry.rb:895:in `encode'
C:/opscode/chef/embedded/lib/ruby/2.1.0/win32/registry.rb:895:in `export_string'
C:/opscode/chef/embedded/lib/ruby/2.1.0/win32/registry.rb:598:in `each_key'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/provider/package/windows/registry_uninstall_entry.rb:39:in `block (2 levels) in find_entries'
C:/opscode/chef/embedded/lib/ruby/2.1.0/win32/registry.rb:422:in `open'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/provider/package/windows/registry_uninstall_entry.rb:38:in `block in find_entries'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/provider/package/windows/registry_uninstall_entry.rb:35:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/provider/package/windows/registry_uninstall_entry.rb:35:in `find_entries'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/provider/package/windows.rb:183:in `uninstall_registry_entries'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/provider/package/windows.rb:64:in `package_provider'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/provider/package/windows.rb:51:in `load_current_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/provider.rb:127:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/resource.rb:596:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/runner.rb:69:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/runner.rb:97:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/resource_collection/resource_list.rb:84:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/resource_collection/resource_list.rb:82:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/runner.rb:96:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/client.rb:667:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/client.rb:662:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/client.rb:662:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/client.rb:701:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/client.rb:281:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/application.rb:267:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/application.rb:243:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/application.rb:226:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/application/client.rb:419:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/lib/chef/application.rb:58:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:61:in `load'
C:/opscode/chef/bin/chef-client:61:in `<main>'
```

**Comment by coderanger** [comment]
Ping @chef/client-windows for triage :)

**Comment by mwrock** [comment]
what locale is the node using? Is it western European by chance?

**Comment by sh9189** [comment]
No, the system locale is just `English(UnitedStates)`, but executing `Encoding.find(Encoding.locale_charmap)` in chef embedded ruby at `C:\opscode\chef\embedded\bin\irb.bat`  returns `Encoding:IBM437`

**Comment by mwrock** [comment]
Sorry the locale is irrelevant. I misread the codepage value above.

It is uncommon (but legal) for symbols to be found in the actual key string. More common for them to show up in the key value data. Unfortunately this is blowing up in the underlying ruby language registry.rb as it enumerates the child keys of `Uninstall`. I'll have a closer look.

**Comment by sh9189** [comment]
Yeah, it looks like there is also a bug filed about this in ruby at https://bugs.ruby-lang.org/issues/11410. The actual error seems to coming from these lines where it is trying to encoding registry sub-key as a string https://github.com/ruby/ruby/blob/trunk/ext/win32/lib/win32/registry.rb#L907-L909

**Comment by mwrock** [comment]
I submitted a monkey patch #4906 to address this.

**Comment by johnbellone** [comment]
Awesome @mwrock !

**Comment by sh9189** [comment]
@mwrock Thanks for the quick fix. Will this also patch ohai? The ohai packages plugin also iterates windows registry keys to get list of installed packages at https://github.com/chef/ohai/blob/master/lib/ohai/plugins/packages.rb#L64-L65 and the issue is seen there also.
