### ISSUE TITLE
yum_package throwing: undefined method `length' for nil:NilClass

### ISSUE THREAD

**Issue by itsSaad** [chef/chef#4914]
## Description
Although it started coming up only today. It was working fine previously. Im testing my cookbooks locally with vagrant, chef-solo and getting the following problem.
```
NoMethodError
-------------
undefined method `length' for nil:NilClass
```
When i try to run `yum_package`.
## Chef Version
12.8.1

## Platform Version
Centos/7
## Replication Case
So far i have not been able to reproduce this.
## Client Output
I get the following error:
```
==> default: Converging 30 resources
==> default: Recipe: base::epel
==> default:   * yum_package[epel-release] action install
==> default:
==> default:
==> default:     ================================================================================
==> default:     Error executing action `install` on resource 'yum_package[epel-release]'
==> default:     ================================================================================
==> default:
==> default:     NoMethodError
==> default:     -------------
==> default:     undefined method `length' for nil:NilClass
==> default:
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /tmp/vagrant-chef/292f7208a0636f73708a65a4b212437d/cookbooks/base/recipes/epel.rb
==> default:
==> default:       1: yum_package 'epel-release' do
==> default:       2:   action :install
==> default:       3: end
==> default:
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /tmp/vagrant-chef/292f7208a0636f73708a65a4b212437d/cookbooks/base/recipes/epel.rb:1:in `from_file'
==> default:
==> default:     yum_package("epel-release") do
==> default:       package_name "epel-release"
==> default:       action [:install]
==> default:       retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :default
==> default:       declared_type :yum_package
==> default:       cookbook_name :base
==> default:       recipe_name "epel"
==> default:       flush_cache {:before=>false, :after=>false}
==> default:     end
==> default:
==> default:     Platform:
==> default:     ---------
==> default:     x86_64-linux
```
Even if I up the VM specs (4gb ram) I still get this error.
My `Vagrantfile` seems like this: 
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

Vagrant.require_version '>= 1.5.0'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  config.vm.hostname = 'base-berkshelf'

  # Set the version of chef to install using the vagrant-omnibus plugin
  # NOTE: You will need to install the vagrant-omnibus plugin:
  #
  #   $ vagrant plugin install vagrant-omnibus
  #
  if Vagrant.has_plugin?("vagrant-omnibus")
    config.omnibus.chef_version = 'latest'
  end

  # Every Vagrant virtual environment requires a box to build off of.
  # If this value is a shorthand to a box in Vagrant Cloud then
  # config.vm.box_url doesn't need to be specified.
  config.vm.box = 'centos/7'


  # Assign this VM to a host-only network IP, allowing you to access it
  # via the IP. Host-only networks can talk to the host machine as well as
  # any other machines on the same network, but cannot be accessed (through this
  # network interface) by any external networks.
  config.vm.network :private_network, type: 'dhcp'

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider :virtualbox do |vb|
  #   # Don't boot with headless mode
  #   vb.gui = true
  #
  #   # Use VBoxManage to customize the VM. For example to change memory:
  #   vb.customize ["modifyvm", :id, "--memory", "1024"]
  # end
  #
  # View the documentation for the provider you're using for more
  # information on available options.

  # The path to the Berksfile to use with Vagrant Berkshelf
  # config.berkshelf.berksfile_path = "./Berksfile"

  # Enabling the Berkshelf plugin. To enable this globally, add this configuration
  # option to your ~/.vagrant.d/Vagrantfile file
  config.berkshelf.enabled = true

  # An array of symbols representing groups of cookbook described in the Vagrantfile
  # to exclusively install and copy to Vagrant's shelf.
  # config.berkshelf.only = []

  # An array of symbols representing groups of cookbook described in the Vagrantfile
  # to skip installing and copying to Vagrant's shelf.
  # config.berkshelf.except = []

  config.vm.provision :chef_solo do |chef|
    chef.json = {
      mysql: {
        server_root_password: 'rootpass',
        server_debian_password: 'debpass',
        server_repl_password: 'replpass'
      }
    }

    chef.run_list = [
      'recipe[base::default]'
    ]
  end
end
```
What would be the fix for this if adding more ram can't help?
Oh and i can run this cookbook on a real production server and it works. Seems something to do with he VM that i have or chef-solo/vagrant
## Stacktrace

The stack trace is as follows:
```
Generated at 2016-05-09 09:57:21 -0400
NoMethodError: yum_package[epel-release] (base::epel line 1) had an error: NoMethodError: undefined method `length' for nil:NilClass
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider/package/yum.rb:59:in `version_parse'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider/package/yum.rb:236:in `initialize'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider/package/yum.rb:252:in `new'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider/package/yum.rb:252:in `parse'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider/package/yum.rb:1218:in `block in install_remote_package'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider/package/yum.rb:1213:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider/package/yum.rb:1213:in `install_remote_package'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider/package/yum.rb:1268:in `install_package'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider/package.rb:101:in `block (2 levels) in action_install'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider/package.rb:227:in `multipackage_api_adapter'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider/package.rb:100:in `block in action_install'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider.rb:176:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider/package.rb:99:in `action_install'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/resource.rb:596:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/client.rb:667:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/client.rb:662:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/client.rb:662:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/client.rb:701:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/client.rb:281:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/application.rb:285:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/application.rb:273:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/application.rb:273:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/application.rb:238:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/application.rb:226:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/application/solo.rb:301:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/application/solo.rb:290:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/application/solo.rb:290:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/application/solo.rb:269:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.38/bin/chef-solo:25:in `<top (required)>'
/bin/chef-solo:52:in `load'
/bin/chef-solo:52:in `<main>'
```

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by lamont-granquist** [comment]
you're not using 12.8.1 you're picking up nightlies and using 12.10.38

should have been fixed by #4912
