### ISSUE TITLE
'knife cookbook show' broken in 12.9.41... undefined method `preferred_manifest_record'

### ISSUE THREAD

**Issue by thechile** [chef/chef#4934]
Using Chef: `12.9.41` when i try to show a cookbook files contents with `knife cookbook show <name> <version> <file_name>` i get the below error:

```
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/knife/cookbook_show.rb:72:in `run': undefined method `preferred_manifest_record' for #<Hash:0x00000002ce3db0> (NoMethodError)
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/knife.rb:421:in `block in run_with_pretty_exceptions'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/local_mode.rb:44:in `with_server_connectivity'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/knife.rb:420:in `run_with_pretty_exceptions'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/knife.rb:219:in `run'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/application/knife.rb:148:in `run'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/bin/knife:25:in `<top (required)>'
        from /usr/bin/knife:51:in `load'
        from /usr/bin/knife:51:in `<main>'
```

Looking at `cookbook_show.rb:72` it's trying to call `preferred_manifest_record` on the returned cookbook version `Hash` object and fails.

```
cookbook = rest.get("cookbooks/#{cookbook_name}/#{cookbook_version}")
manifest_entry = cookbook.preferred_manifest_record(node, segment, filename)
```

**Comment by kisoku** [comment]
How soon can we expect to see this in the current chefdk releases ?

I'm still seeing this as of today

```

**Comment by thechile** [comment]
just FYI this was fixed/working for me using below versions

```
$ /opt/chefdk/embedded/bin/knife -v
Chef: 12.17.44

$ rpm -qa | grep chefdk
chefdk-1.1.16-1.el6.x86_64
```
