### ISSUE TITLE
Failure upgrading to 12.10.24 due to missing multi_xml gem

### ISSUE THREAD

**Issue by eheydrick** [chef/chef#4939]
## Description

Upon upgrading from 12.9.38 to 12.10.24 I am getting an error during compilation related to missing `multi_xml` gem. `multi_xml` is present in chef-client 12.9.38 but not 12.10.24.

## Chef Version

12.10.24

## Platform Version

Ubuntu 14.04 / 16.04

## Replication Case

1. Update to chef-client 12.10.24
2. Run chef-client. 

I have chef_handler 1.3.0 in my runlist.

## Client Output

```
* chef_handler[HipChat::NotifyRoom] action enable
    - disable HipChat::NotifyRoom as a exception handler
    ================================================================================
    Error executing action `enable` on resource 'chef_handler[HipChat::NotifyRoom]'
    ================================================================================

    Gem::MissingSpecError
    ---------------------
    Could not find 'multi_xml' (>= 0.5.2) among 87 total gem(s)
    Checked in 'GEM_PATH=/home/eric/.gem/ruby/2.1.0:/opt/chef/embedded/lib/ruby/gems/2.1.0', execute `gem env` for more information

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/chef_handler/providers/default.rb:40:in `block (2 levels) in class_from_file'
    /var/chef/cache/cookbooks/chef_handler/providers/default.rb:39:in `block in class_from_file'
    /var/chef/cache/cookbooks/hipchat/recipes/handler.rb:54:in `from_file'
    /var/chef/cache/cookbooks/praesidio-chef-client/recipes/hipchat_handler.rb:15:in `from_file'
    /var/chef/cache/cookbooks/praesidio-chef-client/recipes/default.rb:10:in `from_file'
```

## Stacktrace

https://gist.github.com/eheydrick/d7840f8696d84f79ef55239ade6333d1

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by eheydrick** [comment]
I am using chef_handler and the hipchat cookbook to install a hipchat handler. Here's the wrapper that does that: 

```ruby
include_recipe 'chef_handler'
include_recipe 'hipchat::handler'
```

**Comment by eheydrick** [comment]
#### chef-client 12.9.38: 

```
$ /opt/chef/embedded/bin/gem list multi_xml

*** LOCAL GEMS ***

multi_xml (0.5.5)
```

#### chef-client 12.10.24: 

```
$ /opt/chef/embedded/bin/gem list multi_xml

*** LOCAL GEMS ***
```

**Comment by coderanger** [comment]
This is a structural issue with how Rubygems works, it only checks dependencies when updating/installing a gem. `multi_xml` is a dep of `httparty`, so if you remove `httparty` and allow it to reinstall, it would fix itself. The easier fix is probably make your wrapper forcibly reinstall `multi_xml` as a gem.

**Comment by eheydrick** [comment]
But `multi_xml` was included in the 12.9 omnibus package and removed in 12.10. I did not expect that.

**Comment by coderanger** [comment]
Indeed, we stopped depending on it for Chef, which means deb/rpm yanked the files out from under rubygems which then makes rubygems sadpanda.

**Comment by lamont-granquist** [comment]
I agree the experience is not entirely delightful.  The only halfway good solution I could think of is having chef_gem manually do the work to walk down the dependency tree and fix everything, but I'd fear that code would be ugly and produce more tight coupling to rubygems internals.

**Comment by lamont-granquist** [comment]
I think this use case kind of slides me over to thinking that our deinstall script should simply wipe /opt/chef clean.  Then its the responsibility of the chef cookbook's the user is running to have chef_gem statements which repopulate everything from the prior version in there.

This sort of violates how I think packages and package managers should work, but I think this alleyway we wind up going down is completely untenable because of this use case.

If we wipe /opt/chef then there is a perfectly tenable solution which is that users have to correctly maintain their configuration, then on upgrade it all gets rebuilt, and this dependency issue will not occur and if we remove a dep from chef, the chef_gem installation will fix that.

**Comment by lamont-granquist** [comment]
There are people who will break because of this.

But those people will also be broken every time we bump ruby from 2.1 to 2.2 to 2.3 because all the gem library paths change.

What this change would mean is that instead of breaking them every 10th minor update or so we start committing to breaking them every single update.

**Comment by lamont-granquist** [comment]
I accepted minor'd this because I think anyone we break is already going to get broken anyway, i don't think there's any contract here that we've agreed to which would get broken.

I'd agree we need to shout fairly loudly about this change when we make it.

**Comment by aashley** [comment]
I just did a clean install of ChefDK 0.14.25-1 on ubuntu 16.04 and got this issue, its not just an upgrade issue.

Output of process https://gist.github.com/aashley/d12af1f9f7bb2a76b01c2367f8039130

**Comment by lamont-granquist** [comment]
you need to clear out /home/adama/.chefdk, its still an upgrade issue, but the cruft left over is in your home directory.

that is a much harder problem to solve since nuking people's gems out of their home dirs on an upgrade is pretty rude -- but that problem is with chef-dk and not with this chef/chef

**Comment by lamont-granquist** [comment]
We need to get this done for chef-client and chef-dk for 13.0.0 to at least nuke /opt/chef and /opt/chefdk on upgrade.  It is causing considerable pain in the chef-dk/berkshelf/test-kitchen use cases.

**Comment by lamont-granquist** [comment]
Unfortunately with everything else in Chef 13.0, and with the complexity of sorting out all the differences between different packing systems and where the `rm -rf` has to go here (and all the crazy shit like the way the postrm script on rpms runs after the package has been de-installed and re-installed, so you can't use that even though it seems the obvious place...), and the pile of testing we'd have to do around it, so this slipped to Chef 14.0
