### ISSUE TITLE
Can no longer list multiple specific recipes on chef-client command line

### ISSUE THREAD

**Issue by christinedraper** [chef/chef#4997]
## Description

This used to be valid:
```
chef-client -z vagrant_setup.rb deploy.rb
```
but now leads to an error:
```
ERROR: Cookbook @recipe_files not found. If you're loading @recipe_files from another cookbook, make sure you configure the dependency in your metadata
```

## Chef Version

Chef: 12.9.41

## Platform Version

Ubuntu 14.04

## Replication Case
Two recipes, first of which causes compat_resource gem to be loaded, e.g. chef provisioning recipes such as:
```
recipe1:
with_driver 'vagrant'

with_machine_options :vagrant_options => {
  'vm.box' => 'ubuntu64'
}

recipe2:
machine 'appserver'
```
```
chef-client -z recipe1.rb recipe2.rb
```

## Client Output

```
ERROR: Cookbook @recipe_files not found. If you're loading @recipe_files from another cookbook, make sure you configure the dependency in your metadata
```

## Stacktrace

```
Generated at 2016-06-06 08:55:12 -0500
Chef::Exceptions::CookbookNotFound: Cookbook @recipe_files not found. If you're loading @recipe_files from another cookbook, make sure you configure the dependency in your metadata
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/cookbook/cookbook_collection.rb:39:in `block in initialize'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.14.0/lib/ohai/mash.rb:77:in `yield'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.14.0/lib/ohai/mash.rb:77:in `default'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.14.0/lib/ohai/mash.rb:77:in `default'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/compat_resource-12.9.1/files/lib/chef_compat/monkeypatches/chef/recipe.rb:12:in `[]'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/compat_resource-12.9.1/files/lib/chef_compat/monkeypatches/chef/recipe.rb:12:in `new'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/run_context.rb:373:in `load_recipe_file'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/policy_builder/expand_node_object.rb:100:in `block in setup_run_context'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41/lib/chef/policy_builder/expand_node_object.rb:99:in `each'
<snip>
```
The failure appears to be in the recipe monkeypatch on loading the second recipe, when evaluating
`run_context.cookbook_collection[cookbook_name]`. This raises an error because '@recipe_files' (which is used as the cookbook name when loading the first recipe) is not a valid cookbook. One possible fix would be to check for `Chef::Config[:specific_recipes]` in the monkeypatch.

**Comment by christinedraper** [comment]
Please let me know if I should raise on compat_resource instead. It's sort of a chef-client problem in that `load_recipe_file` is setting an invalid cookbook name in the run_context, but it works ok as long as the compat_resource monkeypatch  isnt there.

**Comment by thommay** [comment]
ping @jkeiser , but yes, agree this looks like a bug in compat_resource more than chef.

**Comment by jkeiser** [comment]
@christinedraper yeah, `compat_resource` is the right place for the issue. Thanks!
