### ISSUE TITLE
Chef-Zolo error message when encountering cookbook shadowing is poor

### ISSUE THREAD

**Issue by arothian** [chef/chef#5024]
## Description

When running chef-solo it dies with undefined method error. Previously this worked fine (although the duplicate cookbooks is probably a weird situation). I think probably just a improved error message about duplicate cookbooks is sufficient.
## Chef Version

12.11.18
## Platform Version

Ubuntu 12.04
## Replication Case

Run chef-solo with two directories on the cookbook path, and have duplicate cookbooks between them.
## Client Output

```
[2016-06-10T18:20:55+00:00] ERROR: #<NameError: undefined local variable or method `seen' for #<Chef::ChefFS::FileSystem::MultiplexedDir:0x00000003d3d238>>
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-12.11.18/lib/chef/chef_fs/file_system/multiplexed_dir.rb:44:in `block in make_child_entry'
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-12.11.18/lib/chef/chef_fs/file_system/multiplexed_dir.rb:40:in `each'
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-12.11.18/lib/chef/chef_fs/file_system/multiplexed_dir.rb:40:in `make_child_entry'
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-12.11.18/lib/chef/chef_fs/file_system/base_fs_object.rb:103:in `child'
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-12.11.18/lib/chef/chef_fs/file_system.rb:103:in `block in resolve_path'
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-12.11.18/lib/chef/chef_fs/file_system.rb:102:in `each'
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-12.11.18/lib/chef/chef_fs/file_system.rb:102:in `resolve_path'
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-12.11.18/lib/chef/chef_fs/chef_fs_data_store.rb:828:in `get_single_cookbook_version'
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-12.11.18/lib/chef/chef_fs/chef_fs_data_store.rb:549:in `list'
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-zero-4.6.2/lib/chef_zero/data_store/v1_to_v2_adapter.rb:83:in `block in list'
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-zero-4.6.2/lib/chef_zero/data_store/v1_to_v2_adapter.rb:113:in `fix_exceptions'
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-zero-4.6.2/lib/chef_zero/data_store/v1_to_v2_adapter.rb:82:in `list'
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-zero-4.6.2/lib/chef_zero/rest_base.rb:99:in `list_data'
...
```

**Comment by lamont-granquist** [comment]
that is cookbook shadowing it is no longer supported.

it was deprecated since 0.10.x sometime, and it is unsupportable with the new chef-solo.

since 12.8.1 there should have been better deprecation warnings.

you can still use chef-solo legacy mode if you really have to in order to use it, but it that will go away for ultimate realsies in 13.

that error message does look crappy though

**Comment by lamont-granquist** [comment]
this got fixed at some point in 14 and in 15 cookbook shadowing is gone and raises with an appropriate message
