### ISSUE TITLE
_unless attribute methods broken in chef 12.12.13

### ISSUE THREAD

**Issue by acondrat** [chef/chef#5094]
## Description

_unless attribute methods broken in chef 12.12.13

## Chef Version

12.12.13

## Platform Version

Centos 6, Centos 7

## Replication Case

$ git clone https://github.com/acondrat/chef-12.12.13-issue
$ cd chef-12.12.13-issue/wrappercookbook/
$ bundle
$ kitchen converge

There are two test kitchen instances:
default-centos-chef-121118 - converged successful
default-centos-chef-121213 - failed

**Comment by mtricolici** [comment]
The same situation here. We're using latest postfix cookbook (it have many default_unless calls). We've upgraded to latest chef version and this issue raised :(

**Comment by legal90** [comment]
I've also run into this with `postgresql` cookbook v3.4.16, on this line:
https://github.com/hw-cookbooks/postgresql/blob/v3.4.16/recipes/server.rb#L44

I've reproduced that issue in `chef-shell`, it looks really weird:
```
chef (12.12.13)> node.default_unless['test']['one'] = 'FOO'
 => "FOO"
chef (12.12.13)> node['test']['one']
 => "FOO"
chef (12.12.13)> node.default_unless['test']['two'] = 'BAR'
 => "BAR"
chef (12.12.13)> node['test']['two']
 => nil
chef (12.12.13)> node.default_unless['test']['three'] = 'BAZZ'
=> "BAZZ"
chef (12.12.13)> node['test']['three']
=> nil
```
As you can see, only the first assignment works fine. However, `#debug_value` shows that all these 3 attributes have their default values:

```
chef (12.12.13)> node.debug_value('test', 'one')
 => [["default", "FOO"], ["env_default", :not_present], ["role_default", :not_present], ["force_default", :not_present], ["normal", :not_present], ["override", :not_present], ["role_override", :not_present], ["env_override", :not_present], ["force_override", :not_present], ["automatic", :not_present]]
chef (12.12.13)> node.debug_value('test', 'two')
 => [["default", "BAR"], ["env_default", :not_present], ["role_default", :not_present], ["force_default", :not_present], ["normal", :not_present], ["override", :not_present], ["role_override", :not_present], ["env_override", :not_present], ["force_override", :not_present], ["automatic", :not_present]]
chef (12.12.13)> node.debug_value('test', 'three')
 => [["default", "BAZZ"], ["env_default", :not_present], ["role_default", :not_present], ["force_default", :not_present], ["normal", :not_present], ["override", :not_present], ["role_override", :not_present], ["env_override", :not_present], ["force_override", :not_present], ["automatic", :not_present]]
```

On Chef Client 12.11.18 everything works fine:
```
chef (12.11.18)> node.default_unless['test']['one'] = 'FOO'
 => "FOO"
chef (12.11.18)> node['test']['one']
 => "FOO"
chef (12.11.18)> node.default_unless['test']['two'] = 'BAR'
 => "BAR"
chef (12.11.18)> node['test']['two']
 => "BAR"
```

Seems like it is caused by https://github.com/chef/chef/pull/5029
Since it breaks the backward compatibility, then probably it makes sense to revoke 12.12.13 from "stable".
cc: @lamont-granquist

**Comment by coderanger** [comment]
Ping @chef/client-core for possible high-priority issue.

**Comment by btm** [comment]
@legal90 we don't default to yanking releases because that causes other problems. we're investigating now.

https://github.com/chef/chef-rfc/blob/master/rfc047-release-process.md#critical-regression-handling

**Comment by cwebberOps** [comment]
I am seeing the same issues with the postfix cookbook and can replicate.

**Comment by btm** [comment]
The chef-shell repro case bisects down to 86fa507226b484a71a45ef6129840bc3928be6b7 from #5029 as @legal90 suggested.

**Comment by lamont-granquist** [comment]
Its a failure to reset the deep merge cache:

```
chef (12.12.13)> node.default_unless['test']['one'] = 'FOO'
 => "FOO"
chef (12.12.13)> pp node.debug_value('test')
[["default", {"one"=>"FOO"}],
 ["env_default", :not_present],
 ["role_default", :not_present],
 ["force_default", :not_present],
 ["normal", :not_present],
 ["override", :not_present],
 ["role_override", :not_present],
 ["env_override", :not_present],
 ["force_override", :not_present],
 ["automatic", :not_present]]
chef (12.12.13)> node['test']['one']
 => "FOO"
chef (12.12.13)> node.default_unless['test']['two'] = 'BAR'
 => "BAR"
chef (12.12.13)> pp node.debug_value('test')
[["default", {"one"=>"FOO", "two"=>"BAR"}],
 ["env_default", :not_present],
 ["role_default", :not_present],
 ["force_default", :not_present],
 ["normal", :not_present],
 ["override", :not_present],
 ["role_override", :not_present],
 ["env_override", :not_present],
 ["force_override", :not_present],
 ["automatic", :not_present]]
chef (12.12.13)> node['test']['two']
 => nil
chef (12.12.13)> node.default['test']['two']
 => "BAR"
```

**Comment by btm** [comment]
@lamont-granquist, not sure if this helps or not:

same result from the unchain decorator:
```
chef (12.12.21)> node.default_unless("test2", "one", 'FOO')
 => "FOO" 
chef (12.12.21)> node['test2']['one']
 => "FOO" 
chef (12.12.21)> node.default_unless("test2", "two", 'BAR')
 => "BAR" 
chef (12.12.21)> node['test2']['two']
 => nil 
```

but looks like `node.read` is unaffected:
```
node.default_unless("test3", "one", 'FOO')
node.read("test3","one")
node.default_unless("test3", "two", 'BAR')
node.read("test3","two")
```

**Comment by lamont-granquist** [comment]
well that's weird because all it does now is call `#write()` and all `#write()` ultimately does is call `#[]=` and `#[]=` works fine, and i added explicit tests around the `#write()` case to ensure it was flushing the correct cache value...

**Comment by btm** [comment]
@lamont-granquist there is a behavior related to `[]` being called in between `default_unless`. This symptom also does not occur if you set both attributes without accessing the first with `[]` in between, e.g.

```
chef (12.12.21)> node.default_unless['test']['one'] = 'FOO'
 => "FOO" 
chef (12.12.21)> node.default_unless['test']['two'] = 'BAR'
 => "BAR" 
chef (12.12.21)> node['test']['one']
 => "FOO" 
chef (12.12.21)> node['test']['two']
 => "BAR" 
```

**Comment by lamont-granquist** [comment]
yeah that sort of half makes sense.  you have to hit `#[]` in order to generate the deep merge cache.

at the same time the second default_unless should call node.read() to see if the attr is set, which should go through #[] which should create the deep merge cache.

that may actually be a separate bug (or both might have the same underlying cause).

**Comment by btm** [comment]
@lamont-granquist top_level_breadcrumb is being set to `tags` (early in the run and is never reset?), so when we reset the cache we're not resetting the right part of cache.

https://github.com/chef/chef/blob/master/lib/chef/node/attribute_collections.rb#L149

**Comment by lamont-granquist** [comment]
ah yeah of course.  the lower-level APIs are all working fine, its just node.default_unless and friends aren't setting that to nil any more because i deleted those lines without thinking about it...

patch will be pretty easy, i'll have it a bit after standup...

**Comment by lamont-granquist** [comment]
(next up for 12.13.x will be killing off that stupid top_level_breadcrumb)

**Comment by btm** [comment]
this works for me:

```
diff --git a/lib/chef/node.rb b/lib/chef/node.rb
index 54faab6..e65a7a3 100644
--- a/lib/chef/node.rb
+++ b/lib/chef/node.rb
@@ -191,6 +191,7 @@ class Chef
 
     # Return an attribute of this node.  Returns nil if the attribute is not found.
     def [](attrib)
+      attributes.top_level_breadcrumb = nil
       attributes[attrib]
     end
 
```

**Comment by btm** [comment]
it looks like that's forcing it to work though, there's a more nuanced fix.

**Comment by btm** [comment]
this is closer:
```
diff --git a/lib/chef/node/attribute.rb b/lib/chef/node/attribute.rb
index 09c78c6..ca96c37 100644
--- a/lib/chef/node/attribute.rb
+++ b/lib/chef/node/attribute.rb
@@ -428,18 +428,22 @@ class Chef
       end
 
       def write(level, *args, &block)
+        @top_level_breadcrumb = nil
         self.send(level).write(*args, &block)
       end
 
       def write!(level, *args, &block)
+        @top_level_breadcrumb = nil
         self.send(level).write!(*args, &block)
       end
 
       def unlink(level, *path)
+        @top_level_breadcrumb = nil
         self.send(level).unlink(*path)
       end
 
       def unlink!(level, *path)
+        @top_level_breadcrumb = nil
         self.send(level).unlink!(*path)
       end
```

**Comment by lamont-granquist** [comment]
^ i think the major issue with your version is that while you've fixed `node.write(:default, *stuff)` it leaves `node.default.write(*stuff)` broken.

**Comment by btm** [comment]
yeah, saw that, I hadn't found `common_api.rb` yet.

**Comment by mwrock** [comment]
for those affected by this, we have released 12.12.15 that contain's @lamont-granquist 's fix.Its in the stable channel now. You can get it via:

```
https://omnitruck.chef.io/install.sh | sudo bash -s -- -c stable -P chef -v 12.12.15
```
or
```
. { iwr -useb https://omnitruck.chef.io/install.ps1 } | iex; install -channel stable -project chef -version 12.12.15
```

and we anticipate it hitting our downloads page later tonight at which point we will officially announce the release.

**Comment by timurb** [comment]
I see the same issue in 12.12.15:
```
Generated at 2016-07-11 21:23:40 +0300
NoMethodError: undefined method `newrelic' for #<Chef::Decorator::Unchain:0x00000002f54e50>
/var/chef/cache/cookbooks/basesystem/attributes/default.rb:63:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/dsl/include_attribute.rb:39:in `block in include_attribute'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/dsl/include_attribute.rb:31:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/dsl/include_attribute.rb:31:in `include_attribute'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/run_context/cookbook_compiler.rb:181:in `load_attribute_file'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/run_context/cookbook_compiler.rb:170:in `load_attributes_from_cookbook'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/run_context/cookbook_compiler.rb:110:in `block in compile_attributes'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/run_context/cookbook_compiler.rb:109:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/run_context/cookbook_compiler.rb:109:in `compile_attributes'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/run_context/cookbook_compiler.rb:72:in `compile'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/run_context.rb:176:in `load'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/client.rb:510:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/client.rb:280:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application.rb:286:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application.rb:274:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application.rb:274:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application.rb:239:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application.rb:227:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application/client.rb:456:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application/client.rb:443:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application/client.rb:442:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application/client.rb:442:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application/client.rb:426:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:52:in `load'
/usr/bin/chef-client:52:in `<main>'
```

The line crashing is the following in `attributes/default.rb` for reference:
```
default_unless.newrelic.enable = true
```

I saw the same exception in 12.12.13 while in 12.11.18 it worked with no errors.

**Comment by btm** [comment]
@timurb that sounds like a different bug. Can you try `default_unless['newrelic']['enable'] = true and confirm that works, then file this as a new bug?

**Comment by timurb** [comment]
Yep, looks like that. Bracketed notation works fine here but I see some errors (not exceptions) in other dotted places. Created https://github.com/chef/chef/issues/5102 for that.

**Comment by lamont-granquist** [comment]
this should be fixed, any new bugs needs new issues, if there's any issues with the fix it also needs to go in a new issue, locking...
