### ISSUE TITLE
Error executing action `install` on resource 'homebrew_package[httpd]'

### ISSUE THREAD

**Issue by monajalal** [chef/chef#5101]
Disclaimer: total newbie, was following page 55 of https://surge.omniti.com/2014/presentations/IntroductionToChef_NathenHarvey.pdf and this happened!
```
Monas-MacBook-Pro:lab2 mona$ sudo chef-apply apache.rb
Password:
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * homebrew_package[httpd] action install
    
    ================================================================================
    Error executing action `install` on resource 'homebrew_package[httpd]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of brew info --json=v1 httpd ----
    STDOUT: 
    STDERR: Error: No available formula with the name "httpd"
    ---- End output of brew info --json=v1 httpd ----
    Ran brew info --json=v1 httpd returned 1
    
    Resource Declaration:
    ---------------------
    # In apache.rb
    
      1: package "httpd"
    
    Compiled Resource:
    ------------------
    # Declared in apache.rb:1:in `run_chef_recipe'
    
    homebrew_package("httpd") do
      package_name "httpd"
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :package
      cookbook_name "(chef-apply cookbook)"
      recipe_name "(chef-apply recipe)"
    end
    
    Platform:
    ---------
    x86_64-darwin13.0
    
[2016-07-11T00:20:28-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-07-11T00:20:28-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-07-11T00:20:28-05:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: homebrew_package[httpd] ((chef-apply cookbook)::(chef-apply recipe) line 1) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of brew info --json=v1 httpd ----
STDOUT: 
STDERR: Error: No available formula with the name "httpd"
---- End output of brew info --json=v1 httpd ----
Ran brew info --json=v1 httpd returned 1
```

OS is : 
```
Monas-MacBook-Pro:lab2 mona$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F1713
```

I changed apache.rb after reading this answer: http://stackoverflow.com/a/34245227/2414957

```
 apache.rb                                                                      
  1 package "apache2"
```

But I get this error:
```
Monas-MacBook-Pro:lab2 mona$ sudo chef-apply apache.rb
Password:
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * homebrew_package[apache2] action install
    
    ================================================================================
    Error executing action `install` on resource 'homebrew_package[apache2]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of brew info --json=v1 apache2 ----
    STDOUT: 
    STDERR: Error: No available formula with the name "apache2"
    ---- End output of brew info --json=v1 apache2 ----
    Ran brew info --json=v1 apache2 returned 1
    
    Resource Declaration:
    ---------------------
    # In apache.rb
    
      1: package "apache2"
    
    Compiled Resource:
    ------------------
    # Declared in apache.rb:1:in `run_chef_recipe'
    
    homebrew_package("apache2") do
      package_name "apache2"
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :package
      cookbook_name "(chef-apply cookbook)"
      recipe_name "(chef-apply recipe)"
    end
    
    Platform:
    ---------
    x86_64-darwin13.0
    
[2016-07-11T00:38:18-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-07-11T00:38:18-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-07-11T00:38:18-05:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: homebrew_package[apache2] ((chef-apply cookbook)::(chef-apply recipe) line 1) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of brew info --json=v1 apache2 ----
STDOUT: 
STDERR: Error: No available formula with the name "apache2"
---- End output of brew info --json=v1 apache2 ----
Ran brew info --json=v1 apache2 returned 1
```

**Comment by coderanger** [comment]
This tracker is for bug reports, not user support. Please ask support questions on Slack or Discourse.
