### ISSUE TITLE
set_unless in dot notation causes Chef crashes

### ISSUE THREAD

**Issue by timurb** [chef/chef#5102]
## Description

When attributes are used in dotted notation Chef produces crash with `default_unless`:
```
default_unless.foo = "bar"
```

## Chef Version

I see this crash on 12.12.13 and 12.12.15 but don't see it on 12.11.18

## Platform Version

Ubuntu 14.04

## Replication Case

```
root@vm108842:~# chef-client
Starting Chef Client, version 12.12.15
resolving cookbooks for run list: ["foo"]
Synchronizing Cookbooks:
  - foo (0.2.14)
Installing Cookbook Gems:
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/foo/attributes/default.rb
================================================================================

NoMethodError
-------------
undefined method `foo=' for #<Chef::Decorator::Unchain:0x00000006cc1860>

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/foo/attributes/default.rb:1:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/foo/attributes/default.rb:

  1>> default_unless.foo = 'bar'
  2:

Platform:
---------
x86_64-linux


Running handlers:
  - MailHandler
  - MailHandler
Running handlers complete
Chef Client failed. 0 resources updated in 20 seconds
```

To reproduce simply create cookbook `foo` with the above line in `attributes/default.rb`

## Client Output

```
root@vm108842:~# chef-client -l debug
Starting Chef Client, version 12.12.15
resolving cookbooks for run list: ["foo"]
Synchronizing Cookbooks:
  - foo (0.2.14)
Installing Cookbook Gems:
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/foo/attributes/default.rb
================================================================================

NoMethodError
-------------
undefined method `foo=' for #<Chef::Decorator::Unchain:0x0000000360c6d0>

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/foo/attributes/default.rb:1:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/foo/attributes/default.rb:

  1>> default_unless.foo = 'bar'
  2:

Platform:
---------
x86_64-linux


Running handlers:
  - MailHandler
  - MailHandler
Running handlers complete
Chef Client failed. 0 resources updated in 04 seconds
````

**Comment by btm** [comment]
@timurb can you try out 12.13.2+ from current? The fix from #5103 is in that build.

```
$ curl -L https://omnitruck.chef.io/install.sh | sudo bash -s -- -v 12.13.2 -c current
```

**Comment by timurb** [comment]
@btm this worked fine for me, thanks! Any ETA for releasing that in mainline?

**Comment by btm** [comment]
Sometime this week, we've got to sort out a nokogiri issue and then try to
get a patch build.
