### ISSUE TITLE
lib/chef/provider/package/zypper.rb regex not compatible with zypper version 1.13.*

### ISSUE THREAD

**Issue by yeoldegrove** [chef/chef#5110]
## Description

The regex used in lib/chef/provider/package/zypper.rb are not compatible with zypper version 1.13.* introduced in e.g. Suse Linux Enterprise Server 12 SP2.

## Chef Version

12.12.15

## Platform Version

Suse Linux Enterprise Server 12 SP2

## Replication Case

Have zypper version 1.13.* installed and try to run any resouce installing a package.

## Client Output
[..]

```
Recipe: ntp::ntp
  * zypper_package[ntp] action install
    * No candidate version available for ntp
  ================================================================================
    Error executing action `install` on resource 'zypper_package[ntp]'
    ================================================================================
    
    Chef::Exceptions::Package
    -------------------------
    No candidate version available for ntp
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/ntp/recipes/ntp.rb
    
     20:     package p do
     21:       action :install
     22:     end
     23:   end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/ntp/recipes/ntp.rb:20:in `block in from_file'
    
    zypper_package("ntp") do
      package_name "ntp"
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :package
      cookbook_name "ntp"
      recipe_name "ntp"
    end
    
    Platform:
    ---------
    x86_64-linux


Running handlers:
Running handlers complete
Chef Client failed. 2 resources updated in 06 seconds
```

**Comment by yeoldegrove** [comment]
This is fixed in #5109
