### ISSUE TITLE
Yum multipackage command resulting in empty package list

### ISSUE THREAD

**Issue by coderanger** [chef/chef#5112]
## Description

Seeing an issue in a Bloomberg recipe where the yum provider is trying to run yum install with no package names.
## Chef Version

Reproduced in 12.11.
## Platform Version

RHEL 7.2.
## Replication Case

``` ruby
package ['xfsdump', 'xfsprogs-debuginfo', 'xfsprogs-devel', 'xfsdump-debuginfo', 'xfsprogs-qa-devel', 'xfsprogs', 'valgrind', 'valgrind.i686', 'protobuf-c', 'libunwind', 'openssl', 'readline', 'sqlite', 'libuuid', 'zlib']
```
## Client Output

```
[2016-07-14T17:11:37-04:00] INFO: Processing yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] action install (applications::comdb2 line 4)
[2016-07-14T17:11:37-04:00] DEBUG: Providers for generic yum_package resource enabled on node include: [Chef::Provider::Package::Yum]
[2016-07-14T17:11:37-04:00] DEBUG: Provider for action install on resource yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] is Chef::Provider::Package::Yum
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] checking yum info for ["xfsdump", "xfsprogs-debuginfo", "xfsprogs-devel", "xfsdump-debuginfo", "xfsprogs-qa-devel", "xfsprogs", "valgrind", "valgrind.i686", "protobuf-c", "libunwind", "openssl", "readline", "sqlite", "libuuid", "zlib"]
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] checking yum info for ["xfsdump", "xfsprogs-debuginfo", "xfsprogs-devel", "xfsdump-debuginfo", "xfsprogs-qa-devel", "xfsprogs", "valgrind", "valgrind.i686", "protobuf-c", "libunwind", "openssl", "readline", "sqlite", "libuuid", "zlib"]
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] checking yum info for ["xfsdump", "xfsprogs-debuginfo", "xfsprogs-devel", "xfsdump-debuginfo", "xfsprogs-qa-devel", "xfsprogs", "valgrind", "valgrind.i686", "protobuf-c", "libunwind", "openssl", "readline", "sqlite", "libuuid", "zlib"]
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] checking yum info for ["xfsdump", "xfsprogs-debuginfo", "xfsprogs-devel", "xfsdump-debuginfo", "xfsprogs-qa-devel", "xfsprogs", "valgrind", "valgrind.i686", "protobuf-c", "libunwind", "openssl", "readline", "sqlite", "libuuid", "zlib"]
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] checking yum info for ["xfsdump", "xfsprogs-debuginfo", "xfsprogs-devel", "xfsdump-debuginfo", "xfsprogs-qa-devel", "xfsprogs", "valgrind", "valgrind.i686", "protobuf-c", "libunwind", "openssl", "readline", "sqlite", "libuuid", "zlib"]
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] checking yum info for ["xfsdump", "xfsprogs-debuginfo", "xfsprogs-devel", "xfsdump-debuginfo", "xfsprogs-qa-devel", "xfsprogs", "valgrind", "valgrind.i686", "protobuf-c", "libunwind", "openssl", "readline", "sqlite", "libuuid", "zlib"]
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] checking yum info for ["xfsdump", "xfsprogs-debuginfo", "xfsprogs-devel", "xfsdump-debuginfo", "xfsprogs-qa-devel", "xfsprogs", "valgrind", "valgrind.i686", "protobuf-c", "libunwind", "openssl", "readline", "sqlite", "libuuid", "zlib"]
[2016-07-14T17:11:37-04:00] DEBUG: Parsed out arch i686, new package name is valgrind
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] checking yum info for ["xfsdump", "xfsprogs-debuginfo", "xfsprogs-devel", "xfsdump-debuginfo", "xfsprogs-qa-devel", "xfsprogs", "valgrind", "valgrind", "protobuf-c", "libunwind", "openssl", "readline", "sqlite", "libuuid", "zlib"].i686
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] checking yum info for ["xfsdump", "xfsprogs-debuginfo", "xfsprogs-devel", "xfsdump-debuginfo", "xfsprogs-qa-devel", "xfsprogs", "valgrind", "valgrind", "protobuf-c", "libunwind", "openssl", "readline", "sqlite", "libuuid", "zlib"]
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] checking yum info for ["xfsdump", "xfsprogs-debuginfo", "xfsprogs-devel", "xfsdump-debuginfo", "xfsprogs-qa-devel", "xfsprogs", "valgrind", "valgrind", "protobuf-c", "libunwind", "openssl", "readline", "sqlite", "libuuid", "zlib"]
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] checking yum info for ["xfsdump", "xfsprogs-debuginfo", "xfsprogs-devel", "xfsdump-debuginfo", "xfsprogs-qa-devel", "xfsprogs", "valgrind", "valgrind", "protobuf-c", "libunwind", "openssl", "readline", "sqlite", "libuuid", "zlib"]
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] checking yum info for ["xfsdump", "xfsprogs-debuginfo", "xfsprogs-devel", "xfsdump-debuginfo", "xfsprogs-qa-devel", "xfsprogs", "valgrind", "valgrind", "protobuf-c", "libunwind", "openssl", "readline", "sqlite", "libuuid", "zlib"]
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] checking yum info for ["xfsdump", "xfsprogs-debuginfo", "xfsprogs-devel", "xfsdump-debuginfo", "xfsprogs-qa-devel", "xfsprogs", "valgrind", "valgrind", "protobuf-c", "libunwind", "openssl", "readline", "sqlite", "libuuid", "zlib"]
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] checking yum info for ["xfsdump", "xfsprogs-debuginfo", "xfsprogs-devel", "xfsdump-debuginfo", "xfsprogs-qa-devel", "xfsprogs", "valgrind", "valgrind", "protobuf-c", "libunwind", "openssl", "readline", "sqlite", "libuuid", "zlib"]
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] checking yum info for ["xfsdump", "xfsprogs-debuginfo", "xfsprogs-devel", "xfsdump-debuginfo", "xfsprogs-qa-devel", "xfsprogs", "valgrind", "valgrind", "protobuf-c", "libunwind", "openssl", "readline", "sqlite", "libuuid", "zlib"]
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] installed version: ["3.1.4-1.el7", "3.2.2-2.el7", "3.2.2-2.el7", "3.1.4-1.el7", "3.2.2-2.el7", "3.2.2-2.el7", "3.10.0-16.el7", nil, "1.0.2-2.el7", "1.1-10.el7", "1.0.1e-51.el7_2.1", "6.2-9.el7", "3.7.17-8.el7", "2.23.2-26.el7", "1.2.7-15.el7"] candidate version: ["3.1.4-1.el7", "3.2.2-2.el7", "3.2.2-2.el7", "3.1.4-1.el7", "3.2.2-2.el7", "3.2.2-2.el7", "3.10.0-16.el7", "3.10.0-16.el7", "1.0.2-2.el7", "1.1-10.el7", "1.0.1e-51.el7_2.1", "6.2-9.el7", "3.7.17-8.el7", "2.23.2-26.el7", "1.2.7-15.el7"]
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] xfsdump 3.1.4-1.el7 already installed
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] xfsprogs-debuginfo 3.2.2-2.el7 already installed
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] xfsprogs-devel 3.2.2-2.el7 already installed
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] xfsdump-debuginfo 3.1.4-1.el7 already installed
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] xfsprogs-qa-devel 3.2.2-2.el7 already installed
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] xfsprogs 3.2.2-2.el7 already installed
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] valgrind 3.10.0-16.el7 already installed
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] valgrind not installed, installing 3.10.0-16.el7
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] protobuf-c 1.0.2-2.el7 already installed
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] libunwind 1.1-10.el7 already installed
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] openssl 1.0.1e-51.el7_2.1 already installed
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] readline 6.2-9.el7 already installed
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] sqlite 3.7.17-8.el7 already installed
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] libuuid 2.23.2-26.el7 already installed
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] zlib 1.2.7-15.el7 already installed
[2016-07-14T17:11:37-04:00] INFO: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] installing
[2016-07-14T17:11:37-04:00] DEBUG: yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib]: yum command: "yum -d0 -e0 -y install "
[2016-07-14T17:11:37-04:00] INFO: Running queued delayed notifications before re-raising exception
[2016-07-14T17:11:37-04:00] DEBUG: Re-raising exception: Chef::Exceptions::Exec - yum_package[xfsdump, xfsprogs-debuginfo, xfsprogs-devel, xfsdump-debuginfo, xfsprogs-qa-devel, xfsprogs, valgrind, valgrind.i686, protobuf-c, libunwind, openssl, readline, sqlite, libuuid, zlib] (applications::comdb2 line 4) had an error: Chef::Exceptions::Exec: yum -d0 -e0 -y install  returned 1:
STDOUT:
STDERR: Error: Need to pass a list of pkgs to install
 Mini usage:

install PACKAGE...

Install a package or packages on your system

aliases: install-n, install-na, install-nevra

/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/provider/package/yum.rb:122:in `yum_command'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/provider/package/yum.rb:302:in `install_remote_package'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/provider/package/yum.rb:313:in `install_package'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/provider/package.rb:101:in `block (2 levels) in action_install'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/provider/package.rb:227:in `multipackage_api_adapter'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/provider/package.rb:100:in `block in action_install'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/mixin/why_run.rb:52:in `add_action'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/provider.rb:176:in `converge_by'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/provider/package.rb:99:in `action_install'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/provider.rb:145:in `run_action'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/resource.rb:591:in `run_action'
  /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/runner.rb:97:in `block (2 levels) in converge'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/runner.rb:97:in `each'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/runner.rb:97:in `block in converge'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/runner.rb:96:in `converge'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/client.rb:669:in `block in converge'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/client.rb:664:in `catch'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/client.rb:664:in `converge'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/client.rb:703:in `converge_and_save'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/client.rb:283:in `run'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/application.rb:268:in `run_with_graceful_exit_option'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/application.rb:244:in `block in run_chef_client'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/local_mode.rb:44:in `with_server_connectivity'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/application.rb:227:in `run_chef_client'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/application/client.rb:419:in `run_application'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/application.rb:59:in `run'
  /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/bin/chef-client:26:in `<top (required)>'
  /bin/chef-client:52:in `load'
  /bin/chef-client:52:in `<main>'
```

**Comment by coderanger** [comment]
My guess is this is related to the `valgrind.i686` in the package. The logs for it are definitely weird looking at least:

```
valgrind 3.10.0-16.el7 already installed
valgrind not installed, installing 3.10.0-16.el7
```

Maybe we have some bugs related to alternate arch handling with yum?

**Comment by coderanger** [comment]
May also be related to https://github.com/chef/chef/issues/3476

**Comment by lamont-granquist** [comment]
this is most likely because the provider does not use `use_multipackage_api`
