### ISSUE TITLE
user creation failed because user does not previously exist?

### ISSUE THREAD

**Issue by snebel29** [chef/chef#5137]
## Description

user resource fails to create a local system user because this does not exist within /etc/passwd,  the command issued by chef is usermod

```
usermod -c 'perundeck user' -u '5011' -m -d '/home/perundeck/perundeck' perundeck returned 6, expected 0
```

## Chef Version
```
INFO: *** Chef 11.4.4 ***
```
## Platform Version
```
$ cat /etc/redhat-release 
CentOS Linux release 7.1.1503 (Core)
```
## Replication Case

Create cookbook with a default recipe and the following code

```
##### Create the new local user

username = 'perundeck'
uid = 5011

user "#{username}" do
  action :create
  supports :manage_home => true
  comment "#{username} user"
  uid uid
  home "/home/perundeck/#{username}"
  shell '/bin/bash'
  system true
end
```

run sudo chef-client

## Client Output

```
  * user[perundeck] action create[2016-07-25T06:05:36-07:00] INFO: Processing user[perundeck] action create (ask-pedeploy-test::default line 56)

================================================================================
Error executing action `create` on resource 'user[perundeck]'
================================================================================


Chef::Exceptions::Exec
----------------------
usermod -c 'perundeck user' -u '5011' -m -d '/home/perundeck/perundeck' perundeck returned 6, expected 0


Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/ask-pedeploy-test/recipes/default.rb

 56: user "#{username}" do
 57:   action :create
 58:   supports :manage_home => true
 59:   comment "#{username} user"
 60:   uid uid
 61:   home "/home/perundeck/#{username}"
 62:   shell '/bin/bash'
 63:   system true
 64: end
 65: 



Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/ask-pedeploy-test/recipes/default.rb:56:in `from_file'

user("perundeck") do
  action [:create]
  supports {:manage_home=>true}
  retries 0
  retry_delay 2
  username "perundeck"
  comment "perundeck user"
  uid 5011
  home "/home/perundeck/perundeck"
  shell "/bin/bash"
  system true
  cookbook_name "ask-pedeploy-test"
  recipe_name "default"
end



[2016-07-25T06:05:36-07:00] INFO: Running queued delayed notifications before re-raising exception
[2016-07-25T06:05:36-07:00] ERROR: Running exception handlers
[2016-07-25T06:05:36-07:00] FATAL: Saving node information to /var/chef/cache/failed-run-data.json
[2016-07-25T06:05:36-07:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated
[2016-07-25T06:05:36-07:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-07-25T06:05:36-07:00] FATAL: Chef::Exceptions::Exec: user[perundeck] (ask-pedeploy-test::default line 56) had an error: Chef::Exceptions::Exec: usermod -c 'perundeck user' -u '5011' -m -d '/home/perundeck/perundeck' perundeck returned 6, expected 0
[rundeck@development-rundeck001iad rundeck-resource-generator-from-chef]$ sudo usermod -c 'perundeck user' -u '5011' -m -d '/home/perundeck/perundeck' perundeck
usermod: user 'perundeck' does not exist in /etc/passwd
[rundeck@development-rundeck001iad rundeck-resource-generator-from-chef]$ echo $?
6
```

## Stacktrace

```
Generated at 2016-07-25 06:05:36 -0700
Chef::Exceptions::Exec: user[perundeck] (ask-pedeploy-test::default line 56) had an error: Chef::Exceptions::Exec: usermod -c 'perundeck user' -u '5011' -m -d '/home/perundeck/perundeck' perundeck returned 6, expected 0
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/mixin/command.rb:128:in `handle_command_failures'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/mixin/command.rb:75:in `run_command'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/provider/user/useradd.rb:40:in `manage_user'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/provider/user.rb:129:in `block in action_create'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/mixin/why_run.rb:52:in `call'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/provider.rb:151:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/provider/user.rb:128:in `action_create'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/provider.rb:114:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/resource.rb:606:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/runner.rb:50:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/runner.rb:82:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/runner.rb:82:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/runner.rb:82:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/resource_collection.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/resource_collection.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/runner.rb:81:in `converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/client.rb:404:in `converge'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/client.rb:469:in `do_run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/client.rb:200:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/application.rb:190:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/application/client.rb:297:in `block in run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/application/client.rb:290:in `loop'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/application/client.rb:290:in `run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/lib/chef/application.rb:73:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.4.4/bin/chef-client:26:in `<top (required)>'
/bin/chef-client:23:in `load'
/bin/chef-client:23:in `<main>'
```

**Comment by thommay** [comment]
Please try this with a reasonably modern version of chef.

**Comment by snebel29** [comment]
Hi,
In my organization we still have thousands of nodes using this "legacy" version of chef-client, even if user creation works with a newer version won't fix my problem as I can't just upgrade the whole infrastructure.

If 11.4.4 is not supported anymore I'll create the user using a bash command.

Thanks

**Comment by thommay** [comment]
11.4.4 hasn't been supported for a pretty long time; we do still support Chef 11, but the latest release is 11.18.14 . 
I'm going to go ahead and close this; thanks for your report, and if you do manage to reproduce on latest 11, feel free to reopen.
Thanks,
-Thom

**Comment by eheydrick** [comment]
Does the user exist in LDAP or some other directory per chance? I ran into this issue and turned out the user was in my LDAP directory.
