### ISSUE TITLE
Chef 12.12.15 Upgrade Issue - Error executing action `load` on resource 'bluepill_service[chef-client]'

### ISSUE THREAD

**Issue by sumit-goel** [chef/chef#5139]
## Description

Upgrade chef from version chef-12.9.41-1.el6.x86_64 to chef-12.12.15-1.el6.x86_64 and chef convergence started failing with following error,

```
Recipe: chef-client::bluepill_service
  * template[/etc/bluepill/chef-client.pill] action create (up to date)
  * bluepill_service[chef-client] action enable (up to date)
  * bluepill_service[chef-client] action load

    ================================================================================
    Error executing action `load` on resource 'bluepill_service[chef-client]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/chef/embedded/bin/bluepill load /etc/bluepill/chef-client.pill ----
    STDOUT:
    STDERR: /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/dependency.rb:308:in `to_specs': Could not find 'activesupport' (< 5, >= 3.2) among 130 total gem(s) (Gem::MissingSpecError)
    Checked in 'GEM_PATH=/root/.gem/ruby/2.1.0:/opt/chef/embedded/lib/ruby/gems/2.1.0', execute `gem env` for more information
    	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1439:in `block in activate_dependencies'
    	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1428:in `each'
    	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1428:in `activate_dependencies'
    	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1410:in `activate'
    	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:200:in `rescue in try_activate'
    	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:193:in `try_activate'
    	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
    	from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:40:in `require'
    	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bluepill-0.1.1/bin/bluepill:3:in `<top (required)>'
    	from /opt/chef/embedded/bin/bluepill:22:in `load'
    	from /opt/chef/embedded/bin/bluepill:22:in `<main>'
    ---- End output of /opt/chef/embedded/bin/bluepill load /etc/bluepill/chef-client.pill ----
    Ran /opt/chef/embedded/bin/bluepill load /etc/bluepill/chef-client.pill returned 1

    Cookbook Trace:
    ---------------
    /var/cache/chef/cookbooks/bluepill/providers/service.rb:66:in `block (2 levels) in class_from_file'
    /var/cache/chef/cookbooks/bluepill/providers/service.rb:65:in `block in class_from_file'
    /var/cache/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

    Resource Declaration:
    ---------------------
    # In /var/cache/chef/cookbooks/chef-client/recipes/bluepill_service.rb

     29: bluepill_service 'chef-client' do
     30:   action [:enable, :load, :start]
     31: end

    Compiled Resource:
    ------------------
    # Declared in /var/cache/chef/cookbooks/chef-client/recipes/bluepill_service.rb:29:in `from_file'

    bluepill_service("chef-client") do
      action [:enable, :load, :start]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :bluepill_service
      cookbook_name "chef-client"
      recipe_name "bluepill_service"
      service_name "chef-client"
    end

    Platform:
    ---------
    x86_64-linux
```

## Chef Version

chef-12.12.15-1.el6.x86_64

## Platform Version

RHEL6

## Workaround

Uninstall chef-12.12.15-1.el6.x86_64 and install chef-12.9.41-1.el6.x86_64

**Comment by lamont-granquist** [comment]
we don't ship bluepill and i think activesupport either stopped being shipped with chef or its version is wrong for you now.

rm -rf /opt/chef to clean up the gems deps and reinstall them from scratch should fix it.

dup of other similar upgrade issues.

**Comment by lamont-granquist** [comment]
specifically dup of #4939

**Comment by coderanger** [comment]
More to the point, the bluepill cookbook should not be using Chef's Ruby to manage/install bluepill. This is a bug in the cookbook.

**Comment by lamont-granquist** [comment]
The chef-client cookbook should also probably not support bluepill any more.  It looks like it had its heyday in 2010 and the mailing list has one thread in 2014 and one in 2015 and none in 2016.  Its not quite a dead project but most of the commits are version upgrades and removing old deps and rubocop violations and stuff like that.

**Comment by sumit-goel** [comment]
@lamont-granquist I completely understand that bluepill is not shipped with chef but since bluepill is Chef managed cookbook and as a Chef users I expect Chef managed cookbooks should work fine with any chef client upgrades.

Your suggestion to delete /opt/chef and install the chef did help resolve the issue. Thank you, really appreciate your help.
