### ISSUE TITLE
deploy resource fails with "symlink() function is unimplemented on this machine" on Windows

### ISSUE THREAD

**Issue by maxnasonov** [chef/chef#5143]
## Description

Simple deploy via GIT on Windows with the error.  
## Chef Version

12.9.41
## Platform Version

Windows 2012 R2 Standard
## Replication Case

Use a deploy resource on Windows system.
## Client Output

```
  NotImplementedError
  -------------------
  symlink() function is unimplemented on this machine

  Resource Declaration:
  ---------------------
  # In C:/chef/cache/cookbooks/consul-config/recipes/default.rb

   91:   deploy_branch 'consul-scripts' do
   92:     repo 'git@git.example.com:repo.git'
   93:     deploy_to 'c:\ProgramData\consul\scripts'
   94:     ssh_wrapper ssh_wrapper_path
   95:     branch "master"
   96:     symlink_before_migrate.clear
   97:     create_dirs_before_symlink.clear
   98:     purge_before_symlink.clear
   99:     symlinks.clear
  100:   end
  101:

  Compiled Resource:
  ------------------
  # Declared in C:/chef/cache/cookbooks/consul-config/recipes/default.rb:91:in `from_file'

  deploy_branch("consul-scripts") do
    action [:deploy]
    retries 0
    retry_delay 2
    default_guard_interpreter :default
    deploy_to "c:\\ProgramData\\consul\\scripts"
    repository_cache "cached-copy"
    revision "master"
    remote "origin"
    scm_provider Chef::Provider::Git
    keep_releases 5
    enable_checkout true
    checkout_branch "deploy"
    declared_type :deploy_branch
    cookbook_name "consul-config"
    recipe_name "default"
    repo "git@git.example.com:repo.git"
    git_ssh_wrapper "c:\\users\\administrator\\.ssh\\ssh_wrapper.bat"
    shared_path "c:\\ProgramData\\consul\\scripts/shared"
    destination "c:\\ProgramData\\consul\\scripts/shared/cached-copy"
    current_path "c:\\ProgramData\\consul\\scripts/current"
  end
```
## Stacktrace

```
NotImplementedError: deploy_branch[consul-scripts] (consul-config::default line 91) had an error: NotImplementedError: symlink() function is unimplemented on this machine
C:/opscode/chef/embedded/lib/ruby/2.1.0/fileutils.rb:355:in `symlink'
C:/opscode/chef/embedded/lib/ruby/2.1.0/fileutils.rb:355:in `block in ln_s'
C:/opscode/chef/embedded/lib/ruby/2.1.0/fileutils.rb:1595:in `fu_each_src_dest0'
C:/opscode/chef/embedded/lib/ruby/2.1.0/fileutils.rb:353:in `ln_s'
C:/opscode/chef/embedded/lib/ruby/2.1.0/fileutils.rb:376:in `ln_sf'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/provider/deploy.rb:294:in `block in link_current_release_to_production'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/mixin/why_run.rb:52:in `add_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/provider.rb:175:in `converge_by'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/provider/deploy.rb:290:in `link_current_release_to_production'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/provider/deploy.rb:211:in `symlink'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/provider/deploy.rb:162:in `deploy'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/provider/deploy.rb:109:in `block in action_deploy'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/provider/deploy.rb:440:in `with_rollback_on_error'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/provider/deploy.rb:108:in `action_deploy'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/provider/deploy/revision.rb:39:in `action_deploy'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/provider.rb:144:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/resource.rb:596:in `run_action'
C:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/runner.rb:97:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/resource_collection/resource_list.rb:84:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/resource_collection/resource_list.rb:82:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/runner.rb:96:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/client.rb:667:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/client.rb:662:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/client.rb:662:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/client.rb:701:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/client.rb:281:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/application.rb:267:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/application.rb:243:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/application.rb:226:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/application/client.rb:419:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/lib/chef/application.rb:58:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.41-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:61:in `load'
C:/opscode/chef/bin/chef-client:61:in `<main>'
```

**Comment by stuartpreston** [comment]
The deploy resource was removed in Chef 14 and moved to a Chef Supermarket cookbook (https://supermarket.chef.io/cookbooks/deploy_resource) - closing this.
