### ISSUE TITLE
knife supermarket share doesnt point to private supermarket in any way

### ISSUE THREAD

**Issue by dfduarte** [chef/chef#5147]
## Description

knife supermarket share doesnt point to private supermarket in any way, even using the -m switch, or configuring knife.rb. Problem seen on ubuntu 14.04, and CircleCI.

(Since the supermarket subcomand it's now part of main knife suite, I'm writing the problem down here)

## Chef Version

Chef Development Kit Version: 0.16.28
chef-client version: 12.12.15
delivery version: master (921828facad8a8bbbd767368bfc72f19bd30e7bd)
berks version: 4.3.5
kitchen version: 1.10.2

(I tried to install the old knife-supermarket plugin 0.24 and 0.3.0 as well, but got the same).

## Platform Version

Circle CI (?)
Ubuntu 14.04
OS X El Captain (Note: This Knife version works for some reason)

## Replication Case

Put any cookbooks into your chef-repo folder.
Configure knife.rb with your private supermarket options:

```
# See https://docs.getchef.com/config_rb_knife.html for more information on knife configuration options

current_dir = File.dirname(__FILE__)
log_level                :info
log_location             STDOUT
node_name                "dduarte"
client_key               "#{current_dir}/xxxx.pem"
validation_client_name   "xxxxxx-validator"
validation_key           "#{current_dir}/xxxxx-validator.pem"
chef_server_url          "https://chef-serverxxxx.com/organizations/xxxx"
knife[:supermarket_site] = "https://supermarket.xxxxx.com"
ssl_verify_mode          :verify_none
cookbook_path            ["#{current_dir}/../cookbooks"]
```
Use the knife supermarket share command (with or without -m switch to set the supermarket address).
Watch the command fail miserabily and solely ignoring the -m switch and knife.rb, forcing the upload to the public supermarket (at chef.io).

NOTE: Any other subcomands, like list, search and etc works well.

## Client Output

```
diego@diego-System-Product-Name:~/Downloads/chef-repo$ knife supermarket share test2 -VV
INFO: Using configuration from /home/diego/Downloads/chef-repo/.chef/knife.rb
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating GET to https://supermarket.chef.io/api/v1/cookbooks/test2
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-REMOTE-REQUEST-ID: d66d1a29-b657-4708-897e-761527044f14
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 404 Not Found
DEBUG: cache-control: no-cache
DEBUG: content-encoding: gzip
DEBUG: content-type: application/json; charset=utf-8
DEBUG: date: Fri, 29 Jul 2016 04:58:52 GMT
DEBUG: server: nginx/1.8.1
DEBUG: status: 404 Not Found
DEBUG: x-content-type-options: nosniff
DEBUG: x-frame-options: SAMEORIGIN
DEBUG: x-request-id: 90fd6e3a-aa3e-4d8e-9ed5-6f73cfe7076d
DEBUG: x-runtime: 0.004952
DEBUG: x-xss-protection: 1; mode=block
DEBUG: content-length: 87
DEBUG: connection: Close
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: ---- HTTP Response Body ----
DEBUG: �VJ-*�/��M-.NLO-V��V
J-�/-JNUH�O-V��/QH��,.�S�Ձ�N�OIU�R��w�sQ��?H
DEBUG: ---- End HTTP Response Body -----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: Content-Length validated correctly.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
INFO: HTTP Request Returned 404 Not Found: 
FATAL: Unable to reach Supermarket: 404 "Not Found". Increase log verbosity (-VV) for more information.
DEBUG: 
/opt/chefdk/embedded/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/http.rb:146:in `request'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/http.rb:111:in `get'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/knife/cookbook_site_share.rb:117:in `get_category'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/knife/cookbook_site_share.rb:69:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/knife.rb:421:in `block in run_with_pretty_exceptions'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/knife.rb:420:in `run_with_pretty_exceptions'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/knife.rb:219:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application/knife.rb:148:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/bin/knife:25:in `<top (required)>'
/usr/bin/knife:52:in `load'
/usr/bin/knife:52:in `<main>'
```

The output for knife supermarket list (which works correctly):

```
diego@diego-System-Product-Name:~/Downloads/chef-repo$ knife supermarket list -VV
INFO: Using configuration from /home/diego/Downloads/chef-repo/.chef/knife.rb
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating GET to https://supermarket.xxxxxxxx.com/api/v1/cookbooks?items=10&start=0
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-REMOTE-REQUEST-ID: c3c75396-a11f-4cc7-92fb-58722a0b05e9
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 200 OK
DEBUG: server: nginx/1.8.0
DEBUG: date: Fri, 29 Jul 2016 04:55:10 GMT
DEBUG: content-type: application/json; charset=utf-8
DEBUG: transfer-encoding: chunked
DEBUG: connection: close
DEBUG: status: 200 OK
DEBUG: x-frame-options: SAMEORIGIN
DEBUG: x-xss-protection: 1; mode=block
DEBUG: x-content-type-options: nosniff
DEBUG: etag: W/"114695420651c74a2c17c09cd67bbfaf"
DEBUG: cache-control: max-age=0, private, must-revalidate
DEBUG: x-request-id: fec0ab75-f911-4642-8318-3a268171136c
DEBUG: x-runtime: 0.017274
DEBUG: content-encoding: gzip
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: HTTP server did not include a Content-Length header in response, cannot identify truncated downloads.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating GET to https://supermarket.xxxxxxx.com/api/v1/cookbooks?items=10&start=10
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-REMOTE-REQUEST-ID: c3c75396-a11f-4cc7-92fb-58722a0b05e9
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 200 OK
DEBUG: server: nginx/1.8.0
DEBUG: date: Fri, 29 Jul 2016 04:55:11 GMT
DEBUG: content-type: application/json; charset=utf-8
DEBUG: transfer-encoding: chunked
DEBUG: connection: close
DEBUG: status: 200 OK
DEBUG: x-frame-options: SAMEORIGIN
DEBUG: x-xss-protection: 1; mode=block
DEBUG: x-content-type-options: nosniff
DEBUG: etag: W/"6c429001b46d2b30fc8ca2cc5bf53375"
DEBUG: cache-control: max-age=0, private, must-revalidate
DEBUG: x-request-id: ecfd199f-8337-49a3-b474-ba5c593b33f1
DEBUG: x-runtime: 0.017050
DEBUG: content-encoding: gzip
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: HTTP server did not include a Content-Length header in response, cannot identify truncated downloads.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating GET to https://supermarket.xxxxxx.com/api/v1/cookbooks?items=10&start=20
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-REMOTE-REQUEST-ID: c3c75396-a11f-4cc7-92fb-58722a0b05e9
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 200 OK
DEBUG: server: nginx/1.8.0
DEBUG: date: Fri, 29 Jul 2016 04:55:12 GMT
DEBUG: content-type: application/json; charset=utf-8
DEBUG: transfer-encoding: chunked
DEBUG: connection: close
DEBUG: status: 200 OK
DEBUG: x-frame-options: SAMEORIGIN
DEBUG: x-xss-protection: 1; mode=block
DEBUG: x-content-type-options: nosniff
DEBUG: etag: W/"1e965fa4179c20855b303be38b34a39e"
DEBUG: cache-control: max-age=0, private, must-revalidate
DEBUG: x-request-id: efcd29e8-c345-41b3-a089-b1b578b8198a
DEBUG: x-runtime: 0.014965
DEBUG: content-encoding: gzip
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: HTTP server did not include a Content-Length header in response, cannot identify truncated downloads.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
apache-modproxybypass-falcon2  pdns_parser_enis             
apt                            poise                        
build-essential                poise-service                
chef-sugar                     postgresql                   
chef_handler                   resolvconf                   
compat_resource                rubyzip                      
consul_template                rundeck-cookbook             
cron                           seven_zip                    
database                       squid                        
mingw                          squid-aws                    
nssm                           teste4                       
openssl                        windows                      
pdns                           yum                          
pdns_cookbook                  yum-epel                     
diego@diego-System-Product-Name:~/Downloads/chef-repo$ 
```

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by thommay** [comment]
Thanks for the report. This is a dupliacte of #5092 and was fixed in #5091 . It's due for release in the next version of chef, in a couple of weeks time.
