### ISSUE TITLE
execute a command that requires a root privileges doesn't work properly

### ISSUE THREAD

**Issue by Journerist** [chef/chef#5176]
## Description

After resetting my OS X to an initially state I tried to run my development chef setup. But all recipes that contain any execute commands that requires a user change (usually to "root") doesn't work.

## Chef Version

chef-client version: 12.12.15

## Platform Version

OS X 10.11.6

## Replication Case

create a recipe that contains:

```
execute "chown-usr-local" do
  command "chown -R #{currentUser}:staff /usr/local"
  user "root"
end
```

run chef-client -z -o recipe['yourRecipe']
## Client Output

```
MacBook-Pro:chef-development-setup-master journerist$ chef-client -z -o recipe['git']
[2016-08-07T05:17:01-07:00] WARN: No config file found or specified on command line, using command line options.
Starting Chef Client, version 12.12.15
[2016-08-07T05:17:04-07:00] WARN: Run List override has been provided.
[2016-08-07T05:17:04-07:00] WARN: Original Run List: []
[2016-08-07T05:17:04-07:00] WARN: Overridden Run List: [recipe[git]]
resolving cookbooks for run list: ["git"]
Synchronising Cookbooks:
  - git (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 2 resources
Recipe: git::default
  * execute[chown-usr-local] action run
    - execute chown -R journerist:staff /usr/local
  * homebrew_package[Install Git] action install (up to date)
[2016-08-07T05:17:04-07:00] WARN: Skipping final node save because override_runlist was given

Running handlers:
Running handlers complete
Chef Client finished, 1/2 resources updated in 03 seconds
MacBook-Pro:chef-development-setup-master journerist$ vi cookbooks/git/recipes/default.rb 
MacBook-Pro:chef-development-setup-master journerist$ chef-client -z -o recipe['git']
[2016-08-07T05:17:22-07:00] WARN: No config file found or specified on command line, using command line options.
Starting Chef Client, version 12.12.15
[2016-08-07T05:17:26-07:00] WARN: Run List override has been provided.
[2016-08-07T05:17:26-07:00] WARN: Original Run List: []
[2016-08-07T05:17:26-07:00] WARN: Overridden Run List: [recipe[git]]
resolving cookbooks for run list: ["git"]
Synchronising Cookbooks:
  - git (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 2 resources
Recipe: git::default
  * execute[chown-usr-local] action run
    
    ================================================================================
    Error executing action `run` on resource 'execute[chown-usr-local]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of chown -R journerist:staff /usr/local ----
    STDOUT: 
    STDERR: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:153:in `uid=': Operation not permitted (Errno::EPERM)
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:153:in `set_user'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:332:in `block in fork_subprocess'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:316:in `fork'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:316:in `fork_subprocess'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout/unix.rb:93:in `run_command'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.6/lib/mixlib/shellout.rb:259:in `run_command'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/mixin/shell_out.rb:86:in `shell_out_command'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/mixin/shell_out.rb:39:in `shell_out'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/mixin/shell_out.rb:44:in `shell_out!'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/provider/execute.rb:62:in `block in action_run'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/mixin/why_run.rb:52:in `add_action'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/provider.rb:176:in `converge_by'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/provider/execute.rb:60:in `action_run'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/provider.rb:145:in `run_action'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/resource.rb:591:in `run_action'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/runner.rb:69:in `run_action'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/runner.rb:97:in `block (2 levels) in converge'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/runner.rb:97:in `each'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/runner.rb:97:in `block in converge'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
    	from /opt/chefdk/embedded/lib/ruby/2.1.0/forwardable.rb:183:in `execute_each_resource'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/runner.rb:96:in `converge'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/client.rb:669:in `block in converge'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/client.rb:664:in `catch'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/client.rb:664:in `converge'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/client.rb:703:in `converge_and_save'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/client.rb:283:in `run'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application.rb:286:in `block in fork_chef_client'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application.rb:274:in `fork'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application.rb:274:in `fork_chef_client'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application.rb:239:in `block in run_chef_client'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/local_mode.rb:44:in `with_server_connectivity'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application.rb:227:in `run_chef_client'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application/client.rb:456:in `sleep_then_run_chef_client'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application/client.rb:443:in `block in interval_run_chef_client'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application/client.rb:442:in `loop'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application/client.rb:442:in `interval_run_chef_client'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application/client.rb:426:in `run_application'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application.rb:59:in `run'
    	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/bin/chef-client:26:in `<top (required)>'
    	from /usr/local/bin/chef-client:52:in `load'
    	from /usr/local/bin/chef-client:52:in `<main>'
    ---- End output of chown -R journerist:staff /usr/local ----
```

**Comment by thommay** [comment]
Yes, that's correct behaviour. If you need root privileges, you should run chef using `sudo` or as the root user.
