### ISSUE TITLE
cookbook metadata fails where metadata.json already present

### ISSUE THREAD

**Issue by mrigeshpriyadarshi** [chef/chef#5201]
## Chef Version

Chef Development Kit Version: 0.15.15
chef-client version: 12.11.18
delivery version: 0.0.23 (bf89a6b776b55b89a46bbd57fcaa615c143a09a0)
berks version: 4.3.5
kitchen version: 1.10.0

## Platform Version
Mac Os (workstation)
15.6.0 Darwin Kernel Version 15.6.0

## Replication Case

If we execute "knife cookbook metadata logstash" for the cookbook which already has metadata.json generated, it throws an error instead of validating and updating new changes in the json.

## Stacktrace

```
mac-pro mpriyada$ knife cookbook metadata logstash -VV
INFO: Using configuration from /Users/mpriyada/myWorks/knife.rb
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/cookbook/metadata.rb:644:in `block (2 levels) in validate_json': undefined local variable or method `method_name' for Chef::Cookbook::Metadata:Class (NameError)
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/cookbook/metadata.rb:643:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/cookbook/metadata.rb:643:in `block in validate_json'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/cookbook/metadata.rb:641:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/cookbook/metadata.rb:641:in `validate_json'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/knife/cookbook_metadata.rb:95:in `validate_metadata_json'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/knife/cookbook_metadata.rb:69:in `block in generate_metadata'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/knife/cookbook_metadata.rb:64:in `reverse_each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/knife/cookbook_metadata.rb:64:in `generate_metadata'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/knife/cookbook_metadata.rb:59:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/knife.rb:421:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/knife.rb:420:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/knife.rb:219:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/application/knife.rb:148:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:52:in `load'
	from /opt/chefdk/bin/knife:52:in `<main>'
mac-pro  mpriyada$

```

**Comment by mrigeshpriyadarshi** [comment]
Actually, the below code in metadata.rb (https://github.com/chef/chef/blob/master/lib/chef/cookbook/metadata.rb) is responsible for above error.

```
      def self.validate_json(json_str)
        o = Chef::JSONCompat.from_json(json_str)
        metadata = new()
        VERSION_CONSTRAINTS.each do |dependency_type, hash_key|
          if dependency_group = o[hash_key]
            dependency_group.each do |cb_name, constraints|
              **if metadata.respond_to?(method_name)
                metadata.public_send(method_name, cb_name, *Array(constraints))
              end**
            end
          end
        end
        true
end
```

If we change the "_method_name_" variable to "_dependency_type_", it validates the json.


```
      def self.validate_json(json_str)
        o = Chef::JSONCompat.from_json(json_str)
        metadata = new()
        VERSION_CONSTRAINTS.each do |dependency_type, hash_key|
          if dependency_group = o[hash_key]
            dependency_group.each do |cb_name, constraints|
              if metadata.respond_to?(dependency_type)
                metadata.public_send(dependency_type, cb_name, *Array(constraints))
              end
            end
          end
        end
        true
      end
```

**Comment by lamont-granquist** [comment]
dup of #4428
