### ISSUE TITLE
chef-client service does not log INFO messages

### ISSUE THREAD

**Issue by runningman84** [chef/chef#5273]
If I run chef-client from the shell everything looks fine:
```
root@ip-172-31-10-xx:/var/log/chef# chef-client 
Starting Chef Client, version 12.13.37
resolving cookbooks for run list: ["***-***::default"]
Synchronizing Cookbooks:
  - 7-zip (1.0.2)
  - asy-*** (0.5.38)
  - nginx (2.7.6)
  - python (1.4.6)
  - ntp (2.0.3)
  - sudo (2.7.2)
  - compat_resource (12.14.0)
  - aws (3.4.1)
  - user_shadow (0.1.5)
  - user (0.4.2)
  - rackspace_users (0.2.8)
  - sensu (3.0.0)
  - apt (2.9.2)
  - uchiwa (1.2.0)
  - sysctl (0.7.0)
  - chef-client (5.0.0)
  - logrotate (2.1.0)
  - ms_dotnet (3.0.0)
  - rabbitmq (4.9.0)
  - rsyslog (4.0.1)
  - asy-*** (0.1.5)
  - yum-erlang_solutions (0.3.1)
  - runit (1.8.0)
  - arvato-cdn (0.1.15)
  - ohai (2.1.0)
  - packagecloud (0.2.5)
  - windows (1.44.3)
  - zap (0.11.4)
  - dpkg_autostart (0.2.0)
  - build-essential (2.4.0)
  - cron (1.7.6)
  - filesystem_resize (0.3.0)
  - redisio (2.4.2)
  - erlang (3.0.0)
  - bluepill (2.4.3)
  - chef_handler (1.4.0)
  - yum-epel (0.7.1)
  - os-hardening (1.4.1)
  - ulimit (0.4.0)
  - ssh-hardening (1.2.0)
  - monitor (0.1.21)
  - yum (3.12.0)
Installing Cookbook Gems:
Compiling Cookbooks...
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:643: warning: already initialized constant Chef::RunContext::ChildRunContext::CHILD_STATE
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/run_context.rb:634: warning: previous definition of CHILD_STATE was here
/var/chef/cache/cookbooks/compat_resource/libraries/chef_upstream_version.rb:2: warning: already initialized constant ChefCompat::CHEF_UPSTREAM_VERSION
/var/chef/cache/cookbooks/compat_resource/libraries/chef_upstream_version.rb:2: warning: previous definition of CHEF_UPSTREAM_VERSION was here
Recipe: build-essential::_debian
  * apt_package[autoconf] action install (up to date)
  * apt_package[binutils-doc] action install (up to date)
...
  * directory[/data/.sensu] action create (up to date)
  * sensu_check[fs_writeable_data] action create (up to date)
  * sensu_json_file[/etc/sensu/conf.d/checks/fs_writeable_data.json] action create (up to date)
  * directory[create_dir_for_/etc/sensu/conf.d/checks/fs_writeable_data.json] action create (up to date)
  * file[/etc/sensu/conf.d/checks/fs_writeable_data.json] action create (up to date)
Recipe: monitor::client
  * zap_directory[/etc/sensu/conf.d/checks] action delete (up to date)

Running handlers:
Running handlers complete

Deprecated features used!
  method access to node attributes (node.foo.bar) is deprecated and will be removed in Chef 13, please use bracket syntax (node["foo"]["bar"]) at 9 locations:
    - /var/chef/cache/cookbooks/7-zip/attributes/default.rb:21:in `from_file'
    - /var/chef/cache/cookbooks/os-hardening/attributes/default.rb:22:in `from_file'
    - /var/chef/cache/cookbooks/os-hardening/attributes/sysctl.rb:182:in `from_file'
    - /var/chef/cache/cookbooks/python/attributes/default.rb:23:in `from_file'
    - /var/chef/cache/cookbooks/python/attributes/default.rb:24:in `from_file'
    - /var/chef/cache/cookbooks/python/attributes/default.rb:39:in `from_file'
    - /var/chef/cache/cookbooks/user/attributes/default.rb:22:in `from_file'
    - /var/chef/cache/cookbooks/ssh-hardening/attributes/default.rb:22:in `from_file'
    - /var/chef/cache/cookbooks/nginx/attributes/default.rb:43:in `from_file'
  Cloning resource attributes for service[nginx] from prior resource (CHEF-3694)
Previous service[nginx]: /var/chef/cache/cookbooks/nginx/recipes/package.rb:47:in `from_file'
Current  service[nginx]: /var/chef/cache/cookbooks/nginx/recipes/default.rb:24:in `from_file' at 1 location:
    - /var/chef/cache/cookbooks/nginx/recipes/default.rb:24:in `from_file'
  Cloning resource attributes for file[/etc/apt/preferences.d/sensu.pref] from prior resource (CHEF-3694)
Previous file[/etc/apt/preferences.d/sensu.pref]: /var/chef/cache/cookbooks/apt/providers/preference.rb:52:in `block in class_from_file'
Current  file[/etc/apt/preferences.d/sensu.pref]: /var/chef/cache/cookbooks/apt/providers/preference.rb:67:in `block in class_from_file' at 1 location:
    - /var/chef/cache/cookbooks/apt/providers/preference.rb:67:in `block in class_from_file'

Chef Client finished, 1/268 resources updated in 14 seconds
```

But if I run chef-client from the init script it only shows warnings:
```
root@ip-172-31-10-xx:/var/log/chef# cat /etc/chef/client.rb 
chef_server_url "https://chef.example.com/organizations/example-cloud"
client_fork true
log_location "/var/log/chef/client.log"
ssl_verify_mode :verify_none
validation_client_name "asy-cloud-validator"
verify_api_cert false
node_name "i-xxxxxxxxx"


ohai.plugin_path << "/etc/chef/ohai_plugins"

# Do not crash if a handler is missing / not installed yet
begin
rescue NameError => e
  Chef::Log.error e
end
root@ip-172-31-10-xx:/var/log/chef# /etc/init.d/chef-client run
root@ip-172-31-10-xx:/var/log/chef# ps aux | grep chef-
root      9980  0.0  1.5 229184 58868 ?        Sl   10:50   0:00 /opt/chef/embedded/bin/ruby /usr/bin/chef-client -d -P /var/run/chef/client.pid -c /etc/chef/client.rb -i 1800 -s 300
root     16426  0.0  0.0  10464   940 pts/0    S+   11:14   0:00 grep --color=auto chef-
root@ip-172-31-10-xx:/var/log/chef# tail client.log 
[2016-09-02T11:03:29+00:00] WARN: Ohai::Config[:plugin_path] is set. Ohai::Config[:plugin_path] is deprecated and will be removed in future releases of ohai. Use ohai.plugin_path in your configuration file to configure :plugin_path for ohai.
[2016-09-02T11:03:29+00:00] WARN: Ohai::Config[:plugin_path] is set. Ohai::Config[:plugin_path] is deprecated and will be removed in future releases of ohai. Use ohai.plugin_path in your configuration file to configure :plugin_path for ohai.
[2016-09-02T11:03:29+00:00] WARN: [DEPRECATION] Plugin at /etc/chef/ohai_plugins/nginx.rb is a version 6 plugin. Version 6 plugins will not be supported in future releases of Ohai. Please upgrade your plugin to version 7 plugin syntax. For more information visit here: docs.chef.io/ohai_custom.html
[2016-09-02T11:03:29+00:00] WARN: Ohai::Mixin::Command run_command is deprecated and will be removed in Ohai 9.0.0
[2016-09-02T11:03:29+00:00] WARN: Ohai::Mixin::Command popen4 is deprecated and will be removed in Ohai 9.0.0
[2016-09-02T11:03:31+00:00] WARN: Replacing sensu.pref with sensu.pref in /etc/apt/preferences.d/
[2016-09-02T11:03:34+00:00] WARN: FilesystemResizeCookbook::Filesystem: Unknown fs type: 
[2016-09-02T11:03:34+00:00] WARN: FilesystemResizeCookbook::Filesystem: Unknown fs type: 
[2016-09-02T11:03:34+00:00] WARN: FilesystemResizeCookbook::Filesystem: Unknown fs type: 
[2016-09-02T11:03:34+00:00] WARN: FilesystemResizeCookbook::Filesystem: Unknown fs type: 
```
I have also tried to configure a specific loglevel here:
```
root@ip-172-31-29-xx:/etc/chef# cat client.d/logging.rb 
log_level :info
```

**Comment by runningman84** [comment]
might be linked to https://github.com/chef/chef/issues/3435 and https://github.com/chef-cookbooks/chef-client/issues/369

**Comment by lamont-granquist** [comment]
probably dup of #3770 and #2514

better approach will likely be to attack the command line that the daemon is being invoked with and change it so that it uses '-l info --force-logger' explicitly

**Comment by thommay** [comment]
without further information, we'll be closing this as a duplicate as lamont indicated. If that's not correct, please feel free to reopen with more info.
