### ISSUE TITLE
PolicyBuilder complains about run_list being set in JSON data even though run_list is not set.

### ISSUE THREAD

**Issue by Poohblah** [chef/chef#5353]
## Description

When bootstrapping a node using the `-j`  or `--json-attribute-file` options to pass JSON containing `policy_name` and `policy_group` definitions but no `run_list` definition, `Chef::PolicyBuilder::Policyfile` complains that setting the `run_list` in JSON data is unsupported.
## Chef Version

ChefDK version 0.17.17
## Platform Version

Arch Linux
## Replication Case

Create a node json file with the keys `name`, `policy_name`, and `policy_group`, and use it to bootstrap a fresh node:

```
[birdsnest ~/local/data/sis/git/cookbooks/cub_metadata](master|✚1)[I]% cat nodes/myhost.json
{
  "name": "myhost",
  "policy_name": "cub_policy_myhost",
  "policy_group": "dev"
}
[birdsnest ~/local/data/sis/git/cookbooks/cub_metadata](master|✚1)[I]% knife bootstrap -x root -i /home/jay/.ssh/localization_rsa --bootstrap-version=12.12.15 --json-attribute-file nodes/myhost.json myhost
Doing old-style registration with the validation key at /home/jay/.chef/validation.pem...
Delete your validation key in order to use your user credentials instead

Connecting to myhost
Enter passphrase for /home/jay/.ssh/localization_rsa: 
myhost -----> Installing Chef Omnibus (-v 12.12.15)
myhost downloading https://omnitruck-direct.chef.io/chef/install.sh
myhost   to file /tmp/install.sh.1616/install.sh
myhost trying curl...
myhost el 7 x86_64
myhost Getting information for chef stable 12.12.15 for el...
myhost downloading https://omnitruck-direct.chef.io/stable/chef/metadata?v=12.12.15&p=el&pv=7&m=x86_64
myhost   to file /tmp/install.sh.1626/metadata.txt
myhost trying curl...
myhost sha1 92d14fa522ff14b1e22622312c8271db3cc0d512
myhost sha256   ce1f216242f26d7274c108a9cb9d8add7095727e039bac968de9291f56a90c25
myhost url  https://packages.chef.io/stable/el/7/chef-12.12.15-1.el7.x86_64.rpm
myhost version  12.12.15
myhost downloaded metadata file looks valid...
myhost downloading https://packages.chef.io/stable/el/7/chef-12.12.15-1.el7.x86_64.rpm
myhost   to file /tmp/install.sh.1626/chef-12.12.15-1.el7.x86_64.rpm
myhost trying curl...
myhost Comparing checksum with sha256sum...
myhost Installing chef 12.12.15
myhost installing with rpm...
myhost warning: /tmp/install.sh.1626/chef-12.12.15-1.el7.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
myhost Preparing...                                                            (1################################# [100%]
myhost Updating / installing...
myhost    1:chef-12.12.15-1.el7                                                ( ################################# [100%]
myhost Thank you for installing Chef!
myhost Starting the first Chef Client run...
myhost Starting Chef Client, version 12.12.15
myhost Creating a new client identity for myhost using the validator key.
myhost 
myhost ================================================================================
myhost Chef encountered an error attempting to load the node data for "myhost"
myhost ================================================================================
myhost 
myhost Unexpected Error:
myhost -----------------
myhost Chef::PolicyBuilder::Policyfile::UnsupportedFeature: Policyfile does not support setting the run_list in json data.
myhost 
myhost Platform:
myhost ---------
myhost x86_64-linux
myhost 
myhost 
myhost Running handlers:
myhost [2016-09-20T13:57:24-06:00] ERROR: Running exception handlers
myhost Running handlers complete
myhost [2016-09-20T13:57:24-06:00] ERROR: Exception handlers complete
myhost Chef Client failed. 0 resources updated in 02 seconds
myhost [2016-09-20T13:57:24-06:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
myhost [2016-09-20T13:57:24-06:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
myhost [2016-09-20T13:57:24-06:00] ERROR: Policyfile does not support setting the run_list in json data.
myhost [2016-09-20T13:57:25-06:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
[birdsnest ~/local/data/sis/git/cookbooks/cub_metadata](master|✚1)[I]%
```
## Stacktrace

```
Generated at 2016-09-20 14:03:55 -0600
Chef::PolicyBuilder::Policyfile::UnsupportedFeature: Policyfile does not support setting the run_list in json data.
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/policy_builder/policyfile.rb:80:in `initialize'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/policy_builder/dynamic.rb:155:in `new'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/policy_builder/dynamic.rb:155:in `select_implementation'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/policy_builder/dynamic.rb:74:in `load_node'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/client.rb:467:in `load_node'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/client.rb:269:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application.rb:286:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application.rb:274:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application.rb:274:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application.rb:239:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application.rb:227:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application/client.rb:456:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application/client.rb:443:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application/client.rb:442:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application/client.rb:442:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application/client.rb:426:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:52:in `load'
/usr/bin/chef-client:52:in `<main>'
```

**Comment by Poohblah** [comment]
I'm able to work around this with the following knife plugin that monkey-patches the bootstrap context:
```
require 'chef/knife/core/bootstrap_context'

module BootstrapContextPatches
  def first_boot
    attributes = super
    attributes.delete(:run_list) if attributes[:run_list].empty?
    attributes
  end
end

class Chef
  class Knife
    module Core
      class BootstrapContext
        prepend BootstrapContextPatches
      end
    end
  end
end
```

**Comment by thisisjaid** [comment]
As a small side-note the monkey-patch above fixes the reported problem but seems to then break --policy-group / --policy-name options for knife bootstrap.

Chef Development Kit Version: 1.2.22
