### ISSUE TITLE
User resource fails with "usermod: no flags given"

### ISSUE THREAD

**Issue by phene** [chef/chef#5444]
## Description

User resource errors consistently for a couple of specific users in long-standing environment after upgrade of chef client from 12.5.1. "usermod: no flags given"

## Chef Version

12.15.24
12.14.89

## Platform Version

Ubuntu 12.04

## Replication Case

I have not found a consistent way to replicate this in a fresh environment, but here are the user resources giving me problems:

```ruby
user 'pushsvr' do
  uid 616
  gid 616
  comment 'push service account'
  home push_basedir
  shell '/usr/sbin/nologin'
  system true
end

user 'esearch' do
  action :create
  uid 621
  gid 621
  comment 'Elasticsearch service account'
  home elasticsearch_base
  shell '/bin/false'
end
```

## Chef Output

```
22:57:16  myserver.mydomain:   * linux_user[pushsvr] action create
22:57:16  myserver.mydomain: [2016-10-11T22:57:16+00:00] INFO: Processing linux_user[pushsvr] action create (switchboard::default line 62)
22:57:16  myserver.mydomain: ================================================================================    
22:57:16  myserver.mydomain: Error executing action `create` on resource 'linux_user[pushsvr]'
```

## Stacktrace
```
>>>> Caused by Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
---- Begin output of ["usermod", "pushsvr"] ----
STDOUT:
STDERR: usermod: no flags given
---- End output of ["usermod", "pushsvr"] ----
Ran ["usermod", "pushsvr"] returned 2
/opt/chef/ruby/2.2.0/gems/mixlib-shellout-2.2.7/lib/mixlib/shellout.rb:289:in `invalid!'
/opt/chef/ruby/2.2.0/gems/mixlib-shellout-2.2.7/lib/mixlib/shellout.rb:276:in `error!'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/mixin/shell_out.rb:45:in `shell_out!'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/provider/user/linux.rb:31:in `manage_user'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/provider/user.rb:135:in `block in action_create'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/provider.rb:176:in `converge_by'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/provider/user.rb:134:in `action_create'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/provider.rb:145:in `run_action'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/resource.rb:603:in `run_action'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/runner.rb:69:in `run_action'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/runner.rb:97:in `each'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/resource_collection/stepable_iterator.rb:114:in `call'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/runner.rb:96:in `converge'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/client.rb:669:in `block in converge'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/client.rb:664:in `catch'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/client.rb:664:in `converge'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/client.rb:703:in `converge_and_save'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/client.rb:283:in `run'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/application.rb:302:in `block in fork_chef_client'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/application.rb:290:in `fork'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/application.rb:290:in `fork_chef_client'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/application.rb:255:in `block in run_chef_client'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/application.rb:243:in `run_chef_client'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/application/client.rb:450:in `loop'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/lib/chef/application.rb:60:in `run'
/opt/chef/ruby/2.2.0/gems/chef-12.15.24/bin/chef-client:26:in `<top (required)>'
/opt/chef/bin/chef-client:12:in `load'
/opt/chef/bin/chef-client:12:in `<main>'
```

**Comment by phene** [comment]
Just as an update, I modified the comments and got a successful converge. The subsequent converge failed for this same reason, though.

**Comment by phene** [comment]
I think [this issue](https://github.com/chef/chef/issues/5388) may be related.

**Comment by phene** [comment]
I attempted to change the home directory paths to include a trailing slash, and again I got one successful converge, then a failure.

**Comment by lamont-granquist** [comment]
issue doesn't seem to be related to #5388 

the idempotency check for some reason thinks it needs to call usermod to fix...  something... but then it issues a command which doesn't actually modify anything.

when you change the home directory paths or the comment you give it something to do for real, so it does, then it goes back to failing again.

**Comment by lamont-granquist** [comment]
you could `pp push_basedir` and `pp elasticsearch_base` before those resources and that might shed some light on what is going on.  also the existing lines from /etc/passwd for those users would be useful.

**Comment by phene** [comment]
Yeah, it's not directly related to the paths. I'm going to spend a bit more time today investigating why chef thinks it needs to modify the user.

**Comment by phene** [comment]
I have confirmed that the other issue is EXACTLY what's causing my problem. Here's the code used to detect [if changes have been made to a user](https://github.com/chef/chef/blob/master/lib/chef/provider/user.rb#L117):

```ruby
changed = [ :comment, :home, :shell, :password ].select do |user_attrib|
  !@new_resource.send(user_attrib).nil? && @new_resource.send(user_attrib) != @current_resource.send(user_attrib)
end
```

While the [code for compiling the modifications to send to `usermod`](https://github.com/chef/chef/blob/master/lib/chef/provider/user/linux.rb#L94) does this:

```ruby
new_resource.home && Pathname.new(current_resource.home).cleanpath != Pathname.new(new_resource.home).cleanpath
```

I tested this by injecting some debugging code into `Chef::Provider::User#compare_user`, and it consistently detects that the home path changed, but fails to detect the change when compiling options for `usermod`. I'd propose modifying `Chef::Provider::User#compare_user` to apply the same path-aware logic:

```ruby
      def compare_user
        changed = [ :comment, :shell, :password ].select do |user_attrib|
          !@new_resource.send(user_attrib).nil? && @new_resource.send(user_attrib) != @current_resource.send(user_attrib)
        end

        changed << :home if !@new_resource.send(user_attrib).nil? && Pathname.new(@new_resource.home).cleanpath != Pathname.new(@current_resource.home).cleanpath

        changed += [ :uid, :gid ].select do |user_attrib|
          !@new_resource.send(user_attrib).nil? && @new_resource.send(user_attrib).to_s != @current_resource.send(user_attrib).to_s
        end

        changed.any?
      end
```

**Comment by phene** [comment]
I have confirmed this solves my problem.

**Comment by lamont-granquist** [comment]
can you combine the two `selects` into one that calls `#to_s` on the :comment, :shell, :password fields as well?

since it looks that only returns a boolean you also don't really need to accumulate the array and call `#any?` on it, you can probably short-circuit that and just `return true` the first conditional that matches

you should submit a PR...

**Comment by phene** [comment]
@lamont-granquist PR Submitted.
