### ISSUE TITLE
chef-client 12.15.19 on OSX 10.12 bash  cannot execute as specific user except root (due to TMPDIR issues)

### ISSUE THREAD

**Issue by Sauraus** [chef/chef#5455]
## Description

Specifying a user on the bash resource throws an Permission denied error because the path leading up to where the bash code is rendered is not accessible to that user.
## Chef Version

12.15.19
## Platform Version

OS X 10.12 (Sierra)
## Replication Case

```
bash "Setup osx_signing.keychain for #{node['teamcity']['agent']['user']}" do
    user node['teamcity']['agent']['user']
    group node['teamcity']['agent']['group']
    cwd "/Users/#{node['teamcity']['agent']['user']}"
    environment({ 'HOME' => "/Users/#{node['teamcity']['agent']['user']}", 'USER' => node['teamcity']['agent']['user'] }) # rubocop:disable Lint/ParenthesesAsGroupedExpression
    code <<-EOH
      #!/bin/sh
      . /etc/rc.common
      security create-keychain #{Shellwords.escape(password).prepend('-p ')} osx_signing.keychain
      security import ./osx_signing.p12 -k osx_signing.keychain #{Shellwords.escape(p12_pw).prepend('-P ')} -A
      security lock-keychain osx_signing.keychain
    EOH
    sensitive true
end
```
## Client Output

The problem is that the final `tmp` (/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T) folder is 00700, the entire tree up to that final `T` folder is 00755.

```
sudo ls -asl /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000  
0 drwxr-xr-x@  6 root  wheel  204 Oct  7 11:31 .
0 drwxr-xr-x@ 14 root  wheel  476 Oct  7 11:33 ..
0 drwx------@ 11 root  wheel  374 Oct 13 12:47 T
```

```
* bash[Setup osx_signing.keychain for teamcity] action run

    ================================================================================
    Error executing action `run` on resource 'bash[Setup osx_signing.keychain for teamcity]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '126'
    ---- Begin output of "bash"  "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/chef-script20161013-2837-1io2pcg" ----
    STDOUT: 
    STDERR: bash: /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/chef-script20161013-2837-1io2pcg: Permission denied
    ---- End output of "bash"  "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/chef-script20161013-2837-1io2pcg" ----
    Ran "bash"  "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/chef-script20161013-2837-1io2pcg" returned 126
```
## Stacktrace

```
Generated at 2016-10-13 12:47:34 -0700
Mixlib::ShellOut::ShellCommandFailed: bash[Setup osx_signing.keychain for teamcity] (rblx_teamcity::mac_os_x line 67) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '126'
---- Begin output of "bash"  "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/chef-script20161013-2837-1io2pcg" ----
STDOUT: 
STDERR: bash: /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/chef-script20161013-2837-1io2pcg: Permission denied
---- End output of "bash"  "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/chef-script20161013-2837-1io2pcg" ----
Ran "bash"  "/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/chef-script20161013-2837-1io2pcg" returned 126
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.7/lib/mixlib/shellout.rb:289:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.7/lib/mixlib/shellout.rb:276:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/mixin/shell_out.rb:45:in `shell_out!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/provider/execute.rb:62:in `block in action_run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/provider.rb:176:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/provider/execute.rb:60:in `action_run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/provider/script.rb:63:in `action_run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource.rb:603:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:669:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:664:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:664:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:703:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/client.rb:283:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:302:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:290:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:290:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:255:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:243:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/bin/chef-client:26:in `<top (required)>'
/usr/local/bin/chef-client:54:in `load'
/usr/local/bin/chef-client:54:in `<main>'
```
### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.
- [Server issues](https://github.com/chef/chef-server/issues/new)
- [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
- Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by lamont-granquist** [comment]
i feel like i've seen this one before...

**Comment by lamont-granquist** [comment]
related to #4715 at least

**Comment by walkah** [comment]
Currently getting bit by this as well. Any workarounds?

**Comment by Sauraus** [comment]
@walkah my workaround is to drop a template and/or file and then use the `command` resource to execute it as user `X`.

**Comment by walkah** [comment]
@Sauraus thanks for the quick response!

**Comment by lamont-granquist** [comment]
most likely we need to fix TMPDIR in shellout/shellout! and friends on darwin/OSX/MacOS across the board.

**Comment by bcg62** [comment]
Also experiencing this on osx, breaking the rbenv cookbook

**Comment by lamont-granquist** [comment]
another dup of #7690
