### ISSUE TITLE
several unit tests fail to run when workstation is FIPS enabled

### ISSUE THREAD

**Issue by ghatwala** [chef/chef#5533]
## Description
Getting test case failures.
```
# Run All the Tests 
bundle exec rake spec
```

While tying out the test cases , getting below errors
```
Finished in 13 minutes 15 seconds (files took 12.58 seconds to load)
16974 examples, 3 failures, 31 pending

Failed examples:

rspec ./spec/unit/application/client_spec.rb:431 # Chef::Application::Client configure_chef should set the colored output to true by default on windows and true on all other platforms as well
rspec ./spec/unit/application_spec.rb:134 # Chef::Application when there are no configuration errors configure_chef when a config_file is present should configure chef::config from a file
rspec ./spec/unit/application_spec.rb:139 # Chef::Application when there are no configuration errors configure_chef when a config_file is present should merge the local config hash into chef::config

```

## Chef Version
```
jenkins@1e4fff739f96:~/chef> chef-solo --version
Chef: 12.17.1

```
## Platform Version
```
jenkins@1e4fff739f96:~/chef> arch
ppc64le
```
```
jenkins@1e4fff739f96:~/chef> lscpu
Architecture:          ppc64le
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             16
NUMA node(s):          1
Model:                 IBM pSeries (emulated by qemu)
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             64K
L1i cache:             32K
NUMA node0 CPU(s):     0-15

```
Bundle version
```
jenkins@1e4fff739f96:~/chef> bundle --version
Bundler version 1.13.6

```
```
jenkins@1e4fff739f96:~/chef> ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [powerpc64le-linux]
```
gem version
```
jenkins@1e4fff739f96:~/chef> gem --version
2.6.8
```

chef client
```
jenkins@1e4fff739f96:~/chef> chef-client --version
Chef: 12.17.1

```

OS version
```
jenkins@1e4fff739f96:~/chef> cat /etc/os-release
NAME="SLES"
VERSION="12-SP1"
VERSION_ID="12.1"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP1"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp1"

```

## Replication Case

Now while validating the test case using below options
```
# Run All the Tests
$ bundle exec rake spec
```

## Stacktrace /Debug log

Log of the failed test case when run as unit level
**First test case failure log** 
```
jenkins@1e4fff739f96:~/chef> bundle exec rspec spec/unit/application/client_spec.rb

WARNING: Shared example group 'with a chef repo' has been previously defined at:
  /home/jenkins/.rvm/gems/ruby-2.3.1/gems/cheffish-4.0.0/lib/cheffish/rspec/repository_support.rb:12
...and you are now defining it at:
  /home/jenkins/chef/spec/support/shared/integration/integration_helper.rb:111
The new definition will overwrite the original one.
/home/jenkins/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- win32/daemon (LoadError)
        from /home/jenkins/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Run options:
  include {:focus=>true}
  exclude {:provider=>#<Proc:./spec/spec_helper.rb:183>, :arch=>#<Proc:./spec/spec_helper.rb:177>, :ruby=>"2.3.1", :chef=>"12.17.1", :not_wpar=>true, :broken=>true, :openssl_lt_101=>true, :requires_root_or_running_windows=>true, :requires_root=>true, :selinux_only=>true, :debian_family_only=>true, :aix_only=>true, :system_windows_service_gem_only=>true, :solaris_only=>true, :windows_domain_joined_only=>true, :windows_powershell_dsc_only=>true, :ruby32_only=>true, :ruby64_only=>true, :windows_nano_only=>true, :windows32_only=>true, :windows64_only=>true, :windows_2008r2_or_later=>true, :win2k3_only=>true, :mac_osx_only=>true, :windows_only=>true, :appveyor_only=>true, :volatile_from_verify=>false, :volatile=>true, :external=>true}

All examples were filtered out; ignoring {:focus=>true}

Chef::Application::Client reconfigure
  parse cli_arguments
    should call set_specific_recipes
    --named-run-list
      behaves like sets the configuration
        --named-run-list arglebargle-example
          sets {:named_run_list=>"arglebargle-example"}
    --no-listen
      behaves like sets the configuration
        --no-listen
          sets {:listen=>false}
    --daemonize
      with no value
        behaves like sets the configuration
          --daemonize
            sets {:daemonize=>true}
      with an integer value
        behaves like sets the configuration
          --daemonize 5
            sets {:daemonize=>5}
      with a non-integer value
        behaves like sets the configuration
          --daemonize foo
            sets {:daemonize=>true}
    --config-option
      with a single value
        behaves like sets the configuration
          --config-option chef_server_url=http://example
            sets {:chef_server_url=>"http://example"}
      with two values
        behaves like sets the configuration
          --config-option chef_server_url=http://example --config-option policy_name=web
            sets {:chef_server_url=>"http://example", :policy_name=>"web"}
      with a boolean value
        behaves like sets the configuration
          --config-option minimal_ohai=true
            sets {:minimal_ohai=>true}
      with an empty value
        should terminate with message
      with an invalid value
        should terminate with message
  when configured to not fork the client process
    when interval is given
      should terminate with message
    when interval is given on windows
      should not terminate
    when configured to run once
      should reconfigure chef-client
  daemonized mode
    when no interval has been set
      should set the interval to 1800
    when the daemonize option is an integer
[2016-11-10T16:23:57+00:00] INFO: SIGUSR1 received, waking up
[2016-11-10T16:23:58+00:00] INFO: SIGUSR1 received, waking up
[2016-11-10T16:23:59+00:00] INFO: SIGUSR1 received, waking up
      sleeps for the amount of time passed
  when configured to run once
[2016-11-10T16:24:00+00:00] WARN: *****************************************
[2016-11-10T16:24:00+00:00] WARN: Did not find config file: /etc/chef/client.rb, using command line options.
[2016-11-10T16:24:00+00:00] WARN: *****************************************
[2016-11-10T16:24:00+00:00] INFO: Unable to access cache at /var/chef. Switching cache to /home/jenkins/.chef
    ignores the splay
[2016-11-10T16:24:00+00:00] WARN: *****************************************
[2016-11-10T16:24:00+00:00] WARN: Did not find config file: /etc/chef/client.rb, using command line options.
[2016-11-10T16:24:00+00:00] WARN: *****************************************
[2016-11-10T16:24:00+00:00] INFO: Unable to access cache at /var/chef. Switching cache to /home/jenkins/.chef
    forces the interval to nil
  when the json_attribs configuration option is specified
[2016-11-10T16:24:00+00:00] INFO: Unable to access cache at /var/chef. Switching cache to /home/jenkins/.chef
    reads the JSON attributes from the specified source
  audit mode
    unrecognized setting via config file
[2016-11-10T16:24:00+00:00] WARN: *****************************************
[2016-11-10T16:24:00+00:00] WARN: Did not find config file: /etc/chef/client.rb, using command line options.
[2016-11-10T16:24:00+00:00] WARN: *****************************************
[2016-11-10T16:24:00+00:00] INFO: Unable to access cache at /var/chef. Switching cache to /home/jenkins/.chef
      fatals with a message including the incorrect setting
    unrecognized setting via command line
[2016-11-10T16:24:00+00:00] WARN: *****************************************
[2016-11-10T16:24:00+00:00] WARN: Did not find config file: /etc/chef/client.rb, using command line options.
[2016-11-10T16:24:00+00:00] WARN: *****************************************
[2016-11-10T16:24:00+00:00] INFO: Unable to access cache at /var/chef. Switching cache to /home/jenkins/.chef
      fatals with a message including the incorrect setting
  when both the pidfile and lockfile opts are set to the same value
[2016-11-10T16:24:00+00:00] WARN: *****************************************
[2016-11-10T16:24:00+00:00] WARN: Did not find config file: /etc/chef/client.rb, using command line options.
[2016-11-10T16:24:00+00:00] WARN: *****************************************
    should throw an exception
  behaves like an application that loads a dot d
    when client_d_dir is set to nil
[2016-11-10T16:24:00+00:00] WARN: *****************************************
[2016-11-10T16:24:00+00:00] WARN: Did not find config file: /etc/chef/client.rb, using command line options.
[2016-11-10T16:24:00+00:00] WARN: *****************************************
[2016-11-10T16:24:00+00:00] INFO: Unable to access cache at /var/chef. Switching cache to /home/jenkins/.chef
      does not raise an exception
    when client_d_dir is set to a directory with configuration
[2016-11-10T16:24:00+00:00] WARN: *****************************************
[2016-11-10T16:24:00+00:00] WARN: Did not find config file: /etc/chef/client.rb, using command line options.
[2016-11-10T16:24:00+00:00] WARN: *****************************************
[2016-11-10T16:24:00+00:00] INFO: Unable to access cache at /var/chef. Switching cache to /home/jenkins/.chef
      loads the configuration in order
    when client_d_dir is set to a directory without configuration
[2016-11-10T16:24:00+00:00] WARN: *****************************************
[2016-11-10T16:24:00+00:00] WARN: Did not find config file: /etc/chef/client.rb, using command line options.
[2016-11-10T16:24:00+00:00] WARN: *****************************************
[2016-11-10T16:24:00+00:00] INFO: Unable to access cache at /var/chef. Switching cache to /home/jenkins/.chef
      does not raise an exception
    when client_d_dir is set to a directory containing a directory named foo.rb
[2016-11-10T16:24:00+00:00] WARN: *****************************************
[2016-11-10T16:24:00+00:00] WARN: Did not find config file: /etc/chef/client.rb, using command line options.
[2016-11-10T16:24:00+00:00] WARN: *****************************************
[2016-11-10T16:24:00+00:00] INFO: Unable to access cache at /var/chef. Switching cache to /home/jenkins/.chef
      does not raise an exception

Chef::Application::Client setup_application
  should change privileges

Chef::Application::Client configure_chef
[2016-11-10T16:24:00+00:00] WARN: *****************************************
[2016-11-10T16:24:00+00:00] WARN: Did not find config file: /etc/chef/client.rb, using command line options.
[2016-11-10T16:24:00+00:00] WARN: *****************************************
  should set the colored output to true by default on windows and true on all other platforms as well (FAILED - 1)

Chef::Application::Client run_application
  when sent SIGTERM
    when converging in forked process
[2016-11-10T16:24:00+00:00] INFO: Forking chef instance to converge...
[2016-11-10T16:24:00+00:00] FATAL: SIGTERM received, stopping
      should allow child to finish converging
    when running unforked
      should exit gracefully when sent during converge
[2016-11-10T16:24:03+00:00] FATAL: SIGTERM received, stopping
      should exit hard when sent before converge
  when splay is set
[2016-11-10T16:24:03+00:00] INFO: SIGUSR1 received, waking up
[2016-11-10T16:24:04+00:00] INFO: SIGUSR1 received, waking up
[2016-11-10T16:24:05+00:00] INFO: SIGUSR1 received, waking up
    shouldn't sleep when sent USR1

Failures:

  1) Chef::Application::Client configure_chef should set the colored output to true by default on windows and true on all other platforms as well
     Failure/Error: Chef::Config.init_openssl

       #<File (class)> received :read with unexpected arguments
         expected: ("/etc/chef/client.rb")
              got: ("/proc/sys/crypto/fips_enabled")
        Please stub a default value first if message might be received with other args as well.
     # ./chef-config/lib/chef-config/fips.rb:48:in `fips?'
     # ./chef-config/lib/chef-config/config.rb:562:in `block in <class:Config>'
     # /home/jenkins/.rvm/gems/ruby-2.3.1/gems/mixlib-config-2.2.4/lib/mixlib/config/configurable.rb:48:in `get'
     # /home/jenkins/.rvm/gems/ruby-2.3.1/gems/mixlib-config-2.2.4/lib/mixlib/config.rb:433:in `internal_get'
     # /home/jenkins/.rvm/gems/ruby-2.3.1/gems/mixlib-config-2.2.4/lib/mixlib/config.rb:454:in `internal_get_or_set'
     # /home/jenkins/.rvm/gems/ruby-2.3.1/gems/mixlib-config-2.2.4/lib/mixlib/config.rb:475:in `block in define_attr_accessor_methods'
     # ./chef-config/lib/chef-config/config.rb:568:in `init_openssl'
     # ./lib/chef/application.rb:88:in `configure_chef'
     # ./spec/unit/application/client_spec.rb:424:in `block (2 levels) in <top (required)>'

Finished in 8.55 seconds (files took 1.97 seconds to load)
32 examples, 1 failure

Failed examples:

rspec ./spec/unit/application/client_spec.rb:431 # Chef::Application::Client configure_chef should set the colored output to true by default on windows and true on all other platforms as well
```

**second test case failure log** 

```
jenkins@1e4fff739f96:~/chef> bundle exec rspec spec/unit/application_spec.rb

WARNING: Shared example group 'with a chef repo' has been previously defined at:
  /home/jenkins/.rvm/gems/ruby-2.3.1/gems/cheffish-4.0.0/lib/cheffish/rspec/repository_support.rb:12
...and you are now defining it at:
  /home/jenkins/chef/spec/support/shared/integration/integration_helper.rb:111
The new definition will overwrite the original one.
/home/jenkins/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- win32/daemon (LoadError)
        from /home/jenkins/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Run options:
  include {:focus=>true}
  exclude {:provider=>#<Proc:./spec/spec_helper.rb:183>, :arch=>#<Proc:./spec/spec_helper.rb:177>, :ruby=>"2.3.1", :chef=>"12.17.1", :not_wpar=>true, :broken=>true, :openssl_lt_101=>true, :requires_root_or_running_windows=>true, :requires_root=>true, :selinux_only=>true, :debian_family_only=>true, :aix_only=>true, :system_windows_service_gem_only=>true, :solaris_only=>true, :windows_domain_joined_only=>true, :windows_powershell_dsc_only=>true, :ruby32_only=>true, :ruby64_only=>true, :windows_nano_only=>true, :windows32_only=>true, :windows64_only=>true, :windows_2008r2_or_later=>true, :win2k3_only=>true, :mac_osx_only=>true, :windows_only=>true, :appveyor_only=>true, :volatile_from_verify=>false, :volatile=>true, :external=>true}

All examples were filtered out; ignoring {:focus=>true}

Chef::Application
  when there are no configuration errors
    reconfigure
      should configure chef
      should configure logging
      should not receive set_specific_recipes
    Chef::Application
      run
        should reconfigure the application before running
        should setup the application before running it
        should run the actual application
    configure_chef
      should parse the commandline options
      when a config_file is present
        should configure chef::config from a file (FAILED - 1)
        should merge the local config hash into chef::config (FAILED - 2)
        when openssl fips
          sets openssl in fips mode
      when there is no config_file defined
        should emit a warning
      when the config file is set and not found
        should use the passed in command line options and defaults
    when configuring the logger
      should initialise the chef logger
      when log_level is not set
        behaves like log_level_is_auto
          when STDOUT is to a tty
            configures the log level to :warn
            when force_logger is configured
              configures the log level to info
          when STDOUT is not to a tty
            configures the log level to :info
            when force_formatter is configured
              sets the log level to :warn
      when log_level is :auto
        behaves like log_level_is_auto
          when STDOUT is to a tty
            configures the log level to :warn
            when force_logger is configured
              configures the log level to info
          when STDOUT is not to a tty
            configures the log level to :info
            when force_formatter is configured
              sets the log level to :warn
      log_location
        behaves like sets log_location
          when the configured value is :syslog
            it sets log_location to an instance of Chef::Log::Syslog
        behaves like sets log_location
          when the configured value is "syslog"
            it sets log_location to an instance of Chef::Log::Syslog
  with an invalid log location
    logs a fatal error and exits
  class method: fatal!
[2016-11-10T16:32:01+00:00] ERROR: Chef RFC 062 (https://github.com/chef/chef-rfc/master/rfc062-exit-status.md) defines the exit codes that should be used with Chef.  Chef::Application::ExitCode defines valid exit codes In a future release, non-standard exit codes will be redefined as GENERIC_FAILURE unless `exit_status` is set to `:disabled` in your client.rb. at /home/jenkins/chef/spec/unit/application_spec.rb:299:in `block (3 levels) in <top (required)>'
    should log an error message to the logger
    when an exit code is supplied
[2016-11-10T16:32:01+00:00] ERROR: Chef RFC 062 (https://github.com/chef/chef-rfc/master/rfc062-exit-status.md) defines the exit codes that should be used with Chef.  Chef::Application::ExitCode defines valid exit codes In a future release, non-standard exit codes will be redefined as GENERIC_FAILURE unless `exit_status` is set to `:disabled` in your client.rb. at /home/jenkins/chef/spec/unit/application_spec.rb:305:in `block (4 levels) in <top (required)>'
      should exit with the given exit code
    when an exit code is not supplied
[2016-11-10T16:32:01+00:00] ERROR: Chef RFC 062 (https://github.com/chef/chef-rfc/master/rfc062-exit-status.md) defines the exit codes that should be used with Chef.  Chef::Application::ExitCode defines valid exit codes In a future release, non-standard exit codes will be redefined as GENERIC_FAILURE unless `exit_status` is set to `:disabled` in your client.rb. at /home/jenkins/chef/spec/unit/application_spec.rb:312:in `block (4 levels) in <top (required)>'
      should exit with the default exit code
  setup_application
    should raise an error
  run_application
    should raise an error
  when the config file is not available
    should warn for bad config file path
  run_chef_client
    with an application
      when called with an invalid argument
        should raise an argument error detailing the problem
      when called with an Array-like argument (#size)
        should be cool
  configuration errors
    when config file exists but contains errors
      should raise informative fatals for badly written config

Failures:

  1) Chef::Application when there are no configuration errors configure_chef when a config_file is present should configure chef::config from a file
     Failure/Error: Chef::Config.init_openssl

       #<File (class)> received :read with unexpected arguments
         expected: ("/etc/chef/default.rb")
              got: ("/proc/sys/crypto/fips_enabled")
     # ./chef-config/lib/chef-config/fips.rb:48:in `fips?'
     # ./chef-config/lib/chef-config/config.rb:562:in `block in <class:Config>'
     # /home/jenkins/.rvm/gems/ruby-2.3.1/gems/mixlib-config-2.2.4/lib/mixlib/config/configurable.rb:48:in `get'
     # /home/jenkins/.rvm/gems/ruby-2.3.1/gems/mixlib-config-2.2.4/lib/mixlib/config.rb:433:in `internal_get'
     # /home/jenkins/.rvm/gems/ruby-2.3.1/gems/mixlib-config-2.2.4/lib/mixlib/config.rb:454:in `internal_get_or_set'
     # /home/jenkins/.rvm/gems/ruby-2.3.1/gems/mixlib-config-2.2.4/lib/mixlib/config.rb:475:in `block in define_attr_accessor_methods'
     # ./chef-config/lib/chef-config/config.rb:568:in `init_openssl'
     # ./lib/chef/application.rb:88:in `configure_chef'
     # ./spec/unit/application_spec.rb:136:in `block (5 levels) in <top (required)>'

  2) Chef::Application when there are no configuration errors configure_chef when a config_file is present should merge the local config hash into chef::config
     Failure/Error: Chef::Config.init_openssl

       #<File (class)> received :read with unexpected arguments
         expected: ("/etc/chef/default.rb")
              got: ("/proc/sys/crypto/fips_enabled")
     # ./chef-config/lib/chef-config/fips.rb:48:in `fips?'
     # ./chef-config/lib/chef-config/config.rb:562:in `block in <class:Config>'
     # /home/jenkins/.rvm/gems/ruby-2.3.1/gems/mixlib-config-2.2.4/lib/mixlib/config/configurable.rb:48:in `get'
     # /home/jenkins/.rvm/gems/ruby-2.3.1/gems/mixlib-config-2.2.4/lib/mixlib/config.rb:433:in `internal_get'
     # /home/jenkins/.rvm/gems/ruby-2.3.1/gems/mixlib-config-2.2.4/lib/mixlib/config.rb:454:in `internal_get_or_set'
     # /home/jenkins/.rvm/gems/ruby-2.3.1/gems/mixlib-config-2.2.4/lib/mixlib/config.rb:475:in `block in define_attr_accessor_methods'
     # ./chef-config/lib/chef-config/config.rb:568:in `init_openssl'
     # ./lib/chef/application.rb:88:in `configure_chef'
     # ./spec/unit/application_spec.rb:141:in `block (5 levels) in <top (required)>'

Finished in 0.08831 seconds (files took 1.98 seconds to load)
33 examples, 2 failures

Failed examples:

rspec ./spec/unit/application_spec.rb:134 # Chef::Application when there are no configuration errors configure_chef when a config_file is present should configure chef::config from a file
rspec ./spec/unit/application_spec.rb:139 # Chef::Application when there are no configuration errors configure_chef when a config_file is present should merge the local config hash into chef::config

```

Any pointers to resolve the above test case failure errors ?

Regards,
Amit

**Comment by ghatwala** [comment]
Additional information ... 
Installed the chef gem using below
```
jenkins@1e4fff739f96:~/chef> gem install pkg/chef-12.17.1.gem
Successfully installed chef-12.17.1
Parsing documentation for chef-12.17.1
Done installing documentation for chef after 24 seconds
1 gem installed
```

**Comment by ghatwala** [comment]
Hi All,

Any updates on the above test cases errors ?

**Comment by lamont-granquist** [comment]
looks like the tests are broken when run on a linux box where `/proc/sys/crypto/fips_enabled` exists

**Comment by ghatwala** [comment]
@lamont-granquist : thanks for responding , i have checked my linux box too and confirmed to have - 
```
/proc/sys/crypto/fips_enabled
```
The above is the culprit for the first test case failing for me , however for there is another test case failure too.

```
jenkins@1e4fff739f96:~/chef> bundle exec rspec spec/unit/application_spec.rb

WARNING: Shared example group 'with a chef repo' has been previously defined at:
  /home/jenkins/.rvm/gems/ruby-2.3.1/gems/cheffish-4.0.0/lib/cheffish/rspec/repository_support.rb:12
...and you are now defining it at:
  /home/jenkins/chef/spec/support/shared/integration/integration_helper.rb:111
The new definition will overwrite the original one.
/home/jenkins/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- win32/daemon (LoadError)
        from /home/jenkins/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Run options:
  include {:focus=>true}
  exclude {:provider=>#<Proc:./spec/spec_helper.rb:183>, :arch=>#<Proc:./spec/spec_helper.rb:177>, :ruby=>"2.3.1", :chef=>"12.17.1", :not_wpar=>true, :broken=>true, :openssl_lt_101=>true, :requires_root_or_running_windows=>true, :requires_root=>true, :selinux_only=>true, :debian_family_only=>true, :aix_only=>true, :system_windows_service_gem_only=>true, :solaris_only=>true, :windows_domain_joined_only=>true, :windows_powershell_dsc_only=>true, :ruby32_only=>true, :ruby64_only=>true, :windows_nano_only=>true, :windows32_only=>true, :windows64_only=>true, :windows_2008r2_or_later=>true, :win2k3_only=>true, :mac_osx_only=>true, :windows_only=>true, :appveyor_only=>true, :volatile_from_verify=>false, :volatile=>true, :external=>true}

All examples were filtered out; ignoring {:focus=>true}

Chef::Application
  when there are no configuration errors
    reconfigure
      should configure chef
      should configure logging
      should not receive set_specific_recipes
    Chef::Application
      run
        should reconfigure the application before running
        should setup the application before running it
        should run the actual application
    configure_chef
      should parse the commandline options
      when a config_file is present
        should configure chef::config from a file (FAILED - 1)
        should merge the local config hash into chef::config (FAILED - 2)
        when openssl fips
          sets openssl in fips mode
      when there is no config_file defined
        should emit a warning
      when the config file is set and not found
        should use the passed in command line options and defaults
    when configuring the logger
      should initialise the chef logger
      when log_level is not set
        behaves like log_level_is_auto
          when STDOUT is to a tty
            configures the log level to :warn
            when force_logger is configured
              configures the log level to info
          when STDOUT is not to a tty
            configures the log level to :info
            when force_formatter is configured
              sets the log level to :warn
      when log_level is :auto
        behaves like log_level_is_auto
          when STDOUT is to a tty
            configures the log level to :warn
            when force_logger is configured
              configures the log level to info
          when STDOUT is not to a tty
            configures the log level to :info
            when force_formatter is configured
              sets the log level to :warn
      log_location
        behaves like sets log_location
          when the configured value is :syslog
            it sets log_location to an instance of Chef::Log::Syslog
        behaves like sets log_location
          when the configured value is "syslog"
            it sets log_location to an instance of Chef::Log::Syslog
  with an invalid log location
    logs a fatal error and exits
  class method: fatal!
[2016-11-10T16:32:01+00:00] ERROR: Chef RFC 062 (https://github.com/chef/chef-rfc/master/rfc062-exit-status.md) defines the exit codes that should be used with Chef.  Chef::Application::ExitCode defines valid exit codes In a future release, non-standard exit codes will be redefined as GENERIC_FAILURE unless `exit_status` is set to `:disabled` in your client.rb. at /home/jenkins/chef/spec/unit/application_spec.rb:299:in `block (3 levels) in <top (required)>'
    should log an error message to the logger
    when an exit code is supplied
[2016-11-10T16:32:01+00:00] ERROR: Chef RFC 062 (https://github.com/chef/chef-rfc/master/rfc062-exit-status.md) defines the exit codes that should be used with Chef.  Chef::Application::ExitCode defines valid exit codes In a future release, non-standard exit codes will be redefined as GENERIC_FAILURE unless `exit_status` is set to `:disabled` in your client.rb. at /home/jenkins/chef/spec/unit/application_spec.rb:305:in `block (4 levels) in <top (required)>'
      should exit with the given exit code
    when an exit code is not supplied
[2016-11-10T16:32:01+00:00] ERROR: Chef RFC 062 (https://github.com/chef/chef-rfc/master/rfc062-exit-status.md) defines the exit codes that should be used with Chef.  Chef::Application::ExitCode defines valid exit codes In a future release, non-standard exit codes will be redefined as GENERIC_FAILURE unless `exit_status` is set to `:disabled` in your client.rb. at /home/jenkins/chef/spec/unit/application_spec.rb:312:in `block (4 levels) in <top (required)>'
      should exit with the default exit code
  setup_application
    should raise an error
  run_application
    should raise an error
  when the config file is not available
    should warn for bad config file path
  run_chef_client
    with an application
      when called with an invalid argument
        should raise an argument error detailing the problem
      when called with an Array-like argument (#size)
        should be cool
  configuration errors
    when config file exists but contains errors
      should raise informative fatals for badly written config

Failures:

  1) Chef::Application when there are no configuration errors configure_chef when a config_file is present should configure chef::config from a file
     Failure/Error: Chef::Config.init_openssl

       #<File (class)> received :read with unexpected arguments
         expected: ("/etc/chef/default.rb")
              got: ("/proc/sys/crypto/fips_enabled")
     # ./chef-config/lib/chef-config/fips.rb:48:in `fips?'
     # ./chef-config/lib/chef-config/config.rb:562:in `block in <class:Config>'
     # /home/jenkins/.rvm/gems/ruby-2.3.1/gems/mixlib-config-2.2.4/lib/mixlib/config/configurable.rb:48:in `get'
     # /home/jenkins/.rvm/gems/ruby-2.3.1/gems/mixlib-config-2.2.4/lib/mixlib/config.rb:433:in `internal_get'
     # /home/jenkins/.rvm/gems/ruby-2.3.1/gems/mixlib-config-2.2.4/lib/mixlib/config.rb:454:in `internal_get_or_set'
     # /home/jenkins/.rvm/gems/ruby-2.3.1/gems/mixlib-config-2.2.4/lib/mixlib/config.rb:475:in `block in define_attr_accessor_methods'
     # ./chef-config/lib/chef-config/config.rb:568:in `init_openssl'
     # ./lib/chef/application.rb:88:in `configure_chef'
     # ./spec/unit/application_spec.rb:136:in `block (5 levels) in <top (required)>'

  2) Chef::Application when there are no configuration errors configure_chef when a config_file is present should merge the local config hash into chef::config
     Failure/Error: Chef::Config.init_openssl

       #<File (class)> received :read with unexpected arguments
         expected: ("/etc/chef/default.rb")
              got: ("/proc/sys/crypto/fips_enabled")
     # ./chef-config/lib/chef-config/fips.rb:48:in `fips?'
     # ./chef-config/lib/chef-config/config.rb:562:in `block in <class:Config>'
     # /home/jenkins/.rvm/gems/ruby-2.3.1/gems/mixlib-config-2.2.4/lib/mixlib/config/configurable.rb:48:in `get'
     # /home/jenkins/.rvm/gems/ruby-2.3.1/gems/mixlib-config-2.2.4/lib/mixlib/config.rb:433:in `internal_get'
     # /home/jenkins/.rvm/gems/ruby-2.3.1/gems/mixlib-config-2.2.4/lib/mixlib/config.rb:454:in `internal_get_or_set'
     # /home/jenkins/.rvm/gems/ruby-2.3.1/gems/mixlib-config-2.2.4/lib/mixlib/config.rb:475:in `block in define_attr_accessor_methods'
     # ./chef-config/lib/chef-config/config.rb:568:in `init_openssl'
     # ./lib/chef/application.rb:88:in `configure_chef'
     # ./spec/unit/application_spec.rb:141:in `block (5 levels) in <top (required)>'

Finished in 0.08831 seconds (files took 1.98 seconds to load)
33 examples, 2 failures

Failed examples:

rspec ./spec/unit/application_spec.rb:134 # Chef::Application when there are no configuration errors configure_chef when a config_file is present should configure chef::config from a file
rspec ./spec/unit/application_spec.rb:139 # Chef::Application when there are no configuration errors configure_chef when a config_file is present should merge the local config hash into chef::config
```

Could you please comment on the second test case failures if possible ?

**Comment by ghatwala** [comment]
@lamont-granquist : sorry for spamming , just rechecked all test case failures are referring to the same path : 
```
/proc/sys/crypto/fips_enabled
``
Apologies for the confusion !!!

**Comment by ghatwala** [comment]
Hi All,

Three test cases which were broken when run on a linux box where   -proc/sys/crypto/fips_enabled exists
Now to nullify fips on a linux box , we just need to export the below before running the complete test suite.
$ export CHEF_FIPS=""
After this above step, just run the complete test suite with below command again
# Run All the Tests
$ bundle exec rake spec
...........
..............

```
Top 10 slowest example groups:
  Shell
    5.85 seconds average (17.55 seconds / 3 examples) ./spec/functional/shell_spec.rb:25
  Chef::Resource::RegistryKey
    5.53 seconds average (5.53 seconds / 1 example) ./spec/functional/resource/registry_spec.rb:24
  knife serve
    5.02 seconds average (5.02 seconds / 1 example) ./spec/integration/knife/serve_spec.rb:22
  notifying_block
    4.19 seconds average (8.37 seconds / 2 examples) ./spec/integration/recipes/notifying_block_spec.rb:21
  Chef::Resource::Ohai
    4.14 seconds average (8.29 seconds / 2 examples) ./spec/functional/resource/ohai_spec.rb:21
  Accumulators
    2.71 seconds average (5.41 seconds / 2 examples) ./spec/integration/recipes/accumulator_spec.rb:4
  LWRPs
    2.67 seconds average (2.67 seconds / 1 example) ./spec/integration/recipes/lwrp_spec.rb:4
  chef-client
    2.58 seconds average (5.17 seconds / 2 examples) ./spec/integration/client/ipv6_spec.rb:21
  notifications
    2.45 seconds average (19.61 seconds / 8 examples) ./spec/integration/recipes/notifies_spec.rb:4
  chef-client
    2.44 seconds average (31.71 seconds / 13 examples) ./spec/integration/client/exit_code_spec.rb:8

Finished in 13 minutes 31 seconds (files took 12.5 seconds to load)
17009 examples, 0 failures, 31 pending
```

With this complete test suite is passing now. If possible , can we add this export command in readme -
https://github.com/chef/chef/blob/master/README.md , which will help in ensuring that anytime any linux box has FIPS enabled , the chef test cases will pass. 

Let me know your thoughts on this @lamont-granquist  ?

**Comment by ghatwala** [comment]
@lamont-granquist  , any comments on the above?

**Comment by thommay** [comment]
@ghatwala we'd be happy to accept a PR that adds that.

**Comment by ghatwala** [comment]
@thommay - Have raised a PR , please advise further action.

**Comment by ghatwala** [comment]
pull request id as suggested : https://github.com/chef/chef/pull/5559

**Comment by ghatwala** [comment]
@thommay  : i have  added  a sign-off message in the following DCO text has been manually added to PR 
Signed-off-by: Amit Ghatwal ghatwala@us.ibm.com . Let me know if there's anything amiss ?
