### ISSUE TITLE
default_unless reads merged values

### ISSUE THREAD

**Issue by b-dean** [chef/chef#5556]
## Description

If the normal level is set for an attribute, but default is not set, `default_unless` fails to set the attribute. This used to work in the 12.11.x versions and earlier.

I believe this caused by the changes in 86fa507 for #5029. Another similar (but not exactly the same) issue is #5094

## Chef Version

12.16.42 (although this has probably been an issue since 12.12.9)

## Platform Version

Ubuntu 14.04

## Replication Case

Create the file `example.rb` with the following:

```ruby
node.normal['abc'] = [{'def' => 1}]
puts node.normal.inspect

node.default_unless['abc'] = []
puts node.default.inspect

node.default['abc'].push({'def' => 2})
puts node.default.inspect
```

Then run that script with:

```
$ chef-apply example.rb
```

## Client Output

With Chef 12.11.18 this produces the output:
```
{"tags"=>[], "abc"=>[{"def"=>1}]}
{"abc"=>[]}
{"abc"=>[{"def"=>2}]}
```

However with Chef 12.16.42 it fails with: 
```
{"tags"=>[], "abc"=>[{"def"=>1}]}
{}
[2016-11-16T20:19:40+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-11-16T20:19:40+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-11-16T20:19:40+00:00] FATAL: NoMethodError: Undefined node attribute or method `push' on `node'. To set an attribute, use `push=value' instead.
```

## Stacktrace

```txt
Generated at 2016-11-16 20:19:40 +0000
NoMethodError: Undefined node attribute or method `push' on `node'. To set an attribute, use `push=value' instead.
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/node/attribute_collections.rb:197:in `method_missing'
example.rb:7:in `run_chef_recipe'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/apply.rb:192:in `instance_eval'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/apply.rb:192:in `run_chef_recipe'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/apply.rb:205:in `run_application'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/apply.rb:218:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/bin/chef-apply:25:in `<top (required)>'
/opt/chefdk/bin/chef-apply:58:in `load'
/opt/chefdk/bin/chef-apply:58:in `<main>'
```

**Comment by b-dean** [comment]
It looks to me like this is only setting default if the read of the merged attributes is `nil`. That isn't how it used to work. https://github.com/chef/chef/blob/v12.17.15/lib/chef/node/attribute.rb#L424

**Comment by lamont-granquist** [comment]
yep that looks incorrect.
