### ISSUE TITLE
HTTP 404 Not Found

### ISSUE THREAD

**Issue by WalshStephen** [chef/chef#5575]
## Description

I get a HTTP 404 when I do 'vagrant up' on my vagrantefile created by Chef Kitchen.

## Chef Version
ChefDK: 0.119.6
Chef Client: 12.15.19
Berks: 5.1.0
Kitchen: 1.13.2

## Platform Version
Host: Windows 7, VirtualBox 5.1.10, Vagrant 1.8.7
Vagrant VM: centos-6.7

## Replication Case
Simply run 'vagrant up'

## Client Output
```
==> default: [2016-11-23T20:21:30+00:00] INFO: Started chef-zero at chefzero://l
ocalhost:8889 with repository at /tmp/vagrant-chef/5ea943a5d1132d31adb5da83b450a
75d, /tmp/vagrant-chef
==> default:   One version per cookbook
==> default:
==> default: [2016-11-23T20:21:30+00:00] INFO: Forking chef instance to converge
...
==> default: Starting Chef Client, version 12.16.42
==> default: [2016-11-23T20:21:30+00:00] INFO: *** Chef 12.16.42 ***
==> default: [2016-11-23T20:21:30+00:00] INFO: Platform: x86_64-linux
==> default: [2016-11-23T20:21:30+00:00] INFO: Chef-client pid: 3161
==> default: [2016-11-23T20:21:32+00:00] INFO: HTTP Request Returned 404 Not Fou
nd: Object not found: chefzero://localhost:8889/nodes/vagrant-049873ad
==> default: [2016-11-23T20:21:32+00:00] INFO: HTTP Request Returned 404 Not Fou
nd: Parent not found: chefzero://localhost:8889/nodes
==> default:
==> default: ===================================================================
=============
==> default: Chef encountered an error attempting to load the node data for "vag
rant-049873ad"
==> default: ===================================================================
=============
==> default:
==> default:
==> default: Resource Not Found:
==> default: -------------------
==> default: The server returned a HTTP 404. This usually indicates that your ch
ef_server_url is incorrect.
==> default:
==> default:
==> default:
==> default: Relevant Config Settings:
==> default: -------------------------
==> default: chef_server_url "chefzero://localhost:8889"
==> default:
==> default:
==> default:
==> default: Platform:
==> default: ---------
==> default: x86_64-linux
==> default:
==> default:
==> default:
==> default: Running handlers:
==> default: [2016-11-23T20:21:32+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default:
==> default: [2016-11-23T20:21:32+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 0 resources updated in 01 seconds
==> default: [2016-11-23T20:21:32+00:00] FATAL: Stacktrace dumped to /var/chef/c
ache/chef-stacktrace.out
==> default: [2016-11-23T20:21:32+00:00] FATAL: Please provide the contents of t
he stacktrace.out file if you file a bug report
==> default: [2016-11-23T20:21:32+00:00] ERROR: 404 "Not Found"
==> default: [2016-11-23T20:21:32+00:00] FATAL: Chef::Exceptions::ChildConvergeE
rror: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it.
```

## Stacktrace
```
Generated at 2016-11-23 19:40:43 +0000
Net::HTTPServerException: 404 "Not Found"
/opt/chef/embedded/lib/ruby/2.3.0/net/http/response.rb:120:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/http.rb:150:in `request'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/http.rb:131:in `post'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/node.rb:616:in `create'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/node.rb:569:in `rescue in find_or_create'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/node.rb:565:in `find_or_create'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/policy_builder/dynamic.rb:72:in `load_node'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:467:in `load_node'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:269:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:294:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:282:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:282:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:247:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:235:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'

>>>> Caused by Net::HTTPServerException: 404 "Not Found"
/opt/chef/embedded/lib/ruby/2.3.0/net/http/response.rb:120:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/http.rb:150:in `request'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/http.rb:115:in `get'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/node.rb:581:in `load'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/node.rb:565:in `find_or_create'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/policy_builder/dynamic.rb:72:in `load_node'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:467:in `load_node'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:269:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:294:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:282:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:282:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:247:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:235:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'

```

**Comment by WalshStephen** [comment]
I've tried rolling Vagrant back to 1.8.1 and VirtualBox back to 5.0.... same error.

Does anybody know...
A) If this is an error caused by Chef or Vagrant
B) If this is a known error
and obviously, C) a solution to this?

Thanks :)

**Comment by WalshStephen** [comment]
I've just closed this issue. My chef.nodes_path was incorrect. Newbie mistake
