### ISSUE TITLE
Windows Registry settings - Fails on all Chef Client greater 12.8.1 - Encoding::InvalidByteSequenceError

### ISSUE THREAD

**Issue by knightorc** [chef/chef#5600]
## Description

Briefly describe the issue

## Chef Version

Chef Client > 12.8.1

## Platform Version

Win7 32/x64 (Fails) , Windows 2K8R2 64 (Fails),  Windows 2K12R12 no issues.

Also of note, this is only an issue with our machines that have been running for a long time.  Not able to reproduce in TestKitchen on either Win7 or Win28R2

## Client Output

```
Recipe: vci_windows_settings::disable_machine_password_expiry
  * registry_key[HKLM\SYSTEM\CurrentControlSet\services\Netlogon\Parameters] action create

    ================================================================================
    Error executing action `create` on resource 'registry_key[HKLM\SYSTEM\CurrentControlSet\services\Netlogon\Parameters]'
    ================================================================================

    Encoding::InvalidByteSequenceError
    ----------------------------------
    incomplete "\x00" on UTF-16LE

    Cookbook Trace:
    ---------------
    C:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    C:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    C:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    C:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    C:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

    Resource Declaration:
    ---------------------
    # In C:/chef/cache/cookbooks/vci_windows_settings/recipes/disable_machine_password_expiry.rb

     15: registry_key 'HKLM\SYSTEM\CurrentControlSet\services\Netlogon\Parameters' do
     16:   values [{
     17:     name: 'DisablePasswordChange',
     18:     type: :dword,
     19:     data: 1
     20:   }]
     21:   action :create
     22:   # only_if { disable }
     23: end
```

## Gem list

C:\Windows\system32>gem list

*** LOCAL GEMS ***

addressable (2.4.0)
appbundler (0.9.0)
ast (2.3.0)
bigdecimal (default: 1.2.8)
binding_of_caller (0.7.2)
builder (3.2.2)
bundler (1.12.5)
byebug (9.0.6)
chef (12.15.19 universal-mingw32)
chef-config (12.15.19)
chef-handler-updated-resources (0.2.1)
chef-zero (5.1.0)
chef_handler_foreman (0.1.1)
cheffish (4.0.0)
chefstyle (0.4.0)
coderay (1.1.1)
debug_inspector (0.0.2)
did_you_mean (1.0.0)
diff-lcs (1.2.5)
docile (1.1.5)
erubis (2.7.0)
faraday (0.9.2)
ffi (1.9.14 ruby x64-mingw32)
ffi-win32-extensions (1.0.3)
ffi-yajl (2.3.0)
fuzzyurl (0.9.0)
hashie (3.4.6)
highline (1.7.8)
iniparse (1.4.2)
io-console (default: 0.4.5)
ipaddress (0.8.3)
json (default: 1.8.3)
libyajl2 (1.2.0)
method_source (0.8.2)
mini_portile2 (2.1.0)
minitest (5.8.3)
mixlib-archive (0.2.0)
mixlib-authentication (1.4.1)
mixlib-cli (1.7.0)
mixlib-config (2.2.4)
mixlib-log (1.7.1)
mixlib-shellout (2.2.7 universal-mingw32)
multi_json (1.12.1)
multipart-post (2.0.0)
net-scp (1.2.1)
net-sftp (2.1.2)
net-ssh (3.2.0)
net-ssh-gateway (1.2.0)
net-ssh-multi (1.2.1)
net-telnet (0.1.1)
nokogiri (1.6.8 ruby x64-mingw32)
ohai (8.20.0)
parser (2.3.1.4)
pkg-config (1.1.7)
plist (3.2.0)
power_assert (0.2.6)
powerpack (0.1.1)
proxifier (1.0.3)
pry (0.10.4)
pry-byebug (3.4.0)
pry-remote (0.1.8)
pry-stack_explorer (0.4.9.2)
psych (default: 2.0.17)
rack (2.0.1)
rainbow (2.1.0)
rake (11.3.0, 10.4.2)
rb-readline (0.5.3)
rdoc (default: 4.2.1)
rspec (3.5.0)
rspec-core (3.5.4)
rspec-expectations (3.5.0)
rspec-its (1.2.0)
rspec-mocks (3.5.0)
rspec-support (3.5.0)
rspec_junit_formatter (0.2.3)
rubocop (0.42.0)
ruby-prof (0.16.2)
ruby-progressbar (1.8.1)
rubygems-update (2.6.7)
rubyzip (1.2.0)
serverspec (2.36.1)
sfl (2.2)
simplecov (0.12.0)
simplecov-html (0.10.0)
slop (3.6.0)
specinfra (2.63.1)
syslog-logger (1.6.8)
systemu (2.6.5)
test-unit (3.1.5)
unicode-display_width (1.1.1)
uuidtools (2.1.5)
vault (0.4.0)
win32-api (1.6.0 universal-mingw32, 1.5.3 universal-mingw32)   ** Two versions tried.
win32-dir (0.5.1)
win32-event (0.6.3)
win32-eventlog (0.6.3)
win32-ipc (0.7.0)
win32-mmap (0.4.2)
win32-mutex (0.4.3)
win32-process (0.8.3)
win32-service (0.8.9)
windows-api (0.4.4)
windows-pr (1.2.5)
wmi-lite (1.0.0)

**Comment by knightorc** [comment]
```
C:\Windows\system32>cat c:\chef\cache\chef-stacktrace.out
Generated at 2016-11-30 19:43:15 +0000
Encoding::InvalidByteSequenceError: registry_key[HKLM\SYSTEM\CurrentControlSet\services\Netlogon\Parameters] (vci_windows_settings::disable_machine_password_expiry line 15) had an error: Encoding::InvalidByteSequenceErro
r: incomplete "\x00" on UTF-16LE
C:/opscode/chef/embedded/lib/ruby/2.3.0/win32/registry.rb:650:in `encode'
C:/opscode/chef/embedded/lib/ruby/2.3.0/win32/registry.rb:650:in `read'
C:/opscode/chef/embedded/lib/ruby/2.3.0/win32/registry.rb:576:in `each_value'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/win32/registry.rb:59:in `map'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/win32/registry.rb:59:in `block in get_values'
C:/opscode/chef/embedded/lib/ruby/2.3.0/win32/registry.rb:435:in `open'
C:/opscode/chef/embedded/lib/ruby/2.3.0/win32/registry.rb:542:in `open'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/win32/registry.rb:58:in `get_values'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/provider/registry_key.rb:55:in `load_current_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/provider.rb:128:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/resource.rb:603:in `run_action'
C:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
C:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
C:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
C:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/client.rb:669:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/client.rb:664:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/client.rb:664:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/client.rb:703:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/client.rb:283:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application.rb:284:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application.rb:260:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application.rb:243:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application.rb:60:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/bin/chef-client:26:in `<top (required)>'
c:/opscode/chef/embedded/bin/chef-client:22:in `load'
c:/opscode/chef/embedded/bin/chef-client:22:in `<main>'

>>>> Caused by Encoding::InvalidByteSequenceError: incomplete "\x00" on UTF-16LE
C:/opscode/chef/embedded/lib/ruby/2.3.0/win32/registry.rb:650:in `encode'
C:/opscode/chef/embedded/lib/ruby/2.3.0/win32/registry.rb:650:in `read'
C:/opscode/chef/embedded/lib/ruby/2.3.0/win32/registry.rb:576:in `each_value'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/win32/registry.rb:59:in `map'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/win32/registry.rb:59:in `block in get_values'
C:/opscode/chef/embedded/lib/ruby/2.3.0/win32/registry.rb:435:in `open'
C:/opscode/chef/embedded/lib/ruby/2.3.0/win32/registry.rb:542:in `open'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/win32/registry.rb:58:in `get_values'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/provider/registry_key.rb:55:in `load_current_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/provider.rb:128:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/resource.rb:603:in `run_action'
C:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
C:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
C:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
C:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/client.rb:669:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/client.rb:664:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/client.rb:664:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/client.rb:703:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/client.rb:283:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application.rb:284:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application.rb:260:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application.rb:243:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application.rb:60:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/bin/chef-client:26:in `<top (required)>'
c:/opscode/chef/embedded/bin/chef-client:22:in `load'
c:/opscode/chef/embedded/bin/chef-client:22:in `<main>'
```

**Comment by knightorc** [comment]
I'm going to close this.  This was caused only on systems that originally had the value configured by the legacy windows_registry method by either Chef 10 or 11, pre registry_key method.  Yes we have long lived systems.
