### ISSUE TITLE
Intermittent Chef::Exceptions::ProviderNotFound errors

### ISSUE THREAD

**Issue by rayterrill** [chef/chef#5626]
## Description

Receiving intermittent Chef::Exceptions::ProviderNotFound errors on some nodes. Resolves itself with no changes.

## Chef Version

12.16.42

## Platform Version

Server 2012 R2.

## Replication Case

Unfortunately, this is intermittent, but happening relatively frequently. It seems to occur early in the AM, and only on some nodes.

## Client Output

```
------------------------------------------------------
                      EXCEPTION                       
------------------------------------------------------
Chef::Exceptions::ProviderNotFound: dsc_resource[NetFramework35Core] (SQLServer::default line 15) had an error: Chef::Exceptions::ProviderNotFound: ["You must have Powershell version >= 5.0.10018.0 to use dsc_resource."]
------------------------------------------------------
                     STACK TRACE                      
------------------------------------------------------
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/mixin/why_run.rb:240:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/mixin/why_run.rb:321:in `block in run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/mixin/why_run.rb:320:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/mixin/why_run.rb:320:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/provider.rb:155:in `process_resource_requirements'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/provider.rb:133:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource.rb:622:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/runner.rb:69:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/runner.rb:97:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/runner.rb:96:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/client.rb:669:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/client.rb:664:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/client.rb:664:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/client.rb:703:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/client.rb:283:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application.rb:276:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application.rb:252:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application.rb:235:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:65:in `load'
C:/opscode/chef/bin/chef-client:65:in `<main>'
```

**Comment by lamont-granquist** [comment]
The error message seems pretty clear.  Internally chef-client is using ohai's `node[:languages][:powershell][:version]` attribute so maybe something is going wrong there.  It doesn't look like there can be a bug in this repo though.

The ohai code also seems pretty straightforwards:

https://github.com/chef/ohai/blob/master/lib/ohai/plugins/powershell.rb#L24

If you're seeing intermittent nightly failures, you've probably got some kind of scheduled task which is doing something to powershell or to ohai's ability to find it.  Upgrading it?  Something mangling the PATH?

**Comment by rayterrill** [comment]
Interesting. No scheduled tasks during that time (or anything at all that does anything like mess with path/powershell/upgrading, etc). The Ohai code is indeed very simple.

I almost wonder if it's a resource issue, or something similar - is there an easy to track down what was actually returned by that Ohai shell_out call?

**Comment by mwrock** [comment]
Do you have WMF 5 installed on the node @rayterrill ? If not then I think this error is expected.

**Comment by rayterrill** [comment]
@mwrock Yep - WMF5 installed. That's what's weird - I have chef-client running every 15 minutes, and the failures are only like once a day on some nodes, and very early. Checking on the VMWare side, it almost appears to correlate with high resource utilization (CPU/RAM) - Wondering if it's not getting back an answer at all on the PowerShell version, or timing out, or something like that, as opposed to truly not being able to find WMF5.

**Comment by lamont-granquist** [comment]
timeout errors or whatever windows does for low-ram allocation errors would make perfect sense.

we should really build some kind of way for chef-client and ohai to interact so there was some way for dsc_resource to know that the ohai powershell plugin actually failed hard as opposed to just not finding powershell.   if that's the bug, though, it boils down to a fairly massive refactoring that we probably have an epic kicking around somewhere for.

**Comment by rayterrill** [comment]
Haha. I love your guys' comments on these bugs and questions. :)

I'll check into bumping up resources to see if that solves it - that'd be a pretty easy workaround, and would strengthen the case that it's resource-related, although I'm almost positive it is - it's only happening on nodes that I know are already under resource pressures.

**Comment by lamont-granquist** [comment]
hopefully that resolved the issue..
