### ISSUE TITLE
Unable to run a PowerShell block containing a test against a folder where the last folder in the path contains a space

### ISSUE THREAD

**Issue by andymccall** [chef/chef#5649]
Sorry if this isn't a Chef bug, I've been debating if its limitation of PowerShell or a bug in Chef, in the end I couldn't decide so I've logged this issue. 

## Description

Unable to run a PowerShell block containing a test against a folder where the last folder in the path contains a space.  The PowerShell produced is:

```
# Execute the user's code in a script block --
$chefscriptresult =
{
 Test-Path D:\test\test thispath

 # This assignment doesn't affect the block's return value
 $global:lastcmdlet = $?
}.invokereturnasis()
```

The problem is with this line: Test-Path D:\test\test thispath

I have been unable to work around this in Chef/Ruby by adding additional \'s and/or \".  While you can get a test to work against a directory using:

`test_path="\"D:\\test\test thispath\""`

You are unable to use this path to expand up, for example:

`test_file="#{test_path}\\file.txt"`

As this is translated to:

`"D:\test\test thispath\"file.txt`

Which won't work.  You can work around this in PowerShell directly by simply doing:

 Test-Path "D:\test\test thispath" and  "Test-Path D:\test\test thispath\file.txt" however there I don't think there is a way to get Chef to produce this kind of output.

## Chef Version

Chef: 12.15.19

## Platform Version

Microsoft Windows 2008R2

## Replication Case

```
test_path="D:\\test\test thispath"

powershell_script "create_directoy_if_not_exists" do
   guard_interpreter :powershell_script
   code "New-Item -ItemType Directory -Path #{test_path} -Force"
   not_if "Test-Path #{test_path}"
end
```

## Client Output

```
Failed Chef Client run 355401dd-acf5-405d-9118-2af98ac29640 in 30.2172 seconds.
 Exception type: Mixlib::ShellOut::ShellCommandFailed
 Exception message: powershell_script[create_directoy_if_not_exists] (testcookbook::test line 2) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/chef/AppData/Local/Temp/chef-script20161214-5060-sb2v6l.ps1" ----
STDOUT: 
STDERR: C:\Users\chef\AppData\Local\Temp\chef-script20161214-5060-sb2v6l.ps1 : A 
positional parameter cannot be found that accepts argument 'thispath'.
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep 
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio 
   n,chef-script20161214-5060-sb2v6l.ps1
---- End output of "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/chef/AppData/Local/Temp/chef-script20161214-5060-sb2v6l.ps1" ----
Ran "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/chef/AppData/Local/Temp/chef-script20161214-5060-sb2v6l.ps1" returned 1
 Exception backtrace: C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.7-universal-mingw32/lib/mixlib/shellout.rb:289:in `invalid!'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-shellout-2.2.7-universal-mingw32/lib/mixlib/shellout.rb:276:in `error!'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/mixin/shell_out.rb:45:in `shell_out!'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider/execute.rb:62:in `block in action_run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/mixin/why_run.rb:52:in `add_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:176:in `converge_by'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider/execute.rb:60:in `action_run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider/script.rb:63:in `action_run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider/windows_script.rb:57:in `action_run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider/powershell_script.rb:35:in `action_run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:145:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource.rb:622:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:69:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:97:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:96:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:670:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:665:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:665:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:704:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:284:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:276:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:252:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:235:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:427:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:68:in `load'
C:/opscode/chef/bin/chef-client:68:in `<main>'
```

## Stacktrace

N/A

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by andymccall** [comment]
I'm away from my computer right now, but the second I left the office I realised I hadn't tested:

test_path="D:\\test\test thispath"

powershell_script "create_directoy_if_not_exists" do
   guard_interpreter :powershell_script
   code "New-Item -ItemType Directory -Path \"#{test_path}\" -Force"
   not_if "Test-Path \"#{test_path}\""
end

Which I suspect will work.

**Comment by mwrock** [comment]
I would try:
```
test_path="D:/test/test thispath" # needs either forward slashes or double backslashes

powershell_script "create_directoy_if_not_exists" do
guard_interpreter :powershell_script
code "New-Item -ItemType Directory -Path "#{test_path}" -Force"
not_if "Test-Path '#{test_path}'" # inner quotes should be single
end
```

**Comment by andymccall** [comment]
The following works:

```
test_path="D:\\test\\test thispath"

powershell_script "create_directoy_if_not_exists" do
guard_interpreter :powershell_script
code "New-Item -ItemType Directory -Path \"#{test_path}\" -Force"
not_if "Test-Path \"#{test_path}\"" 
end
```

Closing as its not a bug, more a idiosyncrasy in using powershell_script blocks within Chef.
