### ISSUE TITLE
[Regression?] chef_file with atomic_update true fails on windows

### ISSUE THREAD

**Issue by axos88** [chef/chef#5654]
## Description

Seems to be related to https://tickets.opscode.com/browse/CHEF-4625.
If the destination path exists, (and should be updated), this resource:

	remote_file jar_path do
		source "#{artifactory_base}/#{url}"
		atomic_update false # Workaround, wouldn't want to leave this here...

		notifies :restart, "service[#{service_name}]"
	end

fails with EACCESS. (See output below)

## Chef Version

12.17.44

## Platform Version

Windows 2012R2

## Client Output

```
==> default:       ================================================================================
==> default:       Error executing action `create` on resource 'remote_file[C:/vertx/outbound/outbound.jar]'
==> default:       ================================================================================
==> default:       
==> default:       Errno::EACCES
==> default:       -------------
==> default:       Permission denied @ rb_file_s_rename - (C:/Users/vagrant/AppData/Local/Temp/chef-rest20161216-6644-1xhe2sp, C:/vertx/outbound/outbound.jar)
==> default:       
==> default:       Resource Declaration:
==> default:       ---------------------
==> default:       # In C:/chef/cache/cookbooks/xxx/resources/vertx_module.rb
==> default:       
==> default:        43: 	remote_file jar_path do
==> default:        44: 		source "#{artifactory_base}/#{url}"
==> default:        45: 		atomic_update true
==> default:        46: 
==> default:        47: 		notifies :restart, "service[#{service_name}]"
==> default:        48: 	end
==> default:        49: 
==> default:       
==> default:       Compiled Resource:
==> default:       ------------------
==> default:       # Declared in C:/chef/cache/cookbooks/xxx/resources/vertx_module.rb:43:in `block in class_from_file'
==> default:       
==> default:       remote_file("C:/vertx/outbound/outbound.jar") do
==> default:         provider Chef::Provider::RemoteFile
==> default:         action [:create]
==> default:         retries 0
==> default:         retry_delay 2
==> default:         default_guard_interpreter :default
==> default:         source ["https://admin:xxx@artifactory.xxx/artifactory/xxx.jar"]
==> default:         use_etag true
==> default:         use_last_modified true
==> default:         declared_type :remote_file
==> default:         cookbook_name "xxx"
==> default:         path "C:/vertx/outbound/outbound.jar"
==> default:         atomic_update true
==> default:       end
==> default:       
==> default:       Platform:
==> default:       ---------
==> default:       x64-mingw32
==> default:       
==> default: [2016-12-16T14:37:53+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default:     
==> default:     ================================================================================
==> default:     Error executing action `deploy` on resource 'xxx_vertx_module[outbound]'
==> default:     ================================================================================
==> default:     
==> default:     Errno::EACCES
==> default:     -------------
==> default:     remote_file[C:/vertx/outbound/outbound.jar] (C:/chef/cache/cookbooks/xxx/resources/vertx_module.rb line 43) had an error: Errno::EACCES: Permission denied @ rb_file_s_rename - (C:/Users/vagrant/AppData/Local/Temp/chef-rest20161216-6644-1xhe2sp, C:/vertx/outbound/outbound.jar)
==> default:     
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In C:/chef/cache/cookbooks/xxx/recipes/vertx_modules.rb
==> default:     
==> default:      12: 	vertx_module mod_name do
==> default:      13: 		url mod[:url]
==> default:      14: 		extra_args mod[:extra_args] unless mod[:extra_args].nil?
==> default:      15: 		min_cluster_size mod[:min_cluster_size] unless mod[:min_cluster_size].nil?
==> default:      16: 	end
==> default:      17: end
==> default:     
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in C:/chef/cache/cookbooks/xxx/recipes/vertx_modules.rb:12:in `block in from_file'
==> default:     
==> default:     xxx_vertx_module("outbound") do
==> default:       action [:deploy]
==> default:       retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :default
==> default:       declared_type :vertx_module
==> default:       cookbook_name "xxx"
==> default:       recipe_name "vertx_modules"
==> default:       url "libs-snapshot-local/de/xxx/dist/OutboundModule/1.0-SNAPSHOT/OutboundModule-1.0-20161207.160845-3.jar"
==> default:       extra_args ["-Djavax.net.ssl.trustStorePassword=xxx!", "-Djavax.net.ssl.trustStore=C:/keystores/keystore_vertx.jks"]
==> default:     end
==> default:     
==> default: 
==> default:     Platform:
==> default:     ---------
==> default:     x64-mingw32
==> default:     
==> default: [2016-12-16T14:37:53+00:00] INFO: Running queued delayed notifications before re-raising exception
```

## Stacktrace

```
Generated at 2016-12-16 14:38:15 +0000
Errno::EACCES: xxx_vertx_module[outbound] (xxx::vertx_modules line 12) had an error: Errno::EACCES: remote_file[C:/vertx/outbound/outbound.jar] (C:/chef/cache/cookbooks/xxx/resources/vertx_module.rb line 43) had an error: Errno::EACCES: Permission denied @ rb_file_s_rename - (C:/Users/vagrant/AppData/Local/Temp/chef-rest20161216-6644-1xhe2sp, C:/vertx/outbound/outbound.jar)
C:/opscode/chef/embedded/lib/ruby/2.3.0/fileutils.rb:528:in `rename'
C:/opscode/chef/embedded/lib/ruby/2.3.0/fileutils.rb:528:in `block in mv'
C:/opscode/chef/embedded/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
C:/opscode/chef/embedded/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
C:/opscode/chef/embedded/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
C:/opscode/chef/embedded/lib/ruby/2.3.0/fileutils.rb:517:in `mv'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/file_content_management/deploy/mv_windows.rb:88:in `deploy'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider/file.rb:391:in `update_file_contents'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider/file.rb:423:in `block in do_contents_changes'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/mixin/why_run.rb:52:in `add_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:176:in `converge_by'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider/file.rb:422:in `do_contents_changes'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider/file.rb:154:in `action_create'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:145:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource.rb:622:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:69:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:97:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:96:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:362:in `compile_and_converge_action'
(eval):2:in `action_deploy'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:145:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource.rb:622:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:69:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:97:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:96:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:670:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:665:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:665:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:704:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:284:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:276:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:252:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:235:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:68:in `load'
C:/opscode/chef/bin/chef-client:68:in `<main>'

>>>> Caused by Errno::EACCES: Permission denied @ rb_file_s_rename - (C:/Users/vagrant/AppData/Local/Temp/chef-rest20161216-6644-1xhe2sp, C:/vertx/outbound/outbound.jar)
C:/opscode/chef/embedded/lib/ruby/2.3.0/fileutils.rb:528:in `rename'
C:/opscode/chef/embedded/lib/ruby/2.3.0/fileutils.rb:528:in `block in mv'
C:/opscode/chef/embedded/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
C:/opscode/chef/embedded/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
C:/opscode/chef/embedded/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
C:/opscode/chef/embedded/lib/ruby/2.3.0/fileutils.rb:517:in `mv'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/file_content_management/deploy/mv_windows.rb:88:in `deploy'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider/file.rb:391:in `update_file_contents'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider/file.rb:423:in `block in do_contents_changes'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/mixin/why_run.rb:52:in `add_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:176:in `converge_by'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider/file.rb:422:in `do_contents_changes'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider/file.rb:154:in `action_create'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:145:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource.rb:622:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:69:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:97:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:96:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:362:in `compile_and_converge_action'
(eval):2:in `action_deploy'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/provider.rb:145:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource.rb:622:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:69:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:97:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/runner.rb:96:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:670:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:665:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:665:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:704:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:284:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:276:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:252:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:235:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:68:in `load'
C:/opscode/chef/bin/chef-client:68:in `<main>'
```

**Comment by lamont-granquist** [comment]
```
rb_file_s_rename - (C:/Users/vagrant/AppData/Local/Temp/chef-rest20161216-6644-1xhe2sp, C:/vertx/outbound/outbound.jar)
```

is `Chef::Config[:file_staging_uses_destdir]` false somehow?

**Comment by lamont-granquist** [comment]
dup of #2401 most likely.

**Comment by axos88** [comment]
I did not override it's value, should be at the default.

**Comment by lamont-granquist** [comment]
closing as dup of #2401
