### ISSUE TITLE
Chef Zero/local-mode issue with nodes folder/file permissions on Windows

### ISSUE THREAD

**Issue by ericrlarson** [chef/chef#5768]
## Description

When using chef-zero/local-mode to apply cookbook policies we are running into an error when chef-client is run by a second time by a different user than the first time.  

We are seeing this error in the Chef output: `Chef encountered an error attempting to load the node data for "Win2012Test.GREMLINS.local"`

I have been able to trace this back to a Windows file permissions root cause.  The `nodes` folder created by the client and all the node files contained in that folder are owned by the user that created them and no one else has any access to them at all.  Not even read access.  So when the second execution is done under a different user account the node information cannot be loaded.

Also all of the files under the `local-mode-cache` folder are owned by the user that created them and are completely unaccessible by any other user.  Interestingly the folders created there are accessible by the following profiles:

* CREATOR OWNER
* SYSTEM
* Administrators (the group not the user)
* Users (the group)

Is there a reason that the `nodes` folder is locked down so tightly?  Can the code be changed to use a broader set of permissions for the `nodes` folder and its files?

FYI I have seen some of the issues filed for this error message which are related to Vagrant and other Chef-related tools.  This is a different issue connected with chef-client only.

## Chef Version

12.17.44

## Platform Version

Windows 2012 R2

## Replication Case

1. Install Chef-Client
2. Move cookbooks to the node
3. Run chef-client -z -o `<recipe>` from the repo folder
4. Logout
5. Login as a different user
6. Run Run chef-client -z -o `<recipe>` from the repo folder

## Client Output

```
Starting Chef Client, version 12.17.44
[2017-01-30T12:34:22-05:00] ERROR: #<Errno::EACCES: Permission denied @ rb_sysopen - C:/Support/RadiologyServiceTools/InstallAutomation/nodes/Win2012Test.GREMLINS.local.json>
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/chef_fs/file_system/repository/base_file.rb:138:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/chef_fs/file_system/repository/base_file.rb:138:in `open'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/chef_fs/file_system/repository/base_file.rb:138:in `write'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/chef_fs/file_system/repository/directory.rb:89:in `create_child'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/chef_fs/file_system/repository/nodes_dir.rb:36:in `create_child'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/chef_fs/file_system/multiplexed_dir.rb:59:in `create_child'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/chef_fs/chef_fs_data_store.rb:255:in `block in create'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/chef_fs/chef_fs_data_store.rb:796:in `with_parent_dir'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/chef_fs/chef_fs_data_store.rb:253:in `create'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-zero-5.1.0/lib/chef_zero/data_store/v1_to_v2_adapter.rb:34:in `block in create'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-zero-5.1.0/lib/chef_zero/data_store/v1_to_v2_adapter.rb:113:in `fix_exceptions'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-zero-5.1.0/lib/chef_zero/data_store/v1_to_v2_adapter.rb:33:in `create'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-zero-5.1.0/lib/chef_zero/rest_base.rb:183:in `create_data'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-zero-5.1.0/lib/chef_zero/endpoints/rest_list_endpoint.rb:31:in `post'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-zero-5.1.0/lib/chef_zero/endpoints/nodes_endpoint.rb:24:in `post'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-zero-5.1.0/lib/chef_zero/rest_base.rb:62:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-zero-5.1.0/lib/chef_zero/rest_router.rb:24:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-zero-5.1.0/lib/chef_zero/server.rb:665:in `block in app'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-zero-5.1.0/lib/chef_zero/server.rb:337:in `handle_socketless_request'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-zero-5.1.0/lib/chef_zero/socketless_server_map.rb:87:in `request'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-zero-5.1.0/lib/chef_zero/socketless_server_map.rb:33:in `request'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/http/socketless_chef_zero_client.rb:154:in `request'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/http.rb:340:in `block in send_http_request'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/http.rb:372:in `block in retrying_http_errors'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/http.rb:370:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/http.rb:370:in `retrying_http_errors'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/http.rb:333:in `send_http_request'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/http.rb:148:in `request'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/http.rb:131:in `post'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/node.rb:616:in `create'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/node.rb:569:in `rescue in find_or_create'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/node.rb:565:in `find_or_create'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/policy_builder/dynamic.rb:72:in `load_node'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:468:in `load_node'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:270:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:276:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:252:in `blockin run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:235:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:68:in `load'
C:/opscode/chef/bin/chef-client:68:in `<main>'

================================================================================
Chef encountered an error attempting to load the node data for "Win2012Test.GREMLINS.local"
================================================================================

Unknown Server Error:
---------------------
The server had a fatal error attempting to load the node data.

Server Response:
----------------
Exception raised! #<Errno::EACCES: Permission denied @ rb_sysopen - C:/Support/RadiologyServiceTools/InstallAutomation/nodes/Win2012Test.GREMLINS.local.json>
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/chef_fs/file_system/repository/base_file.rb:138:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/chef_fs/file_system/repository/base_file.rb:138:in `open'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/chef_fs/file_system/repository/base_file.rb:138:in `write'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/chef_fs/file_system/repository/directory.rb:89:in `create_child'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/chef_fs/file_system/repository/nodes_dir.rb:36:in `create_child'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/chef_fs/file_system/multiplexed_dir.rb:59:in `create_child'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/chef_fs/chef_fs_data_store.rb:255:in `block in create'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/chef_fs/chef_fs_data_store.rb:796:in `with_parent_dir'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/chef_fs/chef_fs_data_store.rb:253:in `create'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-zero-5.1.0/lib/chef_zero/data_store/v1_to_v2_adapter.rb:34:in `block in create'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-zero-5.1.0/lib/chef_zero/data_store/v1_to_v2_adapter.rb:113:in `fix_exceptions'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-zero-5.1.0/lib/chef_zero/data_store/v1_to_v2_adapter.rb:33:in `create'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-zero-5.1.0/lib/chef_zero/rest_base.rb:183:in `create_data'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-zero-5.1.0/lib/chef_zero/endpoints/rest_list_endpoint.rb:31:in `post'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-zero-5.1.0/lib/chef_zero/endpoints/nodes_endpoint.rb:24:in `post'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-zero-5.1.0/lib/chef_zero/rest_base.rb:62:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-zero-5.1.0/lib/chef_zero/rest_router.rb:24:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-zero-5.1.0/lib/chef_zero/server.rb:665:in `block in app'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-zero-5.1.0/lib/chef_zero/server.rb:337:in `handle_socketless_request'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-zero-5.1.0/lib/chef_zero/socketless_server_map.rb:87:in `request'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-zero-5.1.0/lib/chef_zero/socketless_server_map.rb:33:in `request'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/http/socketless_chef_zero_client.rb:154:in `request'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/http.rb:340:in `block in send_http_request'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/http.rb:372:in `block in retrying_http_errors'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/http.rb:370:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/http.rb:370:in `retrying_http_errors'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/http.rb:333:in `send_http_request'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/http.rb:148:in `request'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/http.rb:131:in `post'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/node.rb:616:in `create'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/node.rb:569:in `rescue in find_or_create'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/node.rb:565:in `find_or_create'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/policy_builder/dynamic.rb:72:in `load_node'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:468:in `load_node'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/client.rb:270:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:276:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:252:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:235:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:68:in `load'
C:/opscode/chef/bin/chef-client:68:in `<main>'

Platform:
---------
x64-mingw32


Running handlers:
[2017-01-30T12:34:22-05:00] ERROR: Running exception handlers
Running handlers complete
[2017-01-30T12:34:22-05:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 07 seconds
[2017-01-30T12:34:22-05:00] FATAL: Stacktrace dumped to c:/support/radiologyservicetools/installautomation/local-mode-cache/cache/chef-stacktrace.out
[2017-01-30T12:34:22-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-01-30T12:34:22-05:00] FATAL: Chef::Exceptions::RunFailedWrappingError: Found 1 errors, they are stored in the backtrace
```

## Stacktrace

See above

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* Requests for new or alternative functionality should be made to [feedback.chef.io](https://feedback.chef.io/forums/301644-chef-product-feedback/category/110832-chef-client)
* [Chef Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by lamont-granquist** [comment]
```
FYI I have seen some of the issues filed for this error message which are related to Vagrant and other Chef-related tools.
```

@ericrlarson could you drop in some links to those, particularly if they're fresh issues with chef 12.17.x/12.18.x?

**Comment by ericrlarson** [comment]
The main issue I found is here: https://github.com/chef/chef-zero/issues/218.  @jpswade links to several articles, but none seem to be this issue.

Some of the other references/links that I read with related issues:

* https://groups.google.com/forum/#!topic/learnchef-fundamentals-webinar/LYe_i_QIWdU
* https://github.com/mitchellh/vagrant/issues/6110
* https://github.com/chef/chef/issues/1574
* https://github.com/chef/chef/issues/1778

All of them are different in various ways, and none mentioned file permissions.

**Comment by lamont-granquist** [comment]
Yeah the file perms lockdown was only added very recently, those issues are unrelated and just look like old bugginess.

**Comment by lamont-granquist** [comment]
i think #5601 was the change to the file perms

**Comment by ericrlarson** [comment]
Hmmm...ok interesting.

I understand wanting to be careful with file permissions.  Was there ever a discussion on the why here?  Locking down the files like this means that you can only ever have one user account running chef, and that is not the case in our environment.

**Comment by ericrlarson** [comment]
Also is there anyway to achieve a different outcome? ( configure a user group for example? )

**Comment by lamont-granquist** [comment]
i don't think there was a public discussion as to the 'whys'.  paging @thommay and @scottopherson as better people to answer those questions.

**Comment by ericrlarson** [comment]
That is fine.  The real question will be how to get around the issue.

**Comment by tduffield** [comment]
So the reason the file permissions was put into place was for security. If the node object contains sensitive data like passwords we don't want just any user who has access to the box to have access to that data. Many users have a dedicated chef-client service user that runs chef-client and people trigger chef-client runs either by having access to that user account or by triggering a chef-client run via a mechanism like Push Jobs. Would either of those workarounds be amenable to you?

**Comment by ericrlarson** [comment]
Neither of these really work for us.  We are also still understanding exactly how big of an issue this really is.

Background: Our implementation is entirely based on Chef –local-mode right now.  Our servers have no access outside of our customer’s network and we have not been able to successfully justify the extended footprint required for a Chef Server onsite.

The problem we are having is rooted in the past.  Chef-client has already been run under a certain user account, that is not a common service account.  In the future it is possible that the user will use a different account to upgrade the server.  In that upgrade they would encounter this issue.  In most cases we anticipate them using the same user account as in the past.

On possible work around would be to have a cleanup script that deletes the nodes folder at the end of a successful chef run so that each chef-client run can re-create it with its own credentials.  That would take care of future releases and we would do manual cleanup this release if it became necessary.

Thoughts?

**Comment by tduffield** [comment]
Are the users executing the chef-client run part of a common group, i.e. Administrators?

**Comment by ericrlarson** [comment]
Yes the users should be part of the Administrators group.  That is a documented requirement in order to have permission to accomplish install and upgrade tasks.

**Comment by ericrlarson** [comment]
@tduffield did you have an idea we might be able to use regarding the Administrators group?

Also there is a new wrinkle that we have discovered.  We have one implementation where chef-client is being run in the context of a service that runs under the local system account.  That execution does not work because when the folder is created the machine is the owner of the folder not the system account, and so the node file cannot be created due to the same permissions problem.
