### ISSUE TITLE
stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by kareed44** [chef/chef#5783]
## Description

I understand that this repo is not for Chef Vault, but I think Chef Vault's usage of the Chef Client libraries is enough to make it relevant here. Anyways...

When running knife vault refresh I get a failure due to **stack level too deep (SystemStackError)**. From what I understand this is caused by too many nested processes. I added some debug code to see just how many levels deep the error was being thrown at. When it fails, **caller.size** reports the process is at 7285. This seems incredibly deep to me and given that I'm not surprised by the error. We thought it might have be correlated to the number of nodes/clients we have, but after culling a few hundred of them the issue persists. We only just started seeing this issue. We have not upgraded recently. 

Thoughts??

## Chef Version

Chef Server 12.7, Chef Client 12.15.19

## Platform Version

Ubuntu 14.04 

## Stacktrace

/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-log-1.7.1/lib/mixlib/log/formatter.rb:45:in `msg2str': stack level too deep (SystemStackError)
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-log-1.7.1/lib/mixlib/log/formatter.rb:36:in `call'
        from /opt/chef/embedded/lib/ruby/2.3.0/logger.rb:546:in `format_message'
        from /opt/chef/embedded/lib/ruby/2.3.0/logger.rb:434:in `add'
        from /opt/chef/embedded/lib/ruby/2.3.0/logger.rb:455:in `debug'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-log-1.7.1/lib/mixlib/log.rb:120:in `block in debug'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-log-1.7.1/lib/mixlib/log.rb:120:in `each'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/mixlib-log-1.7.1/lib/mixlib/log.rb:120:in `debug'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/http/basic_client.rb:75:in `block (2 levels) in request'
         ... 7278 levels...
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/lib/chef/application/knife.rb:156:in `run'
        from /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19/bin/knife:25:in `<top (required)>'
        from /usr/bin/knife:54:in `load'
        from /usr/bin/knife:54:in `<main>'

**Comment by kareed44** [comment]
It happens in this class: https://github.com/chef/chef/blob/master/lib/chef/search/query.rb

The search function works itself into infinite recursion. Basically it thinks the api should return another page but it cant manage to satisfy the condition that signifies the end of the results.

This is result set that gets returned repeatedly: **{"total"=>298, "start"=>297, "rows"=>[]}**

Is this data corruption of some sort? How would I got about resolving this?

**Comment by kareed44** [comment]
Update... a reindex of the search index both fixed this issue and made the refresh alot faster.
