### ISSUE TITLE
FATAL: NoMethodError: undefined method `password' for Chef::Resource::Execute

### ISSUE THREAD

**Issue by sgtcoolguy** [chef/chef#5824]
## Description

I'm attempting to converge a Windows node (from a Mac box, via knife winrm). I'm using the execute resource to attempt to run SET to set an environment variable at the user-level for a specific build user I'm generating. I can pass the user attribute, but it complains I need to also specify a password attribute. When I attempt to add the password attribute, it complains there is no password attribute on Chef::Resource::Execute.

Similar to http://stackoverflow.com/questions/26089766/trying-to-run-execute-and-batch-as-specified-user-on-windows-with-chef?rq=1 or http://stackoverflow.com/questions/40222811/execute-as-another-user-on-windows-with-chef

## Chef Version

Chef 12.18.31 

## Platform Version

Windows 10 (reports as "x64-mingw32")

## Replication Case

```
execute 'SET BOOST_ROOT' do
  command "set BOOST_ROOT=#{boost_path}"
  user node['jenkins-slave']['user']['username']
  password node['jenkins-slave']['user']['password']
  group node['jenkins-slave']['user']['group']
  environment(
    lazy do
       {
        'HOME' => node['jenkins-slave']['user']['home'],
        'USER' => node['jenkins-slave']['user']['username']
       }
    end
  )
end
```

## Client Output

```
wingin02.lab.sfo.axway.int ================================================================================
wingin02.lab.sfo.axway.int Recipe Compile Error in c:/chef/cache/cookbooks/titanium-windows/recipes/default.rb
wingin02.lab.sfo.axway.int ================================================================================
wingin02.lab.sfo.axway.int 
wingin02.lab.sfo.axway.int NoMethodError
wingin02.lab.sfo.axway.int -------------
wingin02.lab.sfo.axway.int undefined method `password' for Chef::Resource::Execute
wingin02.lab.sfo.axway.int 
wingin02.lab.sfo.axway.int Cookbook Trace:
wingin02.lab.sfo.axway.int ---------------
wingin02.lab.sfo.axway.int   c:/chef/cache/cookbooks/titanium-windows/recipes/_boost.rb:23:in `block in from_file'
wingin02.lab.sfo.axway.int   c:/chef/cache/cookbooks/titanium-windows/recipes/_boost.rb:20:in `from_file'
wingin02.lab.sfo.axway.int   c:/chef/cache/cookbooks/titanium-windows/recipes/default.rb:32:in `from_file'
wingin02.lab.sfo.axway.int 
wingin02.lab.sfo.axway.int Relevant File Content:
wingin02.lab.sfo.axway.int ----------------------
wingin02.lab.sfo.axway.int c:/chef/cache/cookbooks/titanium-windows/recipes/_boost.rb:
wingin02.lab.sfo.axway.int 
wingin02.lab.sfo.axway.int  16:  file "#{boost_path}\\SOURCE_URL" do
wingin02.lab.sfo.axway.int  17:    content node[cookbook_name]['boost']['url']
wingin02.lab.sfo.axway.int  18:  end
wingin02.lab.sfo.axway.int  19:  
wingin02.lab.sfo.axway.int  20:  execute 'SET BOOST_ROOT' do
wingin02.lab.sfo.axway.int  21:    command "set BOOST_ROOT=#{boost_path}"
wingin02.lab.sfo.axway.int  22:    user node['jenkins-slave']['user']['username']
wingin02.lab.sfo.axway.int  23>>   password node['jenkins-slave']['user']['password']
wingin02.lab.sfo.axway.int  24:    group node['jenkins-slave']['user']['group']
wingin02.lab.sfo.axway.int  25:    environment(
wingin02.lab.sfo.axway.int  26:      lazy do
wingin02.lab.sfo.axway.int  27:         {
wingin02.lab.sfo.axway.int  28:          'HOME' => node['jenkins-slave']['user']['home'],
wingin02.lab.sfo.axway.int  29:          'USER' => node['jenkins-slave']['user']['username']
wingin02.lab.sfo.axway.int  30:         }
wingin02.lab.sfo.axway.int  31:      end
wingin02.lab.sfo.axway.int 
wingin02.lab.sfo.axway.int  32:    )
wingin02.lab.sfo.axway.int 
wingin02.lab.sfo.axway.int Platform:
wingin02.lab.sfo.axway.int ---------
wingin02.lab.sfo.axway.int x64-mingw32
wingin02.lab.sfo.axway.int 
wingin02.lab.sfo.axway.int [2017-02-17T11:49:01-08:00] ERROR: Running exception handlers
wingin02.lab.sfo.axway.int [2017-02-17T11:49:01-08:00] ERROR: Exception handlers complete
wingin02.lab.sfo.axway.int [2017-02-17T11:49:01-08:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
wingin02.lab.sfo.axway.int [2017-02-17T11:49:01-08:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
wingin02.lab.sfo.axway.int [2017-02-17T11:49:01-08:00] FATAL: NoMethodError: undefined method `password' for Chef::Resource::Execute
ERROR: Failed to execute command on wingin02.lab.sfo.axway.int return code 1
```

## Stacktrace

```
Generated at 2017-02-17 11:49:01 -0800
NoMethodError: undefined method `password' for Chef::Resource::Execute
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/resource.rb:1364:in `method_missing'
c:/chef/cache/cookbooks/titanium-windows/recipes/_boost.rb:23:in `block in from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/resource_builder.rb:76:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/resource_builder.rb:76:in `build'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/dsl/declare_resource.rb:291:in `build_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/dsl/declare_resource.rb:248:in `declare_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/dsl/resources.rb:40:in `execute'
c:/chef/cache/cookbooks/titanium-windows/recipes/_boost.rb:20:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/cookbook_version.rb:233:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/run_context.rb:338:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/run_context.rb:294:in `block in include_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/run_context.rb:293:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/run_context.rb:293:in `include_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
c:/chef/cache/cookbooks/titanium-windows/recipes/default.rb:32:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/cookbook_version.rb:233:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/run_context.rb:338:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:141:in `block in compile_recipes'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/run_context.rb:187:in `load'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/client.rb:511:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/client.rb:281:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/application.rb:277:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/application.rb:253:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/application.rb:236:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:68:in `load'
C:/opscode/chef/bin/chef-client:68:in `<main>'
```

**Comment by sgtcoolguy** [comment]
Apparently this is new behavior introduced since 12.18.31? I found the attribute in the online docs for the execute resource, and assumed it would work. But apparently I need to wait until a chef client for windows has the latest 12.19.* code in it to support this?

**Comment by sgtcoolguy** [comment]
Related: https://discourse.chef.io/t/execute-resource-on-windows-as-alternate-user/8029

**Comment by lamont-granquist** [comment]
pretty certain that is what the "alternative user identity support" patch in 12.19.33 addresses:

https://discourse.chef.io/t/pre-release-announcement-chef-client-12-19/10452

**Comment by smurawski** [comment]
Chef Client 12.19.36 has support for execute resources with alternate user and password.

One thing to note - the account you run Chef under will require the `SE_ASSIGNPRIMARYTOKEN_NAME/SeAssignPrimaryTokenPrivilege` right (via User Rights Assignment), to use this feature.
