### ISSUE TITLE
cron resource fails changing crontab with not-easy to diagnose error 

### ISSUE THREAD

**Issue by iggyzap** [chef/chef#5848]
## Description

If for some reason cron resource generates input that is not acceptable to crontab utility then it's error does not provide neither input it tried to feed to crontab nor crontab error message .

I had to edit /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/provider/cron.rb to add diagnostic message of what cron tried to feed to crontab to be able to find the issue.

It would be nice if cron resource would output data from crontab along with stuff it tried to pass to it.

## Chef Version

chef-client -v
Chef: 11.12.4

## Platform Version

uname -a
Linux ip-172-31-23-224 4.4.41-36.55.amzn1.x86_64 #1 SMP Wed Jan 18 01:03:26 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

## Client Output
```
Chef::Exceptions::Cron
----------------------
Error updating state of wal_e_base_backup, exit: 1

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/wal-e/recipes/default.rb

 63: cron "wal_e_base_backup" do
 64:   user node[:wal_e][:user]
 65:   command "#{node[:wal_e][:envdir_command]} #{node[:wal_e][:env_dir]} /usr/local/bin/wal-e #{node[:wal_e][:base_backup][:params]} backup-push #{node[:wal_e][:base_backup][:options]} #{node[:wal_e][:pgdata_dir]}"
 66:   home node[:wal_e][:base_backup][:cron_job_home]
 67:   not_if { node[:wal_e][:base_backup][:disabled] }
 68: 
 69:   minute node[:wal_e][:base_backup][:minute]
 70:   hour node[:wal_e][:base_backup][:hour]
 71:   day node[:wal_e][:base_backup][:day]
 72:   month node[:wal_e][:base_backup][:month]
 73:   weekday node[:wal_e][:base_backup][:weekday]
 74: end

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/wal-e/recipes/default.rb:63:in `from_file'

cron("wal_e_base_backup") do
  action :create
  retries 0
  retry_delay 2
  guard_interpreter :default
  minute "0/30"
  hour "*"
  day "*"
  month "*"
  weekday "*"
  command "/usr/local/bin/envdir /etc/wal-e /usr/local/bin/wal-e --aws-instance-profile backup-push  /mnt/postgre/data"
  user "postgres"
  home "/var/lib/pgsql93"
  cookbook_name "wal-e"
  recipe_name "default"
  not_if { #code block }
end

[2017-03-01T11:06:46+00:00] INFO: Running queued delayed notifications before re-raising exception
```

## Stacktrace
```
Chef::Exceptions::Cron: cron[wal_e_base_backup] (wal-e::default line 63) had an error: Chef::Exceptions::Cron: Error updating state of wal_e_base_backup, exit: 1
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/provider/cron.rb:219:in `write_crontab'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/provider/cron.rb:149:in `block in action_create'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/mixin/why_run.rb:52:in `call'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/mixin/why_run.rb:52:in `add_action'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/provider.rb:155:in `converge_by'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/provider/cron.rb:148:in `action_create'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/provider.rb:120:in `run_action'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/resource.rb:637:in `run_action'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/runner.rb:49:in `run_action'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/runner.rb:81:in `block (2 levels) in converge'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/runner.rb:81:in `each'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/runner.rb:81:in `block in converge'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/resource_collection.rb:98:in `block in execute_each_resource'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/resource_collection.rb:96:in `execute_each_resource'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/runner.rb:80:in `converge'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/shell/ext.rb:236:in `run_chef'
	from (irb):1
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/shell.rb:74:in `block in start'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/shell.rb:73:in `catch'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/shell.rb:73:in `start'
	from /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/bin/chef-shell:37:in `<top (required)>'
	from /usr/bin/chef-shell:23:in `load'
	from /usr/bin/chef-shell:23:in `<main>'chef > help
```

**Comment by shortdudey123** [comment]
`11.12.4` is almost 3 years old and is pretty much unsupported at this point.
(Also Ruby 1.9.1 was EOL'd over 2 years ago)

That being said, the cron resource really hasn't changed much since `11.10.0` (other than handling special times which you don't appear to be using)
