### ISSUE TITLE
systemd verify fails for socket units

### ISSUE THREAD

**Issue by tpodom** [chef/chef#5909]
## Description

Trying to create a systemd unit for a socket fails because the related service doesn't exist yet.  I believe this is related to commit aea6988.  When I run systemd-analyze manually it outputs "Service rt.service not loaded, rt.socket cannot be started." because the rt.service is created separately.  Is there a different way to create a socket + service?

## Chef Version

12.19.36 CentOS omnibus

## Platform Version

CentOS 7.3

## Replication Case

```
    systemd_unit 'rt.socket' do
      enabled true
      content({
        'Unit' => {
          'Description' => 'Request Tracker Listen Socket'
        },
        'Socket' => {
          'ListenStream' => "0.0.0.0:9001"
        },
        'Install' => {
          'WantedBy' => 'sockets.target'
        }
      })
      action :create
    end

    systemd_unit 'rt.service' do
      enabled true
      content({
        'Unit' => {
          'Description' => 'Request Tracker Webapp',
          'After' => 'network.target',
          'Requires' => 'rt.socket'
        },
        'Service' => {
          'User' => 'rt',
          'Group' => 'rt',
          'StandardOutput' => 'null',
          'StandardError' => 'syslog',
          'ExecStart' => "/usr/local/bin/systemd-spawn-fcgi.sh /usr/local/rt/sbin/rt-server.fcgi -initial-env RT_SITE_CONFIG=/usr/local/rt/etc/RT_SiteConfig.pm",
          'Restart' => 'always'
        },
        'Install' => {
          'WantedBy' => 'multi-user.target'
        }
      })
      action :create
    end
```

## Client Output
```
==> linux:       * file[/etc/systemd/system/rt.socket] action create
==> linux: 
==> linux:         
==> linux:         ================================================================================
==> linux:         Error executing action `create` on resource 'file[/etc/systemd/system/rt.socket]'
==> linux:         ================================================================================
==> linux:         
==> linux:         Chef::Exceptions::ValidationFailed
==> linux:         ----------------------------------
==> linux:         
==> linux: Proposed content for /etc/systemd/system/rt.socket failed verification #<Chef::Resource::File::Verification:0x000000041f5aa0>
==> linux:         
==> linux:         
==> linux: Compiled Resource:
==> linux:         ------------------
==> linux:         # Declared in 
==> linux:         
==> linux:         file("/etc/systemd/system/rt.socket") do
==> linux:           action [:create]
==> linux:         
==> linux:   retries 0
==> linux:           retry_delay 2
==> linux:           default_guard_interpreter :default
==> linux:           content "[Unit]\nDescription = Request Tracker Listen Socket\n\n[Socket]\nListenStream = 0.0.0.0:9001\n\n[Install]\nWantedBy = sockets.target\n"
==> linux:           owner "root"
==> linux:           group "root"
==> linux:           mode "0644"
==> linux: 
==> linux:           path "/etc/systemd/system/rt.socket"
==> linux:           verifications [#<Chef::Resource::File::Verification:0x000000041f5aa0 @command_opts={}, @command=:systemd_unit, @block=nil, @parent_resource=<file[/etc/systemd/system/rt.socket] @name: "/etc/systemd/system/rt.socket" @noop: nil @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :create, :delete, :touch, :create_if_missing] @action: [:create] @updated: false @updated_by_last_action: false @supports: {} @ignore_failure: false @retries: 0 @retry_delay: 2 @source_line: nil @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @sensitive: false @content: "[Unit]\nDescription = Request Tracker Listen Socket\n\n[Socket]\nListenStream = 0.0.0.0:9001\n\n[Install]\nWantedBy = sockets.target\n" @owner: "root" @group: "root" @mode: "0644" @path: "/etc/systemd/system/rt.socket" @verifications: [...]>>]
==> linux:         end
==> linux:         
==> linux: 
==> linux:         Platform:
==> linux:         ---------
==> linux:         x86_64-linux
==> linux:         
==> linux: 
==> linux:       
==> linux:       ================================================================================
==> linux:       Error executing action `create` on resource 'systemd_unit[rt.socket]'
==> linux:       ================================================================================
==> linux:       
==> linux:       Chef::Exceptions::ValidationFailed
==> linux:       ----------------------------------
==> linux:       file[/etc/systemd/system/rt.socket] (dynamically defined) had an error: Chef::Exceptions::ValidationFailed: Proposed content for /etc/systemd/system/rt.socket failed verification #<Chef::Resource::File::Verification:0x000000041f5aa0>
==> linux:       
==> linux:       Resource Declaration:
==> linux:       ---------------------
==> linux:       # In /var/chef/cache/cookbooks/focal/resources/rt_service_systemd.rb
==> linux:       
==> linux:        82:     systemd_unit 'rt.socket' do
==> linux:        83:       enabled true
==> linux:        84:       content({
==> linux:        85:         'Unit' => {
==> linux:        86:           'Description' => 'Request Tracker Listen Socket'
==> linux:        87:         },
==> linux:        88:         'Socket' => {
==> linux:        89:           'ListenStream' => "0.0.0.0:9001"
==> linux:        90:         },
==> linux:        91:         'Install' => {
==> linux:        92:           'WantedBy' => 'sockets.target'
==> linux:        93:         }
==> linux:        94:       })
==> linux:        95:       action :create
==> linux:        96:     end
==> linux:        97: 
==> linux:       
==> linux:       Compiled Resource:
==> linux:       ------------------
==> linux:       # Declared in /var/chef/cache/cookbooks/focal/resources/rt_service_systemd.rb:82:in `create_init'
==> linux:       
==> linux:       systemd_unit("rt.socket") do
==> linux:         action [:create]
==> linux:         retries 0
==> linux:         retry_delay 2
==> linux:         default_guard_interpreter :default
==> linux:         declared_type :systemd_unit
==> linux:         cookbook_name "focal"
==> linux:         enabled true
==> linux:         content {"Unit"=>{"Description"=>"Request Tracker Listen Socket"}, "Socket"=>{"ListenStream"=>"0.0.0.0:9001"}, "Install"=>{"WantedBy"=>"sockets.target"}}
==> linux:       end
==> linux:       
==> linux:       Platform:
==> linux:       ---------
==> linux:       x86_64-linux
==> linux:       
==> linux: 
==> linux: [2017-03-16T12:27:12-04:00] INFO: Running queued delayed notifications before re-raising exception
==> linux:     
==> linux:     ================================================================================
==> linux:     Error executing action `start` on resource 'focal_rt_service_systemd[rt]'
==> linux:     ================================================================================
==> linux:     
==> linux:     Chef::Exceptions::ValidationFailed
==> linux:     ----------------------------------
==> linux:     systemd_unit[rt.socket] (/var/chef/cache/cookbooks/focal/resources/rt_service_systemd.rb line 82) had an error: Chef::Exceptions::ValidationFailed: file[/etc/systemd/system/rt.socket] (dynamically defined) had an error: Chef::Exceptions::ValidationFailed: Proposed content for /etc/systemd/system/rt.socket failed verification #<Chef::Resource::File::Verification:0x000000041f5aa0>
==> linux:     
==> linux:     Resource Declaration:
==> linux:     ---------------------
==> linux:     # In /var/chef/cache/cookbooks/focal/recipes/rt.rb
==> linux:     
==> linux:      59: focal_rt_service 'rt' do
==> linux:      60:   action [:start, :enable]
==> linux:      61: end
==> linux:      62: 
==> linux:     
==> linux:     Compiled Resource:
==> linux:     ------------------
==> linux:     # Declared in /var/chef/cache/cookbooks/focal/recipes/rt.rb:59:in `from_file'
==> linux:     
==> linux:     focal_rt_service_systemd("rt") do
==> linux:       action [:start, :enable]
==> linux:       updated true
==> linux:       updated_by_last_action true
==> linux:       retries 0
==> linux:       retry_delay 2
==> linux:       default_guard_interpreter :default
==> linux:       declared_type :focal_rt_service
==> linux:       cookbook_name "focal"
==> linux:       recipe_name "rt"
==> linux:     end
==> linux:     
==> linux:     Platform:
==> linux:     ---------
==> linux:     x86_64-linux
```

**Comment by nathwill** [comment]
@tpodom any reason not to invert the order and create the service resource before the socket resource? seems like chef is correctly detecting an ordering dependency here.

**Comment by nathwill** [comment]
if you don't have direct access to the ordering, i think the new :before notification may help here, too.

e.g.

```ruby
    systemd_unit 'rt.socket' do
      content({
        'Unit' => {
          'Description' => 'Request Tracker Listen Socket'
        },
        'Socket' => {
          'ListenStream' => "0.0.0.0:9001"
        },
        'Install' => {
          'WantedBy' => 'sockets.target'
        }
      })
      action :create
      notifies :create, 'systemd_unit[rt.service]', :before
    end

    systemd_unit 'rt.service' do
      enabled true
      content({
        'Unit' => {
          'Description' => 'Request Tracker Webapp',
          'After' => 'network.target',
          'Requires' => 'rt.socket'
        },
        'Service' => {
          'User' => 'rt',
          'Group' => 'rt',
          'StandardOutput' => 'null',
          'StandardError' => 'syslog',
          'ExecStart' => "/usr/local/bin/systemd-spawn-fcgi.sh /usr/local/rt/sbin/rt-server.fcgi -initial-env RT_SITE_CONFIG=/usr/local/rt/etc/RT_SiteConfig.pm",
          'Restart' => 'always'
        },
        'Install' => {
          'WantedBy' => 'multi-user.target'
        }
      })
      action :create
    end
```

**Comment by nathwill** [comment]
so for some reason the verifier seems to be running before the notifier, which prevents the use of `notifies :create, 'systemd_unit[rt.service]', :before` in the socket resource, but if the order in the run-list is corrected to reflect the dependency of the socket unit on the service units presence, chef successfully creates both the service and socket units.

```ruby
systemd_unit 'true.service' do
  content({
    'Unit' => {
      'Description' => 'Truth Service',
      'After' => 'network.target'
    },
    'Service' => {
      'ExecStart' => "/usr/bin/true",
      'Restart' => 'always'
    },
    'Install' => {
      'WantedBy' => 'multi-user.target'
    }
  })
  action :create
end

systemd_unit 'true.socket' do
  content({
    'Unit' => {
      'Description' => 'Truth Listen Socket'
    },
    'Socket' => {
      'ListenStream' => "0.0.0.0:9001"
    },
    'Install' => {
      'WantedBy' => 'sockets.target'
    }
  })
  action [:create, :enable, :start]
end
```

**Comment by tpodom** [comment]
@nathwill OK, I removed the Requires=rt.socket from the rt.service and switched the order and that works.  Thanks for your help!
