### ISSUE TITLE
gem feature in metadata.rb cannot install gem depending on chef

### ISSUE THREAD

**Issue by kamaradclimber** [chef/chef#6038]
## Description

When using gem feature in a cookbook metadata.rb, chef-client fails if that gem depends on chef because it tries to install a binary gem (ffi).

## Chef Version

`12.18.31`

## Replication Case

Use:
```
gem 'chef-vault', '= 3.0.0.rc2'
```
in `metadata.rb`

run chef-client.

## Client Output

```
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Resolving dependencies...
Using public_suffix 2.0.5
Using builder 3.2.3
Using bundler 1.12.5
Using fuzzyurl 0.9.0
Using mixlib-config 2.2.4
Using mixlib-shellout 2.2.7
Using libyajl2 1.2.0
Using hashie 3.5.5
Using mixlib-log 1.7.1
Using rack 2.0.1
Using uuidtools 2.1.5
Using diff-lcs 1.3
Using erubis 2.7.0
Using highline 1.7.8
Using iniparse 1.4.2
Using mixlib-cli 1.7.0
Using net-ssh 4.1.0
Installing ffi 1.9.18 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.18/ext/ffi_c
/opt/chef/embedded/bin/ruby -r ./siteconf20170410-26131-eyv5wa.rb extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/chef/embedded/bin/$(RUBY_BASE_NAME)
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/lib
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:467:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:598:in `try_cpp'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:1102:in `block in have_header'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:953:in `block in checking_for'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:952:in `checking_for'
	from /opt/chef/embedded/lib/ruby/2.3.0/mkmf.rb:1101:in `have_header'
	from extconf.rb:16:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /opt/chef/embedded/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/ffi-1.9.18/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/ffi-1.9.18 for inspection.
Results logged to /opt/chef/embedded/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/ffi-1.9.18/gem_make.out
```

**Comment by kamaradclimber** [comment]
From what I've seen so far:
- chef-client generates a Gemfile with `gem(*['chef-vault', '= 3.0.0.rc2'])`
- chef-client runs `bundle install` in a temporary directory
- bundler tries to install ffi  1.9.18 (chef omnibus contains 1.9.14)
- bundler fails because dev tools are not installed.

**Comment by kamaradclimber** [comment]
One possible solution would be to add gem bundled in the omnibus to the generated Gemfile.

**Comment by lamont-granquist** [comment]
the chef dependency of chef-vault was moved to a dev dependency.  this might not seem like strictly correct ruby behavior but we discovered years ago that plugin-like things worked much better this way.

until someone finds a use case where the dependency fundamentally cannot be moved to a dev dependency or where we wind up really needing this for some other reason, i'm going to close it because we're going to continue to argue that moving the chef dep to a dev dependency is the right course of action and will not prioritize fixing this.

best to open a new ticket if and when a show stopper arises where the dev-dependency workaround does not work.

**Comment by ilovemysillybanana** [comment]
I'm not sure I understand. Are you saying that the feature of loading gems in the metadata.rb file is no longer supported/considered best practice? I'm asking because I've run into this issue with a different gem. What does it mean to move something to a dev dependency?

**Comment by coderanger** [comment]
@ilovemysillybanana No, this was a specific circular dependency issue.

**Comment by ilovemysillybanana** [comment]
@coderanger Ah, okay. Sorry about that then. I'll make a separate issue then.
