### ISSUE TITLE
chef 13 yum_package options option broken

### ISSUE THREAD

**Issue by Stromweld** [chef/chef#6046]
## Description

chef-client 13.0.113 when using the yum package resource with options property defined throws an error on unknown method split.

## Chef Version

13.0.113

## Platform Version

CentOS 6.8 running on AWS cloud

## Replication Case

use yum_package with options '--nogpgcheck' defined.

## Client Output

```
Recipe: dse-nativex::datastax
  * yum_package[dse-full] action install

    ================================================================================
    Error executing action `install` on resource 'yum_package[dse-full]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `split' for ["--nogpgcheck"]:Array

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/dse-nativex/recipes/datastax.rb

      9:     package 'dse-full' do
     10:       version node['cassandra']['dse_version']
     11:       options '--nogpgcheck'
     12:       action :install
     13:     end
     14:   else

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/dse-nativex/recipes/datastax.rb:9:in `from_file'

    yum_package("dse-full") do
      package_name "dse-full"
      action [:install]
      default_guard_interpreter :default
      declared_type :package
      cookbook_name "dse-nativex"
      recipe_name "datastax"
      version "4.8.4-1"
      options ["--nogpgcheck"]
    end

    System Info:
    ------------
    chef_version=13.0.113
    platform=centos
    platform_version=6.8
    ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
    program_name=chef-client worker: ppid=25468;start=19:31:40;
    executable=/opt/chef/bin/chef-client


Running handlers:
[2017-04-10T19:32:02-05:00] ERROR: Running exception handlers
Running handlers complete
[2017-04-10T19:32:02-05:00] ERROR: Exception handlers complete
Chef Client failed. 8 resources updated in 21 seconds
[2017-04-10T19:32:02-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2017-04-10T19:32:02-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-04-10T19:32:02-05:00] ERROR: yum_package[dse-full] (dse-nativex::datastax line 9) had an error: NoMethodError: undefined method `split' for ["--nogpgcheck"]:Array
[2017-04-10T19:32:02-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

## Stacktrace

```
Generated at 2017-04-10 19:46:08 -0500
NoMethodError: yum_package[dse-full] (dse-nativex::datastax line 9) had an error: NoMethodError: undefined method `split' for ["--nogpgcheck"]:Array
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/provider/package/yum.rb:197:in `manage_extra_repo_control'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/provider/package/yum.rb:76:in `load_current_resource'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/provider.rb:154:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/resource.rb:591:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/client.rb:714:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/client.rb:709:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/client.rb:709:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/client.rb:748:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/client.rb:286:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application.rb:291:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application.rb:279:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application.rb:279:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application.rb:244:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application.rb:232:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:58:in `load'
/usr/bin/chef-client:58:in `<main>'

>>>> Caused by NoMethodError: undefined method `split' for ["--nogpgcheck"]:Array
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/provider/package/yum.rb:197:in `manage_extra_repo_control'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/provider/package/yum.rb:76:in `load_current_resource'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/provider.rb:154:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/resource.rb:591:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/client.rb:714:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/client.rb:709:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/client.rb:709:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/client.rb:748:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/client.rb:286:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application.rb:291:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application.rb:279:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application.rb:279:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application.rb:244:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application.rb:232:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.113/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:58:in `load'
/usr/bin/chef-client:58:in `<main>'
```

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* Requests for new or alternative functionality should be made to [feedback.chef.io](https://feedback.chef.io/forums/301644-chef-product-feedback/category/110832-chef-client)
* [Chef Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by coderanger** [comment]
Thanks for the report, we'll look in to it as soon as possible. in the immediate term it should fix this issue if you change your recipe to `options ['--nogpgcheck']` however this should definitely be working.
