### ISSUE TITLE
no_lazy_load false yields Chef::Exceptions::FileNotFound on cookbook_file/remote_directory resources

### ISSUE THREAD

**Issue by natewalck** [chef/chef#6051]
## Description

Using `no_lazy_load false` causes cookbook_file/remote_directory resources to fail on Chef 13.

## Chef Version

```
chef-client --version
Chef: 13.0.113
```
## Platform Version

macOS 10.12.4

## Replication Case

1. Edit `/etc/chef/client.rb` and set `no_lazy_load false`
2. Run a cookbook thats uses a remote_directory resource. For instance:
```
# Cookbook: default.rb
rd = remote_directory '/tmp/rd_test' do
  source 'some/folder'
  owner 'root'
  group 0
  mode 0755
  purge true
  recursive true
  action :nothing
end

rd.run_action(:create)
```

## Client Output
```
Recipe: rd_test::default
  * remote_directory[/tmp/rd_test] action create

    ================================================================================
    Error executing action `create` on resource 'remote_directory[/tmp/rd_test]'
    ================================================================================

    Chef::Exceptions::FileNotFound
    ------------------------------
    cookbook rd_test has no directory files/default/some/folder

    Cookbook Trace:
    ---------------
    /etc/chef/local-mode-cache/cache/cookbooks/rd_test/recipes/default.rb:11:in `from_file'

    Resource Declaration:
    ---------------------
    # In /etc/chef/local-mode-cache/cache/cookbooks/rd_test/recipes/default.rb

      1: rd = remote_directory '/tmp/rd_test' do
      2:   source 'some/folder'
      3:   owner 'root'
      4:   group 0
      5:   mode 0755
      6:   purge true
      7:   recursive true
      8:   action :nothing
      9: end
     10:

    Compiled Resource:
    ------------------
    # Declared in /etc/chef/local-mode-cache/cache/cookbooks/rd_test/recipes/default.rb:1:in `from_file'

    remote_directory("/tmp/rd_test") do
      action [:nothing]
      default_guard_interpreter :default
      path "/tmp/rd_test"
      recursive true
      source "some/folder"
      purge true
      files_backup 5
      files_owner nil
      files_group nil
      files_mode 420
      overwrite true
      declared_type :remote_directory
      cookbook_name "rd_test"
      recipe_name "default"
      owner "root"
      group 0
      mode "0755"
    end

    System Info:
    ------------
    chef_version=13.0.113
    platform=mac_os_x
    platform_version=10.12.4
    ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin14]
    program_name=chef-client worker: ppid=48297;start=12:43:12;
    executable=/opt/chef/embedded/bin/chef-client


  ================================================================================
  Recipe Compile Error in /etc/chef/local-mode-cache/cache/cookbooks/rd_test/recipes/default.rb
  ================================================================================

  Chef::Exceptions::FileNotFound
  ------------------------------
  remote_directory[/tmp/rd_test] (rd_test::default line 1) had an error: Chef::Exceptions::FileNotFound: cookbook rd_test has no directory files/default/some/folder

  Cookbook Trace:
  ---------------
    /etc/chef/local-mode-cache/cache/cookbooks/rd_test/recipes/default.rb:11:in `from_file'

  Relevant File Content:
  ----------------------
  /etc/chef/local-mode-cache/cache/cookbooks/rd_test/recipes/default.rb:

    4:    group 0
    5:    mode 0755
    6:    purge true
    7:    recursive true
    8:    action :nothing
    9:  end
   10:
   11>> rd.run_action(:create)
   12:

  System Info:
  ------------
  chef_version=13.0.113
  platform=mac_os_x
  platform_version=10.12.4
  ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin14]
  program_name=chef-client worker: ppid=48297;start=12:43:12;
  executable=/opt/chef/embedded/bin/chef-client
```

## Stacktrace

https://gist.github.com/natewalck/c20efd4da2ce0566d542785ebe436233

**Comment by natewalck** [comment]
This may be of particular interest to @jaymzh

**Comment by jaymzh** [comment]
@lamont-granquist - this looks like a pretty bad regression.

Also, I should have requested we flip this default in 13... damn.

**Comment by coderanger** [comment]
@jaymzh it is bad but tempered by the fact that almost no one changes this flag (all my cookbooks explode without it so I can vaguely gauge usage based on how many of those big reports I get :)

**Comment by lamont-granquist** [comment]
yeah except @jaymzh uses it a ton.  it is just a 13.0 regression we need to fix...   we should probably see about adding a chef-zero integration test to the specs around it when we do so it doesn't fail without blowing up any unit tests again...

**Comment by thommay** [comment]
Yeah, I'm working my way through this one at the moment. Integration tests are definitely on the radar!
