### ISSUE TITLE
powershell_out broken on chef 13/server 2016

### ISSUE THREAD

**Issue by mwrock** [chef/chef#6082]
Testing the chocolatey cookbook and noticed I was receiving:

```
=============================================================
      Error executing action `run` on resource 'powershell_script[Install Chocolatey]'                                                                                     
           ===================================================================                                                                                        
           ArgumentError                                                                
           -------------                                                                
           wrong number of arguments (given 0, expected 1)                              
```
Looks like any call to `powershell_out!` is raising this:. For instance `powershell_out!("write-host 'yo'")` yields the same error. The call works fine on 2012R2. The full stack trace is:

```
Generated at 2017-04-23 01:12:54 +0000
ArgumentError: powershell_script[Install Chocolatey] (chocolatey::default line 35) had an error: ArgumentError: wrong number of arguments (given 0, expected 1)
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chocolatey/libraries/helpers.rb:34:in `env_path'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/mixin/shell_out.rb:112:in `shell_out'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/mixin/powershell_out.rb:67:in `block in run_command_with_os_architecture'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/mixin/windows_architecture_helper.rb:67:in `with_os_architecture'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/mixin/powershell_out.rb:66:in `run_command_with_os_architecture'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/mixin/powershell_out.rb:37:in `powershell_out'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/mixin/powershell_out.rb:47:in `powershell_out!'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chocolatey/libraries/helpers.rb:49:in `env_var'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chocolatey/libraries/helpers.rb:45:in `machine_env_var'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chocolatey/libraries/helpers.rb:9:in `block in chocolatey_install'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chocolatey/libraries/helpers.rb:9:in `fetch'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chocolatey/libraries/helpers.rb:9:in `chocolatey_install'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chocolatey/libraries/helpers.rb:26:in `chocolatey_installed?'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chocolatey/recipes/default.rb:39:in `block (2 levels) in from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource/conditional.rb:106:in `evaluate_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource/conditional.rb:95:in `evaluate'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource/conditional.rb:88:in `continue?'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource.rb:1435:in `block in should_skip?'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource.rb:1434:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource.rb:1434:in `find'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource.rb:1434:in `should_skip?'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource.rb:590:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/runner.rb:70:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/runner.rb:98:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/runner.rb:98:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/runner.rb:98:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/runner.rb:97:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/client.rb:715:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/client.rb:710:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/client.rb:710:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/client.rb:749:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/client.rb:286:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/application.rb:273:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/application.rb:249:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/application.rb:232:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:69:in `load'
C:/opscode/chef/bin/chef-client:69:in `<main>'

>>>> Caused by ArgumentError: wrong number of arguments (given 0, expected 1)
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chocolatey/libraries/helpers.rb:34:in `env_path'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/mixin/shell_out.rb:112:in `shell_out'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/mixin/powershell_out.rb:67:in `block in run_command_with_os_architecture'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/mixin/windows_architecture_helper.rb:67:in `with_os_architecture'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/mixin/powershell_out.rb:66:in `run_command_with_os_architecture'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/mixin/powershell_out.rb:37:in `powershell_out'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/mixin/powershell_out.rb:47:in `powershell_out!'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chocolatey/libraries/helpers.rb:49:in `env_var'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chocolatey/libraries/helpers.rb:45:in `machine_env_var'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chocolatey/libraries/helpers.rb:9:in `block in chocolatey_install'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chocolatey/libraries/helpers.rb:9:in `fetch'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chocolatey/libraries/helpers.rb:9:in `chocolatey_install'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chocolatey/libraries/helpers.rb:26:in `chocolatey_installed?'
C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chocolatey/recipes/default.rb:39:in `block (2 levels) in from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource/conditional.rb:106:in `evaluate_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource/conditional.rb:95:in `evaluate'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource/conditional.rb:88:in `continue?'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource.rb:1435:in `block in should_skip?'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource.rb:1434:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource.rb:1434:in `find'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource.rb:1434:in `should_skip?'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource.rb:590:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/runner.rb:70:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/runner.rb:98:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/runner.rb:98:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/runner.rb:98:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/runner.rb:97:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/client.rb:715:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/client.rb:710:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/client.rb:710:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/client.rb:749:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/client.rb:286:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/application.rb:273:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/application.rb:249:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/application.rb:232:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.5-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:69:in `load'
C:/opscode/chef/bin/chef-client:69:in `<main>'
```

Will try to dig deeper later

**Comment by mwrock** [comment]
Also works on last version of chef 12 and broken on chef 13 stable and current (13.1.5).

**Comment by mwrock** [comment]
Nevermind. Has nothing to do with powershell out. Method name conflict with chef 13 on the chocolatey side.
