### ISSUE TITLE
chef 13.0.118 windows_task day validation error

### ISSUE THREAD

**Issue by Stromweld** [chef/chef#6104]
## Description

windows_task day validator only accepts weekly frequency when it is also required for :monthly frequency. https://github.com/chef/chef/blob/master/lib/chef/resource/windows_task.rb#L165

## Chef Version

13.0.118

## Platform Version

Windows Server 2012 R2 running on AWS cloud

## Replication Case

Use windows_task resource to create a monthly task that runs on a specific day of the month. We use it to run patches on the third tuesday of every month. See https://supermarket.chef.io/cookbooks/autopatch_ii which is all setup to do that. 

## Client Output

The relevant output of the chef-client run or a link to a gist of the entire run, if there is one.

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it.

## Stacktrace

```
Generated at 2017-04-28 14:47:15 -0500
RuntimeError: day attribute is only valid for tasks that run weekly
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/resource/windows_task.rb:165:in `validate_create_day'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/resource/windows_task.rb:89:in `after_created'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/resource_builder.rb:73:in `build'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/dsl/declare_resource.rb:285:in `build_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/dsl/declare_resource.rb:242:in `declare_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/dsl/resources.rb:38:in `windows_task'
C:/chef/cache/cookbooks/autopatch_ii/recipes/windows.rb:27:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/cookbook_version.rb:205:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/run_context.rb:338:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/run_context.rb:294:in `block in include_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/run_context.rb:293:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/run_context.rb:293:in `include_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
C:/chef/cache/cookbooks/autopatch_ii/recipes/default.rb:25:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/cookbook_version.rb:205:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/run_context.rb:338:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/run_context.rb:294:in `block in include_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/run_context.rb:293:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/run_context.rb:293:in `include_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
C:/chef/cache/cookbooks/role-base-windows-onpremise-nativex/recipes/default.rb:60:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/cookbook_version.rb:205:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/run_context.rb:338:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:163:in `block in compile_recipes'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:160:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:160:in `compile_recipes'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:77:in `compile'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/run_context.rb:187:in `load'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/client.rb:513:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/client.rb:281:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application.rb:273:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application.rb:249:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application.rb:232:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:69:in `load'
C:/opscode/chef/bin/chef-client:69:in `<main>'
```
```

  ================================================================================
  Recipe Compile Error in C:/chef/cache/cookbooks/role-base-windows-onpremise-nativex/recipes/default.rb
  ================================================================================

  RuntimeError
  ------------
  day attribute is only valid for tasks that run weekly

  System Info:
  ------------
  chef_version=13.0.118
  platform=windows
  platform_version=6.3.9600
  ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
  program_name=C:/opscode/chef/bin/chef-client
  executable=C:/opscode/chef/bin/chef-client


  Running handlers:
[2017-04-28T14:47:14-05:00] ERROR: Running exception handlers
  Running handlers complete
[2017-04-28T14:47:14-05:00] ERROR: Exception handlers complete
  Chef Client failed. 1 resources updated in 20 seconds
[2017-04-28T14:47:15-05:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
[2017-04-28T14:47:15-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-04-28T14:47:15-05:00] FATAL: RuntimeError: day attribute is only valid for tasks that run weekly
```

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* Requests for new or alternative functionality should be made to [feedback.chef.io](https://feedback.chef.io/forums/301644-chef-product-feedback/category/110832-chef-client)
* [Chef Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by suchakra** [comment]
When does the fix become available?

**Comment by tas50** [comment]
@suchakra This has shipped. You can pick up any new release of Chef.
