### ISSUE TITLE
default_attribute_blacklist throws 'ERROR: Node attributes are read-only'

### ISSUE THREAD

**Issue by szymonpk** [chef/chef#6120]
## Description

When I'm trying to use [default_attribute_blacklist feature](https://docs.chef.io/attributes.html#blacklist-attributes). I'm getting `ERROR: Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like node.default["key"] = "value"'`

I have not found similar issue report.

## Chef Version

13.0.118, chef.io hosted server

## Platform Version

Ubuntu 16.04

## Replication Case

[I've created small cookbook](https://github.com/szymonpk/blacklist_attributes_issue) which can be run with `kitchen converge`.

## Client Output

    Starting Chef Client, version 13.0.118
    resolving cookbooks for run list: ["blacklist_attributes_issue::default"]
    Synchronizing Cookbooks:
     - blacklist_attributes_issue (0.1.0)
    Installing Cookbook Gems:
    Compiling Cookbooks...
    Converging 0 resources
    [2017-05-04T12:29:13+00:00] WARN: Removing item foo/bar
    [2017-05-04T12:29:13+00:00] WARN: Removing item foo/bar

    Running handlers:
    [2017-05-04T12:29:13+00:00] ERROR: Running exception handlers
    [2017-05-04T12:29:13+00:00] ERROR: Running exception handlers
    Running handlers complete
    [2017-05-04T12:29:13+00:00] ERROR: Exception handlers complete
    [2017-05-04T12:29:13+00:00] ERROR: Exception handlers complete
    Chef Client failed. 0 resources updated in 01 seconds
    [2017-05-04T12:29:13+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
    [2017-05-04T12:29:13+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
    [2017-05-04T12:29:13+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    [2017-05-04T12:29:13+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    [2017-05-04T12:29:13+00:00] ERROR: Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like `node.default["key"] = "value"'
    [2017-05-04T12:29:13+00:00] ERROR: Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like `node.default["key"] = "value"'
    [2017-05-04T12:29:13+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
    [2017-05-04T12:29:13+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

## Stacktrace

    Generated at 2017-05-04 12:29:13 +0000
    Chef::Exceptions::ImmutableAttributeModification: Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like `node.default["key"] = "value"'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/node/mixin/immutablize_hash.rb:48:in `block (2 levels) in <module:ImmutablizeHash>'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/blacklist.rb:60:in `remove_data'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/blacklist.rb:35:in `block in filter'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/blacklist.rb:33:in `each'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/blacklist.rb:33:in `filter'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/node.rb:671:in `block in data_for_save'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/node.rb:659:in `each'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/node.rb:659:in `data_for_save'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/node.rb:596:in `save'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/client.rb:590:in `save_updated_node'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/client.rb:752:in `converge_and_save'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/client.rb:286:in `run'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:291:in `block in fork_chef_client'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:279:in `fork'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:279:in `fork_chef_client'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:244:in `block in run_chef_client'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/local_mode.rb:44:in `with_server_connectivity'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:232:in `run_chef_client'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:450:in `loop'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:450:in `interval_run_chef_client'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:434:in `run_application'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:59:in `run'
    /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/bin/chef-client:26:in `<top (required)>'
    /opt/chef/bin/chef-client:58:in `load'
    /opt/chef/bin/chef-client:58:in `<main>'

**Comment by sean-horn** [comment]
I have an identical repro for this on Chef Client 14.7.17 with a customer and 13.8.5.

Both versions above behave the same in my test environment.

It seems to affect all attribute blacklisting levels but automate.

With the blacklist like this in client.rb

```
automatic_attribute_blacklist ['filesystem/by_mountpoint/', 'filesystem/by_pair/']
override_attribute_blacklist ['seans_override']
```

I get this in the debug/trace output for 13.8.5 and 14.7.17

```
[2019-04-13T15:09:26-04:00] INFO: Blacklisting override node attributes for save
[2019-04-13T15:09:26-04:00] WARN: Removing item seans_override
[2019-04-13T15:09:26-04:00] DEBUG: Re-raising exception: Chef::Exceptions::ImmutableAttributeModification - Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like `node.default["key"] = "value"'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/node/mixin/immutablize_hash.rb:48:in `block (2 levels) in <module:ImmutablizeHash>'
  /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/blacklist.rb:60:in `remove_data'
```

14.7.17

```
[2019-04-13T15:11:48-04:00] DEBUG: Saving the current state of node runner-1-432.lxc
[2019-04-13T15:11:48-04:00] INFO: Blacklisting automatic node attributes for save
[2019-04-13T15:11:48-04:00] WARN: Removing item filesystem/by_mountpoint/
[2019-04-13T15:11:48-04:00] WARN: Removing item filesystem/by_pair/
[2019-04-13T15:11:48-04:00] INFO: Blacklisting override node attributes for save
[2019-04-13T15:11:48-04:00] WARN: Removing item seans_override
[2019-04-13T15:11:48-04:00] TRACE: Re-raising exception: Chef::Exceptions::ImmutableAttributeModification - Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like `node.default["key"] = "value"'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/node/mixin/immutablize_hash.rb:156:in `block (2 levels) in <module:ImmutablizeHash>'
  /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17/lib/chef/blacklist.rb:60:in `remove_data'
```

**Comment by lamont-granquist** [comment]
https://github.com/chef/chef/blob/master/lib/chef/node.rb#L481-L535

`Chef::Node#to_hash`, `Chef::Node#for_json` and `Chef::Node#display_hash` all need to call `#to_hash` on the combined_default/combined_overrides/normal/automatic levels in order to convert those values to actual hashes.

**Comment by lamont-granquist** [comment]
the differences between all of those APIs also seems incredibly poor and I don't quite understand why we have three different ways of converting a node to a hash-like thing (although display_hash makes some sense, but it looks like that has not been updated for policyfile information).

**Comment by sean-horn** [comment]
Tested the #8396 patch on Chef Client 14.7.17. Confirmed working for automatic, override, and default level attributes. Thanks!
