### ISSUE TITLE
Chomp errors when using Chocolatey provider

### ISSUE THREAD

**Issue by TonyChengCME** [chef/chef#6165]
## Description

When I attempt to install a Chocolatey package using the Chef::Provider::Package::Chocolatey provider, I am getting a "undefined method `chomp' for nil:NilClass" error during my attempt to converge.  I upgraded the client to 12.16.64 and was able to execute the recipe locally.

## Chef Version

Initially started at 12.12.15 and upgraded to 12.16.64

## Platform Version

Windows Server 2012 R2

## Replication Case

When I attempt to install a Chocolatey package using the Chef::Provider::Package::Chocolatey provider in client version 12.12.15,  I am getting a `undefined method 'chomp' for nil:NilClass` error during my attempt to converge.  I upgraded the client to 12.16.64 and was able to successfully execute the recipe locally (i.e., "chef-client -z").  I then ran a “choco uninstall java-platform-se-8" and added the JRE installation cookbook to the node’s run_list.  When I execute the chef-client.bat afterwards, it generated the `FATAL: NoMethodError: undefined method 'failed' for nil:NilClass` error again.

## Client Output
```
Recipe: cme_etpawin_javajre::install_javajre
  * chocolatey_package[java-platform-se-8] action install[2017-05-15T15:15:57-05:00] INFO: Processing chocolatey_package
[java-platform-se-8] action install (cme_etpawin_javajre::install_javajre line 1)
 
 
    ================================================================================
    Error executing action `install` on resource 'chocolatey_package[java-platform-se-8]'
    ================================================================================
 
    NoMethodError
    -------------
    undefined method `chomp' for nil:NilClass
 
    Resource Declaration:
    ---------------------
    # In C:/chef/cache/cookbooks/cme_etpawin_javajre/recipes/install_javajre.rb
 
      1: chocolatey_package 'java-platform-se-8' do
      2:   provider                   Chef::Provider::Package::Chocolatey
      3:   version                    '8.0.1210.13'
      4:   action                     :install # defaults to :install if not specified
      5: end
 
    Compiled Resource:
    ------------------
    # Declared in C:/chef/cache/cookbooks/cme_etpawin_javajre/recipes/install_javajre.rb:1:in `from_file'
 
    chocolatey_package("java-platform-se-8") do
      package_name ["java-platform-se-8"]
      provider Chef::Provider::Package::Chocolatey
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :chocolatey_package
      cookbook_name "cme_etpawin_javajre"
      recipe_name "install_javajre"
      version ["8.0.1210.13"]
    end
 
    Platform:
    ---------
    x64-mingw32
 
[2017-05-15T15:16:03-05:00] INFO: Running queued delayed notifications before re-raising exception
 
Running handlers:
[2017-05-15T15:16:03-05:00] ERROR: Running exception handlers
Running handlers complete
[2017-05-15T15:16:03-05:00] ERROR: Exception handlers complete
Chef Client failed. 4 resources updated in 49 seconds
[2017-05-15T15:16:03-05:00] INFO: Sending resource update report (run-id: 3a6c2087-f655-45f8-aa09-277f4026df8f)
[2017-05-15T15:16:03-05:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
[2017-05-15T15:16:03-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-05-15T15:16:03-05:00] FATAL: NoMethodError: undefined method `failed' for nil:NilClass
Did you mean?  fail
```

## Stacktrace

```
Generated at 2017-05-15 15:16:03 -0500
NoMethodError: undefined method `failed' for nil:NilClass
Did you mean?  fail
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/data_collector.rb:210:in `resource_failed'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/event_dispatch/dispatcher.rb:43:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/event_dispatch/dispatcher.rb:43:in `block in call_subscribers'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/event_dispatch/dispatcher.rb:34:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/event_dispatch/dispatcher.rb:34:in `call_subscribers'
(eval):2:in `resource_failed'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource.rb:634:in `rescue in run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource.rb:620:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/runner.rb:69:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/runner.rb:97:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/runner.rb:96:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/client.rb:669:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/client.rb:664:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/client.rb:664:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/client.rb:703:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/client.rb:283:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application.rb:276:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application.rb:252:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application.rb:235:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:65:in `load'
C:/opscode/chef/bin/chef-client:65:in `<main>'

>>>> Caused by NoMethodError: undefined method `chomp' for nil:NilClass
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/provider/package/chocolatey.rb:259:in `block in parse_list_output'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/provider/package/chocolatey.rb:256:in `each_line'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/provider/package/chocolatey.rb:256:in `parse_list_output'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/provider/package/chocolatey.rb:246:in `installed_packages'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/provider/package/chocolatey.rb:191:in `block in build_current_versions'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/provider/package/chocolatey.rb:190:in `map'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/provider/package/chocolatey.rb:190:in `build_current_versions'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/provider/package/chocolatey.rb:48:in `load_current_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/provider.rb:128:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource.rb:622:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/runner.rb:69:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/runner.rb:97:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/runner.rb:97:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/runner.rb:97:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/2.3.0/forwardable.rb:189:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/runner.rb:96:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/client.rb:669:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/client.rb:664:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/client.rb:664:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/client.rb:703:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/client.rb:283:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application.rb:276:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application.rb:252:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application.rb:235:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:65:in `load'
C:/opscode/chef/bin/chef-client:65:in `<main>'
```

**Comment by piyushawasthi** [comment]
@TonyChengCME - I am not able to find "java-platform-se-8" package anywhere. When I was run the recipe for 'java-platform-se-8' it's give me error `No candidate version available for java-platform-se-8`. That's mean 'java-platform-se-8' package is not available in chocolatey. (`https://chocolatey.org/packages?q=java-platform-se-8`)

**So I have tried with following packages and these are working for me.**

1: jre8 (Java SE Runtime Environment 8.0.131)
2: jdk8	(Java SE 8.0.131)
3: javaruntime (Java Runtime (JRE) 8.0.121)
4: javaruntime-platformspecific (Deprecated Java Runtime (JRE) 7.0.79.20161125)

## Chef Version

12.12.15

## Platform Version

Windows Server 2012 R2

Also I have not found chef client stable version 12.16.64, So I have upgraded the client to 12.19.36 and run all above recipe successfully. Also I have tried to un-install all above packages and re-run all recipes for the same again all works for me.

**So here is my suggestion -** 
1: Choose stable client (12.12.15 or 12.19.36) (https://downloads.chef.io/chef)
2: Re-verify the chocolatey package "java-platform-se-8" (https://chocolatey.org/packages?q=java-platform-se-8)

Example Recipe:

```
chocolatey_package 'jre8' do
        provider Chef::Provider::Package::Chocolatey
        action :install # defaults to :install if not specified
end
```
![chef-issue-6165](https://cloud.githubusercontent.com/assets/6093252/26825849/36c00da8-4ad4-11e7-9264-99e86e1cee58.png)

**Comment by TonyChengCME** [comment]
@piyushawasthi :  Thank you for the feedback.  The Java package is internally created and hosted within our own NuGet repository.  The error we are receiving has been analyzed by Chef and is now being tracked as a product defect via Chef support case #15161.  It is currently in the development queue for remediation.

**Comment by btm** [comment]
@TonyChengCME what does `choco list -l -r` return on a machine that has your `java-platform-se-8` package installed?

**Comment by NimishaS** [comment]
@TonyChengCME , @piyushawasthi is working on issue #15161.  Seems like the error is being raised from here: https://github.com/chef/chef/blob/master/lib/chef/data_collector.rb#L212. This is raised when the resource fails for a particular action.
@TonyChengCME , apart from what @btm asked, can you please provide us some more inputs:
1. Is there anyway to share the Java package that is hosted in your NuGet repository? The `chocolatey_package` resource seems to be working for all the java packages available that @piyushawasthi tried.
2. `chef-client` version `12.16.64` isn't available. Can you please confirm if it's the correct version?

**Comment by TonyChengCME** [comment]
Sharad,

My apologies, the client version is actually Chef 12.16.42.  Also, I have attached the Chocolatey package to the Zendesk case.

Sincerely,

Anthony Cheng
CME Group
20 South Wacker Drive
Chicago, IL 60606
W:  312-930-3228
C:  312-504-8720

**Comment by piyushawasthi** [comment]
@TonyChengCME : I fixed the chomp error in https://github.com/chef/chef/pull/6207. Will you please send me output of  `choco source list`.

**Comment by TonyChengCME** [comment]
Piyush,

Here is the output from “choco source list” (with content sanitized):

internalrepository - https://someserver/nexus/service/local/nuget/installe
rs-nuget/ | Priority 0|Bypass Proxy - False|Self-Service - False.
chocolatey.licensed - https://licensedpackages.chocolatey.org/api/v2/ (Authentic
ated)| Priority 10|Bypass Proxy - False|Self-Service - False.
You have 14 days left in your trial period. Purchase licensing
as soon as possible to prevent loss of features. Contact
sales@realdimensions.net

BTW, we are now running version 0.10.6.1 of the Chocolatey client.

Sincerely,

Anthony Cheng
CME Group
20 South Wacker Drive
Chicago, IL 60606
W:  312-930-3228
C:  312-504-8720

**Comment by ferventcoder** [comment]
@TonyChengCME can you run `choco list -r` and provide the output again? Does that trial message show up?

**Comment by ferventcoder** [comment]
Fixed the command.

**Comment by TonyChengCME** [comment]
Rob,

Here’s the output:

[cid:image001.png@01D2E143.2F8E2970]

Here’s the text output:

C:\>choco list -r
chocolatey.extension|1.9.8
chocolatey-agent|0.6.0
anaconda2|4.4.0.0
anaconda3|4.4.0.0
apache-tomcat|9.0.0.0
chocolatey|0.10.6.1
CMED.DataServices|11.3.2.8275
ibm-websphere-mq|8.0.0.6
java-platform-se-8|8.0.1310.11
MATLAB-Runtime|9.2.0.534563
microsoft-odbc-driver-13-for-sql-server|13.0.811.168
microsoft-visual-cplusplus-2017-redistributable|14.10.25017.0
r-for-windows|3.4.0.22570
YamlDotNet|4.1.0

Please let me know if you have any questions or concerns.

Sincerely,

Anthony Cheng
CME Group
20 South Wacker Drive
Chicago, IL 60606
W:  312-930-3228
C:  312-504-8720

**Comment by ferventcoder** [comment]
@TonyChengCME nothing there looks incorrect at all.

All have versions and no other output. I wonder if there is a space that is not being chomped or something.

**Comment by ferventcoder** [comment]
s/space/empty line

**Comment by btm** [comment]
Fixed in https://github.com/chef/chef/pull/6207, in builds v13.2.13+

**Comment by TonyChengCME** [comment]
When is the anticipated release date for v13.2.13 (or higher)?

**Comment by btm** [comment]
@TonyChengCME it will be in current as soon as the pipeline is fixed. Within a couple of days. The 13.2 stable release is targeting the first Monday of July, so 7/3.
