### ISSUE TITLE
chef vagrant up (with chef-solo) error with remote_file

### ISSUE THREAD

**Issue by huamichaelchen** [chef/chef#6267]
## Description

The issue occurs when I setup a mirror for our Nexus Pro, then when I tried to do a vagrant up using the mirror as the artifactory URL, it failed with the message of: 

An existing connection was forcibly closed by the remote host.

## Chef Version
$ chef -v
Chef Development Kit Version: 0.16.28
chef-client version: 12.12.15
delivery version: master (921828facad8a8bbbd767368bfc72f19bd30e7bd)
berks version: 4.3.5
kitchen version: 1.10.2

## Vagrant Version
$ vagrant -v
Vagrant 1.8.1

## VirtualBox Version
$ VBoxManage.exe -v
5.0.28r111378

## Platform Version
Windows Enterprise 8.1

## Stacktrace
You'd see FQDN is because that's replaced intentionally 

[chef-output.txt](https://github.com/chef/chef/files/1142866/chef-output.txt)

**Comment by coderanger** [comment]
The actual error so people don't have to download the file

```
==> default: [2017-07-12T09:25:25-07:00] DEBUG: Chef::HTTP::StreamHandler calling Chef::HTTP::Decompressor::NoopInflater#handle_chunk
==> default:
==> default:
==> default:     ================================================================================
==> default:     Error executing action `create` on resource 'remote_file[C:\chef\cache/jdk-8u101-windows-x64.exe]'
==> default:     ================================================================================
==> default:
==> default:     Errno::ECONNRESET
==> default:     -----------------
==> default:     Error connecting to http://FQDN:8081/repository/ARTIFACT_NAME-Nexus-Pro/ARTIFACT_NAME/java/8u101/jdk-8u101-windows-x64.exe - An existing connection was forcibly closed by the remote host.
==> default:
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In C:\vagrant-chef\397b79e3e4161394a76ff8ee6d9f6895\cookbooks\java\recipes\windows.rb
==> default:
==> default:      45:   remote_file cache_file_path do
==> default:      46:     checksum pkg_checksum if pkg_checksum
==> default:      47:     source node['java']['windows']['url']
==> default:      48:     backup false
==> default:      49:     action :create
==> default:      50:   end
==> default:      51: end
==> default:
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in C:\vagrant-chef\397b79e3e4161394a76ff8ee6d9f6895\cookbooks\java\recipes\windows.rb:45:in `from_file'
==> default:
==> default:     remote_file("C:\chef\cache/jdk-8u101-windows-x64.exe") do
==> default:       provider Chef::Provider::RemoteFile
==> default:       action [:create]
==> default:       retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :default
==> default:       source ["http://FQDN:8081/repository/ARTIFACT_NAME-Nexus-Pro/ARTIFACT_NAME/java/8u101/jdk-8u101-windows-x64.exe"]
==> default:       use_etag true
==> default:       use_last_modified true
==> default:       declared_type :remote_file
==> default:       cookbook_name :java
==> default:
==> default:       recipe_name "windows"
==> default:       atomic_update true
==> default:       path "C:\\chef\\cache/jdk-8u101-windows-x64.exe"
==> default:     end
==> default:
==> default: [2017-07-12T09:25:25-07:00] INFO: Running queued delayed notifications before re-raising exception
==> default: [2017-07-12T09:25:25-07:00] DEBUG: Re-raising exception: Errno::ECONNRESET - remote_file[C:\chef\cache/jdk-8u101-windows-x64.exe] (java::windows line 45) had an error: Errno::ECONNRESET: Error connecting to http://FQDN:8081/repository/ARTIFACT_NAME-Nexus-Pro/ARTIFACT_NAME/java/8u101/jdk-8u101-windows-x64.exe - An existing connection was forcibly closed by the remote host.
==> default: C:/opscode/chef/embedded/lib/ruby/2.0.0/net/protocol.rb:153:in `read_nonblock'
==> default:   C:/opscode/chef/embedded/lib/ruby/2.0.0/net/protocol.rb:153:in `rbuf_fill'
==> default:   C:/opscode/chef/embedded/lib/ruby/2.0.0/net/protocol.rb:104:in `read'
==> default:   C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http/response.rb:284:in `block in read_body_0'
==> default:   C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http/response.rb:250:in `inflater'
==> default:   C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http/response.rb:274:in `read_body_0'
==> default:   C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http/response.rb:201:in `read_body'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/http.rb:406:in `stream_to_tempfile'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/http.rb:175:in `block in streaming_request'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/http/basic_client.rb:88:in `block in request'
==> default:   C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http.rb:1419:in `block (2 levels) in transport_request'
==> default:   C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http/response.rb:162:in `reading_body'
==> default:   C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http.rb:1418:in `block in transport_request'
==> default:   C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http.rb:1409:in `catch'
==> default:   C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http.rb:1409:in `transport_request'
==> default:   C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http.rb:1382:in `request'
==> default:   C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http.rb:1375:in `block in request'
==> default:   C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http.rb:852:in `start'
==> default:   C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http.rb:1373:in `request'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/http/basic_client.rb:65:in `request'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/http.rb:275:in `block in send_http_request'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/http.rb:308:in `block in retrying_http_errors'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/http.rb:306:in `loop'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/http.rb:306:in `retrying_http_errors'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/http.rb:271:in `send_http_request'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/http.rb:173:in `streaming_request'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/remote_file/http.rb:60:in `fetch'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/remote_file/content.rb:71:in `grab_file_from_uri'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/remote_file/content.rb:56:in `try_multiple_sources'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/remote_file/content.rb:41:in `file_for_provider'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/file_content_management/content_base.rb:40:in `tempfile'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/file.rb:462:in `tempfile'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/file.rb:339:in `do_generate_content'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/file.rb:150:in `action_create'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider.rb:144:in `run_action'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource.rb:596:in `run_action'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/runner.rb:73:in `run_action'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/runner.rb:105:in `block (2 levels) in converge'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/runner.rb:105:in `each'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/runner.rb:105:in `block in converge'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/resource_list.rb:84:in `block in execute_each_resource'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/resource_list.rb:82:in `execute_each_resource'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/runner.rb:104:in `converge'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:668:in `block in converge'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:663:in `catch'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:663:in `converge'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:702:in `converge_and_save'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:280:in `run'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application.rb:252:in `run_with_graceful_exit_option'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application.rb:228:in `block in run_chef_client'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application.rb:211:in `run_chef_client'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application/solo.rb:301:in `block in interval_run_chef_client'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application/solo.rb:290:in `loop'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application/solo.rb:290:in `interval_run_chef_client'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application/solo.rb:269:in `run_application'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application.rb:58:in `run'
==> default:   C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/bin/chef-solo:25:in `<top (required)>'
==> default:   C:/opscode/chef/bin/chef-solo:60:in `load'
==> default:   C:/opscode/chef/bin/chef-solo:60:in `<main>'
==> default:
==> default: Running handlers:
==> default: [2017-07-12T09:25:25-07:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2017-07-12T09:25:25-07:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 2 resources updated in 02 minutes 43 seconds
==> default: [2017-07-12T09:25:25-07:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
==> default: [2017-07-12T09:25:25-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2017-07-12T09:25:25-07:00] DEBUG: Errno::ECONNRESET: remote_file[C:\chef\cache/jdk-8u101-windows-x64.exe] (java::windows line 45) had an error: Errno::ECONNRESET: Error connecting to http://FQDN:8081/repository/ARTIFACT_NAME-Nexus-Pro/ARTIFACT_NAME/java/8u101/jdk-8u101-windows-x64.exe - An existing connection was forcibly closed by the remote host.
==> default: C:/opscode/chef/embedded/lib/ruby/2.0.0/net/protocol.rb:153:in `read_nonblock'
==> default: C:/opscode/chef/embedded/lib/ruby/2.0.0/net/protocol.rb:153:in `rbuf_fill'
==> default: C:/opscode/chef/embedded/lib/ruby/2.0.0/net/protocol.rb:104:in `read'
==> default: C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http/response.rb:284:in `block in read_body_0'
==> default: C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http/response.rb:250:in `inflater'
==> default: C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http/response.rb:274:in `read_body_0'
==> default: C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http/response.rb:201:in `read_body'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/http.rb:406:in `stream_to_tempfile'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/http.rb:175:in `block in streaming_request'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/http/basic_client.rb:88:in `block in request'
==> default: C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http.rb:1419:in `block (2 levels) in transport_request'
==> default: C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http/response.rb:162:in `reading_body'
==> default: C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http.rb:1418:in `block in transport_request'
==> default: C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http.rb:1409:in `catch'
==> default: C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http.rb:1409:in `transport_request'
==> default: C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http.rb:1382:in `request'
==> default: C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http.rb:1375:in `block in request'
==> default: C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http.rb:852:in `start'
==> default: C:/opscode/chef/embedded/lib/ruby/2.0.0/net/http.rb:1373:in `request'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/http/basic_client.rb:65:in `request'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/http.rb:275:in `block in send_http_request'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/http.rb:308:in `block in retrying_http_errors'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/http.rb:306:in `loop'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/http.rb:306:in `retrying_http_errors'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/http.rb:271:in `send_http_request'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/http.rb:173:in `streaming_request'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/remote_file/http.rb:60:in `fetch'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/remote_file/content.rb:71:in `grab_file_from_uri'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/remote_file/content.rb:56:in `try_multiple_sources'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/remote_file/content.rb:41:in `file_for_provider'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/file_content_management/content_base.rb:40:in `tempfile'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/file.rb:462:in `tempfile'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/file.rb:339:in `do_generate_content'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider/file.rb:150:in `action_create'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/provider.rb:144:in `run_action'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource.rb:596:in `run_action'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/runner.rb:73:in `run_action'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/runner.rb:105:in `block (2 levels) in converge'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/runner.rb:105:in `each'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/runner.rb:105:in `block in converge'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/resource_list.rb:84:in `block in execute_each_resource'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/resource_collection/resource_list.rb:82:in `execute_each_resource'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/runner.rb:104:in `converge'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:668:in `block in converge'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:663:in `catch'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:663:in `converge'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:702:in `converge_and_save'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/client.rb:280:in `run'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application.rb:252:in `run_with_graceful_exit_option'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application.rb:228:in `block in run_chef_client'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application.rb:211:in `run_chef_client'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application/solo.rb:301:in `block in interval_run_chef_client'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application/solo.rb:290:in `loop'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application/solo.rb:290:in `interval_run_chef_client'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application/solo.rb:269:in `run_application'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/lib/chef/application.rb:58:in `run'
==> default: C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.1-universal-mingw32/bin/chef-solo:25:in `<top (required)>'
==> default: C:/opscode/chef/bin/chef-solo:60:in `load'
==> default: C:/opscode/chef/bin/chef-solo:60:in `<main>'
==> default: [2017-07-12T09:25:25-07:00] FATAL: Errno::ECONNRESET: remote_file[C:\chef\cache/jdk-8u101-windows-x64.exe] (java::windows line 45) had an error: Errno::ECONNRESET: Error connecting to http://FQDN:8081/repository/ARTIFACT_NAME-Nexus-Pro/ARTIFACT_NAME/java/8u101/jdk-8u101-windows-x64.exe - An existing connection was forcibly closed by the remote host.
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by coderanger** [comment]
@huamichaelchen Not sure what we can do about that, either Nexus doesn't like the connection or something similar. Not really Chef related per se.

**Comment by lamont-granquist** [comment]
chef-12.8.1 on ruby 2.0.0 under windows as well.

at a minimum that needs to get replicated on chef-13 and needs to get shown that the url works from inside the vagrant box works, but fails under chef-client.

**Comment by cheeseplus** [comment]
Closing this one due to lack of response and high likelihood this is an issue with Nexus, Vagrant, or something due to local environment.
