### ISSUE TITLE
Require gem with native extensions inside of a library.

### ISSUE THREAD

**Issue by ilovemysillybanana** [chef/chef#6337]
## Description
Trying to install gem with native extensions fails due to not having a C++ compiler on the node. My objective is to install the gem, and then be able to require it inside of a ruby file inside of cookbook/libraries/. 

An example:
```
# cookbook/library/test.rb
require 'mechanize'

class Mechanize::HTTP::Agent
  #...more code here
end
```

This is an example of what I have in my metadata.rb
```
gem 'mechanize', '~> 2.7.5'
```

## Chef Version
Chef Development Kit Version: 1.2.20
chef-client version: 12.4.0
delivery version: master (0b746cafed65a9ea1a79de3cc546e7922de9187c)
berks version: 5.6.4
kitchen version: 1.15.0

## Platform Version
Centos 7.2

## Replication Case
Create a cookbook and require gem to be installed on the node with native extensions, such as mechanize or nokogiri. 

## Client Output

```
Installing Cookbook Gems:
       
       Running handlers:
       [2017-08-16T23:16:46+00:00] ERROR: Running exception handlers
       [2017-08-16T23:16:46+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-08-16T23:16:46+00:00] ERROR: Exception handlers complete
       [2017-08-16T23:16:46+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 23 seconds
       [2017-08-16T23:16:46+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-08-16T23:16:46+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2017-08-16T23:16:46+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-08-16T23:16:46+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-08-16T23:16:46+00:00] ERROR: Expected process to exit with [0], but received '5'
       ---- Begin output of bundle install ----
       STDOUT: Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
       installing your bundle as root will break this application for all non-root
       users on this machine.
       Fetching gem metadata from https://www.rubygems.org/..................
       Fetching version metadata from https://www.rubygems.org/..
       Resolving dependencies...
       Installing unf_ext 0.0.7.4 with native extensions
       Installing mime-types-data 3.2016.0521
       Installing net-http-digest_auth 1.4.1
       Installing net-http-persistent 2.9.4
       Using mini_portile2 2.2.0
       Installing ntlm-http 0.1.1
       Installing webrobots 0.1.2
       Using bundler 1.14.6
       Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
       
       current directory:
       /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.4/ext/unf_ext
       /opt/chef/embedded/bin/ruby -r ./siteconf20170816-11454-ekpbht.rb extconf.rb
       checking for -lstdc++... *** extconf.rb failed ***
       Could not create Makefile due to some reason, probably lack of necessary
       libraries and/or headers.  Check the mkmf.log file for more details.  You may
       need configuration options.
       
       Provided configuration options:
       	--with-opt-dir
       	--with-opt-include
       	--without-opt-include=${opt-dir}/include
       	--with-opt-lib
       	--without-opt-lib=${opt-dir}/lib
       	--with-make-prog
       	--without-make-prog
       	--srcdir=.
       	--curdir
       	--ruby=/opt/chef/embedded/bin/$(RUBY_BASE_NAME)
       	--with-static-libstdc++
       	--without-static-libstdc++
       	--with-stdc++lib
       	--without-stdc++lib
       /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:468:in `try_do': The compiler failed
       to generate an executable file. (RuntimeError)
       You have to install development tools first.
       	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:553:in `try_link0'
       	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:568:in `try_link'
       	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:786:in `try_func'
       	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:1013:in `block in have_library'
       	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:956:in `block in checking_for'
       from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in
       postpone'
       	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:321:in `open'
       	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
       	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:321:in `open'
       	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
       	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:955:in `checking_for'
       	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:1008:in `have_library'
       	from extconf.rb:6:in `<main>'
       
       To see why this extension failed to compile, please check the mkmf.log which can
       be found here:
       
       /opt/chef/embedded/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0/unf_ext-0.0.7.4/mkmf.log
       
       extconf failed, exit code 1
       
       Gem files will remain installed in
       /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.4 for inspection.
       Results logged to
       /opt/chef/embedded/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0/unf_ext-0.0.7.4/gem_make.out
       
       An error occurred while installing unf_ext (0.0.7.4), and Bundler cannot
       continue.
       Make sure that `gem install unf_ext -v '0.0.7.4'` succeeds before bundling.
       STDERR: 
       ---- End output of bundle install ----
       Ran bundle install returned 5
       [2017-08-16T23:16:46+00:00] ERROR: Expected process to exit with [0], but received '5'
       ---- Begin output of bundle install ----
       STDOUT: Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
       installing your bundle as root will break this application for all non-root
       users on this machine.
       Fetching gem metadata from https://www.rubygems.org/..................
       Fetching version metadata from https://www.rubygems.org/..
       Resolving dependencies...
       Installing unf_ext 0.0.7.4 with native extensions
       Installing mime-types-data 3.2016.0521
       Installing net-http-digest_auth 1.4.1
       Installing net-http-persistent 2.9.4
       Using mini_portile2 2.2.0
       Installing ntlm-http 0.1.1
       Installing webrobots 0.1.2
       Using bundler 1.14.6
       Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
       
       current directory:
       /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.4/ext/unf_ext
       /opt/chef/embedded/bin/ruby -r ./siteconf20170816-11454-ekpbht.rb extconf.rb
       checking for -lstdc++... *** extconf.rb failed ***
       Could not create Makefile due to some reason, probably lack of necessary
       libraries and/or headers.  Check the mkmf.log file for more details.  You may
       need configuration options.
       
       Provided configuration options:
       	--with-opt-dir
       	--with-opt-include
       	--without-opt-include=${opt-dir}/include
       	--with-opt-lib
       	--without-opt-lib=${opt-dir}/lib
       	--with-make-prog
       	--without-make-prog
       	--srcdir=.
       	--curdir
       	--ruby=/opt/chef/embedded/bin/$(RUBY_BASE_NAME)
       	--with-static-libstdc++
       	--without-static-libstdc++
       	--with-stdc++lib
       	--without-stdc++lib
       /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:468:in `try_do': The compiler failed
       to generate an executable file. (RuntimeError)
       You have to install development tools first.
       	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:553:in `try_link0'
       	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:568:in `try_link'
       	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:786:in `try_func'
       	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:1013:in `block in have_library'
       	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:956:in `block in checking_for'
       from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in
       postpone'
       	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:321:in `open'
       	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
       	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:321:in `open'
       	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
       	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:955:in `checking_for'
       	from /opt/chef/embedded/lib/ruby/2.4.0/mkmf.rb:1008:in `have_library'
       	from extconf.rb:6:in `<main>'
       
       To see why this extension failed to compile, please check the mkmf.log which can
       be found here:
       
       /opt/chef/embedded/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0/unf_ext-0.0.7.4/mkmf.log
       
       extconf failed, exit code 1
       
       Gem files will remain installed in
       /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/unf_ext-0.0.7.4 for inspection.
       Results logged to
       /opt/chef/embedded/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0/unf_ext-0.0.7.4/gem_make.out
       
       An error occurred while installing unf_ext (0.0.7.4), and Bundler cannot
       continue.
       Make sure that `gem install unf_ext -v '0.0.7.4'` succeeds before bundling.
       STDERR: 
       ---- End output of bundle install ----
       Ran bundle install returned 5
       [2017-08-16T23:16:46+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
       [2017-08-16T23:16:46+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by coderanger** [comment]
Yes, this is what happens. You would have to install whatever build environment you wanted to use before running Chef if you want to support this. We have no plans to do anything more automated than what is there now. I would recommend finding a non-ext gem to use instead, or diving into the wild world of binary (i.e. pre-compiled) fat gems.

**Comment by ilovemysillybanana** [comment]
That makes me sad, but okay. I'll look into the precompiled gem option. Thanks.

**Comment by coderanger** [comment]
You might want to look at the `selenium-webdriver` gem, or possibly Capybara.
