### ISSUE TITLE
Chef Client yum_package version property cannot handle constraints in 12.19.36

### ISSUE THREAD

**Issue by sean-horn** [chef/chef#6419]
## Description

yum_package version property cannot handle constraints such as ">=". The constraint is passed to the install_remote_package method along with the version number, while that method is only expecting a version number.

A good run has this passed to the install_remote_package method `install_remote_package(true, ["4.12-4.el7"])`

A bad run has `install_remote_package(false, [">= 4.12-4.el7"])`

Until this can be rectified, or while Chef decides not to fix it, we should keep around the deprecated ability to install packages with their versions constrained in the package name property as in `yum_package "strace >= 4.12-4.el7" do`

## Chef Version

Chef Client 12.19.36

## Platform Version

CentOS 7.3

## Replication Case

Chef Client 12.19.36 on CentOS 7.3

Code in update-package-bad.rb recipe

```
yum_package "strace" do
  version '>= 4.12-4.el7'
end
```

Code in update-package-good.rb recipe

```
yum_package "strace >= 4.12-4.el7"
```

## Repro

* Failure: Run Chef Client as `chef-client -l debug -z update-package-bad.rb`

```
[2017-09-18T18:42:38+00:00] DEBUG: yum_package[strace] checking yum info for strace
[2017-09-18T18:42:38+00:00] DEBUG: Found Yum package: strace installed version: 4.8-11.el7 candidate version: 4.12-4.el7
[2017-09-18T18:42:38+00:00] DEBUG: yum_package[strace] strace 4.8-11.el7 needs updating to >= 4.8-10.el7


    ================================================================================
    Error executing action `install` on resource 'yum_package[strace]'
    ================================================================================

    Chef::Exceptions::Package
    -------------------------
    Version [">= 4.8-10.el7"] of ["strace"] not found. Did you specify both version and release? (version-release, e.g. 1.84-10.fc6)

    Resource Declaration:
    ---------------------
    # In /update-package-bad.rb

      1: yum_package "strace" do
      2:   version '>= 4.8-10.el7'
      3: end

    Compiled Resource:
    ------------------
    # Declared in /update-package-bad.rb:1:in `from_file'

    yum_package("strace") do
      package_name "strace"
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :yum_package
      cookbook_name "@recipe_files"
      recipe_name "/update-package-bad.rb"
      version ">= 4.8-10.el7"
      flush_cache {:before=>false, :after=>false}
    end

    Platform:
    ---------
    x86_64-linux

[2017-09-18T18:42:38+00:00] INFO: Running queued delayed notifications before re-raising exception
[2017-09-18T18:42:38+00:00] DEBUG: Re-raising exception: Chef::Exceptions::Package - yum_package[strace] (@recipe_files::/update-package-bad.rb line 1) had an error: Chef::Exceptions::Package: Version [">= 4.8-10.el7"] of ["strace"] not found. Did you specify both version and release? (version-release, e.g. 1.84-10.fc6)
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/provider/package/yum.rb:357:in `install_remote_package'
  /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/provider/package/yum.rb:123:in `install_package'
``` 

* Success: Run Chef Client as `chef-client -l debug -z update-package-good.rb`

```
[2017-09-18T18:43:52+00:00] DEBUG: strace >= 4.8-10.el7: Unable to match package 'strace >= 4.8-10.el7' but matched 2 packages, selected 'strace' version '4.12-4.el7'
[2017-09-18T18:43:52+00:00] WARN: yum_package[strace >= 4.8-10.el7] matched multiple Provides for strace >= 4.8-10.el7 but we can only use the first match: strace. Please use a more specific version.
[2017-09-18T18:43:52+00:00] DEBUG: yum_package[strace >= 4.8-10.el7] checking yum info for strace
[2017-09-18T18:43:52+00:00] DEBUG: Found Yum package: strace installed version: 4.8-11.el7 candidate version: 4.12-4.el7
[2017-09-18T18:43:52+00:00] DEBUG: yum_package[strace >= 4.8-10.el7] strace 4.8-11.el7 needs updating to 4.12-4.el7
[2017-09-18T18:43:52+00:00] INFO: yum_package[strace >= 4.8-10.el7] installing strace-4.12-4.el7 from base repository
[2017-09-18T18:43:52+00:00] DEBUG: yum_package[strace >= 4.8-10.el7]: yum command: "yum -d0 -e0 -y install strace-4.12-4.el7"
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
[2017-09-18T18:43:54+00:00] INFO: yum_package[strace >= 4.8-10.el7] installed strace at 4.12-4.el7

    - install version 4.12-4.el7 of package strace
[2017-09-18T18:43:54+00:00] DEBUG: Saving the current state of node test-start.lxc

[root@test-start /]# rpm -qa | grep strace
strace-4.12-4.el7.x86_64
```

**Comment by lamont-granquist** [comment]
Closing as dup of #3908

This is being addressed by @jonlives copying the DNF package provider approach to the yum provider, which is work that is in flight.  The DNF package provider handles constraints correctly:

https://github.com/chef/chef/blob/master/spec/functional/resource/dnf_package_spec.rb#L271-L331

This should also fix many other yum provider issues, including performance and memory consumption issues along with other bugs and the general tirefire nature of the existing codebase.
