### ISSUE TITLE
Chef-client unable to find Recipe

### ISSUE THREAD

**Issue by al1baba** [chef/chef#6423]
## Description

I am getting an error Chef::Exceptions::RecipeNotFound when trying to run the chef-client on a node after uploading my cookbook with knife cookbook upload and updating the node's run-list to call the recipe. I used:
knife node run_list set wtatestuser "recipe[testingnecinit::necinit.rb]"

## Chef Version

Chef Development Kit Version: 2.0.26
chef-client version: 13.2.20
delivery version: master
berks version: 6.2.0
kitchen version: 1.16.0
inspec version: 1.30.0

## Platform Version

The chef server is running Ubuntu and my ChefDK machine is on Mac OSX Sierra (latest stable update).
## Replication Case

First create a working server for chef, then successfully bootstrap the node that you wish to manage with knife bootstrap. Then, create a cookbook with multiple recipes, and upload to chef server with knife cookbook upload. Update the node's run-list with knife node run-list then use knife ssh to remotely run the chef client on the node. Then you should see this error.

## Client Output

 knife sudo password: 
  
```
  Starting Chef Client, version 13.4.19
  resolving cookbooks for run list: ["testingnecinit::necinit.rb"]
  Synchronizing Cookbooks:
    - testingnecinit (0.1.1)
  Installing Cookbook Gems:
  Compiling Cookbooks...
  
  Recipe Compile Error
  
  Chef::Exceptions::RecipeNotFound

  could not find recipe necinit.rb for cookbook testingnecinit
  
  System Info:

  chef_version=13.4.19
  platform=mac_os_x
  platform_version=10.12.6
  ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin14]
  program_name=chef-client worker: ppid=11209;start=09:43:17;
  executable=/opt/chef/bin/chef-client
  
  
  Running handlers:
  [2017-09-19T09:43:21-04:00] ERROR: Running exception handlers
  Running handlers complete
  [2017-09-19T09:43:21-04:00] ERROR: Exception handlers complete
  Chef Client failed. 0 resources updated in 03 seconds
  [2017-09-19T09:43:21-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
  [2017-09-19T09:43:21-04:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
  [2017-09-19T09:43:21-04:00] ERROR: could not find recipe necinit.rb for cookbook testingnecinit
  [2017-09-19T09:43:21-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

## Stacktrace
Generated at 2017-09-19 09:43:21 -0400
Chef::Exceptions::RecipeNotFound: could not find recipe necinit.rb for cookbook testingnecinit
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/cookbook_version.rb:194:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/run_context.rb:343:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/run_context/cookbook_compiler.rb:163:in `block in compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/run_context/cookbook_compiler.rb:160:in `each'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/run_context/cookbook_compiler.rb:160:in `compile_recipes'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/run_context/cookbook_compiler.rb:77:in `compile'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/run_context.rb:192:in `load'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/client.rb:513:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/client.rb:281:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application.rb:291:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application.rb:279:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application.rb:279:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application.rb:244:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application.rb:232:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application/client.rb:457:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application/client.rb:457:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application/client.rb:441:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/bin/chef-client:26:in `<top (required)>'
/usr/local/bin/chef-client:58:in `load'
/usr/local/bin/chef-client:58:in `<main>'
```

##
Not really sure what I'm doing wrong. Any suggestions? I really don't want to have to rebuild this server again (already have like 4 times). It would help if there was better documentation on the non-web assisted version of chef.

**Comment by coderanger** [comment]
That should be `knife node run_list set wtatestuser "recipe[testingnecinit::necinit]"`, i.e. without the `.rb`.

**Comment by al1baba** [comment]
I'm silly thank you.
