### ISSUE TITLE
Resource windows_task fails with invalid date error, when task already exists.

### ISSUE THREAD

**Issue by krzkowalczyk** [chef/chef#6480]
## Description

Resource windows_task fails with invalid date error, when task already exists.

## Chef Version

13.5.3

## Platform Version

Windows 2008 R2 with polish date format (yyyy-MM-dd)
The issue does not occur on english date format.

## Replication Case

Run chef-client cookbook. It will by default register windows task with chef-client
All subsequent chef-client runs ends up with error on windows_task

## Client Output

```
    * windows_task[chef-client] action create[2017-10-06T16:26:19+02:00] INFO: Processing windows_task[chef-client] acti
on create (C:/chef/cache/cookbooks/chef-client/resources/scheduled_task.rb line 46)
[2017-10-06T16:26:19+02:00] DEBUG: Providers for generic windows_task resource enabled on node include: [Chef::Provider:
:WindowsTask, LWRP provider windows_task from cookbook windows]
[2017-10-06T16:26:19+02:00] DEBUG: Provider for action create on resource windows_task[chef-client] is Chef::Provider::W
indowsTask
[2017-10-06T16:26:19+02:00] DEBUG: Looking for existing tasks

Folder: \
HostName:                             MWAWPOSHCK002
TaskName:                             \chef-client
Next Run Time:                        2017-10-06 16:47:00
Status:                               Ready
Logon Mode:                           Interactive/Background
Last Run Time:                        2017-10-06 16:17:00
Last Result:                          1
Author:                               praefectus
Task To Run:                          cmd /c "C:/opscode/chef/bin/chef-client -L C:/chef/log/client.log -c C:/chef/clien
t.rb -s 300"
Start In:                             N/A
Comment:                              N/A
Scheduled Task State:                 Enabled
Idle Time:                            Disabled
Power Management:                     Stop On Battery Mode, No Start On Batteries
Run As User:                          SYSTEM
Delete Task If Not Rescheduled:       Enabled
Stop Task If Runs X Hours and X Mins: 72:00:00
Schedule:                             Scheduling data is not available in this format.
Schedule Type:                        One Time Only, Minute
Start Time:                           16:17:00
Start Date:                           2017-10-06
End Date:                             N/A
Days:                                 N/A
Months:                               N/A
Repeat: Every:                        0 Hour(s), 30 Minute(s)
Repeat: Until: Time:                  None
Repeat: Until: Duration:              Disabled
Repeat: Stop If Still Running:        Disabled
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Date>2017-10-06T15:47:03</Date>
    <Author>praefectus</Author>
  </RegistrationInfo>
  <Triggers>
    <TimeTrigger>
      <Repetition>
        <Interval>PT30M</Interval>
        <StopAtDurationEnd>false</StopAtDurationEnd>
      </Repetition>
      <StartBoundary>2017-10-06T16:17:00</StartBoundary>
      <Enabled>true</Enabled>
    </TimeTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <RunLevel>HighestAvailable</RunLevel>
      <UserId>S-1-5-18</UserId>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>true</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>true</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <Duration>PT10M</Duration>
      <WaitTimeout>PT1H</WaitTimeout>
      <StopOnIdleEnd>true</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <Priority>7</Priority>
    <ExecutionTimeLimit>PT72H</ExecutionTimeLimit>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>cmd</Command>
      <Arguments>/c "C:/opscode/chef/bin/chef-client -L C:/chef/log/client.log -c C:/chef/client.rb -s 300"</Arguments>
    </Exec>
  </Actions>
</Task>[2017-10-06T16:26:20+02:00] DEBUG: Finding system date format
yyyy-MM-dd


      ================================================================================
      Error executing action `create` on resource 'windows_task[chef-client]'
      ================================================================================

      ArgumentError
      -------------
      invalid date

      Resource Declaration:
      ---------------------
      # In C:/chef/cache/cookbooks/chef-client/resources/scheduled_task.rb

       46:   windows_task 'chef-client' do
       47:     run_level :highest
       48:     command "cmd /c \"#{client_cmd}\""
       49:
       50:     user               new_resource.user
       51:     password           new_resource.password
       52:     frequency          new_resource.frequency.to_sym
       53:     frequency_modifier new_resource.frequency_modifier
       54:     start_time         new_resource.start_time || start_time
       55:   end
       56: end

      Compiled Resource:
      ------------------
      # Declared in C:/chef/cache/cookbooks/chef-client/resources/scheduled_task.rb:46:in `block in class_from_file'

      windows_task("chef-client") do
        action :create
        default_guard_interpreter :default
        task_name "chef-client"
        declared_type :windows_task
        cookbook_name "chef-client"
        run_level :highest
        command "cmd /c \"C:/opscode/chef/bin/chef-client -L C:/chef/log/client.log -c C:/chef/client.rb -s 300\""
        user "SYSTEM"
        password nil
        frequency :minute
        frequency_modifier 30
        start_time "16:56"
        execution_time_limit "PT72H"
        start_day "2017-10-06"
      end

      System Info:
      ------------
      chef_version=13.5.3
      platform=windows
      platform_version=6.1.7601
      ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
      program_name=C:/opscode/chef/bin/chef-client
      executable=C:/opscode/chef/bin/chef-client

[2017-10-06T16:26:20+02:00] INFO: Running queued delayed notifications before re-raising exception

```

**Comment by KierranM** [comment]
I'm also running into this issue with Chef 13.4.24 on a system set to the UTC timezone with the same circumstances as described.

**Comment by esalter** [comment]
Also discussed here: https://github.com/chef-cookbooks/chef-client/issues/523

**Comment by samefing** [comment]
Seeing the same issue on a Win2016 Server. Oddly only reports a failure when forcing a chef-client run via WinRM, the automated runs which are initiated by the scheduled task report success.

**Comment by esalter** [comment]
There's a commit that says it fixes it in 13.5.22.

**Comment by krzkowalczyk** [comment]
@esalter could you point me that commit ?
I've just checked 13.5.22 and the problem still occurs

**Comment by esalter** [comment]
Admittedly I had a hard time finding it, it has been reported in a few separate issues. 
 
https://github.com/chef/chef/issues/6439

Says it should have been fixed by commit https://github.com/chef/chef/commit/b0d96997b7a1f53824c3cb0905de3e4bc770e534

I didn't have a chance to do extensive testing, but I tried it out really quick and it seemed to resolve it.  You have to specify the start_day in mm/dd/yyyy format.

**Comment by esalter** [comment]
It's possible this is a separate issue - apologies if I have confused the issue if that's the case.

**Comment by krzkowalczyk** [comment]
After some time spend on debugging this issue I found a root cause. I didn't see this in stacktrace in the first moment:
```
>>>> Caused by ArgumentError: invalid date
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/provider/windows_task.rb:495:in
 `strptime'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/provider/windows_task.rb:495:in
 `parse_day'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/provider/windows_task.rb:226:in
 `start_day_updated?'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/provider/windows_task.rb:212:in
 `task_need_update?'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/provider/windows_task.rb:94:in
`action_create'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/provider.rb:171:in `run_action'

C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/resource.rb:591:in `run_action'
```

It's caused by running `parse_day` function on `new_resource.start_day`, where `new_resource.start_day` it's assumed to be in format `"%m/%d/%Y"`

Be default chef-client::task creates a task with `new_resource.start_time` specified only. When no task exist on the system `new_resource.start_day` is `nil`, and no `parse_day` function is executed on it, due to guards implemented.

Therefore when current task exists, this block assigns to all `nil` attributes in `new_resource` values from `current_resource`. So the `new_resource.start_day` gets date from current task in systems time/date format (which in my case isn't `"%m/%d/%Y"`), and cannot be parsed.

```
        if current_resource.exists
          if !(task_need_update? || new_resource.force)
            Chef::Log.info "#{new_resource} task already exists - nothing to do"
            return
          end
          # To merge current resource and new resource attributes
          resource_attributes.each do |attribute|
            new_resource_attribute = new_resource.send(attribute)
            current_resource_attribute = current_resource.send(attribute)
            new_resource.send("#{attribute}=", current_resource_attribute ) if current_resource_attribute && new_resource_attribute.nil?
          end
        end
```

The breaking change was introduced in [#6312](https://github.com/chef/chef/pull/6312), I don't understand the idea behind overriding data from current_resource. When removing this override, `new_resource.start_day` stays nil, and in my case the issue does not occur. If this override is necessary, then start_day should be reformatted to `"%m/%d/%Y"`, while being retrieved from current_resource.

In addition the resource applied with default chef-client::task recipe is not idempotent, due to comparing start_day and start_time, and here start_times will be always different between runs, as `new_resource.start_time` is dynamically generated each time. Start_time might be removed, as we don't care much about it in this case, and we care more about `frequency_modifier`, but it seems like this won't work as described [here](https://github.com/chef/chef/pull/6312#issuecomment-337533074)

**Comment by deanoroe** [comment]
We're also seeing this issue as above on all our Windows Server 2016 machines, running chef client 13.5.3 and chef client cookbook 8.1.8

**Comment by dreslan** [comment]
We are also seeing this in version 13.6.9 server 2012R2

**Comment by ywainberg** [comment]
Hi
any status on resolving?

**Comment by NimishaS** [comment]
The issue has been resolved in https://github.com/chef/chef/pull/6544. Waiting for it to be merged.
