### ISSUE TITLE
Chef >=13.4.19 Windows remote_file throws undefined local variable or method `node' for #<Chef::Provider::RemoteFile::NetworkFile

### ISSUE THREAD

**Issue by mdpdesign** [chef/chef#6518]
## Description

When using `remote_file` resource and Windows UNC path, on Windows OS, Chef throws error:

```
NameError
---------
undefined local variable or method `node' for #<Chef::Provider::RemoteFile::NetworkFile:0x0000000004a3d690>
```

This is most probably caused by the line: https://github.com/chef/chef/blob/01c43a744c85b89dc153489a9d1182c14ae31371/lib/chef/resource/remote_file.rb#L148

## Chef Version

Chef-client version >=13.4.19

## Platform Version

Windows Server 2012R2

## Replication Case

Declare in the recipe `remote_file` resource and test it on the Windows machine. Network share is accessible without the need for credentials. Mine example looks like this:

### In the default.rb attribute file (IP address is just an example):

```ruby
default['ra']['test']['checksum'] = '9F707096C7D279ED4BC2A40BA695EFAC69C20406E0CA97E2B3E08443C6381D15'
default['ra']['test']['source'] = '\\\\192.168.10.100\Common Software\Downloaded Software\Microsoft\Visual Studio\VS 2015 Enterprise\Windows8.1-KB2999226-x64.msu'
```

### In the default.rb recipe file:

```ruby
update_source          = node['ra']['test']['source']
update_source_checksum = node['ra']['test']['checksum']
temp_dir               = File.join(Chef::Config[:file_cache_path], 'testing_cookbook_temp')
temp_file              = File.join(temp_dir, 'Windows8.1-KB2999226-x64.msu')

# Ensure the target directory exists so we can put the package there
directory 'Create KB2999226 temp directory' do
  path temp_dir
  recursive true
end

# Copy/Download KB file to the temp directory
remote_file temp_file do
  source update_source
  checksum update_source_checksum
end
```

## Client Output

```
$ kitchen converge
-----> Starting Kitchen (v1.16.0)
-----> Converging <default-windows-ra-2012r2>...
       Preparing files for transfer
       Updating policy lock using `chef update`
       Attributes already up to date
       Building policy example-empty-test
       Expanded run list: recipe[empty_cookbook::default]
       Caching Cookbooks...
       Installing empty_cookbook >= 0.0.0 from path

       Lockfile written to C:/Users/Administrator/Desktop/empty-cookbook/empty_cookbook/Policyfile.lock.json
       Policy revision id: 6eda0255e4674a6799eea4642a43166737ef1d4e5abdf176773f216953e16e75
       Installing cookbooks for Policyfile C:/Users/Administrator/Desktop/empty-cookbook/empty_cookbook/Policyfile.rb using `chef install`
       Installing cookbooks from lock
       Installing empty_cookbook 0.1.0
       Preparing dna.json
       Exporting cookbook dependencies from Policyfile C:/Users/ADMINI~1/AppData/Local/Temp/2/default-windows-ra-2012r2-sandbox-20171024-5928-1790s45...
       Exported policy 'example-empty-test' to C:/Users/ADMINI~1/AppData/Local/Temp/2/default-windows-ra-2012r2-sandbox-20171024-5928-1790s45

       To converge this system with the exported policy, run:
         cd C:/Users/ADMINI~1/AppData/Local/Temp/2/default-windows-ra-2012r2-sandbox-20171024-5928-1790s45
         chef-client -z
       Removing non-cookbook files before transfer
       Preparing data_bags
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected ()
       Transferring files to <default-windows-ra-2012r2>
       [2017-10-24T11:22:14+02:00] INFO: Started chef-zero at chefzero://localhost:1 with repository at C:/Users/vagrant/AppData/Local/Temp/kitchen, C:/Users/vagrant/AppData/Local/Temp/kitchen
         One version per cookbook

       Starting Chef Client, version 13.4.19
       [2017-10-24T11:22:14+02:00] INFO: *** Chef 13.4.19 ***
       [2017-10-24T11:22:14+02:00] INFO: Platform: x64-mingw32
       [2017-10-24T11:22:14+02:00] INFO: Chef-client pid: 2320
       [2017-10-24T11:22:14+02:00] INFO: The plugin path C:\chef\ohai\plugins does not exist. Skipping...
       Using policy 'example-empty-test' at revision '6eda0255e4674a6799eea4642a43166737ef1d4e5abdf176773f216953e16e75'
       [2017-10-24T11:22:17+02:00] INFO: Run List is [["recipe[empty_cookbook::default]"]]
       [2017-10-24T11:22:17+02:00] INFO: Run List expands to [empty_cookbook::default@0.1.0 (31280b1)]
       [2017-10-24T11:22:17+02:00] INFO: Starting Chef Run for default-windows-ra-2012r2
       [2017-10-24T11:22:17+02:00] INFO: Running start handlers
       [2017-10-24T11:22:17+02:00] INFO: Start handlers complete.
       resolving cookbooks for run list: ["empty_cookbook::default@0.1.0 (31280b1)"]
       [2017-10-24T11:22:17+02:00] INFO: Loading cookbooks [empty_cookbook@0.1.0]
       Synchronizing Cookbooks:
       [2017-10-24T11:22:17+02:00] INFO: Storing updated cookbooks/empty_cookbook/recipes/default.rb in the cache.
         - empty_cookbook (0.1.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       Converging 2 resources
       Recipe: empty_cookbook::default
         * directory[Create KB2999226 temp directory] action create[2017-10-24T11:22:17+02:00] INFO: Processing directory[Create KB2999226 temp directory] action create (empty_cookbook::default line 13)
       [2017-10-24T11:22:17+02:00] INFO: directory[Create KB2999226 temp directory] created directory C:\Users\vagrant\AppData\Local\Temp\kitchen\cache/testing_cookbook_temp

           - create new directory C:\Users\vagrant\AppData\Local\Temp\kitchen\cache/testing_cookbook_temp
         * remote_file[C:\Users\vagrant\AppData\Local\Temp\kitchen\cache/testing_cookbook_temp/Windows8.1-KB2999226-x64.msu] action create[2017-10-24T11:22:17+02:00] INFO: Processing remote_file[C:\Users\vagrant\AppData\Local\Temp\kitchen\cache/testing_cookbook_temp/Windows8.1-KB2999226-x64.msu] action create (empty_cookbook::default line 19)


           ================================================================================
           Error executing action `create` on resource 'remote_file[C:\Users\vagrant\AppData\Local\Temp\kitchen\cache/testing_cookbook_temp/Windows8.1-KB2999226-x64.msu]'
           ================================================================================

           NameError
           ---------
           undefined local variable or method `node' for #<Chef::Provider::RemoteFile::NetworkFile:0x00000004bb89c0>

           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/empty_cookbook/recipes/default.rb

            19: remote_file temp_file do
            20:   source update_source
            21:   checksum update_source_checksum
            22: end

           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/empty_cookbook/recipes/default.rb:19:in `from_file'

           remote_file("C:\Users\vagrant\AppData\Local\Temp\kitchen\cache/testing_cookbook_temp/Windows8.1-KB2999226-x64.msu") do
             provider Chef::Provider::RemoteFile
             action [:create]
             default_guard_interpreter :default
             source ["\\\\192.12.135.100\\Common Software\\Downloaded Software\\Microsoft\\Visual Studio\\VS 2015 Enterprise\\Windows8.1-KB2999226-x64.msu"]
             use_etag true
             use_last_modified true
             declared_type :remote_file
             cookbook_name "empty_cookbook"
             recipe_name "default"
             checksum "9F707096C7D279ED4BC2A40BA695EFAC69C20406E0CA97E2B3E08443C6381D15"
             remote_domain nil
             remote_user nil
             path "C:\\Users\\vagrant\\AppData\\Local\\Temp\\kitchen\\cache/testing_cookbook_temp/Windows8.1-KB2999226-x64.msu"
             rights nil
             deny_rights nil
             verifications []
           end

           System Info:
           ------------
           chef_version=13.4.19
           platform=windows
           platform_version=6.3.9600
           ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
           program_name=C:/opscode/chef/bin/chef-client
           executable=C:/opscode/chef/bin/chef-client

       [2017-10-24T11:22:17+02:00] INFO: Running queued delayed notifications before re-raising exception

       Running handlers:
       [2017-10-24T11:22:17+02:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-10-24T11:22:17+02:00] ERROR: Exception handlers complete
       Chef Client failed. 1 resources updated in 03 seconds
       [2017-10-24T11:22:17+02:00] FATAL: Stacktrace dumped to C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       [2017-10-24T11:22:17+02:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-10-24T11:22:17+02:00] FATAL: NameError: remote_file[C:\Users\vagrant\AppData\Local\Temp\kitchen\cache/testing_cookbook_temp/Windows8.1-KB2999226-x64.msu] (empty_cookbook::default line 19) had an error: NameError: undefined local variable or method `node' for #<Chef::Provider::RemoteFile::NetworkFile:0x00000004bb89c0>
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-windows-ra-2012r2>.  Please see .kitchen/logs/default-windows-ra-2012r2.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

## Stacktrace

After I ran chef using chef-client 13.4.19, I also tried newer version 13.5.3 of chef-client. Stacktrace is from the 13.5.3 chef-client

```
Generated at 2017-10-24 11:38:41 +0200
NameError: remote_file[C:\Users\vagrant\AppData\Local\Temp\kitchen\cache/testing_cookbook_temp/Windows8.1-KB2999226-x64.msu] (empty_cookbook::default line 19) had an error: NameError: undefined local variable or method `node' for #<Chef::Provider::RemoteFile::NetworkFile:0x0000000004a3d690>
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/mixin/user_context.rb:26:in `with_user_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/provider/remote_file/network_file.rb:46:in `fetch'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/provider/remote_file/content.rb:71:in `grab_file_from_uri'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/provider/remote_file/content.rb:56:in `try_multiple_sources'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/provider/remote_file/content.rb:41:in `file_for_provider'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/file_content_management/content_base.rb:40:in `tempfile'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/provider/file.rb:450:in `tempfile'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/provider/file.rb:327:in `do_generate_content'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/provider/file.rb:140:in `action_create'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/provider.rb:171:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/resource.rb:591:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/runner.rb:70:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/runner.rb:98:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/runner.rb:98:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/runner.rb:98:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/runner.rb:97:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/client.rb:715:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/client.rb:710:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/client.rb:710:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/client.rb:749:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/client.rb:286:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/application.rb:273:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/application.rb:249:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/application.rb:232:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/application/client.rb:457:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/application/client.rb:457:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/application/client.rb:441:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:58:in `load'
C:/opscode/chef/bin/chef-client:58:in `<main>'

>>>> Caused by NameError: undefined local variable or method `node' for #<Chef::Provider::RemoteFile::NetworkFile:0x0000000004a3d690>
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/mixin/user_context.rb:26:in `with_user_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/provider/remote_file/network_file.rb:46:in `fetch'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/provider/remote_file/content.rb:71:in `grab_file_from_uri'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/provider/remote_file/content.rb:56:in `try_multiple_sources'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/provider/remote_file/content.rb:41:in `file_for_provider'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/file_content_management/content_base.rb:40:in `tempfile'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/provider/file.rb:450:in `tempfile'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/provider/file.rb:327:in `do_generate_content'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/provider/file.rb:140:in `action_create'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/provider.rb:171:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/resource.rb:591:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/runner.rb:70:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/runner.rb:98:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/runner.rb:98:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/runner.rb:98:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/runner.rb:97:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/client.rb:715:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/client.rb:710:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/client.rb:710:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/client.rb:749:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/client.rb:286:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/application.rb:273:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/application.rb:249:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/application.rb:232:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/application/client.rb:457:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/application/client.rb:457:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/application/client.rb:441:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:58:in `load'
C:/opscode/chef/bin/chef-client:58:in `<main>'
```

**Comment by tas50** [comment]
This is a known issue that we've resolved with this PR https://github.com/chef/chef/pull/6510. You can use the 13.5.24 build from the current channel to bring that change in or you can wait for the 13.6 release, which will include the fix.
