### ISSUE TITLE
Incorrect Deprecation Warning

### ISSUE THREAD

**Issue by damacus** [chef/chef#6533]
## Description

Chef throws an incorrect DeprecatedFeatureError exception when you attempt to call a resource with a property that doesn't exist

## Chef Version

Chef Client, version 13.5.3

## Platform Version

Test Kitchen, multiple OS

## Replication Case

Calling resource 
```ruby
property :version, String, default: '10'
property :minor_version, String, default: '10-1'

default_action :install

action :install do
  postgresql_repository 'add' do
    version "#{new_resource.version}"
    minor_version "#{new_resource.minor_version}"
  end
end
```

Secondary/nested resource (note it doesn't have minor version):
```ruby
property :version, String, default: '10'
default_action :add

action :add do
---
end
```

## Client Output

```
================================================================================
             Error executing action `install` on resource 'postgresql_client_install[client]'
             ================================================================================

             Chef::Exceptions::DeprecatedFeatureError
             ----------------------------------------
             "rename minor_version to new_resource.minor_version (CHEF-19)/tmp/kitchen/cache/cookbooks/postgresql/resources/client_install.rb:27:in `block (2 levels) in class_from_file'.\nPlease see https://docs.chef.io/deprecations_namespace_collisions.html for further details and information on how to correct this problem. at /opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.5.3/lib/chef/formatters/doc.rb:419:in `deprecation'"

```
## Stacktrace

Full test kitchen run: https://gist.github.com/damacus/fb220a3725e8cf653769e9c0effcbf53

**Comment by coderanger** [comment]
This is a side effect of how the magic scope promotion in resources works, I don't think we can fix it because Ruby doesn't understand a difference between `new_resource.minor_version` and `minor_version` in the resource instance context.

**Comment by damacus** [comment]
I thought that might be the case.
