### ISSUE TITLE
Chef >= 13 gem_package on windows cannot find external gem command via `which` helper

### ISSUE THREAD

**Issue by martinmosegaard** [chef/chef#6708]
## Description
The documentation for the `gem_package` resource, https://docs.chef.io/resource_gem_package.html , makes it sound like the `gem_binary` property is optional:

```
A property for the gem_package provider that is used to specify a gems binary.
By default, the same version of Ruby that is used by the chef-client will be installed.
```

I have a recipe with a block like this:

```
gem_package 'my_gem' do
  action :install
  source 'my-artifact-repository'
end
```

I can run kitchen converge fine with Chef client 12. But with Chef client 13, I get an error like this:

```
Chef::Exceptions::ValidationFailed: Property gem_binary must be one of String!  
You passed false.
```

I have tested with Chef client 13.2.20-1 and 13.4.19-1.

See also https://github.com/chef/chef-web-docs/issues/1169

## Chef Version

I have tested with Chef client 13.2.20-1 and 13.4.19-1.

## Platform Version

Windows Server 2012 R2, both workstation and Kitchen instances

## Replication Case

^^

## Client Output

```

```

**Comment by lamont-granquist** [comment]
really could use the stacktrace.out here

**Comment by martinmosegaard** [comment]
I understand. Please tell me how to get it. Other than that, I imagine it is not so hard to reproduce.

**Comment by martinmosegaard** [comment]
Hope this helps. I was unable to reproduce it on macOS, but on Windows Server 2012/2016.
The cookbook just contains the recipe content mentioned above:

```
[2018-01-04T11:46:06-08:00] WARN: No config file found or specified on command line, using command line options.
Starting Chef Client, version 13.4.19
[2018-01-04T11:46:12-08:00] WARN: Run List override has been provided.
[2018-01-04T11:46:12-08:00] WARN: Original Run List: [recipe[learn_chef_iis]]
[2018-01-04T11:46:12-08:00] WARN: Overridden Run List: [recipe[issue_6708::default]]
resolving cookbooks for run list: ["issue_6708::default"]
Synchronizing Cookbooks:
  - issue_6708 (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: issue_6708::default
  * gem_package[my_gem] action install

    ================================================================================
    Error executing action `install` on resource 'gem_package[my_gem]'
    ================================================================================

    Chef::Exceptions::ValidationFailed
    ----------------------------------
    Property gem_binary must be one of: String!  You passed false.

    Resource Declaration:
    ---------------------
    # In C:/Users/Administrator/.chef/local-mode-cache/cache/cookbooks/issue_6708/recipes/default.rb

      7: gem_package 'my_gem' do
      8:   action :install
      9:   source 'my-artifact-repository'
     10: end

    Compiled Resource:
    ------------------
    # Declared in C:/Users/Administrator/.chef/local-mode-cache/cache/cookbooks/issue_6708/recipes/default.rb:7:in `from_file'

    gem_package("my_gem") do
      package_name "my_gem"
      action [:install]
      default_guard_interpreter :default
      declared_type :gem_package
      cookbook_name "issue_6708"
      recipe_name "default"
      source "my-artifact-repository"
    end

    System Info:
    ------------
    chef_version=13.4.19
    platform=windows
    platform_version=10.0.14393
    ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
    program_name=C:/opscode/chefdk/bin/chef-client
    executable=C:/opscode/chefdk/bin/chef-client


Running handlers:
[2018-01-04T11:46:13-08:00] ERROR: Running exception handlers
Running handlers complete
[2018-01-04T11:46:13-08:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 04 seconds
[2018-01-04T11:46:13-08:00] FATAL: Stacktrace dumped to C:/Users/Administrator/.chef/local-mode-cache/cache/chef-stacktrace.out
[2018-01-04T11:46:13-08:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-01-04T11:46:13-08:00] FATAL: Chef::Exceptions::ValidationFailed: gem_package[my_gem] (issue_6708::default line 7) had an error: Chef::Exceptions::ValidationFailed: Property gem_binary must be one of: String!  You passed false.
```

**Comment by martinmosegaard** [comment]
Oh, and it told me where to find the stacktrace.out too :)

```
Generated at 2018-01-04 11:46:13 -0800
Chef::Exceptions::ValidationFailed: gem_package[my_gem] (issue_6708::default line 7) had an error: Chef::Exceptions::ValidationFailed: Property gem_binary must be one of: String!  You passed false.
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/mixin/params_validate.rb:431:in `_pv_is'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/mixin/params_validate.rb:107:in `block (2 levels) in validate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/mixin/params_validate.rb:104:in `each'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/mixin/params_validate.rb:104:in `block in validate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/mixin/params_validate.rb:94:in `each'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/mixin/params_validate.rb:94:in `validate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/property.rb:470:in `validate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/property.rb:677:in `coerce_and_validate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/property.rb:658:in `input_to_stored_value'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/property.rb:386:in `set'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/property.rb:283:in `call'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/property.rb:525:in `gem_binary'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/provider/package/rubygems.rb:390:in `initialize'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/resource.rb:1403:in `new'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/resource.rb:1403:in `provider_for_action'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/resource.rb:591:in `run_action'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/runner.rb:70:in `run_action'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/runner.rb:98:in `block (2 levels) in converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/runner.rb:98:in `each'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/runner.rb:98:in `block in converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/runner.rb:97:in `converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/client.rb:715:in `block in converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/client.rb:710:in `catch'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/client.rb:710:in `converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/client.rb:749:in `converge_and_save'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/client.rb:286:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/application.rb:273:in `run_with_graceful_exit_option'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/application.rb:249:in `block in run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/application.rb:232:in `run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/application/client.rb:457:in `loop'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/application/client.rb:457:in `interval_run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/application/client.rb:441:in `run_application'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chefdk/bin/chef-client:279:in `load'
C:/opscode/chefdk/bin/chef-client:279:in `<main>'

>>>> Caused by Chef::Exceptions::ValidationFailed: Property gem_binary must be one of: String!  You passed false.
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/mixin/params_validate.rb:431:in `_pv_is'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/mixin/params_validate.rb:107:in `block (2 levels) in validate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/mixin/params_validate.rb:104:in `each'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/mixin/params_validate.rb:104:in `block in validate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/mixin/params_validate.rb:94:in `each'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/mixin/params_validate.rb:94:in `validate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/property.rb:470:in `validate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/property.rb:677:in `coerce_and_validate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/property.rb:658:in `input_to_stored_value'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/property.rb:386:in `set'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/property.rb:283:in `call'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/property.rb:525:in `gem_binary'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/provider/package/rubygems.rb:390:in `initialize'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/resource.rb:1403:in `new'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/resource.rb:1403:in `provider_for_action'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/resource.rb:591:in `run_action'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/runner.rb:70:in `run_action'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/runner.rb:98:in `block (2 levels) in converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/runner.rb:98:in `each'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/runner.rb:98:in `block in converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/runner.rb:97:in `converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/client.rb:715:in `block in converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/client.rb:710:in `catch'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/client.rb:710:in `converge'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/client.rb:749:in `converge_and_save'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/client.rb:286:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/application.rb:273:in `run_with_graceful_exit_option'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/application.rb:249:in `block in run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/application.rb:232:in `run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/application/client.rb:457:in `loop'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/application/client.rb:457:in `interval_run_chef_client'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/application/client.rb:441:in `run_application'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chefdk/bin/chef-client:279:in `load'
C:/opscode/chefdk/bin/chef-client:279:in `<main>'
```

**Comment by martinmosegaard** [comment]
I looked in the git log and there is this notion of `nil` doing a get in Chef 12 but a set `value = nil` in Chef 13, as seen in https://github.com/chef/chef/commit/0d6c4462a6c88584ee8a2c8cedc0865c39880154#diff-92db9a9077f6d081e10802c53a4e849b

Then, in `gem_package.rb` the default for the `gem_binary` property seems to be `nil`, yet the only acceptable type is `String`.
https://github.com/chef/chef/blob/master/lib/chef/resource/gem_package.rb

Could it be that `nil` should be added as an acceptable type for `gem_binary`? As in:
`property :gem_binary, [ String, nil ], desired_state: false`

**Comment by martinmosegaard** [comment]
I tried editing my local version of `gem_package.rb` within `C:\opscode\chefdk\embedded\...` with the above. It changes the error message to:

```
Property gem_binary must be one of: String, nil!  You passed false.
```

**Comment by lamont-granquist** [comment]
so what is failing is this:

```
        def find_gem_by_path
          which("gem", extra_path: RbConfig::CONFIG["bindir"])
        end
```

gem_package is used to install gems into an external ruby instance, and it needs to be in your path or you need to give it the path to the binary.   if you're trying to install gems into chef itself you should use `chef_gem`.  otherwise, i think this is acting as designed its just a very poor error message.

**Comment by martinmosegaard** [comment]
In any case, the current behavior makes it quite hard to understand.

It is a poor error message and I hope it can be fixed in this repo.
It is _also_ poor documentation, because it says the `gem_binary` property is optional. I first tried to file a bug on `chef_web_docs`, but it was closed:

https://github.com/chef/chef-web-docs/issues/1169

@lamont-granquist could you perhaps talk to @brewn ?

**Comment by Techcadia** [comment]
I am also having this issue after upgrading from Chef 12 to Chef 14 and I don't see a resolution.

@martinmosegaard  Did you ever find a fix or workaround?

**Comment by Techcadia** [comment]
My Workaround  was to just statically set the path to the gem_binary
  ```gem_package 'bundler'```

```gem_package 'bundler' do
  gem_binary 'C:\\tools\\ruby23\\bin\\gem'
end```

The code provided above did not discover it correctly even though the $env:path contains the ruby dev
```
PS C:\> where.exe gem
C:\tools\ruby23\bin\gem
C:\tools\ruby23\bin\gem.cmd
```

**Comment by martinmosegaard** [comment]
I used the same workaround. Was mainly confused because of the documentation saying it was optional.

**Comment by lamont-granquist** [comment]
At a guess all I can think of is that the Chef which helper doesn't work with .cmd files?
