### ISSUE TITLE
knife rehash breaks subcommands that have a super-class

### ISSUE THREAD

**Issue by pdf** [chef/chef#6825]
## Description
In #4090 a special-case was added to handle ChefFS specifically, rather than fixing the general case. This leaves all other plugins that use a similar pattern broken after `knife rehash` is called.

## Chef Version
Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4

## Platform Version
Linux/OSX

## Replication Case
See #4089 #4090 and https://github.com/pdf/knife-attribute/issues/4

## Stacktrace
```
/home/user/.chefdk/gem/ruby/2.4.0/gems/knife-attribute-1.1.0/lib/knife-attribute/node/get.rb:4:in `<class:NodeAttributeGet>': uninitialized constant KnifeAttribute::Node::Helpers (NameError)
        from /home/user/.chefdk/gem/ruby/2.4.0/gems/knife-attribute-1.1.0/lib/knife-attribute/node/get.rb:3:in `<module:Node>'
        from /home/user/.chefdk/gem/ruby/2.4.0/gems/knife-attribute-1.1.0/lib/knife-attribute/node/get.rb:2:in `<module:KnifeAttribute>'
        from /home/user/.chefdk/gem/ruby/2.4.0/gems/knife-attribute-1.1.0/lib/knife-attribute/node/get.rb:1:in `<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife/core/hashed_command_loader.rb:80:in `load'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife/core/hashed_command_loader.rb:80:in `block in load_command'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife/core/hashed_command_loader.rb:78:in `each'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife/core/hashed_command_loader.rb:78:in `load_command'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife/core/subcommand_loader.rb:109:in `command_class_from'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife.rb:153:in `subcommand_class_from'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife.rb:214:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application/knife.rb:156:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/bin/knife:25:in `<top (required)>'
        from /usr/bin/knife:255:in `load'
        from /usr/bin/knife:255:in `<main>'
```

**Comment by edgeworthch** [comment]
I encountered something similar and I found that adding e.g. `require knife-attribute/node/helpers` to the plugin file seems to get the constant included.  That might work for your example here.
