### ISSUE TITLE
How do I resolve the below issue with chef-client using knife job

### ISSUE THREAD

**Issue by SrikarshVardhanreddyKolanu** [chef/chef#6864]
## Description

Am using below versions of chef client and chefdk
and when am running knife job start chef-client for client01 it's saying node not found but client01 is added as node to chef server. Could you please help me to solve this

## Chef Version

Chef Development Kit Version: 2.4.20
chef-client version: 13.6.4

## Platform Version

Linux localhost 2.6.32-696.18.7.el6.x86_64 #1 SMP Thu Dec 28 20:15:47 EST 2017 x86_64 x86_64 x86_64 GNU/Linux

## Replication Case

Installed chefdk and chef client versions mentioned above and then after bootstrapping a instance. Tried to run 
`knife job start chef-client client01` 
```
## Client Output
<!--- The relevant output of the chef-client run or a link to a gist of the entire run, if there is one.

ERROR: The object you are looking for could not be found
Response: <!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
  <title>Chef - 404 Not Found</title>
  <link media="all" rel="stylesheet" type="text/css" href="/css/all.css" />
  <!--[if lt IE 7]><link rel="stylesheet" type="text/css" href="/css/lt7.css" /><![endif]-->
</head>
<body>
  <div class="header-block">
    <div id="header">
      <strong class="logo"><a href="https://www.chef.io">Chef</a></strong>
    </div>
  </div>
  <div id="wrapper">
    <div id="main">
      <div class="mybox">
        <div id="content">
          <h1>404 - Not Found</h1>
          <p>Sorry, I can't find what you are looking for.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-block">
    <div id="footer">
      <div class="mybox">
      </div>
      <div class="footer-bottom">
        <span>&copy; 2010&thinsp;&ndash;&thinsp;2017 Chef Software, Inc. All Rights Reserved</span>
      </div>
    </div>
  </div>
</body>
</html>
```

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it. -->

`knife job start chef-client client01 -VV` 
```
INFO: Using configuration from /root/.chef/knife.rb
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request
DEBUG: Signing the request as admin
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::APIVersions#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating POST to https://localhost/organizations/org/pushy/jobs
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Content-Type: application/json
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-Ops-Server-API-Version: 1
DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.1;
DEBUG: X-OPS-USERID: admin
DEBUG: X-OPS-TIMESTAMP: 2018-02-17T00:02:17Z
DEBUG: X-OPS-CONTENT-HASH: D0r7xnP5YLy0ctYNNpQWSivoAGw=
DEBUG: X-OPS-AUTHORIZATION-1: Ue3JjX5cVrlBqs27oGuZz8+DV5OpEj7KV7+m3VTjP4giWQy0lGnR0tNeIvk7
DEBUG: X-OPS-AUTHORIZATION-2: kmUa/NA7osJIK27GXn0mn4AQupzgoDC4GSrosQ8C15QJnPq3Ma43qfIhYX/r
DEBUG: X-OPS-AUTHORIZATION-3: D/s09V60tfhE3qMKkFbGjEXVYM4q8clabqCFfmWjfkPHFeBNkNdAUINXX6e8
DEBUG: X-OPS-AUTHORIZATION-4: 2Vdu41f4kbJV8oFoxUd1l3YmAPu2pdp3N2MOk1X8sF89dbqKlzxIKbi0gMRw
DEBUG: X-OPS-AUTHORIZATION-5: +8kUSB/llHkeWvayuRrQxLSlisbkcTfHhGiZbDtd0K0nnQQkd1DVZSqROFRv
DEBUG: X-OPS-AUTHORIZATION-6: ffKto21VQtxXkdXyJB/xskYLMcT5QClsZiDsSRq9IQ==
DEBUG: HOST: localhost:443
DEBUG: X-REMOTE-REQUEST-ID: e56f65d8-78cc-4f51-a1ec-084772bbd807
DEBUG: Content-Length: 95
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: Using proxy.server.com:8099 for proxy
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 404 Not Found
DEBUG: server: openresty/1.11.2.1
DEBUG: date: Sat, 17 Feb 2018 00:02:17 GMT
DEBUG: content-type: text/html
DEBUG: transfer-encoding: chunked
DEBUG: connection: close
DEBUG: etag: W/"5a5fa509-43c"
DEBUG: content-encoding: gzip
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: ---- HTTP Response Body ----                                            ¯x!Q
DEBUG:TMÓ0½ï¯õ¡\pÝÂJ¥Ô´*EêÐî"V{p§±êØÁ6Í¿Çùêf ð%¶gæÍ{vøõÏëï_6c¡ã+Þ|à\hã##ï«ªjZ½"    XRùã¨NY[Ò }¨KI éVAyFÖD¯ É
ó£#fôöû<ßè×[º¶E)Píô8Õvm£(·
µ×¹ÌÂÍì>Y
         öhRÎ:¬a«9@!S%""´&à¤ÇZKK0ÐîÙ&ÞÈ
[H±}*´D.¡dåDYJ÷+B(óÌcD¿¨wö|AFÜûÏãÆK:v3ìµ]wñ½u®~ß
  y
)B

  ÚA8   ÚÚ  Û|Ñoï@f-þÉûÎ_   4d·¶
:dÖM9+Ã/í´*½                    åKaâIbËzofóÙse|¹Tø|5,´öÜÛ
«Æ$S¸ÕîÔ>GwÒKwái´I{9ÿ"gÝU
7³ýWü¶2Ð<
DEBUG: ---- End HTTP Response Body -----
DEBUG: ---- HTTP Request Body ----
DEBUG: {"command":"chef-client","nodes":["client01"],"quorum":1,"capture_output":false,"env":{}}
DEBUG: ---- End HTTP Request Body ----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: HTTP server did not include a Content-Length header in response, cannot identify truncated downloads.
DEBUG: Chef::HTTP calling Chef::HTTP::APIVersions#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Expected JSON response, but got content-type 'text/html'
DEBUG: Response body contains:
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
  <title>Chef - 404 Not Found</title>
  <link media="a [...truncated...]
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
/opt/chefdk/embedded/lib/ruby/2.4.0/net/http/response.rb:122:in `error!': 404 "Not Found" (Net::HTTPServerException)
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/http.rb:152:in `request'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/http.rb:131:in `post'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/knife-push-1.0.3/lib/chef/knife/job_helpers.rb:95:in `run_helper'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/knife-push-1.0.3/lib/chef/knife/job_start.rb:115:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife.rb:442:in `block in run_with_pretty_exceptions'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/local_mode.rb:44:in `with_server_connectivity'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife.rb:441:in `run_with_pretty_exceptions'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife.rb:219:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/application/knife.rb:156:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/bin/knife:25:in `<top (required)>'
        from /usr/bin/knife:255:in `load'
        from /usr/bin/knife:255:in `<main>'

```

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
