### ISSUE TITLE
etcd cookbook failing in the keys resource with Chef 14, but not 13

### ISSUE THREAD

**Issue by tas50** [chef/chef#6970]
In Chef 14.0.120 I'm seeing a validation failure for actions in etcd_keys, which is wrong and doesn't happen in Chef 13. 

```
Compiling Cookbooks...
================================================================================
Recipe Compile Error in /opt/kitchen/cache/cookbooks/etcd_test/recipes/keys.rb
================================================================================
Chef::Exceptions::ValidationFailed
----------------------------------
Option action must be equal to one of: nothing!  You passed :create.
Cookbook Trace:
---------------
  /opt/kitchen/cache/cookbooks/etcd_test/recipes/keys.rb:2:in `block in from_file'
  /opt/kitchen/cache/cookbooks/etcd_test/recipes/keys.rb:1:in `from_file'
Relevant File Content:
----------------------
/opt/kitchen/cache/cookbooks/etcd_test/recipes/keys.rb:
  1:  etcd_service 'default' do
  2>>   action [:create, :start]
  3:  end
  4:  
  5:  etcd_key '/test' do
  6:    value 'a_test_value'
  7:  end
  8:  
  9:  execute 'etcdctl set /delete delete' do
 10:    not_if { ::File.exist?('/marker_etcd_key_delete') }
 11:  end
System Info:
------------
chef_version=14.0.120
platform=centos
platform_version=7.4.1708
ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
program_name=/opt/chef/embedded/bin/chef-client
executable=/opt/chef/embedded/bin/chef-client
Running handlers:
[2018-03-09T21:26:55+00:00] ERROR: Running exception handlers
[2018-03-09T21:26:55+00:00] ERROR: Running exception handlers
Running handlers complete
[2018-03-09T21:26:55+00:00] ERROR: Exception handlers complete
[2018-03-09T21:26:55+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 05 seconds
[2018-03-09T21:26:55+00:00] FATAL: Stacktrace dumped to /opt/kitchen/cache/chef-stacktrace.out
[2018-03-09T21:26:55+00:00] FATAL: Stacktrace dumped to /opt/kitchen/cache/chef-stacktrace.out
[2018-03-09T21:26:55+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-03-09T21:26:55+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-03-09T21:26:55+00:00] FATAL: Chef::Exceptions::ValidationFailed: Option action must be equal to one of: nothing!  You passed :create.
[2018-03-09T21:26:55+00:00] FATAL: Chef::Exceptions::ValidationFailed: Option action must be equal to one of: nothing!  You passed :create.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <keys-centos-7>.  Please see .kitchen/logs/keys-centos-7.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
The command "KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}" exited with 20.
```

**Comment by lamont-granquist** [comment]
well that's etcd_service not etcd_keys, and that's a library-style cookbook.  

i'm guessing the issue is here:

https://github.com/chef-cookbooks/etcd/blob/master/libraries/etcd_service_base.rb#L14

the `resource_name :etcd_service` there has an implicit `provides :etcd_service` which will wire up the `EtcCookbook::EtcdServiceBase` class itself, which contains no actions.

what changed in 14 is that we're not sorting alphabetically and switched to last-writer wins, so that probably made this class win in certain situations rather than the class it gets mixed into.

the solution is likely deleting that line.

**Comment by lamont-granquist** [comment]
fixed properly here:  https://github.com/chef-cookbooks/etcd/pull/86
