### ISSUE TITLE
Knife Bootstrap LocalMode fails on Guest System

### ISSUE THREAD

**Issue by darkn3rd** [chef/chef#7052]
## Description

I am unable to bootstrap local VM guests using knife, and trying to use `knife bootstrap -z`  for this.  

I couldn't not find easy solution path on this with the documentation, except for chef-zero docs and two blogs on chef local mode.  Guessing chef zero in-memory server is not launched on the guest system, and not obvious guest chef-client to use it.

The use case is for local virtual guests, don't want to register them on a full online Chef Server, as these are temporary disposable development systems.

## Chef Version

* **host system**: `Chef: 13.4.19`
* **guest system**: `Chef: 13.8.5`

## Platform Version

* **host system**: Ubuntu 16.04
* **guest system**: Ubuntu 14.04

## Replication Case

1. `knife bootstrap tools.dev --node-name tools.dev --environment dev --ssh-user vagrant --sudo -z`

**SSH Config for Knife**

```bash
$ cat ~/.ssh/config
Host tools.dev
  HostName 172.16.0.30
  User vagrant
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /path/to/project/.vagrant/machines/tools.dev/virtualbox/private_key
  IdentitiesOnly yes
  LogLevel FATAL
```

**.chef/knife.rb Config**

```ruby
chef_repo = File.join(File.dirname(__FILE__), '../ninjapants-chef-repo')

chef_server_url "http://127.0.0.1:8889"
node_name       "vagrant"
client_key      File.join(File.dirname(__FILE__), "vagrant.pem")
cookbook_path   "#{chef_repo}/cookbooks"
cache_type      "BasicFile"
cache_options :path => "#{chef_repo}/checksums"
```

**Vagrant Environment**

Any virtual guest running on dev system would likely work. Here's the vagrant/virtualbox combination I used:

```ruby
TIME = Time.now.strftime('%Y%m%dT%H%M%S')
VAGRANT_BOX = 'bento/ubuntu-14.04'
CONFIGFILE_HOSTS='./config/hosts'

# build hosts hash
hosts = {}
File.readlines(CONFIGFILE_HOSTS).map(&:chomp).each do |line|
  ipaddr, hostname = line.split(/\s+/)             # only grab first two columns
  hosts[hostname] = ipaddr                         # store in hash
  PRIMARY_SYSTEM = hostname if (line =~ /primary/) # match primary
end

Vagrant.configure('2') do |config|
  hosts.each do |hostname, ipaddr|
    default = if hostname == PRIMARY_SYSTEM then true else false end
    config.vm.define hostname, primary: default do |node|
      node.vm.box = VAGRANT_BOX
      node.vm.hostname = hostname
      node.vm.network 'private_network', ip: ipaddr
      node.vm.provider('virtualbox') do |vbox|
        vbox.name = "#{hostname}_#{TIME}"
      end
    end
  end
end
```
```bash
$ cat config/hosts
172.16.0.30	tools.dev	primary
```

## Client Output

```
Doing old-style registration with the validation key at ...
Delete your validation key in order to use your user credentials instead

Connecting to tools.dev
tools.dev -----> Installing Chef Omnibus (-v 13)
tools.dev downloading https://omnitruck-direct.chef.io/chef/install.sh
tools.dev   to file /tmp/install.sh.1828/install.sh
tools.dev trying wget...
tools.dev ubuntu 14.04 x86_64
tools.dev Getting information for chef stable 13 for ubuntu...
tools.dev downloading https://omnitruck-direct.chef.io/stable/chef/metadata?v=13&p=ubuntu&pv=14.04&m=x86_64
tools.dev   to file /tmp/install.sh.1832/metadata.txt
tools.dev trying wget...
tools.dev sha1	1ecb70effcf557dbac0d0de528bbef6937f9c581
tools.dev sha256	ce0ff3baf39c8c13ed474104928e7e4568a4997a1d5797cae2b2ba3ee001e3a8
tools.dev url	https://packages.chef.io/files/stable/chef/13.8.5/ubuntu/14.04/chef_13.8.5-1_amd64.deb
tools.dev version	13.8.5
tools.dev downloaded metadata file looks valid...
tools.dev downloading https://packages.chef.io/files/stable/chef/13.8.5/ubuntu/14.04/chef_13.8.5-1_amd64.deb
tools.dev   to file /tmp/install.sh.1832/chef_13.8.5-1_amd64.deb
tools.dev trying wget...
tools.dev Comparing checksum with sha256sum...
tools.dev Installing chef 13
tools.dev installing with dpkg...
tools.dev Selecting previously unselected package chef.
(Reading database ... 34772 files and directories currently installed.)
tools.dev Preparing to unpack .../chef_13.8.5-1_amd64.deb ...
tools.dev Unpacking chef (13.8.5-1) ...
tools.dev Setting up chef (13.8.5-1) ...
tools.dev Thank you for installing Chef!
tools.dev Starting the first Chef Client run...
tools.dev Starting Chef Client, version 13.8.5
tools.dev Creating a new client identity for tools.dev using the validator key.
tools.dev 
tools.dev ================================================================================
tools.dev Chef encountered an error attempting to create the client "tools.dev"
tools.dev ================================================================================
tools.dev 
tools.dev System Info:
tools.dev ------------
tools.dev chef_version=13.8.5
tools.dev ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
tools.dev program_name=chef-client worker: ppid=1907;start=01:07:34;
tools.dev executable=/opt/chef/bin/chef-client
tools.dev 
tools.dev 
tools.dev Running handlers:
tools.dev [2018-03-25T01:07:36+00:00] ERROR: Running exception handlers
tools.dev Running handlers complete
tools.dev [2018-03-25T01:07:36+00:00] ERROR: Exception handlers complete
tools.dev Chef Client failed. 0 resources updated in 01 seconds
tools.dev [2018-03-25T01:07:36+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
tools.dev [2018-03-25T01:07:36+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
tools.dev [2018-03-25T01:07:36+00:00] ERROR: No socketless chef-zero server on given port 1
tools.dev [2018-03-25T01:07:36+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

## Stacktrace
```
ChefZero::ServerNotFound: No socketless chef-zero server on given port 1
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.1.0/lib/chef_zero/socketless_server_map.rb:86:in `request'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.1.0/lib/chef_zero/socketless_server_map.rb:33:in `request'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/http/socketless_chef_zero_client.rb:154:in `request'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/http.rb:372:in `block in send_http_request'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/http.rb:404:in `block in retrying_http_errors'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/http.rb:402:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/http.rb:402:in `retrying_http_errors'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/http.rb:365:in `send_http_request'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/http.rb:149:in `request'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/http.rb:131:in `post'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/api_client/registration.rb:96:in `create'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/api_client/registration.rb:87:in `create_or_update'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/api_client/registration.rb:58:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/client.rb:669:in `register'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/client.rb:267:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application.rb:292:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application.rb:280:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application.rb:280:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application.rb:245:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application.rb:233:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application/client.rb:457:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application/client.rb:457:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application/client.rb:441:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:59:in `load'
/usr/bin/chef-client:59:in `<main>'
```

**Comment by darkn3rd** [comment]
Two this is both a 1+ bugs and enhancement request:

* ***bug***: `local-mode` option has two different meanings with Chef tools, (1) use chef-zero server, (2) edit files locally.  This causes confusion.  Maybe have `--local-edit` instead.
* ***bug***: `knife bootstrap --local-mode` is **not** supported, and a stacktrace is perhaps not optimal user feedback for that.
* ***enhancement***: would be to support this facility, which is essentially use the same process that the plug-in knife-zero uses.

**Comment by tas50** [comment]
In Chef Infra Client 15 we entirely reworked the bootstrapping code in knife. It's entirely possible that this is no longer and issue. I'm going to close this out. If someone runs into this with Chef Infra Client 15 or later feel free to open a new issue and link it back to this one.
