### ISSUE TITLE
Chef local-mode on Windows fails when run as a non-Administrator user

### ISSUE THREAD

**Issue by shoreadmin** [chef/chef#7110]
## Description
We currently use chef (on Windows 7 x64) in local mode to configure developer workstations.  We run this in 2 phases; first as an administrator installing applications and configuring system-level settings, and then as the local user configuring local user settings.

This worked fine in 12.11.18-1, however a recent (attempted) upgrade to 13.8.5-1 has tightened up security, amongst other things, setting administrator privileges on the "nodes" directory (done as part of #5781?).  

This works fine, as long as the user is an administrator themselves.  When running as a standard local user the attempt to alter the acl fails with an "Access is denied" (NOTE: I made sure that there was no existing "nodes" directory in existence at the time I ran the user script).

## Chef Version
13.8.5-1

## Platform Version
Windows 7 x64

## Replication Case
Any chef recipe run in local-mode NOT as an administrator

## Client Output/Stacktrace
```
Starting Chef Client, version 13.8.5
[2018-04-03T14:01:58+10:00] ERROR: #<Chef::Exceptions::Win32APIError: Access is denied.
---- Begin Win32 API output ----
System Error Code: 5
System Error Message: Access is denied.
---- End Win32 API output ----
>
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/win32/error.rb:81:in `raise!'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/win32/security.rb:541:in `set_named_security_info'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/win32/security/securable_object.rb:91:in `block in owner='
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/win32/security.rb:620:in `with_privileges'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/win32/security/securable_object.rb:90:in `owner='
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/chef_fs/file_system/repository/chef_repository_file_system_root_dir.rb:123:in `block in create_child'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/chef_fs/file_system/repository/chef_repository_file_system_root_dir.rb:111:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/chef_fs/file_system/repository/chef_repository_file_system_root_dir.rb:111:in `create_child'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/chef_fs/chef_fs_data_store.rb:820:in `get_dir'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/chef_fs/chef_fs_data_store.rb:794:in `with_parent_dir'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/chef_fs/chef_fs_data_store.rb:253:in `create'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.1.0/lib/chef_zero/data_store/v1_to_v2_adapter.rb:34:in `block in create'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.1.0/lib/chef_zero/data_store/v1_to_v2_adapter.rb:113:in `fix_exceptions'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.1.0/lib/chef_zero/data_store/v1_to_v2_adapter.rb:33:in `create'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.1.0/lib/chef_zero/rest_base.rb:180:in `create_data'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.1.0/lib/chef_zero/endpoints/rest_list_endpoint.rb:31:in `post'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.1.0/lib/chef_zero/endpoints/nodes_endpoint.rb:24:in `post'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.1.0/lib/chef_zero/rest_base.rb:59:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.1.0/lib/chef_zero/rest_router.rb:24:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.1.0/lib/chef_zero/server.rb:665:in `block in app'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.1.0/lib/chef_zero/server.rb:336:in `handle_socketless_request'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.1.0/lib/chef_zero/socketless_server_map.rb:87:in `request'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-zero-13.1.0/lib/chef_zero/socketless_server_map.rb:33:in `request'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/http/socketless_chef_zero_client.rb:154:in `request'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/http.rb:372:in `block in send_http_request'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/http.rb:404:in `block in retrying_http_errors'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/http.rb:402:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/http.rb:402:in `retrying_http_errors'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/http.rb:365:in `send_http_request'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/http.rb:149:in `request'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/http.rb:131:in `post'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/node.rb:610:in `create'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/node.rb:568:in `rescue in find_or_create'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/node.rb:563:in `find_or_create'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/policy_builder/dynamic.rb:72:in `load_node'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/client.rb:470:in `load_node'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/client.rb:270:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/application.rb:274:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/application.rb:250:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/application.rb:233:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/application/client.rb:457:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/application/client.rb:457:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/application/client.rb:441:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:59:in `load'
C:/opscode/chef/bin/chef-client:59:in `<main>'
```

**Comment by shoreadmin** [comment]
I suspect that running chef as a non-administrator is a supported use-case?
 
If so, a potential solution for this would just be to simply check if the user is an administrator before attempting to alter the ACLs.

**Comment by darkn3rd** [comment]
Example recipe?  Do you run it from PowerShell? CMD?  Wondering if you would have different experience with `chef-client --local -u $user`

**Comment by shoreadmin** [comment]
I'm not sure running it from powershell or CMD would make a difference.  The issue appears to be that chef  now attempts to perform an operation that requires elevated privileges, regardless of whether the user executing chef actually has them!  

Here's a test recipe for you:

execute "echo message" do
  command "echo 'Hello World'"
  action :run
end
