### ISSUE TITLE
String / array conundrum

### ISSUE THREAD

**Issue by sandstrom** [chef/chef#7115]
## Description

I've tried this snippet (in two versions), passing the key as either a string or an array (not both at the same time of course, only one key, either a string or an array):

```ruby
apt_repository "elastic-6.x" do
  uri          "https://artifacts.elastic.co/packages/6.x/apt"
  distribution 'stable'
  components   ['main']
  key          "https://artifacts.elastic.co/GPG-KEY-elasticsearch" # ALT1
  key          ["https://artifacts.elastic.co/GPG-KEY-elasticsearch"] # ALT2
end
```

## Error when key is a string (ALT1)

```
>>>> Caused by NoMethodError: undefined method `each' for "https://artifacts.elastic.co/GPG-KEY-elasticsearch":String
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/provider/apt_repository.rb:41:in `block in <class:AptRepository>'
(eval):2:in `block in action_add'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/provider.rb:231:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/provider.rb:231:in `compile_and_converge_action'
(eval):2:in `action_add'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/provider.rb:177:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/resource.rb:594:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/runner.rb:70:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/runner.rb:98:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/runner.rb:98:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/runner.rb:98:in `block in converge'
```

## Error when key is an array (ALT2):

```
Chef::Exceptions::ValidationFailed: Option key must be a kind of [String]!  You passed ["https://artifacts.elastic.co/GPG-KEY-elasticsearch"].
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/mixin/params_validate.rb:196:in `_pv_kind_of'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/mixin/params_validate.rb:113:in `block (2 levels) in validate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/mixin/params_validate.rb:110:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/mixin/params_validate.rb:110:in `block in validate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/mixin/params_validate.rb:98:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/mixin/params_validate.rb:98:in `validate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/property.rb:492:in `validate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/property.rb:702:in `coerce_and_validate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/property.rb:685:in `input_to_stored_value'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/property.rb:404:in `set'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/property.rb:326:in `call'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/property.rb:547:in `key'
/var/chef/cache/cookbooks/elastic_search/recipes/default.rb:35:in `block in from_file'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/resource_builder.rb:66:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/resource_builder.rb:66:in `build'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/dsl/declare_resource.rb:293:in `build_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/dsl/declare_resource.rb:250:in `declare_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/dsl/resources.rb:38:in `apt_repository'
/var/chef/cache/cookbooks/elastic_search/recipes/default.rb:31:in `from_file'
```

## Misc info
These lines in the source code should be relevant:

https://github.com/chef/chef/blob/master/lib/chef/provider/apt_repository.rb#L41
https://github.com/chef/chef/blob/v14.0.190/lib/chef/resource/apt_repository.rb#L49

- Chef version: 14.0.190
- Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-103-generic x86_64)
- Running under Vagrant 1.9.1

**Comment by robbkidd** [comment]
I am not able to reproduce this error.


```
> chef --version
Chef Development Kit Version: 2.5.3
chef-client version: 13.8.5
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.20.0
inspec version: 1.51.21

> vagrant --version
Vagrant 2.0.3

> kitchen test ubuntu-1604
-----> Creating <linux-ubuntu-1604>...
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'bento/ubuntu-16.04'...
...
Starting Chef Client, version 14.0.190
...
```

### ALT1 - key as string

```
apt_repository "elastic-6.x" do
  uri "https://artifacts.elastic.co/packages/6.x/apt"
  distribution 'stable'
  components ['main']
  key "https://artifacts.elastic.co/GPG-KEY-elasticsearch" # ALT1
end
```

```
* apt_repository[elastic-6.x] action add
  * remote_file[/tmp/kitchen/cache/https___artifacts_elastic_co_GPG-KEY-elasticsearch] action create
    - create new file /tmp/kitchen/cache/https___artifacts_elastic_co_GPG-KEY-elasticsearch
    - update content in file /tmp/kitchen/cache/https___artifacts_elastic_co_GPG-KEY-elasticsearch from none to 10e406
    --- /tmp/kitchen/cache/https___artifacts_elastic_co_GPG-KEY-elasticsearch	2018-04-04 12:23:17.577262549 +0000
    +++ /tmp/kitchen/cache/.chef-https___artifacts_elastic_co_GPG-KEY-elasticsearch20180404-1739-fz0c9l	2018-04-04 12:23:17.549248550 +0000
    @@ -1 +1,32 @@
    +-----BEGIN PGP PUBLIC KEY BLOCK-----
    +Version: GnuPG v2.0.14 (GNU/Linux)
    + [... key snipped ...]
    +-----END PGP PUBLIC KEY BLOCK-----
    - change mode from '' to '0644'
  * execute[apt-key add /tmp/kitchen/cache/https___artifacts_elastic_co_GPG-KEY-elasticsearch] action run
    - execute apt-key add /tmp/kitchen/cache/https___artifacts_elastic_co_GPG-KEY-elasticsearch
  * execute[apt-cache gencaches] action run
    - execute apt-cache gencaches
  * execute[apt-cache gencaches] action nothing (skipped due to action :nothing)
  * apt_update[elastic-6.x] action nothing (skipped due to action :nothing)
  * file[/etc/apt/sources.list.d/elastic-6.x.list] action create
    - create new file /etc/apt/sources.list.d/elastic-6.x.list
    - update content in file /etc/apt/sources.list.d/elastic-6.x.list from none to 691778
    --- /etc/apt/sources.list.d/elastic-6.x.list	2018-04-04 12:23:17.873410538 +0000
    +++ /etc/apt/sources.list.d/.chef-elastic-620180404-1739-5ytcpr.x.list	2018-04-04 12:23:17.873410538 +0000
    @@ -1 +1,2 @@
    +deb      "https://artifacts.elastic.co/packages/6.x/apt" stable main
    - change mode from '' to '0644'
    - change owner from '' to 'root'
    - change group from '' to 'root'
  * execute[apt-cache gencaches] action run
    - execute apt-cache gencaches
  * apt_update[elastic-6.x] action update
    - force update new lists of packages
    * directory[/var/lib/apt/periodic] action create (up to date)
    * directory[/etc/apt/apt.conf.d] action create (up to date)
    * file[/etc/apt/apt.conf.d/15update-stamp] action create_if_missing (up to date)
    * execute[apt-get -q update] action run
 execute apt-get -q update
```

### ALT2 - key as array of strings

```
apt_repository "elastic-6.x" do
  uri "https://artifacts.elastic.co/packages/6.x/apt"
  distribution 'stable'
  components ['main']
  key ["https://artifacts.elastic.co/GPG-KEY-elasticsearch"] # ALT2
end
```

```
 * apt_repository[elastic-6.x] action add
   * remote_file[/tmp/kitchen/cache/https___artifacts_elastic_co_GPG-KEY-elasticsearch] action create
     - create new file /tmp/kitchen/cache/https___artifacts_elastic_co_GPG-KEY-elasticsearch
     - update content in file /tmp/kitchen/cache/https___artifacts_elastic_co_GPG-KEY-elasticsearch from none to 10e406
     --- /tmp/kitchen/cache/https___artifacts_elastic_co_GPG-KEY-elasticsearch  2018-04-04 12:06:29.136016661 +0000
     +++ /tmp/kitchen/cache/.chef-https___artifacts_elastic_co_GPG-KEY-elasticsearch20180404-1744-owkjk 2018-04-04 12:06:29.108002662 +0000
     @@ -1 +1,32 @@
     +-----BEGIN PGP PUBLIC KEY BLOCK-----
     +Version: GnuPG v2.0.14 (GNU/Linux)
     + [... key snipped ...]
     +-----END PGP PUBLIC KEY BLOCK-----
     - change mode from '' to '0644'
   * execute[apt-key add /tmp/kitchen/cache/https___artifacts_elastic_co_GPG-KEY-elasticsearch] action run
     - execute apt-key add /tmp/kitchen/cache/https___artifacts_elastic_co_GPG-KEY-elasticsearch
   * execute[apt-cache gencaches] action run
     - execute apt-cache gencaches
   * execute[apt-cache gencaches] action nothing (skipped due to action :nothing)
   * apt_update[elastic-6.x] action nothing (skipped due to action :nothing)
   * file[/etc/apt/sources.list.d/elastic-6.x.list] action create
     - create new file /etc/apt/sources.list.d/elastic-6.x.list
     - update content in file /etc/apt/sources.list.d/elastic-6.x.list from none to 691778
     --- /etc/apt/sources.list.d/elastic-6.x.list       2018-04-04 12:06:29.436166650 +0000
     +++ /etc/apt/sources.list.d/.chef-elastic-620180404-1744-1r25y7u.x.list    2018-04-04 12:06:29.436166650 +0000
     @@ -1 +1,2 @@
     +deb      "https://artifacts.elastic.co/packages/6.x/apt" stable main
     - change mode from '' to '0644'
     - change owner from '' to 'root'
     - change group from '' to 'root'
   * execute[apt-cache gencaches] action run
     - execute apt-cache gencaches
   * apt_update[elastic-6.x] action update
     - force update new lists of packages
     * directory[/var/lib/apt/periodic] action create (up to date)
     * directory[/etc/apt/apt.conf.d] action create (up to date)
     * file[/etc/apt/apt.conf.d/15update-stamp] action create_if_missing (up to date)
     * execute[apt-get -q update] action run
- execute apt-get -q update```

**Comment by tas50** [comment]
@sandstrom Any chance you have the apt cookbook in your runlist? If so what version do you have? I believe that #7134 might be the fix here, but updating to the latest apt cookbook would fix it as well in this case.
