### ISSUE TITLE
Chef14: property_is_set? error out

### ISSUE THREAD

**Issue by zopanix** [chef/chef#7116]
## Description
All my cookbooks using property_is_set? method in a custom resource are failing since on chef 14

## Chef Version
sha1	1e8019cf630e8a7c6287e1b950ddeecbe042d554
sha256	26c31070a71309709ed1d19b796ad0b47a283c5c21930906f19e0771a5dd1c1b
url	https://packages.chef.io/files/stable/chef/14.0.190/ubuntu/16.04/chef_14.0.190-1_amd64.deb
version	14.0.190

## Platform Version
debian8
debian9
ubuntu1604
ubuntu1404
rhel7
centos7
win2008r2
win2012r2
win2016

## Replication Case
Use a cookbook with a custom resource that uses the propert_is_set method on one of the properties.

## Client Output

```         
* adjoin_fx[default] action join
           
           ================================================================================
           Error executing action `join` on resource 'adjoin_fx[default]'
           ================================================================================
           
           NoMethodError
           -------------
           undefined method `property_is_set?' for #<#<Class:0x0000000003494ca8>:0x00000000032d31d0>
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/adjoin_fx/resources/adjoin_fx_rhel.rb:53:in `block in class_from_file'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/adjoin_fx/recipes/kitchen.rb
           
            14: adjoin_fx 'default' do
            15:   username   node['adjoin_fx']['username']
            16:   domain     node['adjoin_fx']['domain']
            17:   password   node['adjoin_fx']['password']
            18:   server     node['adjoin_fx']['server']
            19:   os_name    node['platform']              if node['platform_family'] == 'rhel'
            20:   os_version node['platform_version']      if node['platform_family'] == 'rhel'
            21:   action     :join
            22: end
            23: 
            24: adjoin_fx_configure 'default' do
            25:   domain       node['adjoin_fx']['domain']
            26:   login_groups node['adjoin_fx']['login_groups']
            27:   login_users  node['adjoin_fx']['login_users']
            28:   action       :configure
            29: end unless node['platform_family'] == 'windows'
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/adjoin_fx/recipes/kitchen.rb:14:in `from_file'
           
           adjoin_fx("default") do
             action [:join]
             default_guard_interpreter :default
             declared_type :adjoin_fx
             cookbook_name "adjoin_fx"
             recipe_name "kitchen"
             username "JoinDomain"
             domain "c.dazzlingwrench.internal"
             password "*sensitive value suppressed*"
             server "activedirectory.c.dazzlingwrench.internal"
             os_name "redhat"
             os_version "7.4"
           end
           
           System Info:
           ------------
           chef_version=14.0.190
           platform=redhat
           platform_version=7.4
           ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
           program_name=/opt/chef/bin/chef-client
           executable=/opt/chef/bin/chef-client
           
       
       Running handlers:
       [2018-04-04T14:04:05+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2018-04-04T14:04:05+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 02 seconds
       [2018-04-04T14:04:05+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-04-04T14:04:05+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-04-04T14:04:05+00:00] FATAL: NoMethodError: adjoin_fx[default] (adjoin_fx::kitchen line 14) had an error: NoMethodError: undefined method `property_is_set?' for #<#<Class:0x0000000003494ca8>:0x00000000032d31d0>
```

## Stacktrace
I don't have the stacktrace right now

**Comment by lamont-granquist** [comment]
probably going to need the `/tmp/kitchen/cache/chef-stacktrace.out` contents and a pointer to the cookbook code if its public

**Comment by wheatevo** [comment]
I was seeing a similar issue as well. I ended up changing my `property_is_set?(:values) calls to just check for the value of `new_resource.values` for now.

**Comment by zopanix** [comment]
Hey, just posting the chef-stacktrace
```
[kitchenuser@tk-rhel-centos7-d076cc cache]$ sudo cat chef-stacktrace.out 
Generated at 2018-04-05 15:30:55 +0000
NoMethodError: adjoin_fx[default] (adjoin_fx::kitchen line 14) had an error: NoMethodError: undefined method `property_is_set?' for #<#<Class:0x00000000031931f8>:0x0000000002fddcc8>
/tmp/kitchen/cache/cookbooks/adjoin_fx/resources/adjoin_fx_rhel.rb:53:in `block in class_from_file'
(eval):2:in `block in action_join'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/provider.rb:231:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/provider.rb:231:in `compile_and_converge_action'
(eval):2:in `action_join'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/provider.rb:177:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/resource.rb:594:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/runner.rb:70:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/runner.rb:98:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/runner.rb:98:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/runner.rb:98:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/runner.rb:97:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/client.rb:717:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/client.rb:712:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/client.rb:712:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/client.rb:751:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/client.rb:283:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/application.rb:279:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/application.rb:261:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/application/client.rb:440:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/bin/chef-client:26:in `<top (required)>'
/opt/chef/bin/chef-client:59:in `load'
/opt/chef/bin/chef-client:59:in `<main>'
```

**Comment by zopanix** [comment]
@lamont-granquist : Btw, if you wanna have a look at the cookbook, it's on the supermarket: adjoin_fx I'm using the latest version.

**Comment by zopanix** [comment]
@wheatevo : I understand your use case, we're still on chef 13 on our infra (this error is just because our tests play automatically on latest version of chef and we upgrade only when everything passes so no hurry for me, but I would imagine this will cause some problems for a lot of cookbooks since it's oftenly used)

**Comment by wheatevo** [comment]
Not sure if this helps in investigation, but I found that using `new_resource.property_is_set?(:values)` worked successfully while `property_is_set(:values)` did not. Guessing the issue has something to do with the new changes to require `new_resource.PROPERTY` though it might be entirely unrelated.

**Comment by lamont-granquist** [comment]
Ah, this makes sense.

That is a side effect of this:  https://github.com/chef/chef/pull/6952

Specifically the line which excludes the Chef::Resource.instance methods.  Most of those methods make no damn sense to be called from the provider directly and magically (there were probably 50-100 methods that were yanked out, this was just lost in a long list of things that made no sense at all).

I don't find this one to be that bad though.  I'll submit a PR to reinstate it and see what people think.

**Comment by zopanix** [comment]
Hey, I don't really mind this changing, just needs to be documented. In my opinion, since t wasn't a chef deprecation, it should still exist in Chef14, and might be deprecated for Chef15. On the other hand, might as well pull the bandaid off right now and get it over with ^^

**Comment by lamont-granquist** [comment]
Yeah, you'll get some argument from me on that.

The change that I made which caused this was this one line:

https://github.com/chef/chef/pull/6952/files#diff-31a0474b150c23d5e0e8669133fce6d9R354

That does not obviously have anything to do with `property_is_set?` so it never would have occurred to me to deprecate it in Chef-13.  If that was the right thing to do for 14, it sets up a game of "gotcha!" where if I'm just not smart enough to figure out every possible implication of every change it leads to perverse things being done -- during a major release where we're supposed to be able to make breaking changes -- and everything starts to slip and we start do perverse coding to work around not just ripping the band aid off.  It'd be better to add a new deprecation warning to the next maintenance release of Chef-13 -- then a month later people can upgrade to that version of Chef-13 and fix the deprecations and work correctly on Chef-14.

But I don't have a problem with reinstating the API per #7122 since it doesn't seem to hurt anything, and it can be put back in a much less magical and more straightforward to read manner -- so I don't think we need to have that discussion...

**Comment by zopanix** [comment]
@lamont-granquist : Sure, I'll follow your pull request and see what happen to it and how things are resolved. Taking action accordingly once the matter is resolved
