### ISSUE TITLE
Chef14:  Poise tests broke

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#7124]
```
Failures:
  1) Poise::Helpers::LWRPPolyfill Poise::Helpers::LWRPPolyfill::Provider load_current_resource override with no new_resource 
     Failure/Error: subject { provider(:poise_test).new(nil, nil).load_current_resource }
     NoMethodError:
       undefined method `name' for nil:NilClass
     # /home/travis/.rvm/gems/ruby-2.5.1/gems/chef-14.0.190/lib/chef/provider.rb:97:in `initialize'
     # ./test/spec/helpers/lwrp_polyfill_spec.rb:148:in `new'
     # ./test/spec/helpers/lwrp_polyfill_spec.rb:148:in `block (5 levels) in <top (required)>'
     # ./test/spec/helpers/lwrp_polyfill_spec.rb:149:in `block (5 levels) in <top (required)>'
  2) Poise::Helpers::LWRPPolyfill Poise::Helpers::LWRPPolyfill::Provider load_current_resource override with no new_resource 
     Failure/Error: subject { provider(:poise_test).new(nil, nil).load_current_resource }
     NoMethodError:
       undefined method `name' for nil:NilClass
     # /home/travis/.rvm/gems/ruby-2.5.1/gems/chef-14.0.190/lib/chef/provider.rb:97:in `initialize'
     # ./test/spec/helpers/lwrp_polyfill_spec.rb:148:in `new'
     # ./test/spec/helpers/lwrp_polyfill_spec.rb:148:in `block (5 levels) in <top (required)>'
     # ./test/spec/helpers/lwrp_polyfill_spec.rb:150:in `block (5 levels) in <top (required)>'
  3) Poise::Helpers::DefinedIn#poise_defined_in_cookbook 
     Failure/Error: subject { resource(:poise_test).new('test', run_context) }
       #<Double "run context"> received unexpected message :logger with (no args)
     # /home/travis/.rvm/gems/ruby-2.5.1/gems/chef-14.0.190/lib/chef/resource.rb:136:in `initialize'
     # /home/travis/.rvm/gems/ruby-2.5.1/gems/chefspec-7.1.2/lib/chefspec/extensions/chef/resource.rb:42:in `initialize'
     # ./test/spec/helpers/defined_in_spec.rb:56:in `new'
     # ./test/spec/helpers/defined_in_spec.rb:56:in `block (3 levels) in <top (required)>'
     # ./test/spec/helpers/defined_in_spec.rb:58:in `block (3 levels) in <top (required)>'
Finished in 4 minutes 27.8 seconds (files took 22.88 seconds to load)
427 examples, 3 failures
Failed examples:
rspec ./test/spec/helpers/lwrp_polyfill_spec.rb:149 # Poise::Helpers::LWRPPolyfill Poise::Helpers::LWRPPolyfill::Provider load_current_resource override with no new_resource 
rspec ./test/spec/helpers/lwrp_polyfill_spec.rb:150 # Poise::Helpers::LWRPPolyfill Poise::Helpers::LWRPPolyfill::Provider load_current_resource override with no new_resource 
rspec ./test/spec/helpers/defined_in_spec.rb:57 # Poise::Helpers::DefinedIn#poise_defined_in_cookbook 
```

**Comment by coderanger** [comment]
Welp.
