### ISSUE TITLE
Chef14:  knife-windows tests broke

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#7125]
```
Failures:
  1) Chef::Knife::Bootstrap when compared to BootstrapWindowsWinrm uses the same long-name
     Failure/Error: expected = bootstrap.options[win_key][sym]
     NoMethodError:
       undefined method `[]' for nil:NilClass
     Shared Example Group: "compare_options" called from ./spec/unit/knife/bootstrap_options_spec.rb:125
     # ./spec/unit/knife/bootstrap_options_spec.rb:36:in `block in compare_property'
     # ./spec/unit/knife/bootstrap_options_spec.rb:33:in `each'
     # ./spec/unit/knife/bootstrap_options_spec.rb:33:in `compare_property'
     # ./spec/unit/knife/bootstrap_options_spec.rb:55:in `block (3 levels) in <top (required)>'
  2) Chef::Knife::Bootstrap when compared to BootstrapWindowsWinrm uses the same short-name
     Failure/Error: expected = bootstrap.options[win_key][sym]
     NoMethodError:
       undefined method `[]' for nil:NilClass
     Shared Example Group: "compare_options" called from ./spec/unit/knife/bootstrap_options_spec.rb:125
     # ./spec/unit/knife/bootstrap_options_spec.rb:36:in `block in compare_property'
     # ./spec/unit/knife/bootstrap_options_spec.rb:33:in `each'
     # ./spec/unit/knife/bootstrap_options_spec.rb:33:in `compare_property'
     # ./spec/unit/knife/bootstrap_options_spec.rb:59:in `block (3 levels) in <top (required)>'
  3) Chef::Knife::Bootstrap when compared to BootstrapWindowsWinrm uses the same description
     Failure/Error: expected = bootstrap.options[win_key][sym]
     NoMethodError:
       undefined method `[]' for nil:NilClass
     Shared Example Group: "compare_options" called from ./spec/unit/knife/bootstrap_options_spec.rb:125
     # ./spec/unit/knife/bootstrap_options_spec.rb:36:in `block in compare_property'
     # ./spec/unit/knife/bootstrap_options_spec.rb:33:in `each'
     # ./spec/unit/knife/bootstrap_options_spec.rb:33:in `compare_property'
     # ./spec/unit/knife/bootstrap_options_spec.rb:63:in `block (3 levels) in <top (required)>'
  4) Chef::Knife::Bootstrap when compared to BootstrapWindowsWinrm uses the same default value
     Failure/Error: expected = bootstrap.options[win_key][sym]
     NoMethodError:
       undefined method `[]' for nil:NilClass
     Shared Example Group: "compare_options" called from ./spec/unit/knife/bootstrap_options_spec.rb:125
     # ./spec/unit/knife/bootstrap_options_spec.rb:36:in `block in compare_property'
     # ./spec/unit/knife/bootstrap_options_spec.rb:33:in `each'
     # ./spec/unit/knife/bootstrap_options_spec.rb:33:in `compare_property'
     # ./spec/unit/knife/bootstrap_options_spec.rb:67:in `block (3 levels) in <top (required)>'
  5) Chef::Knife::Bootstrap when compared to BootstrapWindowsSsh uses the same long-name
     Failure/Error: expected = bootstrap.options[win_key][sym]
     NoMethodError:
       undefined method `[]' for nil:NilClass
     Shared Example Group: "compare_options" called from ./spec/unit/knife/bootstrap_options_spec.rb:159
     # ./spec/unit/knife/bootstrap_options_spec.rb:36:in `block in compare_property'
     # ./spec/unit/knife/bootstrap_options_spec.rb:33:in `each'
     # ./spec/unit/knife/bootstrap_options_spec.rb:33:in `compare_property'
     # ./spec/unit/knife/bootstrap_options_spec.rb:55:in `block (3 levels) in <top (required)>'
  6) Chef::Knife::Bootstrap when compared to BootstrapWindowsSsh uses the same short-name
     Failure/Error: expected = bootstrap.options[win_key][sym]
     NoMethodError:
       undefined method `[]' for nil:NilClass
     Shared Example Group: "compare_options" called from ./spec/unit/knife/bootstrap_options_spec.rb:159
     # ./spec/unit/knife/bootstrap_options_spec.rb:36:in `block in compare_property'
     # ./spec/unit/knife/bootstrap_options_spec.rb:33:in `each'
     # ./spec/unit/knife/bootstrap_options_spec.rb:33:in `compare_property'
     # ./spec/unit/knife/bootstrap_options_spec.rb:59:in `block (3 levels) in <top (required)>'
  7) Chef::Knife::Bootstrap when compared to BootstrapWindowsSsh uses the same description
     Failure/Error: expected = bootstrap.options[win_key][sym]
     NoMethodError:
       undefined method `[]' for nil:NilClass
     Shared Example Group: "compare_options" called from ./spec/unit/knife/bootstrap_options_spec.rb:159
     # ./spec/unit/knife/bootstrap_options_spec.rb:36:in `block in compare_property'
     # ./spec/unit/knife/bootstrap_options_spec.rb:33:in `each'
     # ./spec/unit/knife/bootstrap_options_spec.rb:33:in `compare_property'
     # ./spec/unit/knife/bootstrap_options_spec.rb:63:in `block (3 levels) in <top (required)>'
  8) Chef::Knife::Bootstrap when compared to BootstrapWindowsSsh uses the same default value
     Failure/Error: expected = bootstrap.options[win_key][sym]
     NoMethodError:
       undefined method `[]' for nil:NilClass
     Shared Example Group: "compare_options" called from ./spec/unit/knife/bootstrap_options_spec.rb:159
     # ./spec/unit/knife/bootstrap_options_spec.rb:36:in `block in compare_property'
     # ./spec/unit/knife/bootstrap_options_spec.rb:33:in `each'
     # ./spec/unit/knife/bootstrap_options_spec.rb:33:in `compare_property'
     # ./spec/unit/knife/bootstrap_options_spec.rb:67:in `block (3 levels) in <top (required)>'
Finished in 0.78692 seconds (files took 0.69463 seconds to load)
135 examples, 8 failures
Failed examples:
rspec ./spec/unit/knife/bootstrap_options_spec.rb[1:1:2] # Chef::Knife::Bootstrap when compared to BootstrapWindowsWinrm uses the same long-name
rspec ./spec/unit/knife/bootstrap_options_spec.rb[1:1:3] # Chef::Knife::Bootstrap when compared to BootstrapWindowsWinrm uses the same short-name
rspec ./spec/unit/knife/bootstrap_options_spec.rb[1:1:4] # Chef::Knife::Bootstrap when compared to BootstrapWindowsWinrm uses the same description
rspec ./spec/unit/knife/bootstrap_options_spec.rb[1:1:5] # Chef::Knife::Bootstrap when compared to BootstrapWindowsWinrm uses the same default value
rspec ./spec/unit/knife/bootstrap_options_spec.rb[1:2:2] # Chef::Knife::Bootstrap when compared to BootstrapWindowsSsh uses the same long-name
rspec ./spec/unit/knife/bootstrap_options_spec.rb[1:2:3] # Chef::Knife::Bootstrap when compared to BootstrapWindowsSsh uses the same short-name
rspec ./spec/unit/knife/bootstrap_options_spec.rb[1:2:4] # Chef::Knife::Bootstrap when compared to BootstrapWindowsSsh uses the same description
rspec ./spec/unit/knife/bootstrap_options_spec.rb[1:2:5] # Chef::Knife::Bootstrap when compared to BootstrapWindowsSsh uses the same default value
```

**Comment by lamont-granquist** [comment]
adding regression tag since my guess from the output is that knife-windows is actually busted on chef-14 and this isn't just test breakage.

**Comment by NAshwini** [comment]
Hi @lamont-granquist  and @btm: `knife bootstrap windows' is working fine, and it's just the tests that is failing. Will fix the specs.
