### ISSUE TITLE
Chef14: yum_package "FakeRepository instance has no attribute 'compare_providers_priority'" issue

### ISSUE THREAD

**Issue by jekriske-lilly** [chef/chef#7126]
## Description
yum_package does not function correctly in RHEL 7.4 with Red Hat Satellite server.

## Chef Version

14.0.190

## Platform Version
RHEL 7.4

## Replication Case
Create new RHEL 7.4 instance hooked into Red Hat Satellite. Run build essential cookbook.

## Client Output

```
Recipe: build-essential::default
  * build_essential[install_packages] action install[2018-04-05T13:59:39-04:00] INFO: Processing build_essential[install_packages] action install (build-essential::default line 22)

    * yum_package[autoconf, bison, flex, gcc, gcc-c++, gettext, kernel-devel, make, m4, ncurses-devel, patch] action install[2018-04-05T13:59:39-04:00] INFO: Processing yum_package[autoconf, bison, flex, gcc, gcc-c++, gettext, kernel-devel, make, m4, ncurses-devel, patch] action install (/opt/chef/cache/cookbooks/build-essential/resources/build_essential.rb line 30)


      ================================================================================
      Error executing action `install` on resource 'yum_package[autoconf, bison, flex, gcc, gcc-c++, gettext, kernel-devel, make, m4, ncurses-devel, patch]'
      ================================================================================

      RuntimeError
      ------------
      yum-helper.py had stderr/stdout output:

      BDB2053 Freeing read locks for locker 0x8b: 16290/140619465414464
      BDB2053 Freeing read locks for locker 0x8d: 16290/140619465414464
      Traceback (most recent call last):
        File "/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/provider/package/yum/yum_helper.py", line 190, in <module>
          query(command)
        File "/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/provider/package/yum/yum_helper.py", line 145, in query
          pkgs = base.bestPackagesFromList(pkgs,single_name=True)
        File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 4441, in bestPackagesFromList
          multi = self._bestPackageFromList(multiLib, req=req)
        File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 4408, in _bestPackageFromList
          bestlist = self._compare_providers(pkglist, reqpo=None, req=req)
        File "/usr/lib/python2.7/site-packages/yum/depsolve.py", line 1590, in _compare_providers
          pkgresults[po] += (100 - po.repo.compare_providers_priority) * 10
      AttributeError: FakeRepository instance has no attribute 'compare_providers_priority'
      Loaded plugins: langpacks, ovl, product-id, subscription-manager, versionlock

      Resource Declaration:
      ---------------------
      # In /opt/chef/cache/cookbooks/build-essential/resources/build_essential.rb

       30:     package %w( autoconf bison flex gcc gcc-c++ gettext kernel-devel make m4 ncurses-devel patch )
       31:

      Compiled Resource:
      ------------------
      # Declared in /opt/chef/cache/cookbooks/build-essential/resources/build_essential.rb:30:in `block in class_from_file'

      yum_package("autoconf, bison, flex, gcc, gcc-c++, gettext, kernel-devel, make, m4, ncurses-devel, patch") do
        package_name ["autoconf", "bison", "flex", "gcc", "gcc-c++", "gettext", "kernel-devel", "make", "m4", "ncurses-devel", "patch"]
        action [:install]
        default_guard_interpreter :default
        declared_type :package
        cookbook_name "build-essential"
      end

      System Info:
      ------------
      chef_version=14.0.190
      platform=redhat
      platform_version=7.4
      ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
      program_name=/usr/bin/chef-client
      executable=/opt/chef/bin/chef-client

[2018-04-05T13:59:46-04:00] INFO: Running queued delayed notifications before re-raising exception

    ================================================================================
    Error executing action `install` on resource 'build_essential[install_packages]'
    ================================================================================
```

## Stacktrace
see above

Works fine with Chef 13.x

**Comment by jekriske-lilly** [comment]
It could be, not sure why it works in Chef 13 though.

**Comment by lamont-granquist** [comment]
everything about the yum_package provider changed in Chef 14, complete rewrite.

**Comment by ronabop** [comment]
Perhaps this will help to debug/isolate it (or help some people get around it):

We were having similar problems with both the build-essential cookbook (and newer build_essential resource, as well), which we tracked back to yum_package and "FakeRepository instance...", and then _further_ tracked down to a use-case where we were seeing the problems on machines that had 
1) build-essential packages already installed prior to installing spacewalk on them (machines that had been initially set up without spacewalk), and 
3) the kernel-devel package itself.

Solution was to uninstall the previously-installed kernel-devel packages from those machines, and afterwards, the yum errors stopped.

**Comment by intuit-tlauder** [comment]
We don't use satellite server but our systems are using a local YUM repo provided by artifactory and we have this issue as well.  Adding those lines to `/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider/package/yum/yum_helper.py` in the latest stable chef-client makes the error go away.

```
--- /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider/package/yum/yum_helper.py.old   2018-04-17 17:46:17.750557551 +0000
+++ /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider/package/yum/yum_helper.py       2018-04-17 17:46:34.120572679 +0000
@@ -27,6 +27,9 @@
         (prco_e, prco_v, prco_r) = stringToVersion(v)
         return (n, f, (prco_e, prco_v, prco_r))

+if not hasattr(yum.packages.FakeRepository, 'compare_providers_priority'):
+    yum.packages.FakeRepository.compare_providers_priority = 99
+
 base = None

 def get_base():

**Comment by bipinbachhao** [comment]
On Satellite subscribed servers adding those lines does not work,

```
 diff /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/provider/package/yum/yum_helper.py.org /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/provider/package/yum/yum_helper.py
29a30,32
> if not hasattr(yum.packages.FakeRepository, 'compare_providers_priority'):
>     yum.packages.FakeRepository.compare_providers_priority = 99
>
```
Error changed little bit

```
 diff /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/provider/package/yum/yum_helper.py.org /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.190/lib/chef/provider/package/yum/yum_helper.py
29a30,32
> if not hasattr(yum.packages.FakeRepository, 'compare_providers_priority'):
>     yum.packages.FakeRepository.compare_providers_priority = 99
>
```

**Comment by lamont-granquist** [comment]
offhand, that looks more like a bug with the lilly-sis yum plugin...
