### ISSUE TITLE
unhandled Python exception in ...lib/chef/provider/package/yum/yum_helper.py - broke since .137 

### ISSUE THREAD

**Issue by tomdoherty** [chef/chef#7153]
## Description
Any release since 14.0.136 results in below error on RHEL 6.9 when using yum_package

Apr 13 16:43:03 ld4vfh03 abrt: detected unhandled Python exception in '/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.197/lib/chef/provider/package/yum/yum_helper.py'
Apr 13 16:43:03 ld4vfh03 abrt: can't communicate with ABRT daemon, is it running? [Errno 2] No such file or directory

Fix from https://github.com/chef/chef/pull/7147/files doesn't work here

## Chef Version
14.0.136+

## Platform Version
RHEL 6.9

## Replication Case
yum_package %w(fixnetix-common fixnetix-midtier fixnetix-vela) do
  version [fixnetix_common_version, fixnetix_midtier_version, fixnetix_vela_version] if fixnetix_common_version
  action [:install]
  notifies :run, 'bash[backup previous SMART configs]', :before
  allow_downgrade true
  notifies :run, 'bash[report package upgrade]', :before
end

## Client Output
As normal
## Stacktrace
decoder.py:338:raw_decode:ValueError: No JSON object could be decoded

Traceback (most recent call last):
  File "/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.197/lib/chef/provider/package/yum/yum_helper.py", line 189, in <module>
    command = json.loads(line)
  File "/usr/lib64/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Local variables in innermost frame:
s: ''
kw: {'context': <json.decoder.JSONDecoder object at 0x21f6e50>, 'idx': 0}
self: <json.decoder.JSONDecoder object at 0x21f6e50>

**Comment by tomdoherty** [comment]
Fixed by #7155
