### ISSUE TITLE
sysctl resource ignore_error is being ignored

### ISSUE THREAD

**Issue by isuftin** [chef/chef#7189]
## Description
When I attempt to use the Chef sysctl resource to apply a key that does not exist on the system, the sysctl resource returns an error even though the ignore_error flag is set to true

## Chef Version
14.0.202

## Platform Version
CentOS 6.9 (as well as 7.x)

## Replication Case
.kitchen.yml:
```
---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6

suites:
  - name: centos6
    run_list:
      - recipe[runme::test_sysctl]

```

test_sysctl.rb:
```
sysctl 'I Will Fail' do
  key 'net.ipv6.route.flush'
  value 1
  ignore_error true
end
```

## Client Output

```
================================================================================
           Error executing action `apply` on resource 'sysctl[fs.suid_dumpable]'
           ================================================================================
           
           RuntimeError
           ------------
           Unknown sysctl key net.ipv6.route.flush!
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/stig/recipes/proc_hard.rb
           
            26:   sysctl param do
            27:     key 'net.ipv6.route.flush'
            28:     value 1
            29:     ignore_error true
            30:   end
            31: end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/stig/recipes/proc_hard.rb:26:in `block in from_file'
           
           sysctl("fs.suid_dumpable") do
             action [:apply]
             default_guard_interpreter :default
             declared_type :sysctl
             cookbook_name "stig"
             recipe_name "proc_hard"
             key "net.ipv6.route.flush"
             value "1"
             ignore_error true
           end
           
           System Info:
           ------------
           chef_version=14.0.202
           platform=centos
           platform_version=6.9
           ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
           program_name=/opt/chef/bin/chef-client
           executable=/opt/chef/bin/chef-client
           
       [2018-04-26T15:15:27+00:00] INFO: Running queued delayed notifications before re-raising exception
       
       Running handlers:
       [2018-04-26T15:15:27+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2018-04-26T15:15:27+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 02 seconds
       [2018-04-26T15:15:27+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-04-26T15:15:27+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-04-26T15:15:27+00:00] DEBUG: RuntimeError: sysctl[fs.suid_dumpable] (stig::proc_hard line 26) had an error: RuntimeError: Unknown sysctl key net.ipv6.route.flush!
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource/sysctl.rb:68:in `get_sysctl_value'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource/sysctl.rb:73:in `block in <class:Sysctl>'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource/action_class.rb:57:in `load_current_resource'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider.rb:165:in `run_action'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource.rb:576:in `run_action'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:70:in `run_action'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:98:in `block (2 levels) in converge'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:98:in `each'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:98:in `block in converge'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:97:in `converge'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:717:in `block in converge'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:712:in `catch'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:712:in `converge'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:751:in `converge_and_save'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:283:in `run'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:279:in `block in run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/local_mode.rb:44:in `with_server_connectivity'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:261:in `run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application/client.rb:440:in `run_application'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:66:in `run'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/bin/chef-client:26:in `<top (required)>'
       /opt/chef/bin/chef-client:59:in `load'
       /opt/chef/bin/chef-client:59:in `<main>'
       
       >>>> Caused by RuntimeError: Unknown sysctl key net.ipv6.route.flush!
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource/sysctl.rb:68:in `get_sysctl_value'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource/sysctl.rb:73:in `block in <class:Sysctl>'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource/action_class.rb:57:in `load_current_resource'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider.rb:165:in `run_action'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource.rb:576:in `run_action'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:70:in `run_action'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:98:in `block (2 levels) in converge'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:98:in `each'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:98:in `block in converge'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:97:in `converge'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:717:in `block in converge'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:712:in `catch'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:712:in `converge'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:751:in `converge_and_save'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:283:in `run'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:279:in `block in run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/local_mode.rb:44:in `with_server_connectivity'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:261:in `run_chef_client'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application/client.rb:440:in `run_application'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:66:in `run'
       /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/bin/chef-client:26:in `<top (required)>'
       /opt/chef/bin/chef-client:59:in `load'
       /opt/chef/bin/chef-client:59:in `<main>'
       [2018-04-26T15:15:27+00:00] FATAL: RuntimeError: sysctl[fs.suid_dumpable] (stig::proc_hard line 26) had an error: RuntimeError: Unknown sysctl key net.ipv6.route.flush!
D      Cleaning up local sandbox in /var/folders/58/n9bfwg050sdg1dmn9688wrcm001rp_/T/centos6-centos-6-sandbox-20180426-59441-4qt5d1
D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Converge failed on instance <centos6-centos-6>.  Please see .kitchen/logs/centos6-centos-6.log for more details
D      ----------------------
D      ------Backtrace-------
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:183:in `report_errors'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:174:in `run_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command/action.rb:36:in `block in call'
D      /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command/action.rb:34:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/cli.rb:52:in `perform'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/cli.rb:193:in `block (2 levels) in <class:CLI>'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/bin/kitchen:13:in `block in <top (required)>'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/errors.rb:171:in `with_friendly_errors'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/bin/kitchen:13:in `<top (required)>'
D      /opt/chefdk/bin/kitchen:255:in `load'
D      /opt/chefdk/bin/kitchen:255:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::InstanceFailure
D      Message: Converge failed on instance <centos6-centos-6>.  Please see .kitchen/logs/centos6-centos-6.log for more details
D      ----------------------
D      ------Backtrace-------
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/provisioner/base.rb:83:in `rescue in call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/provisioner/base.rb:86:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:393:in `block in converge_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:536:in `synchronize_or_call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:498:in `block in action'
D      /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:497:in `action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:389:in `converge_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:368:in `block in transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:367:in `each'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:367:in `transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:135:in `converge'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:197:in `public_send'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: SSH exited (1) for command: [sh -c '
TEST_KITCHEN="1"; export TEST_KITCHEN
sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level debug --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889 
']
D      ----------------------
D      ------Backtrace-------
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/provisioner/base.rb:83:in `rescue in call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/provisioner/base.rb:86:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:393:in `block in converge_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:536:in `synchronize_or_call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:498:in `block in action'
D      /opt/chefdk/embedded/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:497:in `action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:389:in `converge_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:368:in `block in transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:367:in `each'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:367:in `transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/instance.rb:135:in `converge'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:197:in `public_send'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/test-kitchen-1.19.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
```

## Stacktrace
Included in client output

The issue seems to come from https://github.com/chef/chef/blob/92d85cf4c67680d778cbe8bc5c676f9a10fa1442/lib/chef/resource/sysctl.rb#L68

I would expect this to not raise an error and simply warn that the value does not exist, but not error out of the chef client run.

My current workaround looks like:

```
  sysctl param do
    key 'net.ipv6.route.flush'
    value 1
    ignore_error true
    only_if "sysctl -n -e #{param}"
  end
```

**Comment by tas50** [comment]
Fixed by https://github.com/chef/chef/pull/7192. Thanks for the report
