### ISSUE TITLE
osx_profile cannot handle signed configuration profiles

### ISSUE THREAD

**Issue by alexionescu** [chef/chef#7287]
## Description
osx_profile cannot handle mobileconfig files that are signed.

## Chef Version
14.0.202

## Platform Version
macOS 10.13.3

## Replication Case
Create a mobileconfig file, any will do, you can use Apple Configurator for it, then create a self signed key pair. Use the following command to sign the mobileconfig file https://www.steveneppler.com/blog/2011/02/09/signing-ios-mobileconfig-files-with-your-certificate and deploy it with chef.

## Stacktrace

```
Generated at 2018-05-21 14:58:04 -0500
ArgumentError: osx_profile[Lock Screen Message] (laptop::lockscreenmessage line 2) had an error: ArgumentError: invalid byte sequence in UTF-8
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/plist-3.4.0/lib/plist/parser.rb:90:in `scan'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/plist-3.4.0/lib/plist/parser.rb:90:in `parse'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/plist-3.4.0/lib/plist/parser.rb:30:in `parse_xml'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider/osx_profile.rb:233:in `read_plist'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider/osx_profile.rb:126:in `load_profile_hash'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider/osx_profile.rb:170:in `get_profile_hash'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider/osx_profile.rb:41:in `load_current_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/provider.rb:165:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource.rb:576:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:70:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:98:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:98:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:98:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/runner.rb:97:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:717:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:712:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:712:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:751:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:283:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:279:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:261:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application/client.rb:440:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/bin/chef-client:26:in `<top (required)>'
/usr/local/bin/chef-client:59:in `load'
/usr/local/bin/chef-client:59:in `<main>'
```

**Comment by lamont-granquist** [comment]
That looks more like a bug in the plist gem's parser.

**Comment by happicamper** [comment]
Experiencing this issue on applying OS X Server profiles.

**Comment by tas50** [comment]
Given that the plist gem doesn't seem to support this and Apple has moved away from profiles in Big Sur I'm going to close this as a won't fix issue. It's just not something we will be prioritizing to fix.
