### ISSUE TITLE
Apache reverseproxy chefapi ssl errors

### ISSUE THREAD

**Issue by naveenlj** [chef/chef#7327]
## Description
Chef client throws ssl error while trying to connect to chef server. Apache server is running as reverse proxy for chef server api and Apache uses self signed ssl certificated need help with chef-client skipping the Apache SSL

## Chef Version
14.0.202

## Platform Version
Ubuntu

```hidden client name and client domain Client Output
2018-05-31T07:18:00+00:00] INFO: *** Chef 14.0.202 ***
[2018-05-31T07:18:00+00:00] INFO: Platform: x86_64-linux
[2018-05-31T07:18:00+00:00] INFO: Chef-client pid: 31810
[2018-05-31T07:18:00+00:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
[2018-05-31T07:18:02+00:00] INFO: Client key /etc/chef/client.pem is not present - registering
[2018-05-31T07:18:03+00:00] ERROR: SSL Validation failure connecting to host: clientdomain - SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
================================================================================
Chef encountered an error attempting to create the client "testing-sftp.localdomain"
================================================================================
System Info:
------------
chef_version=14.0.202
ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
program_name=/usr/bin/chef-client
executable=/opt/chef/bin/chef-client

[2018-05-31T07:18:03+00:00] ERROR: Running exception handlers
[2018-05-31T07:18:03+00:00] ERROR: Exception handlers complete
[2018-05-31T07:18:03+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-05-31T07:18:03+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-05-31T07:18:03+00:00] FATAL: OpenSSL::SSL::SSLError: SSL Error connecting to https://clientdomain/chef/organizations/clientname/clients - SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)```

## Stacktrace
hidden domain name clientdomain and clientname 
Generated at 2018-05-31 07:18:03 +0000
OpenSSL::SSL::SSLError: SSL Error connecting to https://clientdomain/chef/organizations/clientname/clients - SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/http.rb:451:in `rescue in retrying_http_errors'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/http.rb:408:in `retrying_http_errors'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/http.rb:365:in `send_http_request'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/http.rb:149:in `request'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/http.rb:131:in `post'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/api_client/registration.rb:104:in `create'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/api_client/registration.rb:95:in `create_or_update'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/api_client/registration.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:668:in `register'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:264:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:279:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:261:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application/client.rb:440:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:59:in `load'
/usr/bin/chef-client:59:in `<main>'

>>>> Caused by OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
/opt/chef/embedded/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock'
/opt/chef/embedded/lib/ruby/2.5.0/net/protocol.rb:44:in `ssl_socket_connect'
/opt/chef/embedded/lib/ruby/2.5.0/net/http.rb:981:in `connect'
/opt/chef/embedded/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
/opt/chef/embedded/lib/ruby/2.5.0/net/http.rb:909:in `start'
/opt/chef/embedded/lib/ruby/2.5.0/net/http.rb:1455:in `request'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/http/basic_client.rb:69:in `request'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/http.rb:372:in `block in send_http_request'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/http.rb:411:in `block in retrying_http_errors'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/http.rb:409:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/http.rb:409:in `retrying_http_errors'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/http.rb:365:in `send_http_request'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/http.rb:149:in `request'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/http.rb:131:in `post'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/api_client/registration.rb:104:in `create'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/api_client/registration.rb:95:in `create_or_update'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/api_client/registration.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:668:in `register'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/client.rb:264:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:279:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:261:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application/client.rb:440:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:59:in `load'

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
