### ISSUE TITLE
NameError: undefined local variable or method `node' for Chef::Platform:Class

### ISSUE THREAD

**Issue by dmunney** [chef/chef#7381]
## Description

While installing a windows_feature, exception is thrown:
```NameError: windows_feature[NET-Framework-45-Core] (consul::install_consul_windows line 83) had an error: NameError: undefined local variable or method `node' for Chef::Platform:Class```

## Chef Version

```chef-14.3.16-universal-mingw32```

## Platform Version

```
chef_version=14.3.16
platform=windows
platform_version=6.3.9600
ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
program_name=C:/opscode/chef/bin/chef-client
executable=C:/opscode/chef/bin/chef-client
```

## Replication Case

Resource:
```
windows_feature [
                    'NET-Framework-45-Core',
                ] do
  action :install
  install_method :windows_feature_powershell
end
```

## Client Output

```
[0m
[0m  * windows_feature[NET-Framework-45-Core] action install[2018-06-19T15:26:44+00:00] INFO: Processing windows_feature[NET-Framework-45-Core] action install (consul::install_consul_windows line 83)
[2018-06-19T15:26:44+00:00] INFO: Processing windows_feature[NET-Framework-45-Core] action install (consul::install_consul_windows line 83)

[0m
    ================================================================================[0m
    [31mError executing action `install` on resource 'windows_feature[NET-Framework-45-Core]'[0m
    ================================================================================[0m

[0m    NameError[0m
    ---------[0m
    undefined local variable or method `node' for Chef::Platform:Class[0m

[0m    Resource Declaration:[0m
    ---------------------[0m
    # In c:/chef/cache/cookbooks/consul/recipes/install_consul_windows.rb
[0m    
[0m     83: windows_feature [
[0m     84:                     'NET-Framework-45-Core',
[0m    
[0m    Compiled Resource:[0m
    ------------------[0m
    # Declared in c:/chef/cache/cookbooks/consul/recipes/install_consul_windows.rb:83:in `from_file'
[0m    
[0m    windows_feature("NET-Framework-45-Core") do
[0m      action [:install]
[0m      default_guard_interpreter :default
[0m      declared_type :windows_feature
[0m      cookbook_name "consul"
[0m      recipe_name "install_consul_windows"
[0m      install_method :windows_feature_powershell
[0m      feature_name "NET-Framework-45-Core"
[0m    end
[0m    
[0m    System Info:[0m
    ------------[0m
    chef_version=14.3.16
[0m    platform=windows
[0m    platform_version=6.3.9600
[0m    ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
[0m    program_name=C:/opscode/chef/bin/chef-client
[0m    executable=C:/opscode/chef/bin/chef-client[0m

[0m
```

## Stacktrace

```
NameError: windows_feature[NET-Framework-45-Core] (consul::install_consul_windows line 83) had an error: NameError: undefined local variable or method `node' for Chef::Platform:Class
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/platform/query_helpers.rb:26:in `older_than_win_2012_or_8?'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource/windows_feature_powershell.rb:64:in `to_formatted_array'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource/windows_feature_powershell.rb:39:in `block in <class:WindowsFeaturePowershell>'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/property.rb:672:in `instance_exec'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/property.rb:672:in `exec_in_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/property.rb:469:in `coerce'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/property.rb:701:in `coerce_and_validate'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/property.rb:685:in `input_to_stored_value'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/property.rb:404:in `set'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/property.rb:326:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/property.rb:547:in `feature_name'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource/windows_feature.rb:85:in `block in run_default_subresource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource_builder.rb:66:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource_builder.rb:66:in `build'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/dsl/declare_resource.rb:314:in `build_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/dsl/declare_resource.rb:271:in `declare_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource/windows_feature.rb:83:in `run_default_subresource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource/windows_feature.rb:61:in `block in <class:WindowsFeature>'
(eval):2:in `block in action_install'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/provider.rb:236:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/provider.rb:236:in `compile_and_converge_action'
(eval):2:in `action_install'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/provider.rb:182:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource.rb:577:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/runner.rb:70:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/runner.rb:98:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/runner.rb:98:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/runner.rb:98:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/runner.rb:97:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/client.rb:720:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/client.rb:715:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/client.rb:715:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/client.rb:754:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/client.rb:286:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/application.rb:279:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/application.rb:261:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/application/client.rb:441:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/application.rb:66:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:75:in `load'
C:/opscode/chef/bin/chef-client:75:in `<main>'

>>>> Caused by NameError: undefined local variable or method `node' for Chef::Platform:Class
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/platform/query_helpers.rb:26:in `older_than_win_2012_or_8?'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource/windows_feature_powershell.rb:64:in `to_formatted_array'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource/windows_feature_powershell.rb:39:in `block in <class:WindowsFeaturePowershell>'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/property.rb:672:in `instance_exec'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/property.rb:672:in `exec_in_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/property.rb:469:in `coerce'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/property.rb:701:in `coerce_and_validate'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/property.rb:685:in `input_to_stored_value'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/property.rb:404:in `set'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/property.rb:326:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/property.rb:547:in `feature_name'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource/windows_feature.rb:85:in `block in run_default_subresource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource_builder.rb:66:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource_builder.rb:66:in `build'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/dsl/declare_resource.rb:314:in `build_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/dsl/declare_resource.rb:271:in `declare_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource/windows_feature.rb:83:in `run_default_subresource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource/windows_feature.rb:61:in `block in <class:WindowsFeature>'
(eval):2:in `block in action_install'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/provider.rb:236:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/provider.rb:236:in `compile_and_converge_action'
(eval):2:in `action_install'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/provider.rb:182:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource.rb:577:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/runner.rb:70:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/runner.rb:98:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/runner.rb:98:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/runner.rb:98:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/runner.rb:97:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/client.rb:720:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/client.rb:715:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/client.rb:715:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/client.rb:754:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/client.rb:286:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/application.rb:279:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/application.rb:261:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/application/client.rb:441:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/lib/chef/application.rb:66:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.16-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:75:in `load'
C:/opscode/chef/bin/chef-client:75:in `<main>'
```

**Comment by tas50** [comment]
Resolved by https://github.com/chef/chef/pull/7433

Thanks for the report @dmunney
