### ISSUE TITLE
chef-shell bypasses node ACL when using nodes.list

### ISSUE THREAD

**Issue by rymurph20** [chef/chef#7386]
## Description
First, I apologize if this is the wrong place to post chef-shell issues. If there's a better location, just let me know and I'll move this. The command 'nodes.list' in chef-shell shows all nodes and their attributes despite permissions being set to deny client's read access. 

I've removed all permissions for the 'clients' group on the node and the 'nodes' global container. This was confirmed via the Chef Manage GUI and 'knife acl'.

## Chef Version
Chef 12.19.36

## Platform Version
Ubuntu 14.04.5 LTS

## Replication Case
node1 = Local node I'm running chef-shell from.
node2 = Node in the same organization & environment but 'clients' group has no read permissions.

```
# sudo chef-shell -z
chef (14.1.12)> nodes.show('node1')

#<Chef::Node:0x00000000020f7bf0 @chef_server_rest=nil, @name="node1", @logger=#<Mixlib::Log::Child:0x00000000020f79c0 @parent=Chef::Log, @metadata={:subsystem=>"node"}>, @chef_environment="_default" ...

chef (14.1.12)> nodes.show('node2')

Traceback (most recent call last):
       12: from /usr/bin/chef-shell:270:in `<main>'
       11: from /usr/bin/chef-shell:270:in `load'
       10: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.12/bin/chef-shell:36:in `<top (required)>'
        9: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.12/lib/chef/shell.rb:80:in `start'
        8: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.12/lib/chef/shell.rb:80:in `catch'
        7: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.12/lib/chef/shell.rb:81:in `block in start'
        6: from (irb):2
        5: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.12/lib/chef/shell/model_wrapper.rb:57:in `show'
        4: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.12/lib/chef/node.rb:593:in `load'
        3: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.12/lib/chef/http.rb:115:in `get'
        2: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.12/lib/chef/http.rb:152:in `request'
        1: from /opt/chefdk/embedded/lib/ruby/2.5.0/net/http/response.rb:122:in `error!'
Net::HTTPServerException (403 "Forbidden")

chef (14.1.12)> nodes.list

#<Chef::Node:0x00000000020f7bf0 @chef_server_rest=nil, @name="node2", @logger=#<Mixlib::Log::Child:0x00000000020f79c0 @parent=Chef::Log, @metadata={:subsystem=>"node"}>, @chef_environment="_default"...
#<Chef::Node:0x00000000020f7bf0 @chef_server_rest=nil, @name="node1", @logger=#<Mixlib::Log::Child:0x00000000020f79c0 @parent=Chef::Log, @metadata={:subsystem=>"node"}>, @chef_environment="_default"...

```

Essentially, by using the nodes.show command I'm seeing expected results (403, Forbidden). However, when using nodes.list, I'm still seeing other nodes / attributes that I shouldn't have access to.

## Permissions
'nodes' container global permissions:
```
$ knife acl show containers nodes
create:
  clients:
  groups:
    admins
    users
  users:   pivotal
delete:
  clients:
  groups:
    admins
    users
  users:   pivotal
grant:
  clients:
  groups:  admins
  users:   pivotal
read:
  clients:
  groups:
    admins
    users
  users:   pivotal
update:
  clients:
  groups:
    admins
    users
  users:   pivotal
```

'node2' permissions:
```
$ knife acl show nodes node2 
create:
  clients: node2 
  groups:
    admins
    users
  users:   pivotal
delete:
  clients: node2 
  groups:
    admins
    users
  users:   pivotal
grant:
  clients: node2 
  groups:  admins
  users:   pivotal
read:
  clients: node2 
  groups:
    admins
    users
  users:   pivotal
update:
  clients: node2 
  groups:
    admins
    users
  users:   pivotal
```

**Comment by coderanger** [comment]
This is because `nodes.list` ends up actually using the Search API, rather than the Nodes API which does not check object ACLs by default. You can enable this via `opscode_erchef['strict_search_result_acls'] = true` in your `chef-server.rb` config file.

**Comment by rymurph20** [comment]
That worked, thanks!
