### ISSUE TITLE
Chef::Exceptions::ValidationFailed: Option name's value  does not match regular expression /^[\-[:alnum:]_]+$/

### ISSUE THREAD

**Issue by bpmdoty** [chef/chef#7394]
## Description
chef-client fails to run with trivial environment.  fails with error: `Chef::Exceptions::ValidationFailed: Option name's value  does not match regular expression /^[\-[:alnum:]_]+$/` if environment is set.  If environment is `''`(and node object updated to remove environment) then chef-client runs as expected.

## Chef Version
Chef: 14.2.0

## Platform Version
Ubuntu 18.04 LTS

## Replication Case
Run chef-client in local mode with `environment  'anything'` in /etc/chef/client.rb, and have a corresponding anything.rb in environments directory.

/etc/chef/client.rb:
```
chef_repo_path        '/var/chef'
cache_path            '/var/local/chef/cache'
cookbook_path         ['/var/chef/cookbooks', '/var/chef/site-cookbooks']
data_bag_path         '/var/chef/data_bags'
environment_path      '/var/chef/environments'
file_backup_path      '/var/local/chef/backup'
file_cache_path       '/var/local/chef/cache'
node_path             '/var/chef/nodes'
role_path             '/var/chef/roles'

local_mode            true
chef_zero.enabled     true
environment           'dev'
group                 'root'
ssl_verify_mode       :verify_none
node_name      'ip-10-0-50-20'
```
chef directory structure:
```
/var/chef
├── cookbooks
├── data_bags
├── environments
│   ├── dev.rb
│   └── dev.rb.save
├── nodes
│   └── ip-10-0-50-20.json
├── roles
├── scripts
└── site-cookbooks
    └── hello
        └── recipes
            └── default.rb
```
environments/dev.rb:
```
{
  "name": 'dev',
  "json_class": "Chef::Environment",
  "description": "Staging Environment",
  "cookbook_versions": {},
  "default_attributes": {
    "monitoring": {
    "external_fqdn": "some.dev.fqdn.com"
    }
  },
 "chef_type": "environment"
}
```

## Client Output
```
[2018-06-26T22:52:50+00:00] DEBUG: Extracting run list from JSON attributes provided on command line
[2018-06-26T22:52:50+00:00] INFO: Setting the run_list to [#<Chef::RunList::RunListItem:0x0000000002cdf328 @version=nil, @type=:recipe, @name="hello::default">] from CLI options
[2018-06-26T22:52:50+00:00] DEBUG: Applying attributes from json file
[2018-06-26T22:52:50+00:00] DEBUG: Platform is ubuntu version 18.04
[2018-06-26T22:52:50+00:00] DEBUG: GET /organizations/chef/environments/dev
[2018-06-26T22:52:50+00:00] DEBUG: #<ChefZero::RestRequest:0x0000000003a313c8
 @env=
  {"SCRIPT_NAME"=>"",
   "SERVER_NAME"=>"localhost",
   "REQUEST_METHOD"=>"GET",
   "PATH_INFO"=>"/environments/dev",
   "QUERY_STRING"=>nil,
   "SERVER_PORT"=>1,
   "HTTP_HOST"=>"localhost:1",
   "HTTP_X_OPS_SERVER_API_VERSION"=>"1",
   "rack.url_scheme"=>"chefzero",
   "rack.input"=>#<StringIO:0x0000000003a31418>},
 @rest_base_prefix=["organizations", "chef"],
 @rest_path=["organizations", "chef", "environments", "dev"]>

[2018-06-26T22:52:50+00:00] DEBUG:
--- RESPONSE (200) ---
{
  "name": "",
  "description": "",
  "cookbook_versions": {

  },
  "json_class": "Chef::Environment",
  "chef_type": "environment",
  "default_attributes": {

  },
  "override_attributes": {

  }
}
--- END RESPONSE ---

================================================================================
Error expanding the run_list:
================================================================================

Unexpected Error:
-----------------
Chef::Exceptions::ValidationFailed: Option name's value  does not match regular expression /^[\-[:alnum:]_]+$/

System Info:
------------
chef_version=14.2.0
platform=ubuntu
platform_version=18.04
ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
program_name=/usr/bin/chef-client
executable=/opt/chef/bin/chef-client


Running handlers:
[2018-06-26T22:52:50+00:00] ERROR: Running exception handlers
Running handlers complete
[2018-06-26T22:52:50+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 01 seconds
[2018-06-26T22:52:50+00:00] FATAL: Stacktrace dumped to /var/local/chef/cache/chef-stacktrace.out
[2018-06-26T22:52:50+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-06-26T22:52:50+00:00] DEBUG: Chef::Exceptions::ValidationFailed: Option name's value  does not match regular expression /^[\-[:alnum:]_]+$/
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/mixin/params_validate.rb:303:in `_pv_regex'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/mixin/params_validate.rb:113:in `block (2 levels) in validate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/mixin/params_validate.rb:110:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/mixin/params_validate.rb:110:in `block in validate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/mixin/params_validate.rb:98:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/mixin/params_validate.rb:98:in `validate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/property.rb:492:in `validate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/property.rb:702:in `coerce_and_validate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/property.rb:685:in `input_to_stored_value'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/property.rb:404:in `set'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/property.rb:326:in `call'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/mixin/params_validate.rb:490:in `call'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/mixin/params_validate.rb:129:in `set_or_return'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/environment.rb:57:in `name'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/environment.rb:219:in `from_hash'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/environment.rb:243:in `load'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/node.rb:446:in `apply_expansion_attributes'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/node.rb:434:in `expand!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/policy_builder/expand_node_object.rb:146:in `expand_run_list'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/policy_builder/expand_node_object.rb:130:in `build_node'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/client.rb:485:in `build_node'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/client.rb:269:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/application.rb:279:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/application.rb:261:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/application/client.rb:441:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:75:in `load'
/usr/bin/chef-client:75:in `<main>'
[2018-06-26T22:52:50+00:00] FATAL: Chef::Exceptions::ValidationFailed: Option name's value  does not match regular expression /^[\-[:alnum:]_]+$/
```

## Stacktrace
```
Generated at 2018-06-26 22:52:50 +0000
Chef::Exceptions::ValidationFailed: Option name's value  does not match regular expression /^[\-[:alnum:]_]+$/
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/mixin/params_validate.rb:303:in `_pv_regex'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/mixin/params_validate.rb:113:in `block (2 levels) in validate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/mixin/params_validate.rb:110:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/mixin/params_validate.rb:110:in `block in validate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/mixin/params_validate.rb:98:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/mixin/params_validate.rb:98:in `validate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/property.rb:492:in `validate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/property.rb:702:in `coerce_and_validate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/property.rb:685:in `input_to_stored_value'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/property.rb:404:in `set'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/property.rb:326:in `call'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/mixin/params_validate.rb:490:in `call'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/mixin/params_validate.rb:129:in `set_or_return'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/environment.rb:57:in `name'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/environment.rb:219:in `from_hash'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/environment.rb:243:in `load'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/node.rb:446:in `apply_expansion_attributes'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/node.rb:434:in `expand!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/policy_builder/expand_node_object.rb:146:in `expand_run_list'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/policy_builder/expand_node_object.rb:130:in `build_node'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/client.rb:485:in `build_node'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/client.rb:269:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/application.rb:279:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/application.rb:261:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/application/client.rb:441:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.2.0/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:75:in `load'
/usr/bin/chef-client:75:in `<main>'
```

**Comment by bpmdoty** [comment]
Also, this works in Chef 12.6 up to Chef 12.22.  I haven't tested Chef 13, but would expect it to work there as well.

**Comment by bpmdoty** [comment]
So, this isssue was a PEBKAC, but it would have been nice to get a syntax error or something.
