### ISSUE TITLE
Document setup requirements for functional testing on Chef::Resource::DscResource and Chef::Resource::DscScript on Windows 10

### ISSUE THREAD

**Issue by stuartpreston** [chef/chef#7439]
## Summary

All of the DscResource and DscScript functional tests fail on my Windows 10 Enterprise machine.  We should solve these and document the settings somewhere to allow contributors to safely contribute:

```
Chef::Resource::DscResource
  when Powershell supports Invoke-DscResource
    with an invalid dsc resource
      raises an exception if the resource is not found
    with a valid dsc resource
      converges the resource if it is not converged (FAILED - 1)
      does not converge the resource if it is already converged (FAILED - 2)

Chef::Resource::DscScript
  when supplying configuration through the configuration attribute
    behaves like a dsc_script resource with specified PowerShell configuration code
      should create a registry key with a specific registry value and data (FAILED - 3)
      it should behave like a dsc_script resource with configuration affected by cwd
        when the DSC configuration contains code that raises an exception if cwd has a specific value
          should not raise an exception if the cwd is not etc (FAILED - 4)
          should raise an exception if the cwd is etc (FAILED - 5)
  when supplying configuration using the path attribute
    behaves like a dsc_script resource with specified PowerShell configuration code
      should create a registry key with a specific registry value and data (FAILED - 6)
      it should behave like a dsc_script resource with configuration affected by cwd
        when the DSC configuration contains code that raises an exception if cwd has a specific value
          should not raise an exception if the cwd is not etc (FAILED - 7)
          should raise an exception if the cwd is etc (FAILED - 8)
  when running a configuration that manages users
    behaves like a dsc_script with configuration data
      behaves like a dsc_script with configuration data set via an attribute
        should run a configuration script that creates a user (FAILED - 9)
      behaves like a dsc_script with configuration data set via an attribute
        should run a configuration script that creates a user (FAILED - 10)
    behaves like a dsc_script with configuration data that uses environment variables
      does not directly contain the user name (FAILED - 11)
      behaves like a dsc_script with configuration data
        behaves like a dsc_script with configuration data set via an attribute
          should run a configuration script that creates a user (FAILED - 12)
        behaves like a dsc_script with configuration data set via an attribute
          should run a configuration script that creates a user (FAILED - 13)
    behaves like a dsc_script with configuration data that takes parameters
      does not directly contain the user name (FAILED - 14)
      behaves like a dsc_script with configuration data
        behaves like a dsc_script with configuration data set via an attribute
          should run a configuration script that creates a user (FAILED - 15)
        behaves like a dsc_script with configuration data set via an attribute
          should run a configuration script that creates a user (FAILED - 16)
    behaves like a dsc_script without configuration data that takes parameters
      when configuration data is not specified
        should have a default value of nil for the configuration_data attribute (FAILED - 17)
        should have a default value of nil for the configuration_data_path attribute (FAILED - 18)
        should set a registry key according to parameters passed to the configuration (FAILED- 19)
  when using ps_credential
    allows the use of ps_credential (FAILED - 20)
```

The majority of these seem to be because WinRM is disabled on a 'stock' Windows 10 machine.  Example failure:

```
15) Chef::Resource::DscScript when running a configuration that manages users behaves like a
 dsc_script with configuration data that takes parameters behaves like a dsc_script with confi
guration data behaves like a dsc_script with configuration data set via an attribute should ru
n a configuration script that creates a user
      Failure/Error: powershell_out!(winrm_code)

      Mixlib::ShellOut::ShellCommandFailed:
        Expected process to exit with [0], but received '1'
        ---- Begin output of powershell.exe -NoLogo -NonInteractive -NoProfile -ExecutionPolic
y Unrestricted -InputFormat None -Command "      winrm get winrm/config/listener?Address=*+Tra
nsport=HTTP
              if($LASTEXITCODE -ne 0) {
                winrm create winrm/config/Listener?Address=*+Transport=HTTP
              }
        " ----
        STDOUT:
        STDERR: WSManFault
            Message = The client cannot connect to the destination specified in the request. V
erify that the service on the destination is running and is accepting requests. Consult the lo
gs and documentation for the WS-Management service running on the destination, most commonly I
IS or WinRM. If the destination is the WinRM service, run the following command on the destina
tion to analyze and configure the WinRM service: "winrm quickconfig".

        Error number:  -2144108526 0x80338012
        The client cannot connect to the destination specified in the request. Verify that the
 service on the destination is running and is accepting requests. Consult the logs and documen
tation for the WS-Management service running on the destination, most commonly IIS or WinRM. I
f the destination is the WinRM service, run the following command on the destination to analyz
e and configure the WinRM service: "winrm quickconfig".
        WSManFault
            Message = The client cannot connect to the destination specified in the request. V
erify that the service on the destination is running and is accepting requests. Consult the lo
gs and documentation for the WS-Management service running on the destination, most commonly I
IS or WinRM. If the destination is the WinRM service, run the following command on the destina
tion to analyze and configure the WinRM service: "winrm quickconfig".

        Error number:  -2144108526 0x80338012
        The client cannot connect to the destination specified in the request. Verify that the
 service on the destination is running and is accepting requests. Consult the logs and documen
tation for the WS-Management service running on the destination, most commonly IIS or WinRM. I
f the destination is the WinRM service, run the following command on the destination to analyz
e and configure the WinRM service: "winrm quickconfig".
        ---- End output of powershell.exe -NoLogo -NonInteractive -NoProfile -ExecutionPolicy
Unrestricted -InputFormat None -Command "      winrm get winrm/config/listener?Address=*+Trans
port=HTTP
              if($LASTEXITCODE -ne 0) {
                winrm create winrm/config/Listener?Address=*+Transport=HTTP
              }
        " ----
        Ran powershell.exe -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -I
nputFormat None -Command "      winrm get winrm/config/listener?Address=*+Transport=HTTP
              if($LASTEXITCODE -ne 0) {
                winrm create winrm/config/Listener?Address=*+Transport=HTTP
              }
        " returned 1
      Shared Example Group: "a dsc_script with configuration data set via an attribute" called from ./spec/functional/resource/dsc_script_spec.rb:324
      Shared Example Group: "a dsc_script with configuration data" called from ./spec/functional/resource/dsc_script_spec.rb:357
      Shared Example Group: "a dsc_script with configuration data that takes parameters" called from ./spec/functional/resource/dsc_script_spec.rb:393
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.3.2-universal-mingw32/lib/mixlib/shellout.rb:293:in `invalid'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.3.2-universal-mingw32/lib/mixlib/shellout.rb:280:in `error!'      # ./lib/chef/mixin/powershell_out.rb:48:in `powershell_out!'
      # ./spec/functional/resource/dsc_script_spec.rb:37:in `block (2 levels) in <top (required)>'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:350:in `instance_exec'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:350:in `run'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:509:in `block in run_owned_hooks_for'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:508:in `each'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:508:in `run_owned_hooks_for'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/hooks.rb:460:in `run'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:537:in `block in run_before_context_hooks'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/memoized_helpers.rb:186:in `block in isolate_for_context_hook'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/memoized_helpers.rb:182:in `instance_exec'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/memoized_helpers.rb:182:in `isolate_for_context_hook'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:536:in `run_before_context_hooks'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/example_group.rb:589:in `run'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `block (3 levels) in run_specs'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `map'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:118:in `block (2 levels) in run_specs'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1926:in `with_suite_hooks'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:113:in `block in run_specs'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:79:in `report'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:112:in `run_specs'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:87:in `run'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
      # C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'
      # C:/Ruby25-x64/bin/rspec:23:in `load'
      # C:/Ruby25-x64/bin/rspec:23:in `<main>'

```

## Acceptable fix

Document the required settings on Windows 10 to execute these functional tests correctly.

## Related items

See https://github.com/chef/chef/issues/3106

**Comment by stuartpreston** [comment]
There are no outstanding issues running the Functional Tests on Windows 10.  Just need to ensure WinRM is enabled (for most people it will be already but `Enable-PSRemoting -SkipProfileCheck -Force` will do it if not.
