### ISSUE TITLE
Chef::HTTP::Simple duplicates query parameters on retry

### ISSUE THREAD

**Issue by b-dean** [chef/chef#7461]
## Description
When Chef requests a URI that will cause a retry, the query parameters are duplicated with each retry.

This would also affect an resource that uses Chef's HTTP classes, such as `remote_file`

## Chef Version
14.3.37
Works as expected on 14.2.0

## Platform Version
`chef/chefdk:3.1.1` docker image running on Ubuntu 14.04 host

## Replication Case
Inside a docker container running `chef/chefdk:3.1.1`, create a file `test.rb` with the following content

```ruby
uri = 'http://127.0.0.1:12345/foo?bar=baz'
http = Chef::HTTP::Simple.new(uri)
http.get(uri)
```
The docker image comes with Chef 14.2.0, so first run `chef-apply test.rb` with that version of chef.

The output there shows the expected URI request retrying the same URI 5 times.
```
Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz, retry 1/5
Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz, retry 2/5
Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz, retry 3/5
Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz, retry 4/5
Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz, retry 5/5
```

Then install the newer Chef 14.3.37 with `chef gem install chef -v 14.3.37` and run the `chef-apply` command again.

This shows the URI's query parameters being duplicated with each retry.
```
Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz, retry 1/5
Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz, retry 1/5
Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz, retry 2/5
Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz, retry 2/5
Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz?bar=baz, retry 3/5
Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz?bar=baz, retry 3/5
Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz, retry 4/5
Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz, retry 4/5
Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz, retry 5/5
Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz, retry 5/5
```

See the full output (with `-l debug`) below

## Client Output

```
$ docker run --rm -it chef/chefdk:3.1.1
root@97d8dcb38d2a:/# chef --version
Chef Development Kit Version: 3.1.1
chef-client version: 14.2.0
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.4
kitchen version: 1.22.0
inspec version: 2.1.72

root@f522b19d0a71:/# cat > test.rb <<EOF
> uri = 'http://127.0.0.1:12345/foo?bar=baz'
> http = Chef::HTTP::Simple.new(uri)
> http.get(uri)
> EOF
root@f522b19d0a71:/# chef-apply test.rb 
[2018-07-12T17:12:10+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz, retry 1/5
[2018-07-12T17:12:15+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz, retry 2/5
[2018-07-12T17:12:20+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz, retry 3/5
[2018-07-12T17:12:25+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz, retry 4/5
[2018-07-12T17:12:30+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz, retry 5/5
[2018-07-12T17:12:35+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-07-12T17:12:35+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-07-12T17:12:35+00:00] FATAL: Errno::ECONNREFUSED: Connection refused - Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz, giving up
root@97d8dcb38d2a:/#
root@97d8dcb38d2a:/#
root@97d8dcb38d2a:/# chef gem install chef -v 14.3.37
Fetching: chef-config-14.3.37.gem (100%)
WARNING:  You don't have /root/.chefdk/gem/ruby/2.5.0/bin in your PATH,
	  gem executables will not run.
Successfully installed chef-config-14.3.37
Fetching: chef-14.3.37.gem (100%)
Successfully installed chef-14.3.37
2 gems installed
root@97d8dcb38d2a:/# /opt/chefdk/embedded/bin/chef-apply --version
Chef: 14.3.37
root@97d8dcb38d2a:/# /opt/chefdk/embedded/bin/chef-apply test.rb 
[2018-07-12T17:14:00+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz, retry 1/5
[2018-07-12T17:14:00+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz, retry 1/5
[2018-07-12T17:14:05+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz, retry 2/5
[2018-07-12T17:14:05+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz, retry 2/5
[2018-07-12T17:14:10+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz?bar=baz, retry 3/5
[2018-07-12T17:14:10+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz?bar=baz, retry 3/5
[2018-07-12T17:14:15+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz, retry 4/5
[2018-07-12T17:14:15+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz, retry 4/5
[2018-07-12T17:14:20+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz, retry 5/5
[2018-07-12T17:14:20+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz, retry 5/5
[2018-07-12T17:14:25+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-07-12T17:14:25+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-07-12T17:14:25+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-07-12T17:14:25+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-07-12T17:14:25+00:00] FATAL: Errno::ECONNREFUSED: Connection refused - Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz, giving up
[2018-07-12T17:14:25+00:00] FATAL: Errno::ECONNREFUSED: Connection refused - Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz, giving up
root@97d8dcb38d2a:/#
root@97d8dcb38d2a:/#
root@97d8dcb38d2a:/# /opt/chefdk/embedded/bin/chef-apply test.rb -l debug
[2018-07-12T17:14:51+00:00] DEBUG: Running Ohai with the following configuration: {:logger=>#<Mixlib::Log::Child:0x0000000001d4b678 @parent=Chef::Log, @metadata={:system=>"ohai", :version=>"14.3.0"}>}
[2018-07-12T17:14:51+00:00] DEBUG: Running Ohai with the following configuration: {:logger=>#<Mixlib::Log::Child:0x0000000001d4b678 @parent=Chef::Log, @metadata={:system=>"ohai", :version=>"14.3.0"}>}
[2018-07-12T17:14:51+00:00] DEBUG: Running Ohai with the following configuration: {:logger=>#<Mixlib::Log::Child:0x0000000001d4b678 @parent=Chef::Log, @metadata={:system=>"ohai", :version=>"14.3.0"}>}
[2018-07-12T17:14:51+00:00] DEBUG: Running Ohai with the following configuration: {:logger=>#<Mixlib::Log::Child:0x0000000001d4b678 @parent=Chef::Log, @metadata={:system=>"ohai", :version=>"14.3.0"}>}
[2018-07-12T17:14:52+00:00] DEBUG: Extracting run list from JSON attributes provided on command line
[2018-07-12T17:14:52+00:00] DEBUG: Extracting run list from JSON attributes provided on command line
[2018-07-12T17:14:52+00:00] DEBUG: Applying attributes from json file
[2018-07-12T17:14:52+00:00] DEBUG: Applying attributes from json file
[2018-07-12T17:14:52+00:00] DEBUG: Platform is ubuntu version 16.04
[2018-07-12T17:14:52+00:00] DEBUG: Platform is ubuntu version 16.04
[2018-07-12T17:14:52+00:00] INFO: Run List is []
[2018-07-12T17:14:52+00:00] INFO: Run List is []
[2018-07-12T17:14:52+00:00] INFO: Run List expands to []
[2018-07-12T17:14:52+00:00] INFO: Run List expands to []
[2018-07-12T17:14:52+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz, retry 1/5
[2018-07-12T17:14:52+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz, retry 1/5
[2018-07-12T17:14:57+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz, retry 2/5
[2018-07-12T17:14:57+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz, retry 2/5
[2018-07-12T17:15:02+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz?bar=baz, retry 3/5
[2018-07-12T17:15:02+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz?bar=baz, retry 3/5
[2018-07-12T17:15:07+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz, retry 4/5
[2018-07-12T17:15:07+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz, retry 4/5
[2018-07-12T17:15:12+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz, retry 5/5
[2018-07-12T17:15:12+00:00] ERROR: Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz, retry 5/5
[2018-07-12T17:15:17+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-07-12T17:15:17+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-07-12T17:15:17+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-07-12T17:15:17+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-07-12T17:15:17+00:00] DEBUG: Errno::ECONNREFUSED: Connection refused - Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz, giving up
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:437:in `rescue in retrying_http_errors'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:408:in `retrying_http_errors'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:365:in `send_http_request'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:149:in `request'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:115:in `get'
test.rb:3:in `run_chef_recipe'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/application/apply.rb:192:in `instance_eval'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/application/apply.rb:192:in `run_chef_recipe'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/application/apply.rb:204:in `run_application'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/application/apply.rb:216:in `run'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/bin/chef-apply:24:in `<top (required)>'
/opt/chefdk/embedded/bin/chef-apply:23:in `load'
/opt/chefdk/embedded/bin/chef-apply:23:in `<main>'

>>>> Caused by Errno::ECONNREFUSED: Failed to open TCP connection to 127.0.0.1:12345 (Connection refused - connect(2) for "127.0.0.1" port 12345)
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect'
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
/opt/chefdk/embedded/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/opt/chefdk/embedded/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:935:in `connect'
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:909:in `start'
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:1455:in `request'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http/basic_client.rb:69:in `request'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:372:in `block in send_http_request'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:411:in `block in retrying_http_errors'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:409:in `loop'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:409:in `retrying_http_errors'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:365:in `send_http_request'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:149:in `request'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:115:in `get'
test.rb:3:in `run_chef_recipe'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/application/apply.rb:192:in `instance_eval'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/application/apply.rb:192:in `run_chef_recipe'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/application/apply.rb:204:in `run_application'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/application/apply.rb:216:in `run'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/bin/chef-apply:24:in `<top (required)>'
/opt/chefdk/embedded/bin/chef-apply:23:in `load'
/opt/chefdk/embedded/bin/chef-apply:23:in `<main>'

>>>> Caused by Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 12345
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:937:in `initialize'
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:937:in `open'
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:937:in `block in connect'
/opt/chefdk/embedded/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/opt/chefdk/embedded/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:935:in `connect'
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:909:in `start'
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:1455:in `request'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http/basic_client.rb:69:in `request'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:372:in `block in send_http_request'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:411:in `block in retrying_http_errors'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:409:in `loop'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:409:in `retrying_http_errors'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:365:in `send_http_request'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:149:in `request'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:115:in `get'
test.rb:3:in `run_chef_recipe'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/application/apply.rb:192:in `instance_eval'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/application/apply.rb:192:in `run_chef_recipe'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/application/apply.rb:204:in `run_application'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/application/apply.rb:216:in `run'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/bin/chef-apply:24:in `<top (required)>'
/opt/chefdk/embedded/bin/chef-apply:23:in `load'
/opt/chefdk/embedded/bin/chef-apply:23:in `<main>'
[2018-07-12T17:15:17+00:00] DEBUG: Errno::ECONNREFUSED: Connection refused - Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz, giving up
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:437:in `rescue in retrying_http_errors'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:408:in `retrying_http_errors'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:365:in `send_http_request'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:149:in `request'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:115:in `get'
test.rb:3:in `run_chef_recipe'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/application/apply.rb:192:in `instance_eval'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/application/apply.rb:192:in `run_chef_recipe'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/application/apply.rb:204:in `run_application'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/application/apply.rb:216:in `run'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/bin/chef-apply:24:in `<top (required)>'
/opt/chefdk/embedded/bin/chef-apply:23:in `load'
/opt/chefdk/embedded/bin/chef-apply:23:in `<main>'

>>>> Caused by Errno::ECONNREFUSED: Failed to open TCP connection to 127.0.0.1:12345 (Connection refused - connect(2) for "127.0.0.1" port 12345)
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:939:in `rescue in block in connect'
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:936:in `block in connect'
/opt/chefdk/embedded/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/opt/chefdk/embedded/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:935:in `connect'
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:909:in `start'
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:1455:in `request'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http/basic_client.rb:69:in `request'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:372:in `block in send_http_request'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:411:in `block in retrying_http_errors'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:409:in `loop'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:409:in `retrying_http_errors'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:365:in `send_http_request'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:149:in `request'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:115:in `get'
test.rb:3:in `run_chef_recipe'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/application/apply.rb:192:in `instance_eval'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/application/apply.rb:192:in `run_chef_recipe'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/application/apply.rb:204:in `run_application'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/application/apply.rb:216:in `run'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/bin/chef-apply:24:in `<top (required)>'
/opt/chefdk/embedded/bin/chef-apply:23:in `load'
/opt/chefdk/embedded/bin/chef-apply:23:in `<main>'

>>>> Caused by Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 12345
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:937:in `initialize'
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:937:in `open'
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:937:in `block in connect'
/opt/chefdk/embedded/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
/opt/chefdk/embedded/lib/ruby/2.5.0/timeout.rb:103:in `timeout'
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:935:in `connect'
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:909:in `start'
/opt/chefdk/embedded/lib/ruby/2.5.0/net/http.rb:1455:in `request'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http/basic_client.rb:69:in `request'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:372:in `block in send_http_request'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:411:in `block in retrying_http_errors'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:409:in `loop'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:409:in `retrying_http_errors'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:365:in `send_http_request'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:149:in `request'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/http.rb:115:in `get'
test.rb:3:in `run_chef_recipe'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/application/apply.rb:192:in `instance_eval'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/application/apply.rb:192:in `run_chef_recipe'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/application/apply.rb:204:in `run_application'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/lib/chef/application/apply.rb:216:in `run'
/root/.chefdk/gem/ruby/2.5.0/gems/chef-14.3.37/bin/chef-apply:24:in `<top (required)>'
/opt/chefdk/embedded/bin/chef-apply:23:in `load'
/opt/chefdk/embedded/bin/chef-apply:23:in `<main>'
[2018-07-12T17:15:17+00:00] FATAL: Errno::ECONNREFUSED: Connection refused - Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz, giving up
[2018-07-12T17:15:17+00:00] FATAL: Errno::ECONNREFUSED: Connection refused - Connection refused connecting to http://127.0.0.1:12345/foo?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz?bar=baz, giving up

```

**Comment by lamont-granquist** [comment]
git bisect blames 0bdd618fc5146dad3fa5a90d10a4b5e608e4663d

**Comment by lamont-granquist** [comment]
this is the line which changed the behavior:  https://github.com/chef/chef/commit/0bdd618fc5146dad3fa5a90d10a4b5e608e4663d#diff-78ed46378e56c347328202ad1c8b7d39R155

**Comment by lamont-granquist** [comment]
https://github.com/rubocop-hq/rubocop/issues/6099
