### ISSUE TITLE
rhsm_register error "No such file or directory - subsription-manager"

### ISSUE THREAD

**Issue by Stromweld** [chef/chef#7494]
## Description
receiving error 'rhsm_register error "No such file or directory - subsription-manager"'

## Chef Version
14.3.37

## Platform Version
centos 7.4

## Replication Case
recipe using rhsm_register resource
```
rhsm_register node['hostname'] do
  activation_key 'ecample'
  satellite_host 'satellite.example.com'
  organization 'company'
  install_katello_agent true
  environment 'production'
end
```

## Client Output
```
       Recipe: pl_katello_client::default
         * yum_package[yum-utils, yum-cron] action install (up to date)
         * rhsm_register[default-centos-7] action register

           ================================================================================
           Error executing action `register` on resource 'rhsm_register[default-centos-7]'
           ================================================================================

           Errno::ENOENT
           -------------
           No such file or directory - subscription-manager

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/pl_katello_client/recipes/default.rb

            15: rhsm_register node['hostname'] do
            16:   activation_key node['pl_katello_client']['key']
            17:   satellite_host node['pl_katello_client']['host']
            18:   organization node['pl_katello_client']['org']
            19:   install_katello_agent true
            20:   environment node['pl_katello_client']['environment']
            21:   action :register
            22: end
            23:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/pl_katello_client/recipes/default.rb:15:in `from_file'

           rhsm_register("default-centos-7") do
             action [:register]
             default_guard_interpreter :default
             declared_type :rhsm_register
             cookbook_name "pl_katello_client"
             recipe_name "default"
             activation_key ["Centos"]
             satellite_host "foreman.pmdomhq.protomold.com"
             organization "Proto_Labs"
             install_katello_agent true
             environment "dev"
           end

           System Info:
           ------------
           chef_version=14.3.37
           platform=centos
           platform_version=7.4.1708
           ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
           program_name=/opt/chef/bin/chef-client
           executable=/opt/chef/bin/chef-client


       Running handlers:
       [2018-07-19T17:16:42+00:00] ERROR: Running exception handlers
       [2018-07-19T17:16:42+00:00] ERROR: Running exception handlers
         - Chef::Handler::Slack
         - Chef::Handler::AuditReport
       Running handlers complete
       [2018-07-19T17:16:43+00:00] ERROR: Exception handlers complete
       [2018-07-19T17:16:43+00:00] ERROR: Exception handlers complete
       Chef Client failed. 3 resources updated in 08 seconds
       [2018-07-19T17:16:43+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-07-19T17:16:43+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-07-19T17:16:43+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-07-19T17:16:43+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-07-19T17:16:43+00:00] FATAL: Errno::ENOENT: rhsm_register[default-centos-7] (pl_katello_client::default line 15) had an error: Errno::ENOENT: No such file or directory - subscri
ption-manager
       [2018-07-19T17:16:43+00:00] FATAL: Errno::ENOENT: rhsm_register[default-centos-7] (pl_katello_client::default line 15) had an error: Errno::ENOENT: No such file or directory - subscri
ption-manager
```

## Stacktrace
```
[root@default-centos-7 ~]# cat /tmp/kitchen/cache/chef-stacktrace.out
Generated at 2018-07-19 17:16:43 +0000
Errno::ENOENT: rhsm_register[default-centos-7] (pl_katello_client::default line 15) had an error: Errno::ENOENT: No such file or directory - subscription-manager
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.3.2/lib/mixlib/shellout/unix.rb:340:in `exec'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.3.2/lib/mixlib/shellout/unix.rb:340:in `block in fork_subprocess'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.3.2/lib/mixlib/shellout/unix.rb:318:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.3.2/lib/mixlib/shellout/unix.rb:318:in `fork_subprocess'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.3.2/lib/mixlib/shellout/unix.rb:95:in `run_command'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.3.2/lib/mixlib/shellout.rb:263:in `run_command'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource/rhsm_register.rb:119:in `registered_with_rhsm?'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource/rhsm_register.rb:68:in `block in <class:RhsmRegister>'
(eval):2:in `block in action_register'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider.rb:236:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider.rb:236:in `compile_and_converge_action'
(eval):2:in `action_register'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider.rb:182:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource.rb:577:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/runner.rb:70:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/runner.rb:98:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/runner.rb:98:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/runner.rb:98:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/runner.rb:97:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/client.rb:720:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/client.rb:715:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/client.rb:715:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/client.rb:754:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/client.rb:286:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/application.rb:279:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/application.rb:261:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/application/client.rb:440:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/bin/chef-client:25:in `<top (required)>'
/opt/chef/bin/chef-client:75:in `load'
/opt/chef/bin/chef-client:75:in `<main>'

>>>> Caused by Errno::ENOENT: No such file or directory - subscription-manager
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.3.2/lib/mixlib/shellout/unix.rb:340:in `exec'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.3.2/lib/mixlib/shellout/unix.rb:340:in `block in fork_subprocess'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.3.2/lib/mixlib/shellout/unix.rb:318:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.3.2/lib/mixlib/shellout/unix.rb:318:in `fork_subprocess'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.3.2/lib/mixlib/shellout/unix.rb:95:in `run_command'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.3.2/lib/mixlib/shellout.rb:263:in `run_command'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource/rhsm_register.rb:119:in `registered_with_rhsm?'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource/rhsm_register.rb:68:in `block in <class:RhsmRegister>'
(eval):2:in `block in action_register'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider.rb:236:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider.rb:236:in `compile_and_converge_action'
(eval):2:in `action_register'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider.rb:182:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource.rb:577:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/runner.rb:70:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/runner.rb:98:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/runner.rb:98:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/runner.rb:98:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/runner.rb:97:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/client.rb:720:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/client.rb:715:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/client.rb:715:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/client.rb:754:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/client.rb:286:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/application.rb:279:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/application.rb:261:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/application/client.rb:440:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/bin/chef-client:25:in `<top (required)>'
/opt/chef/bin/chef-client:75:in `load'
```

**Comment by Stromweld** [comment]
according to the stack trace it doesn't like this line https://github.com/chef/chef/blob/master/lib/chef/resource/rhsm_register.rb#L119

**Comment by tas50** [comment]
@Stromweld Thanks for the report. This should be fixed by #7520

**Comment by tas50** [comment]
Merged for 14.4 release!

**Comment by Stromweld** [comment]
cool thanks @tas50

**Comment by Stromweld** [comment]
@tas50 Still getting the same error on chef-client 14.4.56
```
Starting Chef Client, version 14.4.56
       Creating a new client identity for default-centos-7 using the validator key.
       resolving cookbooks for run list: ["pl_katello_client::default"]
       Synchronizing Cookbooks:
         - pl_katello_client (2.0.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       Converging 3 resources
       Recipe: pl_katello_client::default
         * yum_package[yum-utils, yum-cron] action install
           - install version 0:3.4.3-158.el7.centos.noarch of package yum-cron
         * rhsm_register[default-centos-7] action register

           ================================================================================
           Error executing action `register` on resource 'rhsm_register[default-centos-7]'
           ================================================================================

           Errno::ENOENT
           -------------
           No such file or directory - subscription-manager

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/pl_katello_client/recipes/default.rb

            15: rhsm_register node['hostname'] do
            16:   activation_key node['pl_katello_client']['key']
            17:   satellite_host node['pl_katello_client']['host']
            18:   organization node['pl_katello_client']['org']
            19:   install_katello_agent true
            20:   environment node['pl_katello_client']['environment']
            21: end
            22:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/pl_katello_client/recipes/default.rb:15:in `from_file'

           rhsm_register("default-centos-7") do
             action [:register]
             default_guard_interpreter :default
             declared_type :rhsm_register
             cookbook_name "pl_katello_client"
             recipe_name "default"
             activation_key ["Centos"]
             satellite_host "foreman.pmdomhq.protomold.com"
             organization "Proto_Labs"
             install_katello_agent true
             environment "dev"
           end

           System Info:
           ------------
           chef_version=14.4.56
           platform=centos
           platform_version=7.5.1804
           ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
           program_name=/opt/chef/bin/chef-client
           executable=/opt/chef/bin/chef-client


       Running handlers:
       [2018-09-14T23:07:11+00:00] ERROR: Running exception handlers
       [2018-09-14T23:07:11+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2018-09-14T23:07:11+00:00] ERROR: Exception handlers complete
       [2018-09-14T23:07:11+00:00] ERROR: Exception handlers complete
       Chef Client failed. 1 resources updated in 12 seconds
       [2018-09-14T23:07:11+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-09-14T23:07:11+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-09-14T23:07:11+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-09-14T23:07:11+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-09-14T23:07:11+00:00] FATAL: Errno::ENOENT: rhsm_register[default-centos-7] (pl_katello_client::default line 15) had an error: Errno::ENOENT: No such file or directory - subscription-manager
       [2018-09-14T23:07:11+00:00] FATAL: Errno::ENOENT: rhsm_register[default-centos-7] (pl_katello_client::default line 15) had an error: Errno::ENOENT: No such file or directory - subscription-manager
```
