### ISSUE TITLE
chocolatey_package NoMethodError    undefined method `allow_downgrade' for Chef::Resource::ChocolateyPackage

### ISSUE THREAD

**Issue by timbrown5** [chef/chef#7544]
## Description
Recieve an error message say 'allow_downgrade' is not a known method  when trying to download a already installed chocolatey package:

NoMethodError
-------------
undefined method `allow_downgrade' for Chef::Resource::ChocolateyPackage

I thought this might be a conflict with the chocolatey cookbook version of chocolatey_package, but updated to chocolatey 2.0.1 (which doesn't have the chocolatey_package resource) hasn't helped.

## Chef Version
Chef-client 13.10.4
Chef server 12.3.0-1
Chocolatey cookbook 2.0.1

## Platform Version
Windows 10

## Replication Case
The chef snippet which is showing this issue is :

```
if platform_family?('windows')
    include_recipe 'sn_pkg::chocolatey'

    chocolatey_package "git" do
        source  "https://chocolatey.org/api/v2/"
        version "2.18.0"
        action  :upgrade
        options '--allowdowngrade --ignorepackagecodes'
    end

        chocolatey_package "git" do
        source  "https://chocolatey.org/api/v2/"
        version "2.17.1.2"
        action  :upgrade
        options '--allowdowngrade --ignorepackagecodes'
    end
end
```

## Client Output
```
[2018-08-14T14:05:30+01:00] DEBUG: chocolatey_package[git] git 2.18.0 is already installed -- you are equality pinning with an :upgrade action, this may be deprecated in the future
[2018-08-14T14:05:30+01:00] DEBUG: chocolatey_package[git] no versions to upgrade - nothing to do
 (up to date)
  * chocolatey_package[git] action upgrade[2018-08-14T14:05:30+01:00] INFO: Processing chocolatey_package[git] action upgrade (sn_pkg::failing_git line 11)
[2018-08-14T14:05:30+01:00] DEBUG: Providers for generic chocolatey_package resource enabled on node include: [Chef::Provider::Package::Chocolatey]
[2018-08-14T14:05:30+01:00] DEBUG: Provider for action upgrade on resource chocolatey_package[git] is Chef::Provider::Package::Chocolatey
C:\ProgramData\chocolatey
chocolatey|0.10.8
chocolatey-core.extension|1.3.3
chocolatey-uninstall.extension|1.2.0
dbs|2.5.7.310
everything|1.4.1895.20180530
git|2.18.0
git.install|2.18.0
imdisk|2.0.9.20170202
meld|3.16.2
notepadplusplus|7.5.8
notepadplusplus.install|7.5.8
orbis-all|5.50.91.1
orbis-controllercapture|5.50.0.11
orbis-debugger|5.50.0.11
orbis-eventviewer|5.50.0.12
orbis-hosttools|5.50.7.1
orbis-memoryanalyzer|5.50.0.14
orbis-neighborhood|5.50.0.12
orbis-networkmanager|5.0.0.1825
orbis-playgoviewer|5.50.0.11
orbis-razor|5.50.0.13
orbis-remoteviewer|5.50.0.12
orbis-remoteviewerserver|5.50.0.11
orbis-screencapture|5.50.0.11
orbis-sdk|5.50.0.07
orbis-telemetrycollector|0.0.0.3
orbis-tmserver|5.50.0.10
orbis-toolchain|5.50.0.91
orbis-usbdriver|5.0.0.1825
sce-filesystemdriver|6.1.184.15
sn_DotNet3.5|3.5.20180809
sn_DotNet4.5.2|4.5.51209
sn_DotNet4.6|4.6.20160427
sn_VisualStudio2015Professional|14.0.23107
sn_VisualStudio2017Professional|15.7.3
sn_Windows10_CreatorsUpdate|10.0.1703
vsi-2015|2.5.1.4
vsi-2017|2.5.1.4
vsi-all|2.5.1.4
git|2.18.0
git.install|2.18.0
git-lfs|2.5.1
GitHub|3.2.0.0
poshgit|0.7.3.1
ConEmu|18.6.26.0
GitVersion.Portable|3.6.4
SourceTree|2.6.10
git-lfs.install|2.5.1
TortoiseGit|2.6.0.0
gitextensions|2.51.4
Git-Credential-Manager-for-Windows|1.15.2
gittfs|0.29.0
Paket.PowerShell|4.8.8
Atom|1.29.0
git-credential-winstore|2.0.0.20151206
gitlink|3.0.0
msysgit|1.7.10.20120526
Git-TF|2.0.3.20131219
gitkraken|3.6.4
git.commandline|2.11.0.20170203
Paket|5.176.4
Posh-GitHub|0.0.2
git.portable|2.18.0
SublimeText3.PackageControl|2.0.0.20140915
vscode|1.26.0
SmartGit|18.1.3
GitReleaseNotes.Portable|0.7.1
githublink|2.3.0
cyg-get|1.2.1
vsts-sync-migrator|7.5.40
eclipse|4.8.0
git-annex|6.20180227
legitest|2018.2.4.504
github-desktop|1.3.2
Cmder|1.3.5
gitreleasemanager.portable|0.7.1
githubforwindows|2.13.0.2
EthanBrown.ConEmuConfig|0.0.5
gitlab-runner|11.1.0
dotnetcore-windowshosting|2.1.2
TimRayburn.GitAliases|1.2.0
docfx|2.38
hub|2.2.9
Posh-GIT-HG|1.0.4
MarkdownMonster|1.12.10
EthanBrown.GitAliases|0.0.5
Dogtail.VisualStudioToolsforGit|11.2.13230.2
GitDepend.Portable|0.5.0
EthanBrown.GitConfiguration|0.0.4
adobedigitaleditions|4.5.7
dotnetcore-runtime.install|2.1.2
BigGit|1.1.5
jivkok.GitConfig|1.0.1.0
vcxsrv|1.20.0.1
dotnetcore-runtime|2.1.2
PsVso|0.6
GitVersion|1.0.0.1
git-flow-dependencies|0.2
babun|1.2.0.20180102
ungit|0.10.1
logitechgaming|9.00.42
EthanBrown.SublimeText2.GitPackages|0.2.2
dotnetcore|2.1.2
JayHankins.ConEmuConfig|0.0.8
smartgit-with-jre|7.1.1
hugo|0.45
util-linux-ng-getopt|2.14.1
util-linux-ng-libintl3|2.14.1
Devbox-GitFlow|0.0.0
splunkforwarder|6.5.1.1
git-helper|1.5
wincommandpaste|1.1.0.20150826
railsinstaller|3.1.0
git-disable-gcm|1.0.0
TortoiseGit.latest|1.7.15
deepgit|3.0.3
docker-toolbox|18.03.0
gitblit|1.6.2
Devbox-GitSettings|1.0.1
GitReleaseNotes|0.6.1
bfg-repo-cleaner|1.13.0
EthanBrown.GitExtensionsConfiguration|0.0.1
snagit|18.1.1
LibGit2.PowerShell|0.10.1
sparkleshare|1.5.0.20161115
EthanBrown.DevTools.Web|0.3.1
aspnetcore-runtimepackagestore|2.1.2
gitpad|1.2
phpstorm|2018.2.1
PdbGit|3.0.38
getignore|1.0.0.20170723
SemanticMerge|0.9.17.0
posh-ci-git|0.0.1
visualstudio-github|2.2.0.8
nodist|0.8.8
GitDiffMargin.vs2012|1.0
gitter|4.1.0
SublimeText2.PackageControl|1.6.3
jivkok.SublimeText3.Packages|1.0.0.12
aptana-studio|3.7.2
markdown-edit|1.33
PsVsts|1.0.0
mkdocs-material|3.0.3
GitSvnExternals|1.1.0.7
GitDiffMargin.vs2013|2.0.0
invantive-data-hub|17.24.18
git-lfx|0.1.0
vscode-gitignore|0.5.0
pik|0.3.0
gitflow-hooks|1.0.1
gitg.install|3.20.0
pullrequestreleasenotes|1.1.2
git-phlow|3.8.20
giteye|1.5.0
git-lfs-bitbucket-adapter|1.0.6
qtpass|1.2.3
gitg|3.20.0
GitVersioner|1.0.1.14
git-sizer|1.2.0
vscode.portable|1.26.0
redis-desktop-manager|0.8.0.3840
githubsearch|1.2.2
CouchPotato|2012.11.04.1
vscode-gitattributes|0.4.1
openshift-cli|3.10.0
rambox|0.5.17
gitbook-editor|7.0.12
goldendict.install|1.0.1
jivkok.dev1|1.1.0.8
jivkok.tools|1.1.0.7
SickBeard|2012.11.04.1
git-fork|1.20.0
EthanBrown.SublimeText2.EditorPackages|0.2.2
mkdocs|1.0.1
balsamiqmockups.install|1.0.8
splunk-universalforwarder|7.0.1
MarkdownMonster.Portable|1.12.4
balsamiqmockups3|3.4.4
invantive-bridge-power-bi-users|17.24.9
specflow|1.8.1
caddy|0.9.5
vsts-cli|0.1.1
whats-new|1.0.23
googlechrome-zenhub|1.0.0
caret|3.4.6
techsmithsnagit|12.3.1
skype-utility-project|1.4.0
alanstevens.vsextensions|1.07
keeweb|1.6.3
compactgui|2.6.2
dotnetcore-runtime.portable|2.1.2
gogs|0.11.53
flashdevelop|5.3.3.0
SpringToolSuite|3.9.5
alanstevens.vs2012extensions|1.03
logitech-media-server|7.7.5.20161008
gitforce|1.0.50
goldendict.portable|1.0.1
goldendict|1.0.1
cgithubinst|0.1.2
powergist|1.0.15
gh-api-cli|4.0.2
ioquake3.install|1.36
pass-winmenu|1.7
markdowneditor|1.8.159
invantive-bridge-connectors-power-bi|17.24.8
googlechrome-github-expandinizr|1.0.0
edgedeflector|1.1.3.0
vvvv-addonpack.x86|29.2
bitwarden|1.5.0
wave-engine|2.5.0
vvvv-addonpack.x64|29.2
ioquake3|1.36
dnscontrol|0.2.6
SuperCollider|3.9.3.0
invantive-bridge-developers|17.24.9
goldendict-en-ru-en.install|1.0.1
vim-x86.install|7.4.1825
github-hovercard-chrome|1.4.4
justread-chrome|1.1.12


    ================================================================================
    Error executing action `upgrade` on resource 'chocolatey_package[git]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `allow_downgrade' for Chef::Resource::ChocolateyPackage

    Resource Declaration:
    ---------------------
    # In c:/chef/cache/cookbooks/sn_pkg/recipes/failing_git.rb

     11:         chocolatey_package "git" do
     12:         source  "https://chocolatey.org/api/v2/"
     13:         version "2.17.1.2"
     14:         action  :upgrade
     15:         options '--allowdowngrade --ignorepackagecodes'
     16:     end
     17: end

    Compiled Resource:
    ------------------
    # Declared in c:/chef/cache/cookbooks/sn_pkg/recipes/failing_git.rb:11:in `from_file'

    chocolatey_package("git") do
      package_name ["git"]
      action [:upgrade]
      default_guard_interpreter :default
      declared_type :chocolatey_package
      cookbook_name "sn_pkg"
      recipe_name "failing_git"
      source "https://chocolatey.org/api/v2/"
      version ["2.17.1.2"]
      options "--allowdowngrade --ignorepackagecodes"
    end

    System Info:
    ------------
    chef_version=13.10.4
    platform=windows
    platform_version=10.0.17134
    ruby=ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]
    program_name=C:/opscode/chef/bin/chef-client
    executable=C:/opscode/chef/bin/chef-client

[2018-08-14T14:05:35+01:00] INFO: Running queued delayed notifications before re-raising exception
[2018-08-14T14:05:35+01:00] DEBUG: Re-raising exception: NoMethodError - chocolatey_package[git] (sn_pkg::failing_git line 11) had an error: NoMethodError: undefined method `allow_downgrade' for Chef::Resource::ChocolateyPackage
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/resource.rb:1298:in `method_missing'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/provider/package.rb:483:in `block in target_version_array'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/provider/package.rb:577:in `block in each_package'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/provider/package.rb:573:in `each'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/provider/package.rb:573:in `each_with_index'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/provider/package.rb:573:in `each_package'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/provider/package.rb:467:in `target_version_array'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/provider/package.rb:121:in `block in <class:Package>'
  (eval):2:in `block in action_upgrade'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/provider.rb:225:in `instance_eval'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/provider.rb:225:in `compile_and_converge_action'
  (eval):2:in `action_upgrade'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/provider.rb:171:in `run_action'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/resource.rb:592:in `run_action'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/runner.rb:70:in `run_action'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/runner.rb:98:in `block (2 levels) in converge'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/runner.rb:98:in `each'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/runner.rb:98:in `block in converge'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/runner.rb:97:in `converge'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/client.rb:718:in `block in converge'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/client.rb:713:in `catch'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/client.rb:713:in `converge'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/client.rb:752:in `converge_and_save'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/client.rb:286:in `run'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/application.rb:274:in `run_with_graceful_exit_option'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/application.rb:250:in `block in run_chef_client'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/application.rb:233:in `run_chef_client'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/application/client.rb:470:in `sleep_then_run_chef_client'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/application/client.rb:459:in `block in interval_run_chef_client'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/application/client.rb:458:in `loop'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/application/client.rb:458:in `interval_run_chef_client'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/application/client.rb:442:in `run_application'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/application.rb:59:in `run'
  C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/bin/chef-client:26:in `<top (required)>'
  C:/opscode/chef/bin/chef-client:75:in `load'
  C:/opscode/chef/bin/chef-client:75:in `<main>'

Running handlers:
[2018-08-14T14:05:35+01:00] ERROR: Running exception handlers
Running handlers complete
[2018-08-14T14:05:35+01:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 14 seconds
[2018-08-14T14:05:35+01:00] DEBUG: Server doesn't support resource history, skipping resource report.
[2018-08-14T14:05:35+01:00] DEBUG: Audit Reports are disabled. Skipping sending reports.
[2018-08-14T14:05:35+01:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
[2018-08-14T14:05:35+01:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-08-14T14:05:35+01:00] DEBUG: NoMethodError: chocolatey_package[git] (sn_pkg::failing_git line 11) had an error: NoMethodError: undefined method `allow_downgrade' for Chef::Resource::ChocolateyPackage
```

## Stacktrace
```
Generated at 2018-08-14 14:05:35 +0100
NoMethodError: chocolatey_package[git] (sn_pkg::failing_git line 11) had an error: NoMethodError: undefined method `allow_downgrade' for Chef::Resource::ChocolateyPackage
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/resource.rb:1298:in `method_missing'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/provider/package.rb:483:in `block in target_version_array'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/provider/package.rb:577:in `block in each_package'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/provider/package.rb:573:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/provider/package.rb:573:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/provider/package.rb:573:in `each_package'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/provider/package.rb:467:in `target_version_array'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/provider/package.rb:121:in `block in <class:Package>'
(eval):2:in `block in action_upgrade'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/provider.rb:225:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/provider.rb:225:in `compile_and_converge_action'
(eval):2:in `action_upgrade'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/provider.rb:171:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/resource.rb:592:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/runner.rb:70:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/runner.rb:98:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/runner.rb:98:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/runner.rb:98:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/runner.rb:97:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/client.rb:718:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/client.rb:713:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/client.rb:713:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/client.rb:752:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/client.rb:286:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/application.rb:274:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/application.rb:250:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/application.rb:233:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/application/client.rb:470:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/application/client.rb:459:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/application/client.rb:458:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/application/client.rb:458:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/application/client.rb:442:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.10.4-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:75:in `load'
C:/opscode/chef/bin/chef-client:75:in `<main>'
```

**Comment by lamont-granquist** [comment]
This is fixed in Chef-14 by 0ef96784ff

**Comment by lamont-granquist** [comment]
#6942

**Comment by tas50** [comment]
@timbrown5 I've backported this to Chef 13 and it will ship with the next release *soon* https://github.com/chef/chef/pull/7548

**Comment by timbrown5** [comment]
Thanks for the help :-)
