### ISSUE TITLE
Yum python helper is not matching versions correctly when using version

### ISSUE THREAD

**Issue by tarcinil** [chef/chef#7552]
## Description
The yum python helper is incorrectly matching package versions when using version/source.

## Chef Version
chef_version=14.3.37

## Platform Version
platform=redhat
platform_version=6.10
ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]

## Replication Case
When running package with a version and source, python helper is incorrectly matching package versions.

Compiled Resource:
```
# Declared in /var/chef/cache/cookbooks/sensu/recipes/default.rb:31:in `from_file'

yum_package("sensu") do
  package_name "sensu"
  action [:install]
  default_guard_interpreter :default
  declared_type :package
  cookbook_name "sensu"
  recipe_name "default"
  source "/var/chef/cache/sensu-1.2.1-2.el6.x86_64.rpm"
  version "1.2.1-2.el6"
end
```

## Client Output
```
[2018-08-15T13:42:41-05:00] TRACE: Provider for action create on resource remote_file[/var/chef/cache/sensu-1.2.1-2.el6.x86_64.rpm] is Chef::Provider::RemoteFile
[2018-08-15T13:42:41-05:00] TRACE: remote_file[/var/chef/cache/sensu-1.2.1-2.el6.x86_64.rpm] checksumming file at /var/chef/cache/sensu-1.2.1-2.el6.x86_64.rpm.
[2018-08-15T13:42:42-05:00] TRACE: remote_file[/var/chef/cache/sensu-1.2.1-2.el6.x86_64.rpm] checking for changes
[2018-08-15T13:42:42-05:00] TRACE: remote_file[/var/chef/cache/sensu-1.2.1-2.el6.x86_64.rpm] checksum matches target checksum (71ae4c1cf963fdb700bfa914c66f503e8ee0c3a6dc39a2044ea0f111da7f3601) - not updating
[2018-08-15T13:42:42-05:00] TRACE: Found target_mode == current_mode, not updating mode
[2018-08-15T13:42:42-05:00] TRACE: Found target_uid == current_uid, not updating owner
[2018-08-15T13:42:42-05:00] TRACE: Found target_gid == current_gid, not updating group
[2018-08-15T13:42:42-05:00] INFO: Processing yum_package[sensu] action install (sensu::default line 31)
[2018-08-15T13:42:42-05:00] TRACE: Providers for generic yum_package resource enabled on node include: [Chef::Provider::Package::Yum]
[2018-08-15T13:42:42-05:00] TRACE: Provider for action install on resource yum_package[sensu] is Chef::Provider::Package::Yum
[2018-08-15T13:42:42-05:00] TRACE: sending '{"action":"whatinstalled","provides":"sensu","version":"1.2.1","release":"2.el6"}' to python helper
[2018-08-15T13:42:42-05:00] TRACE: got 'sensu 1:1.2.1-2.el6 x86_64' from python helper
[2018-08-15T13:42:42-05:00] TRACE: parsed sensu-1:1.2.1-2.el6.x86_64 from python helper
[2018-08-15T13:42:42-05:00] TRACE: sending '{"action":"versioncompare","versions":["1:1.2.1-2.el6.x86_64","1.2.1-2.el6"]}' to python helper
[2018-08-15T13:42:42-05:00] TRACE: got '1' from python helper
[2018-08-15T13:42:42-05:00] TRACE: sending '{"action":"versioncompare","versions":["1:1.2.1-2.el6.x86_64","1.2.1-2.el6"]}' to python helper
[2018-08-15T13:42:42-05:00] TRACE: got '1' from python helper
[2018-08-15T13:42:42-05:00] TRACE: yum_package[sensu] sensu 1:1.2.1-2.el6.x86_64 needs updating to 1.2.1-2.el6
[2018-08-15T13:42:42-05:00] TRACE: sending '{"action":"whatinstalled","provides":"sensu"}' to python helper
[2018-08-15T13:42:42-05:00] TRACE: got 'sensu 1:1.2.1-2.el6 x86_64' from python helper
[2018-08-15T13:42:42-05:00] TRACE: parsed sensu-1:1.2.1-2.el6.x86_64 from python helper
[2018-08-15T13:42:42-05:00] INFO: Running queued delayed notifications before re-raising exception
```

## Stacktrace
```
Traceback (most recent call last):
       16: from (eval):2:in `action_install'
       15: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider.rb:236:in `compile_and_converge_action'
       14: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider.rb:236:in `instance_eval'
       13: from (eval):2:in `block in action_install'
       12: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider/package.rb:100:in `block in <class:Package>'
       11: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider.rb:227:in `converge_by'
       10: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/mixin/why_run.rb:51:in `add_action'
        9: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider/package.rb:101:in `block (2 levels) in <class:Package>'
        8: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider/package.rb:269:in `multipackage_api_adapter'
        7: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider/package.rb:102:in `block (3 levels) in <class:Package>'
        6: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider/package/yum.rb:120:in `install_package'
        5: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider/package/yum.rb:263:in `yum'
        4: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/mixin/shell_out.rb:124:in `shell_out!'
        3: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/mixin/shell_out.rb:197:in `shell_out_compacted!'
        2: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.3.2/lib/mixlib/shellout.rb:280:in `error!'
        1: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.3.2/lib/mixlib/shellout.rb:293:in `invalid!'
Mixlib::ShellOut::ShellCommandFailed (yum_package[sensu] (sensu::default line 31) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1')
---- Begin output of ["yum", "-y", "install", "/var/chef/cache/sensu-1.2.1-2.el6.x86_64.rpm"] ----
STDOUT: Loaded plugins: product-id, search-disabled-repos, security, subscription-
              : manager
This system is not registered with an entitlement server. You can use subscription-manager to register.
Setting up Install Process
Examining /var/chef/cache/sensu-1.2.1-2.el6.x86_64.rpm: 1:sensu-1.2.1-2.el6.x86_64
/var/chef/cache/sensu-1.2.1-2.el6.x86_64.rpm: does not update installed package.
STDERR: Error: Nothing to do
---- End output of ["yum", "-y", "install", "/var/chef/cache/sensu-1.2.1-2.el6.x86_64.rpm"] ----
Ran ["yum", "-y", "install", "/var/chef/cache/sensu-1.2.1-2.el6.x86_64.rpm"] returned 1
```

**Comment by lamont-granquist** [comment]
the workaround that i'd suggest is not using version.  i'd actually suggest never using version or arch.  the yum provider correctly handles rpm NEVRAs now directly in the package name (with globs) so there shouldn't be any need for either of those properties.

**Comment by lamont-granquist** [comment]
It would also be useful to replicate this on chef >= 14.4.20 after eba0385cdd993554c70caf8c25926b4e867f80fe because this is at least related and the behavior may change.

**Comment by sspans** [comment]
We're hitting identical issues when upgrading to chef 14, however here the symptom is continual reinstallations of the sensu package. Which also seems to indicate busted version comparisons for yum_package.

I don't expect eba0385 to change things because the sensu cookbook enables allow_downgrade.

**Comment by sspans** [comment]
This indeed works as a workaround:

```
edit_resource(:yum_package, 'sensu') do
  name "sensu-#{node['sensu']['version']}"
  version nil
end
```

Results in
```
* yum_package[sensu-1.2.0-1] action install (up to date)
```

**Comment by tarcinil** [comment]
@lamont-granquist 

I can see where you are coming from, however, that method would move from an explicit model to an implicit model.  I think some organizations would not like an implicit model when it comes to maintaining their servers on a patching cycle.

We explicitly outline the versions that we install as a matter of fact.  This allows us to control things from our wrapper cookbooks all the way down to our site-cookbooks.

I reviewed the code a little and it appears that while python helper is a source of one-side of the comparison (left); I am guessing from NEVRA from `whatinstalled` action, I believe that the right side of the comparison is from the version meta-parameter from my input.

```
def compare_versions(version1, version2)
  query("versioncompare", { "versions" => [version1, version2] }).to_i
end
```

This leads to the trace output of 
```
[2018-08-15T13:42:42-05:00] TRACE: sending '{"action":"versioncompare","versions":["1:1.2.1-2.el6.x86_64","1.2.1-2.el6"]}' to python helper
```

I see a few possible outcomes:
- Munge whatinstalled output to remove `arch` so that comparison matching what is expected with the right-side.
- build the right-side of the comparison to include arch inside of it, using something like `Chef::Provider::Package::Yum::Version.version_with_arch`.

I believe that the second option is better as it maintains the workflow that the new python helper introduces but maintains the overall UX for the `package` resource (pre-helper), and eventually into the rpm_utils (I see a comment to replace the `#compare_versions` there).

Thoughts?

**Comment by lamont-granquist** [comment]
> I can see where you are coming from, however, that method would move from an explicit model to an implicit model.

So that is incorrect.  Whatever you can do with the version + arch properties you can now do directly in the package_name and more.  Anything syntax that `yum install` supports should be supported by `yum_package` now.  There is precisely nothing that you gain from using them, and I've documented edge cases in the code where they probably don't work well (and would be very complicated and delicate to fix).

So while I do consider this a bug, you're not going to get anywhere with arguing with me that the name and version properties are better in any sense.  The "workaround" has really become the vastly more reliable syntax that we don't have to piles of bug hunting to try to fix.

**Comment by lamont-granquist** [comment]
Okay so this actually just isn't a bug at all.  The sensu package has an epoch of '1' so this version comparison is entirely correct:

```
{"action":"versioncompare","versions":["1:1.2.1-2.el6.x86_64","1.2.1-2.el6"]}
1
```

if you either leave the epoch off, or include it on the other side then it works:

```
{"action":"versioncompare","versions":["1.2.1-2.el6.x86_64","1.2.1-2.el6"]}
0
{"action":"versioncompare","versions":["1:1.2.1-2.el6.x86_64","1:1.2.1-2.el6"]}
0
```

has actually nothing to do with the arch being set or not.

so this is strictly a bug in the sensu cookbook, that version string doesn't match the package.
