### ISSUE TITLE
apt_packages fails with error "Held packages were changed and -y was used without --allow-change-held-packages"

### ISSUE THREAD

**Issue by fasmat** [chef/chef#7556]
## Description

I try to configure a vagrant image with chef. The image I try to provision is an Ubuntu 18.04 and I provision it with chef_solo. Any pointers to what could be the issue would be helpful!

## Chef Version
14.3.37

## Platform Version
Ubuntu 18.04 amd64 destkop

## Replication Case
I have the following code recepies:

```
node.fetch("packages", []).each do |pkg|
  apt_package pkg["name"] do
    version pkg["version"] if pkg["version"]
    action :install
  end

  apt_package pkg["name"] do
    action :lock if pkg["version"]
  end
end
```

and my packages look like this:

```
"packages": [
    {
        "name": "curl"
    },
    {
        "name": "code",
        "version": "1.25.0-1530796411"
    },
    {
        "name": "build-essential"
    }
]
```

## Client Output

```
==> workstation: ================================================================================
==> workstation:     Error executing action `install` on resource 'apt_package[code]'
==> workstation:     ================================================================================
==> workstation:     
==> workstation:     Mixlib::ShellOut::ShellCommandFailed
==> workstation:     
==> workstation: ------------------------------------
==> workstation:     
==> workstation: Expected process to exit with [0], but received '100'
==> workstation:     ---- Begin output of ["apt-get", "-q", "-y", "-o", "Dpkg::Options::=--force-confdef", "-o", "Dpkg::Options::=--force-confold", "install", "code=1.25.0-1530796411"] ----
==> workstation:     STDOUT: Reading package lists...
==> workstation:     Building dependency tree...
==> workstation:     Reading state information...
==> workstation:     The following additional packages will be installed:
==> workstation:       gconf-service gconf-service-backend gconf2-common libgconf-2-4
==> workstation:     
==> workstation: The following NEW packages will be installed:
==> workstation:       code gconf-service gconf-service-backend gconf2-common libgconf-2-4
==> workstation:     The following held packages will be changed:
==> workstation:       code
==> workstation:     0 upgraded, 5 newly installed, 0 to remove and 32 not upgraded.
==> workstation:     STDERR: E: Held packages were changed and -y was used without --allow-change-held-packages.
==> workstation:     ---- End output of ["apt-get", "-q", "-y", "-o", "Dpkg::Options::=--force-confdef", "-o", "Dpkg::Options::=--force-confold", "install", "code=1.25.0-1530796411"] ----
==> workstation:     Ran ["apt-get", "-q", "-y", "-o", "Dpkg::Options::=--force-confdef", "-o", "Dpkg::Options::=--force-confold", "install", "code=1.25.0-1530796411"] returned 100
```

## Stacktrace

```
>>>> Caused by Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
---- Begin output of ["apt-get", "-q", "-y", "-o", "Dpkg::Options::=--force-confdef", "-o", "Dpkg::Options::=--force-confold", "install", "code=1.25.0-1530796411"] ----
STDOUT: Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  gconf-service gconf-service-backend gconf2-common libgconf-2-4
The following NEW packages will be installed:
  code gconf-service gconf-service-backend gconf2-common libgconf-2-4
The following held packages will be changed:
  code
0 upgraded, 5 newly installed, 0 to remove and 32 not upgraded.
STDERR: E: Held packages were changed and -y was used without --allow-change-held-packages.
---- End output of ["apt-get", "-q", "-y", "-o", "Dpkg::Options::=--force-confdef", "-o", "Dpkg::Options::=--force-confold", "install", "code=1.25.0-1530796411"] ----
Ran ["apt-get", "-q", "-y", "-o", "Dpkg::Options::=--force-confdef", "-o", "Dpkg::Options::=--force-confold", "install", "code=1.25.0-1530796411"] returned 100
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.3.2/lib/mixlib/shellout.rb:293:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.3.2/lib/mixlib/shellout.rb:280:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/mixin/shell_out.rb:197:in `shell_out_compacted!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/mixin/shell_out.rb:124:in `shell_out!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider/package/apt.rb:156:in `run_noninteractive'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider/package/apt.rb:95:in `install_package'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider/package.rb:102:in `block (3 levels) in <class:Package>'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider/package.rb:269:in `multipackage_api_adapter'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider/package.rb:101:in `block (2 levels) in <class:Package>'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/mixin/why_run.rb:51:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider.rb:227:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider/package.rb:100:in `block in <class:Package>'
(eval):2:in `block in action_install'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider.rb:236:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider.rb:236:in `compile_and_converge_action'
(eval):2:in `action_install'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/provider.rb:182:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource.rb:577:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/runner.rb:70:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/runner.rb:98:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/runner.rb:98:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/runner.rb:98:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/runner.rb:97:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/client.rb:720:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/client.rb:715:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/client.rb:715:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/client.rb:754:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/client.rb:286:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/application.rb:279:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/application.rb:261:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/application/client.rb:440:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/application/solo.rb:224:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/bin/chef-solo:24:in `<top (required)>'
/usr/bin/chef-solo:75:in `load'
```

EDIT: formatting

**Comment by lamont-granquist** [comment]
It looks like chef is behaving properly here and the lock from the prior run has put a hold on that package.

It needs to be unlocked in order to be un-held.

There's also the `options` property which could be used to shove `--force-yes` into the command line or shove `--allow-change-held-packages` into the command line.  But chef cannot do either of those by default for obvious reasons.

This boils down to a how-do-i-chef/how-do-i-apt question and not a bug.
