### ISSUE TITLE
Validatorless bootstrap fails 

### ISSUE THREAD

**Issue by Vasu1105** [chef/chef#7561]
## Description
Validatorless bootstrap fails with Error:

```
INFO: Using configuration from /home/msys/workspace/chef-repo/.chef/knife.rb
Doing old-style registration with the validation key at ...
Delete your validation key in order to use your user credentials instead
```

Validatorless bootstrap fails with knife bootstrap command.

I tried to bootstrap a VM using validator less bootstrap using following command 

```knife bootstrap azure@xx.xx.xxx.xxx --bootstrap-version 14.3.37 -P xxxxx -c ~/workspace/chef-repo/.chef/knife.rb --sudo -VV```

I don't have validation_key in my .chef directory and following are the entires of my knife.rb file. Also confirmed that there is no validation.pem on my workstation in /etc/chef directory as mentioned here
https://blog.chef.io/2015/04/16/validatorless-bootstraps/

```
current_dir = File.dirname(__FILE__)
log_level                :info
log_location             STDOUT
node_name                "test"
client_key               "#{current_dir}/xxxx.pem"
chef_server_url          "<chef-server-url>"
cookbook_path            ["#{current_dir}/../cookbooks"]
```

## Chef Version
chef-client v14.3.37
Also checked on master branch.

## Platform Version
Ubuntu 16.04 ( May be this is not platform specific)

## Replication Case
Create vm and then tried to bootstrap it using knife bootstrap command and using validatorless bootstrap. 
## Client Output
Following is the output of knife bootstrap command run.
```
Vasundhara:~/workspace$ knife bootstrap azure@xx.xxx.xxx.xxx --bootstrap-version 14.3.37 -P xxxxx -c ~/workspace/chef-repo/.chef/knife.rb --sudo -VV
INFO: Using configuration from /home/msys/workspace/chef-repo/.chef/knife.rb
Doing old-style registration with the validation key at ...
Delete your validation key in order to use your user credentials instead

Connecting to 40.112.181.122
Traceback (most recent call last):
	16: from /opt/chefdk/embedded/bin/knife:23:in `<main>'
	15: from /opt/chefdk/embedded/bin/knife:23:in `load'
	14: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/bin/knife:24:in `<top (required)>'
	13: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/application/knife.rb:161:in `run'
	12: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/knife.rb:220:in `run'
	11: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/knife.rb:441:in `run_with_pretty_exceptions'
	10: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	 9: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/knife.rb:442:in `block in run_with_pretty_exceptions'
	 8: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/knife/bootstrap.rb:391:in `run'
	 7: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/knife/bootstrap.rb:426:in `knife_ssh'
	 6: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/knife/bootstrap.rb:448:in `ssh_command'
	 5: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/knife/bootstrap.rb:354:in `render_template'
	 4: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `evaluate'
	 3: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `instance_eval'
	 2: from (erubis):196:in `block in evaluate'
	 1: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/knife/core/bootstrap_context.rb:49:in `validation_key'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/knife/core/bootstrap_context.rb:49:in `expand_path': no implicit conversion of nil into String (TypeError)
```

**Comment by coderanger** [comment]
Please run `knife config get` and add the output to this issue.

**Comment by coderanger** [comment]
Never mind, I see the bug. My fault, sorry.
