### ISSUE TITLE
chef 14.3.37 caller_location wrong for deprecations

### ISSUE THREAD

**Issue by kpmueller** [chef/chef#7577]
## Description
I'm running chef-client 14.3 after 13.10, looking for deprecations. It appears to be finding deprecations, but instead of showing where they are, it's printing the wrong caller location:

Examples:

```
Deprecated features used!
  Resource windows_auto_run has been loaded from a cookbook. The resource windows_auto_run is now included in Chef and will take precedence over the existing cookbook resource in the next major release of Chef (15.0, April 2019). You may be able to remove this cookbook dependency from your runlist if you do not use other recipes/resources/libraries from the cookbook. Alternatively there may be a newer version of this cookbook without the windows_auto_run resource. at 1 location:
    - /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/log.rb:51:in `caller_location'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
  Resource windows_feature has been loaded from a cookbook. The resource windows_feature is now included in Chef and will take precedence over the existing cookbook resource in the next major release of Chef (15.0, April 2019). You may be able to remove this cookbook dependency from your runlist if you do not use other recipes/resources/libraries from the cookbook. Alternatively there may be a newer version of this cookbook without the windows_feature resource. at 1 location:
    - /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/log.rb:51:in `caller_location'
   See https://docs.chef.io/deprecations_map_collision.html for further details.
```

## Chef Version
14.3.37

## Platform Version
ubuntu 14.04, ubuntu 18.04

## Replication Case
I don't have one yet, but I will add one if it's not seen by others 

## Client Output
see above

## Stacktrace
none

**Comment by kpmueller** [comment]
This doesn't seem to be a problem anymore now..

```
    - /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.3.37/lib/chef/log.rb:51:in `caller_location'
    - /var/chef/cache/cookbooks/sudo/resources/default.rb:27:in `class_from_file'
```

odd
