### ISSUE TITLE
dmg_package: Can't install dmg package with EULA

### ISSUE THREAD

**Issue by jorgeLuizChaves** [chef/chef#7708]
## Description
Given a dmg package that needs to accept EULA to install dmg_package can't install it 

## Chef Version
Chef: 14.4.56

## Platform Version
MacOS High Sierra 10.13.6

## Replication Case
```ruby
dmg_package 'Evernote' do
    dmg_name 'evernote'
    source 'https://cdn1.evernote.com/mac-smd/public/Evernote_RELEASE_7.5_457109.dmg'
    accept_eula true
end
```

## Client Output

```
  * dmg_package[Evernote] action install
    * remote_file[/Users/jorgeluiz/.chef/cache/evernote.dmg - Evernote] action create (up to date)
    * ruby_block[attach /Users/jorgeluiz/.chef/cache/evernote.dmg] action run

      ================================================================================
      Error executing action `run` on resource 'ruby_block[attach /Users/jorgeluiz/.chef/cache/evernote.dmg]'
      ================================================================================

      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '1'
      ---- Begin output of echo Y | PAGER=true hdiutil attach  '/Users/jorgeluiz/.chef/cache/evernote.dmg' -mountpoint '/Volumes/Evernote' -quiet ----
      STDOUT:
      STDERR:
      ---- End output of echo Y | PAGER=true hdiutil attach  '/Users/jorgeluiz/.chef/cache/evernote.dmg' -mountpoint '/Volumes/Evernote' -quiet ----
      Ran echo Y | PAGER=true hdiutil attach  '/Users/jorgeluiz/.chef/cache/evernote.dmg' -mountpoint '/Volumes/Evernote' -quiet returned 1

      Resource Declaration:
      ---------------------
      # In /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/resource/dmg_package.rb

      114:           ruby_block "attach #{dmg_file}" do
      115:             block do
      116:               cmd = shell_out("hdiutil imageinfo #{passphrase_cmd} '#{dmg_file}' | grep -q 'Software License Agreement: true'")
      117:               software_license_agreement = cmd.exitstatus == 0
      118:               raise "Requires EULA Acceptance; add 'accept_eula true' to package resource" if software_license_agreement && !new_resource.accept_eula
      119:               accept_eula_cmd = new_resource.accept_eula ? "echo Y | PAGER=true" : ""
      120:               shell_out!("#{accept_eula_cmd} hdiutil attach #{passphrase_cmd} '#{dmg_file}' -mountpoint '/Volumes/#{volumes_dir}' -quiet")
      121:             end
      122:             not_if "hdiutil info #{passphrase_cmd} | grep -q 'image-path.*#{dmg_file}'"
      123:           end
      124:

      Compiled Resource:
      ------------------
      # Declared in /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/resource/dmg_package.rb:114:in `block in <class:DmgPackage>'

      ruby_block("attach /Users/jorgeluiz/.chef/cache/evernote.dmg") do
        action [:run]
        default_guard_interpreter :default
        declared_type :ruby_block
        cookbook_name "(chef-apply cookbook)"
        block #<Proc:0x00007fce38747eb8@/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/resource/dmg_package.rb:115>
        block_name "attach /Users/jorgeluiz/.chef/cache/evernote.dmg"
        not_if "hdiutil info  | grep -q 'image-path.*/Users/jorgeluiz/.chef/cache/evernote.dmg'"
      end

      System Info:
      ------------
      chef_version=14.4.56
      platform=mac_os_x
      platform_version=10.13.6
      ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin15]
      program_name=/usr/local/bin/chef-apply
      executable=/opt/chefdk/bin/chef-apply


    ================================================================================
    Error executing action `install` on resource 'dmg_package[Evernote]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    ruby_block[attach /Users/jorgeluiz/.chef/cache/evernote.dmg] (/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/resource/dmg_package.rb line 114) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of echo Y | PAGER=true hdiutil attach  '/Users/jorgeluiz/.chef/cache/evernote.dmg' -mountpoint '/Volumes/Evernote' -quiet ----
    STDOUT:
    STDERR:
    ---- End output of echo Y | PAGER=true hdiutil attach  '/Users/jorgeluiz/.chef/cache/evernote.dmg' -mountpoint '/Volumes/Evernote' -quiet ----
    Ran echo Y | PAGER=true hdiutil attach  '/Users/jorgeluiz/.chef/cache/evernote.dmg' -mountpoint '/Volumes/Evernote' -quiet returned 1

    Resource Declaration:
    ---------------------
    # In development.rb

     48: dmg_package 'Evernote' do
     49:   dmg_name 'evernote'
     50:   source 'https://cdn1.evernote.com/mac-smd/public/Evernote_RELEASE_7.5_457109.dmg'
     51:   accept_eula true
     52: end
     53:

    Compiled Resource:
    ------------------
    # Declared in development.rb:48:in `run_chef_recipe'

    dmg_package("Evernote") do
      action [:install]
      default_guard_interpreter :default
      declared_type :dmg_package
      cookbook_name "(chef-apply cookbook)"
      recipe_name "(chef-apply recipe)"
      dmg_name "evernote"
      source "https://cdn1.evernote.com/mac-smd/public/Evernote_RELEASE_7.5_457109.dmg"
      accept_eula true
      app "Evernote"
    end

    System Info:
    ------------
    chef_version=14.4.56
    platform=mac_os_x
    platform_version=10.13.6
    ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin15]
    program_name=/usr/local/bin/chef-apply
    executable=/opt/chefdk/bin/chef-apply

[2018-09-30T08:51:47-03:00] FATAL: Stacktrace dumped to /Users/jorgeluiz/.chef/cache/chef-stacktrace.out
[2018-09-30T08:51:47-03:00] FATAL: Stacktrace dumped to /Users/jorgeluiz/.chef/cache/chef-stacktrace.out
[2018-09-30T08:51:47-03:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-09-30T08:51:47-03:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-09-30T08:51:47-03:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: dmg_package[Evernote] ((chef-apply cookbook)::(chef-apply recipe) line 48) had an error: Mixlib::ShellOut::ShellCommandFailed: ruby_block[attach /Users/jorgeluiz/.chef/cache/evernote.dmg] (/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.4.56/lib/chef/resource/dmg_package.rb line 114) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of echo Y | PAGER=true hdiutil attach  '/Users/jorgeluiz/.chef/cache/evernote.dmg' -mountpoint '/Volumes/Evernote' -quiet ----
STDOUT:
STDERR:
---- End output of echo Y | PAGER=true hdiutil attach  '/Users/jorgeluiz/.chef/cache/evernote.dmg' -mountpoint '/Volumes/Evernote' -quiet ----
Ran echo Y | PAGER=true hdiutil attach  '/Users/jorgeluiz/.chef/cache/evernote.dmg' -mountpoint '/Volumes/Evernote' -quiet returned 1
➜  recipes git:(master) ✗ chef-apply development.rbRecipe: (chef-apply cookbook)::(chef-apply recipe)  * dmg_package[Evernote] action install
    * remote_file[/Users/jorgeluiz/.chef/cache/evernote.dmg - Evernote] action create (up to date)
    * ruby_block[attach /Users/jorgeluiz/.chef/cache/evernote.dmg] action run
      - execute the ruby block attach /Users/jorgeluiz/.chef/cache/evernote.dmg
    * execute[rsync --force --recursive --links --perms --executability --owner --group --times '/Volumes/Evernote/Evernote.app' '/Applications'] action run
      - execute rsync --force --recursive --links --perms --executability --owner --group --times '/Volumes/Evernote/Evernote.app' '/Applications'
    * file[/Applications/Evernote.app/Contents/MacOS/Evernote] action create (up to date)
    * execute[hdiutil detach '/Volumes/Evernote' || hdiutil detach '/Volumes/Evernote' -force] action run
      - execute hdiutil detach '/Volumes/Evernote' || hdiutil detach '/Volumes/Evernote' -force
```

## Stacktrace
```
I, [2018-09-30T10:36:04.405989 #8033]  INFO -- default-high-sierra-chef14: Running handlers:
I, [2018-09-30T10:36:04.406188 #8033]  INFO -- default-high-sierra-chef14: [2018-09-30T06:36:04-07:00] ERROR: Running exception handlers
I, [2018-09-30T10:36:04.406346 #8033]  INFO -- default-high-sierra-chef14: [2018-09-30T06:36:04-07:00] ERROR: Running exception handlers
I, [2018-09-30T10:36:04.406387 #8033]  INFO -- default-high-sierra-chef14: Running handlers complete
I, [2018-09-30T10:36:04.406607 #8033]  INFO -- default-high-sierra-chef14: [2018-09-30T06:36:04-07:00] ERROR: Exception handlers complete
I, [2018-09-30T10:36:04.406647 #8033]  INFO -- default-high-sierra-chef14: [2018-09-30T06:36:04-07:00] ERROR: Exception handlers complete
I, [2018-09-30T10:36:04.429645 #8033]  INFO -- default-high-sierra-chef14: Chef Client failed. 0 resources updated in 09 seconds
I, [2018-09-30T10:36:04.430314 #8033]  INFO -- default-high-sierra-chef14: [2018-09-30T06:36:04-07:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
I, [2018-09-30T10:36:04.430415 #8033]  INFO -- default-high-sierra-chef14: [2018-09-30T06:36:04-07:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
I, [2018-09-30T10:36:04.430807 #8033]  INFO -- default-high-sierra-chef14: [2018-09-30T06:36:04-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
I, [2018-09-30T10:36:04.431178 #8033]  INFO -- default-high-sierra-chef14: [2018-09-30T06:36:04-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
I, [2018-09-30T10:36:04.432333 #8033]  INFO -- default-high-sierra-chef14: [2018-09-30T06:36:04-07:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: dmg_package[Evernote] (mac-os::development line 48) had an error: Mixlib::ShellOut::ShellCommandFailed: ruby_block[attach /tmp/kitchen/cache/evernote.dmg] (/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33/lib/chef/resource/dmg_package.rb line 111) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
I, [2018-09-30T10:36:04.432505 #8033]  INFO -- default-high-sierra-chef14: ---- Begin output of echo Y | PAGER=true hdiutil attach  '/tmp/kitchen/cache/evernote.dmg' -mountpoint '/Volumes/Evernote' -quiet ----
I, [2018-09-30T10:36:04.432568 #8033]  INFO -- default-high-sierra-chef14: STDOUT: 
I, [2018-09-30T10:36:04.432622 #8033]  INFO -- default-high-sierra-chef14: STDERR: 
I, [2018-09-30T10:36:04.432690 #8033]  INFO -- default-high-sierra-chef14: ---- End output of echo Y | PAGER=true hdiutil attach  '/tmp/kitchen/cache/evernote.dmg' -mountpoint '/Volumes/Evernote' -quiet ----
I, [2018-09-30T10:36:04.432747 #8033]  INFO -- default-high-sierra-chef14: Ran echo Y | PAGER=true hdiutil attach  '/tmp/kitchen/cache/evernote.dmg' -mountpoint '/Volumes/Evernote' -quiet returned 1
I, [2018-09-30T10:36:04.435884 #8033]  INFO -- default-high-sierra-chef14: [2018-09-30T06:36:04-07:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: dmg_package[Evernote] (mac-os::development line 48) had an error: Mixlib::ShellOut::ShellCommandFailed: ruby_block[attach /tmp/kitchen/cache/evernote.dmg] (/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.5.33/lib/chef/resource/dmg_package.rb line 111) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
I, [2018-09-30T10:36:04.435986 #8033]  INFO -- default-high-sierra-chef14: ---- Begin output of echo Y | PAGER=true hdiutil attach  '/tmp/kitchen/cache/evernote.dmg' -mountpoint '/Volumes/Evernote' -quiet ----
I, [2018-09-30T10:36:04.436051 #8033]  INFO -- default-high-sierra-chef14: STDOUT: 
I, [2018-09-30T10:36:04.436093 #8033]  INFO -- default-high-sierra-chef14: STDERR: 
I, [2018-09-30T10:36:04.436128 #8033]  INFO -- default-high-sierra-chef14: ---- End output of echo Y | PAGER=true hdiutil attach  '/tmp/kitchen/cache/evernote.dmg' -mountpoint '/Volumes/Evernote' -quiet ----
I, [2018-09-30T10:36:04.436164 #8033]  INFO -- default-high-sierra-chef14: Ran echo Y | PAGER=true hdiutil attach  '/tmp/kitchen/cache/evernote.dmg' -mountpoint '/Volumes/Evernote' -quiet returned 1
E, [2018-09-30T10:36:04.461987 #8033] ERROR -- default-high-sierra-chef14: Converge failed on instance <default-high-sierra-chef14>.
E, [2018-09-30T10:36:04.462196 #8033] ERROR -- default-high-sierra-chef14: ------Exception-------
E, [2018-09-30T10:36:04.462236 #8033] ERROR -- default-high-sierra-chef14: Class: Kitchen::ActionFailed
E, [2018-09-30T10:36:04.462267 #8033] ERROR -- default-high-sierra-chef14: Message: SSH exited (1) for command: [sh -c '
TEST_KITCHEN="1"; export TEST_KITCHEN
sudo -E /opt/chef/bin/chef-solo --config /tmp/kitchen/solo.rb --log_level auto --no-color --json-attributes /tmp/kitchen/dna.json  --force-formatter 
']
E, [2018-09-30T10:36:04.462297 #8033] ERROR -- default-high-sierra-chef14: ----------------------
E, [2018-09-30T10:36:04.462326 #8033] ERROR -- default-high-sierra-chef14: ------Backtrace-------
E, [2018-09-30T10:36:04.462386 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/provisioner/base.rb:91:in `rescue in call'
E, [2018-09-30T10:36:04.462417 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/provisioner/base.rb:67:in `call'
E, [2018-09-30T10:36:04.462446 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:408:in `block in converge_action'
E, [2018-09-30T10:36:04.462500 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:551:in `synchronize_or_call'
E, [2018-09-30T10:36:04.462530 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:513:in `block in action'
E, [2018-09-30T10:36:04.462559 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
E, [2018-09-30T10:36:04.462594 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:512:in `action'
E, [2018-09-30T10:36:04.462636 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:404:in `converge_action'
E, [2018-09-30T10:36:04.462668 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
E, [2018-09-30T10:36:04.462712 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
E, [2018-09-30T10:36:04.462757 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2018-09-30T10:36:04.462810 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `each'
E, [2018-09-30T10:36:04.462853 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `transition_to'
E, [2018-09-30T10:36:04.462896 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:140:in `converge'
E, [2018-09-30T10:36:04.462939 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `public_send'
E, [2018-09-30T10:36:04.462987 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2018-09-30T10:36:04.463031 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2018-09-30T10:36:04.463145 #8033] ERROR -- default-high-sierra-chef14: ----End Backtrace-----
E, [2018-09-30T10:36:04.463194 #8033] ERROR -- default-high-sierra-chef14: ---Nested Exception---
E, [2018-09-30T10:36:04.463238 #8033] ERROR -- default-high-sierra-chef14: Class: Kitchen::Transport::SshFailed
E, [2018-09-30T10:36:04.463283 #8033] ERROR -- default-high-sierra-chef14: Message: SSH exited (1) for command: [sh -c '
TEST_KITCHEN="1"; export TEST_KITCHEN
sudo -E /opt/chef/bin/chef-solo --config /tmp/kitchen/solo.rb --log_level auto --no-color --json-attributes /tmp/kitchen/dna.json  --force-formatter 
']
E, [2018-09-30T10:36:04.463327 #8033] ERROR -- default-high-sierra-chef14: ----------------------
E, [2018-09-30T10:36:04.463372 #8033] ERROR -- default-high-sierra-chef14: ------Backtrace-------
E, [2018-09-30T10:36:04.463414 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/provisioner/base.rb:91:in `rescue in call'
E, [2018-09-30T10:36:04.463459 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/provisioner/base.rb:67:in `call'
E, [2018-09-30T10:36:04.463504 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:408:in `block in converge_action'
E, [2018-09-30T10:36:04.463584 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:551:in `synchronize_or_call'
E, [2018-09-30T10:36:04.463632 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:513:in `block in action'
E, [2018-09-30T10:36:04.463679 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
E, [2018-09-30T10:36:04.463736 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:512:in `action'
E, [2018-09-30T10:36:04.463783 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:404:in `converge_action'
E, [2018-09-30T10:36:04.463829 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
E, [2018-09-30T10:36:04.463873 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
E, [2018-09-30T10:36:04.463948 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2018-09-30T10:36:04.463997 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `each'
E, [2018-09-30T10:36:04.464041 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `transition_to'
E, [2018-09-30T10:36:04.464085 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:140:in `converge'
E, [2018-09-30T10:36:04.464127 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `public_send'
E, [2018-09-30T10:36:04.464168 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2018-09-30T10:36:04.464210 #8033] ERROR -- default-high-sierra-chef14: /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2018-09-30T10:36:04.464257 #8033] ERROR -- default-high-sierra-chef14: ----End Backtrace-----
```

**Comment by tas50** [comment]
@jorgeLuizChaves Thanks for reporting this. I dug in and ended up doing a good amount of cleanup in the dmg_package resource. Everything passes just fine for me now with your example.

**Comment by tas50** [comment]
This will end up in 14.7
