### ISSUE TITLE
Node Attribute Deep Merge Caching Is Susceptible to Caching an Out of Date Attribute Merge

### ISSUE THREAD

**Issue by joshuaswett** [chef/chef#7738]
## Description

Chef node attributes have various precedence levels and a deep merge is performed when node attributes are looked up.  The result of a deep merge is cached and a StateTracking mixin is used to invalid the cached result when attributes are mutated.  The crux of the issue is that the deep_merge! method in chef/node/attribute.rb can mutate the \_\_root__ StateTracking instance variable and this will break merge cache invalidation.  This doesn't show up often in practice because the \_\_root__ StateTracking variable is "fixed" by the [] method of StateTracking, so a fully-qualified lookup masks the issue (i.e. node.default['foo']['bar'] = 'something').  However, if, for example, you are holding on to a sub-level of the default attribute tree in a variable such that further assignments are done directly on that variable, the issue can show up.  Ex.

```
default['foo']['bar'].tap do |bar|
  # Other stuff up here...
  # Under certain cases this won't invalid the merge cache, see full replication steps
  # for specifics
  bar['hello'] = 'world'
end
```

## Chef Version

Reproducible starting on version 13.4.11

## Platform Version

CentOS 7

## Replication Case

I created a minimal replication example in the form of a script that can be placed in the bin folder of a chef source code checkout and run to reproduce and explain the issue.

As previously stated, the issue can be replicated in any version starting with 13.4.11, but for the purposes of this example, we will use the latest stable version at the time of writing: 14.5.33

```
# Get the code and get set up
git clone https://github.com/chef/chef.git
cd chef
git checkout v14.5.33
bundle install
bundle exec rake install
```

Here's a script that demonstrates the bug and outputs information about what's going on as it does stuff:
```
#!/usr/bin/env ruby

require "rubygems"
$:.unshift(File.join(File.dirname(__FILE__), "..", "lib"))

require "chef"
require "chef/node/attribute"

puts '''
default = {
    "key1" => {
        "key2" => {
            "key3" => true
        }
    }
}
'''

default = {
    "key1" => {
        "key2" => {
            "key3" => true
        }
    }
}

puts '''
env_default = {
    "key1" => {
        "key2" => {
            "key4" => false
        }
    }
}
'''

env_default = {
    "key1" => {
        "key2" => {
            "key4" => false
        }
    }
}

# Keep this simple -- we only have defaults
puts "\n"
puts "a = Chef::Node::Attribute.new({}, default, {}, {})"
a = Chef::Node::Attribute.new({}, default, {}, {}) 
puts "a.env_default = env_default"
a.env_default = env_default

puts "\nFirst let's proxy some relevant StateTracking methods so we can log when they are called"

# Logs a call to the reset_cache method
module ResetCacheLogger
  def reset_cache(path = nil)
    puts "=== ResetCacheLogger ==="
    puts "Reset cache called for path #{path == nil ? 'nil': path}"
    super   
  end 
end

# Logs a call the StateTracking __root__ setter if the set changes the value
module RootChangeLogger
  def __root__=(root)
    if root != __root__
        puts "=== RootChangeLogger ==="
        puts "__root__ on #{__path__} is getting changed from object_id #{__root__.object_id} to #{root.object_id}!\nStacktrace: #{caller.join("\n")}"
    end 
    super   
  end 
end

# Stick our logger modules in where we want them
puts "a.default['key1'].__root__.extend(ResetCacheLogger)"
a.default['key1'].__root__.extend(ResetCacheLogger)
puts "a.default['key1']['key2'].extend(RootChangeLogger)"
a.default['key1']['key2'].extend(RootChangeLogger)

puts "\nWe look up a merged value to make the 'key1' subtree merge get cached..."
puts "Notice that this invokes our logger for the __root__ StateTracking variable getting changed on a.default['key1']['key2'] -- that seems weird"
puts "a['key1']"
puts
a['key1']

puts "\nNow we will use a.default['key1']['key2'].tap to add some default values. Note: This is going to reset the __root__ on a.default['key1']['key2']"
puts "to the proper value since the [] method on StateTracking sets __root__ appropriately as you navigate down the tree"
puts "a.default['key1']['key2'].tap do |key2|"
puts

a.default['key1']['key2'].tap do |key2|
    puts "\nLet's invalid the merge cache by setting a default value..."
    puts "key2['foo'] = 'bar'"
    puts
    key2['foo'] = 'bar'

    puts "\nGreat, now let's look up the value we just set using the merged attributes.  This will result in the"
    puts "'key1' subtree merge result getting cached again, but it will also mutate the __root__ StateTracking variable... this seems bad."
    puts "on a.default['key1']['key2']"
    puts
    puts "\nWe expect a['key1']['key2']['foo'] to return bar. Actual result: #{a['key1']['key2']['foo']}"

    puts "\nWe will now set a default again, and we expect it to result in a call to cache_reset, but it doesn't"
    puts "The reason is that __root__ got redefined when we did the attribute merge above.  In fact, cache_reset is getting"
    puts "called, but on some random VividMash instance that gets created during the merge"
    puts "key2['foo'] = 'bar2'"
    key2['foo'] = 'bar2'

    puts "\nNow when we look up the default value we just set using the merged attributes, we get the wrong result"
    puts "since the previously cached merge was never cleared"
    puts "\nWe expect a['key1']['key2']['foo'] to return bar2. Actual result: #{a['key1']['key2']['foo']}"
end
```
The easiest thing to do is to copy the above script into the bin folder of your chef checkout and call it attribute-bug.rb.  You then run it and it prints the relevant code it is executing and explains what exactly is going wrong:
```
cd bin
# Create attribute-bug.rb with the contents above
bundle exec attribute-bug.rb | less
```

**Comment by lamont-granquist** [comment]
bit simpler repro case:

```ruby
% cat test.rb
#!/usr/bin/env chef-apply

node.default['key1']['key2']['key3'] = true
node.env_default['key1']['key2']['key4'] = false

node.default['key1']['key2'].tap do |key2|
  key2['foo'] = 'bar'
  pp node['key1']['key2']['foo']
  key2['foo'] = 'bar2'
  pp node['key1']['key2']['foo']
  raise "boom" unless node['key1']['key2']['foo'] == "bar2"
end
```

**Comment by lamont-granquist** [comment]
i vaguely recall deliberately breaking this use case to make something else work.

**Comment by lamont-granquist** [comment]
https://github.com/chef/chef/pull/6362 contains the first bad commit.

**Comment by lamont-granquist** [comment]
prior notes and ramblings to myself on this kind of thing:  #5378

**Comment by lamont-granquist** [comment]
I'm seeing the same object_id be set on every call to update `__root__=(node)` i don't think that's the problem, i suspect its with the `__path__`

**Comment by joshuaswett** [comment]
In the replication script I posted, the RootChangeLogger only generates log output if the value of \_\_root\_\_ is getting changed.  Here's a part of the output I see when I run it:
```
=== RootChangeLogger ===
__root__ on ["key2"] is getting changed from object_id 47418417005500 to 47418417042320!
Stacktrace: /home/jswett/src/chef/lib/chef/node/mixin/state_tracking.rb:87:in `copy_state_to'
/home/jswett/src/chef/lib/chef/node/mixin/state_tracking.rb:41:in `[]'
/home/jswett/src/chef/lib/chef/node/attribute.rb:582:in `block in deep_merge!'
/home/jswett/src/chef/lib/chef/node/attribute.rb:579:in `each'
/home/jswett/src/chef/lib/chef/node/attribute.rb:579:in `deep_merge!'
/home/jswett/src/chef/lib/chef/node/attribute.rb:549:in `block in merge_defaults'
/home/jswett/src/chef/lib/chef/node/attribute.rb:547:in `each'
/home/jswett/src/chef/lib/chef/node/attribute.rb:547:in `inject'
/home/jswett/src/chef/lib/chef/node/attribute.rb:547:in `merge_defaults'
/home/jswett/src/chef/lib/chef/node/attribute.rb:528:in `merge_all'
/home/jswett/src/chef/lib/chef/node/attribute.rb:402:in `merged_attributes'
/home/jswett/src/chef/lib/chef/node/mixin/deep_merge_cache.rb:54:in `[]'
/home/jswett/src/chef/lib/chef/node/mixin/state_tracking.rb:38:in `[]'
./attribute-bug.rb:101:in `block in <main>'
./attribute-bug.rb:91:in `tap'
./attribute-bug.rb:91:in `<main>'
```

**Comment by lamont-granquist** [comment]
Ah yeah, now I see it, one different number in a list of like 40 that both look very similar...

**Comment by lamont-granquist** [comment]
validated that the __root__ is being updated there and on that node object, which does in fact smell like something that should never ever happen...

i don't think this is the case i was thinking it was -- which was more related to taking a node object and inserting it into the tree in other locations (the shape there is slightly different since you'd be doing `node.default['key1']['key3'] = key3` inside the tap which gets crazy fairly quickly)

**Comment by lamont-granquist** [comment]
I really wonder why I created that VividMash and then immutablize'd it later rather than just creating an ImmutableMash.

**Comment by lamont-granquist** [comment]
yeah, we wind up passing a vividmash to a vividmash constructor which correctly shortcircuits doing all the work in convert_value() but that winds up with the original object being attached to the merged vivid_mash chain and its __root__ is modified.

building with an immutablemash only bypasses convert_value when given another immutablemash.

so switching that around fixes the problem...

and it passes all the tests....

but why the hell did i write it that way in the first place?

**Comment by lamont-granquist** [comment]
(thanks for the bug, now you know how the sausage is made...)

**Comment by joshuaswett** [comment]
Thanks for fixing the bug!  Yah, this was a fun one to investigate.
