### ISSUE TITLE
NoMethodError in chef-shell

### ISSUE THREAD

**Issue by btm** [chef/chef#7756]
## Description
Attempting to run a resources on an unsupported platform in `chef-shell` raised an unexpected error

I think this isn't unique to my environment. I'll have to try a clean one later but I want to page this out first.
## Chef Version
14.6.29 ish

## Platform Version
Ubuntu

## Replication Case
```
chef-shell
recipe_mode
macosx_service "not-macosx" do
  action :start
end
run_chef
```

## Client Output
```
[2018-10-16T15:17:16-04:00] INFO: Processing macosx_service[bob] action start ((irb#1) line 4)
[2018-10-16T15:17:16-04:00] INFO: Running queued delayed notifications before re-raising exception
Traceback (most recent call last):
       16: from /home/btm/src/chef/lib/chef/resource.rb:589:in `rescue in run_action'
       15: from (eval):2:in `resource_failed'
       14: from /home/btm/src/chef/lib/chef/event_dispatch/dispatcher.rb:34:in `call_subscribers'
       13: from /home/btm/src/chef/lib/chef/event_dispatch/dispatcher.rb:34:in `each'
       12: from /home/btm/src/chef/lib/chef/event_dispatch/dispatcher.rb:43:in `block in call_subscribers'
       11: from /home/btm/src/chef/lib/chef/event_dispatch/dispatcher.rb:43:in `call'
       10: from /home/btm/src/chef/lib/chef/formatters/base.rb:139:in `resource_failed'
        9: from /home/btm/src/chef/lib/chef/formatters/error_mapper.rb:72:in `resource_failed'
        8: from /home/btm/src/chef/lib/chef/formatters/error_inspectors/resource_failure_inspector.rb:38:in `add_explanation'
        7: from /home/btm/src/chef/lib/chef/formatters/error_inspectors/resource_failure_inspector.rb:101:in `filtered_bt'
        6: from /home/btm/.rvm/gems/ruby-2.5.1/gems/mixlib-config-2.2.13/lib/mixlib/config.rb:669:in `block in define_attr_accessor_methods'
        5: from /home/btm/.rvm/gems/ruby-2.5.1/gems/mixlib-config-2.2.13/lib/mixlib/config.rb:648:in `internal_get_or_set'
        4: from /home/btm/.rvm/gems/ruby-2.5.1/gems/mixlib-config-2.2.13/lib/mixlib/config.rb:623:in `internal_get'
        3: from /home/btm/.rvm/gems/ruby-2.5.1/gems/mixlib-config-2.2.13/lib/mixlib/config/configurable.rb:59:in `get'
        2: from /home/btm/src/chef/chef-config/lib/chef-config/config.rb:222:in `block in <class:Config>'
        1: from /home/btm/src/chef/chef-config/lib/chef-config/config.rb:191:in `derive_path_from_chef_repo_path'
NoMethodError (undefined method `uniq' for nil:NilClass)
chef:recipe (14.6.29)> 
```
https://github.com/chef/chef/blob/master/chef-config/lib/chef-config/config.rb#L191

**Comment by kapilchouhan99** [comment]
@btm I am not able to reproduce it on Ubuntu(18.04 and 16.04), I am facing an error like this `Chef::Exceptions::Service (macosx_service[bob] ((irb#1) line 1) had an error: Chef::Exceptions::Service: Could not find plist for macosx_service[bob])`

**Comment by lamont-granquist** [comment]
Can't reproduce and this seems to be blowing up in the resource inspector due to a wonky setting of the chef_repo_path which is masking the error in the actual resource.
