### ISSUE TITLE
windows_service resource fails with 'QueryServiceConfig: The specified resource type cannot be found in the image file.'

### ISSUE THREAD

**Issue by lstyles** [chef/chef#7878]
## Description
service and windows_service resources fail with:
DEBUG: SystemCallError: windows_service[MSSQLSERVER] (company_sqlserver::configure line 288) had an error: SystemCallError: The specified resource type cannot be found in the image file. - QueryServiceConfig: The specified resource type cannot be found in the image file.

The service exists and is running. The same issue can be observed when trying to restart other services, ie: w32time

```
PS C:\Users\kaladmin> Get-Service MSSQLSERVER

Status   Name               DisplayName
------   ----               -----------
Running  MSSQLSERVER        SQL Server (MSSQLSERVER)
```

## Chef Version
14.6.47

## Platform Version
Windows Server 2016 on Azure

## Replication Case
Azure VM. Issue present on various sizes and images.
```
service 'w32time' do
  action :restart
end
```

## Client Output

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it. -->

```
  * windows_service[w32time] action restart[2018-11-06T17:28:13+00:00] INFO: Processing windows_service[w32time] action restart (role_sqlserver::default line 15)
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1103:in `block in services' : WARNING: The registry entry for the bowser service could not be found (StructuredWarnings::StandardWarning)

    ================================================================================
    Error executing action `restart` on resource 'windows_service[w32time]'
    ================================================================================

    SystemCallError
    ---------------
    The specified resource type cannot be found in the image file. - QueryServiceConfig: The specified resource type cannot be found in the image file.

    Resource Declaration:
    ---------------------
    # In c:/chef/cache/cookbooks/role_sqlserver/recipes/default.rb

     15: service 'w32time' do
     16:   action :restart
     17: end
     18:

    Compiled Resource:
    ------------------
    # Declared in c:/chef/cache/cookbooks/role_sqlserver/recipes/default.rb:15:in `from_file'

    windows_service("w32time") do
      action [:restart]
      default_guard_interpreter :default
      service_name "w32time"
      enabled nil
      running nil
      masked nil
      pattern "w32time"
      declared_type :service
      cookbook_name "role_sqlserver"
      recipe_name "default"
    end

    System Info:
    ------------
    chef_version=14.6.47
    platform=windows
    platform_version=10.0.14393
    ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]
    program_name=C:/opscode/chef/bin/chef-client
    executable=C:/opscode/chef/bin/chef-client

[2018-11-06T17:28:14+00:00] INFO: Running queued delayed notifications before re-raising exception
```

## Stacktrace
```
Generated at 2018-11-06 17:28:14 +0000
SystemCallError: windows_service[w32time] (role_sqlserver::default line 15) had an error: SystemCallError: The specified resource type cannot be found in the image file. - QueryServiceConfig: The specified resource type cannot be found in the image file.
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/ffi-win32-extensions-1.0.3/lib/ffi/win32/extensions.rb:64:in `raise_windows_error'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1346:in `get_config_info'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1063:in `block in services'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1035:in `upto'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1035:in `services'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/provider/service/windows.rb:285:in `current_delayed_start'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/provider/service/windows.rb:78:in `load_current_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/provider.rb:165:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/resource.rb:577:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/runner.rb:70:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/runner.rb:98:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/runner.rb:98:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/runner.rb:98:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/runner.rb:97:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/client.rb:720:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/client.rb:715:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/client.rb:715:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/client.rb:754:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/client.rb:286:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/application.rb:279:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/application.rb:261:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/application/client.rb:440:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/application.rb:66:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/bin/chef-client:25:in `<top (required)>'
C:/opscode/chef/bin/chef-client:74:in `load'
C:/opscode/chef/bin/chef-client:74:in `<main>'

>>>> Caused by SystemCallError: The specified resource type cannot be found in the image file. - QueryServiceConfig: The specified resource type cannot be found in the image file.
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/ffi-win32-extensions-1.0.3/lib/ffi/win32/extensions.rb:64:in `raise_windows_error'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1346:in `get_config_info'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1063:in `block in services'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1035:in `upto'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1035:in `services'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/provider/service/windows.rb:285:in `current_delayed_start'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/provider/service/windows.rb:78:in `load_current_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/provider.rb:165:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/resource.rb:577:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/runner.rb:70:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/runner.rb:98:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/runner.rb:98:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/runner.rb:98:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/runner.rb:97:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/client.rb:720:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/client.rb:715:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/client.rb:715:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/client.rb:754:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/client.rb:286:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/application.rb:279:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/application.rb:261:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/application/client.rb:440:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/lib/chef/application.rb:66:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.6.47-universal-mingw32/bin/chef-client:25:in `<top (required)>'
C:/opscode/chef/bin/chef-client:74:in `load'
C:/opscode/chef/bin/chef-client:74:in `<main>'
```

**Comment by lstyles** [comment]
If anyone finds this, for me the issue was caused by setting Windows OS Locale and not restarting before carrying on with the config. The service resource seems to have issues with pending locale change in the OS.
