### ISSUE TITLE
 Errno::ENOENT: No such file or directory @ rb_sysopen - C:/Temp/cds/***.json

### ISSUE THREAD

**Issue by manisha1331** [chef/chef#8082]
**Chef-client version** -14.0.202
**ruby gems**- 2.5.0
**OS**-Windows Server 2016

I am trying to deploy my application using chef.While deploying I am facing the above error
It was able to create few json files, but after creating 7 files in the folder, it is failing every time. Is that something related to the threshold limit of the no of files created ???

Also If I run the same command(for deployment) using chef-client 12.14.89 It is running successfully.

```
**Please refer the below stacktrace--**
Generated at 2018-12-28 05:42:04 -0500
Errno::ENOENT: ruby_block[upload-****] (****::populate_test_environment line 103) had an error: Errno::ENOENT: No such file or directory @ rb_sysopen - C:/Temp/cds/****.war.json
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/multipart-post-2.0.0/lib/composite_io.rb:85:in `initialize'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/multipart-post-2.0.0/lib/composite_io.rb:85:in `open'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/multipart-post-2.0.0/lib/composite_io.rb:85:in `initialize'
C:/chef/local-mode-cache/cache/cookbooks/jwala_library/libraries/toc_client_rest_tool.rb:57:in `new'
C:/chef/local-mode-cache/cache/cookbooks/jwala_library/libraries/toc_client_rest_tool.rb:57:in `block in execute_post_file'
C:/chef/local-mode-cache/cache/cookbooks/jwala_library/libraries/toc_client_rest_tool.rb:56:in `each'
C:/chef/local-mode-cache/cache/cookbooks/jwala_library/libraries/toc_client_rest_tool.rb:56:in `execute_post_file'
C:/chef/local-mode-cache/cache/cookbooks/jwala_library/libraries/toc_client_rest_common.rb:46:in `upload_resource'
C:/chef/local-mode-cache/cache/cookbooks/slpa/recipes/populate_test_environment.rb:106:in `block (2 levels) in from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/provider/ruby_block.rb:31:in `block in action_run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/mixin/why_run.rb:51:in `add_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/provider.rb:227:in `converge_by'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/provider/ruby_block.rb:30:in `action_run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/provider.rb:182:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/resource.rb:576:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/runner.rb:70:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/runner.rb:98:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/runner.rb:98:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/runner.rb:98:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/runner.rb:97:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/client.rb:717:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/client.rb:712:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/client.rb:712:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/client.rb:751:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/client.rb:283:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/application.rb:279:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/application.rb:261:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/application/client.rb:440:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/application.rb:66:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/bin/chef-client:26:in `<top (required)>'
```

**Comment by lamont-granquist** [comment]
this is almost certainly a bug in the jwala_library cookbook you are using.
