### ISSUE TITLE
Data Collector requires token to log to a file

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#8156]
It logs that it needs a token then throws trying to setup an http client:

```
[2019-01-23T11:12:20-08:00] TRACE: Data collector token must be configured to use Chef Automate data collector with Chef Solo
[2019-01-23T11:12:20-08:00] TRACE: Re-raising exception: URI::InvalidURIError - bad URI(is not URI?):
/Users/lamont/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/uri/rfc3986_parser.rb:18:in `rescue in split'
  /Users/lamont/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/uri/rfc3986_parser.rb:15:in `split'
  /Users/lamont/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/uri/rfc3986_parser.rb:73:in `parse'
  /Users/lamont/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/uri/common.rb:237:in `parse'
  /Users/lamont/.rvm/gems/ruby-2.5.3/gems/chef-14.9.13/lib/chef/http.rb:492:in `chef_zero_uri?'
  /Users/lamont/.rvm/gems/ruby-2.5.3/gems/chef-14.9.13/lib/chef/server_api.rb:38:in `initialize'
  /Users/lamont/.rvm/gems/ruby-2.5.3/gems/chef-14.9.13/lib/chef/data_collector.rb:298:in `new'
  /Users/lamont/.rvm/gems/ruby-2.5.3/gems/chef-14.9.13/lib/chef/data_collector.rb:298:in `setup_http_client'
  /Users/lamont/.rvm/gems/ruby-2.5.3/gems/chef-14.9.13/lib/chef/data_collector.rb:119:in `initialize'
  /Users/lamont/.rvm/gems/ruby-2.5.3/gems/chef-14.9.13/lib/chef/client.rb:1029:in `new'
  /Users/lamont/.rvm/gems/ruby-2.5.3/gems/chef-14.9.13/lib/chef/client.rb:1029:in `register_data_collector_reporter'
  /Users/lamont/.rvm/gems/ruby-2.5.3/gems/chef-14.9.13/lib/chef/client.rb:265:in `run'
  /Users/lamont/.rvm/gems/ruby-2.5.3/gems/chef-14.9.13/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
  /Users/lamont/.rvm/gems/ruby-2.5.3/gems/chef-14.9.13/lib/chef/application.rb:279:in `block in run_chef_client'
  /Users/lamont/.rvm/gems/ruby-2.5.3/gems/chef-14.9.13/lib/chef/local_mode.rb:44:in `with_server_connectivity'
  /Users/lamont/.rvm/gems/ruby-2.5.3/gems/chef-14.9.13/lib/chef/application.rb:261:in `run_chef_client'
  /Users/lamont/.rvm/gems/ruby-2.5.3/gems/chef-14.9.13/lib/chef/application/client.rb:440:in `run_application'
  /Users/lamont/.rvm/gems/ruby-2.5.3/gems/chef-14.9.13/lib/chef/application.rb:66:in `run'
  /Users/lamont/.rvm/gems/ruby-2.5.3/gems/chef-14.9.13/bin/chef-client:25:in `<top (required)>'
  /Users/lamont/.rvm/gems/ruby-2.5.3/bin/chef-client:23:in `load'
  /Users/lamont/.rvm/gems/ruby-2.5.3/bin/chef-client:23:in `<main>'
  /Users/lamont/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
  /Users/lamont/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
```

```
Chef::Config[:data_collector][:output_locations] = { files:  [ "/Users/lamont/data_collector.out" ] }
#Chef::Config[:data_collector][:token] = "foo"
```

uncommenting the token line there makes it work.

**Comment by lamont-granquist** [comment]
fixed by #8063
