### ISSUE TITLE
ssh: ed25519 support

### ISSUE THREAD

**Issue by vnz** [chef/chef#8170]
## Description
`chef` command throws error when used with SSH ed25519 for remote access.

## Solution
On ubuntu 18.04, libsodium is auto installed. So, in order to fix this, we need to install the following gems:
```
gem install --user-install -v '~> 4' rbnacl
gem install --user-install -v '~> 1' bcrypt_pbkdf
```

## Chef Version
```
chef --version
Chef Development Kit Version: 3.6.57
chef-client version: 14.8.12
delivery version: master (5fb4908da53579c9dcf4894d4acf94d2d9ee6475)
berks version: 7.0.7
kitchen version: 1.24.0
inspec version: 3.2.6
```

## Platform Version
Ubuntu 18.04
```
uname -a
Linux cerber 4.18.0-13-generic #14-Ubuntu SMP Wed Dec 5 09:04:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

## Replication Case
My `~/.ssh/config`:
```
Host *
  ChallengeResponseAuthentication no
  PasswordAuthentication          no
  PubkeyAuthentication            yes
  StrictHostKeyChecking           no
  ForwardAgent                    yes

  IdentityFile  ~/.ssh/id_ed25519
  IdentityFile  ~/.ssh/id_rsa

  Ciphers           chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
  HostKeyAlgorithms ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,ssh-rsa
  KexAlgorithms     curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256
  MACs              hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
```

How to generate ed25519 key:
```
ssh-keygen -t ed25519 -o -a 100 -f ~/.ssh/id_ed25519
```

## Client Output
```
Traceback (most recent call last):
	48: from /opt/chefdk/bin/chef:306:in `<main>'
	47: from /opt/chefdk/bin/chef:306:in `load'
	46: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-dk-3.6.57/bin/chef:25:in `<top (required)>'
	45: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-dk-3.6.57/lib/chef-dk/cli.rb:73:in `run'
	44: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-dk-3.6.57/lib/chef-dk/command/base.rb:58:in `run_with_default_options'
	43: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-dk-3.6.57/lib/chef-dk/command/provision.rb:237:in `run'
	42: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-dk-3.6.57/lib/chef-dk/chef_runner.rb:43:in `converge'
	41: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/runner.rb:97:in `converge'
	40: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
	39: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
	38: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
	37: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
	36: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
	35: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
	34: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/runner.rb:98:in `block in converge'
	33: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/runner.rb:98:in `each'
	32: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/runner.rb:98:in `block (2 levels) in converge'
	31: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/runner.rb:70:in `run_action'
	30: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/resource.rb:578:in `run_action'
	29: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/provider.rb:182:in `run_action'
	28: from (eval):2:in `action_converge'
	27: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/provider.rb:236:in `compile_and_converge_action'
	26: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/provider.rb:236:in `instance_eval'
	25: from (eval):2:in `block in action_converge'
	24: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-provisioning-2.7.4/lib/chef/provider/machine.rb:56:in `block in <class:Machine>'
	23: from (eval):2:in `action_ready'
	22: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/provider.rb:236:in `compile_and_converge_action'
	21: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/provider.rb:236:in `instance_eval'
	20: from (eval):2:in `block in action_ready'
	19: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-provisioning-2.7.4/lib/chef/provider/machine.rb:39:in `block in <class:Machine>'
	18: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-provisioning-aws-3.0.7/lib/chef/provisioning/aws_driver/driver.rb:762:in `ready_machine'
	17: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-provisioning-aws-3.0.7/lib/chef/provisioning/aws_driver/driver.rb:1392:in `wait_for_transport'
	16: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-provisioning-2.7.4/lib/chef/provisioning/transport/ssh.rb:215:in `available?'
	15: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-provisioning-2.7.4/lib/chef/provisioning/transport/ssh.rb:60:in `execute'
	14: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-provisioning-2.7.4/lib/chef/provisioning/transport/ssh.rb:237:in `session'
	13: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:241:in `start'
	12: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/session.rb:66:in `authenticate'
	11: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/session.rb:66:in `each'
	10: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/session.rb:80:in `block in authenticate'
	 9: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/methods/publickey.rb:19:in `authenticate'
	 8: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/key_manager.rb:101:in `each_identity'
	 7: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/key_manager.rb:221:in `load_identities'
	 6: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/key_manager.rb:221:in `map'
	 5: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/key_manager.rb:225:in `block in load_identities'
	 4: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/key_factory.rb:84:in `load_public_key'
	 3: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/key_factory.rb:103:in `load_data_public_key'
	 2: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/buffer.rb:248:in `read_key'
	 1: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/buffer.rb:282:in `read_keyblob'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/authentication/ed25519_loader.rb:19:in `raiseUnlessLoaded': unsupported key type `ssh-ed25519' (NotImplementedError)
net-ssh requires the following gems for ed25519 support:
 * rbnacl (>= 3.2, < 5.0)
 * rbnacl-libsodium, if your system doesn't have libsodium installed.
 * bcrypt_pbkdf (>= 1.0, < 2.0)
See https://github.com/net-ssh/net-ssh/issues/478 for more information
Gem::MissingSpecError : "Could not find 'rbnacl' (< 5.0, >= 3.2.0) among 292 total gem(s)

```

**Comment by lamont-granquist** [comment]
we added this in #5687, then moved it around in #5736 then we seem to have lost it.

**Comment by lamont-granquist** [comment]
looks like i nuked it in 1b1a8b34c872bc55f2acf77e44ac70e6e1efcab7

**Comment by lamont-granquist** [comment]
bad github, i did not mean to close this issue via that comment...
