### ISSUE TITLE
chocolatey_package: remove package not working properly with source and options

### ISSUE THREAD

**Issue by vsingh-msys** [chef/chef#8231]
## Description

While trying to uninstall a package using `chocolatey_package` resource, it takes all the options as an input and does not check any invalid flags, which might be valid for other actions like installation. Seems like the given options are simply concatenated for all the actions(install/remove/upgrade).
It blows up as given under client output.

## Chef Version

chef-client version: 14.10.9

## Platform Version
Windows

## Client Output

```
---- End output of C:\ProgramData\chocolatey/bin/choco.exe uninstall -y -u username -p password --force --all-versions -source https://www.myget.org/F/chocolatey-window/api/v2 Mahdi72.VSCodeNotify.WPF ----
Ran C:\ProgramData\chocolatey/bin/choco.exe uninstall -y -u username -p password --force --all-versions -source https://www.myget.org/F/chocolatey-window/api/v2 Mahdi72.VSCodeNotify.WPF returned 1
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4-universal-mingw32/lib/mixlib/shellout.rb:297:in `invalid!'
C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4-universal-mingw32/lib/mixlib/shellout.rb:284:in `error!'
/chef/lib/chef/mixin/shell_out.rb:131:in `shell_out_compacted!'
/chef/lib/chef/mixin/shell_out.rb:65:in `shell_out!'
/chef/lib/chef/provider/package/chocolatey.rb:177:in `choco_command'
/chef/lib/chef/provider/package/chocolatey.rb:124:in `remove_package'
/chef/lib/chef/provider/package.rb:155:in `block (3 levels) in <class:Package>'
...
/chef/lib/chef/application/client.rb:440:in `run_application'
/chef/lib/chef/application.rb:66:in `run'
/chef/bin/chef-client:25:in `<top (required)>'
/chefdk/gem/ruby/2.5.0/bin/chef-client:23:in `load'
l/chefdk/gem/ruby/2.5.0/bin/chef-client:23:in `<main>'
```

## Replication Case

Recipe with options " -u .. -p ... " for the private source runs well for action :install. Change the action to remove as follows:

```
chocolatey_package 'Mahdi72.VSCodeNotify.WPF' do
    options                    '-u username -p password --force --all-versions'
    package_name        'Mahdi72.VSCodeNotify.WPF'
    source                     'https://www.myget.org/F/chocolatey-window/api/v2'
    version                    '1.11.3'
    action                     :remove
end
```

**Comment by vsingh-msys** [comment]
As per the documentation https://chocolatey.org/docs/commands-uninstall "-u & -p " are not valid options so existing behavior is correct.
