### ISSUE TITLE
Uninitialized Constant:: Knife Cookbook Metadata From File

### ISSUE THREAD

**Issue by timio73** [chef/chef#8269]
## Description
Attempting to use `knife cookbook metadata from file /path/to/metadata.rb`, I receive the below error instead of the expected metadata.json.

```
Chef::Knife::CookbookMetadata (NameError)
Did you mean?  Chef::Knife::CookbookMetadataFromFile
```

## Chef Version
Chef Workstation 0.2.48, Chef DK 3.4.38 
Succeeds on ChefDK 3.1.0

## Platform Version
Windows 10

## Replication Case
run `knife cookbook metatdata from file ./metadata.rb` from within a cookbook directory.

## Client Output

```
Traceback (most recent call last):
        8: from C:/opscode/chef-workstation/bin/knife:322:in `<main>'
        7: from C:/opscode/chef-workstation/bin/knife:322:in `load'
        6: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/bin/knife:24:in `<top (required)>'
        5: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/application/knife.rb:161:in `run'
        4: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/knife.rb:220:in `run'
        3: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/knife.rb:445:in `run_with_pretty_exceptions'
        2: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
        1: from C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/knife.rb:446:in `block in run_with_pretty_exceptions'
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9-universal-mingw32/lib/chef/knife/cookbook_metadata_from_file.rb:37:in `run': uninitialized constant Chef::Knife::CookbookMetadata (NameError)
Did you mean?  Chef::Knife::CookbookMetadataFromFile
```

**Comment by timio73** [comment]
**Update:** only occurs if knife rehash has been run.  Removing the plugin_manifest.json resolves the issue.

**Comment by lamont-granquist** [comment]
this looks like a bug against chef-workstation, or possibly some kind of impedence mismatch between using chef-workstation and knife-rehash, with additional confusion from the way that you seem to have both chef-workstation and chef-dk packages installed?

i don't think you've found a bug in the code in this repo or with knife itself.

**Comment by vsingh-msys** [comment]
Installed the latest ChefDK on ubuntu 16.04 and run `knife cookbook metadata from file /starter/metadata.rb` works fine but after running `knife rehash` getting error `Exception: NameError: uninitialized constant Chef::Knife::CookbookMetadata`

**But after deleting `plugin_manifest.json` solves the problem.**

Logs:
```
knife cookbook metadata from file /starter/metadata.rb -VV
INFO: Using configuration from /home/vagrant/.chef/config.rb
Traceback (most recent call last):
	8: from /usr/bin/knife:351:in `<main>'
	7: from /usr/bin/knife:351:in `load'
	6: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14/bin/knife:24:in `<top (required)>'
	5: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14/lib/chef/application/knife.rb:162:in `run'
	4: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14/lib/chef/knife.rb:222:in `run'
	3: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14/lib/chef/knife.rb:474:in `run_with_pretty_exceptions'
	2: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14/lib/chef/local_mode.rb:42:in `with_server_connectivity'
	1: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14/lib/chef/knife.rb:475:in `block in run_with_pretty_exceptions'
/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14/lib/chef/knife/cookbook_metadata_from_file.rb:37:in `run': uninitialized constant Chef::Knife::CookbookMetadata (NameError)
```


```
chef -v
ChefDK version: 4.4.27
Chef Infra Client version: 15.3.14
Chef InSpec version: 4.16.0
Test Kitchen version: 2.3.3
Foodcritic version: 16.1.1
Cookstyle version: 5.6.2
```

**Comment by vsingh-msys** [comment]
dup https://github.com/chef/chef/issues/6825
