### ISSUE TITLE
Encoding bugs in resource reporter

### ISSUE THREAD

**Issue by jaymzh** [chef/chef#8326]
## Description
I *think* this is similar to what was fixed in #4409 except that I think that only applies to the REST API not writing to files... if I understand what's going on.

We get this stacktrace:

```
Message=Failed Chef Client run e38d2b96-b51c-47ae-bee1-bbc893857aac in 193.891338 seconds.
 Exception type: Chef::Exceptions::JSON::EncodeError
 Exception message: Invalid UTF-8 string 'Cï¿½CURE 9000 Client': cannot encode to UTF-8
 Exception backtrace: C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.9.1-universal-mingw32/lib/chef/json_compat.rb:55:in `rescue in to_json'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.9.1-universal-mingw32/lib/chef/json_compat.rb:52:in `to_json'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.9.1-universal-mingw32/lib/chef/node.rb:478:in `to_json'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ffi-yajl-2.3.1/lib/ffi_yajl/encoder.rb:42:in `ffi_yajl'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ffi-yajl-2.3.1/lib/ffi_yajl/encoder.rb:42:in `ffi_yajl'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ffi-yajl-2.3.1/lib/ffi_yajl/encoder.rb:42:in `do_yajl_encode'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ffi-yajl-2.3.1/lib/ffi_yajl/encoder.rb:42:in `encode'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/ffi-yajl-2.3.1/lib/ffi_yajl/encoder.rb:57:in `encode'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.9.1-universal-mingw32/lib/chef/json_compat.rb:53:in `to_json'
C:/windows/CPE/Chef/config/cache/cookbooks/fb_chef_handler/libraries/data_collector/messages_monkeypatch.rb:98:in `run_end_message'
C:/windows/CPE/Chef/config/cache/cookbooks/fb_chef_handler/libraries/data_collector_monkeypatch.rb:402:in `send_run_completion'
C:/windows/CPE/Chef/config/cache/cookbooks/fb_chef_handler/libraries/data_collector_monkeypatch.rb:140:in `run_completed'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.9.1-universal-mingw32/lib/chef/event_dispatch/dispatcher.rb:41:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.9.1-universal-mingw32/lib/chef/event_dispatch/dispatcher.rb:41:in `block in call_subscribers'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.9.1-universal-mingw32/lib/chef/event_dispatch/dispatcher.rb:34:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.9.1-universal-mingw32/lib/chef/event_dispatch/dispatcher.rb:34:in `call_subscribers'
(eval):2:in `run_completed'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.9.1-universal-mingw32/lib/chef/client.rb:302:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.9.1-universal-mingw32/lib/chef/application.rb:274:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.9.1-universal-mingw32/lib/chef/application.rb:250:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.9.1-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.9.1-universal-mingw32/lib/chef/application.rb:233:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.9.1-universal-mingw32/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.9.1-universal-mingw32/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.9.1-universal-mingw32/lib/chef/application/client.rb:457:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.9.1-universal-mingw32/lib/chef/application/client.rb:457:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.9.1-universal-mingw32/lib/chef/application/client.rb:441:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.9.1-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.9.1-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:71:in `load'
C:/opscode/chef/bin/chef-client:71:in `<main>'
```

## Chef Version
13.9

## Platform Version
Windows

## Replication Case
not sure, actually

**Comment by svmastersamurai** [comment]
Just for context on this one, this seems to trip up when installed software contains unicode characters while using a call like `Chef::JSONCompat.to_json(node)`. We are running Windows 10 Enterprise of various patch levels. I've seen a gamut of software that can cause it with the most amusing being [Trackmania](https://www.trackmania.com/).

From the best I understand this happens if `node` were serialized into JSON since `node['packages']` will contain a list of installed software, of which any entry could potentially contain a character that can cause the exception.

**Comment by lamont-granquist** [comment]
you need to use `Chef::JSONCompat.to_json(data, validate_utf8: false)` to serialize.  this should only affect the data collector when it is writing to a file, which is a separate JSON serialization path from the rest_clean object that sends over the network.

**Comment by jaymzh** [comment]
Thanks @lamont-granquist .

Hey @svmastersamurai  - you can throw that change into our backport/monkeypatch...
