### ISSUE TITLE
Rapid DSC calls fail on 0x80041033 in functional tests

### ISSUE THREAD

**Issue by btm** [chef/chef#8355]
## Description
These DSC functional tests fail on a test system that is undersized/under high load:
spec/functional/resource/dsc_script_spec.rb:235
spec/functional/resource/dsc_script_spec.rb:342

We've worked around them by increasing the resources on the tester, but they likely indicate an intermittent failure in `dsc_script`.

   WBEM_E_SHUTTING_DOWN = 0x80041033,

We could likely capture that error and retry in a few seconds.

## Replication Case
Run the functional tests on an undersized windows system.

## Stacktrace
```
  1) Chef::Resource::DscScript when supplying configuration using the path attribute behaves like a dsc_script resource with specified PowerShell configuration code should create a registry key with a specific registry value and data
     Failure/Error: dsc_test_resource.run_action(:run)

     Chef::Exceptions::PowershellCmdletException:
       dsc_script[DSCTest] (dynamically defined) had an error: Chef::Exceptions::PowershellCmdletException: PowerShell Cmdlet failed: trap [Exception] {write-error -exception ($_.Exception.Message);exit 1};$ProgressPreference = 'SilentlyContinue'; 

       Start-DscConfiguration -path C:/Users/jenkins/AppData/Local/Temp/cheftest/chef-dsc-script20190409-2888-15udnng -wait -erroraction 'stop' -force   4> 'C:/Users/jenkins/AppData/Local/Temp/cheftest/verbose20190409-2888-j3gw2v';if ( ! $? ) 

       { exit 1 } : The WS-Management service cannot process the request. The WMI service or the WMI provider returned an unknown error: HRESULT 0x80041033 
           + CategoryInfo          : NotSpecified: (:) [Write-Error], Exception
           + FullyQualifiedErrorId : System.Exception
  Shared Example Group: "a dsc_script resource with specified PowerShell configuration code" called from ./spec/functional/resource/dsc_script_spec.rb:379
     # ./lib/chef/util/powershell/cmdlet.rb:93:in `run!'
     # ./lib/chef/util/dsc/local_configuration_manager.rb:58:in `run_configuration_cmdlet'
     # ./lib/chef/util/dsc/local_configuration_manager.rb:37:in `set_configuration'
     # ./lib/chef/provider/dsc_script.rb:36:in `block in initialize'
     # ./lib/chef/provider/dsc_script.rb:96:in `run_configuration'
     # ./lib/chef/provider/dsc_script.rb:46:in `block in action_run'
     # ./lib/chef/mixin/why_run.rb:51:in `add_action'
     # ./lib/chef/provider.rb:235:in `converge_by'
     # ./lib/chef/provider/dsc_script.rb:45:in `action_run'
     # ./lib/chef/provider.rb:190:in `run_action'
     # ./lib/chef/resource.rb:584:in `run_action'
     # ./spec/functional/resource/dsc_script_spec.rb:235:in `block (3 levels) in <top (required)>'
```

**Comment by btm** [comment]
We haven't seen this repeat, potentially fixed/worked around by https://github.com/chef/chef/pull/8359
