### ISSUE TITLE
Search not working in Attributes

### ISSUE THREAD

**Issue by bby-bishopclark** [chef/chef#8356]
## Description
This code is no good:
````
victims=search(:node, 'name:*')
````

It's about the simplest example I can devise, and while it's working in recipe code it's dying in attributes.

This was suggested in #4235 but closed without confirmation.  I could be using it wrongly, and I'm hoping the error message below will show the proof we need.

## Chef Version
14.11.21

## Platform Version
RHEL 6.10

## Client Output

```
FATAL: NoMethodError: undefined method `search' for #<Chef::Node::Attribute:0x0000000003a5b6f0>
```

## Stacktrace
````
Generated at 2019-04-11 07:34:48 -0700
NoMethodError: undefined method `search' for #<Chef::Node::Attribute:0x0000000003a5b6f0>
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/node.rb:263:in `public_send'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/node.rb:263:in `method_missing'
/var/chef/cache/cookbooks/all-datacenter-attributes/attributes/_remote-rsyslog.rb:8:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/mixin/from_file.rb:34:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/mixin/from_file.rb:34:in `from_file'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/dsl/include_attribute.rb:39:in `block in include_attribute'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/dsl/include_attribute.rb:31:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/dsl/include_attribute.rb:31:in `include_attribute'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/run_context/cookbook_compiler.rb:217:in `load_attribute_file'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/run_context/cookbook_compiler.rb:209:in `block in load_attributes_from_cookbook'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/run_context/cookbook_compiler.rb:208:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/run_context/cookbook_compiler.rb:208:in `load_attributes_from_cookbook'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/run_context/cookbook_compiler.rb:135:in `block in compile_attributes'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/run_context/cookbook_compiler.rb:134:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/run_context/cookbook_compiler.rb:134:in `compile_attributes'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/run_context/cookbook_compiler.rb:76:in `compile'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/run_context.rb:199:in `load'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/client.rb:515:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/client.rb:281:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:279:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:261:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application/client.rb:444:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/bin/chef-client:25:in `<top (required)>'
/usr/bin/chef-client:74:in `load'
/usr/bin/chef-client:74:in `<main>'
````

**Comment by bby-bishopclark** [comment]
Logging this for an eventual fix.  
````
victims=Chef::Search::Query.new.search(:node, 'name:*')
````
seems to work in its place for the time being.

**Comment by bastien-jove-cbp** [comment]
`search` is part of the recipe dsl, so indeed don't work in attributes files.

The use case is quite vague, and alternative is to use `node.default['node_list'] = search(:node, 'name:*)` in a recipe to create the attribute `node_list`, but this won't happen at the same time in the run so may not fully address your need.
