### ISSUE TITLE
knife ssh 'unsupported key type' when using ed25519 keys

### ISSUE THREAD

**Issue by jblaine** [chef/chef#8373]
## Description
knife ssh reports "unsupported key type"

## Chef Version
ChefDK 3.8.14

## Platform Version
RHEL 7

## Replication Case
Remote host is RHEL7.6. Client side where knife is running has public keys (known_hosts keys) of type ssh-rsa, ecdsa-sha2-nistp256, ssh-ed25519 for the remote host. Normal usage with just /usr/bin/ssh to the host works fine.

## Client Output
```/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/buffer.rb:295:in 'read_keyblob': unsupported key type```

## Stacktrace
```
#<Thread:0x0000000006968a60@/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        22: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
        21: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session_actions.rb:36:in `block (2 levels) in sessions'
        20: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:138:in `session'
        19: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:488:in `next_session'
        18: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:186:in `new_session'
        17: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:237:in `start'
        16: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:237:in `new'
        15: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:86:in `initialize'
        14: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:86:in `new'
        13: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/algorithms.rb:119:in `initialize'
        12: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/algorithms.rb:230:in `prepare_preferred_algorithms!'
        11: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:96:in `host_keys'
        10: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/known_hosts.rb:58:in `search_for'
         9: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/known_hosts.rb:64:in `search_in'
         8: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/known_hosts.rb:64:in `map'
         7: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/known_hosts.rb:64:in `block in search_in'
         6: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/known_hosts.rb:134:in `keys_for'
         5: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/known_hosts.rb:134:in `open'
         4: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/known_hosts.rb:136:in `block in keys_for'
         3: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/known_hosts.rb:136:in `each_line'
         2: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/known_hosts.rb:154:in `block (2 levels) in keys_for'
         1: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/buffer.rb:248:in 'read_key'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/buffer.rb:295:in 'read_keyblob': unsupported key type

**Comment by tas50** [comment]
We have work in flight for Chef 15 to support ed25519

**Comment by vnz** [comment]
net-ssh requires the following gems for ed25519 support:
 * rbnacl (>= 3.2, < 5.0)
 * rbnacl-libsodium, if your system doesn't have libsodium installed.
 * bcrypt_pbkdf (>= 1.0, < 2.0)
See https://github.com/net-ssh/net-ssh/issues/478 for more information

You close issue about net-ssh and rbnacl without actually fixing them.
This is bad work, chef is not reliable anymore.
Lets go ansible.

**Comment by tas50** [comment]
Master now includes net-ssh and ed22519 gems which resolves this.
