### ISSUE TITLE
knife bootstrap ssh: Train::PlatformDetectionFailed for windows platform

### ISSUE THREAD

**Issue by vsingh-msys** [chef/chef#8423]
## Description
While bootstrapping a windows node by using `knife bootstrap -o ssh FQDN` 
it raises an error `Sorry, we are unable to detect your platform (Train::PlatformDetectionFailed)
	12: from /usr/bin/knife:97:in '<main>'`

## Chef Version
Chef Infra: 15.0.235

## Platform Version
 - Window Server 2012 R2 Datacenter
 - Window Server 2012 R2 Standard
 
## Replication Case
- Install chef https://downloads.chef.io/chef/current/15.0.235
- Create a Window VM.
- Enable SSH on the target host reference https://github.com/chef/knife-windows#knife-bootstrap-windows-ssh
- Bootstrap a the target node by
```
knife bootstrap FQDN -o ssh -N node-name -r "recipe[starter::default]" --connection-user 'username' --connection-password 'password' --no-ssh-verify-host-key

```
## Client Output

```
ChefCore::TargetHost::ConnectionFailure (ChefCore::TargetHost::ConnectionFailure)
```

## Stacktrace
```
Traceback (most recent call last):
	19: from /usr/bin/knife:97:in `<main>'
	18: from /usr/bin/knife:97:in `load'
	17: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.235/bin/knife:24:in `<top (required)>'
	16: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.235/lib/chef/application/knife.rb:162:in `run'
	15: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.235/lib/chef/knife.rb:221:in `run'
	14: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.235/lib/chef/knife.rb:459:in `run_with_pretty_exceptions'
	13: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.235/lib/chef/local_mode.rb:41:in `with_server_connectivity'
	12: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.235/lib/chef/knife.rb:460:in `block in run_with_pretty_exceptions'
	11: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.235/lib/chef/knife/bootstrap.rb:550:in `run'
	10: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.235/lib/chef/knife/bootstrap.rb:604:in `connect!'
	 9: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.235/lib/chef/knife/bootstrap.rb:648:in `do_connect'
	 8: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-core-0.0.3/lib/chef_core/target_host.rb:131:in `connect!'
	 7: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.0.12/lib/train/transports/ssh.rb:82:in `connection'
	 6: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.0.12/lib/train/transports/ssh.rb:238:in `create_new_connection'
	 5: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.0.12/lib/train/transports/ssh.rb:238:in `new'
	 4: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.0.12/lib/train/transports/ssh_connection.rb:53:in `initialize'
	 3: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.0.12/lib/train/extras/command_wrapper.rb:128:in `load'
	 2: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.0.12/lib/train/plugins/base_connection.rb:110:in `platform'
	 1: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.0.12/lib/train/platforms/detect.rb:9:in `scan'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.0.12/lib/train/platforms/detect/scanner.rb:41:in `scan': Sorry, we are unable to detect your platform (Train::PlatformDetectionFailed)
	12: from /usr/bin/knife:97:in `<main>'
	11: from /usr/bin/knife:97:in `load'
	10: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.235/bin/knife:24:in `<top (required)>'
	 9: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.235/lib/chef/application/knife.rb:162:in `run'
	 8: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.235/lib/chef/knife.rb:221:in `run'
	 7: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.235/lib/chef/knife.rb:459:in `run_with_pretty_exceptions'
	 6: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.235/lib/chef/local_mode.rb:41:in `with_server_connectivity'
	 5: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.235/lib/chef/knife.rb:460:in `block in run_with_pretty_exceptions'
	 4: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.235/lib/chef/knife/bootstrap.rb:550:in `run'
	 3: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.235/lib/chef/knife/bootstrap.rb:604:in `connect!'
	 2: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.235/lib/chef/knife/bootstrap.rb:648:in `do_connect'
	 1: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-core-0.0.3/lib/chef_core/target_host.rb:128:in `connect!'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-core-0.0.3/lib/chef_core/target_host.rb:143:in `rescue in connect!': ChefCore::TargetHost::ConnectionFailure (ChefCore::TargetHost::ConnectionFailure)
system:~/pro
```

**Comment by marcparadise** [comment]
https://github.com/inspec/train/pull/416 will resolve this.

**Comment by btm** [comment]
@vsingh-msys Did you verify this works now with Chef 15.0.266+ ? Can we close this now?

**Comment by vsingh-msys** [comment]
Yes, @btm now it works thanks.
