### ISSUE TITLE
knife bootstrap winrm error outs when we use ip address of the VM to bootstrap along with -o option along with it. 

### ISSUE THREAD

**Issue by Vasu1105** [chef/chef#8432]
## Description
When I use following command it errors out `Exception: NameError: uninitialized constant Net::SSH`

I am running following command from my workstation to bootstrap VM.
```
knife bootstrap 137.117.17.107 -o winrm --node-name vj-win2012r2 --connection-user 'username' --connection-password 'password' --connection-port 5985 --winrm-auth-method "negotiate" -c ~/workspace/chef-repo/.chef/config.rb
```
Where as if I use following syntax it does not break and proceeds for further execution
```
knife bootstrap winrm://137.117.17.107 --node-name vj-win2012r2 --connection-user 'azure' --connection-password 'password' --connection-port 5985 --winrm-auth-method "negotiate" -c ~/workspace/chef-repo/.chef/knife.rb
```

## Chef Version

```Chef Infra: 15.0.238```
## Platform Version

Workstation: Ubuntu 18.04

Trying to bootstrap Windows-2012R2

## Replication Case
After running this command 
```
knife bootstrap 137.117.17.107 -o winrm --node-name vj-win2012r2 --connection-user 'username' --connection-password 'password' --connection-port 5985 --winrm-auth-method "negotiate" -c ~/workspace/chef-repo/.chef/config.rb
```
## Stacktrace
```
Connecting to 137.117.17.107
Traceback (most recent call last):
	18: from /usr/bin/knife:80:in `<main>'
	17: from /usr/bin/knife:80:in `load'
	16: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/bin/knife:24:in `<top (required)>'
	15: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/application/knife.rb:162:in `run'
	14: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/knife.rb:221:in `run'
	13: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/knife.rb:459:in `run_with_pretty_exceptions'
	12: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/local_mode.rb:41:in `with_server_connectivity'
	11: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/knife.rb:460:in `block in run_with_pretty_exceptions'
	10: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/knife/bootstrap.rb:548:in `run'
	 9: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/knife/bootstrap.rb:597:in `connect!'
	 8: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/knife/bootstrap.rb:627:in `do_connect'
	 7: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/knife/bootstrap.rb:627:in `new'
	 6: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/knife/bootstrap/train_connector.rb:39:in `initialize'
	 5: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/knife/bootstrap/train_connector.rb:246:in `opts_from_uri'
	 4: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.0.12/lib/train.rb:94:in `unpack_target_from_uri'
	 3: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.0.12/lib/train.rb:125:in `parse_uri'
	 2: from /opt/chef/embedded/lib/ruby/2.6.0/uri/common.rb:234:in `parse'
	 1: from /opt/chef/embedded/lib/ruby/2.6.0/uri/rfc3986_parser.rb:73:in `parse'
/opt/chef/embedded/lib/ruby/2.6.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): "://137.117.17.107" (URI::InvalidURIError)
	16: from /usr/bin/knife:80:in `<main>'
	15: from /usr/bin/knife:80:in `load'
	14: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/bin/knife:24:in `<top (required)>'
	13: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/application/knife.rb:162:in `run'
	12: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/knife.rb:221:in `run'
	11: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/knife.rb:459:in `run_with_pretty_exceptions'
	10: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/local_mode.rb:41:in `with_server_connectivity'
	 9: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/knife.rb:460:in `block in run_with_pretty_exceptions'
	 8: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/knife/bootstrap.rb:548:in `run'
	 7: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/knife/bootstrap.rb:597:in `connect!'
	 6: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/knife/bootstrap.rb:627:in `do_connect'
	 5: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/knife/bootstrap.rb:627:in `new'
	 4: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/knife/bootstrap/train_connector.rb:39:in `initialize'
	 3: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/knife/bootstrap/train_connector.rb:246:in `opts_from_uri'
	 2: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.0.12/lib/train.rb:94:in `unpack_target_from_uri'
	 1: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.0.12/lib/train.rb:124:in `parse_uri'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.0.12/lib/train.rb:135:in `rescue in parse_uri': bad URI(is not URI?): "://137.117.17.107" (Train::UserError)
	10: from /usr/bin/knife:80:in `<main>'
	 9: from /usr/bin/knife:80:in `load'
	 8: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/bin/knife:24:in `<top (required)>'
	 7: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/application/knife.rb:162:in `run'
	 6: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/knife.rb:221:in `run'
	 5: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/knife.rb:459:in `run_with_pretty_exceptions'
	 4: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/local_mode.rb:41:in `with_server_connectivity'
	 3: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/knife.rb:460:in `block in run_with_pretty_exceptions'
	 2: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/knife/bootstrap.rb:548:in `run'
	 1: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/knife/bootstrap.rb:594:in `connect!'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.238/lib/chef/knife/bootstrap.rb:599:in `rescue in connect!': uninitialized constant Net::SSH (NameError)
```

**Comment by btm** [comment]
Fixed by #8440
