### ISSUE TITLE
Chef 15: Knife bootstrap dependencies are not loading

### ISSUE THREAD

**Issue by vsingh-msys** [chef/chef#8461]
## Description
knife.rb class method `deps` not getting called from `bootstrap`.
As from the error message `uninitialized constant Chef::Knife::Bootstrap::ClientBuilder` seems 
require file `require "chef/knife/bootstrap/client_builder` not getting called so it raises constant not found.

~~In dev environment following code loaded~~

https://github.com/chef/chef/blob/61f69e18e69e0dca6e8cffdcd7451181d874cdb3/lib/chef/knife/bootstrap.rb#L392-L400.
~~but the problem in distribution build.~~

Able to reproduce the issue in chef 15 only irrespective of `knife-windows(2.0+ or 3.0+)` versions.
With chef 14 it's working fine.

## Chef Version

Chef Infra Client: 15.0.259, 15.0.256

## Platform Version

Ubuntu 18.04

## Replication Case

1. Install latest chef infra from the current release https://downloads.chef.io/chef/current
2. Install knife windows v3. Reference: https://github.com/chef/knife-windows/issues/479
3. run `knife bootstrap windows winrm`

## Client Output

```
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.256/lib/chef/knife/bootstrap.rb:28: warning: already initialized constant Chef::Knife::Bootstrap::SUPPORTED_CONNECTION_PROTOCOLS
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.256/lib/chef/knife/bootstrap.rb:28: warning: previous definition of SUPPORTED_CONNECTION_PROTOCOLS was here
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.256/lib/chef/knife/bootstrap.rb:29: warning: already initialized constant Chef::Knife::Bootstrap::WINRM_AUTH_PROTOCOL_LIST
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.256/lib/chef/knife/bootstrap.rb:29: warning: previous definition of WINRM_AUTH_PROTOCOL_LIST was here
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.256/lib/chef/knife/bootstrap.rb:339: warning: already initialized constant Chef::Knife::Bootstrap::DEPRECATED_FLAGS
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.256/lib/chef/knife/bootstrap.rb:339: warning: previous definition of DEPRECATED_FLAGS was here
Traceback (most recent call last):
	6: from /opt/chef/embedded/bin/knife:23:in `<main>'
	5: from /opt/chef/embedded/bin/knife:23:in `load'
	4: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.256/bin/knife:24:in `<top (required)>'
	3: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.256/lib/chef/application/knife.rb:162:in `run'
	2: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.256/lib/chef/knife.rb:219:in `run'
	1: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.256/lib/chef/knife.rb:219:in `new'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.256/lib/chef/knife/bootstrap.rb:397:in `initialize': uninitialized constant Chef::Knife::Bootstrap::ClientBuilder (NameError)
Did you mean?  Chef::Knife::Bootstrap::ClientBulkDelete
```

**Comment by vsingh-msys** [comment]
The same issue raised on `knife google` https://github.com/chef/knife-google/issues/144

**Comment by vsingh-msys** [comment]
While debugging this issue
```
   require "erubis" 
  
   require "chef/json_compat" 
   require "chef/util/path_helper" 
   require "chef/knife/bootstrap/chef_vault_handler" 
   require "chef/knife/bootstrap/client_builder" 
   require "chef/knife/bootstrap/train_connector" 
```
Move above require files from `deps` block to top of the file https://github.com/chef/chef/blob/61f69e18e69e0dca6e8cffdcd7451181d874cdb3/lib/chef/knife/bootstrap.rb#L21 
seems it loading and working fine.

Trying to debug why `deps` methods not getting called in latest bootstrapping code.

**Comment by vsingh-msys** [comment]
Provided fixes from the knife-windows side. https://github.com/chef/knife-windows/pull/480
