### ISSUE TITLE
Chef 15: bootstrap options --max-wait raises NoMethodError: undefined method /

### ISSUE THREAD

**Issue by vsingh-msys** [chef/chef#8488]
## Description
If we `--max-wait` options during bootstrap it raises raises NoMethodError /. seems that we are sending string value if max-wait instead of an integer for train ssh connector https://github.com/inspec/train/blob/ec41c1f1e6f38f6ab1c335955651064eaeb7028f/lib/train/transports/ssh_connection.rb#L138. 

## Chef Version
Chef Infra Client: 15.0.275
## Platform Version
Windows 2012R2

## Replication Case
```
knife bootstrap FQDN -N node-name -r "recipe[starter::default]" --connection-user 'username' --connection-password 'password' -c  '../chef-repo/.chef/knife.rb' --no-ssh-verify-host-key --max-wait 50
```

## Client Output

```
NoMethodError: undefined method `/' for "50":String
  /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.1.0/lib/train/transports/ssh_connection.rb:138:in `wait_until_ready'
  /chef/lib/chef/knife/bootstrap/train_connector.rb:69:in `connect!'
  /chef/lib/chef/knife/bootstrap.rb:632:in `do_connect'
  /chef/lib/chef/knife/bootstrap.rb:601:in `connect!'
  /chef/lib/chef/knife/bootstrap.rb:552:in `run'
  /chef/lib/chef/knife.rb:467:in `block in run_with_pretty_exceptions'
  /chef/lib/chef/local_mode.rb:41:in `with_server_connectivity'
  /chef/lib/chef/knife.rb:466:in `run_with_pretty_exceptions'
  /chef/lib/chef/knife.rb:221:in `run'
  /chef/lib/chef/application/knife.rb:162:in `run'
  /chef/bin/knife:24:in `<top (required)>'
  /opt/chef/embedded/lib/ruby/gems/2.6.0/bin/knife:23:in `load'
  /opt/chef/embedded/lib/ruby/gems/2.6.0/bin/knife:23:in `<top (required)>'
```

**Comment by vsingh-msys** [comment]
Fixed in https://github.com/chef/chef/pull/8489
