### ISSUE TITLE
windows_service resource prints ruby warnings from win32-service gem

### ISSUE THREAD

**Issue by tlian** [chef/chef#8497]
# Describe the problem
This issue was very similar to https://github.com/chef/chef/issues/7335.
Please note that issues reported here was indeed different. #7335 did fix the warning message addressed in the ticket. These warning reported here in this ticket were different and required new fix(es).

## Software Version
chef-client 14.12.9

## Replication Case
Use windows_service resource to invoke/start WinQuic service

## Stacktrace

<details><Warning messages>  </summary>

```
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-2.1.4/lib/win32/service.rb:1086:in 'rescue in block in services' : WARNING: Failed to retrieve description for the WinQuic service. (StructuredWarnings::StandardWarning)
```

```
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-2.1.4/lib/win32/service.rb:1146:in 'rescue in block in services' : WARNING: Unable to retrieve failure actions for the WinQuic service (StructuredWarnings::StandardWarning)
```
</details>

**Comment by sarahbakal** [comment]
👍  Windows Server 2019

**Comment by HeyItsGilbert** [comment]
I'm also seeing this on a Windows Server 2019 Datacenter box running Chef 14.7.17.

```
* windows_service[FOO] action enable[2019-11-14T23:00:49+00:00] INFO: Processing windows_service[FOO] action enable (C:/chef/cache/cookbooks/FOO/resources/FOO.rb line 190)
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1086:in `rescue in block in services' : WARNING: Failed to retrieve description for the WinQuic service. (StructuredWarnings::StandardWarning)C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1099:in `rescue in block in services' : WARNING: Unable to get delayed auto start information for the WinQuic service (StructuredWarnings::StandardWarning)C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-1.0.1/lib/win32/service.rb:1157:in `rescue in block in services' : WARNING: Unable to retrieve failure actions for the WinQuic service (StructuredWarnings::StandardWarning) (up to date)
```

**Comment by Fguhhla** [comment]
Got the same issue on Windows 2019 Datacenter
/win32-service-2.1.4/lib/win32/service.rb:1146:in `rescue in block in services': WARNING: Unable to retrieve failure actions for the WinQuic service (StructuredWarnings::StandardWarning)

**Comment by craigontour** [comment]
When running a kitchen converge on local VMware-hosted Windows 2016 server i got this error:
```
$$$$$$ Exception calling "Read" with "3" argument(s): "Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection."
At line:100 char:11
$$$$$$ +       if ($fs.Read($bytes, 0, $fs.Length) -gt 0) {
$$$$$$ +           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-2.1.4/lib/win32/service.rb:1086:in `rescue in block in services' : WARNING: Failed to retrieve description for the CDPUserSvc_2a371 service. (StructuredWarnings::StandardWarning)C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/win32-service-2.1.4/lib/win32/service.rb:1146:in `rescue in block in services' : WARNING: Unable to retrieve failure actions for the CDPUserSvc_2a371 service (StructuredWarnings::StandardWarning)

```

I am on a Mac using
**macos** Big Sur 11.2.3. and **Chef Workstation** version: 21.2.303, **Test kitchen** version: 2.10.0

Kitchen converge did not always fail with that error, but I noticed VMware Tools needed updating so ran that, few reboots later and then kc worked without an error at all. Time will tell.

**Comment by SecDWizar** [comment]
well nothing is being done nor written. is there a way to disable those warnings just?
