### ISSUE TITLE
Chef Client 15 license acceptance on windows fails due to invalid path

### ISSUE THREAD

**Issue by aaronwalker** [chef/chef#8548]
## Description
Chef Client 15 license acceptance on windows fails due to invalid path. This occurs regardless of the value you put in the client.rb `chef_license` or the chef-client `--chef-license` 

It appears to execute the `default_license_locations` method and for version 1.0.5 of the license-acceptance gem this is broken. It appears newer versions of this gem have fixed this issue

## Chef Version
chef-client-15.0.293-1-x64

## Platform Version
Windows 2016

## Client Output
```
1557912534,,ui,message,    azure-arm: Executing Chef: c:/opscode/chef/bin/chef-client.bat --no-color -c C:/Windows/Temp/packer-chef-client/client.rb -j C:/Windows/Temp/packer-chef-client/first-boot.json

1557912543,,ui,message,    azure-arm: c:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/license-acceptance-1.0.5/lib/license_acceptance/config.rb:24:in `join': no implicit conversion of nil into String (TypeError)

1557912543,,ui,message,    azure-arm: 	from c:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/license-acceptance-1.0.5/lib/license_acceptance/config.rb:24:in `default_license_locations'

1557912543,,ui,message,    azure-arm: 	from c:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/license-acceptance-1.0.5/lib/license_acceptance/config.rb:10:in `initialize'

1557912543,,ui,message,    azure-arm: 	from c:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/license-acceptance-1.0.5/lib/license_acceptance/acceptor.rb:25:in `new'

1557912543,,ui,message,    azure-arm: 	from c:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/license-acceptance-1.0.5/lib/license_acceptance/acceptor.rb:25:in `initialize'

1557912543,,ui,message,    azure-arm: 	from c:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/license-acceptance-1.0.5/lib/license_acceptance/acceptor.rb:95:in `new'

1557912543,,ui,message,    azure-arm: 	from c:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/license-acceptance-1.0.5/lib/license_acceptance/acceptor.rb:95:in `check_and_persist!'

1557912543,,ui,message,    azure-arm: 	from c:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/application.rb:254:in `check_license_acceptance'

1557912543,,ui,message,    azure-arm: 	from c:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293-universal-mingw32/lib/chef/application.rb:68:in `run'

1557912543,,ui,message,    azure-arm: 	from c:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-bin-15.0.293/bin/chef-client:25:in `<top (required)>'

1557912543,,ui,message,    azure-arm: 	from c:/opscode/chef/bin/chef-client:167:in `load'

1557912543,,ui,message,    azure-arm: 	from c:/opscode/chef/bin/chef-client:167:in `<main>'

```

**Comment by btm** [comment]
Fixed in #8551
