### ISSUE TITLE
Upgrade to 15.0.298 problem

### ISSUE THREAD

**Issue by bincentvaret** [chef/chef#8555]
## Description
When chef-client is upgraded with chef_client_updater from  15.0.293 to 15.0.298 it loops and chef-client is never upgraded

## Chef Version
15.0.293

## Platform Version
Centos 7
 ~> chef-client -v
Chef Infra Client: 15.0.293

## Replication Case
Use chef_client_updater and let it upgrade chef-client from 15.0.293 to 15.0.298

## Client Output
``` Recipe: chef_client_updater::default
  * chef_client_updater[update chef-client] action update
    * chef_gem[mixlib-install] action install
      - install version ~> 3.11 of package mixlib-install
    - move all files under /opt/chef to /opt/chef.upgrade
    - upgrade chef-client 15.0.293 to 15.0.298[2019-05-16T08:24:27+00:00] WARN: Chef client is running forked with a supervisor. Sending KILL to parent process!
[2019-05-16T08:24:27+00:00] WARN: New chef-client installed and exit is allowed. Forcing chef exit!

Running handlers:
[2019-05-16T08:24:27+00:00] ERROR: Running exception handlers
==========================================================
{"username":"Chef","text":" :skull: Chef run failed on node gra3-eg16s-845682.test.makeorg.tech. 4 resources updated in 19 seconds:\nchef_gem[xml-simple], chef_gem[ovh-rest], chef_gem[deepsort], chef_client_updater[update chef-client]","icon_url":"https://avatars1.githubusercontent.com/u/29740","attachments":[{"text":"exit"}]}
    - Chef::Handler::Slack
  Running handlers complete
[2019-05-16T08:24:27+00:00] ERROR: Exception handlers complete
  Chef Infra Client failed. 4 resources updated in 21 seconds
[2019-05-16T08:24:27+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2019-05-16T08:24:27+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-05-16T08:24:27+00:00] ERROR: exit
```

## Stacktrace
```
Generated at 2019-05-16 08:24:27 +0000
SystemExit: exit
/var/chef/cache/cookbooks/chef_client_updater/providers/default.rb:212:in `exit'
/var/chef/cache/cookbooks/chef_client_updater/providers/default.rb:212:in `run_post_install_action'
/var/chef/cache/cookbooks/chef_client_updater/providers/default.rb:472:in `block (2 levels) in class_from_file'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/mixin/why_run.rb:51:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/provider.rb:235:in `converge_by'
/var/chef/cache/cookbooks/chef_client_updater/providers/default.rb:471:in `block in class_from_file'
(eval):2:in `block in action_update'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/provider.rb:244:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/provider.rb:244:in `compile_and_converge_action'
(eval):2:in `action_update'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/provider.rb:190:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/resource.rb:584:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/runner.rb:70:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/runner.rb:99:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/runner.rb:99:in `each'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/runner.rb:99:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/2.6.0/forwardable.rb:230:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/runner.rb:97:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/client.rb:704:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/client.rb:699:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/client.rb:699:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/client.rb:723:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/client.rb:289:in `run'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/application.rb:332:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/application.rb:320:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/application.rb:320:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/application.rb:285:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/local_mode.rb:41:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/application.rb:273:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/application/client.rb:482:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/application/client.rb:471:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/application/client.rb:470:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/application/client.rb:470:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/application/client.rb:454:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.293/lib/chef/application.rb:69:in `run'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-bin-15.0.293/bin/chef-client:25:in `<top (required)>'
/usr/bin/chef-client:154:in `load'
/usr/bin/chef-client:154:in `<main>'
```

**Comment by tas50** [comment]
This was caused by an issue with our Omnitruck service that has been resolved. You should be good to upgrade now. Sorry for the inconvenience.

**Comment by bincentvaret** [comment]
Everything is fine, thank you !
