### ISSUE TITLE
knife bootstrap giving error undefined method windows? for nil:NilClass

### ISSUE THREAD

**Issue by Vasu1105** [chef/chef#8576]
## Description

knife bootstrap giving error `undefined method windows? for nil:NilClass`
## Chef Version

15.0.303
## Platform Version

Doesn't matter
## Replication Case

 knife bootstrap <ip-address> -N vj-test-ssh -c ~/workspace/chef-repo/.chef/knife.rb --ssh-identity-file ~/.ssh/id_rsa --sudo -VV --yes

## Client Output

```

```

## Stacktrace
```
$ knife bootstrap <ip-address> -N vj-test-ssh -c ~/workspace/chef-repo/.chef/knife.rb --ssh-identity-file ~/.ssh/id_rsa --sudo -VV --yes
INFO: Using configuration from /home/msys/workspace/chef-repo/.chef/knife.rb
DEBUG: Checking if we need to accept Chef license to bootstrap node
DEBUG: Reading products and relationships...
DEBUG: Successfully read products and relationships
DEBUG: License acceptance required for chef version: 15
DEBUG: Searching for the following licenses: ["infra-client", "inspec"]
DEBUG: Found license chef_infra_client at /home/msys/.chef/accepted_licenses/chef_infra_client
DEBUG: Found license inspec at /home/msys/.chef/accepted_licenses/inspec
DEBUG: Missing licenses remaining: []
DEBUG: All licenses present
Creating new client for vj-test-ssh
Creating new node for vj-test-ssh
Traceback (most recent call last):
	10: from /opt/chef/embedded/bin/knife:23:in `<main>'
	 9: from /opt/chef/embedded/bin/knife:23:in `load'
	 8: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.303/bin/knife:24:in `<top (required)>'
	 7: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.303/lib/chef/application/knife.rb:162:in `run'
	 6: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.303/lib/chef/knife.rb:221:in `run'
	 5: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.303/lib/chef/knife.rb:473:in `run_with_pretty_exceptions'
	 4: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.303/lib/chef/local_mode.rb:41:in `with_server_connectivity'
	 3: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.303/lib/chef/knife.rb:474:in `block in run_with_pretty_exceptions'
	 2: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.303/lib/chef/knife/bootstrap.rb:546:in `run'
	 1: from /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.303/lib/chef/knife/bootstrap.rb:570:in `register_client'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.303/lib/chef/knife/bootstrap.rb:512:in `bootstrap_context': undefined method `windows?' for nil:NilClass (NoMethodError)```

**Comment by dheerajd-msys** [comment]
This issue is fixed in https://github.com/chef/chef/pull/8574

**Comment by dheerajd-msys** [comment]
@Vasu1105 Closing this issue as it is fixed in https://github.com/chef/chef/pull/8574
