### ISSUE TITLE
chef-client fails while daemonized after reverting to a VMware snapshot

### ISSUE THREAD

**Issue by Blorpy** [chef/chef#8591]
## Description

After restoring to a VMware snapshot, chef-client fails to run daemonized until you restart the daemon. Running chef-client from a shell/foreground finishes fine. 
## Chef Version

14.11.21, 14.12.9
## Platform Version

CentOS 7.X (Multiple versions affected)
## Replication Case

Restore to snapshot. Wait for chef-client to fail to run while daemonized. 
## Client Output

```
Starting Chef Client, version 14.11.21#033[0m
#033[0m
Running handlers:#033[0m
Running handlers complete
#033[0mChef Client failed. 0 resources updated in 00 seconds#033[0m
```

## Stacktrace

```
Generated at 2019-05-24 15:28:58 +0000
Ohai::Exceptions::AttributeNotFound: No such attribute: 'platform_family'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/ohai-14.8.10/lib/ohai/provides_map.rb:97:in `block in find_closest_providers_for'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/ohai-14.8.10/lib/ohai/provides_map.rb:95:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/ohai-14.8.10/lib/ohai/provides_map.rb:95:in `find_closest_providers_for'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/ohai-14.8.10/lib/ohai/runner.rb:98:in `fetch_plugins'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/ohai-14.8.10/lib/ohai/runner.rb:78:in `run_v7_plugin'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/ohai-14.8.10/lib/ohai/runner.rb:48:in `block in run_plugin'
/opt/chef/embedded/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/ohai-14.8.10/lib/ohai/runner.rb:41:in `run_plugin'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/ohai-14.8.10/lib/ohai/system.rb:112:in `block in run_plugins'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/ohai-14.8.10/lib/ohai/system.rb:111:in `each'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/ohai-14.8.10/lib/ohai/system.rb:111:in `run_plugins'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/ohai-14.8.10/lib/ohai/system.rb:94:in `all_plugins'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/client.rb:608:in `run_ohai'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/client.rb:260:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:321:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:309:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:309:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:274:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:261:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application/client.rb:479:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application/client.rb:468:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application/client.rb:467:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application/client.rb:467:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application/client.rb:451:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21/bin/chef-client:25:in `<top (required)>'
/usr/bin/chef-client:74:in `load'
/usr/bin/chef-client:74:in `<main>'
```

**Comment by lamont-granquist** [comment]
This looks like its probably a VMWare bug that we don't have the time to investigate.
