### ISSUE TITLE
inspec fails at the end of chef-client run

### ISSUE THREAD

**Issue by Stromweld** [chef/chef#8752]
## Description
Inspec fails with a stack trace at the end of the chef client run. This is happening on all of our windows machines. Working with Jerry on slack we believe it's related to inspec train and this issue I opened. https://github.com/inspec/train/issues/475

## Chef Version
chef infra client 15.1.36

## Platform Version
windows 2016

## Replication Case
run chef-client with latest audit cookbook and any profile. also replicated it by running inspec locally with a test profile `inspec init profile test` and `inspec exec .\test`.

## Client Output
```
Running handlers:
  - Chef::Handler::Slack
[2019-07-18T10:16:26-05:00] ERROR: Report handler Chef::Handler::AuditReport raised #<NoMethodError: undefined method `process_id' for #<Array:0x0000000008b2c570>>
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.1.13/lib/train/transports/local.rb:220:in `start_pipe_server'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.1.13/lib/train/transports/local.rb:163:in `acquire_pipe'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.1.13/lib/train/transports/local.rb:145:in `initialize'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.1.13/lib/train/transports/local.rb:52:in `new'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.1.13/lib/train/transports/local.rb:52:in `select_runner'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.1.13/lib/train/transports/local.rb:27:in `initialize'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.1.13/lib/train/transports/local.rb:17:in `new'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/train-core-2.1.13/lib/train/transports/local.rb:17:in `connection'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.6.4/lib/inspec/backend.rb:51:in `create'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.6.4/lib/inspec/runner.rb:78:in `configure_transport'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/inspec-core-4.6.4/lib/inspec/runner.rb:70:in `initialize'
[2019-07-18T10:16:26-05:00] ERROR: C:/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:166:in `new'
[2019-07-18T10:16:26-05:00] ERROR: C:/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:166:in `call'
[2019-07-18T10:16:26-05:00] ERROR: C:/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:82:in `report'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36-universal-mingw32/lib/chef/handler.rb:257:in `run_report_unsafe'
[2019-07-18T10:16:26-05:00] ERROR: C:/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:100:in `run_report_safely'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36-universal-mingw32/lib/chef/handler.rb:123:in `block in run_report_handlers'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36-universal-mingw32/lib/chef/handler.rb:121:in `each'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36-universal-mingw32/lib/chef/handler.rb:121:in `run_report_handlers'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36-universal-mingw32/lib/chef/handler.rb:133:in `block in <class:Handler>'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36-universal-mingw32/lib/chef/client.rb:418:in `block in run_completed_successfully'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36-universal-mingw32/lib/chef/client.rb:417:in `each'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36-universal-mingw32/lib/chef/client.rb:417:in `run_completed_successfully'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36-universal-mingw32/lib/chef/client.rb:293:in `run'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36-universal-mingw32/lib/chef/application.rb:320:in `run_with_graceful_exit_option'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36-universal-mingw32/lib/chef/application.rb:296:in `block in run_chef_client'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36-universal-mingw32/lib/chef/local_mode.rb:42:in `with_server_connectivity'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36-universal-mingw32/lib/chef/application.rb:279:in `run_chef_client'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36-universal-mingw32/lib/chef/application/client.rb:482:in `sleep_then_run_chef_client'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36-universal-mingw32/lib/chef/application/client.rb:471:in `block in interval_run_chef_client'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36-universal-mingw32/lib/chef/application/client.rb:470:in `loop'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36-universal-mingw32/lib/chef/application/client.rb:470:in `interval_run_chef_client'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36-universal-mingw32/lib/chef/application/client.rb:454:in `run_application'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36-universal-mingw32/lib/chef/application.rb:69:in `run'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-bin-15.1.36/bin/chef-client:25:in `<top (required)>'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/bin/chef-client:176:in `load'
[2019-07-18T10:16:26-05:00] ERROR: C:/opscode/chef/bin/chef-client:176:in `<main>'
  - Chef::Handler::AuditReport
Running handlers complete
Chef Infra Client finished, 1/30 resources updated in 14 seconds
```

## Stacktrace
none generated

**Comment by lamont-granquist** [comment]
This doesn't look like a bug in chef client so closing in favor of  inspec/train#475

Inspec / train always get shipped in chef-client and this repo isn't to be used for tracking those version bumps and releases.

**Comment by Stromweld** [comment]
I guess my thought was since chef infra client was shipping a specific version of inspec, when it gets fixed in inspec/train, that a new release of chef infra client would need to ship with the fixed version as well.
