### ISSUE TITLE
Windows Event Log Detail Missing w/chef-client version 15.0.320 +

### ISSUE THREAD

**Issue by danielcbright** [chef/chef#8845]
## Description
When the Chef client starts, finishes or performs any task, it used to be logged in the application log in Windows with meaningful descriptions. Although a log for the event is still showing, it doesn’t give any description of what is happening.
## Chef Version
`>= 15.0.320`
## Platform Version
Windows Server 2016 and 2012R2
## Replication Case
1. Run chef-client either manually or via scheduled task to perform converge action.
2. View the Windows Event Logs for Chef Infra Client

## Client Output
<!--- The relevant output of the chef-client run or a link to a gist of the entire run, if there is one.

This is what shows in the Windows Event Log for the resulting event:
```
The description for Event ID 10001 from source Chef Infra Client cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event:

b0ad69f8-dd4a-4021-a72f-fe476767e9dc
```

## Stacktrace
N/A

**Comment by tas50** [comment]
Adding the regression tag since this was introduced in 15.0

**Comment by dheerajd-msys** [comment]
Hi @danielcbright,

We've tried to install `chef15.314` and `chef13.1.31` on two separate Windows 2012R2.
Getting below logs in event log : 

## Windows with chef v15.3.14
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Chef Infra Client" /> 
  <EventID Qualifiers="0">10003</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2019-10-14T10:05:03.000000000Z" /> 
  <EventRecordID>772</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>dh-win2012r2</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>UNKNOWN</Data> 
  <Data>UNKNOWN</Data> 
  <Data>Chef::Exceptions::PrivateKeyMissing</Data> 
  <Data>I cannot read C:\chef\validation.pem, which you told me to use to sign requests!</Data> 
  <Data>C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14-universal-mingw32/lib/chef/http/authenticator.rb:98:in `rescue in load_signing_key' C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14-universal-mingw32/lib/chef/http/authenticator.rb:84:in `load_signing_key' C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14-universal-mingw32/lib/chef/http/authenticator.rb:42:in `initialize' C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14-universal-mingw32/lib/chef/http.rb:98:in `new' C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14-universal-mingw32/lib/chef/http.rb:98:in `block in initialize' C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14-universal-mingw32/lib/chef/http.rb:97:in `each' C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14-universal-mingw32/lib/chef/http.rb:97:in `initialize' C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14-universal-mingw32/lib/chef/server_api.rb:40:in `initialize' C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14-universal-mingw32/lib/chef/api_client/registration.rb:160:in `new' C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14-universal-mingw32/lib/chef/api_client/registration.rb:160:in `http_api' C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14-universal-mingw32/lib/chef/api_client/registration.rb:106:in `create' C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14-universal-mingw32/lib/chef/api_client/registration.rb:96:in `create_or_update' C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14-universal-mingw32/lib/chef/api_client/registration.rb:59:in `run' C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14-universal-mingw32/lib/chef/client.rb:667:in `register' C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14-universal-mingw32/lib/chef/client.rb:263:in `run' C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14-universal-mingw32/lib/chef/application.rb:320:in `run_with_graceful_exit_option' C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14-universal-mingw32/lib/chef/application.rb:296:in `block in run_chef_client' C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14-universal-mingw32/lib/chef/local_mode.rb:42:in `with_server_connectivity' C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14-universal-mingw32/lib/chef/application.rb:279:in `run_chef_client' C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14-universal-mingw32/lib/chef/application/base.rb:330:in `run_application' C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.3.14-universal-mingw32/lib/chef/application.rb:69:in `run' C:/opscode/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-bin-15.3.14/bin/chef-client:25:in `<top (required)>' C:/opscode/chef/bin/chef-client:176:in `load' C:/opscode/chef/bin/chef-client:176:in `<main>'</Data> 
  </EventData>
  </Event>
```
##  Windows with chef v13.1.31
```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Chef" /> 
  <EventID Qualifiers="0">10003</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2019-10-14T10:31:54.000000000Z" /> 
  <EventRecordID>767</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>dh-win12chef-13</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>UNKNOWN</Data> 
  <Data>UNKNOWN</Data> 
  <Data>Chef::Exceptions::PrivateKeyMissing</Data> 
  <Data>I cannot read C:\chef\validation.pem, which you told me to use to sign requests!</Data> 
  <Data>C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/http/authenticator.rb:95:in `rescue in load_signing_key' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/http/authenticator.rb:85:in `load_signing_key' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/http/authenticator.rb:42:in `initialize' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/http.rb:98:in `new' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/http.rb:98:in `block in initialize' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/http.rb:97:in `each' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/http.rb:97:in `initialize' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/server_api.rb:37:in `initialize' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/api_client/registration.rb:150:in `new' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/api_client/registration.rb:150:in `http_api' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/api_client/registration.rb:96:in `create' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/api_client/registration.rb:87:in `create_or_update' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/api_client/registration.rb:58:in `run' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/client.rb:666:in `register' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/client.rb:267:in `run' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/application.rb:273:in `run_with_graceful_exit_option' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/application.rb:249:in `block in run_chef_client' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/application.rb:232:in `run_chef_client' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/application/client.rb:450:in `loop' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/application/client.rb:434:in `run_application' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/lib/chef/application.rb:59:in `run' C:/opscode/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.1.31-universal-mingw32/bin/chef-client:26:in `<top (required)>' C:/opscode/chef/bin/chef-client:58:in `load' C:/opscode/chef/bin/chef-client:58:in `<main>'</Data> 
  </EventData>
  </Event>
```
I found no much difference in the logged data. Please suggest if there is any mismatch.

Thanks!

**Comment by dheerajd-msys** [comment]
@danielcbright Please check ^.

Thanks!
