### ISSUE TITLE
exiting from knife ssh interactive mode results in "no implicit conversion from nil to integer (TypeError)"

### ISSUE THREAD

**Issue by dfuentes77** [chef/chef#8849]
## Description
I'm able to interact with my hosts in `interactive` mode:
`chef exec knife ssh 'role:transcoder' interactive -VVV`
but when I `quit!`, the console throws an error 

```
knife-ssh> quit!
Bye!
Traceback (most recent call last):
	9: from /opt/chef-workstation/bin/knife:338:in `<main>'
	8: from /opt/chef-workstation/bin/knife:338:in `load'
	7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/bin/knife:24:in `<top (required)>'
	6: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/application/knife.rb:162:in `run'
	5: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/knife.rb:222:in `run'
	4: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/knife.rb:474:in `run_with_pretty_exceptions'
	3: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/local_mode.rb:42:in `with_server_connectivity'
	2: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/knife.rb:475:in `block in run_with_pretty_exceptions'
	1: from /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/knife/ssh.rb:627:in `run'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/knife/ssh.rb:627:in `exit': no implicit conversion from nil to integer (TypeError)
```

## Chef Version
Chef Workstation 0.8.7 

## Platform Version
On macOS 10.14.6 (18G87)

**Comment by tas50** [comment]
Fix merged to master
