### ISSUE TITLE
execute resource user and password properties do not support lazy

### ISSUE THREAD

**Issue by nano-lonny** [chef/chef#8866]
## Description
user and password properties in execute and powershell_script(haven't tested other resources) compile lazy node.run_state variables which leads to a NoMethodError.

## Chef Version
chef_version=14.11.21

 ## Platform Version
Windows 10 build 1809
platform_version=10.0.17763

## Replication Case

```
execute "mkdir" do
    command lazy { "mkdir c:\\temp\\#{node.run_state['cred1']['UserName']}" }
    user lazy { "#{node.run_state['cred1']['UserName']}" }
    password lazy { "#{node.run_state['cred1']['Content']}" }
 end
```

## Client Output
```
PS C:\WINDOWS\system32> chef-client
Starting Chef Client, version 14.11.21
Using policy 'mastr' at revision '679051040ee4cd70fb9e2b6e5a88a19647496155663e00d761e2f2cafce53379'
resolving cookbooks for run list: ["cyberark::default@1.0.1 (cde50e1)", "mastr::default@0.1.2 (be7d346)"]
Synchronizing Cookbooks:
  - cyberark (1.0.1)
  - mastr (0.1.2)
Installing Cookbook Gems:
Compiling Cookbooks...
Recipe: cyberark::default
  * chef_gem[cyberark_credential] action install (up to date)
Recipe: mastrv::default
  * chef_gem[cyberark_credential] action install (up to date)

  ================================================================================
  Recipe Compile Error in C:/chef/cache/cookbooks/mastr/recipes/default.rb
  ================================================================================

  NoMethodError
  -------------
  undefined method `[]' for nil:NilClass

  System Info:
  ------------
  chef_version=14.11.21
  platform=windows
  platform_version=10.0.17763
  ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]
  program_name=C:/opscode/chef/bin/chef-client
  executable=C:/opscode/chef/bin/chef-client
 Running handlers:
[2019-09-05T07:40:14-04:00] ERROR: Running exception handlers
  Running handlers complete
[2019-09-05T07:40:14-04:00] ERROR: Exception handlers complete
  Chef Client failed. 0 resources updated in 46 seconds
[2019-09-05T07:40:15-04:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
[2019-09-05T07:40:15-04:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-09-05T07:40:15-04:00] FATAL: NoMethodError: undefined method `[]' for nil:NilClass

C:/chef/cache/cookbooks/mastrv/recipes/default.rb:59:in `block (2 levels) in from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/property.rb:696:in `instance_exec'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/property.rb:696:in `exec_in_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/property.rb:717:in `stored_value_to_output'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/property.rb:382:in `get'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/property.rb:348:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/property.rb:571:in `user'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/resource/execute.rb:126:in `after_created'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/resource_builder.rb:73:in `build'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/dsl/declare_resource.rb:314:in `build_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/dsl/declare_resource.rb:271:in `declare_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/dsl/resources.rb:38:in `execute'
C:/chef/cache/cookbooks/mastrv/recipes/default.rb:54:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/mixin/from_file.rb:34:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/mixin/from_file.rb:34:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/cookbook_version.rb:199:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/run_context.rb:350:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:166:in `block in compile_recipes'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:163:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:163:in `compile_recipes'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:79:in `compile'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/run_context.rb:199:in `load'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/policy_builder/policyfile.rb:195:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/client.rb:515:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/client.rb:281:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/application.rb:279:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/application.rb:261:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/application/client.rb:444:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/application.rb:66:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/bin/chef-client:25:in `<top (required)>'
C:/opscode/chef/bin/chef-client:74:in `load'
C:/opscode/chef/bin/chef-client:74:in `<main>'
[2019-09-05T07:45:11-04:00] FATAL: NoMethodError: undefined method `[]' for nil:NilClass
```

## Stacktrace

```
Generated at 2019-09-05 07:40:14 -0400
NoMethodError: undefined method `[]' for nil:NilClass
C:/chef/cache/cookbooks/mastr/recipes/default.rb:59:in `block (2 levels) in from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/property.rb:696:in `instance_exec'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/property.rb:696:in `exec_in_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/property.rb:717:in `stored_value_to_output'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/property.rb:382:in `get'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/property.rb:348:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/property.rb:571:in `user'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/resource/execute.rb:126:in `after_created'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/resource_builder.rb:73:in `build'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/dsl/declare_resource.rb:314:in `build_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/dsl/declare_resource.rb:271:in `declare_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/dsl/resources.rb:38:in `execute'
C:/chef/cache/cookbooks/mastr/recipes/default.rb:54:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/mixin/from_file.rb:34:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/mixin/from_file.rb:34:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/cookbook_version.rb:199:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/run_context.rb:350:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:166:in `block in compile_recipes'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:163:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:163:in `compile_recipes'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:79:in `compile'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/run_context.rb:199:in `load'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/policy_builder/policyfile.rb:195:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/client.rb:515:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/client.rb:281:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/application.rb:279:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/application.rb:261:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/application/client.rb:444:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/lib/chef/application.rb:66:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.11.21-universal-mingw32/bin/chef-client:25:in `<top (required)>'
C:/opscode/chef/bin/chef-client:74:in `load'
C:/opscode/chef/bin/chef-client:74:in `<main>'
```

**Comment by lamont-granquist** [comment]
Yeah those properties have custom validation in the after_created hook, which is called "eagerly" so those validated at compile time which un-lazies them.  Either the resources need to be moved to custom resources (which inherently lazies them) or else the lazy needs to be removed and the code which is writing to the node.run_state needs to be moved earlier in the compile time evaluation or needs to be moved to attribute files.

**Comment by tas50** [comment]
I'm going to close this out since as @lamont-granquist stated this is just a fundamental issue with how lazy interacts with some design patterns in Chef resource. There's no fix unless a fundamental redesign of resource validation occurred.
