### ISSUE TITLE
[knife::bootstrap] NameError: uninitialized constant TrainPlugins::WinRM::FS

### ISSUE THREAD

**Issue by vsingh-msys** [chef/chef#8903]
## Description

While bootstrapping a windows node with winrm protocol getting TrainPlugins::WinRM::FS

Created an issue here for reference with PR https://github.com/chef/chef/pull/8854

Issue on train-winrm: https://github.com/inspec/train-winrm/issues/17
PR: https://github.com/inspec/train-winrm/pull/18
## Chef Version
Chef version: 15.3.14

## Platform Version
Windows node with wirnrm protocol

## Replication Case
```
knife bootstrap IP_ADDRESS -N node1 -U username -P password -o winrm  --winrm-ssl  --winrm-no-verify-cert
```

## Client Output

```
bundler: failed to load command: knife (/chef/vendor/bundle/ruby/2.6.0/bin/knife)
NameError: uninitialized constant TrainPlugins::WinRM::FS
  /train-winrm/lib/train-winrm/connection.rb:153:in `file_manager'
  /train-winrm/lib/train-winrm/connection.rb:83:in `upload'
  /chef/lib/chef/knife/bootstrap/train_connector.rb:145:in `upload_file!'
  /chef/lib/chef/knife/bootstrap/train_connector.rb:160:in `upload_file_content!'
  /chef/lib/chef/knife/bootstrap.rb:1050:in `upload_bootstrap'
  /chef/lib/chef/knife/bootstrap.rb:573:in `run'
  /chef/lib/chef/knife.rb:475:in `block in run_with_pretty_exceptions'
  /chef/lib/chef/local_mode.rb:42:in `with_server_connectivity'
  /chef/lib/chef/knife.rb:474:in `run_with_pretty_exceptions'
  /chef/lib/chef/knife.rb:222:in `run'
  /chef/lib/chef/application/knife.rb:162:in `run'
  /chef/bin/knife:24:in `<top (required)>'
  /chef/vendor/bundle/ruby/2.6.0/bin/knife:23:in `load'
  /chef/vendor/bundle/ruby/2.6.0/bin/knife:23:in `<top (required)>'
```

**Comment by stacey843** [comment]
I am getting same error.

**Comment by vsingh-msys** [comment]
@tas50 we need to release https://github.com/inspec/train-winrm/commit/42aec15c5c13092f6a05aa622c2b6994969fed74 and pin it into chef infra?

**Comment by tas50** [comment]
I released the new version and we'll see a version bump PR shortly.
