### ISSUE TITLE
Native gem extenstion compilation broken on RHEL 6

### ISSUE THREAD

**Issue by nhuff** [chef/chef#9144]
## Description
Building native gem extensions is broken on RHEL 6 do to an unsupported compiler option fstack-protector-strong.

## Chef Version
Chef Infra Client: 15.5.17

## Platform Version
RHEL/CENTOS 6

## Replication Case
```
yum install augeas-devel
/opt/chef/embedded/bin/gem install ruby-augeas
```
## Client Output 
```
         * chef_gem[ruby-augeas] action install

           ================================================================================
           Error executing action `install` on resource 'chef_gem[ruby-augeas]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /opt/chef/embedded/bin/gem install ruby-augeas -q --no-document -v "0.5.0" --source=https://www.rubygems.org ----
           STDOUT: Building native extensions. This could take a while...
           STDERR: ERROR:  Error installing ruby-augeas:
                ERROR: Failed to build gem native extension.

        current directory: /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/ruby-augeas-0.5.0/ext/augeas
           /opt/chef/embedded/bin/ruby -I /opt/chef/embedded/lib/ruby/2.6.0 -r ./siteconf20191206-9624-hromz0.rb extconf.rb
           *** extconf.rb failed ***
           Could not create Makefile due to some reason, probably lack of necessary
           libraries and/or headers.  Check the mkmf.log file for more details.  You may
           need configuration options.

           Provided configuration options:
                --with-opt-dir
                --with-opt-include
                --without-opt-include=${opt-dir}/include
                --with-opt-lib
                --without-opt-lib=${opt-dir}/lib
                --with-make-prog
                --without-make-prog
                --srcdir=.
                --curdir
                --ruby=/opt/chef/embedded/bin/$(RUBY_BASE_NAME)
                --with-augeas-config
                --without-augeas-config
                --with-pkg-config
                --without-pkg-config
           /opt/chef/embedded/lib/ruby/2.6.0/mkmf.rb:478:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
           You have to install development tools first.
                from /opt/chef/embedded/lib/ruby/2.6.0/mkmf.rb:563:in `try_link0'
                from /opt/chef/embedded/lib/ruby/2.6.0/mkmf.rb:581:in `try_link'
                from /opt/chef/embedded/lib/ruby/2.6.0/mkmf.rb:683:in `try_ldflags'
                from /opt/chef/embedded/lib/ruby/2.6.0/mkmf.rb:1843:in `pkg_config'
                from extconf.rb:26:in `<main>'

           To see why this extension failed to compile, please check the mkmf.log which can be found here:

             /opt/chef/embedded/lib/ruby/gems/2.6.0/extensions/x86_64-linux/2.6.0/ruby-augeas-0.5.0/mkmf.log

           extconf failed, exit code 1

           Gem files will remain installed in /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/ruby-augeas-0.5.0 for inspection.
           Results logged to /opt/chef/embedded/lib/ruby/gems/2.6.0/extensions/x86_64-linux/2.6.0/ruby-augeas-0.5.0/gem_make.out
           ---- End output of /opt/chef/embedded/bin/gem install ruby-augeas -q --no-document -v "0.5.0" --source=https://www.rubygems.org ----
           Ran /opt/chef/embedded/bin/gem install ruby-augeas -q --no-document -v "0.5.0" --source=https://www.rubygems.org returned 1

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/augeas/recipes/geminstall.rb

             9: chef_gem 'ruby-augeas' do
            10:   compile_time false if Chef::Resource::ChefGem.method_defined?(:compile_time)
            11: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/augeas/recipes/geminstall.rb:9:in `from_file'

           chef_gem("ruby-augeas") do
             package_name "ruby-augeas"
             action [:install]
             default_guard_interpreter :default
             declared_type :chef_gem
             cookbook_name "augeas"
             recipe_name "geminstall"
           end

           System Info:
           ------------
           chef_version=15.5.17
           platform=centos
           platform_version=6.10
           ruby=ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
           program_name=/opt/chef/bin/chef-client
           executable=/opt/chef/bin/chef-client
```
## mkmf.log
```
"pkg-config --exists augeas"
| pkg-config --libs augeas
=> "-laugeas  \n"
"gcc -o conftest -I/opt/chef/embedded/include/ruby-2.6.0/x86_64-linux -I/opt/chef/embedded/include/ruby-2.6.0/ruby/backward -I/opt/chef/embedded/include/ruby-2.6.0 -I. -I/opt/chef/embedded/include -O2 -D_FORTIFY_SOURCE=2 -fstack-protector -O3 -g -pipe -I/opt/chef/embedded/include   -I/opt/chef/embedded/include -O2 -D_FORTIFY_SOURCE=2 -fstack-protector -O3 -g -pipe -fPIC conftest.c  -L. -L/opt/chef/embedded/lib -Wl,-rpath,/opt/chef/embedded/lib -L/opt/chef/embedded/lib -Wl,-rpath,/opt/chef/embedded/lib -L. -Wl,-rpath,/opt/chef/embedded/lib -L/opt/chef/embedded/lib -fstack-protector-strong -rdynamic -Wl,-export-dynamic -L/opt/chef/embedded/lib  -Wl,-rpath,/opt/chef/embedded/lib     -Wl,-rpath,/opt/chef/embedded/lib -L/opt/chef/embedded/lib -lruby  -lm   -lc"
cc1: error: unrecognized command line option "-fstack-protector-strong"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

**Comment by nhuff** [comment]
Looks like the system gcc wasn't used to compile the embedded packages which is causing issues.

```
strings /opt/chef/embedded/lib/libssl.a | grep GCC
GCC: (GNU) 4.9.2
```
```
rpm -q gcc
gcc-4.4.7-23.el6.x86_64
```
That seems to have made ruby think the compiler should support things it doesn't in reality.

**Comment by lamont-granquist** [comment]
yeah the system GCC can't compile ruby 2.6, so it has to be upgraded.

this doesn't seem to have actually been due to my adding `-fstack-protector` to the omnibus default build flags, so it smells like the ruby configure script itself must be determining the compiler supports it and uses it.

**Comment by nhuff** [comment]
Yes as far as I can tell ruby expects to be compiling extensions with the same compilation environment it was compiled with.

**Comment by tas50** [comment]
The fix for this issue is now merged into master. Thanks for the report @nhuff. We'll see if we can get a 15.6 release out in the next few days.
