### ISSUE TITLE
PolicyBuilder complains about run_list being set in JSON data even though run_list is not set. 

### ISSUE THREAD

**Issue by NAshwini** [chef/chef#9155]
## Description
When bootstrapping a node using the -j or --json-attribute-file options to pass JSON containing `policy_name` and `policy_group` definitions but no run_list definition,  Chef::PolicyBuilder::Policyfile complains that setting the run_list in JSON data is unsupported.
This internally set a empty runlist in first-boot attribute which leads to above issue.

## Chef Version
14.14.29

## Platform Version
Ubuntu18

## Replication Case
Create a json file with value as ` { "policy_group": "azuregrp", "policy_name": "azurepolicy" } `
Try to bootstrap a fresh node by command `knife bootstrap <IP-Address>  -x "azure" -P "<PASSWORD>" --json-attribute-file /etc/chef/bootattr.json -c "/etc/chef/knife.rb" --sudo`

## Client Output

```
Unexpected Error:
 Chef::PolicyBuilder::Policyfile::UnsupportedFeature: Policyfile does not support setting the run_list in json data.

```

## Stacktrace

```
Generated at 2019-12-11 09:43:06 +0000
Chef::PolicyBuilder::Policyfile::UnsupportedFeature: Policyfile does not support setting the run_list in json data.
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/policy_builder/policyfile.rb:107:in `initialize'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/policy_builder/dynamic.rb:155:in `new'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/policy_builder/dynamic.rb:155:in `select_implementation'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/policy_builder/dynamic.rb:74:in `load_node'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/client.rb:472:in `load_node'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/client.rb:267:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/application.rb:279:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/application.rb:261:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/application/client.rb:449:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/bin/chef-client:25:in `<top (required)>'
/usr/bin/chef-client:81:in `load'

```

**Comment by nkanne** [comment]
I am having the same issue. Where do we specify the runlist, if we dont specify it in the policy file?

Chef::PolicyBuilder::Policyfile::UnsupportedFeature: Policyfile does not support setting the run_list in json data.

{

"revision_id": "...",

"name": "customapp",

"run_list": [

"recipe[customapp::default]"
],

"included_policy_locks": [

],

"cookbook_locks": {

"customapp": {

  "version": "0.1.0",

  "identifier": "----",

  "dotted_decimal_identifier": "...",

  "source": ".",

  "cache_key": null,

  "scm_info": {

    "scm": "git",

    "remote": null,

    "revision": null,

    "working_tree_clean": true,

    "published": false,

    "synchronized_remote_branches": [

    ]

  },

  "source_options": {

    "path": "."

  }

},

"my_base_xx": {

  "version": "0.1.0",

  "identifier": "fddfdf",

  "dotted_decimal_identifier": "zzzz",

  "source": "../windows_base_prod",

  "cache_key": null,

  "scm_info": {

    "scm": "git",

    "remote": null,

    "revision": null,

    "working_tree_clean": true,

    "published": false,

    "synchronized_remote_branches": [

    ]

  },

  "source_options": {

    "path": "../my_base_xx"

  }

}
},

"default_attributes": {

},

"override_attributes": {

},

"solution_dependencies": {

"Policyfile": [

  [

    "customapp",

    ">= 0.0.0"

  ],

  [

    "my_base_xx",

    ">= 0.0.0"

  ]

],

"dependencies": {

  "customapp (0.1.0)": [

    [

      "my_base_xx",

      ">= 0.0.0"

    ]

  ],

  "my_base_xx (0.1.0)": [

  ]

}
}

}
