### ISSUE TITLE
FFI deprectation warnings in knife

### ISSUE THREAD

**Issue by tas50** [chef/chef#9225]
These started when we updated FFI

```
C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/ffi-1.12.1-x64-mingw32/lib/ffi/struct.rb:207:in `layout': [DEPRECATION] Struct layout is already defined for class Windows::ServiceStructs::SERVICE_STATUS_PROCESS. Redefinition as in C:/opscode/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/win32-service-2.1.4/lib/win32/windows/structs.rb:72:in `<class:SERVICE_STATUS_PROCESS>' will be disallowed in ffi-2.0. (StructuredWarnings::StandardWarning)
```

**Comment by tas50** [comment]
See more complete output of a knife command with these warnings in #9224

**Comment by kapilchouhan99** [comment]
It's fixed on this PR: https://github.com/chef/win32-service/pull/71, so we can close this issue.
