### ISSUE TITLE
Remove highline gem

### ISSUE THREAD

**Issue by reedlaw** [chef/chef#9359]
### Describe the Enhancement:
Highline dependency is too restrictive.

### Describe the Need:
It prevents other gems from being updated.

### Current Alternative
#8381 already supplied the alternative

### Can We Help You Implement This?:
From searching the code it doesn't seem like highline is being used at all. It could be as simple as removing the gem and unused methods.

**Comment by tas50** [comment]
@reedlaw There's a few other places we use highline that need to get updated to use the tty gems. #8381 was the first part of this work, but it was also the easy part.

**Comment by lamont-granquist** [comment]
./lib/chef/knife/core/ui.rb and ./lib/chef/formatters/indentable_output_stream.rb still use it.

**Comment by btm** [comment]
`highline.ask` should be pretty easily replaceable by `tty-prompt`.

I can't figure out a way to get `tty-table` to look like `highline.list`
```
2.7.0-preview1 :008 > HighLine.new.list(['one', 'two', '12' ], :columns_down)
 => "one  two  12 \n" 
2.7.0-preview1 :009 > HighLine.new.list(['one', 'two', '123' ], :columns_down)
 => "one  two  123\n" 
2.7.0-preview1 :010 > HighLine.new.list(['one', 'two', '1234' ], :columns_down)
 => "one   two   1234\n" 
2.7.0-preview1 :011 > HighLine.new.list(['one', 'two', '12345' ], :columns_down)
 => "one    two    12345\n" 
```

**Comment by rmoriz** [comment]
There was a braking change introduced by switching to pastel:

```ruby
irb(main):015:0> highline.color("test", [:bold, :white])
=> "\e[1m\e[37mtest\e[0m"

irb(main):016:0> pastel.decorate("test", [:bold, :white])
Traceback (most recent call last):
       16: from /Users/rmoriz/.asdf/installs/ruby/2.7.1/bin/irb:23:in `<main>'
       15: from /Users/rmoriz/.asdf/installs/ruby/2.7.1/bin/irb:23:in `load'
       14: from /Users/rmoriz/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/irb-1.2.3/exe/irb:11:in `<top (required)>'
       13: from (irb):16
       12: from /Users/rmoriz/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/forwardable.rb:235:in `decorate'
       11: from /Users/rmoriz/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/pastel-0.7.4/lib/pastel/color.rb:60:in `decorate'
       10: from /Users/rmoriz/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/pastel-0.7.4/lib/pastel/color.rb:140:in `lookup'
        9: from /Users/rmoriz/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/pastel-0.7.4/lib/pastel/color.rb:140:in `fetch'
        8: from /Users/rmoriz/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/pastel-0.7.4/lib/pastel/color.rb:141:in `block in lookup'
        7: from /Users/rmoriz/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/pastel-0.7.4/lib/pastel/color.rb:153:in `code'
        6: from /Users/rmoriz/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/pastel-0.7.4/lib/pastel/color.rb:153:in `each'
        5: from /Users/rmoriz/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/pastel-0.7.4/lib/pastel/color.rb:158:in `block in code'
        4: from /Users/rmoriz/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/pastel-0.7.4/lib/pastel/color.rb:236:in `validate'
        3: from /Users/rmoriz/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/pastel-0.7.4/lib/pastel/color.rb:195:in `valid?'
        2: from /Users/rmoriz/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/pastel-0.7.4/lib/pastel/color.rb:195:in `all?'
        1: from /Users/rmoriz/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/pastel-0.7.4/lib/pastel/color.rb:195:in `block in valid?'
NoMethodError (undefined method `to_sym' for [:bold, :white]:Array)
Did you mean?  to_s
               to_set

```
This breaks the knife plugin https://github.com/eligible/knife-bastion/blob/master/lib/chef/knife/bastion_base.rb#L42

**Comment by tas50** [comment]
Considering this done enough now that it's out of chef itself
