### ISSUE TITLE
User resource on OSX throwing undefined method `size' for nil:NilClass

### ISSUE THREAD

**Issue by johnmccrae** [chef/chef#9362]
## Description
Executing the User resource from Chef Infra Client version 15.7.32 returns an error:

    NoMethodError
    -------------
    undefined method `size' for nil:NilClass

## Chef Version

Chef Workstation version: 0.15.18
Chef Infra Client version: 15.7.32
Chef InSpec version: 4.18.51
Chef CLI version: 2.0.0
Test Kitchen version: 2.3.4
Cookstyle version: 5.20.0

## Platform Version
Mac osx 10.15.3

## Replication Case
```
  case node['platform_version'].to_s
  when '10.15.3'

    user 'blarflAdmin' do
      action [:create]
      password "thisiscrazybutyeahIlove2"
      username "blarflAdmin"
      home "/Users/blarflAdmin"
    end

    mac_updates 'Adding Settings to the Mac'

  end
```
## Client Output
```
Synchronizing Cookbooks:
  - ChefDesktop (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 2 resources
Recipe: ChefDesktop::default
  * mac_user[blarflAdmin] action create
    
    ================================================================================
    Error executing action `create` on resource 'mac_user[blarflAdmin]'
    ================================================================================
    
    NoMethodError
    -------------
    undefined method `size' for nil:NilClass
    
    Resource Declaration:
    ---------------------
    # In /Users/johnmccrae/.chef/local-mode-cache/cache/cookbooks/ChefDesktop/recipes/default.rb
    
     57:     user 'blarflAdmin' do
     58:       action [:create]
     59:       password "thisiscrazybutyeahIlove2"
     60:       username "blarflAdmin"
     61:       home "/Users/blarflAdmin"
     62:     end
     63: 
    
    Compiled Resource:
    ------------------
    # Declared in /Users/johnmccrae/.chef/local-mode-cache/cache/cookbooks/ChefDesktop/recipes/default.rb:57:in `from_file'
    
    mac_user("blarflAdmin") do
      action [:create]
      default_guard_interpreter :default
      declared_type :user
      cookbook_name "ChefDesktop"
      recipe_name "default"
      password "*sensitive value suppressed*"
      username "blarflAdmin"
      home "/Users/blarflAdmin"
    end
    
    System Info:
    ------------
    chef_version=15.7.32
    platform=mac_os_x
    platform_version=10.15.3
    ruby=ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin17]
    program_name=/opt/chef-workstation/bin/chef-client
    executable=/opt/chef-workstation/bin/chef-client
    

Running handlers:
[2020-02-12T09:40:20-08:00] ERROR: Running exception handlers
Running handlers complete
[2020-02-12T09:40:20-08:00] ERROR: Exception handlers complete
Chef Infra Client failed. 0 resources updated in 04 seconds
[2020-02-12T09:40:20-08:00] FATAL: Stacktrace dumped to /Users/johnmccrae/.chef/local-mode-cache/cache/chef-stacktrace.out
[2020-02-12T09:40:20-08:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-02-12T09:40:20-08:00] FATAL: NoMethodError: mac_u


The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it. -->

```

```

## StacktraceGenerated at 2020-02-12 09:40:20 -0800
NoMethodError: mac_user[blarflAdmin] (ChefDesktop::default line 57) had an error: NoMethodError: undefined method `size' for nil:NilClass
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/provider/user/mac.rb:461:in `convert_to_binary'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/provider/user/mac.rb:447:in `password_diverged?'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/provider/user/mac.rb:334:in `diverged?'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/provider/user/mac.rb:211:in `block in compare_user'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/provider/user/mac.rb:211:in `any?'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/provider/user/mac.rb:211:in `compare_user'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/provider/user.rb:125:in `action_create'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/provider.rb:189:in `run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/resource.rb:586:in `run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/runner.rb:74:in `run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/runner.rb:108:in `each'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/runner.rb:132:in `block in converge'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/resource_collection/stepable_iterator.rb:115:in `call_iterator_block'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/resource_collection/stepable_iterator.rb:86:in `step'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef-workstation/embedded/lib/ruby/2.6.0/forwardable.rb:230:in `execute_each_resource'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/runner.rb:130:in `converge'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/client.rb:703:in `block in converge'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/client.rb:698:in `catch'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/client.rb:698:in `converge'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/client.rb:722:in `converge_and_save'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/client.rb:288:in `run'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/application.rb:320:in `run_with_graceful_exit_option'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/application.rb:296:in `block in run_chef_client'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/application.rb:279:in `run_chef_client'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/application/base.rb:330:in `run_application'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/application.rb:69:in `run'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-bin-15.7.32/bin/chef-client:25:in `<top (required)>'
/opt/chef-workstation/bin/chef-client:361:in `load'
/opt/chef-workstation/bin/chef-client:361:in `<main>'

>>>> Caused by NoMethodError: undefined method `size' for nil:NilClass
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/provider/user/mac.rb:461:in `convert_to_binary'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/provider/user/mac.rb:447:in `password_diverged?'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/provider/user/mac.rb:334:in `diverged?'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/provider/user/mac.rb:211:in `block in compare_user'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/provider/user/mac.rb:211:in `any?'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/provider/user/mac.rb:211:in `compare_user'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/provider/user.rb:125:in `action_create'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/provider.rb:189:in `run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/resource.rb:586:in `run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/runner.rb:74:in `run_action'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/runner.rb:108:in `each'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/runner.rb:132:in `block in converge'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/resource_collection/stepable_iterator.rb:115:in `call_iterator_block'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/resource_collection/stepable_iterator.rb:86:in `step'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef-workstation/embedded/lib/ruby/2.6.0/forwardable.rb:230:in `execute_each_resource'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/runner.rb:130:in `converge'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/client.rb:703:in `block in converge'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/client.rb:698:in `catch'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/client.rb:698:in `converge'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/client.rb:722:in `converge_and_save'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/client.rb:288:in `run'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/application.rb:320:in `run_with_graceful_exit_option'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/application.rb:296:in `block in run_chef_client'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/application.rb:279:in `run_chef_client'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/application/base.rb:330:in `run_application'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32/lib/chef/application.rb:69:in `run'
/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/chef-bin-15.7.32/bin/chef-client:25:in `<top (required)>'
/opt/chef-workstation/bin/chef-client:361:in `load'
/opt/chef-workstation/bin/chef-client:361:in `<main>'%

**Comment by zenspider** [comment]
Not reproducible. Verified after talking to @johnmccrae ... closing.
