### ISSUE TITLE
Initial checkout of subversion resources fails when no explicit revision given

### ISSUE THREAD

**Issue by tomhughes** [chef/chef#9373]
## Description

The `subversion` resource fails to perform the `sync` action if there is no existing checkout and no revision is specified or a non-numeric revision that needs resolving is specified.

The problem is that `revision_int` in the provider is called to resolve the revision and it attempts to run `svn info` but [tries to set the current working directory to the checkout while it does](https://github.com/chef/chef/blob/master/lib/chef/provider/subversion.rb#L129) so (which is not necessary as we are interrogating the remote repository) which causes `shell_out!` to error as it can't change to that directory and then we get a report that `svn info` output couldn't be parsed (because there was no output).

## Chef Version

14.14.29 and 15.8.23

## Platform Version

Ubuntu 18.04

## Replication Case

```
chef (14.14.29)> recipe_mode
chef:recipe (14.14.29)> subversion "/tmp/test" do
chef:recipe > action :sync
chef:recipe ?> repository "https://plugins.svn.wordpress.org/wp-fail2ban/tags/4.2.7.1"
chef:recipe ?> end
 => <subversion[/tmp/test] @name: "/tmp/test" @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :sync, :checkout, :export, :diff, :log, :force_export] @action: [:sync] @updated: false @updated_by_last_action: false @source_line: "(irb#1):1:in `irb_binding'" @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @declared_type: :subversion @cookbook_name: nil @recipe_name: nil @repository: "https://plugins.svn.wordpress.org/wp-fail2ban/tags/4.2.7.1"> 
chef:recipe (14.14.29)> run_chef
```

## Client Output

```
2020-02-18T09:50:18+00:00] INFO: Processing subversion[/tmp/test] action sync ((irb#1) line 1)
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout/unix.rb:185:in `chdir': No such file or directory @ dir_s_chdir - /tmp/test (Errno::ENOENT)
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout/unix.rb:185:in `set_cwd'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout/unix.rb:337:in `block in fork_subprocess'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout/unix.rb:318:in `fork'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout/unix.rb:318:in `fork_subprocess'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout/unix.rb:95:in `run_command'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.4/lib/mixlib/shellout.rb:267:in `run_command'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/mixin/shell_out.rb:234:in `shell_out_command'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/mixin/shell_out.rb:200:in `shell_out_compacted!'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/mixin/shell_out.rb:124:in `shell_out!'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/provider/subversion.rb:129:in `revision_int'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/provider/subversion.rb:106:in `checkout_command'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/provider/subversion.rb:61:in `block in action_checkout'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/mixin/why_run.rb:51:in `add_action'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/provider.rb:227:in `converge_by'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/provider/subversion.rb:60:in `action_checkout'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/provider/subversion.rb:94:in `action_sync'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/provider.rb:182:in `run_action'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/resource.rb:578:in `run_action'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/runner.rb:74:in `run_action'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/runner.rb:108:in `block in run_all_actions'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/runner.rb:108:in `each'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/runner.rb:108:in `run_all_actions'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/runner.rb:132:in `block in converge'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/runner.rb:130:in `converge'
	from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/shell/ext.rb:236:in `run_chef'
	from (irb#1):5:in `irb_binding'
	from /opt/chef/embedded/lib/ruby/2.5.0/irb/workspace.rb:85:in `eval'
	from /opt/chef/embedded/lib/ruby/2.5.0/irb/workspace.rb:85:in `evaluate'
	from /opt/chef/embedded/lib/ruby/2.5.0/irb/ext/tracer.rb:65:in `evaluate'
	from /opt/chef/embedded/lib/ruby/2.5.0/irb/context.rb:380:in `evaluate'
	from /opt/chef/embedded/lib/ruby/2.5.0/irb.rb:491:in `block (2 levels) in eval_input'
	from /opt/chef/embedded/lib/ruby/2.5.0/irb.rb:623:in `signal_status'
	from /opt/chef/embedded/lib/ruby/2.5.0/irb.rb:488:in `block in eval_input'
	from /opt/chef/embedded/lib/ruby/2.5.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'
	from /opt/chef/embedded/lib/ruby/2.5.0/irb/ruby-lex.rb:232:in `loop'
	from /opt/chef/embedded/lib/ruby/2.5.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
	from /opt/chef/embedded/lib/ruby/2.5.0/irb/ruby-lex.rb:231:in `catch'
	from /opt/chef/embedded/lib/ruby/2.5.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
	from /opt/chef/embedded/lib/ruby/2.5.0/irb.rb:487:in `eval_input'
	from /opt/chef/embedded/lib/ruby/2.5.0/irb/ext/multi-irb.rb:208:in `block (2 levels) in irb'
	from /opt/chef/embedded/lib/ruby/2.5.0/irb/ext/multi-irb.rb:207:in `catch'
	from /opt/chef/embedded/lib/ruby/2.5.0/irb/ext/multi-irb.rb:207:in `block in irb'

================================================================================
Error executing action `sync` on resource 'subversion[/tmp/test]'
================================================================================

RuntimeError
------------
Could not parse `svn info` data: 

Resource Declaration:
---------------------


Compiled Resource:
------------------
# Declared in (irb#1):1:in `irb_binding'

subversion("/tmp/test") do
  action [:sync]
  default_guard_interpreter :default
  declared_type :subversion
  repository "https://plugins.svn.wordpress.org/wp-fail2ban/tags/4.2.7.1"
  destination "/tmp/test"
end

System Info:
------------
chef_version=14.14.29
platform=ubuntu
platform_version=18.04
ruby=ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux]
program_name=/usr/bin/chef-shell
executable=/opt/chef/embedded/lib/ruby/2.5.0/irb/ext/multi-irb.rb

[2020-02-18T09:50:18+00:00] INFO: Running queued delayed notifications before re-raising exception
Traceback (most recent call last):
       16: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
       15: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/runner.rb:132:in `block in converge'
       14: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/runner.rb:108:in `run_all_actions'
       13: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/runner.rb:108:in `each'
       12: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/runner.rb:108:in `block in run_all_actions'
       11: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/runner.rb:74:in `run_action'
       10: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/resource.rb:578:in `run_action'
        9: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/provider.rb:182:in `run_action'
        8: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/provider/subversion.rb:94:in `action_sync'
        7: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/provider/subversion.rb:60:in `action_checkout'
        6: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/provider.rb:227:in `converge_by'
        5: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/mixin/why_run.rb:51:in `add_action'
        4: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/provider/subversion.rb:61:in `block in action_checkout'
        3: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/provider/subversion.rb:106:in `checkout_command'
        2: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/provider/subversion.rb:131:in `revision_int'
        1: from /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.14.29/lib/chef/provider/subversion.rb:177:in `extract_revision_info'
RuntimeError (subversion[/tmp/test] ((irb#1) line 1) had an error: RuntimeError: Could not parse `svn info` data: )
```

**Comment by tas50** [comment]
While this is a known issue I'm going to close it out at this point and we're not focusing on improvements to the subversion resource due to lack of interest in subversion. If someone in the community would like to take up this work we'd gladly merge the PR, but the Infra team won't be taking on this work.
