### ISSUE TITLE
Fix windows_certificate functional tests under buildkite

### ISSUE THREAD

**Issue by btm** [chef/chef#9435]
## Description

After merging #9427, which allowed tests that were limited to appveyor to run elsewhere, we're seeing failures of the windows_certificate functional tests. For example: 

https://buildkite.com/chef-oss/chef-chef-master-verify/builds/2992#b1201dfd-b461-4ae0-a0ea-a1f5bcec237e/819-8366

```
1) Chef::Resource::WindowsCertificate action :create Again adding the same certificate Idempotent: Does not converge while addition
--
  | Failure/Error: expect(win_certificate).not_to be_updated_by_last_action
  | expected `<windows_certificate[ChefFunctionalTest] @name: "ChefFunctionalTest" @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :create, :acl_add, :delete, :fetch, :verify] @action: [:create] @updated: true @updated_by_last_action: true @source_line: nil @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0.3965711 @store_name: "Chef-Functional-Test" @source: "C:/bkb1201dfd/spec/data/windows_certificates/test.cer">.updated_by_last_action?` to return false, got true
  | # ./spec/functional/resource/windows_certificate_spec.rb:132:in `block (4 levels) in <top (required)>'
```

and

```
8) Chef::Resource::WindowsCertificate action: verify When a certificate is present For a valid thumbprint Displays correct message
--
  | Failure/Error: expect(stdout.string.strip).to eq("Certificate is valid")
  |  
  | expected: "Certificate is valid"
  | got: "Certificate not valid"
  |  
  | (compared using ==)
  | # ./spec/functional/resource/windows_certificate_spec.rb:289:in `block (5 levels) in <top (required)>'
```

Reproduce these failures and correct or replace the tests.

**Comment by tas50** [comment]
These tests have been disabled here temporarily so we can continue to work on other issues and still get builds passing to current:

https://github.com/chef/chef/pull/9459

These are the individual tests that need investigation.
