### ISSUE TITLE
Package resource failing on RHEL 8.1

### ISSUE THREAD

**Issue by donwlewis** [chef/chef#9440]
## Description
Package resource fails after one package resource runs for the first time on RHEL 8.1.

## Chef Version
- 15.4.45
- 15.7.32
- 15.8.23

## Platform Version
RHEL 8.1

## Replication Case
Create a cookbook that has the following resource:

```ruby
package 'git' do
  action :install
end

package 'zip' do
  action :install
end
```

## Client Output
```
         * timezone[UTC] action set
           * dnf_package[tzdata] action install
             
             ================================================================================
             Error executing action `install` on resource 'dnf_package[tzdata]'
             ================================================================================
             
             RuntimeError
             ------------
             dnf-helper.py had stderr output:
             
             Traceback (most recent call last):
        File "/usr/lib/python3.6/site-packages/dnf/repo.py", line 566, in load
          ret = self._repo.load()
        File "/usr/lib64/python3.6/site-packages/libdnf/repo.py", line 503, in load
          return _repo.Repo_load(self)
             RuntimeError: Failed to synchronize cache for repo 'rhel-8-for-x86_64-appstream-rpms'
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
        File "/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.8.23/lib/chef/provider/package/dnf/dnf_helper.py", line 106, in <module>
          query(command)
        File "/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.8.23/lib/chef/provider/package/dnf/dnf_helper.py", line 52, in query
          sack = get_sack()
        File "/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.8.23/lib/chef/provider/package/dnf/dnf_helper.py", line 32, in get_sack
          base.fill_sack(load_system_repo='auto')
        File "/usr/lib/python3.6/site-packages/dnf/base.py", line 400, in fill_sack
          self._add_repo_to_sack(r)
        File "/usr/lib/python3.6/site-packages/dnf/base.py", line 135, in _add_repo_to_sack
          repo.load()
        File "/usr/lib/python3.6/site-packages/dnf/repo.py", line 568, in load
          raise dnf.exceptions.RepoError(str(e))
             dnf.exceptions.RepoError: Failed to synchronize cache for repo 'rhel-8-for-x86_64-appstream-rpms'
             
             Resource Declaration:
             ---------------------
             # In /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.8.23/lib/chef/resource/timezone.rb
             
       39:           package "tzdata" do
       40:             package_name platform_family?("suse") ? "timezone" : "tzdata"
       41:           end
       42:         end
             
             Compiled Resource:
             ------------------
             # Declared in /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.8.23/lib/chef/resource/timezone.rb:39:in `block in <class:Timezone>'
             
             dnf_package("tzdata") do
        package_name "tzdata"
        action [:install]
        default_guard_interpreter :default
        declared_type :package
        cookbook_name "pt_linux"
             end
             
             System Info:
             ------------
             chef_version=15.8.23
             platform=redhat
             platform_version=8.1
             ruby=ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
             program_name=/bin/chef-client
             executable=/opt/chef/bin/chef-client
             
           
           ================================================================================
           Error executing action `set` on resource 'timezone[UTC]'
           ================================================================================
           
           RuntimeError
           ------------
           dnf_package[tzdata] (/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.8.23/lib/chef/resource/timezone.rb line 39) had an error: RuntimeError: dnf-helper.py had stderr output:
           
           Traceback (most recent call last):
             File "/usr/lib/python3.6/site-packages/dnf/repo.py", line 566, in load
        ret = self._repo.load()
             File "/usr/lib64/python3.6/site-packages/libdnf/repo.py", line 503, in load
        return _repo.Repo_load(self)
           RuntimeError: Failed to synchronize cache for repo 'rhel-8-for-x86_64-appstream-rpms'
           
           During handling of the above exception, another exception occurred:
           
           Traceback (most recent call last):
             File "/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.8.23/lib/chef/provider/package/dnf/dnf_helper.py", line 106, in <module>
        query(command)
             File "/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.8.23/lib/chef/provider/package/dnf/dnf_helper.py", line 52, in query
        sack = get_sack()
             File "/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.8.23/lib/chef/provider/package/dnf/dnf_helper.py", line 32, in get_sack
        base.fill_sack(load_system_repo='auto')
             File "/usr/lib/python3.6/site-packages/dnf/base.py", line 400, in fill_sack
        self._add_repo_to_sack(r)
             File "/usr/lib/python3.6/site-packages/dnf/base.py", line 135, in _add_repo_to_sack
        repo.load()
             File "/usr/lib/python3.6/site-packages/dnf/repo.py", line 568, in load
        raise dnf.exceptions.RepoError(str(e))
           dnf.exceptions.RepoError: Failed to synchronize cache for repo 'rhel-8-for-x86_64-appstream-rpms'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/pt_linux/recipes/default.rb
           
            11: timezone 'UTC' do
            12:   timezone 'UTC'
            13:   action :set
            14: end
            15: 
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/pt_linux/recipes/default.rb:11:in `from_file'
           
           timezone("UTC") do
             action [:set]
             default_guard_interpreter :default
             declared_type :timezone
             cookbook_name "pt_linux"
             recipe_name "default"
             timezone "UTC"
           end
           
           System Info:
           ------------
           chef_version=15.8.23
           platform=redhat
           platform_version=8.1
           ruby=ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
           program_name=/bin/chef-client
           executable=/opt/chef/bin/chef-client
           
       
       Running handlers:
       [2020-03-04T02:21:12+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2020-03-04T02:21:12+00:00] ERROR: Exception handlers complete
       Chef Infra Client failed. 2 resources updated in 30 seconds
       [2020-03-04T02:21:12+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2020-03-04T02:21:12+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2020-03-04T02:21:12+00:00] FATAL: RuntimeError: timezone[UTC] (pt_linux::default line 11) had an error: RuntimeError: dnf_package[tzdata] (/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.8.23/lib/chef/resource/timezone.rb line 39) had an error: RuntimeError: dnf-helper.py had stderr output:
       
       Traceback (most recent call last):
         File "/usr/lib/python3.6/site-packages/dnf/repo.py", line 566, in load
           ret = self._repo.load()
         File "/usr/lib64/python3.6/site-packages/libdnf/repo.py", line 503, in load
           return _repo.Repo_load(self)
       RuntimeError: Failed to synchronize cache for repo 'rhel-8-for-x86_64-appstream-rpms'
       
       During handling of the above exception, another exception occurred:
       
       Traceback (most recent call last):
         File "/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.8.23/lib/chef/provider/package/dnf/dnf_helper.py", line 106, in <module>
           query(command)
         File "/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.8.23/lib/chef/provider/package/dnf/dnf_helper.py", line 52, in query
           sack = get_sack()
         File "/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.8.23/lib/chef/provider/package/dnf/dnf_helper.py", line 32, in get_sack
           base.fill_sack(load_system_repo='auto')
         File "/usr/lib/python3.6/site-packages/dnf/base.py", line 400, in fill_sack
           self._add_repo_to_sack(r)
         File "/usr/lib/python3.6/site-packages/dnf/base.py", line 135, in _add_repo_to_sack
           repo.load()
         File "/usr/lib/python3.6/site-packages/dnf/repo.py", line 568, in load
           raise dnf.exceptions.RepoError(str(e))
       dnf.exceptions.RepoError: Failed to synchronize cache for repo 'rhel-8-for-x86_64-appstream-rpms'
```

**Comment by donwlewis** [comment]
Actually investigating this more this seems more like an issue with the `package` resource.  If you have multiple `package` resources in a recipe, the first one kicks off just fine, but the subsequent ones fail with the same error.

**Comment by donwlewis** [comment]
Sorry this is my bad.  Apparently `dnf-utils` went back to being `yum-utils` in RHEL 8.1...sigh...I will close this out.
