### ISSUE TITLE
gem_package fails

### ISSUE THREAD

**Issue by ifasoldt** [chef/chef#9776]
## Description

A few days ago, when our chef instance automatically upgraded to the most recent version of Chef (16.0.257) chef client started breaking when attempting to run the latest cookbooks. It continually fails when trying to use `gem_package` to install `bundler`.

The stacktrace makes it clear that the problem is with the `which` method. It takes only one arg, but `find_gem_by_path` is passing in two: 

```
def find_gem_by_path
  which("gem", extra_path: RbConfig::CONFIG["bindir"])
end
```

If it helps, here's the which method as defined in my chef cache

```
    def which(cmd)
      ENV['PATH'] = '' if ENV['PATH'].nil?
      paths = (ENV['PATH'].split(::File::PATH_SEPARATOR) + %w(/bin /usr/bin /sbin /usr/sbin))

      paths.each do |path|
        possible = File.join(path, cmd)
        return possible if File.executable?(possible)
      end

      nil
    end
```

I tried deleting the chef-client cache, thinking that it might be a cached version of `which` that needed to be rebuilt/cached, but the problem has persisted. 

## Chef Version

`chef_version=16.0.257`
## Platform Version

   ```
    platform=ubuntu
    platform_version=16.04
    ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
    program_name=/usr/bin/chef-client
    executable=/opt/chef/bin/chef-client
   ```

## Replication Case

`gem_package 'bundler'`

## Client Output

```
Recipe: p89-ruby::ruby
  * apt_package[git] action install (up to date)
  * apt_package[nodejs] action install (up to date)
  * gem_package[bundler] action install
    
    ================================================================================
    Error executing action `install` on resource 'gem_package[bundler]'
    ================================================================================
    
    ArgumentError
    -------------
    wrong number of arguments (given 2, expected 1)
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/apt/libraries/helpers.rb:33:in `which'
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/p89-ruby/recipes/ruby.rb
    
     25: gem_package 'bundler'
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/p89-ruby/recipes/ruby.rb:25:in `from_file'
    
    gem_package("bundler") do
      package_name "bundler"
      action [:install]
      default_guard_interpreter :default
      declared_type :gem_package
      cookbook_name "p89-ruby"
      recipe_name "ruby"
    end
    
    System Info:
    ------------
    chef_version=16.0.257
    platform=ubuntu
    platform_version=16.04
    ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
    program_name=/usr/bin/chef-client
    executable=/opt/chef/bin/chef-client
    

Running handlers:
[2020-05-01T16:49:30+00:00] ERROR: Running exception handlers
Running handlers complete
[2020-05-01T16:49:30+00:00] ERROR: Exception handlers complete
Chef Infra Client failed. 1 resources updated in 10 seconds
[2020-05-01T16:49:30+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2020-05-01T16:49:30+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-05-01T16:49:30+00:00] FATAL: ArgumentError: gem_package[bundler] (p89-ruby::ruby line 25) had an error: ArgumentError: wrong number of arguments (given 2, expected 1)
```

## Stacktrace

```
ArgumentError: gem_package[bundler] (p89-ruby::ruby line 25) had an error: ArgumentError: wrong number of arguments (given 2, expected 1)
/var/chef/cache/cookbooks/apt/libraries/helpers.rb:33:in `which'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/provider/package/rubygems.rb:437:in `find_gem_by_path'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/provider/package/rubygems.rb:411:in `initialize'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/resource.rb:1498:in `new'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/resource.rb:1498:in `provider_for_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/resource.rb:591:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/runner.rb:74:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/runner.rb:108:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/runner.rb:132:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/resource_collection/stepable_iterator.rb:115:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/resource_collection/stepable_iterator.rb:86:in `step'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/runner.rb:130:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/client.rb:714:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/client.rb:709:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/client.rb:709:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/client.rb:733:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/client.rb:288:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/application.rb:292:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/application.rb:268:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/application.rb:251:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/application/base.rb:335:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/application.rb:68:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.0.257/bin/chef-client:25:in `<top (required)>'
/usr/bin/chef-client:171:in `load'
/usr/bin/chef-client:171:in `<main>'

>>>> Caused by ArgumentError: wrong number of arguments (given 2, expected 1)
/var/chef/cache/cookbooks/apt/libraries/helpers.rb:33:in `which'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/provider/package/rubygems.rb:437:in `find_gem_by_path'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/provider/package/rubygems.rb:411:in `initialize'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/resource.rb:1498:in `new'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/resource.rb:1498:in `provider_for_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/resource.rb:591:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/runner.rb:74:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/runner.rb:108:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/runner.rb:132:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/resource_collection/stepable_iterator.rb:115:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/resource_collection/stepable_iterator.rb:86:in `step'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/runner.rb:130:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/client.rb:714:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/client.rb:709:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/client.rb:709:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/client.rb:733:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/client.rb:288:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/application.rb:292:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/application.rb:268:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/application.rb:251:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/application/base.rb:335:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/application.rb:68:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.0.257/bin/chef-client:25:in `<top (required)>'
/usr/bin/chef-client:171:in `load'

```

**Comment by lamont-granquist** [comment]
The apt cookbook is injecting a helper into the DSL with a different method signature which breaks the internal which API

What version of the apt cookbook?

**Comment by lamont-granquist** [comment]
NM, it is certainly buggy in the latest:

https://github.com/chef-cookbooks/apt/blob/master/libraries/helpers.rb

Kind of leaning towards this being a breaking change and the cookbooks needing to update.  Need to think about it, but the cookbooks definitely need to update and stop doing that.

**Comment by tas50** [comment]
@ifasoldt I pushed up a new release of the apt cookbook that should fix this up. Try updating that an open this back up if you're still having issues.

**Comment by ifasoldt** [comment]
I'll check today guys. Appreciate the timely response!

**Comment by marc-tt** [comment]
I'm getting the same issue with chef_version=16.0.287


### Chef Version

chef_version=16.0.257


### Platform Version

platform=ubuntu
platform_version=16.04
ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
program_name=/usr/bin/chef-client
executable=/opt/chef/bin/chef-client


### Replication Case

```
gem_package 'backup' do
  options '--no-document'
  version '5.0.0.beta.2'
end
```

### Client output

```
    
    ================================================================================
    Error executing action `install` on resource 'gem_package[backup]'
    ================================================================================
    
    ArgumentError
    -------------
    wrong number of arguments (given 2, expected 1)
    
    Resource Declaration:
    ---------------------
    # In /root/chef/cookbooks/backup-system-ruby/recipes/default.rb
    
     12: gem_package 'backup' do
     13:   options '--no-document'
     14:   version '5.0.0.beta.2'
     15: end
    
    Compiled Resource:
    ------------------
    # Declared in /root/chef/cookbooks/backup-system-ruby/recipes/default.rb:12:in `from_file'
    
    gem_package("backup") do
      package_name "backup"
      action [:install]
      default_guard_interpreter :default
      declared_type :gem_package
      cookbook_name "backup-system-ruby"
      recipe_name "default"
      options "--no-document"
      version "5.0.0.beta.2"
    end
    
    System Info:
    ------------
    chef_version=16.0.287
    platform=ubuntu
    platform_version=20.04
    ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
    program_name=/usr/bin/chef-solo
    executable=/opt/chef/bin/chef-solo
    
[2020-05-12T15:26:57+00:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2020-05-12T15:26:57+00:00] ERROR: Running exception handlers
Running handlers complete
[2020-05-12T15:26:57+00:00] ERROR: Exception handlers complete
Chef Infra Client failed. 0 resources updated in 08 seconds
[2020-05-12T15:26:57+00:00] FATAL: Stacktrace dumped to /root/chef/chef-stacktrace.out
[2020-05-12T15:26:57+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-05-12T15:26:57+00:00] FATAL: ArgumentError: gem_package[backup] (backup-system-ruby::default line 12) had an error: ArgumentError: wrong number of arguments (given 2, expected 1)
```

### Stacktrace

```
ArgumentError: gem_package[backup] (backup-system-ruby::default line 12) had an error: ArgumentError: wrong number of arguments (given 2, expected 1)
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-sugar-5.1.9/lib/chef/sugar/shell.rb:132:in `which'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/provider/package/rubygems.rb:437:in `find_gem_by_path'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/provider/package/rubygems.rb:411:in `initialize'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource.rb:1498:in `new'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource.rb:1498:in `provider_for_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource.rb:591:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/runner.rb:74:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/runner.rb:108:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/runner.rb:132:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource_collection/stepable_iterator.rb:115:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource_collection/stepable_iterator.rb:86:in `step'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/runner.rb:130:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/client.rb:714:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/client.rb:709:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/client.rb:709:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/client.rb:733:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/client.rb:288:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/application.rb:292:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/application.rb:268:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/application.rb:251:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/application/base.rb:335:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/application.rb:68:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/application/solo.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.0.287/bin/chef-solo:24:in `<top (required)>'
/usr/bin/chef-solo:171:in `load'
/usr/bin/chef-solo:171:in `<main>'

>>>> Caused by ArgumentError: wrong number of arguments (given 2, expected 1)
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-sugar-5.1.9/lib/chef/sugar/shell.rb:132:in `which'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/provider/package/rubygems.rb:437:in `find_gem_by_path'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/provider/package/rubygems.rb:411:in `initialize'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource.rb:1498:in `new'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource.rb:1498:in `provider_for_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource.rb:591:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/runner.rb:74:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/runner.rb:108:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/runner.rb:132:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource_collection/stepable_iterator.rb:115:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource_collection/stepable_iterator.rb:86:in `step'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/runner.rb:130:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/client.rb:714:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/client.rb:709:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/client.rb:709:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/client.rb:733:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/client.rb:288:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/application.rb:292:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/application.rb:268:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/application.rb:251:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/application/base.rb:335:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/application.rb:68:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/application/solo.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.0.287/bin/chef-solo:24:in `<top (required)>'
/usr/bin/chef-solo:171:in `load'
/usr/bin/chef-solo:171:in `<main>'
```

**Comment by fletchowns** [comment]
I'm also still seeing this issue, how do we re-open it?
