### ISSUE TITLE
chef-solo or chef-client in local-mode fails on AIX with error FATAL: ThreadError: can't create Thread

### ISSUE THREAD

**Issue by roxyland** [chef/chef#9805]
## Description

`chef-solo` or `chef-client` in local-mode fails on AIX with error 
```
FATAL: ThreadError: can't create Thread:  Resource temporarily unavailable
```

## Chef Version

16.0.275

```
  System Info:
  ------------
  chef_version=16.0.275
  platform=aix
  platform_version=7.2
  ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [powerpc-aix7.1.5.0]
  program_name=/usr/bin/chef-solo
  executable=/opt/chef/bin/chef-solo
```

## Platform Version

AIX 7.2 

## Replication Case

`chef-solo -c solo.rb`
OR 
`chef-client -z -c solo.rb` 

fails with FATAL: ThreadError: can't create Thread: Resource temporarily unavailable.

### solo.rb
```
current_dir     = File.expand_path(File.dirname(__FILE__))
file_cache_path         "#{current_dir}"
cookbook_path           "#{current_dir}/cookbooks"
role_path               "#{current_dir}/roles"
data_bag_path           "#{current_dir}/data_bags"
file_backup_path        "#{current_dir}/backup"
file_cache_path         "#{current_dir}/cache"
role_path               "#{current_dir}/roles"
environment_path        "#{current_dir}/environments"
require 'rubygems'
require 'ohai'
o = Ohai::System.new
o.all_plugins
json_attribs            "#{current_dir}/node_json_files/#{o[:hostname]}.json"
```

## Client Output

```/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:13: warning: already initialized constant Ed25519::KEY_SIZE
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:13: warning: previous definition of KEY_SIZE was here
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:16: warning: already initialized constant Ed25519::SIGNATURE_SIZE
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:16: warning: previous definition of SIGNATURE_SIZE was here
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:19: warning: already initialized constant Ed25519::VerifyError
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:19: warning: previous definition of VerifyError was here
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:22: warning: already initialized constant Ed25519::SelfTestFailure
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:22: warning: previous definition of SelfTestFailure was here
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:13: warning: already initialized constant Ed25519::KEY_SIZE
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:13: warning: previous definition of KEY_SIZE was here
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:16: warning: already initialized constant Ed25519::SIGNATURE_SIZE
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:16: warning: previous definition of SIGNATURE_SIZE was here
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:19: warning: already initialized constant Ed25519::VerifyError
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:19: warning: previous definition of VerifyError was here
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:22: warning: already initialized constant Ed25519::SelfTestFailure
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:22: warning: previous definition of SelfTestFailure was here
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:13: warning: already initialized constant Ed25519::KEY_SIZE
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:13: warning: previous definition of KEY_SIZE was here
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:16: warning: already initialized constant Ed25519::SIGNATURE_SIZE
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:16: warning: previous definition of SIGNATURE_SIZE was here
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:19: warning: already initialized constant Ed25519::VerifyError
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:19: warning: previous definition of VerifyError was here
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:22: warning: already initialized constant Ed25519::SelfTestFailure
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/ed25519-1.2.4/lib/ed25519.rb:22: warning: previous definition of SelfTestFailure was here
Starting Chef Infra Client, version 16.0.275
resolving cookbooks for run list: ["aix_base_rolecookbook"]
Synchronizing Cookbooks:

  ================================================================================
  Error Syncing Cookbooks:
  ================================================================================

  Unexpected Error:
  -----------------
  ThreadError: can't create Thread: Resource temporarily unavailable

  System Info:
  ------------
  chef_version=16.0.275
  platform=aix
  platform_version=7.2
  ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [powerpc-aix7.1.5.0]
  program_name=/usr/bin/chef-solo
  executable=/opt/chef/bin/chef-solo


  Running handlers:
[2020-05-06T20:17:08+10:00] ERROR: Running exception handlers
  Running handlers complete
[2020-05-06T20:17:08+10:00] ERROR: Exception handlers complete
  Chef Infra Client failed. 0 resources updated in 25 seconds
[2020-05-06T20:17:08+10:00] FATAL: Stacktrace dumped to /home/user01/chef-repo/cache/chef-stacktrace.out
[2020-05-06T20:17:08+10:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-05-06T20:17:08+10:00] FATAL: ThreadError: can't create Thread: Resource temporarily unavailable
```

## Stacktrace

```
Generated at 2020-05-06 20:17:08 +1000
ThreadError: can't create Thread: Resource temporarily unavailable
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.275/lib/chef/util/threaded_job_queue.rb:49:in `initialize'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.275/lib/chef/util/threaded_job_queue.rb:49:in `new'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.275/lib/chef/util/threaded_job_queue.rb:49:in `block in process'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.275/lib/chef/util/threaded_job_queue.rb:48:in `each'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.275/lib/chef/util/threaded_job_queue.rb:48:in `map'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.275/lib/chef/util/threaded_job_queue.rb:48:in `process'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.275/lib/chef/cookbook/synchronizer.rb:188:in `sync_cookbooks'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.275/lib/chef/policy_builder/expand_node_object.rb:205:in `sync_cookbooks'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.275/lib/chef/policy_builder/expand_node_object.rb:89:in `setup_run_context'
/opt/chef/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.275/lib/chef/client.rb:498:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.275/lib/chef/client.rb:284:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.275/lib/chef/application.rb:292:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.275/lib/chef/application.rb:268:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.275/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.275/lib/chef/application.rb:251:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.275/lib/chef/application/base.rb:335:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.275/lib/chef/application.rb:68:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.275/lib/chef/application/solo.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.0.275/bin/chef-solo:24:in `<top (required)>'
/usr/bin/chef-solo:169:in `load'
```

**Comment by Firenice03** [comment]
Was this resolved - this error has been occurring since 15.x.x - and looks be reoccurring 16.x.x.

**Comment by Firenice03** [comment]
System Info:
  ------------
  chef_version=15.6.10
  platform=aix
  platform_version=7.2
  ruby=ruby 2.6.5p114 (2019-10-01 revision 67812) [powerpc-aix7.1.5.0]
  program_name=/usr/bin/chef-client
  executable=/opt/chef/bin/chef-client

 FATAL: ThreadError: can't create Thread: Resource temporarily unavailable

Even if limits are updated and rebooted... 
default:
        fsize = -1
        core = 2097151
        cpu = -1
        data = 262144
        rss = -1
        stack = 65536
        nofiles = 50000
