### ISSUE TITLE
Native extension building still broken on RHEL 6

### ISSUE THREAD

**Issue by nhuff** [chef/chef#9831]
## Description
Building native gems is broken on RHEL 6
 
## Chef Version
chef-client 15 and chef-client 16

## Platform Version
RHEL 6.10 and CentOS 6.10

## Replication Case
build_essential 'ruby-augeas'
package 'augeas-devel'
chef_gem 'ruby-augeas'

## Client Output
```
        * chef_gem[ruby-augeas] action install
           
           ================================================================================
           Error executing action `install` on resource 'chef_gem[ruby-augeas]'
           ================================================================================
           
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '1'
           ---- Begin output of /opt/chef/embedded/bin/gem install ruby-augeas -q --no-document -v "0.5.0" --source=https://www.rubygems.org ----
           STDOUT: Building native extensions. This could take a while...
           STDERR: ERROR:  Error installing ruby-augeas:
                ERROR: Failed to build gem native extension.
           
        current directory: /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/ruby-augeas-0.5.0/ext/augeas
           /opt/chef/embedded/bin/ruby -I /opt/chef/embedded/lib/ruby/2.6.0 -r ./siteconf20200508-3455-btgqtk.rb extconf.rb
           *** extconf.rb failed ***
           Could not create Makefile due to some reason, probably lack of necessary
           libraries and/or headers.  Check the mkmf.log file for more details.  You may
           need configuration options.
           
           Provided configuration options:
                --with-opt-dir
                --with-opt-include
                --without-opt-include=${opt-dir}/include
                --with-opt-lib
                --without-opt-lib=${opt-dir}/lib
                --with-make-prog
                --without-make-prog
                --srcdir=.
                --curdir
                --ruby=/opt/chef/embedded/bin/$(RUBY_BASE_NAME)
                --with-augeas-config
                --without-augeas-config
                --with-pkg-config
                --without-pkg-config
           /opt/chef/embedded/lib/ruby/2.6.0/mkmf.rb:478:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
           You have to install development tools first.
                from /opt/chef/embedded/lib/ruby/2.6.0/mkmf.rb:563:in `try_link0'
                from /opt/chef/embedded/lib/ruby/2.6.0/mkmf.rb:581:in `try_link'
                from /opt/chef/embedded/lib/ruby/2.6.0/mkmf.rb:683:in `try_ldflags'
                from /opt/chef/embedded/lib/ruby/2.6.0/mkmf.rb:1843:in `pkg_config'
                from extconf.rb:26:in `<main>'
           
           To see why this extension failed to compile, please check the mkmf.log which can be found here:
           
             /opt/chef/embedded/lib/ruby/gems/2.6.0/extensions/x86_64-linux/2.6.0/ruby-augeas-0.5.0/mkmf.log
```

## mkmf.log
```
"pkg-config --exists augeas"
| pkg-config --libs augeas
=> "-laugeas  \n"
"gcc -o conftest -I/opt/chef/embedded/include/ruby-2.6.0/x86_64-linux -I/opt/chef/embedded/include/ruby-2.6.0/ruby/backward -I/opt/chef/embedded/include/ruby-2.6.0 -I. -I/opt/chef/embedded/include -O2 -D_FORTIFY_SOURCE=2 -fstack-protector -O3 -g -pipe -I/opt/chef/embedded/include   -I/opt/chef/embedded/include -O2 -D_FORTIFY_SOURCE=2 -fstack-protector -O3 -g -pipe -fPIC conftest.c  -L. -L/opt/chef/embedded/lib -Wl,-rpath,/opt/chef/embedded/lib -L/opt/chef/embedded/lib -Wl,-rpath,/opt/chef/embedded/lib -L. -Wl,-rpath,/opt/chef/embedded/lib -L/opt/chef/embedded/lib -fstack-protector -rdynamic -Wl,-export-dynamic -L/opt/chef/embedded/lib  -Wl,-rpath,/opt/chef/embedded/lib     -Wl,-rpath,/opt/chef/embedded/lib -L/opt/chef/embedded/lib -lruby  -lm   -lc"
In file included from /opt/chef/embedded/include/ruby-2.6.0/ruby/ruby.h:29,
                 from /opt/chef/embedded/include/ruby-2.6.0/ruby.h:33,
                 from conftest.c:1:
/opt/chef/embedded/include/ruby-2.6.0/ruby/defines.h:154:23: error: stdalign.h: No such file or directory
In file included from /opt/chef/embedded/include/ruby-2.6.0/ruby.h:33,
                 from conftest.c:1:
/opt/chef/embedded/include/ruby-2.6.0/ruby/ruby.h:1437: error: wrong number of arguments specified for ‘__deprecated__’ attribute
/opt/chef/embedded/include/ruby-2.6.0/ruby/ruby.h:1446: error: wrong number of arguments specified for ‘__deprecated__’ attribute
/opt/chef/embedded/include/ruby-2.6.0/ruby/ruby.h: In function ‘rb_mul_size_overflow’:
/opt/chef/embedded/include/ruby-2.6.0/ruby/ruby.h:1688: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘c2’
/opt/chef/embedded/include/ruby-2.6.0/ruby/ruby.h:1688: error: ‘c2’ undeclared (first use in this function)
/opt/chef/embedded/include/ruby-2.6.0/ruby/ruby.h:1688: error: (Each undeclared identifier is reported only once
/opt/chef/embedded/include/ruby-2.6.0/ruby/ruby.h:1688: error: for each function it appears in.)
/opt/chef/embedded/include/ruby-2.6.0/ruby/ruby.h:1688: error: expected ‘)’ before ‘__int128’
/opt/chef/embedded/include/ruby-2.6.0/ruby/ruby.h:1688: error: expected ‘)’ before ‘__int128’
In file included from /opt/chef/embedded/include/ruby-2.6.0/ruby/ruby.h:2111,
                 from /opt/chef/embedded/include/ruby-2.6.0/ruby.h:33,
                 from conftest.c:1:
/opt/chef/embedded/include/ruby-2.6.0/ruby/intern.h: At top level:
/opt/chef/embedded/include/ruby-2.6.0/ruby/intern.h:192: error: wrong number of arguments specified for ‘__deprecated__’ attribute
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

**Comment by nhuff** [comment]
Pretty sure Issue #9144 was never fully fixed.

**Comment by lamont-granquist** [comment]
Does installing devtoolset-7 and using scl to make it the default compiler fix the issue?

https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/

**Comment by lamont-granquist** [comment]
Ruby 2.7 has now dropped support for the RHEL6 default compiler, so our build systems all had to be updated, so this likely won't get fixed short of having build_essentials upgrade RHEL6 to a later compiler.

(Unless its determined that something else is going on, but if its compiler versioning then the default RHEL6 compiler probably isn't ever coming back)

**Comment by nhuff** [comment]
Running `scl enable devtoolset-7 -- /opt/chef/embedded/bin/gem install ruby-augeas` does seem to successfully build the native extensions.  Not sure what the correct thing to do going forward for RHEL/Centos 6 is.  I am probably just going to stick with version 14 since we are phasing out our RHEL 6 systems anyway as they are going to be out of normal support soon.  Maybe just document the issue and workaround.

**Comment by tas50** [comment]
@nhuff We have this listed as a breaking change in Chef Infra Client 16 with the workaround here: https://docs.chef.io/release_notes/#red-hat--centos-6-systems-require-c11-gcc-for-some-gem-installations

**Comment by tas50** [comment]
I'm going to close this one out since there isn't really a fix other than upgrading GCC on the host or upgrading off RHEL 6.
