### ISSUE TITLE
windows_package never executes the installer

### ISSUE THREAD

**Issue by mginster** [chef/chef#9884]
# Description
windows_package resource has stopped functioning with 16.1

## Chef Version
16.1.0
Note: This exact resource below works in 14.12.9.

## Platform Version
Windows 10

## Replication Case
Run a windows_package resource. Ex:

```
windows_package 'Microsoft Visual C++ 2005 Redistributable (x64)' do
  source path_to_source/vcredist_x64.exe
  options '/q'
  remote_file_attributes path: "#{Chef::Config[:file_cache_path]}/vcredist_2005_x64.exe"
  returns [0, 3010]
  installer_type :custom
  action :install
  only_if { feature_flag('vcredist_2005_x64') }
end
```

## Stacktrace

```
Generated at 2020-05-18 20:23:38 -0700
Mixlib::ShellOut::CommandTimeout: windows_package[Microsoft Visual C++ 2005 Redistributable (x64)] (ncr_aloha_foundation::cpp_redist line 21) had an error: Mixlib::ShellOut::CommandTimeout: command timed out:
---- Begin output of start "" /wait "c:\users\vagrant\appdata\local\temp\kitchen\cache\package\vcredist_x64.exe"   /q & exit %%%%ERRORLEVEL%%%% ----
STDOUT: 
STDERR: 
---- End output of start "" /wait "c:\users\vagrant\appdata\local\temp\kitchen\cache\package\vcredist_x64.exe"   /q & exit %%%%ERRORLEVEL%%%% ----

ProcessId: 3704
app_name: C:\Windows\system32\cmd.exe
command_line: cmd /c "start "" /wait "c:\users\vagrant\appdata\local\temp\kitchen\cache\package\vcredist_x64.exe"   /q & exit %%%%ERRORLEVEL%%%%"
timeout: 600
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.0.9-universal-mingw32/lib/mixlib/shellout/windows.rb:130:in `block in run_command'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.0.9-universal-mingw32/lib/mixlib/shellout/windows.rb:104:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.0.9-universal-mingw32/lib/mixlib/shellout/windows.rb:104:in `run_command'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.0.9-universal-mingw32/lib/mixlib/shellout.rb:270:in `run_command'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/mixin/shell_out.rb:166:in `shell_out_command'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/mixin/shell_out.rb:125:in `shell_out_compacted!'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/mixin/shell_out.rb:60:in `shell_out!'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/provider/package/windows/exe.rb:58:in `install_package'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/provider/package/windows.rb:140:in `install_package'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/provider/package.rb:95:in `block (3 levels) in <class:Package>'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/provider/package.rb:244:in `multipackage_api_adapter'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/provider/package.rb:94:in `block (2 levels) in <class:Package>'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/mixin/why_run.rb:51:in `add_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/provider.rb:268:in `converge_by'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/provider/package.rb:93:in `block in <class:Package>'
(eval):2:in `block in action_install'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/provider.rb:279:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/provider.rb:279:in `compile_and_converge_action'
(eval):2:in `action_install'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/provider.rb:220:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/resource.rb:591:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/runner.rb:74:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/runner.rb:108:in `block in run_all_actions'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/runner.rb:108:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/runner.rb:108:in `run_all_actions'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/runner.rb:132:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:115:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:86:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/2.7.0/forwardable.rb:235:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/runner.rb:130:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/client.rb:714:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/client.rb:709:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/client.rb:709:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/client.rb:733:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/client.rb:288:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/application.rb:292:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/application.rb:268:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/local_mode.rb:42:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/application.rb:251:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/application/base.rb:335:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.0-universal-mingw32/lib/chef/application.rb:68:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.1.0/bin/chef-client:25:in `<top (required)>'
C:/opscode/chef/bin/chef-client:184:in `load'
C:/opscode/chef/bin/chef-client:184:in `<main>'
```

**Comment by snehaldwivedi** [comment]
Hi @mginster,

I have tried to replicate the issue on the latest chef version `17` and mentioned version `16.1.0` and its working fine as below 

```
Chef Infra Client version: 17.0.242

PS C:\Users\Administrator\first_cookbook> chef-apply .\recipes\default.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * windows_package[7zip] action install
    * remote_file[C:\chef\cache\package\7z938-x64.msi] action create (up to date)
    - install version 9.38.00.0 of package 7zip
```


```
Chef Infra Client version: 16.1.0

PS C:\Users\Administrator\first_cookbook> chef-apply .\recipes\default.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * windows_package[7zip] action install
    * remote_file[C:\chef\cache\package\7z938-x64.msi] action create (up to date)
    - install version 9.38.00.0 of package 7zip
```

Please try upgrading to the latest version and if you are still facing issue please let us know some more details.

**Comment by snehaldwivedi** [comment]
@mginster Closing this card for now as there is no update from you. Please reopen it again if you still face the issue.
