### ISSUE TITLE
zypper_repository not working with latest bento opensuse-15 image

### ISSUE THREAD

**Issue by Xorima** [chef/chef#9947]
## Description
`zypper_repository` is failing due to a gpg error

## Chef Version
Tested with 16 latest and 15 latest

## Platform Version
opensuse-15 bento box 

## Replication Case
```
zypper_repository "nginx" do
  description 'Nginx.org repository'
  baseurl "https://nginx.org/packages/sles/12"
  gpgkey "https://nginx.org/keys/nginx_signing.key"
end
```
or run the `repo-opensuse-15` from the https://github.com/sous-chefs/nginx cookbook

## Client Output
```
* zypper_repository[nginx] action create**** Cached keyfile is: /tmp/kitchen/cache/nginx_signing.key
       
             * remote_file[/tmp/kitchen/cache/nginx_signing.key] action create (up to date)
             * execute[import gpg key from https://nginx.org/keys/nginx_signing.key] action run
        
        ================================================================================
        Error executing action `run` on resource 'execute[import gpg key from https://nginx.org/keys/nginx_signing.key]'
        ================================================================================
        
        NoMethodError
        -------------
        undefined method `[]' for nil:NilClass
        
        Resource Declaration:
        ---------------------
        # In /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/provider/zypper_repository.rb
        
        160:         declare_resource(:execute, "import gpg key from #{new_resource.gpgkey}") do
        161:           command "/bin/rpm --import #{cached_keyfile}"
        162:           not_if { key_installed?(cached_keyfile) }
        163:           action :run
        164:         end
        165:       end
        
        Compiled Resource:
        ------------------
        # Declared in /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/provider/zypper_repository.rb:160:in `install_gpg_key'
        
        execute("import gpg key from https://nginx.org/keys/nginx_signing.key") do
          action [:run]
          default_guard_interpreter :execute
          command "/bin/rpm --import /tmp/kitchen/cache/nginx_signing.key"
          backup 5
          declared_type :execute
          cookbook_name "test"
          domain nil
          user nil
          not_if { #code block }
        end
        
        System Info:
        ------------
        chef_version=15.11.8
        platform=opensuseleap
        platform_version=15.1
        ruby=ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]
        program_name=/opt/chef/bin/chef-client
        executable=/opt/chef/bin/chef-client
        
```
## Stacktrace
```
Generated at 2020-06-02 15:21:34 +0000
NoMethodError: nginx_install[repo] (test::repo line 3) had an error: NoMethodError: zypper_repository[nginx] (/tmp/kitchen/cache/cookbooks/nginx/resources/install.rb line 192) had an error: NoMethodError: execute[import gpg key from https://nginx.org/keys/nginx_signing.key] (/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/provider/zypper_repository.rb line 160) had an error: NoMethodError: undefined method `[]' for nil:NilClass
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/provider/zypper_repository.rb:137:in `key_fingerprint'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/provider/zypper_repository.rb:125:in `key_installed?'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/resource.rb:1334:in `method_missing'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/provider/zypper_repository.rb:162:in `block (2 levels) in install_gpg_key'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/resource/conditional.rb:106:in `evaluate_block'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/resource/conditional.rb:95:in `evaluate'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/resource/conditional.rb:88:in `continue?'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/resource.rb:1547:in `block in should_skip?'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/resource.rb:1546:in `each'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/resource.rb:1546:in `find'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/resource.rb:1546:in `should_skip?'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/resource.rb:584:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/runner.rb:74:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/runner.rb:108:in `block in run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/runner.rb:108:in `each'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/runner.rb:108:in `run_all_actions'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/runner.rb:132:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/resource_collection/resource_list.rb:96:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/resource_collection/stepable_iterator.rb:115:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/resource_collection/stepable_iterator.rb:86:in `step'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/resource_collection/resource_list.rb:94:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/2.6.0/forwardable.rb:230:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/runner.rb:130:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.11.8/lib/chef/provider.rb:246:in `compile_and_converge_action'
(eval):2:in `action_create'
```

**Comment by tas50** [comment]
It looks like gpg 2.2 which shipped in opensuse 15.x and sles 15.x changed the output we relied on to get the fingerprint of the current key. We're going to have to find a command that works in gpg 2.2 or stop relying on shellout to gpg here.

**Comment by tas50** [comment]
The fix for this is in master and will go out in 16.2. Thanks for the report @Xorima
