### ISSUE TITLE
sudo resource ValidationFailed Chef Infra Client 16.0.287

### ISSUE THREAD

**Issue by dheerajd-msys** [chef/chef#9990]
## Description

Executing a client run with a simple sudo resource definition fails on Chef Infra Client 16.0.287
## Chef Version

Chef Infra Client 16.0.287
## Platform Version

This was tried  on CentOS Linux release 7.6.1810 (Core)
## Replication Case

Test with a resource definition like:
```
sudo '20_test' do
    groups 'testuser'
    commands ['ls', 'pwd']
    nopasswd true
end

```
## Client Output

```
================================================================================
      Error executing action `create` on resource 'template[/etc/sudoers.d/20_test]'
      ================================================================================

      Chef::Exceptions::ValidationFailed
      ----------------------------------
      Proposed content for /etc/sudoers.d/20_test failed verification cat /etc/sudoers %{path} | /usr/sbin/visudo -cf -
      STDOUT: parse error in stdin near line 123

      STDERR: >>> stdin: syntax error near line 123 <<<
      >>> stdin: syntax error near line 124 <<<


      Temporary file moved to /root/.chef/local-mode-cache/cache/failed_validations/.chef-20_test20200514-4997-1yf32tu

      Resource Declaration:
      ---------------------
      # In /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource/sudo.rb

      174:           template file_path do
      175:             source ::File.expand_path("../support/sudoer.erb", __FILE__)
      176:             local true
      177:             mode "0440"
      178:             variables sudoer:            (new_resource.groups + new_resource.users).join(","),
      179:                       host:               new_resource.host,
      180:                       runas:              new_resource.runas,
      181:                       nopasswd:           new_resource.nopasswd,
      182:                       noexec:             new_resource.noexec,
      183:                       commands:           new_resource.commands,
      184:                       command_aliases:    new_resource.command_aliases,
      185:                       defaults:           new_resource.defaults,
      186:                       setenv:             new_resource.setenv,
      187:                       env_keep_add:       new_resource.env_keep_add,
      188:                       env_keep_subtract:  new_resource.env_keep_subtract
      189:             verify visudo_content(file_path) if visudo_present?
      190:             action :create
      191:           end
      192:         end

      Compiled Resource:
      ------------------
      # Declared in /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource/sudo.rb:174:in `block in <class:Sudo>'

      template("/etc/sudoers.d/20_test") do
        action [:create]
        default_guard_interpreter :default
        source "/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource/support/sudoer.erb"
        declared_type :template
        cookbook_name "test_sudo"
        local true
        mode "0440"
        variables {:sudoer=>"%testuser", :host=>"ALL", :runas=>"ALL", :nopasswd=>true, :noexec=>false, :commands=>["ls", "pwd"], :command_aliases=>[], :defaults=>[], :setenv=>false, :env_keep_add=>[], :env_keep_subtract=>[]}
        verifications [#<Chef::Resource::File::Verification:0x0000000001fdb168 @command_opts={}, @command="cat /etc/sudoers %{path} | /usr/sbin/visudo -cf -", @block=nil, @parent_resource=<template[/etc/sudoers.d/20_test] @name: "/etc/sudoers.d/20_test" @before: nil @params: nil @provider: nil @allowed_actions: [:nothing, :create, :delete, :touch, :create_if_missing] @action: [:create] @updated: false @updated_by_last_action: false @source_line: "/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource/sudo.rb:174:in `block in <class:Sudo>'" @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @source: "/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource/support/sudoer.erb" @inline_helper_blocks: {} @inline_helper_modules: [] @helper_modules: [] @declared_type: :template @cookbook_name: "test_sudo" @recipe_name: nil @local: true @mode: "0440" @variables: {:sudoer=>"%testuser", :host=>"ALL", :runas=>"ALL", :nopasswd=>true, :noexec=>false, :commands=>["ls", "pwd"], :command_aliases=>[], :defaults=>[], :setenv=>false, :env_keep_add=>[], :env_keep_subtract=>[]} @verifications: [...] @path: "/etc/sudoers.d/20_test" @owner: nil @group: nil>, @output="STDOUT: parse error in stdin near line 123\n\nSTDERR: >>> stdin: syntax error near line 123 <<<\n>>> stdin: syntax error near line 124 <<<\n\n">]
        path "/etc/sudoers.d/20_test"
        owner nil
        group nil
      end

      System Info:
      ------------
      chef_version=16.0.287
      platform=centos
      platform_version=7.6.1810
      ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
      program_name=/bin/chef-client
      executable=/opt/chef/bin/chef-client


    ================================================================================
    Error executing action `create` on resource 'sudo[20_test]'
    ================================================================================

    Chef::Exceptions::ValidationFailed
    ----------------------------------
    template[/etc/sudoers.d/20_test] (/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource/sudo.rb line 174) had an error: Chef::Exceptions::ValidationFailed: Proposed content for /etc/sudoers.d/20_test failed verification cat /etc/sudoers %{path} | /usr/sbin/visudo -cf -
    STDOUT: parse error in stdin near line 123

    STDERR: >>> stdin: syntax error near line 123 <<<
    >>> stdin: syntax error near line 124 <<<


    Temporary file moved to /root/.chef/local-mode-cache/cache/failed_validations/.chef-20_test20200514-4997-1yf32tu

    Resource Declaration:
    ---------------------
    # In /root/.chef/local-mode-cache/cache/cookbooks/test_sudo/recipes/default.rb

      7: sudo '20_test' do
      8:     groups 'testuser'
      9:     commands ['ls', 'pwd']
     10:     nopasswd true
     11: end

    Compiled Resource:
    ------------------
    # Declared in /root/.chef/local-mode-cache/cache/cookbooks/test_sudo/recipes/default.rb:7:in `from_file'

    sudo("20_test") do
      action [:create]
      default_guard_interpreter :default
      declared_type :sudo
      cookbook_name "test_sudo"
      recipe_name "default"
      groups ["%testuser"]
      commands ["ls", "pwd"]
      nopasswd true
      users []
      config_prefix "/etc"
      filename "20_test"
      command_aliases []
      defaults []
      env_keep_add []
      env_keep_subtract []
    end

    System Info:
    ------------
    chef_version=16.0.287
    platform=centos
    platform_version=7.6.1810
    ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
    program_name=/bin/chef-client
    executable=/opt/chef/bin/chef-client


Running handlers:
[2020-05-14T08:57:57+00:00] ERROR: Running exception handlers
Running handlers complete
[2020-05-14T08:57:57+00:00] ERROR: Exception handlers complete
Chef Infra Client failed. 0 resources updated in 03 seconds
[2020-05-14T08:57:57+00:00] FATAL: Stacktrace dumped to /root/.chef/local-mode-cache/cache/chef-stacktrace.out
[2020-05-14T08:57:57+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-05-14T08:57:57+00:00] FATAL: Chef::Exceptions::ValidationFailed: sudo[20_test] (test_sudo::default line 7) had an error: Chef::Exceptions::ValidationFailed: template[/etc/sudoers.d/20_test] (/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.287/lib/chef/resource/sudo.rb line 174) had an error: Chef::Exceptions::ValidationFailed: Proposed content for /etc/sudoers.d/20_test failed verification cat /etc/sudoers %{path} | /usr/sbin/visudo -cf -
STDOUT: parse error in stdin near line 123

STDERR: >>> stdin: syntax error near line 123 <<<
>>> stdin: syntax error near line 124 <<<


Temporary file moved to /root/.chef/local-mode-cache/cache/failed_validations/.chef-20_test20200514-4997-1yf32tu

```
## Expected Behaviour
A successful run that produces a drop-in `/etc/sudoers.d` configuration

**Comment by antima-gupta** [comment]
This issue is occurring because of `commands` property value.Please check `commands` property description in [sudo cookbook doc](https://supermarket.chef.io/cookbooks/sudo) under properties section.It must contain a full path to command for example: `commands ['/bin/ls', '/bin/pwd']`.

## Recipe:
```
sudo '20_test' do
  groups 'testuser1'
  commands ['/bin/ls', '/bin/pwd']
  nopasswd true
end
```
## Command: 
sudo chef-client --local-mode --override-runlist test_cookbook

## Log:

[2020-06-17T14:28:56+05:30] INFO: Started Chef Infra Zero at chefzero://localhost:1 with repository at /home/antima/workspace/learn-chef (One version per cookbook)
Starting Chef Infra Client, version 16.1.16
[2020-06-17T14:28:56+05:30] INFO: *** Chef Infra Client 16.1.16 ***
[2020-06-17T14:28:56+05:30] INFO: Platform: x86_64-linux
[2020-06-17T14:28:56+05:30] INFO: Chef-client pid: 20485
[2020-06-17T14:30:05+05:30] WARN: Run List override has been provided.
[2020-06-17T14:30:05+05:30] WARN: Original Run List: []
[2020-06-17T14:30:05+05:30] WARN: Overridden Run List: [recipe[test_cookbook]]
[2020-06-17T14:30:05+05:30] INFO: Run List is [recipe[test_cookbook]]
[2020-06-17T14:30:05+05:30] INFO: Run List expands to [test_cookbook]
[2020-06-17T14:30:05+05:30] INFO: Starting Chef Infra Client Run for antimagupta
[2020-06-17T14:30:05+05:30] INFO: Running start handlers
[2020-06-17T14:30:05+05:30] INFO: Start handlers complete.
resolving cookbooks for run list: ["test_cookbook"]
[2020-06-17T14:30:07+05:30] INFO: Loading cookbooks [test_cookbook@0.2.0]
[2020-06-17T14:30:07+05:30] INFO: Skipping removal of obsoleted cookbooks from the cache
Synchronizing Cookbooks:
[2020-06-17T14:30:07+05:30] INFO: Storing updated cookbooks/test_cookbook/recipes/default.rb in the cache.
  - test_cookbook (0.2.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: test_cookbook::default
  * sudo[20_test] action create[2020-06-17T14:30:08+05:30] INFO: Processing sudo[20_test] action create (test_cookbook::default line 14)

    * directory[/etc/sudoers.d/] action create[2020-06-17T14:30:08+05:30] INFO: Processing directory[/etc/sudoers.d/] action create (/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/resource/sudo.rb line 158)
 (up to date)
    * template[/etc/sudoers.d/20_test] action create[2020-06-17T14:30:08+05:30] INFO: Processing template[/etc/sudoers.d/20_test] action create (/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-16.1.16/lib/chef/resource/sudo.rb line 174)
[2020-06-17T14:30:09+05:30] INFO: template[/etc/sudoers.d/20_test] created file /etc/sudoers.d/20_test

      - create new file /etc/sudoers.d/20_test[2020-06-17T14:30:09+05:30] INFO: template[/etc/sudoers.d/20_test] updated file contents /etc/sudoers.d/20_test

      - update content in file /etc/sudoers.d/20_test from none to 45752f
      --- /etc/sudoers.d/20_test	2020-06-17 14:30:09.013716520 +0530
      +++ /etc/sudoers.d/.chef-20_test20200617-20485-47jpo6	2020-06-17 14:30:08.793718058 +0530
      @@ -1 +1,5 @@
      +# This file is managed by Chef Infra Client. Changes will be overwritten.
      +
      +%testuser1 ALL=(ALL) NOPASSWD:/bin/ls
      +%testuser1 ALL=(ALL) NOPASSWD:/bin/pwd[2020-06-17T14:30:09+05:30] INFO: template[/etc/sudoers.d/20_test] mode changed to 440

      - change mode from '' to '0440'
  
[2020-06-17T14:30:09+05:30] WARN: Skipping final node save because override_runlist was given
[2020-06-17T14:30:09+05:30] INFO: Chef Infra Client Run complete in 4.107963552 seconds
[2020-06-17T14:30:09+05:30] INFO: Skipping removal of unused files from the cache

Running handlers:
[2020-06-17T14:30:09+05:30] INFO: Running report handlers
Running handlers complete
[2020-06-17T14:30:09+05:30] INFO: Report handlers complete
Chef Infra Client finished, 2/3 resources updated in 01 minutes 12 seconds

**Comment by dheerajd-msys** [comment]
Closing out this issue since this is working perfect with above information, as we were getting reported by customer.
